Repository web-infra-dev/rspack, pull requests merged in 2023-05, with the labels that each got.

#2998 refactor(core): use directory for chunk_graph module
  crates/rspack_core/src/chunk_graph/mod.rs
Labels: team

#2997 chore: add node shims example
  examples/node-globals-shim/index.html
  examples/node-globals-shim/package.json
  examples/node-globals-shim/rspack.config.js
  examples/node-globals-shim/src/answer.js
  examples/node-globals-shim/src/index.js
  examples/node-globals-shim/src/process-shim.js
  examples/node-globals-shim/src/util.js
  pnpm-lock.yaml
Labels: team

#2996 test(split_chunks): add test of extract-css-to-single-chunk
  packages/rspack/tests/configCases/split-chunks/css-simple/foo.css
  packages/rspack/tests/configCases/split-chunks/css-simple/foo.js
  packages/rspack/tests/configCases/split-chunks/css-simple/index.css
  packages/rspack/tests/configCases/split-chunks/css-simple/index.js
  packages/rspack/tests/configCases/split-chunks/css-simple/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/foo.css
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/foo.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/index.css
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/index.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/shims.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/webpack.config.js
Labels: team

#2967 chore: remove clap
  Cargo.lock
  Cargo.toml
  crates/cargo-rst/Cargo.toml
  crates/cargo-rst/src/lib.rs
  crates/cargo-rst/src/main.rs
  crates/cargo-rst/tests/main.rs
  crates/rspack_ast_viewer/Cargo.toml
  crates/rspack_ast_viewer/src/main.rs
Labels: team

#2980 feat(x.mjs): add `x clean` command
  package.json
  x.mjs
Labels: team, release: feature

#3000 feat(new_split_chunks): support `reuseExistingChunk`
  .changeset/strange-pans-raise.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/module_group.rs
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/tests/configCases/split-chunks/disable-reuse-existing-chunk-simple/foo-2.js
  packages/rspack/tests/configCases/split-chunks/disable-reuse-existing-chunk-simple/foo.js
  packages/rspack/tests/configCases/split-chunks/disable-reuse-existing-chunk-simple/index.js
  packages/rspack/tests/configCases/split-chunks/disable-reuse-existing-chunk-simple/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/reuse-existing-chunk-simple/foo-2.js
  packages/rspack/tests/configCases/split-chunks/reuse-existing-chunk-simple/foo.js
  packages/rspack/tests/configCases/split-chunks/reuse-existing-chunk-simple/index.js
  packages/rspack/tests/configCases/split-chunks/reuse-existing-chunk-simple/webpack.config.js
Labels: team, release: feature

#3006 fix: entry startup for target node
  .changeset/lovely-onions-perform.md
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/mod.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/start_entry_point.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/start_entry_point_with_async.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_chunk_dependencies.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_chunk_dependencies_with_async.js
  crates/rspack_plugin_runtime/src/runtime_module/startup_chunk_dependencies.rs
  crates/rspack_plugin_runtime/src/runtime_module/startup_entry_point.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/shims.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/webpack.config.js
Labels: team, release: bug fix

#2999 chore: add add loader_name to loader_sync_call in trace
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
Labels: team

#2987 feat(rspack): add ignoreWarnings option
  .changeset/olive-lobsters-tie.md
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/lib/ignoreWarningsPlugin.ts
  packages/rspack/src/rspack.ts
  packages/rspack/tests/Defaults.unittest.ts
Labels: p3-nice-to-have, release: feature

#3002 chore: fine grained tracing
  crates/bench/src/main.rs
  crates/rspack_tracing/src/lib.rs
Labels: team

#3004 chore: make release profile the same for Cargo.toml and node_binding/Cargo.toml
  Cargo.toml
  crates/node_binding/Cargo.toml
Labels: team

#3008 chore: 🤖 bump napi cli
  .changeset/friendly-zebras-hope.md
  crates/node_binding/binding.d.ts
  crates/node_binding/package.json
  crates/node_binding/scripts/build.js
  pnpm-lock.yaml
Labels: team

#3013 chore: 🤖 recover check on save
  .vscode/settings.json
Labels: team

#3001 fix: circular dependencies rebuild panic
  .changeset/cuddly-fans-glow.md
  crates/rspack_core/src/compiler/hmr.rs
  packages/rspack/tests/hotCases/runtime/hmr-circular/a.js
  packages/rspack/tests/hotCases/runtime/hmr-circular/b.js
  packages/rspack/tests/hotCases/runtime/hmr-circular/changed-file.js
  packages/rspack/tests/hotCases/runtime/hmr-circular/entry.js
  packages/rspack/tests/hotCases/runtime/hmr-circular/index.js
Labels: team, release: bug fix

#3014 fix(core): fix require(`./xxx/xx.js`) failed
  crates/rspack_plugin_javascript/src/dependency/commonjs/require.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  packages/rspack/tests/cases/context/issue-3014/answer.js
  packages/rspack/tests/cases/context/issue-3014/index.js
Labels: team, release: bug fix

#3015 feat(new_split_chunks): support `splitChunks.{cacheGroup}.minSize`
  .changeset/witty-months-look.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/split-chunks-common/move-entry/a.js
  packages/rspack/tests/configCases/split-chunks-common/move-entry/index.js
  packages/rspack/tests/configCases/split-chunks-common/move-entry/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/move-entry/webpack.config.js
Labels: team, release: feature

#3021 chore(rust): bump sass-embedded and remove protobuf requirement
  .github/workflows/bench-history.yaml
  .github/workflows/bench.yaml
  .github/workflows/bundle-stats.yaml.bak
  .github/workflows/check-js.yaml.bak
  .github/workflows/check-rs.yaml
  .github/workflows/release-canary.yml
  .github/workflows/reusable-build.yml
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_loader_sass/src/lib.rs
Labels: team

#3020 chore: link to rspack-dev-guide and make content more general in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: team

#3017 feat: support inline match resource
  .changeset/tender-poets-look.md
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/utils/identifier.rs
  packages/rspack/tests/configCases/loader/issue-webpack-9053/.gitignore
  packages/rspack/tests/configCases/loader/issue-webpack-9053/b.js
  packages/rspack/tests/configCases/loader/issue-webpack-9053/c.js
  packages/rspack/tests/configCases/loader/issue-webpack-9053/index.js
  packages/rspack/tests/configCases/loader/issue-webpack-9053/node_modules/loader1.js
  packages/rspack/tests/configCases/loader/issue-webpack-9053/node_modules/loader2.js
  packages/rspack/tests/configCases/loader/issue-webpack-9053/node_modules/loader3.js
  packages/rspack/tests/configCases/loader/issue-webpack-9053/webpack.config.js
Labels: team, release: feature

#2955 feat(new_split_chunks): support `splitChunks.name`
  .changeset/fair-rivers-tickle.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/split-chunks-common/simple/a.js
  packages/rspack/tests/configCases/split-chunks-common/simple/index.js
  packages/rspack/tests/configCases/split-chunks-common/simple/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/simple/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/index.js
  packages/rspack/tests/configCases/split-chunks/split-chunks-dot-name/foo-2.js
  packages/rspack/tests/configCases/split-chunks/split-chunks-dot-name/foo.js
  packages/rspack/tests/configCases/split-chunks/split-chunks-dot-name/index.js
  packages/rspack/tests/configCases/split-chunks/split-chunks-dot-name/webpack.config.js
Labels: team, release: feature

#3023 refactor: external module for http request
  .changeset/yellow-days-yawn.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  crates/rspack_plugin_css/tests/fixtures/custom/http_import/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/expected/main.css
  crates/rspack_plugin_externals/src/http_external_plugin.rs
  crates/rspack_plugin_externals/src/lib.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/externals/array-externals/webpack.config.js
  packages/rspack/tests/configCases/externals/custom-url/index.css
  packages/rspack/tests/configCases/externals/custom-url/index.js
  packages/rspack/tests/configCases/externals/custom-url/webpack.config.js
Labels: team

#3016 fix(core): compatible with stats.version
  crates/rspack/tests/tree-shaking/with-assets/expected/main.js
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_asset/tests/fixtures/rspack/asset-source/expected/main.js
  crates/rspack_plugin_asset/tests/fixtures/webpack/asset-advanced/expected/main.js
  crates/rspack_plugin_asset/tests/fixtures/webpack/asset-simple/expected/main.js
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/main.js
  packages/rspack/package.json
  packages/rspack/src/compiler.ts
  packages/rspack/src/multiStats.ts
  packages/rspack/src/stats.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: bug fix

#2446 feat: simple normal module hook
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/normalModule.ts
  packages/rspack/src/util/scheme.ts
  packages/rspack/src/util/webpack.ts
Labels: team, release: feature

#3024 refactor: remove dependency parent module identifier
  .changeset/dry-dingos-study.md
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/common_js_require_context_dependency.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/dynamic_import.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/import_context_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/require_context_dependency.rs
  crates/rspack_core/src/dependency/require_resolve_dependency.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_core/src/dependency/static_exports_dependency.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require.rs
  crates/rspack_plugin_javascript/src/dependency/esm/export.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_wasm/src/dependency.rs
Labels: team

#3031 refactor(chunk_graph): split methods of `ChunkGraph` into different files
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/chunk_graph/mod.rs
Labels: team, ready to merge

#3029 feat: allow to pass `false` to `splitChunks.name` and `splitChunks.{cacheGroup}.name`
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
Labels: team, release: feature

#3033 perf(split_chunks): use `intersection` instead of `union`
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
Labels: team, release: performance

#3032 chore: 🤖 add alias cargo test no fail fast
  .cargo/config.toml
Labels: team

#3018 test(split_chunks): Migrate `test/configCases/split-chunks-common` of Webpack
  packages/rspack/tests/configCases/split-chunks-common/_hot-multi/common.js
  packages/rspack/tests/configCases/split-chunks-common/_hot-multi/first.js
  packages/rspack/tests/configCases/split-chunks-common/_hot-multi/second.js
  packages/rspack/tests/configCases/split-chunks-common/_hot-multi/shared.js
  packages/rspack/tests/configCases/split-chunks-common/_hot-multi/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/_hot-multi/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/_hot/index.js
  packages/rspack/tests/configCases/split-chunks-common/_hot/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/_hot/vendor.js
  packages/rspack/tests/configCases/split-chunks-common/_hot/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/_library/a.js
  packages/rspack/tests/configCases/split-chunks-common/_library/index.js
  packages/rspack/tests/configCases/split-chunks-common/_library/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/_library/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/_target-node/index.js
  packages/rspack/tests/configCases/split-chunks-common/_target-node/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/_target-node/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/correct-order/a.js
  packages/rspack/tests/configCases/split-chunks-common/correct-order/index.js
  packages/rspack/tests/configCases/split-chunks-common/correct-order/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/correct-order/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/extract-async-from-entry/index.js
  packages/rspack/tests/configCases/split-chunks-common/extract-async-from-entry/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/extract-async-from-entry/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/inverted-order/a.js
  packages/rspack/tests/configCases/split-chunks-common/inverted-order/index.js
  packages/rspack/tests/configCases/split-chunks-common/inverted-order/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/inverted-order/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/a.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/b.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/index.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/index2.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/index.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/pageA.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/pageB.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/pageC.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/reusableComponent.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/second.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/webpack.config.js
Labels: team

#3005 feat(rust): add output.sourceMapFilename core
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_testing/src/test_config.rs
  crates/rspack_testing/test.config.scheme.json
  package.json
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/output/source-map-filename/index.js
  packages/rspack/tests/configCases/output/source-map-filename/two.js
  packages/rspack/tests/configCases/output/source-map-filename/webpack.config.js
  webpack-test/configCases/source-map/relative-source-map-path/index.js
Labels: p3-nice-to-have, release: feature

#2984 feat: optimization.realContentHash
  .changeset/sweet-owls-smash.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/asset.rs
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/LICENSE
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_plugin_wasm/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  examples/arco-pro/rspack.config.js
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/util/fake.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/HashTestCases.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/configCases/builtins/minify-pure-funcs/index.js
  packages/rspack/tests/configCases/builtins/minify-pure-funcs/webpack.config.js
  packages/rspack/tests/hashCases/package-path-change-0/webpack.config.js
  packages/rspack/tests/hashCases/package-path-change-1/webpack.config.js
  packages/rspack/tests/hashCases/real-content-hash/a/a.js
  packages/rspack/tests/hashCases/real-content-hash/a/b.js
  packages/rspack/tests/hashCases/real-content-hash/a/file.jpg
  packages/rspack/tests/hashCases/real-content-hash/a/file.png
  packages/rspack/tests/hashCases/real-content-hash/a/index.js
  packages/rspack/tests/hashCases/real-content-hash/a/lazy.js
  packages/rspack/tests/hashCases/real-content-hash/a/module.js
  packages/rspack/tests/hashCases/real-content-hash/b/a.js
  packages/rspack/tests/hashCases/real-content-hash/b/b.js
  packages/rspack/tests/hashCases/real-content-hash/b/file.jpg
  packages/rspack/tests/hashCases/real-content-hash/b/file.png
  packages/rspack/tests/hashCases/real-content-hash/b/index.js
  packages/rspack/tests/hashCases/real-content-hash/b/lazy.js
  packages/rspack/tests/hashCases/real-content-hash/b/module.js
  packages/rspack/tests/hashCases/real-content-hash/test.config.js
  packages/rspack/tests/hashCases/real-content-hash/webpack.config.js
Labels: release: feature

#2974 refactor(rust): add more restriction clippy rules
  .cargo/config.toml
  crates/cargo-rst/src/record.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_error/src/emitter.rs
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
  crates/rspack_ids/src/named_module_ids_plugin.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/export.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_library/src/export_property_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/basic_runtime_requirements.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/hot_module_replacement.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  crates/rspack_tracing/src/lib.rs
Labels: team

#3036 chore: 🤖 refactor before resolve
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compiler.ts
Labels: team

#3040 refactor(new_split_chunks): use `RspackRegex`
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
Labels: team

#3041 feat(new_split_chunks): support `id_hint` internally
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
Labels: team, release: feature, release: ignore

#3003 ci: make pr and main use the same CI workflow
  .github/workflows/bundle-stats.yaml.bak
  .github/workflows/check-js.yaml.bak
  .github/workflows/check-rs-ignore.yaml.bak
  .github/workflows/test-ignore.yml.bak
  .github/workflows/test-main.yml
  .github/workflows/test-pr.yml
  .github/workflows/test.yml
Labels: team

#3048 refactor(houseclean): split js plugin, parser and generator into different folders
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
Labels: team, release: ignore

#3049 refactor(houseclean): split css plugin, parser and generator into different folders
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_css/src/swc_css_compiler.rs
Labels: team, release: ignore, ready to review

#3009 feat(angular): adding initial support
  .gitignore
  .vscode/launch.json
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/js_values/stats.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/stats.rs
  examples/angular/README.md
  examples/angular/angular.json
  examples/angular/package.json
  examples/angular/rspack.config.js
  examples/angular/src/app/app-routing.module.ts
  examples/angular/src/app/app.component.html
  examples/angular/src/app/app.component.scss
  examples/angular/src/app/app.component.spec.ts
  examples/angular/src/app/app.component.ts
  examples/angular/src/app/app.module.ts
  examples/angular/src/assets/.gitkeep
  examples/angular/src/favicon.ico
  examples/angular/src/index.html
  examples/angular/src/main.ts
  examples/angular/src/styles.scss
  examples/angular/tsconfig.app.json
  examples/angular/tsconfig.json
  examples/angular/tsconfig.spec.json
  examples/angular/webpack.config.js
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/index.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  pnpm-lock.yaml
Labels: p1-important, release: feature

#3059 fix: 🐛 cross compile
  crates/node_binding/scripts/build.js
Labels: team, release: bug fix

#3061 fix: css url generate with auto public path
  .changeset/yellow-wombats-behave.md
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_html/src/config.rs
  packages/rspack/tests/cases/css/rewrite-url-auto-public-path/index.css
  packages/rspack/tests/cases/css/rewrite-url-auto-public-path/index.js
  packages/rspack/tests/cases/css/rewrite-url-auto-public-path/logo.png
  packages/rspack/tests/cases/css/rewrite-url-auto-public-path/webpack.config.js
Labels: team, release: bug fix

#3055 refactor: 💡 angular support
  examples/angular/package.json
  examples/angular/scripts/build.js
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/normalModule.ts
Labels: team

#3050 feat: optional-dependency
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/utils/hooks.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_testing/src/run_fixture.rs
  packages/rspack/tests/configCases/errors/missing-module/index.js
  packages/rspack/tests/configCases/errors/not-fully-specified/index.js
  packages/rspack/tests/configCases/warnings/missing-module/index.js
  packages/rspack/tests/configCases/warnings/missing-module/webpack.config.js
  packages/rspack/tests/configCases/warnings/not-fully-specified/fully-specified.mjs
  packages/rspack/tests/configCases/warnings/not-fully-specified/index.js
  packages/rspack/tests/configCases/warnings/not-fully-specified/not-fully-specified.mjs
Labels: p2-signifincant, release: feature

#3064 chore: take bump check temporarily
  scripts/check_changeset.js
Labels: team

#3057 fix: already split module should connect chunk group at multiply entry
  .changeset/strange-points-worry.md
  crates/rspack/tests/samples/remove-parent-modules/cycle-entry/expected/index_js.js
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/webpack.config.js
Labels: team, release: bug fix

#3065 chore: add stale bot, which only adds the "stale" label and never closes issues or PRs
  .github/stale.yml
Labels: team

#3072 fix(resolve): bump nodejs-resolver to fix baseUrl bug in tsconfig
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
Labels: team, release: bug fix

#3080 feat(rust): support __webpack_chunk_load__ module variable
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  packages/rspack/tests/cases/module-variables/webpack_chunk_load/index.js
Labels: release: feature

#3075 refactor(hmr): change visit_node_children from macro to fn
  crates/rspack_plugin_javascript/src/visitors/dependency/hmr_scanner.rs
Labels: team

#3076 feat: support `optimization.removeEmptyChunks` config
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#3068 feat(core): support custom dependency type internally
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/utils/hooks.rs
Labels: team, release: feature

#3043 feat(chunkId): care about `Chunk#id_name_hints` and generate more stable chunk id
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_ids/Cargo.toml
  crates/rspack_ids/src/lib.rs
  crates/rspack_ids/src/stable_named_chunk_ids_plugin.rs
Labels: team, release: feature, ready to review

#3030 chore: add svg-react-loader & node-loader example
  examples/loader-compat/package.json
  examples/loader-compat/rspack.config.js
  examples/loader-compat/src/arco.svg
  examples/loader-compat/src/index.js
  pnpm-lock.yaml
Labels: team

#3035 chore: single workspace
  .cargo/config.toml
  .github/workflows/check-rs.yaml
  .github/workflows/reusable-build.yml
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/build.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_options/src/options/raw_target.rs
  crates/rspack_error/Cargo.toml
  crates/rspack_testing/examples/build-cli.rs
  crates/rspack_testing/src/run_fixture.rs
  scripts/check_rust_dependency.cjs
  x.mjs
Labels: team, p1-important

#3093 feat(minify-plugin): support minify-css for minify-plugin
  .changeset/few-mugs-remember.md
  examples/extract-license/index.html
  examples/extract-license/package.json
  examples/extract-license/rspack.config.js
  examples/extract-license/src/index.js
  examples/plugin-compat/package.json
  examples/plugin-compat/rspack.config.js
  examples/plugin-compat/src/index.css
  examples/plugin-compat/src/index.js
  packages/rspack-plugin-minify/src/index.js
  pnpm-lock.yaml
Labels: team, release: feature

#3081 chore(rspack): add github-actions-reporter to jest
  packages/rspack-cli/jest.config.js
  packages/rspack-dev-server/jest.config.js
  packages/rspack/jest.config.js
Labels: team

#3083 fix(rspack_plugin_javascript): remove empty whitespace from runtime
  crates/rspack/tests/fixtures/dynamic-import/expected/runtime.js
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/copyPlugin/build/main.js
Labels: team, release: bug fix

#3086 feat(new_split_chunks): support `splitChunks.{cacheGroup}.enforce`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
  packages/rspack/src/config/schema.js
  packages/rspack/tests/configCases/split-chunks/reuse-chunk-name/b.js
  packages/rspack/tests/configCases/split-chunks/reuse-chunk-name/c.js
  packages/rspack/tests/configCases/split-chunks/reuse-chunk-name/index.js
  packages/rspack/tests/configCases/split-chunks/reuse-chunk-name/test.config.js
  packages/rspack/tests/configCases/split-chunks/reuse-chunk-name/webpack.config.js
Labels: team, release: feature, ready to review

#3094 fix: add correct chunk group runtime for multiply entry single runtime
  .changeset/seven-tigers-guess.md
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/tests/HotTestCases.template.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/a/index.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/b/index.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/changed-file.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/file.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/main/async.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/main/index.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/webpack.config.js
Labels: team, release: bug fix

#3082 chore: add test commands to x.mjs
  x.mjs
Labels: team

#3095 feat(realContentHash): multi contenthash in filename
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/asset.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/util/index.ts
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/hashCases/real-content-hash/webpack.config.js
Labels: release: feature

#3100 fix(emotion): should use source code for computing hash
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
Labels: team, release: bug fix

#3107 fix: fix esbuild iife for minify plugin
  packages/rspack-plugin-minify/src/index.js
Labels: team, release: bug fix

#3099 chore: disable perfsee upload in ci environment
  examples/perfsee/package.json
Labels: team

#3106 chore(rust): clean up dependencies via `cargo-machete`
  Cargo.lock
  crates/bench/Cargo.toml
  crates/node_binding/Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_futures/Cargo.toml
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_json/Cargo.toml
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_remove_empty_chunks/Cargo.toml
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_testing/Cargo.toml
Labels: team

#3098 chore: remove unused workspace dev dependencies
  package.json
  packages/rspack-plugin-html/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#3109 refactor(new_split_chunks): split methods of `SplitChunksPlugin` into different files
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/chunk.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
Labels: team, release: ignore, ready to review

#3037 fix(context module): should escape context module regex
  crates/rspack/tests/fixtures/dynamic-import/expected/main.js
  crates/rspack/tests/tree-shaking/context-module/expected/main.js
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/index.js
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/resources/pre_a.js
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/resources/pre_b.js
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/resources/pre_c.js
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/test.config.json
Labels: p2-signifincant, release: bug fix, ready to review

#3114 chore: fix toml indentation
  .taplo.toml
  Cargo.toml
  crates/bench/Cargo.toml
  crates/rspack_ast_viewer/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_build/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_napi_shared/Cargo.toml
  crates/rspack_testing/Cargo.toml
Labels: team

#2831 refactor: Remove impl `Module` for `Box<dyn Module>` in codebase
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
Labels: p3-nice-to-have, ready to merge

#3010 feat: add compatible compilation.chunks
  examples/plugin-compat/package.json
  examples/plugin-compat/rspack.config.js
  examples/plugin-compat/src/index.js
  packages/rspack/src/compilation.ts
  pnpm-lock.yaml
Labels: p2-signifincant, release: feature

#3115 chore: placeholder options for stats nestedModules
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/stats.ts
Labels: team

#3117 ci: run x86_64-unknown-linux-gnu tests without docker
  .github/actions/docker-test/action.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  .github/workflows/test.yml
  package.json
Labels: team

#3121 feat: add build meta exports type
  .changeset/nasty-schools-draw.md
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/strict.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team, release: feature

#3122 ci: run e2e tests in ubuntu-latest
  .github/workflows/reusable-build.yml
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team

#3123 chore(examples): remove unused eslint-loader from examples/eslint
  examples/eslint/package.json
  pnpm-lock.yaml
Labels: team

#3125 fix: 🐛 tree shaking nuxt error
  crates/rspack_core/src/compiler/mod.rs
Labels: team, release: bug fix

#3119 feat(new_split_chunks): support `maxInitialRequests` and `maxAsyncRequests` internally
  .changeset/orange-doors-pull.md
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/max_request.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
Labels: team, release: feature, release: ignore

#3136 chore: enable emitCss for svelte
  examples/svelte/rspack.config.js
Labels: team

#3138 chore(examples/plugin-compat): disable verbose log && add inline css
  examples/plugin-compat/index.ejs
  examples/plugin-compat/rspack.config.js
Labels: team

#3139 chore: clean up Cargo.toml for node_binding and rspack_binding_options
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
Labels: team

#3146 chore: upgrade ts-jest to 29.1.0
  package.json
  pnpm-lock.yaml
Labels: team

#3140 chore(rspack-cli): run jest with --runInBand
  packages/rspack-cli/package.json
Labels: team

#3141 feat(core): external supports array
  .vscode/launch.json
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/tests/configCases/externals/array-externals/index.js
  packages/rspack/tests/configCases/externals/array-externals/inject.js
  packages/rspack/tests/configCases/externals/array-externals/webpack.config.js
Labels: team, release: feature

#3113 perf: 🤖 optimize regex
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_regex/Cargo.toml
  crates/rspack_regex/src/algo.rs
  crates/rspack_regex/src/lib.rs
  packages/rspack/src/compiler.ts
Labels: team, release: performance

#3154 feat(plugin-node-polyfill): add process & buffer to node-polyfill
  examples/node-polyfill/index.html
  examples/node-polyfill/package.json
  examples/node-polyfill/rspack.config.js
  examples/node-polyfill/src/index.js
  packages/rspack-plugin-node-polyfill/src/index.js
  pnpm-lock.yaml
Labels: team, release: feature

#3156 chore: Upgraded `webpack` to `5.76.0`
  package.json
  packages/rspack-dev-client/package.json
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: p3-nice-to-have

#3159 fix(create-rspack): fix compatible problem with node@14
  packages/rspack-cli/src/commands/preview.ts
Labels: team, release: bug fix

#3105 fix: call devServer.invalidate() panic
  .changeset/honest-turtles-decide.md
  packages/rspack/src/watching.ts
Labels: team, release: bug fix

#3160 refactor(rust): remove dead code
  Cargo.lock
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/lib.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/ast/minify.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/export.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/visitors/clear_mark.rs
  crates/rspack_plugin_javascript/src/visitors/format.rs
  crates/rspack_plugin_javascript/src/visitors/inject_runtime_helper.rs
  crates/rspack_plugin_javascript/src/visitors/relay.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/provide.rs
  crates/rspack_plugin_javascript/src/visitors/tree_shaking.rs
  crates/rspack_plugin_split_chunks/src/plugin.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
  crates/rspack_regex/Cargo.toml
Labels: team

#3165 chore: fix version manually
  crates/node_binding/package.json
  crates/rspack_fs_node/package.json
  examples/angular/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  packages/create-rspack/package.json
  packages/playground/package.json
  packages/postcss-loader/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-client/package.json
  packages/rspack-dev-middleware/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-html/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-node-polyfill/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#3163 feat(core): support webpack-manifest-plugin
  examples/plugin-compat/package.json
  examples/plugin-compat/rspack.config.js
  packages/rspack/src/compilation.ts
  pnpm-lock.yaml
Labels: team, release: feature

#3124 feat(library): support system.js
  Cargo.lock
  crates/rspack/tests/fixtures/dynamic-import/expected/runtime.js
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/utils.rs
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/src/test_config.rs
  crates/rspack_testing/test.config.scheme.json
  examples/basic/rspack.config.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/externals/externals-system/index.js
  packages/rspack/tests/configCases/externals/externals-system/reexport-external.js
  packages/rspack/tests/configCases/externals/externals-system/test.config.js
  packages/rspack/tests/configCases/externals/externals-system/webpack.config.js
  packages/rspack/tests/configCases/target/system-context/index.js
  packages/rspack/tests/configCases/target/system-context/test.config.js
  packages/rspack/tests/configCases/target/system-context/webpack.config.js
  packages/rspack/tests/configCases/target/system-export/index.js
  packages/rspack/tests/configCases/target/system-export/test.config.js
  packages/rspack/tests/configCases/target/system-export/webpack.config.js
  packages/rspack/tests/configCases/target/system-named/index.js
  packages/rspack/tests/configCases/target/system-named/test.config.js
  packages/rspack/tests/configCases/target/system-named/webpack.config.js
  packages/rspack/tests/configCases/target/system-unnamed/index.js
  packages/rspack/tests/configCases/target/system-unnamed/test.config.js
  packages/rspack/tests/configCases/target/system-unnamed/webpack.config.js
  packages/rspack/tests/copyPlugin/build/main.js
  packages/rspack/tests/helpers/fakeSystem.js
Labels: p2-signifincant, release: feature, ready to review

#3178 chore: 🤖 fix cargo test crash
  .cargo/config.toml
Labels: team

#3143 refactor: compilation getPath
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/asset.rs
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/js_values/mod.rs
  crates/node_binding/src/js_values/path_data.rs
  crates/rspack/tests/fixtures.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_css/tests/fixtures/custom/modules-ident-name/expected/main.css
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.9e427565ffd0a9b0.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.9e427565ffd0a9b0.html
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/sub/other.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/user/[id].js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/user/[id]/page.js
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_plugin_wasm/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack-plugin-html/tests/basic.spec.js
  packages/rspack/src/compilation.ts
  packages/rspack/src/util/index.ts
  packages/rspack/tests/configCases/builtins/css-modules-local-ident-name-hash/index.js
  packages/rspack/tests/configCases/module/match-module-type/index.js
  packages/rspack/tests/configCases/rule-set/parser/index.js
  packages/rspack/tests/runtimeCases/runtime/split-chunk-with-hash/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk-with-content-hash/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk-with-hash/webpack.config.js
Labels: team, to be discussed

#3172 fix(license-plugin): add support for license-plugin in case of perChunkOutput as false
  packages/rspack/src/compiler.ts
Labels: p3-nice-to-have, release: bug fix

#3167 fix: 🐛 don't crash when export * of external module
  crates/rspack_core/src/tree_shaking/optimizer.rs
  packages/rspack/tests/configCases/tree-shaking/export-star-of-external-module/index.js
  packages/rspack/tests/configCases/tree-shaking/export-star-of-external-module/lib.js
  packages/rspack/tests/configCases/tree-shaking/export-star-of-external-module/webpack.config.js
Labels: team, release: bug fix

#3175 chore: console error info when ./x failed
  x
Labels: team

#3179 fix(magic_comment): support '()'
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/user/(id)/page.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/index.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/user/page/3.js
Labels: p2-signifincant, release: bug fix

#3183 fix: add experiments.css schema
  packages/rspack/src/config/schema.js
Labels: team, release: bug fix

#3171 feat(new_split_chunks): support `max_size`
  .changeset/young-experts-give.md
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/module_group.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/max_request.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/split-chunks/max-size-casing/chunk.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/file-A2.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/file-B2.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/file-a1.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/file-b1.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/index.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/test.config.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/webpack.config.js
Labels: team, release: feature, release: ignore

#3191 fix(plugin-node-polyfill): remove console polyfill
  examples/node-polyfill/src/index.js
  examples/node-polyfill/src/logger.js
  packages/rspack-plugin-node-polyfill/src/index.js
Labels: team, release: bug fix

#3186 feat(resolve): support custom exports fields
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/compiler/resolver.rs
  crates/rspack_core/src/options/resolve.rs
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/resolve/conditions/test.config.js
  packages/rspack/tests/configCases/resolve/exports-fields/.gitignore
  packages/rspack/tests/configCases/resolve/exports-fields/index.js
  packages/rspack/tests/configCases/resolve/exports-fields/node_modules/exports-field/b.js
  packages/rspack/tests/configCases/resolve/exports-fields/node_modules/exports-field/package.json
  packages/rspack/tests/configCases/resolve/exports-fields/webpack.config.js
Labels: team, release: feature

#3192 chore: fix arco-pro example crashing in debug mode
  examples/arco-pro/rspack.config.js
Labels: team

#3188 feat: add output.hotUpdateMainFilename & output.hotUpdateChunkFilename
  .changeset/empty-owls-jump.md
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/path_data.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_runtime/src/basic_runtime_requirements.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_update_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_main_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_chunk_update_filename.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_update_manifest_filename.js
  crates/rspack_testing/src/test_config.rs
  packages/rspack/package.json
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#3195 chore: fix arco-pro crash again
  examples/arco-pro/patches/mock.js
  examples/arco-pro/rspack.config.js
Labels: team

#3200 chore: fix node16 tests
  packages/rspack/tests/case.template.ts
Labels: team

#3197 fix: wasm loading runtime on node-18
  crates/rspack_plugin_wasm/src/loading_plugin.rs
  crates/rspack_plugin_wasm/src/runtime.rs
Labels: team, release: bug fix

#3168 ci: add test Node.js v18
  .github/workflows/reusable-build.yml
  crates/rspack_fs_node/package.json
  package.json
  packages/playground/package.json
  packages/rspack-cli/jest.config.js
  packages/rspack-dev-client/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-html/package.json
  packages/rspack/jest.config.js
  packages/rspack/package.json
  packages/rspack/tests/helpers/createLazyTestEnv.js
  pnpm-lock.yaml
  scripts/test/patch-node-env.cjs
  webpack-test/package.json
Labels: team

#3194 fix: render exports for esm output at hmr
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
Labels: team, release: bug fix

#3181 fix: export-all-from-side-effects-free-commonjs
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/expected/main.js
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/index.js
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/lib.js
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/package.json
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/test.config.json
  crates/rspack_core/src/tree_shaking/debug_helper.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3201 fix: fix provide can't be override by user
  packages/rspack-plugin-node-polyfill/src/index.js
Labels: release: bug fix

#3206 chore: fix jest crash on node
  packages/rspack-cli/package.json
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/tests/build/config/loadConfig.test.ts
  packages/rspack-cli/tests/build/config/test.rspack.config.cjs
  packages/rspack-cli/tsconfig.json
Labels: team

#3204 fix: provided dependency generated code not stable
  Cargo.lock
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/provide.rs
  packages/rspack/tests/HashTestCases.test.ts
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/hashCases/provided-dependency-order/index.js
  packages/rspack/tests/hashCases/provided-dependency-order/webpack.config.js
Labels: team, release: bug fix

#3208 fix: ci clippy
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3151 fix: context module elimated
  crates/rspack/tests/tree-shaking/context-module-elimated/README.md
  crates/rspack/tests/tree-shaking/context-module-elimated/child/child/index.js
  crates/rspack/tests/tree-shaking/context-module-elimated/child/index.js
  crates/rspack/tests/tree-shaking/context-module-elimated/expected/main.js
  crates/rspack/tests/tree-shaking/context-module-elimated/index.js
  crates/rspack/tests/tree-shaking/context-module-elimated/lib.js
  crates/rspack/tests/tree-shaking/context-module-elimated/package.json
  crates/rspack/tests/tree-shaking/context-module-elimated/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
Labels: team, release: bug fix

#3215 chore(gitattributes): make repo more rusty
  .gitattributes
Labels: team, release: ignore

#3211 ci: create issue in rspack-website when a pr is merged with "need documentation" label
  .github/workflows/need-doc.yml
Labels: need documentation

#3216 chore(license): split third party licenses to a separate file
  LICENSE
  THIRD-PARTY-LICENSE
Labels: team, release: ignore

#3226 fix: 🐛 amd external-array
  crates/rspack_plugin_library/src/utils.rs
Labels: team, release: bug fix

#3228 perf: skip call chunkAsset hook when not in use
  packages/rspack/src/compiler.ts
Labels: team, release: performance

#3230 chore: add `x ready` command for running everything
  x.mjs
Labels: team

#3220 feat: data uri support
  Cargo.lock
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack/tests/fixtures/dynamic-import/expected/main.js
  crates/rspack/tests/tree-shaking/context-module/expected/main.js
  crates/rspack_base64/src/lib.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/common_js_require_context_dependency.rs
  crates/rspack_core/src/dependency/import_context_dependency.rs
  crates/rspack_core/src/dependency/require_context_dependency.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/expected/main.js
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_library/src/utils.rs
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/LICENSE
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_schemes/src/lib.rs
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/cases/schemes/data-imports/index.js
  packages/rspack/tests/copyPlugin/build/main.js
Labels: team, release: feature

#3218 feat(types): support string or object in copy.patterns array
  packages/rspack/src/config/builtins.ts
Labels: team, release: feature

#3238 feat: add scheme, mimetype, and resourceFragment rule condition
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/node_binding/src/js_values/path_data.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/utils/identifier.rs
  crates/rspack_core/src/utils/module_rules.rs
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/cases/schemes/data-imports/a.css
  packages/rspack/tests/cases/schemes/data-imports/index.css
  packages/rspack/tests/cases/schemes/data-imports/index.js
  packages/rspack/tests/cases/schemes/data-imports/webpack.config.js
Labels: team, release: feature

#3060 feat: normal module factory after resolve hooks
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compiler.ts
  packages/rspack/src/normalModuleFactory.ts
Labels: team, release: feature

#3244 fix(dev-client): remove some unused dependencies
  packages/rspack-dev-client/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#3246 feat: add support for `Rule.loader` and `Rule.options`
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
Labels: team, release: feature

#3250 fix: `source` could be unavailable if asset was deleted
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
Labels: team, release: bug fix

#3245 ci: remove unnecessary `test` option from reusable-build
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  .github/workflows/test.yml
Labels: team

#3251 fix(core): upgrade regress to 0.6.0 to fix regress compile regex error
  Cargo.lock
  crates/rspack_regex/Cargo.toml
  packages/rspack/tests/cases/context/issue-3241/index.js
  packages/rspack/tests/cases/context/issue-3241/nr-hooks/ahook.js
Labels: team, release: bug fix

#3235 feat: add afterCompile hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compiler.ts
Labels: release: feature

#3248 ci: automatically create Tuesday's release PR
  .github/workflows/check-rs.yaml
  .github/workflows/release-nightly.yml
  .github/workflows/release-pull-request.yml
  .github/workflows/release.yml
Labels: team

#3261 chore: add debug shell
  .github/workflows/reusable-build.yml
Labels: team

#3209 refactor(new_split_chunks): re-organize code structures
  crates/rspack_plugin_split_chunks_new/src/plugin/max_size.rs
Labels: team, release: ignore

#3265 ci: remove nightly step from full release
  .github/workflows/release.yml
Labels: team

#3256 chore: progressively migrate webpack test case
  webpack-test/ChangesAndRemovalsTemp/temp-file.js
  webpack-test/ChangesAndRemovalsTemp/temp-file2.js
  webpack-test/ConfigTestCases.template.js
  webpack-test/Examples.test.js
  webpack-test/HotTestCases.template.js
  webpack-test/MemoryLimitTestCases.test.js
  webpack-test/README.md
  webpack-test/Stats.test.js
  webpack-test/StatsTestCases.basictest.js
  webpack-test/TestCases.template.js
  webpack-test/WatchTestCases.template.js
  webpack-test/configCases/assets/delete-asset/test.filter.js
  webpack-test/lib/util/filterUtil.js
  webpack-test/package.json
  webpack-test/scripts/test-metric.js
Labels: team

#3266 chore: 🤖 ignore title validate
  .github/workflows/lint-pr.yaml
Labels: team

#3176 fix: namespace access on var decl rhs
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/a.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/b.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/enum-old.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/enum.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/expected/main.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/index.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/lib.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
Labels: team, release: bug fix

#3214 fix(tree_shaking): obj['test'] reference
  crates/rspack/tests/tree-shaking/issues_3198/expected/main.js
  crates/rspack/tests/tree-shaking/issues_3198/index.js
  crates/rspack/tests/tree-shaking/issues_3198/test.config.json
  crates/rspack/tests/tree-shaking/issues_3198/test.js
  crates/rspack_core/src/tree_shaking/visitor.rs
Labels: release: bug fix

#3262 chore: remove jest-github-actions-reporter
  packages/rspack-cli/jest.config.js
  packages/rspack-cli/package.json
  packages/rspack-dev-server/jest.config.js
  packages/rspack-dev-server/package.json
  packages/rspack/jest.config.js
  packages/rspack/package.json
Labels: team

#3274 chore: fix broken pnpm lockfile
  pnpm-lock.yaml
Labels: team

#3268 fix: external amd array case
  crates/rspack_plugin_library/src/utils.rs
Labels: team, release: bug fix

#3275 chore(examples): add missing private to two example packages
  examples/plugin-compat/package.json
  examples/proxy/package.json
Labels: team

#3276 ci: publish nightly with release script
  .github/actions/pnpm-cache/action.yml
  .github/workflows/release-nightly.yml
Labels: team

#3279 fix: bump swc to fix many bugs
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/visitors/tree_shaking.rs
  packages/rspack/tests/configCases/rule-set/module-type/app.tsx
Labels: team, release: bug fix, release: ignore

#3282 fix: should not resolve to a rule if an existing rule does not have its data
  crates/rspack_core/src/utils/module_rules.rs
Labels: team, release: bug fix

#3284 ci: only cache pnpm on main branch for avoiding 10GB cache limit
  .github/actions/pnpm-cache/action.yml
Labels: team

#3281 chore: add storybook example
  examples/react-storybook/.eslintrc.js
  examples/react-storybook/.storybook/main.js
  examples/react-storybook/.storybook/preview.js
  examples/react-storybook/.storybook/rspack.config.js
  examples/react-storybook/index.html
  examples/react-storybook/package.json
  examples/react-storybook/rspack.config.js
  examples/react-storybook/src/App.css
  examples/react-storybook/src/App.jsx
  examples/react-storybook/src/assets/react.svg
  examples/react-storybook/src/index.css
  examples/react-storybook/src/main.jsx
  examples/react-storybook/src/stories/Button.stories.js
  examples/react-storybook/src/stories/Button.tsx
  examples/react-storybook/src/stories/Header.jsx
  examples/react-storybook/src/stories/Header.stories.js
  examples/react-storybook/src/stories/Introduction.mdx
  examples/react-storybook/src/stories/Page.jsx
  examples/react-storybook/src/stories/Page.stories.js
  examples/react-storybook/src/stories/assets/code-brackets.svg
  examples/react-storybook/src/stories/assets/colors.svg
  examples/react-storybook/src/stories/assets/comments.svg
  examples/react-storybook/src/stories/assets/direction.svg
  examples/react-storybook/src/stories/assets/flow.svg
  examples/react-storybook/src/stories/assets/plugin.svg
  examples/react-storybook/src/stories/assets/repo.svg
  examples/react-storybook/src/stories/assets/stackalt.svg
  examples/react-storybook/src/stories/button.css
  examples/react-storybook/src/stories/header.css
  examples/react-storybook/src/stories/page.css
  examples/react-storybook/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: team

#3249 feat: support resolve.extensionAlias
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/options/resolve.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/resolve/extension-alias/index.js
  packages/rspack/tests/configCases/resolve/extension-alias/src/index.mts
  packages/rspack/tests/configCases/resolve/extension-alias/webpack.config.js
Labels: team, release: feature, need documentation
