Repository web-infra-dev/rspack, pull requests merged in 2023-04, with the labels that each got.

#2575 feat(rspack-cli): emit warning if the using nodejs version is not recommended
  packages/rspack-cli/src/rspack-cli.ts
Labels: p3-nice-to-have

#2578 feat(rspack_plugin_dev_friendly_split_chunks): reduce `MAX_MODULES_PER_CHUNK` and add `MAX_SIZE_PER_CHUNK` condition
  .changeset/tame-seals-pull.md
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
Labels: team, p1-planned

#2584 ci: encore PR titles to follow the conventional-commit rules
  .github/workflows/lint-pr.yaml
  CONTRIBUTING.md
Labels: team

#2586 fix(cli): fix semver missing
  .changeset/honest-houses-dress.md
  packages/rspack-cli/package.json
  pnpm-lock.yaml
Labels: team

#2588 chore: fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: team

#2596 chore: remove copy-plugin from cra example
  examples/cra-ts/package.json
  examples/cra-ts/public/index.html
  examples/cra-ts/rspack.config.js
  examples/cra/package.json
  examples/cra/public/index.html
  examples/cra/rspack.config.js
  pnpm-lock.yaml
Labels: team

#2600 fix: swc css minifier global not set
  crates/rspack_plugin_css/src/lib.rs
Labels: team

#2576 fix(dev-client): use webpack-dev-server/client directly
  .changeset/empty-horses-sleep.md
  package.json
  packages/playground/fixtures/react/webpack.config.js
  packages/rspack-dev-client/package.json
  packages/rspack-dev-client/src/clients/SockJSClient.ts
  packages/rspack-dev-client/src/clients/WebSocketClient.ts
  packages/rspack-dev-client/src/devServer.ts
  packages/rspack-dev-client/src/index.ts
  packages/rspack-dev-client/src/socket.ts
  packages/rspack-dev-server/package.json
  packages/rspack-dev-server/src/reload.ts
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  pnpm-lock.yaml
Labels: team

#2589 feat(html): support templateContent in `builtins.html`
  .changeset/clean-turkeys-dance.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/index.js
  crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/test.config.json
  packages/rspack/tests/configCases/builtins/html-template-content/index.js
  packages/rspack/tests/configCases/builtins/html-template-content/webpack.config.js
Labels: team

#2587 fix(hmr): improve detecting of ReactRefreshBoundary and Return value of `React.createContext` is not considered as React component
  .changeset/gold-moons-poke.md
  README.md
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
  packages/playground/fixtures/react/src/App.jsx
  packages/playground/fixtures/react/src/CountProvider.jsx
  packages/playground/fixtures/react/src/index.jsx
  packages/playground/fixtures/react/test/index.test.ts
  packages/rspack-dev-client/package.json
  packages/rspack-dev-client/src/reactRefresh.ts
  pnpm-lock.yaml
Labels: team

#2606 ci: release pre check
  .github/workflows/release.yml
Labels: team

#2506 fix: bump nodejs-resolver to fix path issue with chinese characaters
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/options/resolve.rs
  packages/rspack/src/config/types.ts
Labels: team

#2625 fix: initial watching should stale until invalidate happens
  .changeset/four-vans-decide.md
  packages/rspack/src/multiCompiler.ts
  packages/rspack/src/watching.ts
  packages/rspack/tests/MultiCompiler.test.ts
Labels: team

#2615 chore: Upgrade typescript
  examples/arco-pro/package.json
  examples/svelte/package.json
  examples/svelte/tsconfig.json
  package.json
  packages/rspack-dev-client/package.json
  packages/rspack-dev-server/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#2574 perf: remove block_in_place for function type RuleSetCondition
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/rspack_binding_options/src/options/raw_module.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/utils/module_rules.rs
Labels: team

#2629 chore: add library example
  examples/library/package.json
  examples/library/rspack.config.js
  examples/library/src/index.js
  pnpm-lock.yaml
Labels: team

#2630 ci: add refactor type on lint-pr
  .github/workflows/lint-pr.yaml
Labels: team

#2627 test: webpack test credit
  webpack-test/README.md
Labels: team

#2632 feat: add support for output.crossOriginLoading config
  crates/node_binding/binding.d.ts
  crates/rspack/tests/fixtures/.hash/expected/runtime.js
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  crates/rspack_testing/src/test_config.rs
  packages/playground/fixtures/cross-origin-loading/package.json
  packages/playground/fixtures/cross-origin-loading/rspack.config.js
  packages/playground/fixtures/cross-origin-loading/src/foo.js
  packages/playground/fixtures/cross-origin-loading/src/index.html
  packages/playground/fixtures/cross-origin-loading/src/index.js
  packages/playground/fixtures/cross-origin-loading/test/index.test.ts
  packages/playground/fixtures/react/rspack.config.js
  packages/playground/fixtures/utils.ts
  packages/playground/scripts/setupFiles.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  pnpm-lock.yaml
Labels: team, p1-signifincant-downstream-blocker

#2635 fix: fix typing of raw cross origin loading
  .changeset/cuddly-llamas-wave.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
Labels: team

#2641 fix(hmr): should inject react refresh runtime code correctly
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
Labels: team

#2644 chore: add a issue template for creating tracking issue
  .github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
Labels: team

#2637 feat: support node false
  .changeset/dull-sheep-argue.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/parsing/issue-9156/index.js
  packages/rspack/tests/configCases/parsing/issue-9156/webpack.config.js
  packages/rspack/tests/configCases/parsing/node-source-plugin-off/index.js
  packages/rspack/tests/configCases/parsing/node-source-plugin-off/webpack.config.js
  packages/rspack/tests/configCases/parsing/node-stuff-plugin-off/index.js
  packages/rspack/tests/configCases/parsing/node-stuff-plugin-off/test.config.js
  packages/rspack/tests/configCases/parsing/node-stuff-plugin-off/webpack.config.js
  packages/rspack/tests/copyPlugin/build/main.js
Labels: team

#2647 chore: fix the format of 3-tracking-issue.en-US
  .github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
Labels: team

#2634 fix: 🐛 Module Export Entry does not respect ordering
  .changeset/chilly-colts-yawn.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/cache/local/code_splitting_cache.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_loader_sass/tests/fixtures.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/tests/case.template.ts
  packages/rspack/tests/configCases/builtins/html-entry-order/index.html
  packages/rspack/tests/configCases/builtins/html-entry-order/index.js
  packages/rspack/tests/configCases/builtins/html-entry-order/polyfill.js
  packages/rspack/tests/configCases/builtins/html-entry-order/webpack.config.js
Labels: team, p1-signifincant-downstream-blocker

#2565 fix: detect export destructring in tree-shaking
  .changeset/lemon-spies-shout.md
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_error/tests/fixtures/should_not_warn_export_destructring/a.js
  crates/rspack_error/tests/fixtures/should_not_warn_export_destructring/fixtures__should_not_warn_export_destructring.snap
  crates/rspack_error/tests/fixtures/should_not_warn_export_destructring/index.js
  crates/rspack_error/tests/fixtures/should_not_warn_export_destructring/test.config.json
Labels: p3-nice-to-have

#2648 chore: prepare for rspack-ecosystem-ci
  .github/workflows/ecosystem-ci-trigger.yml
  package.json
  packages/rspack-cli/jest.config.js
  packages/rspack-cli/tests/build/json/.gitignore
  packages/rspack-cli/tests/build/json/stats.json
Labels: team

#2658 chore: fix ecosystem-ci trigger comment
  .github/workflows/ecosystem-ci-trigger.yml
Labels: team

#2651 feat: split chunks more delicately for `devFriendlySplitChunks: true`
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
Labels: p2-signifincant, team, ready to merge

#2649 chore: add nestjs example
  examples/nestjs/README.md
  examples/nestjs/package.json
  examples/nestjs/rspack.config.js
  examples/nestjs/src/app.controller.ts
  examples/nestjs/src/app.module.ts
  examples/nestjs/src/app.service.ts
  examples/nestjs/src/main.ts
  pnpm-lock.yaml
Labels: team

#2661 fix: 🐛 release ci syntax
  .github/workflows/release.yml
Labels: team

#2662 chore(ci): comment out release-pre-check
  .github/workflows/release.yml
Labels: team

#2660 refactor: 🤖 remove unnecessary ignore clippy
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
Labels: team

#2665 feat: enable resolve.fullySpecified for defaultRules
  .changeset/friendly-pillows-divide.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/configCases/errors/not-fully-specified/fully-specified.mjs
  packages/rspack/tests/configCases/errors/not-fully-specified/index.js
  packages/rspack/tests/configCases/errors/not-fully-specified/not-fully-specified.mjs
Labels: team

#2663 feat: support module.rule[].descriptionData
  .changeset/pink-owls-sip.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  crates/rspack_plugin_javascript/src/utils.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#2666 fix: nested byDependency not merge
  crates/rspack_core/src/options/resolve.rs
  crates/rspack_core/src/utils/module_rules.rs
  examples/bundle-splitting/package.json
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/resolve/nested-by-dependency/bar.mjs
  packages/rspack/tests/configCases/resolve/nested-by-dependency/baz.js
  packages/rspack/tests/configCases/resolve/nested-by-dependency/foo.bar
  packages/rspack/tests/configCases/resolve/nested-by-dependency/index.js
  packages/rspack/tests/configCases/resolve/nested-by-dependency/webpack.config.js
Labels: team

#2677 fix: use codegen hash to calculate chunk hashes & fix runtime chunk hash
  .changeset/flat-needles-suffer.md
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  packages/rspack/tests/HashTestCases.test.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/hashCases/package-path-change-0/.gitignore
  packages/rspack/tests/hashCases/package-path-change-0/index.js
  packages/rspack/tests/hashCases/package-path-change-0/node_modules/package/package.json
  packages/rspack/tests/hashCases/package-path-change-0/node_modules/package/package0.js
  packages/rspack/tests/hashCases/package-path-change-0/webpack.config.js
  packages/rspack/tests/hashCases/package-path-change-1/.gitignore
  packages/rspack/tests/hashCases/package-path-change-1/index.js
  packages/rspack/tests/hashCases/package-path-change-1/node_modules/package/package.json
  packages/rspack/tests/hashCases/package-path-change-1/node_modules/package/package1.js
  packages/rspack/tests/hashCases/package-path-change-1/webpack.config.js
Labels: team, p0-urgent

#2681 chore: add "pending triage" to new issue by default
  .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
  .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
Labels: team

#2682 ci: remove issue-labeler
  .github/issue-labeler.yml
  .github/workflows/issue-label.yml
Labels: team

#2655 chore: several style change for more concise code
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: p3-nice-to-have

#2659 feat: Support output.clean
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_build/fixture/test.config.json
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_fs/src/async.rs
  crates/rspack_fs/src/native.rs
  crates/rspack_fs_node/src/async.rs
  crates/rspack_fs_node/src/node.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/fileSystem.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Output.test.ts
Labels: p2-signifincant, ready to merge

#2679 feat: support output.chunkLoadingGlobal
  .changeset/strange-pianos-knock.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.js
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
Labels: team

#2685 feat(cli): support mjs&cjs as default config file
  .changeset/curvy-weeks-burn.md
  packages/rspack-cli/src/utils/loadConfig.ts
Labels: team

#2686 feat: support magical comment "webpackChunkName"
  crates/rspack_core/src/ast/javascript.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/dependency/dynamic_import.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  package.json
  packages/rspack/tests/cases/parsing/issue-6867/a.js
  packages/rspack/tests/cases/parsing/issue-6867/b.js
  packages/rspack/tests/cases/parsing/issue-6867/c.js
  packages/rspack/tests/cases/parsing/issue-6867/d.js
  packages/rspack/tests/cases/parsing/issue-6867/e.js
  packages/rspack/tests/cases/parsing/issue-6867/f.js
  packages/rspack/tests/cases/parsing/issue-6867/g.js
  packages/rspack/tests/cases/parsing/issue-6867/h.js
  packages/rspack/tests/cases/parsing/issue-6867/index.js
  packages/rspack/tests/copyPlugin/build/_t3/dest1/tempfile1.txt
  packages/rspack/tests/copyPlugin/fixtures/watch/_t3/directory/tempfile1.txt
  packages/rspack/tests/copyPlugin/fixtures/watch/_t3/directory/tempfile2.txt
  pnpm-lock.yaml
Labels: team, p1-signifincant-downstream-blocker, block: modern.js

#2636 test: 💍 webpack stats test
  webpack-test/Errors.test.js
  webpack-test/HotTestCases.template.js
  webpack-test/Stats.test.js
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap.bak
  webpack-test/package.json
Labels: team

#2689 ci: 🎡 fix spell check failed
  .typos.toml
Labels: team

#2690 fix: changeset remove not exist package
  .changeset/warm-snakes-bathe.md
Labels: team

#2684 feat: import meta scanner
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/esm/import-meta/index.js
Labels: team

#2703 chore: split test
  package.json
  packages/playground/package.json
Labels: team

#2698 chore: remove the prefix of title in GitHub issue template
  .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
  .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
Labels: team

#2715 chore: Revert "chore: bump napi"
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/package.json
  pnpm-lock.yaml
Labels: team

#2716 chore: check bump in ci
  scripts/check_changeset.js
Labels: team

#2720 chore: add datetime to nightly version
  .changeset/config.json
Labels: team

#2707 fix(html): html inject public path incorrect
  .changeset/dry-camels-tie.md
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/plugin.rs
  packages/rspack/tests/configCases/builtins/html-public-path-auto/index.js
  packages/rspack/tests/configCases/builtins/html-public-path-auto/webpack.config.js
Labels: team

#2726 chore: add graph of contributors
  README.md
Labels: team

#2723 chore: enable strictCommand & strictOption check
  .changeset/bright-carrots-behave.md
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
Labels: team

#2729 chore: use copilot in PR template by default
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#2730 chore: Improve PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#2725 fix(progress): should not display empty progress bar
  .changeset/shiny-squids-matter.md
  crates/rspack_plugin_progress/src/lib.rs
Labels: team

#2731 feat(core): print the module identifier if not founded
  crates/rspack_core/src/chunk_graph.rs
Labels: team

#2736 chore: add codeowner for crate error
  .github/CODEOWNERS
Labels: team

#2737 feat: passthrough panics for parallel-running futures
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_futures/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
Labels: team

#2734 fix: panic hook failed to restore after being suppressed
  .changeset/honest-actors-smoke.md
  crates/rspack_error/src/catch_unwind.rs
Labels: team

#2714 fix(react-refresh): lazily access `module.exports` to prevent unexpected/potential TDZ error
  .changeset/pretty-rocks-cross.md
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
Labels: team

#2724 fix(cli): fix default NODE_ENV of command
  packages/rspack-cli/src/rspack-cli.ts
Labels: team

#2743 chore: remove continue-on-error from reusable-build
  .github/workflows/reusable-build.yml
Labels: team

#2744 fix: :bug: fix crash in multiCompiler
  .changeset/metal-dodos-play.md
  .github/actions/docker-test/action.yml
  .github/workflows/reusable-build.yml
  crates/node_binding/src/lib.rs
  packages/rspack/tests/MultiCompiler.test.ts
Labels: team

#2746 ci: remove invalid "description" field from release-canary
  .github/workflows/release-canary.yml
Labels: team

#2747 fix(css): should generate css assets even if the imported css file is empty
  crates/rspack_plugin_css/src/plugin.rs
  packages/playground/fixtures/import-empty-css-file/package.json
  packages/playground/fixtures/import-empty-css-file/rspack.config.js
  packages/playground/fixtures/import-empty-css-file/src/empty.css
  packages/playground/fixtures/import-empty-css-file/src/empty.js
  packages/playground/fixtures/import-empty-css-file/src/index.html
  packages/playground/fixtures/import-empty-css-file/src/index.js
  packages/playground/fixtures/import-empty-css-file/test/index.test.ts
Labels: team

#2749 revert: "fix(css): should generate css assets even if the imported css file is empty"
  crates/rspack_plugin_css/src/plugin.rs
  packages/playground/fixtures/import-empty-css-file/package.json
  packages/playground/fixtures/import-empty-css-file/rspack.config.js
  packages/playground/fixtures/import-empty-css-file/src/empty.css
  packages/playground/fixtures/import-empty-css-file/src/empty.js
  packages/playground/fixtures/import-empty-css-file/src/index.html
  packages/playground/fixtures/import-empty-css-file/src/index.js
  packages/playground/fixtures/import-empty-css-file/test/index.test.ts
Labels: team

#2754 chore: introduce zx, corepack and setup script
  CONTRIBUTING.md
  package.json
  scripts/.gitignore
  scripts/README.md
  scripts/build-npm.js
  scripts/check_changeset.js
  scripts/check_rust_dependency.js
  scripts/cmd.js
  scripts/log.js
  scripts/meta/doctor.mjs
  scripts/meta/setup.mjs
  scripts/package.json
  scripts/tsconfig.json
  scripts/update_swc_version.js
Labels: team

#2755 chore: fix typo
  scripts/README.md
  scripts/meta/setup.mjs
Labels: team

#2756 chore: remove `zx` in setup script
  package.json
  scripts/README.md
  scripts/doctor.mjs
  scripts/meta/setup.mjs
Labels: team

#2759 fix(css): should generate css assets even if the imported css file is empty
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_css/tests/fixtures/custom/modules-ident-name/style.module.css
  packages/playground/fixtures/import-empty-css-file/package.json
  packages/playground/fixtures/import-empty-css-file/rspack.config.js
  packages/playground/fixtures/import-empty-css-file/src/empty.css
  packages/playground/fixtures/import-empty-css-file/src/empty.js
  packages/playground/fixtures/import-empty-css-file/src/index.html
  packages/playground/fixtures/import-empty-css-file/src/index.js
  packages/playground/fixtures/import-empty-css-file/test/index.test.ts
  packages/rspack/src/web/ResolveSwcPlugin.ts
  pnpm-lock.yaml
Labels: p2-signifincant, release: bug fix

#2765 chore: Add release.yml
  .github/release.yml
Labels: team

#2721 fix(builtins.provide): should only replace exactly matched expression
  .changeset/clean-plums-kick.md
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/provide.rs
  crates/rspack_plugin_javascript/tests/fixtures/provide/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/provide/index.js
  crates/rspack_plugin_javascript/tests/fixtures/provide/process.js
  crates/rspack_plugin_javascript/tests/fixtures/provide/test.config.json
  packages/rspack/tests/configCases/builtins/provide/index.js
  packages/rspack/tests/configCases/builtins/provide/process.js
  packages/rspack/tests/configCases/builtins/provide/webpack.config.js
Labels: p2-signifincant, release: bug fix

#2770 feat(html): `builtins.html` should inject `<script href="xxxx" />` in `<head />`
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/tests/fixtures/chunks/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/favicon/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.c58a17e264b8bc1.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.cf6dd0ecc5222c7a.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.14c6c3011e162801.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.9abfee7e7d4b36c9.html
  crates/rspack_plugin_html/tests/fixtures/meta/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/minify/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/mpa/expected/chunk1.html
  crates/rspack_plugin_html/tests/fixtures/mpa/expected/chunk2.html
  crates/rspack_plugin_html/tests/fixtures/mpa/expected/chunk3.html
  crates/rspack_plugin_html/tests/fixtures/public-path/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/template+templateParameters/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/expected/index.html
  crates/rspack_plugin_html/tests/fixtures/title/expected/index.html
Labels: release: feature

#2767 ci: labeling PR with release: xxx automatically
  .github/pr-labeler.yml
  .github/workflows/lint-pr.yaml
Labels: team

#2766 chore: ignore the PRs created by github-actions in release notes
  .github/release.yml
Labels: team

#2769 chore: improve structrue of PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#2717 chore: 🤖 bump napi
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/package.json
  packages/playground/fixtures/import-empty-css-file/test/index.test.ts
  pnpm-lock.yaml
  scripts/check_rust_dependency.js
Labels: team

#2294 perf(core): improve cold startup performance by caching `depended_modules` function in code splitter
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: performance

#2776 feat: 🎸 export info support
  crates/node_binding/Cargo.lock
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/webpack_ext.rs
  examples/basic/src/answer.js
  examples/basic/src/b.js
  examples/basic/src/index.js
Labels: team, release: feature

#2778 fix: redirect `name_for_condition` in BoxModule
  crates/rspack_core/src/module.rs
Labels: team, release: bug fix

#2783 chore: Revert "chore: 🤖 bump napi (#2717)"
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/package.json
  packages/playground/fixtures/import-empty-css-file/test/index.test.ts
  pnpm-lock.yaml
  scripts/check_rust_dependency.js
Labels: team

#2794 chore: fine grained lint stage
  package.json
Labels: team

#2796 ci: set fail-fast: false for matrix builds
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  .github/workflows/test-main.yml
  .github/workflows/test-pr.yml
Labels: team

#2792 feat: add chunkFormat & chunkLoading & enabledChunkLoadingTypes config
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_hmr.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/configCases/plugins/polyfill/webpack.config.js
  packages/rspack/tests/configCases/umd/issue-15545/index.js
  packages/rspack/tests/configCases/umd/issue-15545/test.config.js
  packages/rspack/tests/configCases/umd/issue-15545/webpack.config.js
Labels: team, p1-important, release: feature

#2799 chore: 🤖 revert examples basic
  examples/basic/src/answer.js
  examples/basic/src/b.js
  examples/basic/src/index.js
Labels: team

#2798 ci: only cache Rust builds on the main branch
  .github/workflows/check-rs.yaml
  .github/workflows/reusable-build.yml
Labels: team

#2782 refactor: SplitChunksPlugin
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_split_chunks_new/LICENSE
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/module_group.rs
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
Labels: team

#2789 feat: impl new loader-runner
  .changeset/rich-kings-itch.md
  Cargo.lock
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/LICENSE
  crates/rspack_loader_runner/src/content.rs
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_runner/src/plugin.rs
  crates/rspack_loader_runner/src/runner.rs
Labels: team, p1-important, release: feature

#2805 chore: fix lock
  crates/node_binding/Cargo.lock
Labels: team

#2745 test: webpack compatibility metric
  .typos.toml
  webpack-test/Stats.test.js
  webpack-test/__snapshots__/Cli.basictest.js.snap.bak
  webpack-test/__snapshots__/Cli.basictest.js.snap.diff
  webpack-test/__snapshots__/ConfigCacheTestCases.longtest.js.snap.bak
  webpack-test/__snapshots__/ConfigCacheTestCases.longtest.js.snap.diff
  webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap.diff
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap.bak
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap.diff
  webpack-test/__snapshots__/target-browserslist.unittest.js.snap.bak
  webpack-test/__snapshots__/target-browserslist.unittest.js.snap.diff
  webpack-test/cases/errors/case-sensitive/test.filter.js
  webpack-test/package.json
  webpack-test/scripts/snapshot-metric.js
  webpack-test/scripts/test-metric.js
Labels: team

#2807 fix: preset env use unresolved_mark
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
  packages/rspack/tests/configCases/builtins/preset-env/index.js
Labels: team, release: bug fix

#2809 ci: fix fail-fast
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/test-main.yml
  .github/workflows/test-pr.yml
Labels: team

#2810 fix: 🐛 fix ci a is undefined
  packages/rspack/tests/configCases/builtins/preset-env/index.js
Labels: team, release: bug fix

#2814 chore: 🤖 check node binding lock file
  .github/workflows/check-rs.yaml
Labels: team

#2812 feat: support complex magical comment `import(/* webpackChunkName: "/dist/d/js_d" */ "./d")`
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/bug_only_single_quote.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/bug_only_single_quote_js.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/normal.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/sub/fold.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/sub/single.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/index.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/normal.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/other.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/single_quote.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/sub_fold.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/test.config.json
Labels: release: feature

#2818 ci: share rust target directory in check-rs
  .github/workflows/check-rs.yaml
Labels: team

#2825 chore: remove ./x and Makefile and replace them with npm scripts
  .github/workflows/bench-history.yaml
  .github/workflows/release-canary.yml
  CONTRIBUTING.md
  Makefile
  package.json
  scripts/check_rust_dependency.js
  scripts/cmd.js
  x
Labels: team

#2826 chore: 🤖 optimize code completion of config.target
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
Labels: team

#2434 feat: preview command
  .changeset/poor-monkeys-shave.md
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/src/utils/options.ts
Labels: p3-nice-to-have, release: feature

#2830 chore: bump sugar_path to 0.0.12
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/rspack_core/src/options/output.rs
Labels: team

#2833 ci: 🐛CI ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL
  package.json
Labels: team

#2835 fix: support magic comment `import( /* webpackChunkName: "/user/[id]/page" */ './foo')` containing `[id]`
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/user/user/[id].js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/user/user/[id]/page/page.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/index.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/user/1.js
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/user/page/2.js
Labels: release: bug fix

#2834 fix: use webworker instead of web-worker in AvailableTarget type
  .changeset/real-eagles-do.md
  packages/rspack/src/config/types.ts
Labels: team, release: bug fix

#2827 chore: scripts should be ESM by default
  .github/workflows/check-changeset.yml
  .github/workflows/check-rs.yaml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  package.json
  scripts/build-npm.cjs
  scripts/check_changeset.cjs
  scripts/check_rust_dependency.cjs
  scripts/doctor.js
  scripts/doctor.mjs
  scripts/log.js
  scripts/meta/setup.js
  scripts/package.json
Labels: team

#2836 ci: install pnpm in benchmark CI
  .github/workflows/bench-history.yaml
  .github/workflows/bench.yaml
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: team

#2819 feat: implement built-in `BannerPlugin`
  .changeset/swift-apes-exist.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/utils/comment.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_banner/src/lib.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/builtins.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/util/fake.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/cases/hooks/processAssetsStageAdditions/index.js
  packages/rspack/tests/cases/hooks/processAssetsStageAdditions/webpack.config.js
  packages/rspack/tests/configCases/builtins/banner/a.js
  packages/rspack/tests/configCases/builtins/banner/b.js
  packages/rspack/tests/configCases/builtins/banner/index.js
  packages/rspack/tests/configCases/builtins/banner/webpack.config.js
Labels: team, release: feature

#2844 perf(rspack_core): reduce memory allocation when cloning RuntimeSpec
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_main_filename.rs
Labels: team, release: performance

#2817 chore: bump resolver and fix resolve.alias with resource query
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
Labels: team, p1-signifincant-downstream-blocker, release: bug fix

#2847 chore: 🤖 add common-check.yaml and fix ci
  .github/workflows/check-rs.yaml
  .github/workflows/common-check.yaml
  .typos.toml
Labels: team

#2840 chore: use `zx` to replace xtask
  .cargo/config.toml
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  benchcases/css-heavy/test.config.json
  benchcases/lodash-with-simple-css/test.config.json
  crates/rspack/benches/main.rs
  scripts/bench/make-threejs10x-production-config.js
  scripts/bench/make-threejs10x.js
  scripts/meta/check_is_workspace_root.js
  scripts/meta/setup.js
  scripts/package.json
  scripts/tsconfig.json
  xtask/Cargo.toml
  xtask/src/copy_three.rs
  xtask/src/main.rs
Labels: team

#2848 chore: 🤖 update benchmark link
  .github/workflows/common-check.yaml
  README.md
Labels: team

#2758 feat(hook): add optimizeModules hook
  .changeset/new-papayas-rest.md
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/tests/Compiler.test.ts
Labels: p2-signifincant, release: feature

#2839 feat: add ImportScriptsChunkLoadingPlugin
  .changeset/stupid-poets-brake.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js
  crates/rspack_plugin_runtime/src/basic_runtime_requirements.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_script_url.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_trusted_types_policy.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr_manifest.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/HotTestCases.template.ts
  packages/rspack/tests/HotTestCasesWebWorker.test.ts
  packages/rspack/tests/HotTestCasesWebWorkerWithIncRebuild.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/trusted-types/custom-policy-name/empty.js
  packages/rspack/tests/configCases/trusted-types/custom-policy-name/index.js
  packages/rspack/tests/configCases/trusted-types/custom-policy-name/webpack.config.js
  packages/rspack/tests/configCases/trusted-types/default-policy-name/empty.js
  packages/rspack/tests/configCases/trusted-types/default-policy-name/index.js
  packages/rspack/tests/configCases/trusted-types/default-policy-name/webpack.config.js
  packages/rspack/tests/configCases/trusted-types/no-policy-name/empty.js
  packages/rspack/tests/configCases/trusted-types/no-policy-name/index.js
  packages/rspack/tests/configCases/trusted-types/no-policy-name/webpack.config.js
  packages/rspack/tests/configCases/trusted-types/no-trusted-types/empty.js
  packages/rspack/tests/configCases/trusted-types/no-trusted-types/index.js
  packages/rspack/tests/configCases/trusted-types/no-trusted-types/webpack.config.js
  packages/rspack/tests/helpers/FakeDocument.js
  packages/rspack/tests/helpers/supportsWorker.js
Labels: team, release: feature

#2857 perf: avoid `clone` while matching `import.meta.webpackHot`
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: team, release: performance

#2808 feat: support loader-runner and pitching
  .changeset/eight-needles-film.md
  Cargo.lock
  crates/loader_runner/Cargo.toml
  crates/loader_runner/LICENSE
  crates/loader_runner/src/lib.rs
  crates/loader_runner/src/plugin.rs
  crates/loader_runner/src/runner.rs
  crates/loader_runner/tests/fixtures/file.png
  crates/loader_runner/tests/fixtures/simple.css
  crates/loader_runner/tests/fixtures/simple.js
  crates/loader_runner/tests/load_runner.rs
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_options/src/options/raw_target.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/loader/process_resource.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  packages/rspack/src/RuleSetCompiler.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/loader-runner/LoaderLoadingError.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/loadLoader.js
  packages/rspack/tests/configCases/loader/binary-with-source-map/empty-loader.js
  packages/rspack/tests/configCases/loader/pitching/index.js
  packages/rspack/tests/configCases/loader/pitching/lib.js
  packages/rspack/tests/configCases/loader/pitching/pitching-loader.js
  packages/rspack/tests/configCases/loader/pitching/simple-async-loader.js
  packages/rspack/tests/configCases/loader/pitching/simple-loader.js
  packages/rspack/tests/configCases/loader/pitching/webpack.config.js
Labels: team, release: feature

#2858 fix: sourcemap lost when enable builtins.banner
  .changeset/strong-peaches-warn.md
  crates/node_binding/src/js_values/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_banner/src/lib.rs
  packages/rspack/tests/configCases/builtins/banner/index.js
  packages/rspack/tests/configCases/builtins/banner/webpack.config.js
Labels: team, release: bug fix

#2862 feat: support `Rule.enforce`
  .changeset/yellow-apples-marry.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/hooks.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/loader/pre-post-loader/a.js
  packages/rspack/tests/configCases/loader/pre-post-loader/index.js
  packages/rspack/tests/configCases/loader/pre-post-loader/loader1.js
  packages/rspack/tests/configCases/loader/pre-post-loader/loader2.js
  packages/rspack/tests/configCases/loader/pre-post-loader/loader3.js
  packages/rspack/tests/configCases/loader/pre-post-loader/webpack.config.js
Labels: team, release: feature

#2865 refactor: `crates/rspack_plugin_javascript/src/visitors/dependency/util.rs`
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hmr_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: team

#2603 feat: chunk asset hook
  .vscode/settings.json
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/chunk.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/tests/configCases/hooks/check-asset/a.js
  packages/rspack/tests/configCases/hooks/check-asset/index.js
  packages/rspack/tests/configCases/hooks/check-asset/webpack.config.js
Labels: team, release: feature

#2859 fix: undefined reasons with stats.toJson
  .changeset/unlucky-geckos-hug.md
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_binding_options/src/options/raw_stats.rs
  crates/rspack_core/src/options/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/stats.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: bug fix

#2860 refactor(runtime): unwrap the function in ir
  crates/rspack/tests/fixtures/dynamic-import/expected/runtime.js
  crates/rspack_plugin_runtime/src/runtime/common/_export_star.js
  crates/rspack_plugin_runtime/src/runtime/common/_interop_require.js
  packages/rspack/tests/__snapshots__/HashTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#2869 fix(resolve): return query and fragment when alias target had
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  packages/rspack/tests/configCases/module/issue-2791/answer.js
  packages/rspack/tests/configCases/module/issue-2791/index.js
  packages/rspack/tests/configCases/module/issue-2791/webpack.config.js
Labels: team, release: bug fix

#2866 feat: support passing function to `externals`
  .changeset/new-apricots-glow.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_plugin_externals/src/plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/externals/array-externals/index.js
  packages/rspack/tests/configCases/externals/array-externals/webpack.config.js
Labels: team, release: feature

#2861 fix: remove`.d.ts` from the default `resolve.extensions`
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/Defaults.unittest.ts
Labels: release: breaking change, release: bug fix

#2872 refactor: align `starts_with` with the same semantics
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: team

#2874 fix: react refresh runtime inject for nest function call
  .changeset/light-students-jog.md
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
Labels: team, release: bug fix

#2875 perf: bailout if possible and ignore AstNode of type in `ReactRefreshUsageFinder`
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
Labels: team, release: performance

#2864 feat: add moduleAssets for stats
  .changeset/fair-buttons-fail.md
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/js_values/stats.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/stats.ts
  packages/rspack/tests/Compiler.test.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#2878 refactor: Make `check_changeset.cjs` ESM and use ZX
  .github/workflows/check-changeset.yml
  scripts/check_changeset.js
Labels: team

#2880 chore: should exit if the exitCode is not zero at `check_changeset.js`
  scripts/check_changeset.js
Labels: team

#2871 fix: optimize tree shaking swc/helpers
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-imported-unused/expected/main.js
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-imported-unused/index.js
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-imported-unused/source/index.js
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-imported-unused/source/package.json
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-imported-unused/test.config.json
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/expected/main.js
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/index.js
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/source/index.js
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/source/package.json
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/test.config.json
  crates/rspack/tests/tree-shaking/ts-target-es5/expected/main.js
  crates/rspack/tests/tree-shaking/ts-target-es5/index.ts
  crates/rspack/tests/tree-shaking/ts-target-es5/package.json
  crates/rspack/tests/tree-shaking/ts-target-es5/test.config.json
  crates/rspack_core/src/tree_shaking/debug_helper.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/visitors/inject_runtime_helper.rs
  crates/rspack_plugin_javascript/src/visitors/tree_shaking.rs
Labels: team, release: bug fix

#2876 chore: fix peerDep of rspack-plugin-html
  .changeset/stale-seas-poke.md
  packages/rspack-plugin-html/package.json
  pnpm-lock.yaml
Labels: team

#2883 fix(resolve): delay the directory check in exportsFieldPlugin
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
Labels: team, release: bug fix

#2887 chore: fix `make-threejs10x.js` script
  scripts/bench/make-threejs10x.js
Labels: team

#2867 feat: support inline loader
  .changeset/green-rocks-mate.md
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/loader.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack/tests/configCases/loader/pre-post-loader/index.js
  packages/rspack/tests/configCases/loader/pre-post-loader/webpack.config.js
Labels: release: feature

#2892 feat: 🎸 compiler. getCache
  .changeset/clever-students-shake.md
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/lib/Cache.js
  packages/rspack/src/lib/CacheFacade.js
  packages/rspack/src/lib/HookWebpackError.js
  packages/rspack/src/lib/WebpackError.js
  packages/rspack/src/lib/cache/getLazyHashedEtag.js
  packages/rspack/src/lib/cache/mergeEtags.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/tests/Compiler.test.ts
Labels: team, release: feature

#2784 chore: 🤖 bump napi retry
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/package.json
  pnpm-lock.yaml
  scripts/check_rust_dependency.cjs
Labels: team

#2894 perf: compose loaders on the native side
  .changeset/curly-peaches-study.md
  crates/node_binding/src/js_values/stats.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/loader.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/normal_module.rs
  packages/rspack/src/config/adapter-rule-use.ts
Labels: team, release: performance

#2898 fix: fix loader arguments
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/index.ts
Labels: team, release: bug fix

#2888 feat: require.resolve and require.resolveWeak for string literal
  .changeset/smart-seas-fix.md
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/require_resolve_dependency.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
  crates/rspack_plugin_split_chunks_new/src/plugin.rs
  packages/rspack/tests/cases/chunks/weak-dependencies/a.js
  packages/rspack/tests/cases/chunks/weak-dependencies/b.js
  packages/rspack/tests/cases/chunks/weak-dependencies/c.js
  packages/rspack/tests/cases/chunks/weak-dependencies/d.js
  packages/rspack/tests/cases/chunks/weak-dependencies/index.js
Labels: team, release: feature

#2911 fix: HMR scanner should only visit dependencies related to HMR
  crates/node_binding/binding.d.ts
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hmr_scanner.rs
Labels: team, release: bug fix

#2907 feat: enable compression and cache with `noEmitAssets: true`
  packages/rspack-dev-middleware/src/middleware.ts
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
Labels: team, release: feature

#2925 chore: add hmr for loader example
  examples/loader-compat/rspack.config.js
Labels: team

#2928 fix: benchmark CI failed.
  scripts/bench/make-threejs10x.js
Labels: team, release: bug fix

#2930 feat: support experiments.css
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/options/experiments.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
Labels: team, release: feature

#2934 fix: add missing `newSplitChunks` in schema.js
  packages/rspack/src/config/schema.js
Labels: team, release: bug fix
