Repository web-infra-dev/rspack, pull requests merged in 2023-07, with the labels that each got.

#3669 ci: refactor release-canary
  .github/workflows/release-canary.yml
  .github/workflows/reusable-build.yml
Labels: team

#3672 fix: hoist async or generate anonymous function decl at export decl
  crates/rspack/tests/tree-shaking/rollup-unused-called-import/expected/main.js
  crates/rspack/tests/tree-shaking/side-effects-analyzed/expected/main.js
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/expected/main.js
  crates/rspack/tests/tree-shaking/side-effects-two/expected/main.js
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/expected/main.js
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/a.js
  packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/b.js
  packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/c.js
  packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/d.js
  packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/index.js
Labels: team, release: bug fix

#3668 fix: panic when using worker with treeShaking enabled
  Cargo.lock
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/tree_shaking/js_module.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_plugin_worker/Cargo.toml
  examples/worker/rspack.config.js
  packages/rspack/tests/configCases/tree-shaking/new-url/b.js
  packages/rspack/tests/configCases/tree-shaking/new-url/b.worker.js
  packages/rspack/tests/configCases/tree-shaking/new-url/index.js
  webpack-test/configCases/worker/node-worker-hmr/test.filter.js
  webpack-test/configCases/worker/node-worker-named/test.filter.js
  webpack-test/configCases/worker/node-worker/test.filter.js
  webpack-test/configCases/worker/worker-contenthash/test.filter.js
Labels: team, release: bug fix

#3663 fix: reexport all as tree shaking
  crates/rspack/tests/tree-shaking/reexport-all-as/expected/main.js
  crates/rspack/tests/tree-shaking/reexport-all-as/package.json
  crates/rspack/tests/tree-shaking/reexport-all-as/package/autogen/a.js
  crates/rspack/tests/tree-shaking/reexport-all-as/package/autogen/b.js
  crates/rspack/tests/tree-shaking/reexport-all-as/package/autogen/c.js
  crates/rspack/tests/tree-shaking/reexport-all-as/package/autogen/index.js
  crates/rspack/tests/tree-shaking/reexport-all-as/package/package.json
  crates/rspack/tests/tree-shaking/reexport-all-as/package/src/index.js
  crates/rspack/tests/tree-shaking/reexport-all-as/src/index.js
  crates/rspack/tests/tree-shaking/reexport-all-as/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3664 test: add more E2E test case
  packages/playground/cases/css/import-empty-css-file/rspack.config.js
  packages/playground/cases/hooks/asset-emitted/index.test.ts
  packages/playground/cases/hooks/asset-emitted/rspack.config.js
  packages/playground/cases/hooks/asset-emitted/src/foo.js
  packages/playground/cases/hooks/asset-emitted/src/index.html
  packages/playground/cases/hooks/asset-emitted/src/index.js
  packages/playground/cases/html/cross-origin-loading/index.test.ts
  packages/playground/cases/html/cross-origin-loading/rspack.config.js
  packages/playground/cases/react/basic/rspack.config.js
  packages/playground/cases/react/tailwindcss/index.test.ts
  packages/playground/cases/react/tailwindcss/rspack.config.js
  packages/playground/cases/react/tailwindcss/src/App.css
  packages/playground/cases/react/tailwindcss/src/App.jsx
  packages/playground/cases/react/tailwindcss/src/index.html
  packages/playground/cases/react/tailwindcss/src/main.jsx
  packages/playground/cases/react/tailwindcss/tailwind.config.js
  packages/playground/fixtures/rspack.ts
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team

#3691 chore: uncomment worker example
  examples/worker/example.js
Labels: team

#3657 fix: npm package contains default_index.ejs file
  packages/rspack-plugin-html/package.json
Labels: release: bug fix

#3693 fix: rumtime_stmts => runtime_stmts
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
Labels: team, release: bug fix

#3699 ci: compile dependencies with optimization for faster tests
  .github/workflows/reusable-build.yml
Labels: team

#3631 feat: Disable source maps for rspack core
  packages/rspack/package.json
  packages/rspack/tsconfig.lib.json
Labels: release: feature

#3702 fix: resolve worker without extension
  crates/rspack_core/src/dependency/mod.rs
  packages/rspack/tests/configCases/worker/not-fully-specified-by-default/a.js
  packages/rspack/tests/configCases/worker/not-fully-specified-by-default/index.js
Labels: team, release: bug fix

#3652 test: banner hash plugin
  Cargo.lock
  crates/rspack_core/src/options/output.rs
  crates/rspack_hash/Cargo.toml
  crates/rspack_hash/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.e77efc5983febd0a.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.e77efc5983febd0a.html
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/lib/BannerPlugin.js
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/css-loader/css-modules-classname/index.js
  pnpm-lock.yaml
  webpack-test/configCases/plugins/banner-plugin-hashing/test.filter.js
  webpack-test/configCases/plugins/banner-plugin-hashing/webpack.config.js
Labels: team

#3706 fix(splitChunks): should validate `min_size` of `ModuleGroup` in the each end of round
  crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/another.js
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/index.js
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/shared.js
  packages/rspack/tests/configCases/split-chunks/issue-3646/webpack.config.js
Labels: team, release: bug fix

#3698 chore(examples): remove some duplicated files in vue folders
  examples/vue2/src/assets/App.vue
  examples/vue2/src/assets/components/HelloWorld.vue
  examples/vue2/src/assets/main.js
  examples/vue2/src/assets/style.css
  examples/vue3-vanilla/src/assets/style.css
Labels: team

#3703 fix: worker chunk looses runtime modules in incremental rebuild
  crates/rspack_core/src/cache/local/code_splitting_cache.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  examples/monaco-editor-js/index.js
  examples/monaco-editor-js/rspack.config.js
  examples/monaco-editor-ts-react/rspack.config.js
  examples/monaco-editor-ts-react/src/components/Editor.tsx
  examples/monaco-editor-ts-react/tsconfig.json
  packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/module.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/changed-file.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/compute.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/index.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/test.filter.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/worker.js
Labels: team, release: bug fix

#3697 fix(minifier): fix minifier options difference between minifications
  examples/angular/scripts/build.js
  packages/rspack-plugin-minify/src/index.js
Labels: team, release: bug fix

#3710 fix: `chunkhash` should be available in chunk context
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/asset.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/output.rs
  packages/rspack/src/util/index.ts
  packages/rspack/tests/configCases/output/chunk-filename/index.js
  packages/rspack/tests/configCases/output/chunk-filename/webpack.config.js
Labels: team, release: bug fix

#3708 fix: replace module refrence or __webpack_module__ to module argument
  crates/rspack_plugin_javascript/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
Labels: team, release: bug fix

#3696 chore: fix jest hastle warning
  packages/rspack/tests/cases/hooks/entryOption/package.json
  packages/rspack/tests/cases/hooks/stillValidModule/package.json
Labels: team

#3712 ci: remove setup-zip because it is no longer needed
  .github/workflows/reusable-build.yml
Labels: team

#3714 refactor(util): 1.better string concat performance 2.reduce code complexity 3.add comments
  Cargo.lock
  Cargo.toml
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/identifier.rs
Labels: team

#3711 fix: worker HMR
  crates/rspack_core/src/compiler/hmr.rs
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/shared.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/changed-file.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/chunk.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/chunkS.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/index.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/module.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/moduleA.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/moduleAs.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/moduleB.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/moduleBs.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/moduleS.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/test.filter.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/webpack.config.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/worker.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/workerA.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/workerB.js
  packages/rspack/tests/hotCases/worker/update-in-worker/changed-file.js
  packages/rspack/tests/hotCases/worker/update-in-worker/index.js
  packages/rspack/tests/hotCases/worker/update-in-worker/module.js
  packages/rspack/tests/hotCases/worker/update-in-worker/test.filter.js
  packages/rspack/tests/hotCases/worker/update-in-worker/worker.js
Labels: team, release: bug fix

#3716 chore: 🤖 revert file name generate logic
  crates/rspack_core/src/options/output.rs
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
Labels: team

#3683 refactor: set dependency id at dependency init
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_wasm/src/dependency.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#3719 refactor: use bit flags insert for RuntimeGlobals
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
Labels: team

#3721 feat: update all swc crates
  Cargo.lock
  Cargo.toml
  crates/rspack/tests/fixtures/dynamic-import/expected/main.js
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
  crates/rspack_plugin_javascript/tests/fixtures/builtins/define/expected/main.js
  crates/swc_plugin_import/Cargo.toml
  crates/swc_plugin_import/src/lib.rs
  crates/swc_plugin_import/src/visit.rs
  crates/swc_plugin_import/tests/fixtures/basic/actual.js
  crates/swc_plugin_import/tests/fixtures/basic/expected.js
  crates/swc_plugin_import/tests/fixtures/basic/option.json
  crates/swc_plugin_import/tests/fixtures/custom-name-fn/actual.js
  crates/swc_plugin_import/tests/fixtures/custom-name-fn/expected.js
  crates/swc_plugin_import/tests/fixtures/custom-name-fn/option.js
  crates/swc_plugin_import/tests/fixtures/custom-name-tpl/actual.js
  crates/swc_plugin_import/tests/fixtures/custom-name-tpl/expected.js
  crates/swc_plugin_import/tests/fixtures/custom-name-tpl/option.json
  crates/swc_plugin_import/tests/fixtures/custom-style-name/actual.js
  crates/swc_plugin_import/tests/fixtures/custom-style-name/expected.js
  crates/swc_plugin_import/tests/fixtures/custom-style-name/option.json
  crates/swc_plugin_import/tests/fixtures/ignore-es-component/actual.js
  crates/swc_plugin_import/tests/fixtures/ignore-es-component/expected.js
  crates/swc_plugin_import/tests/fixtures/ignore-es-component/option.json
  crates/swc_plugin_import/tests/fixtures/ignore-style-component/actual.js
  crates/swc_plugin_import/tests/fixtures/ignore-style-component/expected.js
  crates/swc_plugin_import/tests/fixtures/ignore-style-component/option.json
  crates/swc_plugin_import/tests/fixtures/no-default/actual.js
  crates/swc_plugin_import/tests/fixtures/no-default/expected.js
  crates/swc_plugin_import/tests/fixtures/no-default/option.json
  crates/swc_plugin_import/tests/fixtures/style-css/actual.js
  crates/swc_plugin_import/tests/fixtures/style-css/expected.js
  crates/swc_plugin_import/tests/fixtures/style-css/option.json
  crates/swc_plugin_import/tests/fixtures/style-fn/actual.js
  crates/swc_plugin_import/tests/fixtures/style-fn/expected.js
  crates/swc_plugin_import/tests/fixtures/style-fn/option.js
  crates/swc_plugin_import/tests/fixtures/style-library/actual.js
  crates/swc_plugin_import/tests/fixtures/style-library/expected.js
  crates/swc_plugin_import/tests/fixtures/style-library/option.json
  crates/swc_plugin_import/tests/fixtures/style-tpl/actual.js
  crates/swc_plugin_import/tests/fixtures/style-tpl/expected.js
  crates/swc_plugin_import/tests/fixtures/style-tpl/option.js
  crates/swc_plugin_import/tests/fixtures/style-true/actual.js
  crates/swc_plugin_import/tests/fixtures/style-true/expected.js
  crates/swc_plugin_import/tests/fixtures/style-true/option.json
  crates/swc_plugin_import/tests/main.rs
Labels: team, release: feature

#3621 feat: support function `Rule.use`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_testing/src/test_config.rs
  examples/loader-compat/rspack.config.js
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/tests/configCases/module/function-use/index.js
  packages/rspack/tests/configCases/module/function-use/index.less
  packages/rspack/tests/configCases/module/function-use/loader.js
  packages/rspack/tests/configCases/module/function-use/webpack.config.js
Labels: release: feature, need documentation

#3725 fix: non amd external break amd library
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  packages/rspack/tests/configCases/externals/non-amd-externals-amd/index.js
  packages/rspack/tests/configCases/externals/non-amd-externals-amd/test.config.js
  packages/rspack/tests/configCases/externals/non-amd-externals-amd/webpack.config.js
  packages/rspack/tests/configCases/library/amd-unnamed/index.js
Labels: team, release: bug fix

#3722 feat: implement statsPrinter hook and DefaultStatsPrinterPlugin
  examples/stats/index.html
  examples/stats/package.json
  examples/stats/rspack.config.js
  examples/stats/src/answer.js
  examples/stats/src/index.js
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/multiStats.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/StatsPrinter.ts
  packages/rspack/src/util/SizeFormatHelpers.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  pnpm-lock.yaml
Labels: release: feature

#3727 feat(rspack_plugin_css): add css/auto same as webpack
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/builtins/css-auto/index.css
  packages/rspack/tests/configCases/builtins/css-auto/index.js
  packages/rspack/tests/configCases/builtins/css-auto/index.module.css
  packages/rspack/tests/configCases/builtins/css-auto/webpack.config.js
Labels: team, release: feature, feat: css

#3733 chore: 🤖 enable tree shaking in bench
  scripts/bench/make-threejs10x-production-config.js
Labels: team

#3731 fix: react refresh in async entrypoint
  crates/rspack_plugin_javascript/src/ast/mod.rs
  crates/rspack_plugin_javascript/src/ast/parse.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
  packages/playground/cases/react/worker/index.test.ts
  packages/playground/cases/react/worker/rspack.config.js
  packages/playground/cases/react/worker/src/App.jsx
  packages/playground/cases/react/worker/src/Button.jsx
  packages/playground/cases/react/worker/src/index.html
  packages/playground/cases/react/worker/src/index.jsx
  packages/playground/cases/react/worker/src/worker.js
  packages/rspack-dev-client/package.json
  packages/rspack-dev-client/src/reactRefresh.js
  packages/rspack-dev-client/src/reactRefreshEntry.js
  packages/rspack-dev-client/tsconfig.json
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack/tsconfig.json
  packages/rspack/tsconfig.lib.json
Labels: team, release: bug fix

#3734 refactor(css): reduce code complexity
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/swc_css_compiler.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
Labels: team

#3739 fix: infer async module for EsmExport dependency
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  packages/rspack/tests/cases/wasm/export-imported-global/env.js
  packages/rspack/tests/cases/wasm/export-imported-global/index.js
  packages/rspack/tests/cases/wasm/export-imported-global/module.js
  packages/rspack/tests/cases/wasm/export-imported-global/module.wat
  packages/rspack/tests/cases/wasm/export-imported-global/webpack.config.js
  pnpm-lock.yaml
  webpack-test/cases/wasm/decoding/test.filter.js
  webpack-test/cases/wasm/export-imported-global/test.filter.js
  webpack-test/cases/wasm/finalize-exports-issue-8261/node_modules/side-effect-free/index.js
  webpack-test/cases/wasm/finalize-exports-issue-8261/node_modules/side-effect-free/module.wat
  webpack-test/cases/wasm/finalize-exports-issue-8261/node_modules/side-effect-free/package.json
  webpack-test/cases/wasm/finalize-exports-issue-8261/test.filter.js
  webpack-test/cases/wasm/global-refs-imported-global/test.filter.js
  webpack-test/cases/wasm/import-wasm-wasm/test.filter.js
  webpack-test/cases/wasm/imported-global-preserve-ordering/test.filter.js
  webpack-test/cases/wasm/imported-global-preserve-type/test.filter.js
  webpack-test/cases/wasm/imports-circular/test.filter.js
  webpack-test/cases/wasm/imports-complex-types/test.filter.js
  webpack-test/cases/wasm/imports-many-direct/test.filter.js
  webpack-test/cases/wasm/imports-multiple/test.filter.js
  webpack-test/cases/wasm/imports/test.filter.js
  webpack-test/cases/wasm/memory/test.filter.js
  webpack-test/cases/wasm/order/test.filter.js
  webpack-test/cases/wasm/simple/test.filter.js
  webpack-test/cases/wasm/table/test.filter.js
  webpack-test/cases/wasm/two-files-loader/test.filter.js
  webpack-test/cases/wasm/unused-export/test.filter.js
  webpack-test/cases/wasm/v128/test.filter.js
  webpack-test/cases/wasm/wasm-explorer-examples-async/node_modules/env.js
  webpack-test/cases/wasm/wasm-explorer-examples-async/test.filter.js
  webpack-test/cases/wasm/wasm-explorer-examples-sync/node_modules/env.js
  webpack-test/cases/wasm/wasm-explorer-examples-sync/test.filter.js
  webpack-test/package.json
Labels: team, release: bug fix

#3743 chore: temporary comment worker e2e
  packages/playground/cases/react/worker/index.test.ts
  packages/playground/cases/react/worker/src/App.jsx
Labels: team

#3730 chore: release canary with x86_64-unknown-linux-gnu for Cloud IDE
  .github/workflows/release-canary.yml
Labels: team

#3741 test: enable more webpack loader test cases
  webpack-test/TestCases.template.js
  webpack-test/cases/loaders/_css/node_modules/resources-module/import2.less
  webpack-test/cases/loaders/_css/node_modules/resources-module/stylesheet-import2.css
  webpack-test/cases/loaders/css-loader/test.filter.js
  webpack-test/cases/loaders/emit-file/test.filter.js
  webpack-test/cases/loaders/issue-10725/test.filter.js
  webpack-test/cases/loaders/issue-2299/test.filter.js
  webpack-test/cases/loaders/issue-4959/test.filter.js
  webpack-test/cases/loaders/less-loader/node_modules/resources-module/import2.less
  webpack-test/cases/loaders/less-loader/node_modules/resources-module/stylesheet-import2.css
  webpack-test/cases/loaders/less-loader/test.filter.js
  webpack-test/cases/loaders/module-description-file/node_modules/testloader/lib/loader-indirect.js
  webpack-test/cases/loaders/module-description-file/node_modules/testloader/lib/loader.js
  webpack-test/cases/loaders/module-description-file/node_modules/testloader/lib/loader.webpack-loader.js
  webpack-test/cases/loaders/module-description-file/node_modules/testloader/lib/loader2.web-loader.js
  webpack-test/cases/loaders/module-description-file/node_modules/testloader/lib/loader3.loader.js
  webpack-test/cases/loaders/module-description-file/node_modules/testloader/package.json
  webpack-test/cases/loaders/module-description-file/test.filter.js
  webpack-test/cases/loaders/no-string/test.filter.js
  webpack-test/cases/loaders/query/index.js
  webpack-test/cases/loaders/query/test.filter.js
  webpack-test/cases/loaders/resolve/test.filter.js
  webpack-test/cases/loaders/utils/test.filter.js
  webpack-test/configCases/loaders/hot-in-context/test.filter.js
  webpack-test/configCases/loaders/hot-in-context/webpack.config.js
  webpack-test/configCases/loaders/issue-3320/node_modules/any-loader.js
  webpack-test/configCases/loaders/issue-3320/test.filter.js
  webpack-test/configCases/loaders/issue-9053/node_modules/loader1.js
  webpack-test/configCases/loaders/issue-9053/node_modules/loader2.js
  webpack-test/configCases/loaders/issue-9053/node_modules/loader3.js
  webpack-test/configCases/loaders/issue-9053/test.filter.js
  webpack-test/configCases/loaders/pr-14384/PluginWithLoader.js
  webpack-test/configCases/loaders/pr-14384/test.filter.js
Labels: team

#3746 chore: remove version in stats test snapshot
  packages/rspack/tests/Stats.test.ts
Labels: team

#3749 fix(rspack_core): context delete file
  crates/rspack_core/src/context_module.rs
  packages/playground/cases/context/delete-file/index.test.ts
  packages/playground/cases/context/delete-file/rspack.config.js
  packages/playground/cases/context/delete-file/src/index.html
  packages/playground/cases/context/delete-file/src/index.js
  packages/playground/cases/context/delete-file/src/mod1.js
  packages/playground/cases/context/delete-file/src/mod2.js
Labels: release: bug fix

#3751 refactor: rename `CodeGeneratableDependency` to `DependencyTemplate` for more consistency
  crates/rspack_core/src/dependency/code_generatable_dependency.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
Labels: team

#3752 chore: serialize the graph for better debugging.
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol_graph.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_identifier/Cargo.toml
  crates/rspack_identifier/src/lib.rs
  crates/rspack_symbol/src/lib.rs
Labels: team

#3728 chore: bump Rust dependencies
  Cargo.lock
  Cargo.toml
  crates/cargo-rst/Cargo.toml
  crates/node_binding/Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_build/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_hash/Cargo.toml
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_dev_friendly_split_chunks/Cargo.toml
  crates/rspack_plugin_entry/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_regex/Cargo.toml
  crates/rspack_symbol/Cargo.toml
  crates/swc_plugin_import/Cargo.toml
Labels: team

#3756 feat(ast_viewer): support contexting in ast viewer
  crates/rspack_ast_viewer/Cargo.toml
  crates/rspack_ast_viewer/src/main.rs
Labels: team, release: feature

#3757 fix: should escape css url content
  crates/rspack_plugin_css/src/dependency/url.rs
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/css/urls/index.js
  packages/rspack/tests/configCases/css/urls/urls.css
Labels: team, release: bug fix

#3758 chore: add @ScriptedAlchemy to Rspack core
  GOVERNANCE.md
Labels: team

#3763 fix: react refresh module id
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
  packages/playground/cases/react/basic/index.test.ts
  packages/playground/cases/react/basic/react-refresh.js
  packages/playground/cases/react/basic/rspack.config.js
  packages/playground/cases/react/basic/src/App.jsx
  packages/playground/cases/react/basic/src/SameExportName1.jsx
  packages/playground/cases/react/basic/src/SameExportName2.jsx
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#3502 feat: support ensure_chunk_conditions_plugin
  .vscode/settings.json
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_ensure_chunk_conditions/Cargo.toml
  crates/rspack_plugin_ensure_chunk_conditions/LICENSE
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
  packages/rspack/tests/configCases/externals/external-module-in-main-chunk-amd/index.js
  packages/rspack/tests/configCases/externals/external-module-in-main-chunk-amd/webpack.config.js
Labels: on hold, release: feature

#3779 fix: avoid rspack_plugin_ensure_chunk_conditions loop
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
Labels: team, release: bug fix

#3782 fix: hmr should work for inject css link to body
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading.js
  packages/playground/cases/css/render-to-body/index.test.ts
  packages/playground/cases/css/render-to-body/rspack.config.js
  packages/playground/cases/css/render-to-body/src/index.css
  packages/playground/cases/css/render-to-body/src/index.html
  packages/playground/cases/css/render-to-body/src/index.js
Labels: team, release: bug fix

#3788 ci: release canary without debug mode because binary size is too big to upload (>1G)
  .github/workflows/release-canary.yml
Labels: team

#3786 fix(core): Typo in html builtins types
  packages/rspack/src/config/zod/builtins.ts
Labels: release: bug fix

#3783 feat(splitChunks): support `splitChunks.{cacheGroup}.idHint`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  packages/rspack/src/config/zod/optimization/split-chunks.ts
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/index.js
Labels: team, release: feature

#3775 feat(core): add test/include/exclude options to builtins.minifyOptions
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/ast/minify.rs
  crates/rspack_plugin_javascript/src/ast/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_regex/src/algo.rs
  crates/rspack_regex/src/lib.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/builtins.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/builtins/minify-exclude/a.js
  packages/rspack/tests/configCases/builtins/minify-exclude/b.js
  packages/rspack/tests/configCases/builtins/minify-exclude/index.js
  packages/rspack/tests/configCases/builtins/minify-exclude/webpack.config.js
  packages/rspack/tests/configCases/builtins/minify-include/a.js
  packages/rspack/tests/configCases/builtins/minify-include/b.js
  packages/rspack/tests/configCases/builtins/minify-include/index.js
  packages/rspack/tests/configCases/builtins/minify-include/webpack.config.js
  packages/rspack/tests/configCases/builtins/minify-test/a.js
  packages/rspack/tests/configCases/builtins/minify-test/a2.js
  packages/rspack/tests/configCases/builtins/minify-test/b.js
  packages/rspack/tests/configCases/builtins/minify-test/index.js
  packages/rspack/tests/configCases/builtins/minify-test/webpack.config.js
Labels: release: feature

#3791 chore: bump swc version
  Cargo.lock
  Cargo.toml
Labels: team

#3794 fix: compilation hash should hash hot index to avoid hmr loop
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.45c5ae0f4b61cf7f.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.45c5ae0f4b61cf7f.html
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/hotCases/hash/hot-index/changed-file.js
  packages/rspack/tests/hotCases/hash/hot-index/file.js
  packages/rspack/tests/hotCases/hash/hot-index/index.js
Labels: team, release: bug fix

#3789 fix: tree shaking with a cyclic reference
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/expected/main.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/package.json
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/App.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/containers/containers.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/containers/index.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/containers/package.json
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/containers/page-container/index.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/containers/platform-container/index.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/src/index.js
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/test.config.json
  crates/rspack/tests/tree-shaking/export_star/expected/main.js
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3682 feat: support stats option "source"
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/stats.ts
  packages/rspack/src/stats.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/library/esmodule/index.js
  packages/rspack/tests/statsCases/simple-module-source/index.js
  packages/rspack/tests/statsCases/simple-module-source/raw.png
  packages/rspack/tests/statsCases/simple-module-source/stringModule.js
  packages/rspack/tests/statsCases/simple-module-source/webpack.config.js
Labels: release: feature

#3797 fix: shorthand filed symbol unsed
  crates/rspack/tests/tree-shaking/class-extend/app.js
  crates/rspack/tests/tree-shaking/class-extend/expected/main.js
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
Labels: team, release: bug fix

#3717 feat(packages/rspack): add version check for binding
  packages/rspack/src/chunk_group.ts
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/util/bindingVersionCheck.ts
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/normalization.ts
  packages/rspack/src/watching.ts
Labels: release: feature

#3800 feat: nested import tree shaking
  crates/bench/src/main.rs
  crates/rspack/tests/tree-shaking/export_star/expected/main.js
  crates/rspack/tests/tree-shaking/reexport-all-as/expected/main.js
  crates/rspack/tests/tree-shaking/reexport-all-as/package/autogen/a.js
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol_graph.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_symbol/src/lib.rs
  examples/basic/src/lib.js
Labels: team, release: feature

#3807 ci: split `cargo check` and `cargo test` into two jobs
  .github/workflows/ci.yml
Labels: team

#3801 fix: react class component hmr
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
  packages/playground/cases/react/class-component/index.test.ts
  packages/playground/cases/react/class-component/react-refresh.js
  packages/playground/cases/react/class-component/rspack.config.js
  packages/playground/cases/react/class-component/src/App.jsx
  packages/playground/cases/react/class-component/src/index.html
  packages/playground/cases/react/class-component/src/index.jsx
Labels: team, release: bug fix

#3806 chore: remove rspack_build
  Cargo.lock
  crates/rspack_build/Cargo.toml
  crates/rspack_build/README.md
  crates/rspack_build/fixture/app.js
  crates/rspack_build/fixture/test.config.json
  crates/rspack_build/src/main.rs
Labels: team

#3804 fix: fix css semicolon replacement
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/expected/main.css
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/tests/fixtures/custom/http_import/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-charset/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/shared-import/expected/main.css
  packages/playground/cases/css/import-double-css-files-with-empty/index.test.ts
  packages/playground/cases/css/import-double-css-files-with-empty/rspack.config.js
  packages/playground/cases/css/import-double-css-files-with-empty/src/_empty.css
  packages/playground/cases/css/import-double-css-files-with-empty/src/body.css
  packages/playground/cases/css/import-double-css-files-with-empty/src/empty.css
  packages/playground/cases/css/import-double-css-files-with-empty/src/index.html
  packages/playground/cases/css/import-double-css-files-with-empty/src/index.js
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/configCases/source-map/verify-bundle-css-minify/entry.css
  packages/rspack/tests/configCases/source-map/verify-bundle-css-minify/index.js
  packages/rspack/tests/configCases/source-map/verify-bundle-css/entry.css
Labels: team, release: bug fix

#3817 fix: react refresh false shouldn't inject react refresh runtime
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  packages/rspack/tests/configCases/builtins/react-refresh-false/index.jsx
  packages/rspack/tests/configCases/builtins/react-refresh-false/webpack.config.js
Labels: team, release: bug fix

#3822 fix: original source should respect to the module type
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_loader_runner/src/content.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/source-map/cheap/index.js
Labels: team, release: bug fix

#3808 refactor: assign dep id for each symbol.
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/symbol_graph.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_symbol/Cargo.toml
  crates/rspack_symbol/LICENSE
Labels: team

#3819 chore: use v0.x.y instead of 0.x.y for release tag
  scripts/release/publish.mjs
Labels: team

#3818 fix: css asset tree shaking
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_asset/src/lib.rs
  packages/rspack/tests/configCases/tree-shaking/asset-is-dep-of-css-source/a.svg
  packages/rspack/tests/configCases/tree-shaking/asset-is-dep-of-css-source/index.css
  packages/rspack/tests/configCases/tree-shaking/asset-is-dep-of-css-source/index.js
  packages/rspack/tests/configCases/tree-shaking/asset-is-dep-of-css-source/package.json
  packages/rspack/tests/configCases/tree-shaking/asset-is-dep-of-css-source/webpack.config.js
Labels: team, release: bug fix

#3780 fix: error in plugin apply is not be reported when using cli
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/tests/build/plugin-apply-error/plugin-apply-error.test.ts
  packages/rspack-cli/tests/build/plugin-apply-error/rspack.config.js
  packages/rspack-cli/tests/build/plugin-apply-error/src/index.js
  packages/rspack-cli/tsconfig.json
  packages/rspack/src/rspack.ts
Labels: team, release: bug fix

#3833 test: basic webpack side effects and treeshaking tests
  webpack-test/TestCases.template.js
  webpack-test/cases/optimize/concat-star-import/node_modules/cmodule/index.js
  webpack-test/cases/optimize/concat-star-import/node_modules/cmodule/package.json
  webpack-test/cases/optimize/concat-star-import/test.filter.js
  webpack-test/cases/optimize/many-exports-100/test.filter.js
  webpack-test/cases/optimize/many-exports-120/test.filter.js
  webpack-test/cases/optimize/many-exports-40/test.filter.js
  webpack-test/cases/optimize/node_modules/pmodule/a.js
  webpack-test/cases/optimize/node_modules/pmodule/b.js
  webpack-test/cases/optimize/node_modules/pmodule/c.js
  webpack-test/cases/optimize/node_modules/pmodule/index.js
  webpack-test/cases/optimize/node_modules/pmodule/package.json
  webpack-test/cases/optimize/node_modules/pmodule/tracker.js
  webpack-test/cases/optimize/side-effects-all-used/test.filter.js
  webpack-test/cases/optimize/side-effects-simple-unused/test.config.js
  webpack-test/cases/optimize/side-effects-simple-unused/test.filter.js
  webpack-test/cases/optimize/tree-shaking-star/test.filter.js
  webpack-test/cases/optimize/tree-shaking-star2/test.filter.js
  webpack-test/configCases/inner-graph/defaultArrow/test.filter.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/nmodule/a.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/nmodule/b.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/nmodule/c.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/nmodule/index.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/nmodule/package.json
  webpack-test/configCases/side-effects/side-effects-override/node_modules/nmodule/tracker.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/pmodule/a.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/pmodule/b.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/pmodule/c.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/pmodule/index.js
  webpack-test/configCases/side-effects/side-effects-override/node_modules/pmodule/package.json
  webpack-test/configCases/side-effects/side-effects-override/node_modules/pmodule/tracker.js
  webpack-test/configCases/side-effects/side-effects-override/test.filter.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/boolean-value-module/a.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/boolean-value-module/b.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/boolean-value-module/c.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/boolean-value-module/index.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/boolean-value-module/package.json
  webpack-test/configCases/side-effects/side-effects-values/node_modules/boolean-value-module/tracker.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/glob-value-module/a.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/glob-value-module/b.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/glob-value-module/index.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/glob-value-module/package.json
  webpack-test/configCases/side-effects/side-effects-values/node_modules/glob-value-module/src/a.js
  webpack-test/configCases/side-effects/side-effects-values/node_modules/glob-value-module/tracker.js
  webpack-test/configCases/side-effects/side-effects-values/test.filter.js
Labels: team

#3835 chore(types): should not return null when only called rspack with one parameter
  packages/rspack/src/rspack.ts
Labels: team

#3844 feat: add some exports info api
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
Labels: team, release: feature

#3847 fix: export imported a import declaration with all as.
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/answer.js
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/expected/main.js
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/index.js
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/lib.js
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/test.config.json
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/test.js
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
Labels: team, release: bug fix

#3855 feat: implement dependency resource_identifier
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#3809 fix: banner shouldn't be injected to asset
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/builtins/banner/empty.png
  packages/rspack/tests/configCases/builtins/banner/index.js
  packages/rspack/tests/configCases/builtins/banner/webpack.config.js
  packages/rspack/tests/statsCases/auxiliary-files-test/index.js
  packages/rspack/tests/statsCases/auxiliary-files-test/raw.png
  packages/rspack/tests/statsCases/auxiliary-files-test/stringModule.js
  packages/rspack/tests/statsCases/auxiliary-files-test/webpack.config.js
Labels: team, release: bug fix

#3856 fix: generate correct name for library umd define
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  packages/rspack/tests/configCases/library/umd-named-define/index.js
  packages/rspack/tests/configCases/library/umd-named-define/webpack.config.js
Labels: team, release: bug fix

#3857 fix: should replace _webpack_require to __nested_webpack_require_ at …
  crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
  packages/rspack/tests/cases/parsing/nested-webpack-require/index.js
Labels: team, release: bug fix

#3859 perf: reduce dependency clone at make
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: performance

#3839 chore: use dep_id instead of module id
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/tree_shaking/analyzer.rs
  crates/rspack_core/src/tree_shaking/asset_module.rs
  crates/rspack_core/src/tree_shaking/js_module.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#3869 refactor: remove ctxt of variable in import map
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
Labels: team
