Repository web-infra-dev/rspack, pull requests merged in 2023-03, with the labels that each got.

#2224 ci: team-label action
  .github/teams.yml
  .github/workflows/team-label.yaml
Labels: team

#2217 feat: array type for externals
  .changeset/nasty-taxis-protect.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/rspack.ts
Labels: team

#2226 fix(plugin-html): fix template with process
  .changeset/smart-starfishes-perform.md
  packages/rspack-plugin-html/src/template.ts
  packages/rspack-plugin-html/tests/basic.spec.js
  packages/rspack-plugin-html/tests/fixtures/issue2179.html
Labels: team

#2230 feat(cli): support config return promise
  .changeset/silent-falcons-joke.md
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
  packages/rspack-cli/tests/build/basic/entry.function.js
  packages/rspack-cli/tests/build/basic/entry.promise.js
  packages/rspack/src/util/index.ts
Labels: team

#2232 refactor: ast -> AST in readme
  README.md
Labels: team

#2172 fix: Avoid reporting warning the export when src module format is none esm
  .changeset/rude-dryers-grab.md
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_error/tests/fixtures.rs
  crates/rspack_error/tests/fixtures/export_star_error/bar.js
  crates/rspack_error/tests/fixtures/export_star_error/fixtures__export_star_error.snap
  crates/rspack_error/tests/fixtures/export_star_error/foo.js
  crates/rspack_error/tests/fixtures/export_star_error/index.js
  crates/rspack_error/tests/fixtures/export_star_error/result.js
  crates/rspack_error/tests/fixtures/export_star_error/test.config.json
  crates/rspack_error/tests/fixtures/should_not_warn_when_commjs_not_export/a.js
  crates/rspack_error/tests/fixtures/should_not_warn_when_commjs_not_export/fixtures__should_not_warn_when_commjs_not_export.snap
  crates/rspack_error/tests/fixtures/should_not_warn_when_commjs_not_export/index.js
  crates/rspack_error/tests/fixtures/should_not_warn_when_commjs_not_export/test.config.json
  crates/rspack_error/tests/fixtures/should_not_warn_when_src_format_is_umd/a.js
  crates/rspack_error/tests/fixtures/should_not_warn_when_src_format_is_umd/fixtures__should_not_warn_when_src_format_is_umd.snap
  crates/rspack_error/tests/fixtures/should_not_warn_when_src_format_is_umd/index.js
  crates/rspack_error/tests/fixtures/should_not_warn_when_src_format_is_umd/test.config.json
  crates/rspack_error/tests/fixtures/should_warn_when_esm_not_export/a.js
  crates/rspack_error/tests/fixtures/should_warn_when_esm_not_export/fixtures__should_warn_when_esm_not_export.snap
  crates/rspack_error/tests/fixtures/should_warn_when_esm_not_export/index.js
  crates/rspack_error/tests/fixtures/should_warn_when_esm_not_export/test.config.json
Labels: team

#2216 refactor: runtime module
  .changeset/light-planets-cheat.md
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_runtime/src/basic_runtime_requirements.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/ensure_chunk.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_update_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_full_hash.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_main_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/global.rs
  crates/rspack_plugin_runtime/src/runtime_module/has_own_property.rs
  crates/rspack_plugin_runtime/src/runtime_module/hot_module_replacement.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  crates/rspack_plugin_runtime/src/runtime_module/normal.rs
  crates/rspack_plugin_runtime/src/runtime_module/on_chunk_loaded.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#2235 fix: try rs test run in single thread
  .github/workflows/check-rs.yaml
  x
Labels: team

#2233 fix: normalize identifier for externalsType umd
  .changeset/yellow-keys-breathe.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/utils/identifier.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/umd_library_plugin.rs
Labels: team

#2239 feat: externalsPresets.node
  .changeset/lemon-pillows-fry.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/node/NodeTargetPlugin.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/WatchTestCases.template.ts
  packages/rspack/tests/case.template.ts
  packages/rspack/tests/cases/chunks/_import/webpack.config.js
  packages/rspack/tests/configCases/externals/array-externals/index.js
  packages/rspack/tests/configCases/externals/array-externals/inject.js
  packages/rspack/tests/configCases/externals/array-externals/webpack.config.js
  packages/rspack/tests/configCases/externals/prefer-provided-over-built-in/index.js
  packages/rspack/tests/configCases/externals/prefer-provided-over-built-in/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-terser/index.js
  packages/rspack/tests/configCases/rule-set/test/index.js
  packages/rspack/tests/configCases/source-map/basic/webpack.config.js
  packages/rspack/tests/configCases/source-map/cheap-module/webpack.config.js
  packages/rspack/tests/configCases/source-map/cheap/webpack.config.js
  packages/rspack/tests/configCases/source-map/eval-source-map/webpack.config.js
  packages/rspack/tests/configCases/source-map/hidden/webpack.config.js
  packages/rspack/tests/configCases/source-map/inline/webpack.config.js
  packages/rspack/tests/configCases/source-map/nosources/webpack.config.js
  packages/rspack/tests/configCases/source-map/relative-source-map-path/webpack.config.js
  packages/rspack/tests/configCases/source-map/verify-bundle-css-minify/webpack.config.js
  packages/rspack/tests/configCases/source-map/verify-bundle-css/webpack.config.js
  packages/rspack/tests/configCases/source-map/verify-css-js-mix/webpack.config.js
  packages/rspack/tests/configCases/source-map/verify-es6-minify/webpack.config.js
  packages/rspack/tests/configCases/source-map/verify-es6/webpack.config.js
  packages/rspack/tests/configCases/target/node/webpack.config.js
Labels: team

#2243 fix: postcss modules warning when using postcss-loader
  .changeset/big-maps-fly.md
  crates/rspack_plugin_css/src/plugin.rs
Labels: team

#2250 fix: runtime module cacheable
  .changeset/olive-spoons-kick.md
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_full_hash.rs
  packages/rspack/tests/cases/module-variables/webpack-hash/index.js
Labels: team

#2204 chore: bump swc
  .github/workflows/check-rs.yaml
  Cargo.lock
  Cargo.toml
  crates/bench/Cargo.toml
  crates/cargo-rst/Cargo.toml
  crates/loader_runner/Cargo.toml
  crates/loader_runner/tests/load_runner.rs
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack/tests/tree-shaking/basic/expected/main.js
  crates/rspack/tests/tree-shaking/default_export/expected/main.js
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/expected/main.js
  crates/rspack_ast_viewer/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_build/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_database/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_futures/Cargo.toml
  crates/rspack_identifier/Cargo.toml
  crates/rspack_ids/Cargo.toml
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_napi_shared/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/visitors/mod.rs
  crates/rspack_plugin_dev_friendly_split_chunks/Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/visitors/asset.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/utils.rs
  crates/rspack_plugin_javascript/src/visitors/format.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs
  crates/rspack_plugin_json/Cargo.toml
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_regex/Cargo.toml
  crates/rspack_symbol/Cargo.toml
  crates/rspack_testing/Cargo.toml
  crates/rspack_tracing/Cargo.toml
  crates/rspack_util/Cargo.toml
  scripts/update_swc_version.js
Labels: team

#2186 fix(dev-middleware): compatibility with native node handler
  .changeset/eleven-falcons-approve.md
  packages/rspack-dev-middleware/src/middleware.ts
Labels: Ready to merge

#2246 chore: 🤖 do not cancel task in main branch
  .github/workflows/bench.yaml
  .github/workflows/check-rs.yaml
Labels: team

#2265 refactor(rspack_core): refactor ModuleGraph
  crates/node_binding/src/js_values/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/common_js_require_context_dependency.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/css/import.rs
  crates/rspack_core/src/dependency/css/url.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/import_context_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/require_context_dependency.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require.rs
  crates/rspack_plugin_javascript/src/dependency/esm/dynamic_import.rs
  crates/rspack_plugin_javascript/src/dependency/esm/export.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/visitors/format.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
Labels: team

#2276 revert: downgrade swc version
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/visitors/format.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs
Labels: team

#2286 chore: fix lockfile problem
  pnpm-lock.yaml
Labels: team

#2282 fix: fix webpack-sources interoperation
  .changeset/stale-schools-promise.md
  crates/node_binding/src/js_values/source.rs
  packages/rspack/src/util/createSource.ts
  packages/rspack/tests/configCases/asset/issue#2283/img.png
  packages/rspack/tests/configCases/asset/issue#2283/index.js
  packages/rspack/tests/configCases/asset/issue#2283/webpack.config.js
Labels: team

#2279 refactor module graph lookups
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team

#2267 feat: 🤖 finish defineConfig
  .changeset/ninety-terms-build.md
  packages/rspack-cli/src/index.ts
  packages/rspack-cli/src/rspack-cli.ts
Labels: team

#2292 fix: contenthash should care about ChunkGraphModule#id
  .changeset/seven-dancers-melt.md
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin.rs
Labels: team

#2146 feat(create): support package manager detect in create-rspack command
  .changeset/tidy-donkeys-remain.md
  packages/create-rspack/index.js
Labels: Ready to merge

#2300 fix(ci): clean up check-rs, attempt to fix ci cache taking 1G
  .github/workflows/check-rs.yaml
Labels: team

#2305 feat: release action support only create release tag
  .github/workflows/release-pull-request.yml
  .github/workflows/release.yml
Labels: team

#2307 ci: combine lint, format and test to save ci time and cache
  .github/workflows/check-rs.yaml
Labels: team

#2296 fix: mjs file node mode interop
  .changeset/loud-pianos-smash.md
  crates/rspack_core/src/ast/javascript.rs
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/strict.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/cases/interop/node-mode/index.js
  packages/rspack/tests/cases/interop/node-mode/lib.mjs
  packages/rspack/tests/cases/interop/node-mode/value.js
Labels: team

#2310 chore: make solid example refresh happen
  examples/solid/package.json
  examples/solid/src/App.jsx
  examples/solid/src/Message.jsx
  pnpm-lock.yaml
Labels: team

#2314 fix: fix identifier of missing module
  .changeset/popular-walls-accept.md
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#2306 fix(html): builtins.html minify not work
  .changeset/stale-lizards-allow.md
  crates/rspack_plugin_html/src/parser.rs
  packages/rspack/tests/configCases/builtins/html-minify/index.html
  packages/rspack/tests/configCases/builtins/html-minify/index.js
  packages/rspack/tests/configCases/builtins/html-minify/webpack.config.js
Labels: team

#2244 fix: create-rspack default command conflict with help command
  .changeset/flat-parrots-invite.md
  packages/create-rspack/index.js
Labels: Ready to merge

#2308 ci: cache pnpm in check-rs
  .github/workflows/check-rs.yaml
Labels: team

#2326 Revert "ci: cache pnpm in check-rs (#2308)"
  .github/workflows/check-rs.yaml
Labels: team

#2325 fix(cli): set stats default to errors-warning to avoid server info flushhed by module stats
  .changeset/happy-berries-wonder.md
  packages/rspack-cli/src/rspack-cli.ts
Labels: team

#2329 fix: css hmr memory middleware
  .changeset/polite-rice-search.md
  packages/rspack-dev-middleware/src/middleware.ts
Labels: team

#2303 feat: stats.outputPath
  .changeset/forty-cougars-develop.md
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/stats.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#2342 feat(runtime): support `__filename` polyfill
  .changeset/soft-doors-guess.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_node.rs
  crates/rspack_core/src/options/node.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/cases/module-variables/dirname-mock/index.js
  packages/rspack/tests/cases/module-variables/dirname-mock/webpack.config.js
  packages/rspack/tests/cases/module-variables/dirname-true/child/child.js
  packages/rspack/tests/cases/module-variables/dirname-true/index.js
  packages/rspack/tests/cases/module-variables/dirname-true/webpack.config.js
  packages/rspack/tests/cases/module-variables/dirname-web-default/index.js
Labels: team

#2357 ci: add write permission to team-label
  .github/workflows/team-label.yaml
Labels: team

#2330 fix: Tailwind CSS HMR not work
  .changeset/eighty-bugs-cry.md
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/snapshot/manager.rs
  crates/rspack_core/src/compiler/hmr.rs
Labels: team

#2348 feat: expose description data to resolve_data
  Cargo.lock
  Cargo.toml
  crates/loader_runner/Cargo.toml
  crates/loader_runner/src/runner.rs
  crates/loader_runner/tests/load_runner.rs
  crates/node_binding/Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/cache/occasion/resolve_module.rs
  crates/rspack_core/src/compiler/resolver.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/test.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/utils/hooks.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_sass/tests/fixtures.rs
Labels: team

#2126 feat(builtin.copy): add simple ignore option
  .changeset/brown-gifts-retire.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_plugin_copy/src/lib.rs
Labels: team

#2369 chore: add rspack feishu group
  README.zh-CN.md
Labels: team

#2349 chore: upgrade webpack-dev-server & webpack-dev-middleware
  .changeset/breezy-parents-reflect.md
  .changeset/strange-shirts-impress.md
  packages/rspack-dev-middleware/package.json
  packages/rspack-dev-server/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#2367 feat: parse with comments
  crates/rspack_core/src/ast/javascript.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/ast/parse.rs
  crates/rspack_plugin_javascript/src/plugin.rs
Labels: team

#2383 fix(core): fix regex external not working
  .changeset/clever-pianos-help.md
  crates/rspack_binding_options/src/options/raw_external.rs
  packages/rspack/tests/configCases/externals/array-externals/index.js
  packages/rspack/tests/configCases/externals/array-externals/inject.js
  packages/rspack/tests/configCases/externals/array-externals/webpack.config.js
Labels: team

#2380 fix: :bug: fix parsing error in html template path
  .changeset/friendly-peas-fly.md
  crates/rspack_plugin_html/src/plugin.rs
Labels: team

#2387 fix: progress plugin percent symbol
  .changeset/swift-queens-battle.md
  crates/rspack_plugin_progress/src/lib.rs
Labels: team

#2390 fix(dev-server): delete isWebTarget
  .changeset/wild-tables-dance.md
  packages/rspack-dev-server/src/server.ts
Labels: team

#2395 fix: release action node architecture config
  .github/workflows/release.yml
Labels: team

#2396 feat: 🤖 additionalAssets
  .changeset/red-swans-sell.md
  packages/rspack/src/compilation.ts
Labels: team

#2328 fix: react refresh runtime injection
  .changeset/polite-tigers-obey.md
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  packages/rspack-dev-client/src/reactRefresh.ts
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
Labels: team

#2378 feat: module.hot.accept/decline support arrary dependencies
  .changeset/big-seals-fly.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/esm/dynamic_import.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hmr_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/format.rs
  packages/rspack/tests/HotTestCases.template.ts
  packages/rspack/tests/hotCases/chunk/accept-system-import-webpackhot/changed-file.js
  packages/rspack/tests/hotCases/chunk/accept-system-import-webpackhot/chunk.js
  packages/rspack/tests/hotCases/chunk/accept-system-import-webpackhot/chunk2.js
  packages/rspack/tests/hotCases/chunk/accept-system-import-webpackhot/file.js
  packages/rspack/tests/hotCases/chunk/accept-system-import-webpackhot/index.js
  packages/rspack/tests/hotCases/chunk/accept-system-import/changed-file.js
  packages/rspack/tests/hotCases/chunk/accept-system-import/chunk.js
  packages/rspack/tests/hotCases/chunk/accept-system-import/chunk2.js
  packages/rspack/tests/hotCases/chunk/accept-system-import/file.js
  packages/rspack/tests/hotCases/chunk/accept-system-import/index.js
  packages/rspack/tests/hotCases/harmony/auto-import-multiple/changed-file.js
  packages/rspack/tests/hotCases/harmony/auto-import-multiple/commonjs.js
  packages/rspack/tests/hotCases/harmony/auto-import-multiple/file.js
  packages/rspack/tests/hotCases/harmony/auto-import-multiple/index.js
  packages/rspack/tests/hotCases/invalidate/conditional-accept/changed-file.js
  packages/rspack/tests/hotCases/invalidate/conditional-accept/data.json
  packages/rspack/tests/hotCases/invalidate/conditional-accept/index.js
  packages/rspack/tests/hotCases/invalidate/conditional-accept/module1.js
  packages/rspack/tests/hotCases/invalidate/conditional-accept/module2.js
  packages/rspack/tests/hotCases/invalidate/conditional-accept/store.js
  packages/rspack/tests/hotCases/invalidate/during-idle/a.js
  packages/rspack/tests/hotCases/invalidate/during-idle/b.js
  packages/rspack/tests/hotCases/invalidate/during-idle/c.js
  packages/rspack/tests/hotCases/invalidate/during-idle/index.js
  packages/rspack/tests/hotCases/invalidate/during-idle/module.js
Labels: team

#2402 chore: 🤖 recover benchmark history
  .github/workflows/bench-history.yaml
Labels: team

#2415 fix: returning exports from runtime for libraries
  .changeset/brown-countries-attack.md
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  packages/rspack/tests/configCases/library/umd/index.js
Labels: team

#2168 feat(rspack-cli): support mjs config
  .changeset/lemon-clocks-boil.md
  packages/rspack-cli/src/globals.d.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
  packages/rspack-cli/tests/build/basic/entry.config.mjs
  packages/rspack-cli/tsconfig.json
  packages/rspack-dev-server/src/server.ts
Labels: team

#2419 chore: update rspack-sources
  .changeset/bright-fishes-raise.md
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
Labels: team

#2404 refactor: css dependencies
  .changeset/cold-geckos-jog.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_core/src/dependency/code_generatable.rs
  crates/rspack_core/src/dependency/css/mod.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/dependency/code_generation.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/mod.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_css/src/visitors/analyze_imports_with_path.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  packages/rspack/tests/cases/css/rewrite-url/index.css
  packages/rspack/tests/cases/css/rewrite-url/index.js
Labels: team

#2421 fix: export without specifier
  .changeset/cyan-emus-love.md
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/a.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/b.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/c.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/cjs.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/cjs1.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/cjs2.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/d.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/e.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/e1.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/f.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/g.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/h.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/index.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/m.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/n.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/o.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/p.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/q.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/side-effect-free/m.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/side-effect-free/o.js
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/side-effect-free/package.json
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/some.json
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/some1.json
  packages/rspack/tests/cases/parsing/harmony-export-import-specifier/weird-cjs.js
  packages/rspack/tests/cases/parsing/harmony-reexport/a.js
  packages/rspack/tests/cases/parsing/harmony-reexport/b.js
  packages/rspack/tests/cases/parsing/harmony-reexport/c.js
  packages/rspack/tests/cases/parsing/harmony-reexport/empty.js
  packages/rspack/tests/cases/parsing/harmony-reexport/index.js
  packages/rspack/tests/cases/parsing/harmony-reexport/reexport.js
  packages/rspack/tests/cases/parsing/harmony/.gitignore
  packages/rspack/tests/cases/parsing/harmony/index.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/abc.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/abc_c.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/circularEven.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/circularOdd.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/commonjs-trans.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/commonjs.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/def.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/exportKinds.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/exports-specifier.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/reexport.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/reexport2.js
  packages/rspack/tests/cases/parsing/harmony/node_modules/unused.js
Labels: team

#2425 feat: stats for timings and builtAt
  .changeset/stale-ways-drum.md
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack/scripts/precompile-schema.js
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/stats.ts
  packages/rspack/src/watching.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/StatsTestCases.test.ts
Labels: team

#2439 refactor(rust): remove unnecessary usage of crossbeam
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/ast/minify.rs
  crates/rspack_plugin_javascript/src/plugin.rs
Labels: team

#2436 chore(rust): remove cargo warnings around napi
  crates/rspack_binding_macros/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_napi_shared/Cargo.toml
Labels: team

#2435 Bump Rust to Rust v1.68.0 (nightly-2023-03-09)
  crates/cargo-rst/src/rst.rs
  crates/rspack_core/src/options/cache.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/tree_shaking/symbol_graph.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_napi_shared/src/errors.rs
  crates/rspack_plugin_html/src/plugin.rs
  rust-toolchain.toml
  xtask/src/main.rs
Labels: team

#2453 fix: amd should return exports with iife
  .changeset/brave-snails-whisper.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/configCases/library/amd-named/index.js
Labels: team

#2465 fix: skip some tests in watch suspend
  packages/rspack/src/watching.ts
  packages/rspack/tests/WatchSuspend.test.js
Labels: team

#2454 fix(relay): :bug: apply unresolved_mark to require
  .changeset/shaggy-books-return.md
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/relay.rs
  packages/rspack/tests/configCases/builtins/relay-webpack-require/custom/MyComponent.graphql.ts
  packages/rspack/tests/configCases/builtins/relay-webpack-require/index.js
  packages/rspack/tests/configCases/builtins/relay-webpack-require/mock.js
  packages/rspack/tests/configCases/builtins/relay-webpack-require/relay.config.js
  packages/rspack/tests/configCases/builtins/relay-webpack-require/webpack.config.js
Labels: team

#2455 fix: use babel mode for mjs
  .changeset/curly-fishes-mix.md
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  packages/rspack/tests/cases/interop/mjs/a.js
  packages/rspack/tests/cases/interop/mjs/index.js
  packages/rspack/tests/cases/interop/mjs/lib.mjs
  packages/rspack/tests/cases/interop/mjs/value.js
  packages/rspack/tests/cases/interop/node-mode/lib.mjs
Labels: team

#2471 ci: check team-label only on pr and issue open
  .github/workflows/team-label.yaml
Labels: team

#2474 ci: use pnpm/action-setup in check-changeset
  .github/workflows/check-changeset.yml
Labels: team

#2476 chore(rust): remove unused dependencies via cargo-udeps
  Cargo.lock
  crates/bench/Cargo.toml
  crates/cargo-rst/Cargo.toml
  crates/node_binding/Cargo.lock
  crates/node_binding/Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack_binding_macros/Cargo.toml
  crates/rspack_build/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_testing/Cargo.toml
Labels: team

#2458 fix: should not remove empty initial chunk
  crates/rspack_plugin_remove_empty_chunks/src/lib.rs
Labels: team

#2470 ci: cache pnpm dependencies in check-rs workflow
  .github/workflows/check-rs.yaml
Labels: team

#2481 ci: fix check-rs
  .github/workflows/check-rs.yaml
Labels: team

#2459 feat: resolve.byDependency
  .changeset/rude-beds-whisper.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/compiler/resolver.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/options/resolve.rs
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/expected/main.js
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/index.js
  packages/rspack-cli/src/commands/build.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/cases/resolve/dep-conditions/.gitignore
  packages/rspack/tests/cases/resolve/dep-conditions/index.js
  packages/rspack/tests/cases/resolve/dep-conditions/node_modules/dep-condition/default.js
  packages/rspack/tests/cases/resolve/dep-conditions/node_modules/dep-condition/import.js
  packages/rspack/tests/cases/resolve/dep-conditions/node_modules/dep-condition/package.json
  packages/rspack/tests/cases/resolve/dep-conditions/node_modules/dep-condition/require.js
  packages/rspack/tests/configCases/resolve/by-dependency/baz.js
  packages/rspack/tests/configCases/resolve/by-dependency/foo.bar
  packages/rspack/tests/configCases/resolve/by-dependency/index.js
  packages/rspack/tests/configCases/resolve/by-dependency/webpack.config.js
  packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/module.js
Labels: team

#2487 feat(runtime): support set __webpack_public_path__ runtime
  .changeset/honest-rabbits-lie.md
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  packages/rspack/tests/cases/module-variables/webpack-public-path/index.js
Labels: team

#2494 fix(core): change the callback type of compiler.watch to `Callback`
  packages/rspack-dev-server/src/server.ts
  packages/rspack/src/compiler.ts
Labels: team

#2469 test(e2e): basic
  .github/workflows/test.yml
  .gitignore
  packages/playground/custom.d.ts
  packages/playground/fixtures/react/package.json
  packages/playground/fixtures/react/src/App.jsx
  packages/playground/fixtures/react/src/index.css
  packages/playground/fixtures/react/src/index.html
  packages/playground/fixtures/react/src/index.jsx
  packages/playground/fixtures/react/test/index.test.ts
  packages/playground/fixtures/react/webpack.config.js
  packages/playground/fixtures/utils.ts
  packages/playground/jest.config.js
  packages/playground/package.json
  packages/playground/scripts/env.ts
  packages/playground/scripts/globalSetup.ts
  packages/playground/scripts/globalTearDown.ts
  packages/playground/scripts/setupFiles.ts
  packages/playground/tsconfig.json
  packages/rspack-dev-server/tests/e2e-fixtures/react/app.jsx
  packages/rspack-dev-server/tests/e2e-fixtures/react/package.json
  packages/rspack-dev-server/tests/e2e/hot-reaload.test.ts
  packages/rspack-dev-server/tests/helpers/emitFile.ts
  packages/rspack-dev-server/tests/helpers/runBrowser.ts
  packages/rspack-dev-server/tests/helpers/tempDir.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: team

#2503 fix: cjs transfrom preset env
  .changeset/brave-pillows-tan.md
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  packages/rspack/tests/configCases/target/mix-cjs-esm/webpack.config.js
Labels: team

#2508 chore: fix version bump
  .github/workflows/bench-history.yaml
  crates/rspack_fs_node/package.json
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team

#2505 fix: duplicate __webpack_require__.a in async module
  .changeset/smart-wolves-prove.md
  crates/rspack_plugin_javascript/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/visitors/async_module.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/tests/fixtures/v128/expected/main.js
  examples/wasm-simple/index.html
  examples/wasm-simple/rspack.config.js
Labels: team

#2509 fix: context module request
  .changeset/clean-pugs-relate.md
  crates/rspack_core/src/compiler/resolver.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  packages/rspack/tests/cases/context/ignore-hidden-files/index.js
  packages/rspack/tests/cases/context/issue-3873/index.js
Labels: team

#2518 CI: use regex to trigger issue labeler
  .github/issue-labeler.yml
Labels: team

#2514 chore: fix canary release
  .github/workflows/release.yml
  crates/node_binding/package.json
Labels: team

#2499 chore: expose error data , part of angular
  packages/playground/fixtures/utils.ts
  packages/rspack-cli/src/utils/loadConfig.test.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack/src/compilation.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/copyPlugin/__snapshots__/CopyPlugin.test.js.snap
  packages/rspack/tests/statsCases/compitable-errors-object/index.js
  packages/rspack/tests/statsCases/compitable-errors-object/webpack.config.js
Labels: team

#2528 Revert "fix(cli): mode default config by process.env.NODE_ENV (#2343)"
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/utils/buildConfig.test.ts
  packages/rspack-cli/src/utils/buildConfig.ts
Labels: team

#2543 fix: fix hmr not working
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_hmr.js
  packages/rspack-dev-middleware/src/middleware.ts
Labels: team, p1-planned

#2538 chore: pr test workflow
  .github/workflows/test-pr.yml
  .github/workflows/test.yml
  crates/rspack/Cargo.toml
Labels: team

#2536 ci: 🎡 fix broken CI
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/errors/compitable-errors-object/index.js
  packages/rspack/tests/configCases/errors/compitable-errors-object/webpack.config.js
Labels: team

#2547 fix(rspack_testing): document on how to run the Rust core
  crates/rspack_testing/examples/build-cli.rs
  crates/rspack_testing/src/eval_raw.rs
Labels: team

#2500 fix: bump version
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.lock
  crates/rspack/tests/tree-shaking/ts-target-es5/expected/main.js
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/expected/main.css
  crates/rspack_plugin_css/src/plugin.rs
  crates/rspack_plugin_css/src/pxtorem/tests/cases/should_handle_values_and_values_without_a_leading_0.css.snap
  crates/rspack_plugin_css/src/pxtorem/tests/cases/should_not_replace_values_in_double_quotes_or_single_quotes.css.snap
  crates/rspack_plugin_javascript/src/visitors/format.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/less-loader/additional-data-async-fn/index.js
  packages/rspack/tests/configCases/less-loader/additional-data-fn/index.js
  packages/rspack/tests/configCases/warnings/css-error-tolerate/index.css
  packages/rspack/tests/configCases/warnings/css-error-tolerate/index.js
  packages/rspack/tests/configCases/warnings/css-error-tolerate/webpack.config.js
  packages/rspack/tests/statsCases/legacy-ie-css-warning/index.css
  packages/rspack/tests/statsCases/legacy-ie-css-warning/index.js
  packages/rspack/tests/statsCases/legacy-ie-css-warning/webpack.config.js
Labels: team

#2492 feat: built-in support for ProvidePlugin
  .changeset/wet-spies-fold.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/provide.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/builtins.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/configCases/builtins/provide/a.js
  packages/rspack/tests/configCases/builtins/provide/aaa.js
  packages/rspack/tests/configCases/builtins/provide/b.js
  packages/rspack/tests/configCases/builtins/provide/bbbccc.js
  packages/rspack/tests/configCases/builtins/provide/ddd.js
  packages/rspack/tests/configCases/builtins/provide/env.js
  packages/rspack/tests/configCases/builtins/provide/esm.js
  packages/rspack/tests/configCases/builtins/provide/foo.mjs
  packages/rspack/tests/configCases/builtins/provide/harmony.js
  packages/rspack/tests/configCases/builtins/provide/harmony2.js
  packages/rspack/tests/configCases/builtins/provide/index.js
  packages/rspack/tests/configCases/builtins/provide/webpack.config.js
Labels: ready to merge, p1-planned

#2532 fix: library amd returning
  .changeset/late-icons-talk.md
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  packages/rspack/tests/configCases/library/amd-named/index.js
Labels: team

#2548 chore: expose `util` for compiler.webpack
  .changeset/bright-roses-cover.md
  packages/rspack/src/compiler.ts
Labels: team

#2535 feat: new url dependency in `target: 'node'`
  .changeset/ninety-kings-report.md
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
Labels: team

#2549 chore: remove unnecessary std::mem::take
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_error/src/lib.rs
Labels: p3-nice-to-have, ready to merge

#2554 chore: git attributes ignore test related files
  .gitattributes
Labels: team

#2555 deps(node_binding): dashmap v5.4.0
  crates/node_binding/Cargo.toml
Labels: team

#2541 chore: unify line endings for all files for any new clone
  .editorconfig
  .gitattributes
Labels: p3-nice-to-have

#2560 fix: add more hash logic
  .changeset/smart-radios-peel.md
  Cargo.lock
  crates/node_binding/Cargo.lock
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_core/src/options/devtool.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/lib.rs
Labels: team

#2557 fix: should generate correct output when running `rspack build --json stats.json`
  .changeset/shiny-moose-rhyme.md
  .github/workflows/test-pr.yml
  crates/rspack_fs_node/package.json
  packages/playground/package.json
  packages/rspack-cli/package.json
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/tests/build/config/loadConfig.test.ts
  packages/rspack-cli/tests/build/config/test.rspack.config.js
  packages/rspack-cli/tests/build/json/json.test.ts
  packages/rspack-cli/tests/build/json/logging.config.js
  packages/rspack-cli/tests/build/json/src/index.js
  packages/rspack-cli/tests/build/json/stats.json
  packages/rspack-cli/tsconfig.json
Labels: team

#2561 test: add e2e test in linux
  .github/workflows/test-pr.yml
  .github/workflows/test.yml
  packages/playground/package.json
  packages/rspack/src/config/defaults.ts
Labels: team

#2564 chore: enable merge_queue
  .github/workflows/test-pr.yml
Labels: team

#2562 feat: module.rule[].dependency
  .changeset/moody-needles-train.md
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/case.template.ts
  packages/rspack/tests/cases/css/rewrite-url-with-css-filename/webpack.config.js
  packages/rspack/tests/cases/css/rewrite-url/index.js
  packages/rspack/tests/cases/module-variables/webpack-public-path/webpack.config.js
  packages/rspack/tests/configCases/asset-url/target-node1/index.css
  packages/rspack/tests/configCases/asset-url/target-node1/index.js
  packages/rspack/tests/configCases/asset-url/target-node1/webpack.config.js
  packages/rspack/tests/configCases/asset-url/target-node2/index.css
  packages/rspack/tests/configCases/asset-url/target-node2/index.js
  packages/rspack/tests/configCases/asset-url/target-node2/webpack.config.js
  packages/rspack/tests/configCases/rule-set/generator/webpack.config.js
  packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/module.js
  packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/webpack.config.js
Labels: team

#2542 chore: add devcontainer files
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: p3-nice-to-have

#2468 fix: require.cache undefined
  .changeset/two-beds-brush.md
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/simple/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/simple/index.js
  crates/rspack_plugin_javascript/tests/fixtures/simple/test.config.json
Labels: p3-minor-bug

#2571 fix: :bug: windows absolute should not be considered as scheme
  .changeset/fair-parents-repair.md
  crates/rspack_core/src/normal_module_factory.rs
Labels: team

#2480 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: team
