Repository web-infra-dev/rspack, pull requests merged in 2023-09, with the labels that each got.

#4087 fix: make dev-server compatible with globalThis
  packages/rspack-dev-client/src/reactRefreshEntry.js
Labels: release: bug fix

#4088 fix: upgrade swc
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_javascript/src/utils.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/swc_plugin_import/src/lib.rs
Labels: team, release: bug fix

#4072 fix(runtime): should calculate installed css chunks correctly
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/runtimeCases/runtime/dynamic-chunk-with-hash/dynamic.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-chunk-with-hash/index.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-chunk-with-hash/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-chunk/dynamic.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-chunk/index.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-chunk/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-content-hash/dynamic.css
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-content-hash/dynamic.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-content-hash/index.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-content-hash/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-hash/common.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-hash/dynamic.css
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-hash/dynamic.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-hash/index.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-hash/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk/common.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk/dynamic.css
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk/dynamic.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk/index.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/common.css
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/common.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/index1.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/index2.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/webpack.config.js
Labels: team, release: bug fix

#4090 revert: "ci: reduce binary size"
  .github/workflows/reusable-build.yml
Labels: team

#4094 feat: export externals plugin and node target plugin, electron target plugin
  packages/rspack/src/Compiler.ts
  packages/rspack/src/index.ts
Labels: team, release: feature

#4100 ci: take down windows test
  .github/workflows/ci.yml
Labels: team

#4095 fix: align stats.modulesSpace default behaivor with webpack
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Stats.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/Stats.test.ts
Labels: team, release: bug fix

#4104 chore: refactor exports info
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/plugin/provided_exports_plugin.rs
Labels: team

#4097 chore: add license check
  .github/workflows/ci.yml
  crates/rspack_database/Cargo.toml
  crates/rspack_identifier/Cargo.toml
  deny.toml
Labels: team

#4092 fix: avoid inject refresh runtime for it self
  packages/playground/cases/react/basic/rspack.config.js
  packages/rspack-dev-client/package.json
  packages/rspack-dev-client/src/runtimePathRegexp.js
  packages/rspack-dev-server/src/server.ts
Labels: team, release: bug fix

#4105 revert: apply entry and externals eagerly
  packages/rspack/src/Compiler.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team

#4107 feat: initialize future flags
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/options/experiments.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/experiments.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature, need documentation

#4110 fix: css loading module should render initial_chunk_ids
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/index1.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/index2.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk/other.css
Labels: team, release: bug fix

#4096 feat(core): code generation module hash
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/cache/occasion/code_generate.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  packages/playground/cases/context/delete-file/src/index.js
  packages/rspack/tests/hotCases/asset/parser-and-generator-states/changed-file.js
  packages/rspack/tests/hotCases/asset/parser-and-generator-states/file.js
  packages/rspack/tests/hotCases/asset/parser-and-generator-states/index.js
  packages/rspack/tests/hotCases/asset/parser-and-generator-states/logo.svg
  packages/rspack/tests/hotCases/asset/parser-and-generator-states/webpack.config.js
  packages/rspack/tests/hotCases/css/parser-and-generator-states/changed-file.js
  packages/rspack/tests/hotCases/css/parser-and-generator-states/index.js
  packages/rspack/tests/hotCases/css/parser-and-generator-states/index.module.css
  packages/rspack/tests/hotCases/css/parser-and-generator-states/webpack.config.js
  packages/rspack/tests/hotCases/harmony/cjs-analyze-changed/changed-file.js
  packages/rspack/tests/hotCases/harmony/cjs-analyze-changed/file.js
  packages/rspack/tests/hotCases/harmony/cjs-analyze-changed/index.js
  packages/rspack/tests/hotCases/harmony/cjs-analyze-changed/reexport.js
Labels: release: feature

#4115 fix: improve interoperability of rules with side-effects
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
Labels: release: bug fix

#4122 chore: increase windows ci test timeout minutes
  .github/workflows/reusable-build.yml
Labels: team

#4119 chore: expose statsModule.nameForCondition
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/fixtures/abc-query.js
Labels: team

#4111 fix: `builtin:swc-loader` does not report error correctly
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_swc/src/lib.rs
  package.json
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/parse-error-builtin-swc-loader/index.ts
  packages/rspack/tests/statsCases/parse-error-builtin-swc-loader/webpack.config.js
Labels: team, release: bug fix

#4125 chore: 🤖 align webpack factory meta
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  packages/rspack/src/Compiler.ts
Labels: team

#4106 chore: add documenation link notice of pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#4130 chore: use cross-env
  package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#4098 refactor: zod schema and normalized types
  crates/rspack_core/src/options/externals.rs
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/package.json
  packages/rspack/scripts/precompile-schema.js
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/builtin-plugin/HtmlPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/index.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/target.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/config/zod/_rewrite.ts
  packages/rspack/src/config/zod/builtins.ts
  packages/rspack/src/config/zod/devtool.ts
  packages/rspack/src/config/zod/entry.ts
  packages/rspack/src/config/zod/experiments.ts
  packages/rspack/src/config/zod/externals-presets.ts
  packages/rspack/src/config/zod/externals-type.ts
  packages/rspack/src/config/zod/externals.ts
  packages/rspack/src/config/zod/index.ts
  packages/rspack/src/config/zod/infrastructure-logging.ts
  packages/rspack/src/config/zod/module.ts
  packages/rspack/src/config/zod/node.ts
  packages/rspack/src/config/zod/optimization/index.ts
  packages/rspack/src/config/zod/optimization/split-chunks.ts
  packages/rspack/src/config/zod/output.ts
  packages/rspack/src/config/zod/plugins.ts
  packages/rspack/src/config/zod/resolve.ts
  packages/rspack/src/config/zod/snapshot.ts
  packages/rspack/src/config/zod/stats.ts
  packages/rspack/src/config/zod/target.ts
  packages/rspack/src/config/zod/watch-options.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/validate.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/split-chunks/max-size-casing/webpack.config.js
  pnpm-lock.yaml
Labels: team

#4132 fix: test snapshot path
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/fixtures/abc-query.js
Labels: team, release: bug fix

#4134 fix: use module.rules.include to avoid runtime inject it self
  packages/rspack-dev-client/package.json
  packages/rspack-dev-client/src/runtimePathRegexp.js
  packages/rspack-dev-client/src/runtimePaths.js
  packages/rspack-dev-server/src/server.ts
Labels: team, release: bug fix

#4138 chore: format PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#4142 chore: disable sync document when closed merge request
  .github/workflows/need-doc.yml
Labels: team

#4140 feat(core): add cache hits info to stats
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/cache/occasion/code_generate.rs
  crates/rspack_core/src/cache/occasion/resolve_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/logger.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/src/logging/Logger.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/tests/Stats.test.ts
Labels: release: feature

#4145 fix: console should not appear here
  packages/rspack-dev-server/src/server.ts
Labels: team, release: bug fix

#4146 chore: takedown down monaco-editor example build in ci
  examples/monaco-editor-js/package.json
  examples/monaco-editor-ts-react/package.json
Labels: team

#4149 fix: vue3 hmr
  crates/rspack_core/src/compiler/compilation.rs
  packages/playground/cases/vue3/index.test.ts
  packages/playground/cases/vue3/rspack.config.js
  packages/playground/cases/vue3/src/App.vue
  packages/playground/cases/vue3/src/index.html
  packages/playground/cases/vue3/src/main.js
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#4141 feat: HarmonyExportImportedSpecifierDependency get mode
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: team, release: feature

#4101 fix: patch `sendStats` of webpack-dev-server
  packages/rspack-dev-server/src/patch.ts
  packages/rspack-dev-server/src/server.ts
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#4144 fix(css/modules): bump swc version to fix #3875 and add test
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/custom/composes/b.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/composes/d.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/composes/e.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/composes/f.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/composes/index.js
  crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/custom/composes/style.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/composes/test.config.json
  crates/rspack_plugin_css/tests/fixtures/custom/http_import/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/custom/modules-ident-name/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/at-charset/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/default-options/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/multiple-entry/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/nested/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/output-iife/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/shared-import/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-async-load-css/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-async/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-commonjs-syntax/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-es-module-syntax/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-multiple/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple/snapshot/output.snap
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_testing/src/run_fixture.rs
Labels: release: bug fix

#4153 fix: ignoreWarnings should work when call stats.getJson
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/ignore-warning/index.js
  packages/rspack/tests/statsCases/ignore-warning/index.scss
  packages/rspack/tests/statsCases/ignore-warning/webpack.config.js
Labels: team, release: bug fix

#4148 feat: support stats ids
  packages/rspack/src/Compilation.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: release: feature

#4151 feat: support function for `BannerPlugin`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/mod.rs
  crates/rspack_binding_options/src/chunk.rs
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_banner/src/lib.rs
  packages/rspack/src/builtin-plugin/BannerPlugin.ts
  packages/rspack/src/builtin-plugin/ProgressPlugin.ts
  packages/rspack/src/index.ts
  packages/rspack/src/lib/BannerPlugin.js
  packages/rspack/src/lib/LoaderOptionsPlugin.js
  packages/rspack/src/lib/Template.js
  packages/rspack/src/lib/util/create-schema-validation.js
  packages/rspack/src/lib/util/memoize.js
  packages/rspack/src/schemas/plugins/BannerPlugin.check.js
  packages/rspack/src/schemas/plugins/BannerPlugin.json
  packages/rspack/src/schemas/plugins/LoaderOptionsPlugin.check.js
  packages/rspack/src/schemas/plugins/LoaderOptionsPlugin.json
Labels: team, release: feature

#4155 test: snapshot css modules separately
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures.rs
  crates/rspack_plugin_css/tests/fixtures/custom/http_import/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/b.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/d.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/e.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/f.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/index.js
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/style.module.css
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/test.config.json
  crates/rspack_plugin_css/tests/fixtures/webpack/at-charset/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/default-options/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/multiple-entry/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/nested/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/output-iife/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/shared-import/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-async-load-css/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-async/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-commonjs-syntax/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-es-module-syntax/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-multiple/snapshot/output.snap
  crates/rspack_plugin_css/tests/fixtures/webpack/simple/snapshot/output.snap
  crates/rspack_testing/src/lib.rs
  crates/rspack_testing/src/run_fixture.rs
Labels: team

#4121 feat: expose `keepFnNames` and `keepClassNames` options of builtin swc minfier
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_testing/test.config.scheme.json
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/builtins/minify-keep-classnames/index.js
  packages/rspack/tests/configCases/builtins/minify-keep-classnames/webpack.config.js
  packages/rspack/tests/configCases/builtins/minify-keep-fn-names/index.js
  packages/rspack/tests/configCases/builtins/minify-keep-fn-names/webpack.config.js
Labels: ready to merge, release: feature, need documentation

#4116 perf: optimize process assets
  Cargo.lock
  Cargo.toml
Labels: team, release: performance

#4161 chore: fix publish problems of react-refresh
  packages/rspack-plugin-react-refresh/package.json
Labels: team

#4164 fix: export client dir in react-refresh-plugin
  packages/rspack-plugin-react-refresh/package.json
Labels: team, release: bug fix

#4165 fix: resolve async css chunk loading promise
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_loading.js
  packages/playground/cases/react/basic/index.test.ts
  packages/playground/cases/react/basic/src/App.jsx
  packages/playground/cases/react/basic/src/LazyComponent.css
  packages/playground/cases/react/basic/src/LazyComponent.jsx
Labels: team, release: bug fix

#4166 chore: add profile syntax comment
  packages/rspack-cli/src/utils/profile.ts
Labels: team

#4167 fix: chunkLoading false
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  packages/rspack/tests/configCases/chunk-loading/false/dynamic.js
  packages/rspack/tests/configCases/chunk-loading/false/index.js
  packages/rspack/tests/configCases/chunk-loading/false/webpack.config.js
Labels: team, release: bug fix

#4156 refactor: naming to RspackPlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_progress.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_externals/src/http_externals_plugin.rs
  crates/rspack_plugin_externals/src/lib.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/parser.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/visitors/asset.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/BannerPlugin.ts
  packages/rspack/src/builtin-plugin/CopyPlugin.ts
  packages/rspack/src/builtin-plugin/CopyRspackPlugin.ts
  packages/rspack/src/builtin-plugin/DefinePlugin.ts
  packages/rspack/src/builtin-plugin/ElectronTargetPlugin.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/src/builtin-plugin/HttpExternalsPlugin.ts
  packages/rspack/src/builtin-plugin/HttpExternalsRspackPlugin.ts
  packages/rspack/src/builtin-plugin/NodeTargetPlugin.ts
  packages/rspack/src/builtin-plugin/ProgressPlugin.ts
  packages/rspack/src/builtin-plugin/ProvidePlugin.ts
  packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/copyPlugin/fixtures/watch/_t2/directory/tempfile1.txt
  packages/rspack/tests/copyPlugin/fixtures/watch/_t2/directory/tempfile2.txt
Labels: team

#4169 feat(config): warn while using `experiments.newSplitChunks`
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#4170 fix(core): add AbstractMethodError and fix references
  packages/rspack/src/lib/AbstractMethodError.js
  packages/rspack/src/util/hash/index.js
Labels: release: bug fix

#4173 feat: improve zod types
  packages/rspack/src/config/zod.ts
Labels: team, release: feature, release: ignore

#4174 feat(config): only warn while `experiments.newSplitChunks` being explicitly setted
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#4178 ci: refine artifact publishing
  scripts/build-npm.cjs
Labels: team

#4175 feat: compatible with html-webpack-plugin
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  examples/plugin-compat/package.json
  examples/plugin-compat/rspack.config.js
  packages/rspack/package.json
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/ArrayPushCallbackChunkFormatPlugin.ts
  packages/rspack/src/builtin-plugin/CommonJsChunkFormatPlugin.ts
  packages/rspack/src/builtin-plugin/EnableChunkLoadingPlugin.ts
  packages/rspack/src/builtin-plugin/EnableLibraryPlugin.ts
  packages/rspack/src/builtin-plugin/EnableWasmLoadingPlugin.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/builtin-plugin/ModuleChunkFormatPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/index.ts
  packages/rspack/src/lib/LoaderTargetPlugin.js
  packages/rspack/src/node/NodeTemplatePlugin.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/util/fake.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/plugins/html-webpack-plugin/index.js
  packages/rspack/tests/configCases/plugins/html-webpack-plugin/template.html
  packages/rspack/tests/configCases/plugins/html-webpack-plugin/template.pug
  packages/rspack/tests/configCases/plugins/html-webpack-plugin/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/split-css-chunk-async/webpack.config.js
  pnpm-lock.yaml
  webpack-test/configCases/asset-modules/base-uri/test.filter.js
  webpack-test/configCases/worker/web-worker/test.filter.js
Labels: team, release: feature

#4147 feat: combine three tree shaking related plugin, and add corresponding configuration.
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#4184 feat: add externalsPresets webAsync target support
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_plugin_externals/src/http_externals_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/builtin-plugin/HttpExternalsRspackPlugin.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: release: feature

#4185 fix: perf regression caused by optimizeTree hook
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  packages/rspack/src/Compiler.ts
Labels: team, release: bug fix

#3771 feat: add boolean type for builtins.html[0].inject
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/visitors/asset.rs
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/tests/configCases/builtins/html-inject/index.js
  packages/rspack/tests/configCases/builtins/html-inject/webpack.config.js
  pnpm-lock.yaml
Labels: release: feature

#4193 refactor: public path runtime module
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_wasm/src/runtime.rs
  packages/rspack/tests/cases/css/rewrite-url-auto-public-path/webpack.config.js
Labels: team

#4194 fix: shouldn't always apply react refresh plugin
  examples/nestjs/rspack.config.js
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
Labels: team, release: bug fix

#4192 feat(rspack_core): oxc_resolver v0.2.0
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
Labels: team, release: feature

#4197 feat(progress): optimize the progress bar style
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#4200 fix: fix module source-map
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  examples/builtin-swc-loader/src/App.jsx
  examples/builtin-swc-loader/src/index.jsx
  packages/rspack/tests/configCases/source-map/source-map/App.jsx
  packages/rspack/tests/configCases/source-map/source-map/index.js
  packages/rspack/tests/configCases/source-map/source-map/webpack.config.js
Labels: team, release: bug fix

#4196 feat: disableReactRefreshByDefault future flag
  examples/nestjs/rspack.config.js
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#4208 chore: more tree shaking test2
  crates/rspack/tests/tree-shaking/bb/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/bb/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/cjs-tree-shaking-basic/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/cjs-tree-shaking-basic/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/explicit_named_export_higher_priority_2/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/explicit_named_export_higher_priority_2/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/inherit_export_map_should_lookup_in_dfs_order/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/inherit_export_map_should_lookup_in_dfs_order/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/named-export-decl-with-src-eval/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/named-export-decl-with-src-eval/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-prune/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-prune/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/snapshot/snap.diff
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
Labels: team

#4210 perf: remove `panic_hook`
  crates/rspack_error/src/catch_unwind.rs
Labels: team, release: performance

#4218 chore: fix example dep
  examples/proxy/package.json
  pnpm-lock.yaml
Labels: team

#4213 perf: parallelize swc js minify
  Cargo.lock
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_util/src/lib.rs
Labels: team, release: performance

#4221 fix: remove `react` from `rspackExperiments` of `builtin:swc-loader`
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_loader_swc/src/transformer.rs
  packages/rspack/tests/configCases/builtin-swc-loader/react-refresh-false/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-classic/webpack.config.js
Labels: team, release: bug fix

#4220 fix: merge disableReactRefreshByDefault to disableTransformByDefault
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: bug fix

#4223 fix: missing rspack-only plugins on compiler.webpack
  packages/rspack/src/Compiler.ts
Labels: team, release: bug fix

#4222 chore: fix example-emotion
  examples/emotion/rspack.config.js
Labels: team

#4199 feat: export HMR plugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  packages/playground/fixtures/index.ts
  packages/playground/fixtures/rspack.ts
  packages/playground/package.json
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/HotModuleReplacementPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/HotTestCases.template.ts
  pnpm-lock.yaml
Labels: team, release: feature

#4226 feat: deprecate `builtin:sass-loader`
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapterRuleUse.ts
Labels: team, release: feature

#4227 feat: support `output.hotUpdateGlobal`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_hmr.js
  crates/rspack_testing/src/test_config.rs
  examples/nestjs/rspack.config.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/output-hot-config/hot-update-global/a.js
  packages/rspack/tests/configCases/output-hot-config/hot-update-global/b.js
  packages/rspack/tests/configCases/output-hot-config/hot-update-global/index.js
  packages/rspack/tests/configCases/output-hot-config/hot-update-global/test.config.js
  packages/rspack/tests/configCases/output-hot-config/hot-update-global/webpack.config.js
Labels: team, release: feature

#4229 fix: filter export imported specifier used name .
  .github/workflows/ci.yml
  crates/rspack/tests/check.js
  crates/rspack/tests/fixtures.rs
  crates/rspack/tests/tree-shaking/bb/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/bb/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/export_star/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export_star/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/import-var-assign-side-effects/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/import-var-assign-side-effects/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/rename-export-from-import/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/rename-export-from-import/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/ts-target-es5/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/ts-target-es5/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/snapshot/snap.diff
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
Labels: team, release: bug fix

#4232 fix: fix react-refresh `self` is not defined
  packages/rspack-plugin-react-refresh/client/reactRefreshEntry.js
Labels: team, release: bug fix

#4233 feat: support `include` and `exclude` of react-refresh-rspack-plugin
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-plugin-react-refresh/src/index.js
  packages/rspack-plugin-react-refresh/src/options.js
  packages/rspack-plugin-react-refresh/src/options.json
  packages/rspack-plugin-react-refresh/tests/fixtures/.gitignore
  packages/rspack-plugin-react-refresh/tests/fixtures/custom/index.js
  packages/rspack-plugin-react-refresh/tests/fixtures/default/index.js
  packages/rspack-plugin-react-refresh/tests/fixtures/node_modules/foo/index.js
  packages/rspack-plugin-react-refresh/tests/fixtures/node_modules/foo/package.json
  packages/rspack-plugin-react-refresh/tests/test.spec.ts
  pnpm-lock.yaml
Labels: team, release: feature, need documentation

#4237 chore: worklet example & express example
  examples/worklet/index.html
  examples/worklet/loader/worklet-loader.js
  examples/worklet/package.json
  examples/worklet/rspack.config.js
  examples/worklet/src/answer.js
  examples/worklet/src/index.js
  examples/worklet/src/lib.js
  examples/worklet/src/worklet/answer.ts
  examples/worklet/src/worklet/complex.worklet.js
  examples/worklet/src/worklet/simple.worklet.js
  pnpm-lock.yaml
Labels: team

#4242 fix: react refresh test windows failed
  packages/rspack-plugin-react-refresh/tests/test.spec.ts
Labels: team, release: bug fix

#4243 fix: avoid double react refresh transform in rspack-dev-server
  packages/rspack-dev-server/src/server.ts
  packages/rspack-plugin-react-refresh/src/index.js
Labels: team, release: bug fix

#4234 feat: support object external item value
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/property_access.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_library/src/utils.rs
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/configCases/externals/item-value-object/index.js
  packages/rspack/tests/configCases/externals/item-value-object/lodash.js
  packages/rspack/tests/configCases/externals/item-value-object/webpack.config.js
Labels: team, release: feature

#4235 fix: passing option as `&str` caused memory leak in `builtin:swc-loader`
  crates/node_binding/src/loader.rs
Labels: team, release: bug fix

#4248 fix(chore): fix node path compatible problem & add express example
  examples/express/package.json
  examples/express/rspack.config.js
  examples/express/src/api/root.ts
  examples/express/src/main.ts
  packages/rspack/src/builtin-loader/swc/relay.ts
  pnpm-lock.yaml
Labels: team, release: bug fix

#4249 chore: add builtins.react/... only works for transformByDefault tip
  packages/rspack/src/builtin-plugin/index.ts
Labels: team

#4251 fix: $RefreshReg$ is not defined error in node_modules
  crates/rspack_loader_react_refresh/src/lib.rs
  crates/rspack_swc_visitors/src/react.rs
  packages/playground/cases/react/basic-disableTransformByDefault/.gitignore
  packages/playground/cases/react/basic-disableTransformByDefault/node_modules/foo/index.jsx
  packages/playground/cases/react/basic-disableTransformByDefault/node_modules/foo/package.json
  packages/playground/cases/react/basic-disableTransformByDefault/rspack.config.js
  packages/playground/cases/react/basic-disableTransformByDefault/src/App.jsx
  packages/rspack-plugin-react-refresh/client/reactRefreshEntry.js
  packages/rspack-plugin-react-refresh/tests/test.spec.ts
Labels: team, release: bug fix

#4252 chore: fix lockfile
  pnpm-lock.yaml
Labels: team

#4257 fix(rspack_loader_swc): Fail the build when jsc.target and env are used together for the SWC loader
  crates/rspack_loader_swc/src/lib.rs
Labels: release: bug fix

#4256 fix: type error when use builtins:swc-loader and disableTransformByDefault
  packages/rspack-dev-server/src/server.ts
Labels: team, release: bug fix

#4271 chore: change nightly release notification to discord other than github issue
  .github/workflows/release-nightly.yml
Labels: team

#4266 fix: css chunk loading missing chunkIds
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_loading.js
Labels: team, release: bug fix
