Repository web-infra-dev/rspack, pull requests merged in 2023-12, with the labels that each got.

#4836 feat: JsAsset remove version field
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/asset.rs
  packages/rspack/src/util/index.ts
Labels: team, release: feature

#4832 chore: enable new tree shaking for all tests.
  Cargo.lock
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  webpack-test/ConfigTestCases.template.js
  webpack-test/TestCases.template.js
  webpack-test/cases/parsing/issue-7519/test.config.js
Labels: team

#4855 feat: implement `ChunkGraph.getChunkModulesIterable` and `ChunkGraph.getChunkEntryModulesIterable`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/chunk.rs
  packages/rspack/src/Chunk.ts
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/tests/configCases/plugins/chunk-modules/async.js
  packages/rspack/tests/configCases/plugins/chunk-modules/index.js
  packages/rspack/tests/configCases/plugins/chunk-modules/webpack.config.js
Labels: release: feature

#4857 fix: js files are not minified well when outputModule is true (#4819)
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/tests/configCases/plugins/minify-module/index.js
  packages/rspack/tests/configCases/plugins/minify-module/module-entry.js
  packages/rspack/tests/configCases/plugins/minify-module/module.js
  packages/rspack/tests/configCases/plugins/minify-module/test.config.js
  packages/rspack/tests/configCases/plugins/minify-module/webpack.config.js
Labels: release: bug fix

#4879 chore: remove @rspack/dev-client
  .github/CODEOWNERS
  examples/basic/rspack.config.js
  packages/playground/package.json
  packages/rspack-dev-client/CHANGELOG.md
  packages/rspack-dev-client/LICENSE
  packages/rspack-dev-client/README.md
  packages/rspack-dev-client/package.json
  packages/rspack-dev-client/src/reactRefresh.js
  packages/rspack-dev-client/src/reactRefreshEntry.js
  pnpm-lock.yaml
Labels: team

#4850 ci: optimize diff workflow
  .github/workflows/diff.yml
Labels: team, A-build-testing

#4863 feat(runtime-diff): alignment of wasm async loading runtime module
  crates/rspack_core/src/utils/runtime.rs
  crates/rspack_plugin_wasm/src/loading_plugin.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/runtime.rs
  crates/rspack_plugin_wasm/src/runtime/async-wasm-loading.js
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/snapshot/output.snap
  crates/rspack_plugin_wasm/tests/fixtures/v128/snapshot/output.snap
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-async-node-module/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-async-node-module/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-async-node-module/src/wasm.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-async-node-module/src/wasm2.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-async-node-module/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-async-node-module/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-fetch/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-fetch/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-fetch/src/wasm.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-fetch/src/wasm2.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-fetch/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading-fetch/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/src/wasm.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/src/wasm2.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/webpack.config.js
Labels: team, same as webpack, release: feature

#4875 fix: production environment refreshPlugin error
  packages/create-rspack/template-react-ts/rspack.config.js
  packages/create-rspack/template-react/rspack.config.js
Labels: release: bug fix

#4884 fix(e2e): remove dev-client based e2e testing cases to fix e2e testing
  packages/playground/cases/react/basic-deprecated-dev-client/index.test.ts
  packages/playground/cases/react/basic-deprecated-dev-client/react-refresh.js
  packages/playground/cases/react/basic-deprecated-dev-client/rspack.config.js
  packages/playground/cases/react/basic-deprecated-dev-client/src/App.jsx
  packages/playground/cases/react/basic-deprecated-dev-client/src/CountProvider.jsx
  packages/playground/cases/react/basic-deprecated-dev-client/src/ReactRefreshFinder.jsx
  packages/playground/cases/react/basic-deprecated-dev-client/src/SameExportName1.jsx
  packages/playground/cases/react/basic-deprecated-dev-client/src/SameExportName2.jsx
  packages/playground/cases/react/basic-deprecated-dev-client/src/index.css
  packages/playground/cases/react/basic-deprecated-dev-client/src/index.html
  packages/playground/cases/react/basic-deprecated-dev-client/src/index.jsx
Labels: release: bug fix

#4883 feat: align webpack - allow `false` for `optimization.splitChunks` on options validation
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/configCases/split-chunks-common/default/index.js
  packages/rspack/tests/configCases/split-chunks-common/default/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/default/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/disable/index.js
  packages/rspack/tests/configCases/split-chunks-common/disable/test.config.js
  packages/rspack/tests/configCases/split-chunks-common/disable/webpack.config.js
Labels: release: feature

#4886 chore: remove plugin-compat example
  examples/plugin-compat/index.ejs
  examples/plugin-compat/index.html
  examples/plugin-compat/package.json
  examples/plugin-compat/public/robots.txt
  examples/plugin-compat/rspack.config.js
  examples/plugin-compat/src/answer.js
  examples/plugin-compat/src/index.css
  examples/plugin-compat/src/index.js
  examples/plugin-compat/src/secret.ts
  examples/plugin-compat/tsconfig.json
  packages/rspack-plugin-html/README.md
  pnpm-lock.yaml
Labels: team

#4888 chore: add LingyuCoder to team members
  .github/teams.yml
Labels: team

#4805 feat: mangle exports
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack/tests/fixtures.rs
  crates/rspack/tests/samples/mangle-exports-demo/answer.js
  crates/rspack/tests/samples/mangle-exports-demo/index.js
  crates/rspack/tests/samples/mangle-exports-demo/lib.js
  crates/rspack/tests/samples/mangle-exports-demo/snapshot/output.snap
  crates/rspack/tests/samples/mangle-exports-demo/test.config.json
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/snap.diff
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/utils/mangle_exports.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_wasm/src/dependency/mod.rs
  crates/rspack_plugin_wasm/src/dependency/static_exports_dependency.rs
  crates/rspack_plugin_wasm/src/dependency/wasm_import_dependency.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, need documentation, release: feature

#4814 feat: support scriptType
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/output/script-type/a.js
  packages/rspack/tests/configCases/output/script-type/b.png
  packages/rspack/tests/configCases/output/script-type/index.js
  packages/rspack/tests/configCases/output/script-type/webpack.config.js
Labels: release: feature

#4799 feat: extract data from mf generated code
  crates/rspack_core/src/mf/container/remote_module.rs
  crates/rspack_core/src/mf/container/remote_runtime_module.rs
  crates/rspack_core/src/mf/mod.rs
  crates/rspack_core/src/mf/sharing/consume_shared_module.rs
  crates/rspack_core/src/mf/sharing/consume_shared_runtime_module.rs
  crates/rspack_core/src/mf/sharing/provide_shared_module.rs
  crates/rspack_core/src/mf/sharing/provide_shared_plugin.rs
  crates/rspack_core/src/mf/sharing/share_runtime_module.rs
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/remotesLoading.js
  packages/rspack/src/sharing/consumesLoading.js
  packages/rspack/src/sharing/initializeSharing.js
  webpack-test/configCases/container/module-federation-with-shareScope/App.js
  webpack-test/configCases/container/module-federation-with-shareScope/ComponentB.js
  webpack-test/configCases/container/module-federation-with-shareScope/ComponentC.js
  webpack-test/configCases/container/module-federation-with-shareScope/index.js
  webpack-test/configCases/container/module-federation-with-shareScope/node_modules/package.json
  webpack-test/configCases/container/module-federation-with-shareScope/node_modules/react.js
  webpack-test/configCases/container/module-federation-with-shareScope/package.json
  webpack-test/configCases/container/module-federation-with-shareScope/test.config.js
  webpack-test/configCases/container/module-federation-with-shareScope/test.filter.js
  webpack-test/configCases/container/module-federation-with-shareScope/upgrade-react.js
  webpack-test/configCases/container/module-federation-with-shareScope/webpack.config.js
Labels: team, release: feature

#4874 chore: avoid enable new treeshaking and the `builtins.treeShaking` at the same time
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/compiler/mod.rs
Labels: team

#4894 fix: chunk modules test on windows
  packages/rspack/tests/configCases/plugins/chunk-modules/index.js
  packages/rspack/tests/configCases/plugins/chunk-modules/webpack.config.js
Labels: team, release: bug fix

#4851 refactor: key performance in merge_matched_item_into_module_group_map
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_split_chunks_new/src/options/cache_group_test.rs
  crates/rspack_plugin_split_chunks_new/src/options/chunk_name.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
Labels: A-performance, release: performance

#4900 fix: module decorator when harmony mixed
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/bbb.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs1.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs2.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs3.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs4.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs5.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm1.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm2.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm3.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm4.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm5.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm6.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/index.js
Labels: team, release: bug fix

#4891 chore(runtime-diff): align module decorator runtime modules with webpack
  crates/rspack_plugin_runtime/src/runtime_module/runtime/harmony_module_decorator.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/node_module_decorator.js
  packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/src/aaa.js
  packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/src/bbb.js
  packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/src/aaa.js
  packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/src/bbb.js
  packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/test.config.js
Labels: team, same as webpack

#4856 chore(runtime-diff): alignment of hot module replacement runtime module
  crates/rspack_plugin_hmr/src/runtime/hot_module_replacement.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/runtimeDiffCases/runtime-hot-module-replacement/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-hot-module-replacement/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-hot-module-replacement/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-hot-module-replacement/webpack.config.js
Labels: team, same as webpack

#4904 fix: webpack-test/cases/parsing/issue-7519 with tree shaking enable
  webpack-test/TestCases.template.js
  webpack-test/cases/parsing/issue-7519/test.config.js
Labels: team, release: bug fix

#4853 fix: eco-ci trigger after nightly release
  .github/workflows/release-nightly.yml
Labels: team, release: bug fix

#4918 feat: eval binary expression
  crates/rspack_plugin_javascript/src/utils/basic_evaluated_expression.rs
  crates/rspack_plugin_javascript/src/utils/const.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#4920 test: prevent .DS_store been add to test cases on macos
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/HotTestCases.template.ts
  packages/rspack/tests/RuntimeDiff.diff.test.ts
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/WatchTestCases.template.ts
  packages/rspack/tests/case.template.ts
  packages/rspack/tests/utils.ts
Labels: team

#4928 fix(rspack_core): oxc_resolver v0.6.0 - resolve styled-components correctly
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team, release: bug fix

#4927 fix: inner graph function visit
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
Labels: team, release: bug fix

#4917 feat: runtime optimization
  .vscode/launch.json
  crates/rspack/tests/fixtures.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack/tests/cases/used-exports/used-exports-global/index.js
  packages/rspack/tests/cases/used-exports/used-exports-global/lib.js
  packages/rspack/tests/cases/used-exports/used-exports-global/package.json
  packages/rspack/tests/cases/used-exports/used-exports-global/sub.js
  packages/rspack/tests/cases/used-exports/used-exports-global/webpack.config.js
  packages/rspack/tests/cases/used-exports/used-exports-true/index.js
  packages/rspack/tests/cases/used-exports/used-exports-true/lib.js
  packages/rspack/tests/cases/used-exports/used-exports-true/package.json
  packages/rspack/tests/cases/used-exports/used-exports-true/sub.js
  packages/rspack/tests/cases/used-exports/used-exports-true/webpack.config.js
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/container/1-transitive-overriding/webpack.config.js
  webpack-test/configCases/sharing/provide-multiple-versions/webpack.config.js
Labels: team, release: feature

#4929 feat: support eval `typeof require`
  Cargo.lock
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/basic_evaluated_expression.rs
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/utils/const/mod.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_cond_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#4937 chore: deprecate @rspack/plugin-node-polyfill
  packages/rspack-plugin-node-polyfill/README.md
Labels: team

#4940 chore: add debug info under panic with debug build
  crates/node_binding/src/panic.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/debug_info.rs
  crates/rspack_core/src/lib.rs
Labels: team

#4947 fix: should return number.to_string instead of char::from
  crates/rspack/tests/fixtures.rs
  crates/rspack_plugin_javascript/src/utils/mangle_exports.rs
Labels: team, release: bug fix

#4946 fix: rm dep type for resolve
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
Labels: release: bug fix

#4866 refactor: error and diagnostics
  Cargo.lock
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_error/src/error.rs
  crates/rspack_error/src/lib.rs
  crates/rspack_error/src/macros.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
Labels: team

#4955 fix: 🐛 align with webpack number_hash
  crates/rspack_util/src/number_hash.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/copyPlugin/build/main.js
Labels: team, release: bug fix

#4950 chore: optimize diff test case
  diffcases/arco-pro/rspack.config.js
  diffcases/arco-pro/webpack.config.js
  packages/rspack-test-tools/src/compare/compare.ts
  packages/rspack-test-tools/src/compare/format-code.ts
  packages/rspack-test-tools/src/compare/replace-module-argument.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/reporter/diff-html.ts
  packages/rspack-test-tools/src/webpack/module-placeholder-plugin.ts
  packages/rspack-test-tools/viewer/pages/diff-report.tsx
  packages/rspack-test-tools/viewer/templates/diff.html
  packages/rspack-test-tools/viewer/utils/generateTreeData.tsx
  packages/rspack/tests/RuntimeDiff.diff.test.ts
  scripts/diff.cjs
Labels: team

#4961 fix: module.context is undefined
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  packages/rspack/src/Module.ts
Labels: release: bug fix

#4962 fix: remove static new_treeshaking switch
  crates/rspack/tests/fixtures.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: bug fix

#4964 feat: support optimization.splitChunks.hidePathInfo option
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_plugin_split_chunks/src/options/split_chunks_options.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/split-chunks/max-size-casing/webpack.config.js
Labels: release: feature

#4967 fix: compare blocks and its group_options
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  packages/playground/cases/chunk/issue-4936/index.test.ts
  packages/playground/cases/chunk/issue-4936/rspack.config.js
  packages/playground/cases/chunk/issue-4936/src/app.js
  packages/playground/cases/chunk/issue-4936/src/index.js
  packages/playground/cases/html/issue-4366/index.test.ts
Labels: release: bug fix

#4880 refactor: should not always rely on `Result`
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_ast/src/lib.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_loader_react_refresh/src/lib.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/swc_css_compiler.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
Labels: team

#4952 chore(webpack-test): enable resolving/browser-field tests
  Cargo.lock
  crates/rspack_core/Cargo.toml
  webpack-test/TestCases.template.js
  webpack-test/cases/resolving/browser-field/errors.js
  webpack-test/cases/resolving/browser-field/test.filter.js
Labels: team

#4971 fix: get js chunk filename
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
Labels: team, release: bug fix

#4972 test(runtime): add test case of using [id] in get chunk filename runtime module
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/a.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/b.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/common/0.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/common/1.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/other/0.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/other/1.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/0.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/1.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/10.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/11.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/12.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/13.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/14.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/15.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/16.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/17.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/18.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/19.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/2.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/3.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/4.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/5.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/6.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/7.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/8.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/shared/9.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/test.config.js
  packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/webpack.config.js
Labels: team

#4508 chore(runtime-diff): alignment of startup chunk dependencies runtime module
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_chunk_dependencies.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_chunk_dependencies_with_async.js
  crates/rspack_plugin_runtime/src/runtime_module/startup_chunk_dependencies.rs
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/async.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/index.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/lib-1.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/other.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/shared.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/webpack.config.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/async.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/index.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/lib-1.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/lib-2.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/other.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/shared.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/webpack.config.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/async.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/index.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/lib-1.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/lib-2.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/lib-3.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/other.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/shared.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/webpack.config.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/index.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/lib-1.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/lib-2.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/lib-3.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/other.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/shared.js
  packages/rspack/tests/configCases/chunk-loading/startup-require/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-startup-chunk-dependencies/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-startup-chunk-dependencies/src/another.js
  packages/rspack/tests/runtimeDiffCases/runtime-startup-chunk-dependencies/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-startup-chunk-dependencies/src/shared.js
  packages/rspack/tests/runtimeDiffCases/runtime-startup-chunk-dependencies/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-startup-chunk-dependencies/webpack.config.js
Labels: team, same as webpack

#4858 feat: 🎸 json tree shaking
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_json/src/json_exports_dependency.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_json/tests/fixtures/simple/json.json
  crates/rspack_plugin_json/tests/fixtures/simple/snapshot/output.snap
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/data/c.json
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/data/d.json
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/data/e.json
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/data/f.json
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/data/g.json
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/index.js
  packages/rspack/tests/configCases/tree-shaking/import-by-name-json/webpack.config.js
  webpack-test/configCases/sharing/share-multiple-versions/webpack.config.js
Labels: release: feature

#4975 feat: add script nonce
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/nonce.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/configCases/nonce/not-set-nonce/empty.js
  packages/rspack/tests/configCases/nonce/not-set-nonce/index.js
  packages/rspack/tests/configCases/nonce/not-set-nonce/webpack.config.js
  packages/rspack/tests/configCases/nonce/set-nonce/empty.js
  packages/rspack/tests/configCases/nonce/set-nonce/index.js
  packages/rspack/tests/configCases/nonce/set-nonce/webpack.config.js
  webpack-test/configCases/web/nonce/test.filter.js
Labels: team, release: feature

#4976 fix: add node modules to npmginore in templates
  packages/create-rspack/template-react-ts/.npmignore
  packages/create-rspack/template-react/.npmignore
  packages/create-rspack/template-vanilla/.npmignore
  packages/create-rspack/template-vue/.npmignore
Labels: release: bug fix

#4970 feat(es): allow parse js hashbang syntax
  crates/rspack_plugin_javascript/src/ast/parse.rs
  crates/rspack_plugin_javascript/tests/fixtures/hashbang/index.js
  crates/rspack_plugin_javascript/tests/fixtures/hashbang/lib.js
  crates/rspack_plugin_javascript/tests/fixtures/hashbang/snapshot/output.snap
  crates/rspack_plugin_javascript/tests/fixtures/hashbang/test.config.json
  webpack-test/cases/parsing/hashbang/test.filter.js
Labels: release: feature

#4954 fix: align mangle exports comments
  crates/rspack/tests/samples/mangle-exports-demo/snapshot/output.snap
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/template.rs
Labels: team, release: bug fix

#4949 fix(config): support pass false to plugins
  packages/rspack/src/Compiler.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/configCases/plugins/plugins-falsy/a.js
  packages/rspack/tests/configCases/plugins/plugins-falsy/index.js
  packages/rspack/tests/configCases/plugins/plugins-falsy/webpack.config.js
Labels: release: bug fix

#4911 fix(@rspack/core): minify should be disabled when minimizer is an empty array
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/plugins/minify-disabled-on-empty-array/index.css
  packages/rspack/tests/configCases/plugins/minify-disabled-on-empty-array/index.js
  packages/rspack/tests/configCases/plugins/minify-disabled-on-empty-array/webpack.config.js
Labels: release: bug fix

#4985 ci: speed up CI by turning off sourcemap for arco-pro
  examples/arco-pro/rspack.config.js
Labels: team

#4988 feat(runtime): support module.parser.url=relative
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/relative_url.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/relative_url.js
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  webpack-test/configCases/asset-url/relative/test.filter.js
Labels: team, release: feature

#4987 fix: append builtin minify plugin for child compiler
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/tests/configCases/plugins/issue-4982/child.js
  packages/rspack/tests/configCases/plugins/issue-4982/index.js
  packages/rspack/tests/configCases/plugins/issue-4982/webpack.config.js
Labels: release: bug fix

#4983 fix: 🐛 class memeber side effects
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/a.js
  packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/index.js
  packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/lib.js
  packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/webpack.config.js
Labels: release: bug fix

#4984 fix: handle chunk relation
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/exist.js
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/index.js
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/parent-1.js
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/parent-2.js
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/shared.js
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/test.config.json
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/remove_parent_modules.rs
Labels: team, release: bug fix

#4990 feat(runtime): support __webpack_chunkname__
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_runtime/src/runtime_module/chunk_name.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  webpack-test/configCases/parsing/extended-api/test.filter.js
Labels: team, release: feature

#4998 fix(runtime): globals on require in runtime plugin
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: team, release: bug fix

#4993 feat: support __webpack_runtime_id__
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime_id.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  webpack-test/configCases/optimization/depend-on-runtimes/test.filter.js
Labels: team, release: feature

#4916 chore(runtime-diff): module chunk loading runtime module
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading_with_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/webpack.config.js
Labels: team

#5000 fix: parse left and right when eval failed for logic expr
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: bug fix

#5002 chore: add comparator for diff tester
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  packages/rspack-test-tools/src/compare/comparator.ts
  packages/rspack-test-tools/src/compare/index.ts
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/plugin/index.ts
  packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/webpack/module-placeholder-plugin.ts
Labels: team

#5003 fix: license-webpack-plugin failed to generate license for some of module
  packages/rspack/src/Module.ts
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/plugins/chunk-modules/index.js
  packages/rspack/tests/configCases/plugins/chunk-modules/webpack.config.js
Labels: team, release: bug fix

#5007 feat: stats for childCompiler
  packages/rspack/src/Compilation.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: need documentation, release: feature

#5009 revert: "chore: add comparator for diff tester"
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  packages/rspack-test-tools/src/compare/comparator.ts
  packages/rspack-test-tools/src/compare/index.ts
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/plugin/index.ts
  packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/webpack/module-placeholder-plugin.ts
Labels: team

#5011 chore: run benchmark on main branch
  .github/workflows/bench-main.yaml
Labels: team

#5012 chore(diff): add more diff cases
  crates/rspack_core/src/chunk.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/relative_url.js
  packages/rspack/tests/runtimeDiffCases/runtime-chunk-name/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-chunk-name/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-chunk-name/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-chunk-name/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-relative-url/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-relative-url/src/index.css
  packages/rspack/tests/runtimeDiffCases/runtime-relative-url/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-relative-url/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-relative-url/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-runtime-id/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-runtime-id/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-runtime-id/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-runtime-id/webpack.config.js
Labels: team

#5015 fix: stats childCompiler test
  packages/rspack/tests/Stats.test.ts
Labels: team, release: bug fix

#5016 chore(diff): scan diff cases by glob
  packages/rspack/package.json
  packages/rspack/tests/RuntimeDiff.diff.test.ts
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/async-node-module/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/async-node-module/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/async-node-module/src/wasm.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/async-node-module/src/wasm2.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/async-node-module/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/async-node-module/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/basic/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/basic/src/wasm.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/basic/src/wasm2.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/fetch/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/fetch/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/fetch/src/wasm.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/fetch/src/wasm2.wat
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/fetch/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-wasm-loading/fetch/webpack.config.js
  pnpm-lock.yaml
Labels: team

#5019 feat: add function type splitChunks chunks
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/builtin-plugin/WorkerPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/container/ContainerPlugin.ts
  packages/rspack/src/container/ContainerReferencePlugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/sharing/ProvideSharedPlugin.ts
  packages/rspack/tests/configCases/split-chunks/chunks-function/index.js
  packages/rspack/tests/configCases/split-chunks/chunks-function/lib1.js
  packages/rspack/tests/configCases/split-chunks/chunks-function/lib2.js
  packages/rspack/tests/configCases/split-chunks/chunks-function/shared.js
  packages/rspack/tests/configCases/split-chunks/chunks-function/webpack.config.js
Labels: team, need documentation, release: feature

#5020 feat: support rgb colors for ansi-html
  packages/rspack-dev-server/src/ansiHTML.js
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/ansiHTML.test.ts
Labels: team, release: feature

#5021 fix: runtime chunk order
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/utils/mod.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: bug fix

#4979 feat(cli): support to set output.path
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
Labels: release: feature

#5023 chore: update Readme.md
  README.md
  README.zh-CN.md
Labels: team

#5037 feat: support eval abstract equal
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_array_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5034 fix: add "symlinks" option to resolve config validation
  packages/rspack/src/config/zod.ts
Labels: release: bug fix

#5035 chore: remove #4325 in webpack-test
  crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
  webpack-test/cases/cjs-tree-shaking/reexports/test.filter.js
  webpack-test/cases/parsing/harmony-deep-exports/test.filter.js
  webpack-test/cases/parsing/harmony-duplicate-export/test.filter.js
Labels: team

#5036 fix(remove-parent-modules): only filter runtime chunk
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: bug fix

#5042 fix: 🐛 fix escape json
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_json/tests/fixtures/simple/json.json
  crates/rspack_plugin_json/tests/fixtures/simple/snapshot/output.snap
Labels: team, release: bug fix

#5032 refactor: make sure add all runtime globals when process_runtime_requirements
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap
  crates/rspack_plugin_html/tests/fixtures/variant/snapshot/output.snap
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  crates/rspack_plugin_wasm/src/loading_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/copyPlugin/build/main.js
Labels: team

#5043 fix: umd library integrate with newTreeshaking
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
Labels: team, release: bug fix

#4915 chore(runtime-diff): jsonp chunk loading runtime module
  crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap
  crates/rspack_plugin_html/tests/fixtures/variant/snapshot/output.snap
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_hmr.js
  packages/rspack/tests/RuntimeDiff.diff.test.ts
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/basic/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/basic/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/with-hmr/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/with-hmr/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/with-hmr/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/with-hmr/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-jsonp-chunk-loading/with-hmr/webpack.config.js
Labels: team

#4959 feat: isomorphism mf 1.0 and 1.5
  .eslintignore
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/container/expose_runtime_module.rs
  crates/rspack_plugin_mf/src/container/mod.rs
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/container/remotesLoading.js
  crates/rspack_plugin_mf/src/lib.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/consumesCommon.js
  crates/rspack_plugin_mf/src/sharing/consumesInitial.js
  crates/rspack_plugin_mf/src/sharing/consumesLoading.js
  crates/rspack_plugin_mf/src/sharing/initializeSharing.js
  crates/rspack_plugin_mf/src/sharing/mod.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_plugin.rs
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/ContainerPlugin.ts
  packages/rspack/src/container/ContainerReferencePlugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
  packages/rspack/src/container/remotesLoading.js
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/sharing/ProvideSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
  packages/rspack/src/sharing/ShareRuntimePlugin.ts
  packages/rspack/src/sharing/consumesLoading.js
  packages/rspack/src/sharing/initializeSharing.js
  webpack-test/packages/rspack/node_modules/make-dir/index.d.ts
  webpack-test/packages/rspack/node_modules/make-dir/index.js
  webpack-test/packages/rspack/node_modules/make-dir/license
  webpack-test/packages/rspack/node_modules/make-dir/package.json
  webpack-test/packages/rspack/node_modules/make-dir/readme.md
Labels: team, release: feature

#4994 fix: remove available modules from ancestor
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/foo.js
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/index.js
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/parent-1.js
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/parent-2.js
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/shared.js
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/test.config.json
  crates/rspack_core/src/build_chunk_graph/remove_parent_modules.rs
Labels: team, release: bug fix

#5047 chore(rspack_core): oxc_resolver v0.6.2
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team

#4924 refactor: diagnosable modules
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  x.mjs
Labels: team

#5051 feat: eval array and regexp in binary expr
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5050 fix: webpack-test/configCases/split-chunks/async-entries
  webpack-test/configCases/split-chunks/asnyc-entries/test.filter.js
Labels: team, release: bug fix

#5046 fix: extract_block_modules dependencies order
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/tests/cases/schemes/data-imports/webpack.config.js
Labels: team, release: bug fix

#5001 perf: use async fs
  packages/rspack/src/fileSystem.ts
  packages/rspack/src/util/memoize.ts
  packages/rspack/tests/Errors.test.ts
Labels: team, release: performance

#5059 fix: `ruleSetLogicalConditions.not should not just array
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
Labels: release: bug fix

#5061 feat: support pseudo webpack extension and custom module type
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack-cli/tests/build/basic/public/main.js
  packages/rspack-cli/tests/build/basic/public/main.js.map
  packages/rspack/tests/configCases/loader/match-module-type/foo.custom
  packages/rspack/tests/configCases/loader/match-module-type/index.js
  packages/rspack/tests/configCases/loader/match-module-type/loader-test.js
  packages/rspack/tests/configCases/loader/match-module-type/webpack.config.js
Labels: team, need documentation, release: feature

#5064 feat: eval template string in binary expr
  crates/rspack_plugin_javascript/src/utils/const/mod.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5049 feat: diagnostics in overlay
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_error/src/emitter.rs
  packages/rspack/tests/Compiler.test.ts
  packages/rspack/tests/Errors.test.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  webpack-test/configCases/plugins/environment-plugin/errors-sort.js
Labels: team, release: feature

#5069 fix: hmr css with filename
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/playground/cases/css/css-filename/index.test.ts
  packages/playground/cases/css/css-filename/rspack.config.js
  packages/playground/cases/css/css-filename/src/index.css
  packages/playground/cases/css/css-filename/src/index.js
Labels: team, release: bug fix

#5062 feat: add module parse error
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/diagnostics.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_error/src/error.rs
  crates/rspack_error/src/ext.rs
  crates/rspack_error/src/lib.rs
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/fixtures__char-based-offset-error-span.snap
  crates/rspack_error/tests/fixtures/html_syntax_error/fixtures__html_syntax_error.snap
  crates/rspack_error/tests/fixtures/js_syntax_error/fixtures__js_syntax_error.snap
  crates/rspack_error/tests/fixtures/jsx_syntax_error/fixtures__jsx_syntax_error.snap
  crates/rspack_error/tests/fixtures/recoverable_syntax_error/fixtures__recoverable_syntax_error.snap
  crates/rspack_error/tests/fixtures/sass-warnings/fixtures__sass-warnings.snap
  crates/rspack_error/tests/fixtures/ts_syntax_error/fixtures__ts_syntax_error.snap
  crates/rspack_error/tests/fixtures/tsx_syntax_error/fixtures__tsx_syntax_error.snap
  crates/rspack_error/tests/out_of_order/multi_json_syntax_error/fixtures__multi_json_syntax_error.snap
  crates/rspack_error/tests/out_of_order/multiple_file_syntax_error/fixtures__multiple_file_syntax_error.snap
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/swc_css_compiler.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/ast/parse.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/tests/Errors.test.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#5070 fix: serialize path of stats on windows
  packages/rspack/tests/StatsTestCases.test.ts
Labels: team, release: bug fix

#5073 feat: eval if-else stmt
  Cargo.lock
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/utils/const/if_stmt.rs
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/utils/const/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5075 chore: force build JS packages on CI
  package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-html/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
Labels: team

#5066 feat: deprecate apply options lazily
  packages/rspack-cli/package.json
  packages/rspack/src/Compiler.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  pnpm-lock.yaml
Labels: team, need documentation, release: feature

#5076 feat: introduce `is_strict` in scanner
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/utils/const/if_stmt.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
  packages/rspack/tests/cases/parsing/issue-4816/regexp/a.filtered.js
  packages/rspack/tests/cases/parsing/issue-4816/regexp/a.js
Labels: release: feature

#5080 fix: boolean matcher regexp
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
Labels: team, release: bug fix

#5083 fix: exportImportedspecifier interop
  crates/rspack_core/src/exports_info.rs
  packages/rspack/tests/configCases/tree-shaking/commonjs-reexport-interop/a.js
  packages/rspack/tests/configCases/tree-shaking/commonjs-reexport-interop/index.js
  packages/rspack/tests/configCases/tree-shaking/commonjs-reexport-interop/lib.js
  packages/rspack/tests/configCases/tree-shaking/commonjs-reexport-interop/package.json
  packages/rspack/tests/configCases/tree-shaking/commonjs-reexport-interop/webpack.config.js
Labels: team, release: bug fix

#5079 fix: OOM when use trace
  crates/rspack_core/src/compiler/compilation.rs
Labels: team, release: bug fix

#5014 chore: add comparator for diff tester
  .eslintignore
  .github/workflows/diff.yml
  .prettierignore
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/rspack.config.js
  packages/rspack-test-tools/src/compare/comparator.ts
  packages/rspack-test-tools/src/compare/index.ts
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/plugin/index.ts
  packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/reporter/diff-html.ts
  packages/rspack-test-tools/src/webpack/module-placeholder-plugin.ts
  packages/rspack-test-tools/template/diff.bundle.css
  packages/rspack-test-tools/template/diff.bundle.js
  packages/rspack-test-tools/template/diff.html
Labels: team

#5087 feat: support __webpack_is_included__
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/ignore_error_module_factory.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  packages/rspack/tests/cases/parsing/webpack-is-included/index.js
  packages/rspack/tests/cases/parsing/webpack-is-included/module1.js
  packages/rspack/tests/cases/parsing/webpack-is-included/module2.js
  packages/rspack/tests/cases/parsing/webpack-is-included/moduleUnused.js
  packages/rspack/tests/cases/parsing/webpack-is-included/moduleUsed.js
Labels: team, release: feature

#5055 fix: unnecessary import runtime code from css_loading_with_loading.js
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
Labels: release: bug fix

#4913 chore(runtime-diff): require chunk loading runtime module
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr_manifest.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/basic/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/basic/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/with-hmr/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/with-hmr/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/with-hmr/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/with-hmr/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/with-hmr/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/basic/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/basic/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/with-hmr/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/with-hmr/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/with-hmr/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/with-hmr/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-require-chunk-loading/with-hmr/webpack.config.js
Labels: team

#4914 chore(runtime-diff): import scripts chunk loading diff runtime module
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/basic/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/basic/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/with-hmr/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/with-hmr/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/with-hmr/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/with-hmr/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-import-scripts-chunk-loading/with-hmr/webpack.config.js
Labels: team

#5094 feat: eval regexp in require.context
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_array_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_new_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
  crates/rspack_regex/src/lib.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5084 feat: support error early bail
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/diagnostics.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/utils/import_var.rs
  crates/rspack_error/src/error.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Compiler.test.ts
  packages/rspack/tests/Errors.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/errors/experiments-css-off/webpack.config.js
  packages/rspack/tests/fixtures/empty-dependency.js
  webpack-test/cases/parsing/issue-2006/errors.js
  webpack-test/cases/parsing/issue-2006/test.filter.js
Labels: team, need documentation, release: feature

#4912 chore(runtime-diff): read file chunk loading runtime module
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_hmr_manifest.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_loading.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/basic/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/basic/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/with-hmr/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/with-hmr/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/with-hmr/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/with-hmr/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-read-file-chunk-loading/with-hmr/webpack.config.js
Labels: team

#5093 fix: pass define plugin to childCompiler
  packages/rspack/src/builtin-plugin/DefinePlugin.ts
  packages/rspack/tests/configCases/plugins/html-define/document.ejs
  packages/rspack/tests/configCases/plugins/html-define/index.js
  packages/rspack/tests/configCases/plugins/html-define/webpack.config.js
Labels: team, release: bug fix

#5098 fix: unique name in load script runtime module
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/basic/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/basic/src/async.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/basic/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/basic/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/basic/webpack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/unique-name/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/unique-name/src/async.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/unique-name/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/unique-name/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/unique-name/webpack.config.js
Labels: team, release: bug fix

#5099 fix: asset publicPath in css with rule asset generator
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack/tests/cases/css/rewrite-url-rule-public-path/index.css
  packages/rspack/tests/cases/css/rewrite-url-rule-public-path/index.js
  packages/rspack/tests/cases/css/rewrite-url-rule-public-path/logo.png
  packages/rspack/tests/cases/css/rewrite-url-rule-public-path/webpack.config.js
Labels: team, release: bug fix

#5102 feat: support `hooks.afterOptimizeModules`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/Compiler.test.ts
Labels: release: feature

#5092 fix: umd with library.export
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
Labels: team, release: bug fix

#5029 chore: remove heavy debug node `util.inspect` call
  packages/rspack/src/rspack.ts
Labels: team

#5095 chore: fix typos in JavaScript and TypeScript files
  .typos.toml
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_loading.js
  diffcases/arco-pro/src/pages/visualization/multi-dimension-data-analysis/data-overview.tsx
  packages/rspack-cli/src/globals.d.ts
  packages/rspack-dev-server/src/ansiHTML.js
  packages/rspack-plugin-html/src/index.ts
  packages/rspack-plugin-react-refresh/src/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team

#5109 fix: apply entry lazily warning message
  packages/rspack/src/rspackOptionsApply.ts
Labels: team, release: bug fix

#5105 feat: support custom filename for GetChunkFilenameRuntimeModule
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: team, release: feature

#5112 chore: send notification when main branch ci failed
  .github/workflows/ci.yml
  scripts/alert/lark.js
Labels: team

#5101 fix(mf1.5): remoteInfos when moduleIds is not named
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/container/remotesLoading.js
  crates/rspack_plugin_mf/src/sharing/initializeSharing.js
  crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
  packages/rspack/package.json
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/default.runtime.js
  pnpm-lock.yaml
Labels: team, release: bug fix

#5116 feat(mf): add version check warning for sharing
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/ignore_error_module_factory.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_plugin_mf/src/container/container_entry_module_factory.rs
  crates/rspack_plugin_mf/src/container/fallback_module_factory.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  packages/rspack/package.json
  pnpm-lock.yaml
  webpack-test/configCases/container/2-transitive-overriding/test.filter.js
  webpack-test/configCases/sharing/consume-module/test.filter.js
  webpack-test/configCases/sharing/no-override-loaded/node_modules/package/index.js
  webpack-test/configCases/sharing/no-override-loaded/node_modules/package/package.json
Labels: team, release: feature

#5113 feat: add diag test
  .prettierignore
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/diagnostics.test.ts
  packages/rspack/tests/diagnostics/parse-failed/index.js
  packages/rspack/tests/diagnostics/parse-failed/stats.err
  pnpm-lock.yaml
Labels: release: feature

#5119 fix(rspack-dev-server): remove webpack dep
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#5114 feat: support CommonJsSelfReferenceDependency
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/self_module_factory.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  packages/rspack/tests/cases/cjs-tree-shaking/self-reference/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/self-reference/reading-self-from-exports-call.js
  packages/rspack/tests/cases/cjs-tree-shaking/self-reference/reading-self-from-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/self-reference/reading-self-from-module-exports-call.js
  packages/rspack/tests/cases/cjs-tree-shaking/self-reference/reading-self-from-module-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/self-reference/reading-self-from-this.js
Labels: release: feature

#5127 feat: removes all deprecate warning in CI
  package.json
  packages/rspack/src/util/index.ts
  pnpm-lock.yaml
Labels: release: feature

#5126 feat: warning of magic comment
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
Labels: team, release: feature

#5125 perf: exports info hash
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: performance

#5128 fix(mf): should not have extra empty chunk
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  webpack-test/configCases/container/2-transitive-overriding/index.js
  webpack-test/configCases/container/2-transitive-overriding/test.filter.js
  webpack-test/configCases/container/3-container-full/test.filter.js
Labels: team, release: bug fix

#5129 fix: user freindly error msg for output.hashFunction
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/configCases/output/issue-4504/errors.js
  packages/rspack/tests/configCases/output/issue-4504/index.js
  packages/rspack/tests/configCases/output/issue-4504/webpack.config.js
Labels: release: bug fix

#4901 fix: library module renderStartup missing export
  crates/rspack_plugin_library/src/module_library_plugin.rs
  packages/rspack/tests/configCases/output-module/issue-4784/index.js
  packages/rspack/tests/configCases/output-module/issue-4784/m.js
  packages/rspack/tests/configCases/output-module/issue-4784/test.config.js
  packages/rspack/tests/configCases/output-module/issue-4784/webpack.config.js
  webpack-test/configCases/container/0-container-full/test.filter.js
  webpack-test/configCases/container/1-container-full/test.filter.js
  webpack-test/configCases/container/3-container-full/test.filter.js
  webpack-test/configCases/container/module-federation-with-shareScope/test.filter.js
Labels: release: bug fix

#5130 feat: support DependencyTemplate of CommonJsExportRequireDependency
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  packages/rspack/tests/cases/cjs-tree-shaking/export-require/exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require/foo.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require/module-exports-whole.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require/module-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require/this.js
Labels: team, release: feature

#5117 fix(plugin-runtime): `stringify_chunk` should escape special chars in chunk names as js\'s JSON.stringify do
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  packages/rspack/tests/configCases/chunk-loading/chunk-name/a.js
  packages/rspack/tests/configCases/chunk-loading/chunk-name/index.js
  packages/rspack/tests/configCases/chunk-loading/chunk-name/test.config.js
  packages/rspack/tests/configCases/chunk-loading/chunk-name/webpack.config.js
Labels: release: bug fix

#5134 fix: entryOptions should able to merge
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  packages/rspack/tests/configCases/container/.2-container-full/webpack.config.js
  packages/rspack/tests/configCases/container/0-container-full/webpack.config.js
  packages/rspack/tests/configCases/container/1-container-full/webpack.config.js
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/container/2-container-full/test.filter.js
Labels: team, release: bug fix

#5124 fix: should not create additional missing modules
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/cache/occasion/resolve_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/ignore_error_module_factory.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_core/src/self_module_factory.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module_factory.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/container/fallback_module_factory.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  packages/rspack/tests/Compiler.test.ts
  packages/rspack/tests/Errors.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/warnings/not-fully-specified/index.js
  packages/rspack/tests/configCases/warnings/missing-module/index.js
  packages/rspack/tests/diagnostics/empty-dependency/index.js
  packages/rspack/tests/diagnostics/empty-dependency/stats.err
Labels: team, release: bug fix

#5140 fix(treeshaking): calculate add_connection_states right
  crates/rspack_core/src/module_graph/connection.rs
Labels: team, release: bug fix

#5141 refactor: 🤖 avoid clone exports info
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
Labels: team

#5142 fix: sort errors and warnings in stats based on offsets
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/stats.rs
Labels: team, release: bug fix

#5144 fix: harmony export default from should be a parse error
  crates/rspack_plugin_javascript/src/utils/mod.rs
  packages/rspack/tests/case.template.ts
  packages/rspack/tests/cases/cjs-interop/non-existing-export/warnings.js
  packages/rspack/tests/cases/context/issue-5750/warnings.js
  packages/rspack/tests/cases/css/rewrite-url-auto-public-path/warnings.js
  packages/rspack/tests/cases/css/rewrite-url-with-css-filename/warnings.js
  packages/rspack/tests/cases/errors/harmony-export-default-from/bar.js
  packages/rspack/tests/cases/errors/harmony-export-default-from/errors.js
  packages/rspack/tests/cases/errors/harmony-export-default-from/foo.js
  packages/rspack/tests/cases/errors/harmony-export-default-from/index.js
  packages/rspack/tests/cases/parsing/harmony-duplicate-export/warnings.js
  packages/rspack/tests/cases/parsing/harmony-export-precedence/warnings.js
  packages/rspack/tests/cases/parsing/harmony-info/warnings.js
  packages/rspack/tests/cases/parsing/harmony-star-conflict/warnings.js
  packages/rspack/tests/cases/warnings/not-fully-specified/warnings.js
Labels: team, release: bug fix

#5145 fix: import meta url property
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/esm/import-meta-property/index.js
Labels: team, release: bug fix

#5148 fix: enable more mf v1.5 tests
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/tests/configCases/container/0-transitive-overriding/webpack.config.js
  packages/rspack/tests/configCases/container/1-transitive-overriding/webpack.config.js
  packages/rspack/tests/configCases/container/2-container-full/App.js
  packages/rspack/tests/configCases/container/2-container-full/Self.js
  packages/rspack/tests/configCases/container/2-container-full/index.js
  packages/rspack/tests/configCases/container/2-container-full/node_modules/package.json
  packages/rspack/tests/configCases/container/2-container-full/node_modules/react.js
  packages/rspack/tests/configCases/container/2-container-full/package.json
  packages/rspack/tests/configCases/container/2-container-full/upgrade-react.js
  packages/rspack/tests/configCases/container/2-container-full/webpack.config.js
  packages/rspack/tests/configCases/container/2-transitive-overriding/index.js
  packages/rspack/tests/configCases/container/2-transitive-overriding/shared.js
  packages/rspack/tests/configCases/container/2-transitive-overriding/webpack.config.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/App.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/ComponentB.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/ComponentC.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/index.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/node_modules/package.json
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/node_modules/react.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/package.json
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/test.config.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/upgrade-react.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/webpack.config.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/index.js
  packages/rspack/tests/hotCases/worker/move-between-runtime/worker.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk-with-hash/index.js
  packages/rspack/tests/runtimeCases/runtime/dynamic-css-chunk/index.js
Labels: team, release: bug fix

#5136 chore: add module federation example
  examples/module-federation-v1.5/app/package.json
  examples/module-federation-v1.5/app/rspack.config.js
  examples/module-federation-v1.5/app/src/App.js
  examples/module-federation-v1.5/app/src/bootstrap.js
  examples/module-federation-v1.5/app/src/index.js
  examples/module-federation-v1.5/app/src/runtimePlugins/logger.js
  examples/module-federation-v1.5/lib1/package.json
  examples/module-federation-v1.5/lib1/rspack.config.js
  examples/module-federation-v1.5/lib1/src/Component.js
  examples/module-federation-v1.5/lib1/src/bootstrap.js
  examples/module-federation-v1.5/lib1/src/index.js
  examples/module-federation-v1.5/lib2/package.json
  examples/module-federation-v1.5/lib2/rspack.config.js
  examples/module-federation-v1.5/lib2/src/Component.js
  examples/module-federation-v1.5/lib2/src/LazyComponent.js
  examples/module-federation-v1.5/package.json
  examples/module-federation-v1/app/package.json
  examples/module-federation-v1/app/rspack.config.js
  examples/module-federation-v1/app/src/App.js
  examples/module-federation-v1/app/src/bootstrap.js
  examples/module-federation-v1/app/src/index.js
  examples/module-federation-v1/lib1/package.json
  examples/module-federation-v1/lib1/rspack.config.js
  examples/module-federation-v1/lib1/src/Component.js
  examples/module-federation-v1/lib1/src/bootstrap.js
  examples/module-federation-v1/lib1/src/index.js
  examples/module-federation-v1/lib2/package.json
  examples/module-federation-v1/lib2/rspack.config.js
  examples/module-federation-v1/lib2/src/Component.js
  examples/module-federation-v1/lib2/src/LazyComponent.js
  examples/module-federation-v1/package.json
  packages/rspack/src/container/ModuleFederationPlugin.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: team

#5146 fix: external modules in esm
  crates/rspack_core/src/external_module.rs
  packages/rspack/tests/configCases/library/esm-external/index.js
  packages/rspack/tests/configCases/library/esm-external/webpack.config.js
Labels: team, release: bug fix

#5137 fix: should store dependencies even if module factorization is failed
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
Labels: team, release: bug fix

#5155 perf: delete useless calls
  packages/rspack/src/config/defaults.ts
Labels: release: performance

#5153 feat: support custom banner
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/tests/configCases/plugins/issue-5068-1/index.js
  packages/rspack/tests/configCases/plugins/issue-5068-1/webpack.config.js
  packages/rspack/tests/configCases/plugins/issue-5068-2/index.js
  packages/rspack/tests/configCases/plugins/issue-5068-2/webpack.config.js
  pnpm-lock.yaml
Labels: release: feature

#5156 feat: bump tracing to support `NO_COLOR`
  Cargo.lock
  Cargo.toml
Labels: release: feature
