Repository web-infra-dev/rspack, pull requests merged in 2023-06, with the labels that each got.

#3372 fix: fix wrong context in external function
  crates/rspack_plugin_externals/src/plugin.rs
Labels: release: bug fix

#3384 chore: 🤖 disable for now
  .github/workflows/reusable-build.yml
Labels: team

#3380 feat: nested module rules
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
Labels: team, release: feature

#3385 fix: update lock for ecosystem-ci
  pnpm-lock.yaml
Labels: team, release: bug fix

#3388 fix: metric recover
  .github/workflows/reusable-build.yml
  webpack-test/scripts/pr-diff.js
Labels: team, release: bug fix

#3389 chore: 🤖 tweak word case
  packages/rspack/src/compiler.ts
Labels: team

#3394 chore: delete npm folder
  .gitignore
  npm/darwin-arm64/README.md
  npm/darwin-arm64/package.json
  npm/darwin-x64/README.md
  npm/darwin-x64/package.json
  npm/linux-arm64-gnu/README.md
  npm/linux-arm64-gnu/package.json
  npm/linux-arm64-musl/README.md
  npm/linux-arm64-musl/package.json
  npm/linux-x64-gnu/README.md
  npm/linux-x64-gnu/package.json
  npm/linux-x64-musl/README.md
  npm/linux-x64-musl/package.json
  npm/win32-arm64-msvc/README.md
  npm/win32-arm64-msvc/package.json
  npm/win32-ia32-msvc/README.md
  npm/win32-ia32-msvc/package.json
  npm/win32-x64-msvc/README.md
  npm/win32-x64-msvc/package.json
Labels: team

#3350 fix(rust): use jemallocator for linux gnu, mimalloc for everything else
  .github/actions/docker-build/action.yml
  .github/workflows/reusable-build.yml
  Cargo.lock
  Cargo.toml
  crates/bench/Cargo.toml
  crates/bench/src/main.rs
  crates/node_binding/Cargo.toml
  crates/node_binding/src/lib.rs
  crates/rspack/Cargo.toml
  crates/rspack/benches/main.rs
  crates/rspack_build/Cargo.toml
Labels: team, release: bug fix

#3393 chore: add back vue build
  examples/vue/package.json
  examples/vue3-vanilla/package.json
  pnpm-lock.yaml
Labels: team

#3395 chore: remove commit step when publishing
  scripts/release/publish.mjs
Labels: team

#3378 feat: make options having a single source of truth
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/package.json
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/_rewrite.ts
  packages/rspack/src/config/zod/builtins.ts
  packages/rspack/src/config/zod/devtool.ts
  packages/rspack/src/config/zod/entry.ts
  packages/rspack/src/config/zod/experiments.ts
  packages/rspack/src/config/zod/externals-presets.ts
  packages/rspack/src/config/zod/externals-type.ts
  packages/rspack/src/config/zod/externals.ts
  packages/rspack/src/config/zod/index.ts
  packages/rspack/src/config/zod/infrastructure-logging.ts
  packages/rspack/src/config/zod/module.ts
  packages/rspack/src/config/zod/node.ts
  packages/rspack/src/config/zod/output.ts
  packages/rspack/src/config/zod/snapshot.ts
  packages/rspack/src/config/zod/stats.ts
  packages/rspack/src/config/zod/target.ts
  packages/rspack/src/config/zod/watch-options.ts
  packages/rspack/src/rspack.ts
  pnpm-lock.yaml
Labels: team, release: feature

#3367 feat: resource within scheme
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/rspack/tests/tree-shaking/context-module/expected/main.js
  crates/rspack_core/src/cache/occasion/resolve_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/context.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/utils/hooks.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_error/src/error.rs
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
  crates/rspack_ids/src/named_chunk_ids_plugin.rs
  crates/rspack_ids/src/named_module_ids_plugin.rs
  crates/rspack_ids/src/stable_named_chunk_ids_plugin.rs
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_runner/src/scheme.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_html/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/utils.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/new_node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/tests/fixtures/issuse_2960/expected/main.js
  crates/rspack_plugin_split_chunks_new/src/plugin/max_size.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/tests/IgnorePlugin.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/schemes/resource-within-scheme/.gitignore
  packages/rspack/tests/cases/schemes/resource-within-scheme/index.js
  packages/rspack/tests/cases/schemes/resource-within-scheme/node_modules/polyfill/index.js
  packages/rspack/tests/cases/schemes/resource-within-scheme/node_modules/polyfill/package.json
  packages/rspack/tests/cases/schemes/resource-within-scheme/webpack.config.js
  packages/rspack/tests/ignorePlugin/index.js
  packages/rspack/tests/statsCases/ignore-plugin/globalIndex.js
  packages/rspack/tests/statsCases/ignore-plugin/index.js
  packages/rspack/tests/statsCases/ignore-plugin/locals/en.js
  packages/rspack/tests/statsCases/ignore-plugin/locals/zh.js
  packages/rspack/tests/statsCases/ignore-plugin/webpack.config.js
Labels: release: feature

#3397 feat: support file uri
  Cargo.lock
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/utils/module_rules.rs
  crates/rspack_loader_runner/src/scheme.rs
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_schemes/src/file_uri.rs
  crates/rspack_plugin_schemes/src/lib.rs
  packages/rspack/tests/cases/schemes/file-url/.gitignore
  packages/rspack/tests/cases/schemes/file-url/index.js
  packages/rspack/tests/cases/schemes/file-url/src with spaces/module.js
  packages/rspack/tests/cases/schemes/file-url/webpack.config.js
Labels: team, release: feature

#3398 chore: add vue2-ts example
  examples/vue/src/App.vue
  examples/vue/src/assets/App.vue
  examples/vue/src/assets/components/HelloWorld.vue
  examples/vue/src/assets/main.js
  examples/vue2-ts/index.html
  examples/vue2-ts/package.json
  examples/vue2-ts/rspack.config.js
  examples/vue2-ts/src/App.vue
  examples/vue2-ts/src/assets/rspack.svg
  examples/vue2-ts/src/assets/vue.svg
  examples/vue2-ts/src/components/HelloWorld.vue
  examples/vue2-ts/src/main.ts
  examples/vue2-ts/src/style.css
  examples/vue3-vanilla/src/assets/App.vue
  examples/vue3-vanilla/src/assets/components/HelloWorld.vue
  examples/vue3-vanilla/src/assets/main.js
  pnpm-lock.yaml
Labels: team

#3400 chore: support short build commands
  x.mjs
Labels: team

#3390 feat: add finishMake hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compiler.ts
  packages/rspack/tests/configCases/hooks/compilation-hooks/a.js
  packages/rspack/tests/configCases/hooks/compilation-hooks/index.js
  packages/rspack/tests/configCases/hooks/compilation-hooks/webpack.config.js
Labels: release: feature

#2153 feat: create-rspack add template-vue
  .changeset/many-glasses-applaud.md
  packages/create-rspack/index.js
  packages/create-rspack/template-vue/_gitignore
  packages/create-rspack/template-vue/index.html
  packages/create-rspack/template-vue/package.json
  packages/create-rspack/template-vue/rspack.config.js
  packages/create-rspack/template-vue/src/App.vue
  packages/create-rspack/template-vue/src/assets/rspack.svg
  packages/create-rspack/template-vue/src/assets/vue.svg
  packages/create-rspack/template-vue/src/components/HelloWorld.vue
  packages/create-rspack/template-vue/src/main.js
  packages/create-rspack/template-vue/src/style.css
  pnpm-lock.yaml
Labels: on hold, release: feature

#3405 fix: fix aarch64-unknown-linux-gnu not building jemallocator
  .github/workflows/reusable-build.yml
Labels: team, release: bug fix

#3318 feat: Add 'succeedModule' and 'stillValidModule' hooks
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/js_values/module.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/tests/cases/hooks/stillValidModule/package.json
  packages/rspack/tests/cases/hooks/stillValidModule/plugins/MyStillValidModulePlugin.js
  packages/rspack/tests/cases/hooks/stillValidModule/src/answer.js
  packages/rspack/tests/cases/hooks/stillValidModule/src/index.js
  packages/rspack/tests/cases/hooks/stillValidModule/webpack.config.js
  packages/rspack/tests/cases/hooks/succeedModule/package.json
  packages/rspack/tests/cases/hooks/succeedModule/plugins/MySucceedModulePlugin.js
  packages/rspack/tests/cases/hooks/succeedModule/src/answer.js
  packages/rspack/tests/cases/hooks/succeedModule/src/index.js
  packages/rspack/tests/cases/hooks/succeedModule/webpack.config.js
Labels: release: feature

#3399 fix: remove css updatedModulesList at hmr
  crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_hmr.js
Labels: team, release: bug fix

#3362 chore(packages): upload less files to npm
  packages/postcss-loader/package.json
  packages/rspack-dev-client/package.json
  packages/rspack-dev-middleware/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-html/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-node-polyfill/package.json
Labels: team

#3411 fix: shouldn't diff hot update chunk at hmr
  crates/rspack_core/src/compiler/hmr.rs
Labels: team, release: bug fix

#3413 feat(config): friendly config error message
  packages/rspack/package.json
  packages/rspack/src/config/index.ts
  packages/rspack/src/error/InvalidateConfiguration.ts
  packages/rspack/src/rspack.ts
  pnpm-lock.yaml
Labels: team, release: feature

#3415 fix: support config version when emitAsset
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/asset.rs
  packages/rspack/src/util/index.ts
Labels: team, release: bug fix

#3416 feat(config): zod schema for optimization
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/_rewrite.ts
  packages/rspack/src/config/zod/optimization/index.ts
  packages/rspack/src/config/zod/optimization/split-chunks.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#3420 feat(splitChunks): support passing `false` to `splitChunks.{cacheGroup}.xxx`
  crates/node_binding/binding.d.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/optimization/split-chunks.ts
Labels: team, release: feature

#3414 feat: electron support
  crates/node_binding/binding.d.ts
  crates/rspack/tests/fixtures/dynamic-import/expected/main.js
  crates/rspack/tests/fixtures/dynamic-import/expected/runtime.js
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/target.rs
  crates/rspack_plugin_externals/src/electron_target_plugin.rs
  crates/rspack_plugin_externals/src/lib.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/externals-presets.ts
  packages/rspack/src/config/zod/target.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/target/electron-renderer/.gitignore
  packages/rspack/tests/configCases/target/electron-renderer/index.js
  packages/rspack/tests/configCases/target/electron-renderer/node_modules/foo/browser.js
  packages/rspack/tests/configCases/target/electron-renderer/node_modules/foo/main.js
  packages/rspack/tests/configCases/target/electron-renderer/node_modules/foo/package.json
  packages/rspack/tests/configCases/target/electron-renderer/webpack.config.js
Labels: team, release: feature

#3427 chore: fix release mr
  npm/darwin-arm64/CHANGELOG.md
Labels: team

#3429 chore: add release nigthly after full release
  .github/workflows/release.yml
Labels: team

#3426 fix: sourcemap as an empty string
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/tests/configCases/loader/issue-3418/index.js
  packages/rspack/tests/configCases/loader/issue-3418/lib.js
  packages/rspack/tests/configCases/loader/issue-3418/loader.js
  packages/rspack/tests/configCases/loader/issue-3418/webpack.config.js
Labels: team, release: bug fix

#3432 chore(webpack-test): --forceExit for open handles
  webpack-test/package.json
Labels: team

#3442 fix(types): type error for `runtimeChunk`
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/optimization/index.ts
Labels: team, release: bug fix

#3443 chore: fix binding
  npm/win32-x64-msvc/package.json
Labels: team

#3445 test: webpack cache deps test to file deps test
  .gitignore
  packages/rspack/tests/configCases/split-chunks/max-size-casing/webpack.config.js
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/cache-dependencies/managed-items-unsafe-cache/test.filter.js
  webpack-test/configCases/cache-dependencies/managed-items/test.filter.js
  webpack-test/configCases/dependencies/file-dependencies/extra.js
  webpack-test/configCases/dependencies/file-dependencies/index.js
  webpack-test/configCases/dependencies/file-dependencies/loader.js
  webpack-test/configCases/dependencies/file-dependencies/node_modules/package/extra.js
  webpack-test/configCases/dependencies/file-dependencies/node_modules/package/index.js
  webpack-test/configCases/dependencies/file-dependencies/node_modules/package/package.json
  webpack-test/configCases/dependencies/file-dependencies/webpack.config.js
Labels: team

#3271 fix(context_module_cache): fix cache directory bug
  crates/rspack_core/src/cache/snapshot/manager.rs
  packages/rspack/tests/configCases/cache/issuse_3254/a/a.js
  packages/rspack/tests/configCases/cache/issuse_3254/index.js
  packages/rspack/tests/configCases/cache/issuse_3254/webpack.config.js
Labels: p2-signifincant, release: bug fix, ready to review

#3450 chore: use latest npm version as snapshot prefix
  scripts/release/version.mjs
Labels: team

#3455 feat: use immutable reference for process asset hook
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_real_content_hash/src/lib.rs
Labels: team, release: feature

#3458 feat: zod schema for `buliltins.postcss` and deprecate `buliltins.postcss`
  packages/rspack/src/config/zod/_rewrite.ts
  packages/rspack/src/config/zod/builtins.ts
Labels: team, release: feature

#3464 feat: make plugin driver immutable
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/loader/process_resource.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/utils/hooks.rs
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
  crates/rspack_ids/src/named_chunk_ids_plugin.rs
  crates/rspack_ids/src/named_module_ids_plugin.rs
  crates/rspack_ids/src/stable_named_chunk_ids_plugin.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_remove_empty_chunks/src/lib.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/basic_runtime_requirements.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/hot_module_replacement.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
Labels: team, release: feature

#3422 feat: support asset generator data url and publicPath
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_asset/tests/fixtures/webpack/asset-simple/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/5b6d4936f12d1301.svg
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/8c7236080ec784a5.svg
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/main.js
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/builtins.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/cases/css/rewrite-url-with-css-filename/index.js
  packages/rspack/tests/cases/css/rewrite-url/index.js
  packages/rspack/tests/cases/schemes/data-imports/index.js
  webpack-test/configCases/contenthash/assets/test.filter.js
  webpack-test/configCases/contenthash/assets/webpack.config.js
  webpack-test/configCases/contenthash/include-chunk-id/test.filter.js
  webpack-test/configCases/custom-hash-function/xxhash/test.filter.js
Labels: team, release: feature

#3469 fix: partially fix polyfill
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/expected/main.js
  crates/rspack/tests/tree-shaking/ts-target-es5/expected/main.js
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  examples/basic/rspack.config.js
  packages/rspack/tests/configCases/target/web-es5-issue-2664/index.js
  packages/rspack/tests/configCases/target/web-es5-issue-2664/webpack.config.js
Labels: team, release: bug fix

#3473 feat(splitChunks): support passing `RegExp` to `splitChunks.chunks`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/ext/js_string_ext.rs
  crates/rspack_binding_options/src/ext/mod.rs
  crates/rspack_binding_options/src/js_values/js_reg_exp.rs
  crates/rspack_binding_options/src/js_values/mod.rs
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
  packages/rspack/src/config/zod/optimization/split-chunks.ts
  packages/rspack/tests/configCases/split-chunks/issue-17332/bar.js
  packages/rspack/tests/configCases/split-chunks/issue-17332/foo.js
  packages/rspack/tests/configCases/split-chunks/issue-17332/index.js
  packages/rspack/tests/configCases/split-chunks/issue-17332/test.config.js
  packages/rspack/tests/configCases/split-chunks/issue-17332/webpack.config.js
Labels: team, release: feature

#3472 feat: support for partially enabled incremental rebuilds
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/cache/local/code_splitting_cache.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/schema.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/experiments.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#3478 chore(devServer): use webpack-dev-middleware instead of @rspack/dev-middleware
  packages/rspack-cli/tsconfig.json
  packages/rspack-dev-middleware/src/index.ts
  packages/rspack-dev-server/package.json
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tsconfig.json
  pnpm-lock.yaml
Labels: team

#3482 fix(splitChunk): custom cacheGroup default priority consistent with webpack
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  packages/rspack/tests/configCases/split-chunks/default-priority/a.js
  packages/rspack/tests/configCases/split-chunks/default-priority/b.js
  packages/rspack/tests/configCases/split-chunks/default-priority/c.js
  packages/rspack/tests/configCases/split-chunks/default-priority/index.js
  packages/rspack/tests/configCases/split-chunks/default-priority/test.config.js
  packages/rspack/tests/configCases/split-chunks/default-priority/webpack.config.js
Labels: team, release: bug fix

#3480 chore: trigger nightly ecosystem-ci after nightly release
  .github/workflows/release-nightly.yml
  scripts/release/publish.mjs
Labels: team

#3486 fix(provide): fix object-expr
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/provide.rs
  crates/rspack_plugin_javascript/tests/fixtures/provide/expected/main.js
  crates/rspack_plugin_javascript/tests/fixtures/provide/index.js
  crates/rspack_plugin_javascript/tests/fixtures/provide/name.js
  crates/rspack_plugin_javascript/tests/fixtures/provide/test.config.json
Labels: release: bug fix

#3490 chore(rust): bump rustc to v1.70.0 (nightly-2023-06-01)
  .cargo/config.toml
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/dependency/code_generatable.rs
  crates/rspack_plugin_split_chunks/src/chunks_info_item.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/chunk.rs
  crates/rspack_regex/tests/main.rs
  crates/rspack_symbol/src/lib.rs
  packages/rspack/tests/configCases/builtins/react-runtime-automic/index.jsx
  rust-toolchain.toml
Labels: team

#3495 feat: validate the passing object whether it's a `RegExp`
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_napi_shared/src/ext/js_string_ext.rs
  crates/rspack_napi_shared/src/ext/mod.rs
  crates/rspack_napi_shared/src/js_values/js_reg_exp.rs
  crates/rspack_napi_shared/src/js_values/mod.rs
  crates/rspack_napi_shared/src/lib.rs
  crates/rspack_napi_shared/src/utils.rs
Labels: team, release: feature

#3491 ci: adjust timeout-minutes for CI because mac is too slow
  .github/workflows/reusable-build.yml
Labels: team

#3494 fix: Base64Error caused by unclean base64
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_base64/Cargo.toml
  crates/rspack_base64/src/lib.rs
  crates/rspack_plugin_schemes/src/data_uri.rs
  packages/rspack/tests/cases/schemes/data-imports/bad-base64.css
  packages/rspack/tests/cases/schemes/data-imports/index.css
  packages/rspack/tests/cases/schemes/data-imports/index.js
  packages/rspack/tests/cases/schemes/data-imports/webpack.config.js
  packages/rspack/tests/cases/schemes/file-url/webpack.config.js
Labels: team, release: bug fix

#3498 feat(config): zod scheme for plugins
  packages/rspack/src/config/zod/_rewrite.ts
  packages/rspack/src/config/zod/index.ts
  packages/rspack/src/config/zod/plugins.ts
Labels: release: feature

#3496 feat: support compilation.rebuildModule
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/compilation.rs
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/cache/storage/memory.rs
  crates/rspack_core/src/cache/storage/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/rebuild_deps_builder.rs
  crates/rspack_core/src/compiler/mod.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/util/MergeCaller.ts
  packages/rspack/tests/configCases/compilation/rebuild-module/a.js
  packages/rspack/tests/configCases/compilation/rebuild-module/index.js
  packages/rspack/tests/configCases/compilation/rebuild-module/loader.js
  packages/rspack/tests/configCases/compilation/rebuild-module/webpack.config.js
Labels: team, release: feature

#3509 test(splitChunks): migrate more tests at `test/configCases/split-chunks`
  packages/rspack/tests/configCases/split-chunks/_issue-12307/a-only-module.js
  packages/rspack/tests/configCases/split-chunks/_issue-12307/a.js
  packages/rspack/tests/configCases/split-chunks/_issue-12307/b.js
  packages/rspack/tests/configCases/split-chunks/_issue-12307/index.js
  packages/rspack/tests/configCases/split-chunks/_issue-12307/shared-module.js
  packages/rspack/tests/configCases/split-chunks/_issue-12307/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/issue-11337/a.js
  packages/rspack/tests/configCases/split-chunks/issue-11337/b.js
  packages/rspack/tests/configCases/split-chunks/issue-11337/index.js
  packages/rspack/tests/configCases/split-chunks/issue-11337/module1.js
  packages/rspack/tests/configCases/split-chunks/issue-11337/module2.js
  packages/rspack/tests/configCases/split-chunks/issue-11337/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/a.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/b.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/index.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/test.config.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/vendor/vendor-a.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/vendor/vendor-b.js
  packages/rspack/tests/configCases/split-chunks/issue-8908/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/issue-9491/index.js
  packages/rspack/tests/configCases/split-chunks/issue-9491/test.config.js
  packages/rspack/tests/configCases/split-chunks/issue-9491/webpack.config.js
Labels: team

#3510 fix(deps): use `zod-validation-error@1.2.0` to support `node@^14.17`
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#3512 chore: use snapshot to test hash and css modules classname
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/cases/css/rewrite-url-with-css-filename/index.js
  packages/rspack/tests/cases/css/rewrite-url/index.js
  packages/rspack/tests/configCases/builtins/css-modules-composes-preprocessers/index.js
  packages/rspack/tests/configCases/builtins/css-modules-composes-sass/index.js
  packages/rspack/tests/configCases/builtins/css-modules-composes/index.js
  packages/rspack/tests/configCases/builtins/css-modules-dedupe/index.js
  packages/rspack/tests/configCases/builtins/css-modules-exports-only/index.js
  packages/rspack/tests/configCases/builtins/css-modules-local-ident-name-hash/index.js
  packages/rspack/tests/configCases/builtins/css-modules-local-ident-name-path/src/index.js
  packages/rspack/tests/configCases/builtins/css-modules-locals-convention-camelCase/index.js
  packages/rspack/tests/configCases/builtins/css-modules-locals-convention-camelCaseOnly/index.js
  packages/rspack/tests/configCases/builtins/css-modules-locals-convention-dashes/index.js
  packages/rspack/tests/configCases/builtins/css-modules-pseudo/index.js
  packages/rspack/tests/configCases/builtins/css-modules-simple/index.js
Labels: team

#3529 refactor(css): Remove unnecessary and structure code, add comments
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/expected/main.css
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/tests/fixtures/custom/http_import/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/custom/modules-ident-name/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/postcss/default/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/postcss/pxtorem/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/postcss/simple-config/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-charset/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/default-options/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/multiple-entry/expected/main-one.css
  crates/rspack_plugin_css/tests/fixtures/webpack/multiple-entry/expected/main-two.css
  crates/rspack_plugin_css/tests/fixtures/webpack/nested/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/output-iife/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/shared-import/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-async-load-css/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-async/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-commonjs-syntax/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-es-module-syntax/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/simple-multiple/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/simple/expected/main.css
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/cases/schemes/data-imports/index.js
Labels: team

#3531 feat(css): emit debug info in development mode
  crates/rspack_core/src/options/mode.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack/tests/__snapshots__/case.test.ts.snap
Labels: team, release: feature

#3468 feat(core): support async-node target
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_external_install_chunk.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_hmr.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_hmr_manifest.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_on_chunk_load.js
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/target.ts
  packages/rspack/tests/configCases/target/async-node/index.js
  packages/rspack/tests/configCases/target/async-node/webpack.config.js
  webpack-test/TestCases.template.js
  webpack-test/cases/json/data/test.filter.js
  webpack-test/configCases/simple/empty-config/test.filter.js
  webpack-test/configCases/simple/multi-compiler-functions-export/test.filter.js
  webpack-test/configCases/simple/multi-compiler-functions/test.filter.js
  webpack-test/configCases/simple/multi-compiler/test.filter.js
  webpack-test/jest.config.js
  webpack-test/package.json
Labels: team, release: feature

#3535 fix(css): should skip when `last_module == selected_module` and align more with Webpack
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
Labels: team, release: bug fix

#3382 feat: support builtin swc-loader
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_loader_swc/.gitignore
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/LICENSE
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures/esm/expected/main.js
  crates/rspack_loader_swc/tests/fixtures/esm/index.js
  crates/rspack_loader_swc/tests/fixtures/esm/test.config.json
  crates/rspack_loader_swc/tests/fixtures/ts/expected/main.js
  crates/rspack_loader_swc/tests/fixtures/ts/index.tsx
  crates/rspack_loader_swc/tests/fixtures/ts/test.config.json
  crates/rspack_loader_swc/tests/my_first_plugin.wasm
  crates/rspack_loader_swc/tests/swc-plugin/expected/index.js
  crates/rspack_loader_swc/tests/swc-plugin/expected/simple.js
  crates/rspack_loader_swc/tests/swc-plugin/index.js
  crates/rspack_plugin_javascript/src/visitors/dependency/hmr_scanner.rs
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/src/test_config.rs
  examples/builtin-swc-loader/.gitignore
  examples/builtin-swc-loader/index.html
  examples/builtin-swc-loader/package.json
  examples/builtin-swc-loader/rspack.config.js
  examples/builtin-swc-loader/src/App.css
  examples/builtin-swc-loader/src/App.jsx
  examples/builtin-swc-loader/src/index.css
  examples/builtin-swc-loader/src/index.jsx
  examples/builtin-swc-loader/src/logo.svg
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/loader/loader-builtin-swc/index.js
  packages/rspack/tests/configCases/loader/loader-builtin-swc/webpack.config.js
  packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/index.js
  packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/webpack.config.js
  pnpm-lock.yaml
Labels: release: feature

#3536 perf: compilation.*Dependencies cache results and merge call
  packages/rspack/src/compilation.ts
  packages/rspack/src/util/MergeCaller.ts
  packages/rspack/src/util/fake.ts
Labels: team, release: performance

#3537 chore: add project governance
  GOVERNANCE.md
Labels: team

#3514 fix: example angular bundle size is a lot bigger than webpack
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/tree_shaking/debug_helper.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  examples/angular/angular.json
  examples/angular/package.json
  examples/angular/rspack.config.js
  examples/angular/webpack.config.js
  packages/rspack-plugin-minify/src/index.js
  packages/rspack/src/compiler.ts
  packages/rspack/tests/configCases/tree-shaking/assets1/package/a.svg
  packages/rspack/tests/configCases/tree-shaking/assets1/package/b.svg
  pnpm-lock.yaml
Labels: team, release: bug fix

#3541 test: 💍 support test.filter.js return string
  webpack-test/lib/util/filterUtil.js
Labels: team

#3540 fix: 🐛 ignore github ID for typos check
  .typos.toml
Labels: team, release: bug fix

#3374 ci: use debug build for tests
  .github/actions/docker-build/action.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#3549 chore: correct comments
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/chunk.rs
Labels: team

#3376 fix: migrate more webpack library test
  .typos.toml
  Cargo.lock
  crates/rspack/tests/fixtures/dynamic-import/expected/runtime.js
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.dd90b569897554bf.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.dd90b569897554bf.html
  crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html
  crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/wasm/memory/run.js
  packages/rspack/tests/configCases/library/0-create-library/a.js
  packages/rspack/tests/configCases/library/0-create-library/index.js
  packages/rspack/tests/configCases/library/0-create-library/nested.js
  packages/rspack/tests/configCases/library/0-create-library/non-external.js
  packages/rspack/tests/configCases/library/0-create-library/test.config.js
  packages/rspack/tests/configCases/library/0-create-library/webpack.config.js
  packages/rspack/tests/configCases/library/_1-use-library/.gitignore
  packages/rspack/tests/configCases/library/_1-use-library/default-test.js
  packages/rspack/tests/configCases/library/_1-use-library/index.js
  packages/rspack/tests/configCases/library/_1-use-library/node_modules/external.js
  packages/rspack/tests/configCases/library/_1-use-library/test.config.js
  packages/rspack/tests/configCases/library/_1-use-library/this-test.js
  packages/rspack/tests/configCases/library/_1-use-library/var-test.js
  packages/rspack/tests/configCases/library/_1-use-library/webpack.config.js
  packages/rspack/tests/configCases/library/array-window/index.js
  packages/rspack/tests/configCases/library/array-window/webpack.config.js
  packages/rspack/tests/configCases/library/invalid-name/errors.js
  packages/rspack/tests/configCases/library/invalid-name/index.js
  packages/rspack/tests/configCases/library/invalid-name/webpack.config.js
  webpack-test/Stats.test.js
Labels: team, release: bug fix

#3547 perf: 🤖 optimize tree shaking
  .gitignore
  crates/rspack/tests/tree-shaking/ts-target-es5/expected/main.js
  crates/rspack/tests/tree-shaking/webpack-innergraph-circular/expected/main.js
  crates/rspack_core/src/tree_shaking/visitor.rs
  packages/rspack-plugin-minify/src/index.js
Labels: team, release: performance

#3560 fix: windows ci
  packages/rspack/tests/configCases/library/_0-create-library/a.js
  packages/rspack/tests/configCases/library/_0-create-library/index.js
  packages/rspack/tests/configCases/library/_0-create-library/nested.js
  packages/rspack/tests/configCases/library/_0-create-library/non-external.js
  packages/rspack/tests/configCases/library/_0-create-library/test.config.js
  packages/rspack/tests/configCases/library/_0-create-library/webpack.config.js
Labels: team, release: bug fix

#3545 refactor: EntryOptions and EntryPlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/cache/local/code_splitting_cache.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/dependency/dynamic_import.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs
  crates/rspack_plugin_entry/Cargo.toml
  crates/rspack_plugin_entry/LICENSE
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/src/run_fixture.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/index.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  pnpm-lock.yaml
Labels: team

#3566 test(webpack): enable some tests related to splitChunks
  webpack-test/configCases/split-chunks-common/correct-order/test.filter.js
  webpack-test/configCases/split-chunks-common/extract-async-from-entry/test.filter.js
  webpack-test/configCases/split-chunks-common/inverted-order/test.filter.js
  webpack-test/configCases/split-chunks-common/issue-12128/test.filter.js
  webpack-test/configCases/split-chunks-common/library/test.filter.js
  webpack-test/configCases/split-chunks-common/move-entry/test.filter.js
  webpack-test/configCases/split-chunks-common/move-to-grandparent/test.filter.js
  webpack-test/configCases/split-chunks-common/simple/test.filter.js
  webpack-test/configCases/split-chunks-common/target-node/test.filter.js
  webpack-test/configCases/split-chunks/asnyc-entries/test.filter.js
  webpack-test/configCases/split-chunks/issue-11337/test.filter.js
  webpack-test/configCases/split-chunks/issue-8908/test.filter.js
  webpack-test/configCases/split-chunks/issue-9491/test.filter.js
  webpack-test/configCases/split-chunks/max-size-casing/test.filter.js
  webpack-test/configCases/split-chunks/move-to-entrypoint/test.filter.js
  webpack-test/configCases/split-chunks/reuse-chunk-name/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-no-async/test.filter.js
Labels: team

#3542 fix: do not expose non-webpack node interfaces
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
Labels: team, release: bug fix

#3569 feat(splitChunks): support `splitChunks.{cacheGroup}.type`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/cache_group.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
  crates/rspack_plugin_split_chunks_new/src/lib.rs
  packages/rspack/src/config/zod/optimization/split-chunks.ts
  webpack-test/configCases/split-chunks/module-type-filter/test.filter.js
Labels: team, release: feature

#3570 chore: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#3573 refactor(rspack_regex): readability and functionality
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_regex/src/algo.rs
  crates/rspack_regex/src/lib.rs
  crates/rspack_regex/tests/main.rs
Labels: team, ready to review

#3574 feat: easier way for converting `JsRegExp` to `RspackRegex`
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_napi_shared/Cargo.toml
  crates/rspack_napi_shared/src/ext/js_reg_exp_ext.rs
  crates/rspack_napi_shared/src/ext/mod.rs
  crates/rspack_napi_shared/src/js_values/js_reg_exp.rs
  crates/rspack_napi_shared/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/common.rs
Labels: team, release: feature, ready to review

#3577 fix: code generation cache not working
  crates/rspack_core/src/compiler/hmr.rs
Labels: team, release: bug fix

#3578 chore: add vue3-tsx example
  examples/vue3-tsx/global.d.ts
  examples/vue3-tsx/index.html
  examples/vue3-tsx/package.json
  examples/vue3-tsx/rspack.config.js
  examples/vue3-tsx/src/App.css
  examples/vue3-tsx/src/App.tsx
  examples/vue3-tsx/src/assets/vue.svg
  examples/vue3-tsx/src/index.css
  examples/vue3-tsx/src/main.tsx
  examples/vue3-tsx/tsconfig.json
  pnpm-lock.yaml
Labels: team

#3584 feat: chunkLoading for per entry
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/entry.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/builtins/css-modules-local-ident-name-path/webpack.config.js
  packages/rspack/tests/configCases/entry/chunk-loading/a.js
  packages/rspack/tests/configCases/entry/chunk-loading/async.js
  packages/rspack/tests/configCases/entry/chunk-loading/b.js
  packages/rspack/tests/configCases/entry/chunk-loading/test.config.js
  packages/rspack/tests/configCases/entry/chunk-loading/webpack.config.js
Labels: team, release: feature

#3563 fix: Wasm sideEffect analysis failed
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol_graph.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
  crates/rspack_symbol/src/lib.rs
  packages/rspack/tests/configCases/tree-shaking/new-url/a.js
  packages/rspack/tests/configCases/tree-shaking/new-url/a.wasm
  packages/rspack/tests/configCases/tree-shaking/new-url/index.js
  packages/rspack/tests/configCases/tree-shaking/new-url/webpack.config.js
  pnpm-lock.yaml
Labels: team, release: bug fix

#3585 fix: create rspack project template
  packages/create-rspack/template-react-ts/public/react.svg
  packages/create-rspack/template-react-ts/rspack.config.js
  packages/create-rspack/template-react/package.json
Labels: team, release: bug fix

#3586 fix: rspack serve will automatically rebuild once
  crates/rspack_core/src/module_factory.rs
  crates/rspack_loader_runner/src/runner.rs
  packages/rspack/tests/cases/schemes/data-imports/webpack.config.js
Labels: team, release: bug fix

#3579 test: 🤖 banner plugin
  packages/rspack/package.json
  packages/rspack/src/index.ts
  packages/rspack/src/lib/BannerPlugin.js
  packages/rspack/src/lib/ModuleFilenameHelpers.js
  packages/rspack/src/lib/Template.js
  packages/rspack/src/lib/util/create-schema-validation.js
  packages/rspack/src/lib/util/memoize.js
  packages/rspack/src/schemas/plugins/BannerPlugin.check.js
  packages/rspack/src/schemas/plugins/BannerPlugin.json
  pnpm-lock.yaml
  webpack-test/configCases/plugins/banner-plugin/test.filter.js
  webpack-test/configCases/plugins/banner-plugin/webpack.config.js
Labels: team

#3592 fix: react flow side effect analyze
  crates/rspack_core/src/tree_shaking/asset_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/test.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
Labels: team, release: bug fix

#3590 feat: false for chunkLoading and asyncChunks
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/entry.ts
  packages/rspack/src/config/zod/output.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/entry/no-chunking/a.js
  webpack-test/configCases/entry/no-chunking/test.config.js
  webpack-test/configCases/entry/no-chunking/test.filter.js
  webpack-test/scripts/dbg/document.test.js
  webpack-test/scripts/dbg/jest.config.js
Labels: team, release: feature

#3559 fix: WebpackDevServer typing import
  packages/rspack/src/config/types.ts
Labels: release: bug fix

#3601 fix: adjust rspack/core dependencies
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#3604 fix: import export check invalidation on make stage
  crates/rspack_core/src/compiler/hmr.rs
Labels: team, release: bug fix

#3614 feat: baseUri and publicPath for per entry
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/base_uri.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/entry.ts
  packages/rspack/src/config/zod/output.ts
  webpack-test/configCases/entry/entry-base-uri/test.filter.js
Labels: team, release: feature

#3618 chore: add basic-ts example
  .github/workflows/lint-pr.yaml
  examples/basic-ts/index.html
  examples/basic-ts/package.json
  examples/basic-ts/rspack.config.js
  examples/basic-ts/src/alias-1/a.ts
  examples/basic-ts/src/alias-2/b.ts
  examples/basic-ts/src/index.ts
  examples/basic-ts/tsconfig.json
  pnpm-lock.yaml
Labels: team

#3499 feat: add entryOption hook
  packages/rspack/src/compiler.ts
  packages/rspack/src/rspack.ts
  packages/rspack/tests/cases/hooks/entryOption/package.json
  packages/rspack/tests/cases/hooks/entryOption/src/answer.js
  packages/rspack/tests/cases/hooks/entryOption/src/index.js
  packages/rspack/tests/cases/hooks/entryOption/src/index2.js
  packages/rspack/tests/cases/hooks/entryOption/webpack.config.js
Labels: release: feature

#3627 fix: side effects rule match
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/tests/configCases/tree-shaking/side-effects-rule/index.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-rule/package/a.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-rule/package/b.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-rule/package/index.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-rule/package/package.json
  packages/rspack/tests/configCases/tree-shaking/side-effects-rule/webpack.config.js
Labels: team, release: bug fix

#3628 chore: 🤖 pass terser options
  packages/rspack-plugin-minify/src/index.js
Labels: team

#3624 chore(ci): should not add stale tag for awaiting more feedback issues
  .github/stale.yml
Labels: team

#3623 chore: exit if cargo returns any non-zero code
  crates/node_binding/scripts/build.js
Labels: team

#3591 fix(commonjs_scanner): ignore unresolve require span
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/issue-3558/index.js
  packages/rspack/tests/statsCases/issue-3558/webpack.config.js
Labels: release: bug fix

#3630 ci: write a comment to issue when canary release is finished.
  .github/workflows/release-canary.yml
  scripts/release/publish.mjs
Labels: team

#3637 fix: 🤖 pr number
  .github/workflows/release-canary.yml
Labels: team, release: bug fix

#3605 chore: loader options plugin
  packages/rspack/src/index.ts
  packages/rspack/src/lib/LoaderOptionsPlugin.js
  packages/rspack/src/schemas/plugins/LoaderOptionsPlugin.check.js
  packages/rspack/src/schemas/plugins/LoaderOptionsPlugin.json
  webpack-test/configCases/plugins/loader-options-plugin/test.filter.js
  webpack-test/configCases/plugins/loader-options-plugin/webpack.config.js
Labels: team

#3595 feat(config): zod schema for output
  packages/rspack/src/config/zod/output.ts
Labels: release: feature

#3643 fix(examples/vue): refine module resource matching rule.
  examples/vue/rspack.config.js
  examples/vue2-ts/rspack.config.js
  examples/vue2/rspack.config.js
  examples/vue3-vanilla/rspack.config.js
Labels: release: bug fix

#3654 chore: update CODEOWNERS.md
  .github/CODEOWNERS
Labels: team

#3662 feat: filename per entry
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/entry.ts
  packages/rspack/src/config/zod/output.ts
  packages/rspack/tests/configCases/entry/filename/index.js
  packages/rspack/tests/configCases/entry/filename/test.config.js
  packages/rspack/tests/configCases/entry/filename/webpack.config.js
Labels: team, release: feature

#3659 fix: minimize don't support output target equal "module"
  crates/rspack_plugin_javascript/src/ast/minify.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  packages/rspack/tests/configCases/library/esmodule/index.js
  packages/rspack/tests/configCases/library/esmodule/webpack.config.js
Labels: release: bug fix

#3617 feat: worker support
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_javascript/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_worker/Cargo.toml
  crates/rspack_plugin_worker/src/lib.rs
  crates/rspack_testing/src/test_config.rs
  examples/worker/chat-module.js
  examples/worker/chat-worker.js
  examples/worker/example.js
  examples/worker/fib-worker.js
  examples/worker/fibonacci.js
  examples/worker/index.html
  examples/worker/package.json
  examples/worker/rspack.config.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/output.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/module.js
  packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/webpack.config.js
  pnpm-lock.yaml
  webpack-test/configCases/worker/custom-worker/test.filter.js
  webpack-test/configCases/worker/node-worker-hmr/test.filter.js
  webpack-test/configCases/worker/node-worker-named/test.filter.js
  webpack-test/configCases/worker/node-worker/test.filter.js
  webpack-test/configCases/worker/web-worker/test.filter.js
  webpack-test/configCases/worker/worker-contenthash/test.filter.js
Labels: team, release: feature, need documentation

#3667 feat: support module decorator to give warning for mix harmony-commonjs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_runtime/src/runtime_module/harmony_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/node_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/harmony_module_decorator.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/node_module_decorator.js
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix/index.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix/module.js
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix/module1.js
Labels: release: feature

#3670 fix: runtime chunk hash should has full hash
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack/tests/hashCases/full-hash/test.config.js
  packages/rspack/tests/hashCases/full-hash/version0-copy/foo.js
  packages/rspack/tests/hashCases/full-hash/version0-copy/index.js
  packages/rspack/tests/hashCases/full-hash/version0/foo.js
  packages/rspack/tests/hashCases/full-hash/version0/index.js
  packages/rspack/tests/hashCases/full-hash/version1/foo.js
  packages/rspack/tests/hashCases/full-hash/version1/index.js
  packages/rspack/tests/hashCases/full-hash/webpack.config.js
Labels: team, release: bug fix
