Repository web-infra-dev/rspack, pull requests merged in 2023-10, with the labels that each got.

#4281 chore: add github-sync-issue
  .github/github-issue-sync.yml
Labels: team

#4282 chore: move sync workflow
  .github/workflows/github-issue-sync.yml
Labels: team

#4287 chore: try free disk for linux
  .github/workflows/reusable-build.yml
Labels: team

#4288 chore: only remove android sdk
  .github/workflows/reusable-build.yml
Labels: team

#4228 feat: implement styled_components visitor
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_loader_swc/src/transformer.rs
  crates/rspack_swc_visitors/Cargo.toml
  crates/rspack_swc_visitors/src/lib.rs
  crates/rspack_swc_visitors/src/styled_components.rs
  packages/rspack/package.json
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/Button/index.jsx
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/index.jsx
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/webpack.config.js
  pnpm-lock.yaml
Labels: release: feature, need documentation

#4267 feat: handle `react-refresh` resolving in `@rspack/plugin-react-refresh`
  packages/rspack-plugin-react-refresh/src/index.js
  packages/rspack/src/web/ResolveSwcPlugin.ts
Labels: team, release: feature

#4255 feat: support `Compilation.namedChunks`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/compilation.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/tests/Compiler.test.ts
Labels: team, release: feature

#4294 fix: rspack builtin.html.meta.* support Record<string, string>
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/tests/configCases/builtins/html-meta/index.js
  packages/rspack/tests/configCases/builtins/html-meta/webpack.config.js
Labels: team, release: bug fix

#4290 feat(rspack_core): configurable tsconfig project references
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/resolve.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_a/conf.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_a/src/aliased/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_a/src/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_b/src/aliased/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_b/src/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_b/tsconfig.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_c/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_c/src/aliased/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/project_c/tsconfig.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/tsconfig.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-auto/webpack.config.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_a/conf.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_a/src/aliased/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_a/src/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_b/src/aliased/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_b/src/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_b/tsconfig.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_c/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_c/src/aliased/index.js
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/project_c/tsconfig.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/tsconfig.json
  packages/rspack/tests/configCases/resolve-new/tsconfig-project-references-manual/webpack.config.js
Labels: team, release: feature, need documentation

#4280 feat(split chunks): split chunks should consider chunk combinations
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
  packages/rspack/tests/configCases/split-chunks-common/correct-order/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/extract-async-from-entry/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/inverted-order/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/issue-12128/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/move-entry/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/move-to-grandparent/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/simple/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/a.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/b.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/c.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/d.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/e.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/f.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/g.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/index.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/x.js
  packages/rspack/tests/configCases/split-chunks-common/split-chunks-combinations/y.js
  packages/rspack/tests/configCases/split-chunks/disable-reuse-existing-chunk-simple/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/extract-css-to-single-chunk/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/max-size-casing/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/reuse-existing-chunk-simple/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/should-not-reuse-existing-chunk-simple-if-cache-group-name-specified/webpack.config.js
  packages/rspack/tests/configCases/split-chunks/split-chunks-dot-name/index.js
  packages/rspack/tests/configCases/split-chunks/split-chunks-dot-name/webpack.config.js
  packages/rspack/tests/hashCases/full-hash/webpack.config.js
  packages/rspack/tests/hashCases/package-path-change/webpack.config.js
Labels: team, release: feature

#4263 feat: Adding runtime param when executing codegen
  crates/rspack_core/src/cache/occasion/code_generate.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
Labels: team, release: feature

#4302 chore: enable more webpack-test
  webpack-test/cases/chunks/circular-correctness/test.filter.js
  webpack-test/cases/chunks/import-circle/test.filter.js
  webpack-test/cases/chunks/import-context-exist-chunk/test.filter.js
  webpack-test/cases/chunks/import-context/test.filter.js
  webpack-test/cases/chunks/import/test.filter.js
  webpack-test/cases/chunks/issue-2443/test.filter.js
  webpack-test/cases/chunks/issue-5153/test.filter.js
Labels: team

#4308 chore: fix nestjs example
  examples/nestjs/rspack.config.js
Labels: team

#4312 chore: remove unused imports
  crates/rspack_binding_macros/src/lib.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
Labels: team

#4292 chore: update vue2 example using experiments.css
  examples/vue2/package.json
  examples/vue2/rspack.config.js
  examples/vue2/src/App.vue
  pnpm-lock.yaml
Labels: team

#4316 feat: comment test markdown for webpack-test
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  webpack-test/ConfigTestCases.template.js
  webpack-test/Examples.test.js
  webpack-test/HotTestCases.template.js
  webpack-test/MemoryLimitTestCases.test.js
  webpack-test/StatsTestCases.basictest.js
  webpack-test/TestCases.template.js
  webpack-test/WatchTestCases.template.js
  webpack-test/cases/amd/define-needs-module/test.filter.js
  webpack-test/cases/amd/namedModules/test.filter.js
  webpack-test/cases/amd/namedModulesConstArrayDep/test.filter.js
  webpack-test/cases/async-modules/double-import/test.filter.js
  webpack-test/cases/async-modules/micro-ticks-parents/test.filter.js
  webpack-test/cases/async-modules/reexport-unknown/test.filter.js
  webpack-test/cases/async-modules/runtime-performance/test.filter.js
  webpack-test/cases/async-modules/top-level-await-without-export/test.filter.js
  webpack-test/cases/async-modules/top-level-await/test.filter.js
  webpack-test/cases/async-modules/top-level-error/test.filter.js
  webpack-test/cases/chunks/context-weak/test.filter.js
  webpack-test/cases/chunks/context/test.filter.js
  webpack-test/cases/chunks/inline-options/test.filter.js
  webpack-test/cases/chunks/named-chunks/test.filter.js
  webpack-test/cases/chunks/nested-in-empty/test.filter.js
  webpack-test/cases/chunks/parsing/test.filter.js
  webpack-test/cases/chunks/runtime/test.filter.js
  webpack-test/cases/chunks/var-inject-error-handler/test.filter.js
  webpack-test/cases/chunks/weak-dependencies-context/test.filter.js
  webpack-test/cases/chunks/weak-dependencies/test.filter.js
  webpack-test/cases/chunks/weird-reference-to-entry/test.filter.js
  webpack-test/configCases/loaders/hot-in-context/test.filter.js
  webpack-test/configCases/worker/node-worker-hmr/webpack.config.js
  webpack-test/lib/util/filterUtil.js
  webpack-test/scripts/pr-diff.js
  webpack-test/scripts/test-metric-util.js
  webpack-test/scripts/test-metric.js
Labels: team, release: feature

#4322 fix(4314): remove help info print when throw error
  packages/rspack-cli/src/rspack-cli.ts
Labels: release: bug fix

#4330 fix: detect cjs assign esModule mark
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  webpack-test/cases/cjs-interop/non-existing-export/test.filter.js
  webpack-test/cases/cjs-tree-shaking/bailouts/test.filter.js
  webpack-test/cases/cjs-tree-shaking/cjs-to-esm/test.filter.js
  webpack-test/cases/cjs-tree-shaking/esModule-getter/test.filter.js
  webpack-test/cases/cjs-tree-shaking/esm-to-cjs/test.filter.js
  webpack-test/cases/cjs-tree-shaking/exports/test.filter.js
  webpack-test/cases/cjs-tree-shaking/importing/test.filter.js
  webpack-test/cases/cjs-tree-shaking/mjs/test.filter.js
  webpack-test/cases/cjs-tree-shaking/mutate/test.filter.js
  webpack-test/cases/cjs-tree-shaking/namespace/test.filter.js
  webpack-test/cases/cjs-tree-shaking/non-root-this/test.filter.js
  webpack-test/cases/cjs-tree-shaking/object-define-property-replace/test.filter.js
  webpack-test/cases/cjs-tree-shaking/objects/test.filter.js
  webpack-test/cases/cjs-tree-shaking/parsing/test.filter.js
  webpack-test/cases/cjs-tree-shaking/reexports/test.filter.js
  webpack-test/cases/cjs-tree-shaking/transpiled/test.filter.js
  webpack-test/cases/cjs-tree-shaking/weird-names/test.filter.js
  webpack-test/cases/compile/deduplication-bundle-loader/test.filter.js
  webpack-test/cases/compile/error-hide-stack/test.filter.js
  webpack-test/cases/compile/long-module-chain/test.filter.js
  webpack-test/cases/context/import-meta-webpack-context/test.filter.js
  webpack-test/cases/context/issue-10969/test.filter.js
  webpack-test/cases/context/issue-5750/test.filter.js
  webpack-test/cases/entry-exports-field/import-and-require/node_modules/pck/import.js
  webpack-test/cases/entry-exports-field/import-and-require/node_modules/pck/package.json
  webpack-test/cases/entry-exports-field/import-and-require/node_modules/pck/require.js
  webpack-test/cases/entry-exports-field/import-and-require/test.filter.js
  webpack-test/cases/entry-exports-field/imports/test.filter.js
  webpack-test/cases/entry-exports-field/loader/node_modules/toml-parser/index.js
  webpack-test/cases/entry-exports-field/loader/node_modules/toml-parser/loader.js
  webpack-test/cases/entry-exports-field/loader/node_modules/toml-parser/package.json
  webpack-test/cases/entry-exports-field/loader/test.filter.js
  webpack-test/cases/entry-exports-field/self/test.filter.js
  webpack-test/cases/loaders/emit-file/test.filter.js
  webpack-test/configCases/target/chunk-loading-per-entry/test.filter.js
  webpack-test/scripts/pr-diff.js
  webpack-test/scripts/test-metric.js
Labels: team

#3949 feat(plugin-copy): support info option
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack/tests/copyPlugin/CopyPlugin.test.js
  packages/rspack/tests/copyPlugin/__snapshots__/CopyPlugin.test.js.snap
  packages/rspack/tests/copyPlugin/build/main.js
  packages/rspack/tests/copyPlugin/build/unoptimized.js
  packages/rspack/tests/copyPlugin/fixtures/js/unoptimized.js
Labels: team, need documentation

#4337 chore: align webpack tests
  webpack-test/configCases/split-chunks/asnyc-entries/test.filter.js
  webpack-test/configCases/split-chunks/chunk-filename-delimiter-default/test.filter.js
  webpack-test/configCases/split-chunks/chunk-filename-delimiter/test.filter.js
  webpack-test/configCases/split-chunks/custom-filename-function/test.filter.js
  webpack-test/configCases/split-chunks/custom-filename-many-custom/test.filter.js
  webpack-test/configCases/split-chunks/custom-filename/test.filter.js
  webpack-test/configCases/split-chunks/entry-point-error/test.filter.js
  webpack-test/configCases/split-chunks/incorrect-chunk-reuse/test.filter.js
  webpack-test/configCases/split-chunks/issue-11337/test.filter.js
  webpack-test/configCases/split-chunks/issue-11513/test.filter.js
  webpack-test/configCases/split-chunks/issue-12307/test.filter.js
  webpack-test/configCases/split-chunks/issue-8908/test.filter.js
  webpack-test/configCases/split-chunks/issue-9491/test.filter.js
  webpack-test/configCases/split-chunks/max-size-casing/test.filter.js
  webpack-test/configCases/split-chunks/module-type-filter/test.filter.js
  webpack-test/configCases/split-chunks/move-to-entrypoint/test.filter.js
  webpack-test/configCases/split-chunks/no-options/test.filter.js
  webpack-test/configCases/split-chunks/reuse-chunk-name/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-async-node/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-no-async/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-node-13130/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-node/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk/test.filter.js
  webpack-test/configCases/split-chunks/vendor-only-entrypoint/node_modules/vendor.js
  webpack-test/configCases/split-chunks/vendor-only-entrypoint/test.filter.js
Labels: team

#4351 chore: enable more webpack-test
  webpack-test/cases/entry-inline/no-var-leak-strict/test.filter.js
  webpack-test/cases/entry-inline/no-var-leak/test.filter.js
  webpack-test/cases/errors/case-sensitive/test.filter.js
  webpack-test/cases/errors/crash-missing-import/test.filter.js
  webpack-test/cases/errors/cyclic-reexport-references/test.filter.js
  webpack-test/cases/errors/harmony-import-missing/test.filter.js
  webpack-test/cases/errors/harmony-import-missing2/test.filter.js
  webpack-test/cases/errors/load-module-cycle-multiple/test.filter.js
  webpack-test/cases/errors/load-module-cycle/test.filter.js
  webpack-test/cases/errors/load-module-error/test.filter.js
  webpack-test/cases/errors/loader-error-warning/test.filter.js
  webpack-test/cases/errors/mjs-non-fully-specified/test.filter.js
  webpack-test/cases/errors/module-request/test.filter.js
  webpack-test/cases/esm/import-meta/index.js
  webpack-test/cases/esm/import-meta/test.filter.js
  webpack-test/cases/esm/import-meta/warnings.js
  webpack-test/cases/inner-graph/circular/test.filter.js
  webpack-test/cases/inner-graph/circular2/test.filter.js
  webpack-test/cases/inner-graph/export-default-named/test.filter.js
  webpack-test/cases/inner-graph/extend-class/test.filter.js
  webpack-test/cases/inner-graph/no-side-effects/test.filter.js
  webpack-test/cases/inner-graph/pure-in-removed/test.filter.js
  webpack-test/cases/inner-graph/reexport-namespace-and-default/test.filter.js
  webpack-test/cases/inner-graph/simple/test.filter.js
  webpack-test/cases/inner-graph/static-of-class/test.filter.js
  webpack-test/cases/inner-graph/switch/test.filter.js
  webpack-test/cases/inner-graph/try-globals/test.filter.js
Labels: team

#4356 fix: variable undefined with multiple same import
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack/tests/configCases/tree-shaking/multiple-same-import-side-effect/index.js
  packages/rspack/tests/configCases/tree-shaking/multiple-same-import-side-effect/lib.js
  packages/rspack/tests/configCases/tree-shaking/multiple-same-import-side-effect/webpack.config.js
Labels: team, release: bug fix

#4359 fix: update lockfile
  pnpm-lock.yaml
Labels: team, release: bug fix

#4360 chore: use self hosted ci
  .github/actions/docker-build/action.yml
  .github/actions/pnpm-cache/action.yml
  .github/actions/rustup/action.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#4345 feat: support TLA
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  webpack-test/cases/async-modules/double-import/test.filter.js
  webpack-test/cases/async-modules/issue-16097/index.js
  webpack-test/cases/async-modules/issue-16097/won't-run-tla.js
  webpack-test/cases/async-modules/micro-ticks-parents/test.filter.js
  webpack-test/cases/async-modules/reexport-unknown/test.filter.js
  webpack-test/cases/async-modules/runtime-performance/test.filter.js
  webpack-test/cases/async-modules/top-level-await-without-export/test.filter.js
  webpack-test/cases/async-modules/top-level-await/test.filter.js
  webpack-test/cases/async-modules/top-level-error/test.filter.js
Labels: team, release: feature

#4368 chore: expose discord explictly in readme
  README.md
  README.zh-CN.md
Labels: team

#4369 chore: support run ci with forked repo PR
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#4361 feat: update dependency
  crates/rspack/tests/fixtures.rs
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export-imported-import-all-as/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/react-redux-like/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/react-redux-like/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport-all-as/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport-all-as/snapshot/snap.diff
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: release: feature

#4372 chore: bump swc
  Cargo.lock
  Cargo.toml
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/snapshot/new_treeshaking.snap
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_css/src/swc_css_compiler.rs
  crates/rspack_plugin_javascript/src/utils.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs
Labels: team

#4353 fix: splitChunks.enforce, pass more webpack-tests
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  webpack-test/configCases/split-chunks-common/correct-order/test.filter.js
  webpack-test/configCases/split-chunks-common/extract-async-from-entry/test.filter.js
  webpack-test/configCases/split-chunks-common/hot-multi/test.filter.js
  webpack-test/configCases/split-chunks-common/hot-multi/webpack.config.js
  webpack-test/configCases/split-chunks-common/hot/test.filter.js
  webpack-test/configCases/split-chunks-common/hot/webpack.config.js
  webpack-test/configCases/split-chunks-common/inverted-order/test.filter.js
  webpack-test/configCases/split-chunks-common/issue-12128/test.filter.js
  webpack-test/configCases/split-chunks-common/library/test.filter.js
  webpack-test/configCases/split-chunks-common/move-entry/test.filter.js
  webpack-test/configCases/split-chunks-common/move-to-grandparent/test.filter.js
  webpack-test/configCases/split-chunks-common/simple/test.filter.js
  webpack-test/configCases/split-chunks-common/target-node/test.filter.js
Labels: team, release: bug fix

#4371 chore: add auto issue comment
  .github/workflows/issue-close-require.yml
  .github/workflows/label-auto-comment.yml
Labels: team

#4378 chore: set lang to en for react-ts template
  packages/create-rspack/template-react-ts/index.html
Labels: team

#4387 chore: fix rustup install components failed
  .github/workflows/reusable-build.yml
Labels: team

#4373 fix(splitChunks): not matched cacheGroup should not affect cacheGroupIndex
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  crates/rspack_plugin_split_chunks_new/src/module_group.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
  packages/playground/cases/css/chunk-loading-order/index.test.ts
  packages/playground/cases/css/chunk-loading-order/rspack.config.js
  packages/playground/cases/css/chunk-loading-order/src/a.css
  packages/playground/cases/css/chunk-loading-order/src/async.js
  packages/playground/cases/css/chunk-loading-order/src/b.css
  packages/playground/cases/css/chunk-loading-order/src/index.js
  packages/playground/fixtures/rspack.ts
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/src/config/adapter.ts
Labels: team, release: bug fix

#4388 fix: HarmonyExportImportedDependency `get_exports`
  crates/rspack/tests/fixtures.rs
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/cyclic-reference-export-all/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/snapshot/output.snap
  crates/rspack/tests/tree-shaking/transitive-bailout/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/transitive-bailout/snapshot/snap.diff
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: bug fix

#4374 chore: enable oxc_resolver in webpack tests
  webpack-test/ConfigTestCases.template.js
  webpack-test/TestCases.template.js
  webpack-test/cases/resolving/browser-field/test.filter.js
  webpack-test/cases/resolving/commomjs-local-module/test.filter.js
  webpack-test/cases/resolving/context/test.filter.js
  webpack-test/cases/resolving/data-uri/test.filter.js
  webpack-test/cases/resolving/issue-11555/test.filter.js
  webpack-test/cases/resolving/issue-2986/test.filter.js
  webpack-test/cases/resolving/query/test.filter.js
  webpack-test/cases/resolving/single-file-module/test.filter.js
  webpack-test/configCases/resolve-merging/override/test.filter.js
  webpack-test/configCases/resolve/context-resolve-with-ignore/test.filter.js
  webpack-test/configCases/resolve/empty-context-module/test.filter.js
  webpack-test/configCases/resolve/fallback/test.filter.js
  webpack-test/configCases/resolve/issue-11335-context-module/test.filter.js
  webpack-test/configCases/resolve/issue-15580/test.filter.js
  webpack-test/configCases/resolve/multi-alias/test.filter.js
  webpack-test/configCases/resolve/only-module/test.filter.js
  webpack-test/configCases/resolving/extensions-order/test.filter.js
  webpack-test/configCases/resolving/prefer-absolute/test.filter.js
  webpack-test/configCases/resolving/prefer-root/test.filter.js
Labels: team

#4400 fix: 🐛 use get_ids instead of `self.ids`
  crates/rspack/tests/tree-shaking/import-var-assign-side-effects/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/import-var-assign-side-effects/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport-all-as/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport-all-as/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/snap.diff
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
Labels: team, release: bug fix

#4405 chore: remove useless rustup target install
  .github/workflows/reusable-build.yml
Labels: team

#4402 fix: export default as edge case in `HarmonyExportImportedSpecifierDependency`
  crates/rspack/tests/tree-shaking/export-named-decl-as/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export-named-decl-as/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/import-var-assign-side-effects/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/import-var-assign-side-effects/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/react-redux-like/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/react-redux-like/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport_default_as/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport_default_as/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/rename-export-from-import/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/rename-export-from-import/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-analyzed/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-flagged-only/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-two/snapshot/snap.diff
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_wasm/src/dependency.rs
Labels: team, release: bug fix

#4403 fix: do not stopped when decode base64 failed
  crates/rspack_plugin_schemes/src/data_uri.rs
  packages/rspack/package.json
  packages/rspack/tests/cases/css/issue-4258/index.css
  packages/rspack/tests/cases/css/issue-4258/index.js
Labels: release: bug fix

#4375 fix: cjs bare exports expression detect
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  webpack-test/cases/json/data/test.filter.js
  webpack-test/cases/json/default-default-with-concatenation/test.filter.js
  webpack-test/cases/json/default-default/test.filter.js
  webpack-test/cases/json/import-assertions-type-json/test.filter.js
  webpack-test/cases/json/import-by-name-with-concatenation/test.filter.js
  webpack-test/cases/json/import-by-name/test.filter.js
  webpack-test/cases/json/import-lazy/test.filter.js
  webpack-test/cases/json/import-with-default-with-concatenation/test.filter.js
  webpack-test/cases/json/import-with-default/test.filter.js
  webpack-test/cases/json/prototype-methods/test.filter.js
  webpack-test/cases/json/reexport/test.filter.js
  webpack-test/cases/json/weird-properties/test.filter.js
  webpack-test/cases/large/big-assets/index.js
  webpack-test/cases/large/big-assets/test.filter.js
  webpack-test/cases/large/many-replacements/test.filter.js
  webpack-test/cases/loaders/async/test.filter.js
  webpack-test/cases/loaders/coffee-loader/test.filter.js
  webpack-test/cases/loaders/context/test.filter.js
  webpack-test/cases/loaders/css-loader/test.filter.js
  webpack-test/cases/loaders/import-module/test.filter.js
  webpack-test/cases/loaders/json-loader/test.filter.js
  webpack-test/cases/loaders/less-loader/test.filter.js
  webpack-test/cases/loaders/module-description-file/test.filter.js
  webpack-test/cases/loaders/pug-loader/test.filter.js
  webpack-test/cases/loaders/query/test.filter.js
  webpack-test/cases/loaders/raw-loader/test.filter.js
  webpack-test/cases/loaders/resolve/test.filter.js
  webpack-test/cases/loaders/utils/test.filter.js
  webpack-test/cases/mjs/no-module-main-field/node_modules/m/a.js
  webpack-test/cases/mjs/no-module-main-field/node_modules/m/a.mjs
  webpack-test/cases/mjs/no-module-main-field/node_modules/m/b.js
  webpack-test/cases/mjs/no-module-main-field/node_modules/m/b.mjs
  webpack-test/cases/mjs/no-module-main-field/node_modules/m/package.json
  webpack-test/cases/mjs/no-module-main-field/test.filter.js
  webpack-test/cases/mjs/type-module/test.fitler.js
  webpack-test/cases/nonce/set-nonce/test.filter.js
  webpack-test/scripts/test-metric-util.js
Labels: team, release: bug fix

#4407 fix: 🐛 pure expression dependency apply replace resouce,and get side effects state impl
  crates/rspack/tests/tree-shaking/side-effects-export-default-expr/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/side-effects-export-default-expr/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/snap.diff
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
Labels: team, release: bug fix

#4412 fix: use indirect call for TaggedTpl
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack/tests/cases/indirect-call/call/dep.js
  packages/rspack/tests/cases/indirect-call/call/index.js
  packages/rspack/tests/cases/indirect-call/tagged-template-expression/dep.js
  packages/rspack/tests/cases/indirect-call/tagged-template-expression/dep1.js
  packages/rspack/tests/cases/indirect-call/tagged-template-expression/index.js
Labels: release: bug fix

#4413 fix: fake namespace mode should fallthrough
  crates/rspack/tests/fixtures/code-splitting/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/self-import/snapshot/output.snap
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/snapshot/output.snap
  webpack-test/cases/mjs/non-enumerable/test.filter.js
  webpack-test/cases/mjs/type-module/test.filter.js
  webpack-test/cases/optimize/concat-star-import/test.filter.js
  webpack-test/cases/optimize/many-exports-100/test.filter.js
  webpack-test/cases/optimize/many-exports-120/test.filter.js
  webpack-test/cases/optimize/many-exports-40/test.filter.js
  webpack-test/cases/optimize/side-effects-all-chain-unused/test.filter.js
  webpack-test/cases/optimize/side-effects-all-used/test.filter.js
  webpack-test/cases/optimize/side-effects-immediate-unused/test.filter.js
  webpack-test/cases/optimize/side-effects-reexport-start-unknown/test.filter.js
  webpack-test/cases/optimize/side-effects-root-unused/test.filter.js
  webpack-test/cases/optimize/side-effects-scope-hoisting/test.filter.js
  webpack-test/cases/optimize/side-effects-transitive-unused/test.filter.js
  webpack-test/cases/optimize/tree-shaking-commonjs/test.filter.js
  webpack-test/cases/optimize/tree-shaking-star/test.filter.js
  webpack-test/cases/optimize/tree-shaking-star2/test.filter.js
Labels: team, release: bug fix

#4417 chore: windows and macos add target before build
  .github/workflows/reusable-build.yml
Labels: team

#4423 fix: loader definition not being exported
  packages/rspack/src/config/adapter.ts
Labels: team, release: bug fix

#4428 chore: upgrade napi
  Cargo.lock
  Cargo.toml
  crates/rspack_napi_shared/src/errors.rs
  packages/rspack/tests/configCases/errors/asset-module-build-failed/index.js
  packages/rspack/tests/configCases/errors/loader-error-async/index.js
  packages/rspack/tests/configCases/errors/loader-syntax-error/index.js
  packages/rspack/tests/configCases/errors/loader-throw-error/index.js
Labels: team

#4425 fix: insert the path of html template to fileDependencies
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  packages/playground/cases/html/issue-4366/index.test.ts
  packages/playground/cases/html/issue-4366/rspack.config.js
  packages/playground/cases/html/issue-4366/src/index.html
  packages/playground/cases/html/issue-4366/src/index.js
Labels: release: bug fix

#4418 feat: support passing query to loader
  packages/rspack/package.json
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/tests/configCases/builtin-swc-loader/source-map/a.ts
  packages/rspack/tests/configCases/builtin-swc-loader/source-map/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/source-map/webpack.config.js
  packages/rspack/tests/configCases/loader/options/a.js
  packages/rspack/tests/configCases/loader/options/b.js
  packages/rspack/tests/configCases/loader/options/c.js
  packages/rspack/tests/configCases/loader/options/d.js
  packages/rspack/tests/configCases/loader/options/e.js
  packages/rspack/tests/configCases/loader/options/error1.js
  packages/rspack/tests/configCases/loader/options/error2.js
  packages/rspack/tests/configCases/loader/options/f.js
  packages/rspack/tests/configCases/loader/options/g.js
  packages/rspack/tests/configCases/loader/options/h.js
  packages/rspack/tests/configCases/loader/options/i.js
  packages/rspack/tests/configCases/loader/options/index.js
  packages/rspack/tests/configCases/loader/options/infrastructure-log.js
  packages/rspack/tests/configCases/loader/options/loader-1.js
  packages/rspack/tests/configCases/loader/options/loader-1.options.json
  packages/rspack/tests/configCases/loader/options/loader-2.js
  packages/rspack/tests/configCases/loader/options/loader-2.options.json
  packages/rspack/tests/configCases/loader/options/loader.js
  packages/rspack/tests/configCases/loader/options/webpack.config.js
  packages/rspack/tests/configCases/source-map/source-map/index.js
  pnpm-lock.yaml
  webpack-test/cases/large/many-replacements/test.filter.js
  webpack-test/cases/loaders/coffee-loader/test.filter.js
  webpack-test/configCases/loaders/options/test.filter.js
  webpack-test/package.json
  webpack-test/packages/rspack/node_modules/make-dir/index.d.ts
  webpack-test/packages/rspack/node_modules/make-dir/index.js
  webpack-test/packages/rspack/node_modules/make-dir/license
  webpack-test/packages/rspack/node_modules/make-dir/package.json
  webpack-test/packages/rspack/node_modules/make-dir/readme.md
  webpack-test/scripts/test-metric-util.js
Labels: team, release: feature

#4444 fix: 🐛 export multiple export
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/index.js
  packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/lib.js
  packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/reexport.js
  packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/webpack.config.js
Labels: team, release: bug fix

#4436 fix: use string as key for resolve.by_dependency
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/options/resolve.rs
  packages/rspack/src/config/README.md
  packages/rspack/tests/configCases/resolve/issue-4432/index.js
  packages/rspack/tests/configCases/resolve/issue-4432/package/custom.js
  packages/rspack/tests/configCases/resolve/issue-4432/package/package.json
  packages/rspack/tests/configCases/resolve/issue-4432/webpack.config.js
Labels: release: bug fix

#4451 fix: empty __resourceQuery replace
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  packages/rspack/tests/cases/parsing/empty-resource-query/a.js
  packages/rspack/tests/cases/parsing/empty-resource-query/abc.js
  packages/rspack/tests/cases/parsing/empty-resource-query/index.js
  webpack-test/cases/parsing/issue-7778/test.filter.js
Labels: team, release: bug fix

#4384 feat: to support the monaco-editor-webpack-plugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_limit_chunk_count.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/mod.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_plugin_limit_chunk_count/Cargo.toml
  crates/rspack_plugin_limit_chunk_count/src/chunk_combination.rs
  crates/rspack_plugin_limit_chunk_count/src/lib.rs
  crates/rspack_plugin_web_worker_template/Cargo.toml
  crates/rspack_plugin_web_worker_template/src/lib.rs
  examples/monaco-editor-webpack-plugin/index.html
  examples/monaco-editor-webpack-plugin/index.js
  examples/monaco-editor-webpack-plugin/package.json
  examples/monaco-editor-webpack-plugin/rspack.config.js
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/LimitChunkCountPlugin.ts
  packages/rspack/src/builtin-plugin/WebWorkerTemplatePlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/index.ts
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/a.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/b.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/c.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/d.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/e.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/index.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/test.filter.js
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/webpack.config.js
Labels: release: feature

#4448 fix: nested member chain
  crates/rspack/tests/fixtures.rs
  crates/rspack/tests/tree-shaking/export-star-chain/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export-star-chain/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/export_star/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export_star/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/inherit_export_map_should_lookup_in_dfs_order/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/inherit_export_map_should_lookup_in_dfs_order/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/nested-import-3/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/nested-import-3/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/nested-import-4/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/nested-import-4/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/simple-namespace-access/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/simple-namespace-access/snapshot/snap.diff
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
Labels: team, release: bug fix

#4457 fix: mark regexp as None when it has g or y flag for context module
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
  crates/rspack_regex/src/algo.rs
  crates/rspack_regex/src/lib.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/context/issue-5750/index.js
Labels: release: bug fix

#4468 fix: not replace require when it not resolved
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  pnpm-lock.yaml
  webpack-test/cases/require/issue-4465/index.js
Labels: release: bug fix

#4460 chore: add ./x webpack for run tests against webpack-test suites
  x.mjs
Labels: team

#4463 fix: side effects analyze in exported decl or expr
  crates/rspack/tests/check.js
  crates/rspack/tests/tree-shaking/static-class/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/static-class/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-innergraph-circular/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-innergraph-circular/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/snap.diff
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: release: bug fix

#4469 fix: the scheduled GitHub action should not run on forked repositories
  .github/workflows/issue-close-require.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release-pull-request.yml
Labels: release: bug fix

#4452 chore: optimize CI running speed
  .github/actions/docker-build/action.yml
  .github/actions/docker-run/action.yml
  .github/actions/docker-test/action.yml
  .github/actions/download-artifact/action.yml
  .github/actions/pnpm-cache/action.yml
  .github/actions/rustup/action.yml
  .github/actions/upload-artifact/action.yml
  .github/workflows/ci.yml
  .github/workflows/get-runner-labels.yml
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  packages/playground/playwright.config.ts
  packages/rspack/jest.config.js
Labels: team

#4477 fix: not print the warning when use child compiler
  package.json
  packages/rspack-cli/tests/build/issue-4467/child/index.js
  packages/rspack-cli/tests/build/issue-4467/child/rspack.config.js
  packages/rspack-cli/tests/build/issue-4467/index.test.ts
  packages/rspack-cli/tests/build/issue-4467/root/index.js
  packages/rspack-cli/tests/build/issue-4467/root/rspack.config.js
  packages/rspack-cli/tests/build/json/json.test.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/index.ts
Labels: release: bug fix

#4480 fix: duplicate entrypoint files
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  packages/rspack/tests/configCases/errors/entry-runtime-error/a.js
  packages/rspack/tests/configCases/errors/entry-runtime-error/b.js
  packages/rspack/tests/configCases/errors/entry-runtime-error/errors.js
  packages/rspack/tests/configCases/errors/entry-runtime-error/test.config.js
  packages/rspack/tests/configCases/errors/entry-runtime-error/webpack.config.js
Labels: team, release: bug fix

#4482 chore: remove --no-frozen-lockfile when pnpm install
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  pnpm-lock.yaml
Labels: team

#4487 fix: windows stats snapshot
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/limit-chunk-count-plugin/test.filter.js
Labels: team, release: bug fix

#4484 fix: remove unnecessary normalize for `output.chunk_loading_global`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  packages/rspack/src/ModuleTypeConstants.js
  packages/rspack/src/Template.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/library/invalid-name/test.filter.js
  packages/rspack/tests/hotCases/chunk/issue-4476/changed-file.js
  packages/rspack/tests/hotCases/chunk/issue-4476/file.js
  packages/rspack/tests/hotCases/chunk/issue-4476/index.js
  packages/rspack/tests/hotCases/chunk/issue-4476/webpack.config.js
Labels: release: bug fix

#4492 revert: should have null as placeholder in stats chunks before chunkIds
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/asset.rs
  crates/node_binding/src/js_values/chunk_group.rs
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/js_values/mod.rs
  crates/node_binding/src/js_values/module.rs
  crates/node_binding/src/js_values/normal_module_factory.rs
  crates/node_binding/src/js_values/path_data.rs
  crates/node_binding/src/js_values/source.rs
  crates/node_binding/src/js_values/stats.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/mod.rs
  crates/node_binding/src/utils.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/chunk.rs
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/LICENSE
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_database/src/ukey.rs
  packages/rspack/src/Chunk.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/util/comparators.ts
  packages/rspack/tests/Stats.test.ts
Labels: team
