Repository web-infra-dev/rspack, pull requests merged in 2023-11, with the labels that each got.

#4493 chore: update pnpm lock file
  pnpm-lock.yaml
Labels: team

#4494 chore: alignment of async runtime module
  crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-module/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-module/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-module/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-async-module/webpack.config.js
Labels: team, same as webpack

#4498 chore(runtime-diff): alignment of create fake namespace object runtime module
  packages/rspack/tests/runtimeDiffCases/runtime-create-fake-namespace-object/src/async.js
  packages/rspack/tests/runtimeDiffCases/runtime-create-fake-namespace-object/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-create-fake-namespace-object/test.config.js
Labels: team, same as webpack

#4499 feat: support `Compiler.compile`
  packages/rspack/src/Compiler.ts
  packages/rspack/src/util/assertNotNil.ts
  packages/rspack/tests/configCases/hooks/issue-4395/index.js
  packages/rspack/tests/configCases/hooks/issue-4395/rspack.config.js
Labels: release: feature

#4501 chore(runtime-diff): alignment of get main filename
  crates/rspack_plugin_runtime/src/runtime_module/get_main_filename.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/runtimeDiffCases/runtime-get-main-filename/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-main-filename/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-main-filename/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-main-filename/webpack.config.js
Labels: team, same as webpack

#4495 chore: check pnpm lockfile on ci
  .github/actions/pnpm-cache/action.yml
  .github/workflows/bench-history.yaml.bak
  .github/workflows/ci.yml
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
Labels: team

#4506 chore(runtime-diff): alignment of global runtime module
  crates/rspack_plugin_runtime/src/runtime_module/runtime/global.js
  packages/rspack/tests/runtimeDiffCases/runtime-global/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-global/src/index.css
  packages/rspack/tests/runtimeDiffCases/runtime-global/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-global/src/logo.png
  packages/rspack/tests/runtimeDiffCases/runtime-global/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-global/webpack.config.js
Labels: team, same as webpack

#4503 chore(runtime-diff): alignment of get trusted type policy runtime module
  crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_trusted_types_policy.js
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/src/chunk.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/webpack.config.js
Labels: team, same as webpack

#4486 refactor(plugin-react-refresh): using tsc to build
  packages/rspack-plugin-react-refresh/options.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-plugin-react-refresh/src/index.ts
  packages/rspack-plugin-react-refresh/src/options.js
  packages/rspack-plugin-react-refresh/src/options.ts
  packages/rspack-plugin-react-refresh/tsconfig.build.json
  packages/rspack-plugin-react-refresh/tsconfig.json
Labels: team

#4497 feat: replace top-level this in esm
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_top_level_this.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  webpack-test/cases/parsing/es2020/test.filter.js
Labels: release: feature

#4516 chore: release do not use local cache
  .github/actions/download-artifact/action.yml
  .github/actions/upload-artifact/action.yml
Labels: team

#4514 fix: the scheduled GitHub action should not run on forked repositories
  .github/workflows/release-nightly.yml
Labels: release: bug fix

#4519 perf: pass `SyntaxContext` by copy
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: release: performance

#4507 chore(runtime-diff): alignment of load script runtime module
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/src/async.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/test.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-load-script/webpack.config.js
Labels: team, same as webpack

#4481 fix: class extends
  crates/rspack/tests/tree-shaking/class-extend/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/class-extend/snapshot/snap.diff
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: release: bug fix

#4533 chore: bump swc
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
Labels: highlight

#4534 feat: support banner in extractComments of minify
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack/tests/Compiler.test.ts
  packages/rspack/tests/configCases/plugins/swc-js-minifer/extract.js
  packages/rspack/tests/configCases/plugins/swc-js-minifer/index.js
  packages/rspack/tests/configCases/plugins/swc-js-minifer/webpack.config.js
Labels: release: feature

#4502 feat: support optional chaining
  crates/rspack/tests/tree-shaking/import-optional-chaining/app.js
  crates/rspack/tests/tree-shaking/import-optional-chaining/index.js
  crates/rspack/tests/tree-shaking/import-optional-chaining/package.json
  crates/rspack/tests/tree-shaking/import-optional-chaining/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/import-optional-chaining/snapshot/output.snap
  crates/rspack/tests/tree-shaking/import-optional-chaining/test.config.json
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_swc_visitors/Cargo.toml
  packages/rspack/tests/helpers/supportsOptionalChaining.js
Labels: team, release: feature

#4539 perf(@rspack/core): remove util dependency
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: performance

#4545 feat: support timestamps
  packages/playground/cases/vue3/index.test.ts
  packages/playground/cases/vue3/rspack.config.js
  packages/playground/cases/vue3/src/App.vue
  packages/playground/cases/vue3/src/enums.ts
  packages/playground/package.json
  packages/rspack/src/Compiler.ts
  packages/rspack/src/FileSystemInfo.ts
  packages/rspack/src/Watching.ts
  pnpm-lock.yaml
Labels: team, release: feature

#4379 feat: support WarnCaseSensitiveModulesPlugin
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
  crates/rspack_plugin_warn_sensitive_module/src/lib.rs
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/src/test_config.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/cases/warnings/case-sensitive/A.js
  packages/rspack/tests/cases/warnings/case-sensitive/B/file.js
  packages/rspack/tests/cases/warnings/case-sensitive/a.js
  packages/rspack/tests/cases/warnings/case-sensitive/b/file.js
  packages/rspack/tests/cases/warnings/case-sensitive/index.js
  packages/rspack/tests/cases/warnings/case-sensitive/warnings.js
  webpack-test/cases/errors/case-sensitive/A.js
  webpack-test/cases/errors/case-sensitive/B/file.js
  webpack-test/cases/errors/case-sensitive/test.filter.js
Labels: release: feature

#4554 feat: support more minify options
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/error.rs
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  examples/minify-test/a.js
  examples/minify-test/a2.js
  examples/minify-test/b.js
  examples/minify-test/index.js
  examples/minify-test/rspack.config.js
  package.json
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/plugins/minify-ascii-only/a.js
  packages/rspack/tests/configCases/plugins/minify-ascii-only/index.js
  packages/rspack/tests/configCases/plugins/minify-ascii-only/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-comment-all/a.js
  packages/rspack/tests/configCases/plugins/minify-comment-all/index.js
  packages/rspack/tests/configCases/plugins/minify-comment-all/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-comment-some/a.js
  packages/rspack/tests/configCases/plugins/minify-comment-some/index.js
  packages/rspack/tests/configCases/plugins/minify-comment-some/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-disable-mangle-compress/a.js
  packages/rspack/tests/configCases/plugins/minify-disable-mangle-compress/index.js
  packages/rspack/tests/configCases/plugins/minify-disable-mangle-compress/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-drop-console/index.js
  packages/rspack/tests/configCases/plugins/minify-drop-console/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-exclude/a.js
  packages/rspack/tests/configCases/plugins/minify-exclude/b.js
  packages/rspack/tests/configCases/plugins/minify-exclude/index.js
  packages/rspack/tests/configCases/plugins/minify-exclude/test.filter.js
  packages/rspack/tests/configCases/plugins/minify-exclude/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-extract-comments/index.js
  packages/rspack/tests/configCases/plugins/minify-extract-comments/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-keep-classnames/index.js
  packages/rspack/tests/configCases/plugins/minify-keep-classnames/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-keep-fn-names/index.js
  packages/rspack/tests/configCases/plugins/minify-keep-fn-names/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-pure-funcs/index.js
  packages/rspack/tests/configCases/plugins/minify-pure-funcs/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-test/a.js
  packages/rspack/tests/configCases/plugins/minify-test/a2.js
  packages/rspack/tests/configCases/plugins/minify-test/b.js
  packages/rspack/tests/configCases/plugins/minify-test/index.js
  packages/rspack/tests/configCases/plugins/minify-test/test.filter.js
  packages/rspack/tests/configCases/plugins/minify-test/webpack.config.js
  pnpm-lock.yaml
Labels: team, release: feature

#4548 fix: deep insert runtime to splitted chunk
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  webpack-test/configCases/chunk-graph/issue-9634/test.filter.js
Labels: release: bug fix

#4561 chore: adjust to 14 days for need reproduction label
  .github/workflows/bench-history.yaml.bak
  .github/workflows/issue-close-require.yml
  .github/workflows/label-auto-comment.yml
Labels: team

#4555 fix: succeedModule hook panic when can't convert to jsModule
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/source.rs
  packages/rspack/tests/cases/hooks/succeedModule/src/child/a.js
  packages/rspack/tests/cases/hooks/succeedModule/src/index.js
Labels: team, release: bug fix

#4547 feat: support entryDescription.library
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_napi_shared/src/lib.rs
  crates/rspack_napi_shared/src/utils.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_library/src/utils.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/system_context.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_testing/src/test_config.rs
  examples/library/rspack.config.js
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/lib/EntryOptionPlugin.ts
  packages/rspack/tests/Defaults.unittest.ts
  webpack-test/configCases/entry/issue-13637/test.filter.js
  webpack-test/scripts/test-metric-util.js
Labels: team, release: feature

#4563 fix: make builtin plugins class name consistent with webpack
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/tests/builtinPlugin.test.ts
Labels: team, release: bug fix

#4567 chore: upload artifact use RUNNER_LABELS
  .github/actions/upload-artifact/action.yml
Labels: team

#4570 feat: support webpackContextName for import context
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/to_path.rs
  crates/rspack_plugin_javascript/src/dependency/context/context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/chunks/issue-4338/a/index.js
  packages/rspack/tests/cases/chunks/issue-4338/a/local/one.js
  packages/rspack/tests/cases/chunks/issue-4338/a/local/two.js
  packages/rspack/tests/cases/chunks/issue-4338/b/index.js
  packages/rspack/tests/cases/chunks/issue-4338/b/local/one.js
  packages/rspack/tests/cases/chunks/issue-4338/b/local/two.js
  packages/rspack/tests/cases/chunks/issue-4338/c/index.js
  packages/rspack/tests/cases/chunks/issue-4338/c/local/one.js
  packages/rspack/tests/cases/chunks/issue-4338/c/local/two.js
  packages/rspack/tests/cases/chunks/issue-4338/index.js
Labels: release: feature

#4577 fix: require.context should not fail when using `endWith` algo (#4557)
  crates/rspack_regex/src/algo.rs
  packages/rspack/tests/cases/context/issue-4557/folder/my-story.js
  packages/rspack/tests/cases/context/issue-4557/index.js
Labels: release: bug fix

#4573 feat(example): vue2-tsx
  examples/vue2-tsx/global.d.ts
  examples/vue2-tsx/index.html
  examples/vue2-tsx/package.json
  examples/vue2-tsx/rspack.config.js
  examples/vue2-tsx/src/App.vue
  examples/vue2-tsx/src/assets/logo.png
  examples/vue2-tsx/src/components/SFC_JSX_Counter.vue
  examples/vue2-tsx/src/components/SFC_TSX_Counter.vue
  examples/vue2-tsx/src/components/TSX_Counter.tsx
  examples/vue2-tsx/src/main.ts
  examples/vue2-tsx/src/style.less
  examples/vue2-tsx/tsconfig.json
  pnpm-lock.yaml
Labels: release: feature

#4575 fix: fix unsoundness of napi type detection
  crates/rspack_napi_shared/src/js_values/js_reg_exp.rs
  crates/rspack_napi_shared/src/utils.rs
Labels: team, release: bug fix

#4543 fix: add the `./package.json` in the package.json's exports
  packages/rspack-dev-client/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-html/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-node-polyfill/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack/package.json
Labels: release: bug fix

#4572 feat(runtime): alignment of commonjs exports dependency
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/output.snap
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/snapshot/output.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
Labels: same as webpack, release: feature

#4580 feat: deprecate splitChunks options
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#4574 fix: tree shaking dfs_order test case.
  crates/rspack/tests/check.js
  crates/rspack/tests/tree-shaking/inherit_export_map_should_lookup_in_dfs_order/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/inherit_export_map_should_lookup_in_dfs_order/snapshot/snap.diff
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
Labels: team, release: bug fix

#4586 feat: add module and context fields in loader context
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
Labels: team, release: feature

#4581 feat(runtime): alignment of module runtime requirements
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: team, same as webpack, release: feature

#4591 perf(plugin-react-refresh): remove schema-utils
  packages/rspack-plugin-react-refresh/options.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-plugin-react-refresh/src/index.ts
  pnpm-lock.yaml
Labels: team, release: performance

#4592 fix: avoid generate banner when there are not extract comment
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack/tests/configCases/plugins/swc-js-minifier/extract.js
  packages/rspack/tests/configCases/plugins/swc-js-minifier/index.js
  packages/rspack/tests/configCases/plugins/swc-js-minifier/no-extract.js
  packages/rspack/tests/configCases/plugins/swc-js-minifier/webpack.config.js
Labels: release: bug fix

#4593 perf(@rspack/core): remove schema-utils
  packages/rspack/package.json
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
  pnpm-lock.yaml
Labels: team, release: performance

#4598 chore: fix `launch.json`
  .vscode/launch.json
Labels: team

#4599 chore: auto assign author as assignee
  .github/auto_assign.yml
  .github/workflows/auto-assign.yaml
Labels: team

#4600 chore: fix auto-assign workflow
  .github/workflows/auto-assign.yaml
Labels: team

#4607 chore(runtime-diff): alignment of compat get default export runtime module
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/test.config.js
Labels: team, same as webpack

#4496 chore: move @rspack/dev-server from deps to devDeps
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: team

#4604 chore: export more stats type for users use
  packages/rspack/src/Stats.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
Labels: team

#4608 chore: add react-refresh to rspack-cli reference
  packages/rspack-cli/tsconfig.json
Labels: team

#4606 fix: fix url rewriting in css variables
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  examples/tailwind/l.js
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/cases/css/rewrite-url-css-variables/index.css
  packages/rspack/tests/cases/css/rewrite-url-css-variables/index.js
  packages/rspack/tests/cases/css/rewrite-url-css-variables/logo.png
  packages/rspack/tests/cases/css/rewrite-url-css-variables/webpack.config.js
Labels: team, release: bug fix

#4610 fix: fix infinite while loop when entry name contains '/' like 'routes/index'
  .vscode/launch.json
  crates/rspack_plugin_runtime/src/helpers.rs
Labels: team, release: bug fix

#4620 ci: disable minification for example/arco-pro to speed up CI
  examples/arco-pro/rspack.config.js
Labels: team

#4621 fix: warning for direct access import.meta
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  webpack-test/cases/parsing/asi/test.filter.js
Labels: release: bug fix

#4614 feat(resolver): print detailed error messages for oxc_resolver (#4564)
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
Labels: release: feature

#4615 fix(chunk_graph): chunkGraph insert if not present
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
Labels: team, release: bug fix

#4616 fix: use original value when `import.style` is object
  crates/node_binding/src/lib.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_css/src/lib.rs
  packages/rspack/src/builtin-loader/swc/pluginImport.ts
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/.gitignore
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/diy.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/button/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/button/style/css.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/button/style/index.css
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/package.json
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/rspack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/src/index.js
Labels: release: bug fix

#4611 chore: better debugging
  .vscode/extensions.json
  examples/basic/src/lib.js
  package.json
  pnpm-lock.yaml
  x.mjs
Labels: team

#4627 chore: remove goverance
  GOVERNANCE.md
Labels: team

#4617 refactor(process_runtime_requirements): align api with webpack
  crates/rspack_core/src/compiler/compilation.rs
Labels: team

#4631 chore: bump swc-emotion
  Cargo.lock
  Cargo.toml
Labels: team

#4595 refactor: AsyncDependenciesBlock
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/chunks/issue-4338/index.js
Labels: team

#4624 ci: disable most of the optimization.minimize in examples to speed up CI
  examples/angular/rspack.config.js
  examples/cra-ts/rspack.config.js
  examples/cra/rspack.config.js
  examples/extract-license/rspack.config.js
  examples/loader-compat/rspack.config.js
  examples/plugin-compat/package.json
  examples/plugin-compat/rspack.config.js
  examples/react-15-classic/rspack.config.js
  examples/react-15/rspack.config.js
  examples/react-refresh-babel-loader/rspack.config.js
  examples/react-refresh/rspack.config.js
  examples/react-storybook/rspack.config.js
  examples/react-with-less/rspack.config.js
  examples/react-with-sass/rspack.config.js
  examples/solid/rspack.config.js
  examples/styled-components/rspack.config.js
  examples/svgr/rspack.config.js
  examples/vue2-tsx/rspack.config.js
  examples/vue3-jsx/rspack.config.js
  examples/vue3-vanilla/rspack.config.js
  pnpm-lock.yaml
Labels: team

#4636 feat: add auxiliary_files in js chunk
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk.rs
  packages/rspack/src/Chunk.ts
Labels: team, release: feature

#4628 feat: support library for instance unique name
  packages/rspack-plugin-react-refresh/client/reactRefreshEntry.js
  packages/rspack-plugin-react-refresh/src/index.ts
  packages/rspack-plugin-react-refresh/src/options.ts
  packages/rspack-plugin-react-refresh/tests/test.spec.ts
  packages/rspack/src/Compiler.ts
Labels: release: feature

#4637 fix: 🐛 recursive visitor state
  crates/rspack/tests/check.js
  crates/rspack/tests/tree-shaking/issue-4637/index.js
  crates/rspack/tests/tree-shaking/issue-4637/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/issue-4637/snapshot/output.snap
  crates/rspack/tests/tree-shaking/issue-4637/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/issue-4637/test.config.json
  crates/rspack/tests/tree-shaking/issue-4637/util.js
  crates/rspack_core/src/tree_shaking/visitor.rs
Labels: team, release: bug fix

#4629 fix: 🐛 detecting export named decl side effects
  crates/rspack/tests/check.js
  crates/rspack/tests/tree-shaking/named-export-decl-with-src-eval/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/named-export-decl-with-src-eval/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/rollup-unused-var/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/rollup-unused-var/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/ts-target-es5/index.ts
  crates/rspack/tests/tree-shaking/ts-target-es5/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/ts-target-es5/snapshot/output.snap
  crates/rspack/tests/tree-shaking/ts-target-es5/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/snap.diff
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
Labels: team, release: bug fix

#4645 chore: drop NodeJS 14 support
  .github/workflows/reusable-build.yml
  packages/rspack/package.json
Labels: team

#4650 fix: compiler.webpack.ModuleFilenameHelpers type error
  tsconfig.base.json
Labels: team, release: bug fix

#4657 chore: support passing refs to ecosystem-ci
  .github/workflows/ecosystem-ci-trigger.yml
Labels: team

#4653 revert: get export default
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/a.js
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/b.js
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/index.js
  packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/test.config.js
Labels: bug

#4658 ci: disable more optimization.minimize in examples/
  examples/builtin-swc-loader/rspack.config.js
  examples/emotion/rspack.config.js
Labels: team

#4659 test: add test cases for #4643
  packages/rspack/tests/cases/parsing/issue-4643/a.js
  packages/rspack/tests/cases/parsing/issue-4643/b.js
  packages/rspack/tests/cases/parsing/issue-4643/c.js
  packages/rspack/tests/cases/parsing/issue-4643/index.js
Labels: team, A-build-testing

#4651 fix(typing): fix ExternalObject type argument not found
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_values/src/compilation.rs
Labels: release: bug fix

#4665 fix: `require.context` should parse literals
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
  packages/rspack/tests/cases/context/issue-4663/assets/sample.js
  packages/rspack/tests/cases/context/issue-4663/index.js
Labels: team, release: bug fix

#4655 fix: arco pro tree shaking issues
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/answer.js
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/app.js
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/index.js
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/snapshot/output.snap
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/snapshot/snap.diff
  crates/rspack/tests/tree-shaking/pure_comments_magic_comments/test.config.json
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack-dev-server/tsconfig.build.json
Labels: team, release: bug fix

#4675 chore: remove useless pnpm:devPreinstall and doctor.js from `package.json`
  package.json
  scripts/doctor.js
Labels: team

#4674 fix: fix filenames with multiple bytes in match-resource
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/tests/configCases/loader/issue-4630/index.js
  packages/rspack/tests/configCases/loader/issue-4630/webpack.config.js
  packages/rspack/tests/configCases/loader/issue-4630/こんにちは世界.js
  packages/rspack/tests/configCases/loader/issue-4630/你好世界.js
  packages/rspack/tests/configCases/loader/issue-4630/반갑구나세상아.js
  x.mjs
Labels: team, release: bug fix

#4679 fix(runtime): revert alignment of commonjs exports dependency
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/output.snap
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/snapshot/output.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
Labels: team, release: bug fix

#4673 fix(typing): fix packages/rspack-cli ts-expect-error
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/src/utils/profile.ts
Labels: release: bug fix

#4682 feat: support `ContextDependency`
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_dependency.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/dependency_category.rs
  crates/rspack_core/src/dependency/dependency_id.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/import_dependency_trait.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/mod.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_wasm/src/dependency.rs
  crates/rspack_regex/src/lib.rs
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/WatchTestCases.template.ts
Labels: release: feature

#4688 chore: bump dev webpack from 5.76.0 to 5.89.0
  examples/angular/package.json
  package.json
  pnpm-lock.yaml
Labels: team, A-build-testing

#4694 fix(webpack-test): fix the slow 5 seconds test
  webpack-test/cases/parsing/issue-11353/async_generator_function.js
Labels: team, release: bug fix

#4695 fix(webpack-test): fix the 1 second slow test
  webpack-test/configCases/asset-modules/_images/empty.png
  webpack-test/configCases/asset-modules/base-uri/index.js
Labels: team, release: bug fix

#4691 chore: run webpack tests in parallel
  webpack-test/jest.config.js
  webpack-test/package.json
Labels: team

#4698 feat: support optimization.nodeEnv
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/builtin-swc-loader/source-map/index.js
  packages/rspack/tests/configCases/source-map/source-map/index.js
Labels: release: feature

#4705 fix: @swc/jest type error
  crates/node_binding/binding.d.ts
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#4710 chore: remove angular example
  examples/angular/README.md
  examples/angular/angular.json
  examples/angular/package.json
  examples/angular/rspack.config.js
  examples/angular/scripts/build.js
  examples/angular/src/app/app-routing.module.ts
  examples/angular/src/app/app.component.html
  examples/angular/src/app/app.component.scss
  examples/angular/src/app/app.component.spec.ts
  examples/angular/src/app/app.component.ts
  examples/angular/src/app/app.module.ts
  examples/angular/src/assets/.gitkeep
  examples/angular/src/favicon.ico
  examples/angular/src/index.html
  examples/angular/src/main.ts
  examples/angular/src/styles.scss
  examples/angular/tsconfig.app.json
  examples/angular/tsconfig.json
  examples/angular/tsconfig.spec.json
  examples/angular/webpack.config.js
Labels: team

#4707 chore: skip show sccache stats
  .github/actions/docker-build/action.yml
Labels: team

#4709 fix: export StatsCompilation
  packages/rspack/src/exports.ts
Labels: team, release: bug fix

#4693 fix: 🐛assignDeterministicIds alignment
  crates/rspack_core/src/options/output.rs
  crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
  crates/rspack_ids/src/id_helpers.rs
Labels: team, release: bug fix

#4706 chore: skip show sccache stats
  .github/actions/docker-build/action.yml
Labels: team

#4683 fix: 🐛 should invoke `visit_prop` anyway in inner_graph
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
Labels: team, release: bug fix

#4701 fix(harmony-deps-scanner): should only be `dep.call=true` in call_expr or tagged template's tag
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
Labels: team, release: bug fix

#4715 chore(webpack-test): remove the flaky test which requires on timings
  webpack-test/cases/async-modules/runtime-performance/index.js
Labels: team

#4719 chore: pnpm set cache dir by version
  .github/actions/pnpm-cache/action.yml
Labels: team

#4716 chore(chunk_graph): improve chunk_graph perf
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
Labels: team

#4724 perf: reduce aggregateTimeout to speed up HMR
  packages/rspack/src/Watching.ts
Labels: team, release: performance

#4727 feat: `experiments.incrementalRebuild` add deprecation warning
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#4725 fix: sort by chunk name before merge duplicate chunk
  crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
  packages/rspack/tests/cases/chunks/issue-4338/index.js
Labels: release: bug fix

#4728 fix: remove default export
  packages/rspack/src/Compiler.ts
  packages/rspack/src/index.ts
Labels: team, release: bug fix

#4726 ci: improve webpack-test stability
  webpack-examples/asset-simple/images/file.jpg
  webpack-examples/asset-simple/images/file.png
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/asset-modules/_images/empty.png
  webpack-test/configCases/asset-modules/_images/file.jpg
  webpack-test/configCases/asset-modules/_images/file.png
  webpack-test/configCases/asset-modules/_images/file_copy.png
  webpack-test/configCases/asset-modules/base-uri/index.js
  webpack-test/configCases/css/urls/img img.png
  webpack-test/configCases/css/urls/img.png
  webpack-test/configCases/side-effects/url/file.png
Labels: team

#4730 fix(resolver): make sure package.json path is inside the resolved path
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team, release: bug fix

#4717 chore: use eprintln to report error for runtime_requirements
  crates/rspack_core/src/code_generation_results.rs
Labels: team

#4733 chore: self hosted macos skip remove sdk
  .github/workflows/reusable-build.yml
Labels: team

#4732 fix: compare chunks by modules
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_testing/src/test_config.rs
Labels: team, release: bug fix

#4729 fix(harmony-import-specifier-dep-scanner): add new expr into consideration
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
Labels: team, release: bug fix

#4641 feat: support Chunk.groupsIterable and ChunkGroup.getParents
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/tests/answer.js
  crates/node_binding/tests/binding.spec.ts
  crates/node_binding/tests/index.js
  crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/output.snap
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_database/src/database.rs
  packages/rspack/package.json
  packages/rspack/src/Chunk.ts
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/util/comparators.ts
  packages/rspack/tests/configCases/cache/issuse-3254/a/a.js
  packages/rspack/tests/configCases/cache/issuse-3254/index.js
  packages/rspack/tests/configCases/cache/issuse-3254/webpack.config.js
  packages/rspack/tests/configCases/chunk-loading/issue-3896/file/a.js
  packages/rspack/tests/configCases/chunk-loading/issue-3896/index.js
  packages/rspack/tests/configCases/chunk-loading/issue-3896/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/issue-4019/shared.js
  pnpm-lock.yaml
Labels: release: feature

#4737 feat(plugin-driver): add execute module
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/codegen_result.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_testing/src/eval_raw.rs
  crates/rspack_testing/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
Labels: team, release: feature

#4738 refactor: move impl_runtime_module macro to core
  Cargo.lock
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_plugin_hmr/Cargo.toml
  crates/rspack_plugin_hmr/src/hot_module_replacement.rs
  crates/rspack_plugin_runtime/src/runtime_module/async_module.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/base_uri.rs
  crates/rspack_plugin_runtime/src/runtime_module/compat_get_default_export.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_fake_namespace_object.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_script_url.rs
  crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/define_property_getters.rs
  crates/rspack_plugin_runtime/src/runtime_module/ensure_chunk.rs
  crates/rspack_plugin_runtime/src/runtime_module/export_webpack_require.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_update_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_full_hash.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_main_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
  crates/rspack_plugin_runtime/src/runtime_module/global.rs
  crates/rspack_plugin_runtime/src/runtime_module/harmony_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/has_own_property.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_block.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/make_namespace_object.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  crates/rspack_plugin_runtime/src/runtime_module/node_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/normal.rs
  crates/rspack_plugin_runtime/src/runtime_module/on_chunk_loaded.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/startup_chunk_dependencies.rs
  crates/rspack_plugin_runtime/src/runtime_module/startup_entry_point.rs
  crates/rspack_plugin_runtime/src/runtime_module/system_context.rs
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_plugin_wasm/src/runtime.rs
Labels: team

#4744 fix: remove @types/webpack-dev-server
  packages/rspack-dev-server/src/server.ts
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#4743 chore: ci set pnpm store-dir in project
  .github/actions/pnpm-cache/action.yml
Labels: team

#4746 fix: use fixed version for rspack in template
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/create-rspack/template-vue/package.json
Labels: release: bug fix

#4742 feat: support `Compiler.shouldEmit`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  package.json
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/configCases/hooks/should-emit-1/index.js
  packages/rspack/tests/configCases/hooks/should-emit-1/webpack.config.js
  packages/rspack/tests/configCases/hooks/should-emit-2/index.js
  packages/rspack/tests/configCases/hooks/should-emit-2/webpack.config.js
Labels: release: feature

#4642 feat: Module Federation, part 1, ContainerPlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/mf/container/container_entry_dependency.rs
  crates/rspack_core/src/mf/container/container_entry_module.rs
  crates/rspack_core/src/mf/container/container_entry_module_factory.rs
  crates/rspack_core/src/mf/container/container_exposed_dependency.rs
  crates/rspack_core/src/mf/container/container_plugin.rs
  crates/rspack_core/src/mf/container/mod.rs
  crates/rspack_core/src/mf/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/runtime.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/container/ContainerPlugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/options.ts
  packages/rspack/src/exports.ts
  webpack-test/configCases/container/container-entry/test.filter.js
  webpack-test/configCases/container/container-entry/webpack.config.js
Labels: team, release: feature

#4750 chore: fix debugger launcher on window
  crates/node_binding/package.json
  examples/test.js
  package.json
  pnpm-lock.yaml
  scripts/.gitignore
  scripts/debug/launch.mjs
  scripts/package.json
  scripts/tsconfig.json
  x.mjs
Labels: team

#4752 chore: upgrade template to 0.4.0
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react-ts/rspack.config.js
  packages/create-rspack/template-react/package.json
  packages/create-rspack/template-react/rspack.config.js
  packages/create-rspack/template-vanilla/_gitignore
  packages/create-rspack/template-vanilla/index.html
  packages/create-rspack/template-vanilla/package.json
  packages/create-rspack/template-vanilla/rspack.config.js
  packages/create-rspack/template-vanilla/src/index.js
  packages/create-rspack/template-vanilla/src/message.js
  packages/create-rspack/template-vue/package.json
  packages/create-rspack/template-vue/rspack.config.js
  packages/create-rspack/template-vue/src/components/HelloWorld.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: team

#4756 perf: compilation.hooks.optimizeChunkModules auto disable
  packages/rspack/src/Compiler.ts
Labels: team, release: performance

#4668 chore: rspack test tools diff
  .github/workflows/reusable-build.yml
  package.json
  packages/rspack-test-tools/CHANGELOG.md
  packages/rspack-test-tools/LICENSE
  packages/rspack-test-tools/README.md
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/compare/compare.ts
  packages/rspack-test-tools/src/compare/format-code.ts
  packages/rspack-test-tools/src/compare/index.ts
  packages/rspack-test-tools/src/compare/replace-module-argument.ts
  packages/rspack-test-tools/src/compare/replace-runtime-module-name.ts
  packages/rspack-test-tools/src/compiler.ts
  packages/rspack-test-tools/src/helper/index.ts
  packages/rspack-test-tools/src/helper/parse-modules.ts
  packages/rspack-test-tools/src/helper/read-config-file.ts
  packages/rspack-test-tools/src/helper/run-build.ts
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/test/context.ts
  packages/rspack-test-tools/src/test/tester.ts
  packages/rspack-test-tools/src/type.ts
  packages/rspack-test-tools/src/webpack/module-placeholder-plugin.ts
  packages/rspack-test-tools/tsconfig.build.json
  packages/rspack-test-tools/tsconfig.json
  packages/rspack/package.json
  packages/rspack/tests/RuntimeDiff.diff.test.ts
  packages/rspack/tests/helpers/tester/case/diff.ts
  packages/rspack/tests/helpers/tester/case/index.ts
  packages/rspack/tests/helpers/tester/helper/compare-modules.ts
  packages/rspack/tests/helpers/tester/helper/index.ts
  packages/rspack/tests/helpers/tester/helper/parse-modules.ts
  packages/rspack/tests/helpers/tester/helper/replace-module-argument.ts
  packages/rspack/tests/helpers/tester/index.ts
  packages/rspack/tests/helpers/tester/processor/diff.ts
  packages/rspack/tests/helpers/tester/processor/index.ts
  pnpm-lock.yaml
Labels: team, A-build-testing

#4761 fix: typos
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/create-rspack/template-vanilla/package.json
Labels: release: bug fix

#4763 fix: zod-validation-error type error
  diffcases/arco-pro/tsconfig.json
  examples/arco-pro/tsconfig.json
  examples/basic-ts/tsconfig.json
  examples/react-storybook/tsconfig.json
  package.json
  packages/create-rspack/template-react-ts/tsconfig.json
  packages/rspack-plugin-html/tsconfig.json
  packages/rspack-plugin-react-refresh/tsconfig.json
  packages/rspack-test-tools/tsconfig.json
  packages/rspack/package.json
  packages/rspack/tsconfig.json
  pnpm-lock.yaml
  scripts/tsconfig.json
  webpack-test/package.json
Labels: release: bug fix

#4758 chore(webpack-test): make tests more future proof
  package.json
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/async-library/0-create-library/test.filter.js
  webpack-test/configCases/issues/issue-7563/test.filter.js
Labels: team

#4766 fix: only register `SplitChunkPlugin` once
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/configCases/chunk-loading/issue-4754/child-entry.js
  packages/rspack/tests/configCases/chunk-loading/issue-4754/index.js
  packages/rspack/tests/configCases/chunk-loading/issue-4754/webpack.config.js
Labels: release: bug fix

#4772 chore: canary release add windows and enable windows ci on main branch
  .github/workflows/ci.yml
  .github/workflows/release-canary.yml
Labels: team

#4773 feat: support `compilation.hooks.childCompiler`
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: release: feature

#4735 feat: Module Federation, part 2, ContainerReferencePlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/mf/container/container_entry_dependency.rs
  crates/rspack_core/src/mf/container/container_entry_module.rs
  crates/rspack_core/src/mf/container/container_reference_plugin.rs
  crates/rspack_core/src/mf/container/mod.rs
  crates/rspack_core/src/mf/container/module_federation_runtime_plugin.rs
  crates/rspack_core/src/mf/container/remote_module.rs
  crates/rspack_core/src/mf/container/remote_runtime_module.rs
  crates/rspack_core/src/mf/container/remote_to_external_dependency.rs
  crates/rspack_core/src/mf/mod.rs
  crates/rspack_core/src/mf/sharing/mod.rs
  crates/rspack_core/src/mf/sharing/share_runtime_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/utils/extract_url_and_global.rs
  crates/rspack_core/src/utils/mod.rs
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/container/ContainerReferencePlugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
  packages/rspack/src/container/remotesLoading.js
  packages/rspack/src/exports.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/sharing/initializeSharing.js
  packages/rspack/src/util/validate.ts
  webpack-test/configCases/container/circular/test.filter.js
  webpack-test/configCases/container/circular/webpack.config.js
  webpack-test/configCases/container/container-reference/test.filter.js
  webpack-test/configCases/container/container-reference/webpack.config.js
  webpack-test/configCases/container/error-handling/test.filter.js
  webpack-test/configCases/container/error-handling/webpack.config.js
  webpack-test/configCases/container/module-federation/test.filter.js
  webpack-test/configCases/container/module-federation/webpack.config.js
Labels: team, release: feature

#4670 fix uniqueName Acquisition method
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
Labels: release: bug fix

#4781 fix: regex flags
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/tests/configCases/module/test/a.SVG
  packages/rspack/tests/configCases/module/test/index.js
  packages/rspack/tests/configCases/module/test/webpack.config.js
Labels: release: bug fix

#4786 feat: bump swc to support `format.inline_script`
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_css/tests/fixtures/custom/modules-composes/snapshot/output.snap
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/plugins/minify-test/c.js
  packages/rspack/tests/configCases/plugins/minify-test/index.js
  packages/rspack/tests/configCases/plugins/minify-test/webpack.config.js
Labels: release: feature

#4778 feat: Module Federation, part 3, ProvideSharedPlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/mf/container/remote_module.rs
  crates/rspack_core/src/mf/sharing/mod.rs
  crates/rspack_core/src/mf/sharing/provide_for_shared_dependency.rs
  crates/rspack_core/src/mf/sharing/provide_shared_dependency.rs
  crates/rspack_core/src/mf/sharing/provide_shared_module.rs
  crates/rspack_core/src/mf/sharing/provide_shared_module_factory.rs
  crates/rspack_core/src/mf/sharing/provide_shared_plugin.rs
  crates/rspack_core/src/mf/sharing/share_runtime_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/container/ContainerReferencePlugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/sharing/ProvideSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
  packages/rspack/src/sharing/initializeSharing.js
  packages/rspack/src/sharing/utils.ts
  webpack-test/configCases/sharing/provide-eager-module/node_modules/common/index.js
  webpack-test/configCases/sharing/provide-eager-module/node_modules/common/package.json
  webpack-test/configCases/sharing/provide-eager-module/node_modules/uncommon/index.js
  webpack-test/configCases/sharing/provide-eager-module/node_modules/uncommon/package.json
  webpack-test/configCases/sharing/provide-eager-module/test.filter.js
  webpack-test/configCases/sharing/provide-eager-module/webpack.config.js
  webpack-test/configCases/sharing/provide-module/node_modules/package/index.js
  webpack-test/configCases/sharing/provide-module/node_modules/package/package.json
  webpack-test/configCases/sharing/provide-module/test.filter.js
  webpack-test/configCases/sharing/provide-module/webpack.config.js
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/my-module/index.js
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/my-module/node_modules/shared/index.js
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/my-module/node_modules/shared/package.json
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/shared/index.js
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/shared/package.json
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/unused-module/node_modules/shared/index.js
  webpack-test/configCases/sharing/provide-multiple-versions/node_modules/unused-module/node_modules/shared/package.json
  webpack-test/configCases/sharing/provide-multiple-versions/webpack.config.js
  webpack-test/configCases/sharing/provide-shared-with-runtime-chunk/node_modules/x/index.js
  webpack-test/configCases/sharing/provide-shared-with-runtime-chunk/node_modules/x/package.json
  webpack-test/configCases/sharing/provide-shared-with-runtime-chunk/test.filter.js
  webpack-test/configCases/sharing/provide-shared-with-runtime-chunk/webpack.config.js
Labels: team, release: feature

#4782 fix: keep the query passed to loader
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/tests/configCases/module/issue-4777/index.js
  packages/rspack/tests/configCases/module/issue-4777/loader.js
  packages/rspack/tests/configCases/module/issue-4777/sub/a.js
  packages/rspack/tests/configCases/module/issue-4777/sub/b.js
  packages/rspack/tests/configCases/module/issue-4777/sub/c.js
  packages/rspack/tests/configCases/module/issue-4777/sub/d.js
  packages/rspack/tests/configCases/module/issue-4777/sub/e.js
  packages/rspack/tests/configCases/module/issue-4777/sub/f.js
  packages/rspack/tests/configCases/module/issue-4777/sub/g.js
  packages/rspack/tests/configCases/module/issue-4777/sub/h.js
  packages/rspack/tests/configCases/module/issue-4777/webpack.config.js
  webpack-test/configCases/loaders/issue-3320/test.filter.js
Labels: release: bug fix

#4793 fix: mf test on windows
  packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
Labels: team, release: bug fix

#4764 feat: support String.raw for context module
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs
  packages/rspack/tests/cases/context/context-module-cjs-require-tagged-template/child/child/index.js
  packages/rspack/tests/cases/context/context-module-cjs-require-tagged-template/child/index.js
  packages/rspack/tests/cases/context/context-module-cjs-require-tagged-template/index.js
  packages/rspack/tests/cases/context/context-module-dynamic-import-tagged-template/child/index.js
  packages/rspack/tests/cases/context/context-module-dynamic-import-tagged-template/index.js
  webpack-test/cases/parsing/complex-require/test.filter.js
Labels: release: feature

#4794 fix: use correct DefinePlugin in plugin-react-refresh
  packages/rspack-plugin-react-refresh/src/index.ts
Labels: team, release: bug fix

#4810 fix: include tpl string into bail out module ident
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  packages/rspack/tests/configCases/chunk-loading/issue-4800/index.js
  packages/rspack/tests/configCases/chunk-loading/issue-4800/logo1.js
  packages/rspack/tests/configCases/chunk-loading/issue-4800/logo2.js
  packages/rspack/tests/configCases/chunk-loading/issue-4800/webpack.config.js
  pnpm-lock.yaml
Labels: release: bug fix

#4807 fix(plugin-react-refresh): fix peer warning and reduce dependencies
  packages/rspack-plugin-react-refresh/client/reactRefresh.js
  packages/rspack-plugin-react-refresh/client/refreshUtils.js
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-plugin-react-refresh/src/index.ts
  pnpm-lock.yaml
Labels: team, release: bug fix

#4813 fix: bump styled_components and add tests
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/src/transformer.rs
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/Button2/index.jsx
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/index.jsx
Labels: release: bug fix

#4806 chore: diff html reporter integration
  .github/workflows/diff.yml
  packages/rspack-test-tools/src/reporter/diff-html.ts
  packages/rspack-test-tools/src/reporter/index.ts
  packages/rspack-test-tools/viewer/templates/diff.html
  scripts/diff.cjs
Labels: team, A-build-testing

#4824 fix: updated swc to solve the asciionly bug
  Cargo.lock
  Cargo.toml
  packages/rspack/tests/configCases/plugins/issue-4797/index.js
  packages/rspack/tests/configCases/plugins/issue-4797/webpack.config.js
Labels: release: bug fix

#4811 ci: diff html reporter
  .github/workflows/diff.yml
  packages/rspack-test-tools/src/reporter/diff-stats.ts
  scripts/diff.cjs
Labels: team, A-build-testing

#4829 fix: repeat report view link in stats report
  packages/rspack-test-tools/src/reporter/diff-stats.ts
Labels: release: bug fix

#4831 fix: nested new url
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  packages/rspack/tests/cases/parsing/nested-new-url/a.txt
  packages/rspack/tests/cases/parsing/nested-new-url/index.js
Labels: team, release: bug fix

#4830 fix(resolver): resolve query and fragments with unicode filenames
  Cargo.lock
  crates/rspack_core/Cargo.toml
  packages/rspack/tests/cases/resolve/query/index.js
  packages/rspack/tests/cases/resolve/query/测试.js
Labels: team, release: bug fix
