Repository web-infra-dev/rspack, pull requests merged in 2023-08, with the labels that each got.

#3852 refactor: css-import span should be calculated with at-rule
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
Labels: team

#3873 feat(css): remove support for `@rspack/postcss-loader`
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack/tests/configCases/postcss/basic/index.css
  packages/rspack/tests/configCases/postcss/basic/index.js
  packages/rspack/tests/configCases/postcss/basic/index.module.css
  packages/rspack/tests/configCases/postcss/basic/webpack.config.js
  packages/rspack/tests/configCases/postcss/css-modules-with-tree-shaking/a.js
  packages/rspack/tests/configCases/postcss/css-modules-with-tree-shaking/index.css
  packages/rspack/tests/configCases/postcss/css-modules-with-tree-shaking/index.js
  packages/rspack/tests/configCases/postcss/css-modules-with-tree-shaking/index.module.css
  packages/rspack/tests/configCases/postcss/css-modules-with-tree-shaking/webpack.config.js
  packages/rspack/tests/configCases/postcss/modules-config/auto-false.module.css
  packages/rspack/tests/configCases/postcss/modules-config/auto-function.css
  packages/rspack/tests/configCases/postcss/modules-config/auto-regex.css
  packages/rspack/tests/configCases/postcss/modules-config/auto-true.module.css
  packages/rspack/tests/configCases/postcss/modules-config/generateScopedName.module.css
  packages/rspack/tests/configCases/postcss/modules-config/index.js
  packages/rspack/tests/configCases/postcss/modules-config/localsConvention.module.css
  packages/rspack/tests/configCases/postcss/modules-config/modules-false.module.css
  packages/rspack/tests/configCases/postcss/modules-config/modules-true.css
  packages/rspack/tests/configCases/postcss/modules-config/webpack.config.js
  packages/rspack/tests/configCases/postcss/with-previous-source-map/index.js
  packages/rspack/tests/configCases/postcss/with-previous-source-map/index.scss
  packages/rspack/tests/configCases/postcss/with-previous-source-map/webpack.config.js
  packages/rspack/tests/configCases/postcss/with-source-map/index.css
  packages/rspack/tests/configCases/postcss/with-source-map/index.js
  packages/rspack/tests/configCases/postcss/with-source-map/webpack.config.js
Labels: team, release: breaking change, release: feature

#3871 feat: create fake namespace object for import context module
  crates/rspack/tests/fixtures/code-splitting/expected/main.js
  crates/rspack/tests/fixtures/dynamic-import/expected/main.js
  crates/rspack/tests/samples/remove-parent-modules/cycle-dynamic-entry/expected/dynamic-1_js.js
  crates/rspack/tests/samples/remove-parent-modules/cycle-dynamic-entry/expected/dynamic-2_js.js
  crates/rspack/tests/samples/remove-parent-modules/cycle-entry/expected/index.js
  crates/rspack/tests/samples/remove-parent-modules/cycle-entry/expected/index2.js
  crates/rspack/tests/samples/remove-parent-modules/cycle-entry/expected/index_js.js
  crates/rspack/tests/samples/remove-parent-modules/intersection/expected/index.js
  crates/rspack/tests/samples/remove-parent-modules/intersection/expected/index2.js
  crates/rspack/tests/samples/remove-parent-modules/self-import/expected/main.js
  crates/rspack/tests/samples/remove-parent-modules/simple/expected/main.js
  crates/rspack/tests/tree-shaking/tree-shaking-lazy-import/expected/main.js
  crates/rspack/tests/tree-shaking/webpack-innergraph-circular/expected/main.js
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/fake_namespace_object.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/runtime/lazy_context_module.js
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/main.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  webpack-test/cases/mjs/namespace-object-lazy/test.filter.js
  webpack-test/cases/mjs/non-mjs-namespace-object-lazy/test.filter.js
Labels: team, release: feature

#3876 fix: render library runtime for include entry chunks
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/library/umd-named-define-runtime-chunk/index.js
  packages/rspack/tests/configCases/library/umd-named-define-runtime-chunk/webpack.config.js
  webpack-test/configCases/library/a/test.filter.js
  webpack-test/configCases/library/array-global/test.filter.js
  webpack-test/configCases/library/array-window/test.filter.js
  webpack-test/configCases/library/assign-properties/test.filter.js
  webpack-test/configCases/library/b/test.filter.js
  webpack-test/configCases/library/type-assign-properties/test.filter.js
  webpack-test/configCases/library/type-assign-runtime-chunk/test.filter.js
  webpack-test/configCases/library/type-assign/test.filter.js
  webpack-test/configCases/library/umd-array/test.filter.js
  webpack-test/configCases/library/umd/test.filter.js
Labels: team, release: bug fix

#3880 refactor: parse result remove ast
  crates/node_binding/src/js_values/compilation.rs
  crates/rspack_core/src/cache/occasion/code_generate.rs
  crates/rspack_core/src/cache/occasion/create_chunk_assets.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_asset/tests/fixtures/webpack/asset-simple/expected/main.js
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/7908863e290b1fc6.svg
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/ef0c5aab88bb335e.svg
  crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/main.js
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  crates/rspack_plugin_wasm/tests/fixtures/v128/expected/main.js
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/__snapshots__/case.test.ts.snap
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
Labels: team

#3892 feat: add more context for error frame
  Cargo.lock
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/emitter.rs
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/fixtures__char-based-offset-error-span.snap
  crates/rspack_error/tests/fixtures/html_syntax_error/fixtures__html_syntax_error.snap
  crates/rspack_error/tests/fixtures/js_syntax_error/fixtures__js_syntax_error.snap
  crates/rspack_error/tests/fixtures/jsx_syntax_error/fixtures__jsx_syntax_error.snap
  crates/rspack_error/tests/fixtures/recoverable_syntax_error/fixtures__recoverable_syntax_error.snap
  crates/rspack_error/tests/fixtures/sass-warnings/fixtures__sass-warnings.snap
  crates/rspack_error/tests/fixtures/ts_syntax_error/fixtures__ts_syntax_error.snap
  crates/rspack_error/tests/fixtures/tsx_syntax_error/fixtures__tsx_syntax_error.snap
  crates/rspack_error/tests/out_of_order/multi_json_syntax_error/fixtures__multi_json_syntax_error.snap
  crates/rspack_error/tests/out_of_order/multiple_file_syntax_error/fixtures__multiple_file_syntax_error.snap
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#3831 fix: modify Configuration type to support MultiRspackOptions
  packages/rspack/package.json
  packages/rspack/src/config/types.ts
  packages/rspack/src/index.ts
  packages/rspack/tests/configCases/type/multiple-options/index.js
  packages/rspack/tests/configCases/type/multiple-options/rspack.config.js
  packages/rspack/tsconfig.test.json
Labels: release: bug fix

#3893 feat: stats logging
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/logger.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.383f50b7350faed1.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.383f50b7350faed1.html
  crates/rspack_plugin_real_content_hash/src/lib.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#3884 fix(core): add resove failing reason for import in esm file
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_error/src/emitter.rs
  packages/rspack/tests/Compiler.test.ts
  packages/rspack/tests/Errors.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/fixtures/errors/resolve-fail-esm/answer.js
  packages/rspack/tests/fixtures/errors/resolve-fail-esm/index.js
  packages/rspack/tests/fixtures/errors/resolve-fail-esm/package.json
  packages/rspack/tests/fixtures/temp-watch-1569996664301/bundle.js
Labels: team, release: bug fix

#3902 revert: "fix: modify Configuration type to support MultiRspackOptions"
  packages/rspack/package.json
  packages/rspack/src/config/types.ts
  packages/rspack/src/index.ts
  packages/rspack/tests/configCases/type/multiple-options/index.js
  packages/rspack/tests/configCases/type/multiple-options/rspack.config.js
  packages/rspack/tsconfig.test.json
Labels: team

#3905 feat: stats logging, part 2
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/logger.rs
  packages/playground/cases/context/delete-file/index.test.ts
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/logging/Logger.ts
  packages/rspack/src/stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/logging/index.js
  packages/rspack/tests/statsCases/logging/test-loader.js
  packages/rspack/tests/statsCases/logging/webpack.config.js
Labels: team, release: feature

#3911 chore: add deprecate message in rspack-dev-middleware readme
  packages/rspack-dev-middleware/README.md
Labels: team

#3907 fix: fix a panic issue of `get_hash` if assertion is failed
  crates/node_binding/src/js_values/stats.rs
Labels: team, release: bug fix

#3912 fix: should generate diffrent name for chunk asset at hmr
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  packages/rspack/tests/hotCases/chunk/asset/changed-file.js
  packages/rspack/tests/hotCases/chunk/asset/file.js
  packages/rspack/tests/hotCases/chunk/asset/index.js
  packages/rspack/tests/hotCases/chunk/asset/raw.png
  packages/rspack/tests/hotCases/chunk/asset/webpack.config.js
Labels: team, release: bug fix

#3906 test: migrate inner-graph test
  webpack-test/cases/inner-graph/circular/test.config.js
  webpack-test/cases/inner-graph/circular/test.filter.js
  webpack-test/cases/inner-graph/circular2/test.config.js
  webpack-test/cases/inner-graph/circular2/test.filter.js
  webpack-test/cases/inner-graph/class-dynamic-props/test.config.js
  webpack-test/cases/inner-graph/class-dynamic-props/test.filter.js
  webpack-test/cases/inner-graph/export-default-named/test.config.js
  webpack-test/cases/inner-graph/export-default-named/test.filter.js
  webpack-test/cases/inner-graph/extend-class/test.config.js
  webpack-test/cases/inner-graph/extend-class/test.filter.js
  webpack-test/cases/inner-graph/extend-class2/test.config.js
  webpack-test/cases/inner-graph/extend-class2/test.filter.js
  webpack-test/cases/inner-graph/no-side-effects/test.config.js
  webpack-test/cases/inner-graph/no-side-effects/test.filter.js
  webpack-test/cases/inner-graph/pure-in-removed/test.config.js
  webpack-test/cases/inner-graph/pure-in-removed/test.filter.js
  webpack-test/cases/inner-graph/reexport-namespace-and-default/test.config.js
  webpack-test/cases/inner-graph/reexport-namespace-and-default/test.filter.js
  webpack-test/cases/inner-graph/simple/test.config.js
  webpack-test/cases/inner-graph/simple/test.filter.js
  webpack-test/cases/inner-graph/static-of-class/test.config.js
  webpack-test/cases/inner-graph/static-of-class/test.filter.js
  webpack-test/cases/inner-graph/switch/test.config.js
  webpack-test/cases/inner-graph/switch/test.filter.js
  webpack-test/cases/inner-graph/try-globals/test.config.js
  webpack-test/cases/inner-graph/try-globals/test.filter.js
Labels: team

#3895 feat: more generic nested import
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/expected/main.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package.json
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/a.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/aa.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/b.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/c.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/index.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/package.json
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/src/index.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/src/index.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/test.config.json
  crates/rspack/tests/tree-shaking/simple-namespace-access/expected/main.js
  crates/rspack_core/src/tree_shaking/js_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
Labels: team, release: feature

#3915 feat: support minifyOptions.asciiOnly
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/builtins.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/builtins/minify-ascii-only/a.js
  packages/rspack/tests/configCases/builtins/minify-ascii-only/index.js
  packages/rspack/tests/configCases/builtins/minify-ascii-only/webpack.config.js
Labels: release: feature, need documentation

#3916 feat: add more logger.time in plugins
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
  crates/rspack_plugin_remove_empty_chunks/src/lib.rs
  crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs
  packages/rspack/tests/Stats.test.ts
Labels: team, release: feature

#3924 feat: support configuration.profile
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/module_profile.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/index.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#3923 feat(chunkIds): align `chunkIds: 'named'` with Webpack
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/utils/find_graph_roots.rs
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/index.js
Labels: team, release: feature

#3929 fix: tree shaking visit dynamic prop
  crates/rspack_core/src/tree_shaking/visitor.rs
  packages/rspack/tests/configCases/tree-shaking/member-expr-computed-prop/index.js
  packages/rspack/tests/configCases/tree-shaking/member-expr-computed-prop/lib.js
  packages/rspack/tests/configCases/tree-shaking/member-expr-computed-prop/package.json
  packages/rspack/tests/configCases/tree-shaking/member-expr-computed-prop/webpack.config.js
Labels: team, release: bug fix

#3904 fix: import export all as is empty module
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/a.js
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/answer.js
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/app.js
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/expected/main.js
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/index.js
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3930 chore: nest example support hmr
  examples/nestjs/package.json
  examples/nestjs/rspack.config.js
  examples/nestjs/src/main.ts
  pnpm-lock.yaml
Labels: team

#3927 feat: support minifyOptions.comments
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_plugin_javascript/src/ast/minify.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/builtins.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/builtins/minify-comment-all/a.js
  packages/rspack/tests/configCases/builtins/minify-comment-all/index.js
  packages/rspack/tests/configCases/builtins/minify-comment-all/webpack.config.js
  packages/rspack/tests/configCases/builtins/minify-comment-default-false/a.js
  packages/rspack/tests/configCases/builtins/minify-comment-default-false/index.js
  packages/rspack/tests/configCases/builtins/minify-comment-default-false/webpack.config.js
  packages/rspack/tests/configCases/builtins/minify-comment-some/a.js
  packages/rspack/tests/configCases/builtins/minify-comment-some/index.js
  packages/rspack/tests/configCases/builtins/minify-comment-some/webpack.config.js
Labels: release: feature

#3934 perf: reduce `compilation.getAssets` overhead
  packages/rspack/src/compilation.ts
Labels: team, release: performance

#3935 chore: add close-issues bot
  .github/issue-close-require.yml
Labels: team

#3938 fix(core): remove webpack-dev-server from @rspack/core
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#3942 feat: support more predefined processAssets stage on js side
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/js_values/hooks.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/util/fake.ts
  packages/rspack/tests/configCases/plugins/internal-processAssets-stage/index.js
  packages/rspack/tests/configCases/plugins/internal-processAssets-stage/webpack.config.js
Labels: team, release: feature

#3899 fix(core): fix missing source_info in esm module error
  crates/rspack_core/src/utils/hooks.rs
  packages/rspack/tests/Errors.test.ts
Labels: team, release: bug fix

#3947 fix: nested import follow a export all symbol
  crates/rspack/tests/tree-shaking/nested-import-3/answer.js
  crates/rspack/tests/tree-shaking/nested-import-3/app.js
  crates/rspack/tests/tree-shaking/nested-import-3/expected/main.js
  crates/rspack/tests/tree-shaking/nested-import-3/index.js
  crates/rspack/tests/tree-shaking/nested-import-3/lib.js
  crates/rspack/tests/tree-shaking/nested-import-3/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3946 chore: normalize filename
  packages/rspack-cli/src/commands/build.ts
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/MultiStats.ts
  packages/rspack/src/MultiWatching.ts
  packages/rspack/src/NormalModule.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/src/Stats.ts
  packages/rspack/src/Watching.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/optimization/index.ts
  packages/rspack/src/config/zod/plugins.ts
  packages/rspack/src/index.ts
  packages/rspack/src/lib/BannerPlugin.js
  packages/rspack/src/lib/LoaderOptionsPlugin.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/StatsFactory.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/index.ts
  packages/rspack/src/web/ResolveSwcPlugin.ts
  packages/rspack/tests/Compiler.test.ts
  pnpm-lock.yaml
Labels: team

#3948 fix: fix trace subscriber for dev
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/utils.rs
  crates/rspack_tracing/src/lib.rs
  packages/rspack/src/rspack.ts
Labels: team, release: bug fix

#3951 fix: nested import with export imported dependency
  crates/rspack/tests/tree-shaking/nested-import-4/answer.js
  crates/rspack/tests/tree-shaking/nested-import-4/expected/main.js
  crates/rspack/tests/tree-shaking/nested-import-4/index.js
  crates/rspack/tests/tree-shaking/nested-import-4/lib.js
  crates/rspack/tests/tree-shaking/nested-import-4/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#3957 revert: "chore: normalize filename"
  packages/rspack-cli/src/commands/build.ts
  packages/rspack/src/chunk_group.ts
  packages/rspack/src/compilation.ts
  packages/rspack/src/compiler.ts
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/optimization/index.ts
  packages/rspack/src/config/zod/plugins.ts
  packages/rspack/src/index.ts
  packages/rspack/src/lib/BannerPlugin.js
  packages/rspack/src/lib/LoaderOptionsPlugin.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/multiCompiler.ts
  packages/rspack/src/multiStats.ts
  packages/rspack/src/multiWatching.ts
  packages/rspack/src/normalModule.ts
  packages/rspack/src/normalModuleFactory.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/StatsFactory.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/index.ts
  packages/rspack/src/watching.ts
  packages/rspack/src/web/ResolveSwcPlugin.ts
  packages/rspack/tests/Compiler.test.ts
  pnpm-lock.yaml
Labels: team

#3937 feat: add profile switch in cli
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/utils.rs
  crates/rspack/tests/fixtures.rs
  crates/rspack_error/tests/fixtures.rs
  crates/rspack_testing/examples/build-cli.rs
  crates/rspack_testing/src/run_fixture.rs
  crates/rspack_tracing/src/lib.rs
  packages/rspack-cli/package.json
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/build/profile/profile.test.ts
  packages/rspack-cli/tests/build/profile/rspack.config.js
  packages/rspack-cli/tests/build/profile/src/index.js
  packages/rspack-cli/tests/utils/test-utils.ts
  packages/rspack/src/index.ts
  packages/rspack/src/rspack.ts
  pnpm-lock.yaml
Labels: team, release: feature

#3964 chore: move binding utils
  crates/node_binding/src/lib.rs
  crates/node_binding/src/utils.rs
Labels: team

#3053 feat(chunkIds): support `optimization.chunkIds: 'deterministic'`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_ids/Cargo.toml
  crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod/optimization/index.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: p2-signifincant, ready to merge, release: feature

#3965 feat: add logging when RSPACK_PROFILE enabled
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/build/profile/profile.test.ts
Labels: team, release: feature

#3971 chore: test multi pull request template
  .github/PULL_REQUEST_TEMPLATE/minor-release-mr.md
Labels: team

#3970 fix: getHash occasionally panic when rebuild
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/watchCases/stats/get-hash-panic/0/changing-file.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/0/index.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/1/changing-file.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/2/changing-file.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/webpack.config.js
Labels: team, release: bug fix

#3975 chore: sync doc when add need documentation label
  .github/workflows/need-doc.yml
Labels: team

#3978 chore: test label
  .github/workflows/need-doc.yml
Labels: team

#3979 chore: add release scope
  .github/workflows/lint-pr.yaml
Labels: team

#3973 feat(core): expose `RuntimeGlobals`
  packages/rspack/src/RuntimeGlobals.ts
  packages/rspack/src/index.ts
Labels: release: feature, need documentation

#3980 feat: support dispatching builtin loaders on Node
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/loader.rs
  crates/node_binding/src/plugins/loader.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_swc/src/lib.rs
  packages/rspack/src/compilation.ts
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/loadLoader.js
  packages/rspack/src/util/index.ts
Labels: team, release: feature

#3985 feat: add timestamp on profile dist
  packages/rspack-cli/src/rspack-cli.ts
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/build/profile/profile.test.ts
Labels: team, release: feature

#3983 chore: support nodejs benchmark
  .github/workflows/bench-history.yaml.bak
  .github/workflows/bench-rust.yaml
  .github/workflows/bench.yml
Labels: team

#3987 chore: remove benchmark test on merge_group
  .github/workflows/bench.yml
Labels: team

#3992 chore: add postcss-loader-example
  examples/postcss-loader/index.html
  examples/postcss-loader/package.json
  examples/postcss-loader/rspack.config.js
  examples/postcss-loader/src/index.css
  examples/postcss-loader/src/index.js
  pnpm-lock.yaml
Labels: team

#3994 chore: benchmark pr remove useless inputs
  .github/workflows/bench.yml
Labels: team

#3988 feat: support builtin loader with inline loader syntax
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/loader.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_options/src/options/raw_target.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/utils/identifier.rs
  crates/rspack_error/tests/fixtures.rs
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_testing/examples/build-cli.rs
  crates/rspack_testing/src/run_fixture.rs
  crates/rspack_testing/src/test_config.rs
  examples/vue/rspack.config.js
  examples/vue2-ts/rspack.config.js
  examples/vue2-ts/src/App.vue
  examples/vue2/rspack.config.js
  packages/rspack/src/config/adapter-rule-use.ts
  packages/rspack/src/loader-runner/loadLoader.js
  packages/rspack/tests/configCases/builtin-swc-loader/basic/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/basic/lib.ts
  packages/rspack/tests/configCases/builtin-swc-loader/basic/pitching-loader.js
  packages/rspack/tests/configCases/builtin-swc-loader/basic/webpack.config.js
Labels: team, release: feature

#3998 feat: support resolving builtin loaders in Rust tests
  Cargo.lock
  crates/bench/src/main.rs
  crates/rspack/benches/main.rs
  crates/rspack/tests/fixtures.rs
  crates/rspack_error/tests/fixtures.rs
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/test.config.json
  crates/rspack_error/tests/fixtures/sass-warnings/test.config.json
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/test.config.json
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures/esm/test.config.json
  crates/rspack_loader_swc/tests/fixtures/ts/test.config.json
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/examples/build-cli.rs
  crates/rspack_testing/src/lib.rs
  crates/rspack_testing/src/loader.rs
  crates/rspack_testing/src/run_fixture.rs
  crates/rspack_testing/src/test_config.rs
  crates/rspack_testing/test.config.scheme.json
Labels: team, release: feature

#3999 chore: add oxlint
  .eslintignore
  .github/workflows/ci.yml
  examples/loader-compat/rspack.config.js
  package.json
  pnpm-lock.yaml
Labels: team

#3972 perf: reduce memory size of const dependency and dependency type
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
Labels: team, release: performance

#3989 chore: add condition to module graph connection
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
Labels: team

#4007 feat(webpack-tree-shaking): side effects plugin
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: feature

#4005 fix: disable DevtoolPlugin when options.devtool=false
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/options/devtool.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.4344d8eb2dd8519f.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.4344d8eb2dd8519f.html
  crates/rspack_testing/src/test_config.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: release: bug fix

#3995 chore: add benchmark test for merge queue
  .github/workflows/bench-merge-queue.yml
Labels: team

#4004 feat: merge same init fragments
  crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/expected/main.js
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_plugin_javascript/src/runtime.rs
Labels: team, release: feature

#3962 feat: cjs analyze
  crates/rspack/tests/fixtures/code-splitting/expected/main.js
  crates/rspack/tests/samples/remove-parent-modules/self-import/expected/main.js
  crates/rspack/tests/tree-shaking/cjs-export-computed-property/expected/main.js
  crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/expected/main.js
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/main.js
Labels: team, release: feature

#4022 fix(runtime): should calculate `initial_chunks` correctly
  crates/rspack_core/src/chunk.rs
  packages/rspack/tests/runtimeCases/runtime/issue-4019/dynamic.js
  packages/rspack/tests/runtimeCases/runtime/issue-4019/index.js
  packages/rspack/tests/runtimeCases/runtime/issue-4019/index2.js
  packages/rspack/tests/runtimeCases/runtime/issue-4019/shared.js
  packages/rspack/tests/runtimeCases/runtime/issue-4019/webpack.config.js
Labels: team, release: bug fix

#4018 ci: reduce binary size
  .github/workflows/reusable-build.yml
Labels: team

#4026 refactor: changed ModuleGraph dependencies to BoxDependency
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/tree_shaking/js_module.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.4344d8eb2dd8519f.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/default.dcfc4627956fe13e.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.4344d8eb2dd8519f.html
  crates/rspack_plugin_html/tests/fixtures/filename/expected/index.dcfc4627956fe13e.html
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_plugin_wasm/src/dependency.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#3982 refactor(rspack_loader_runner): remove nodejs_resolver dependency
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/utils/module_rules.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_loader_runner/src/runner.rs
Labels: team

#4017 fix: tree shaking transitive bailout
  crates/rspack/tests/tree-shaking/transitive-bailout/a.js
  crates/rspack/tests/tree-shaking/transitive-bailout/answer.js
  crates/rspack/tests/tree-shaking/transitive-bailout/expected/main.js
  crates/rspack/tests/tree-shaking/transitive-bailout/index.js
  crates/rspack/tests/tree-shaking/transitive-bailout/lib.js
  crates/rspack/tests/tree-shaking/transitive-bailout/test.config.json
  crates/rspack_core/src/tree_shaking/optimizer.rs
Labels: team, release: bug fix

#4034 perf: reduce ModuleGraphModule memory size
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_util/src/comparators.rs
Labels: team, release: performance

#4010 feat: add HarmonyImportSideEffectDependency
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_side_effect_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#4037 perf: merge HarmonyImportSideEffectDependency into HarmonyImportDependency
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_side_effect_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: performance

#4029 revert: "fix: getHash occasionally panic when rebuild (#3970)"
  crates/node_binding/binding.d.ts
  crates/node_binding/src/js_values/compilation.rs
  crates/node_binding/src/js_values/stats.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/missing_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/watchCases/stats/get-hash-panic/0/changing-file.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/0/index.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/1/changing-file.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/2/changing-file.js
  packages/rspack/tests/watchCases/stats/get-hash-panic/webpack.config.js
Labels: team

#4008 feat: support option `resolveLoader`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/loader.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod/index.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/loader/additional-data/webpack.config.js
  packages/rspack/tests/configCases/loader/source-map/webpack.config.js
  webpack-test/configCases/loaders/issue-3320/deprecations.js
  webpack-test/configCases/loaders/issue-3320/index.js
  webpack-test/configCases/loaders/issue-3320/test.filter.js
  webpack-test/scripts/test-metric.js
Labels: team, release: feature

#4014 feat: export `Watching` type
  packages/rspack/src/index.ts
Labels: team, release: feature

#4028 fix: add workaround for accessing previous stats
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#4035 perf: reduce task structs memory size
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/compiler/resolver.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_loader_sass/src/lib.rs
Labels: team, release: performance

#4011 chore: fix nestjs example
  examples/nestjs/package.json
  examples/nestjs/rspack.config.js
Labels: team

#4038 feat: support `ident` for builtin loader
  crates/node_binding/src/plugins/loader.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_runner/src/scheme.rs
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/tests/configCases/loader/builtin-loader-ident/index.js
  packages/rspack/tests/configCases/loader/builtin-loader-ident/lib.ts
  packages/rspack/tests/configCases/loader/builtin-loader-ident/webpack.config.js
Labels: team, release: feature

#4046 refactor: add InitFragment trait
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
Labels: team

#4048 refactor(rspack_core): implement resolver proxy
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/resolver.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/resolve.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_core/src/utils/hooks.rs
  crates/rspack_core/src/utils/mod.rs
Labels: team

#4045 feat: FlagDependencyExports part 1
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/provided_exports_plugin.rs
Labels: team, release: feature

#4053 chore: run oxlint on all files during lint-staged (for now)
  lint-staged.config.mjs
  package.json
Labels: team

#4055 fix: source map not update when hmr
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_plugin_hmr/Cargo.toml
  crates/rspack_plugin_hmr/LICENSE
  crates/rspack_plugin_hmr/src/hot_module_replacement.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_hmr/src/runtime/hot_module_replacement.js
  crates/rspack_plugin_runtime/src/hot_module_replacement.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/src/test_config.rs
  packages/rspack/tests/hotCases/source-map/disable/changed-file.js
  packages/rspack/tests/hotCases/source-map/disable/file.js
  packages/rspack/tests/hotCases/source-map/disable/index.js
  packages/rspack/tests/hotCases/source-map/disable/webpack.config.js
  packages/rspack/tests/hotCases/source-map/enable/changed-file.js
  packages/rspack/tests/hotCases/source-map/enable/file.js
  packages/rspack/tests/hotCases/source-map/enable/index.js
  packages/rspack/tests/hotCases/source-map/enable/webpack.config.js
Labels: team, release: bug fix

#4052 feat: implement HarmonyExportSpecifierDependency get_exports
  crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/expected/main.js
  crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/expected/main.js
  crates/rspack/tests/tree-shaking/react-redux-like/expected/main.js
  crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/expected/main.js
  crates/rspack/tests/tree-shaking/simple-namespace-access/expected/main.js
  crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/expected/main.js
  crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/expected/main.js
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/provided_exports_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
Labels: team, release: feature

#4058 chore: fix cache problem
  Cargo.lock
  crates/rspack_error/Cargo.toml
Labels: team

#4068 chore: takedown node14 test on windows
  .github/workflows/reusable-build.yml
Labels: team

#4071 fix: sort import var at wasm codegen
  Cargo.lock
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/tests/fixtures/.imports-multiple/expected/main.js
  crates/rspack_plugin_wasm/tests/fixtures/.imports-multiple/snapshot/output.snap
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/index.js
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/module.js
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/module2.js
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/snapshot/output.snap
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/test.config.json
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/wasm.wasm
Labels: team, release: bug fix

#4073 feat: expose `EntryPlugin`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/index.ts
  packages/rspack/src/lib/EntryOptionPlugin.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team, release: feature

#4057 feat: provide exports p2
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/provided_exports_plugin.rs
Labels: team, release: feature

#4077 chore: skip empty test folder
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/configCases/css/urls/webpack.config.js
Labels: team

#4085 fix: umd analyze
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  packages/rspack/tests/cases/mjs/cjs-import-default/index.mjs
  packages/rspack/tests/cases/mjs/cjs-import-default/umd.js
Labels: team, release: bug fix

#4083 feat: expose `ExternalsPlugin`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_plugin_externals/src/electron_target_plugin.rs
  crates/rspack_plugin_externals/src/http_externals_plugin.rs
  crates/rspack_plugin_externals/src/lib.rs
  crates/rspack_plugin_externals/src/node_target_plugin.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/builtin-plugin/ElectronTargetPlugin.ts
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/builtin-plugin/HttpExternalsPlugin.ts
  packages/rspack/src/builtin-plugin/NodeTargetPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team, release: feature

#4086 ci: only run `merge_group` tests on check being requested
  .github/workflows/ci.yml
Labels: team
