Repository web-infra-dev/rspack, pull requests merged in 2024-03, with the labels that each got.

#5826 fix: @rspack/dev-server Cannot find module
  packages/rspack-dev-server/src/server.ts
Labels: release: bug fix

#5830 perf: let CachedSource work right
  Cargo.lock
  Cargo.toml
Labels: release: performance

#5827 chore: disable jest sourcemap support
  packages/rspack/jest.config.js
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#5831 fix: let filename can receive null
  crates/rspack_binding_options/src/options/raw_devtool.rs
  packages/rspack/src/rspackOptionsApply.ts
Labels: release: bug fix

#5840 fix: should not generate minify plugin based on devtool
  packages/rspack-plugin-minify/src/index.js
  packages/rspack/tests/configCases/plugins/minify-with-devtool-false/index.js
  packages/rspack/tests/configCases/plugins/minify-with-devtool-false/lib.js
  packages/rspack/tests/configCases/plugins/minify-with-devtool-false/webpack.config.js
Labels: team, release: bug fix

#5843 chore: set pnpm store-dir to global store-dir + version
  .github/actions/pnpm-cache/action.yml
Labels: team

#5820 chore: remove unused local variables
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/MultiWatching.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/util/comparators.ts
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
Labels: team

#5846 feat: run ecosystem ci as merged into main
  .github/workflows/ci.yml
Labels: release: feature

#5848 fix: jest disable transform node_module
  packages/rspack/jest.config.js
Labels: team, release: bug fix

#5828 fix: cjs interop
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  packages/rspack/tests/cases/cjs-tree-shaking/cjs-interop/a.js
  packages/rspack/tests/cases/cjs-tree-shaking/cjs-interop/b.js
  packages/rspack/tests/cases/cjs-tree-shaking/cjs-interop/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/cjs-interop/package.json
  packages/rspack/tests/cases/cjs-tree-shaking/cjs-interop/webpack.config.js
Labels: team, release: bug fix

#5844 fix: require as expression
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack/tests/cases/warnings/require-as-expression/index.js
  packages/rspack/tests/cases/warnings/require-as-expression/warnings.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/index.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/index.js
  packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/index.js
Labels: team, release: bug fix

#5849 feat: support compilation.renameAsset
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/tests/configCases/asset/rename-asset/chunk.js
  packages/rspack/tests/configCases/asset/rename-asset/index.js
  packages/rspack/tests/configCases/asset/rename-asset/webpack.config.js
Labels: team, release: feature

#5850 fix: webpackMode eager for dynamic import
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack/tests/configCases/parsing/import-eager/index.js
  packages/rspack/tests/configCases/parsing/import-eager/two.js
  packages/rspack/tests/configCases/parsing/import-eager/webpack.config.js
  webpack-test/cases/scope-hoisting/issue-10308/test.filter.js
Labels: team, release: bug fix

#5832 fix: panic pass query to loader without resource with resource query
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/loader.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
  webpack-test/cases/loaders/query/index.js
  webpack-test/cases/loaders/query/test.filter.js
Labels: release: bug fix

#5854 chore: disable jest transform
  packages/rspack/jest.config.js
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
Labels: team

#5803 feat: side effects bailout out stats
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/tests/__snapshots__/Stats.test.js.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/statsCases/side-effects-bailouts/index.js
  packages/rspack/tests/statsCases/side-effects-bailouts/lib.js
  packages/rspack/tests/statsCases/side-effects-bailouts/webpack.config.js
Labels: team, release: feature

#5855 chore: disable webpack-test jest transform
  webpack-test/jest.config.js
Labels: team

#5491 fix(wasm): add fallback for MIME mismatch error in async wasm loading
  crates/rspack_plugin_wasm/src/runtime.rs
  diffcases/arco-pro/package.json
  package.json
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#5808 fix(rspack_loader_swc): enable SWC plugins
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack/package.json
  packages/rspack/tests/ConfigTestCases.template.js
  packages/rspack/tests/StatsTestCases.basictest.js
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/webpack.config.js
  packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/index.js
  pnpm-lock.yaml
Labels: release: bug fix

#5858 chore: x script support force build
  x.mjs
Labels: team

#5865 revert: "fix(rspack_loader_swc): enable SWC plugins"
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack/package.json
  packages/rspack/tests/ConfigTestCases.template.js
  packages/rspack/tests/StatsTestCases.basictest.js
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/index.js
  packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/index.js
  packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/webpack.config.js
  pnpm-lock.yaml
Labels: team

#5864 fix: 🐛 bailout stats location
  Cargo.lock
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/statsCases/side-effects-bailouts/lib.js
Labels: team, release: bug fix

#5837 fix: fix some "changes didn't emit a rebuild" issues
  crates/rspack_core/src/module_factory.rs
Labels: release: bug fix

#5880 chore: support test release build in CI and enable windows test in CI
  .github/workflows/ci.yml
Labels: team

#5881 chore: remove duplicate "uses"
  .github/workflows/ci.yml
Labels: team

#5876 fix: 🐛 should not mangle css module identifier
  crates/rspack_plugin_css/src/dependency/css_module_export.rs
Labels: team, release: bug fix

#5875 fix: export default alias
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/a.js
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/answer.js
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/app.js
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/index.js
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/lib.js
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/package.json
  packages/rspack/tests/configCases/tree-shaking/export-default-alias/webpack.config.js
Labels: team, release: bug fix

#5861 feat: support stage for processAssets
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_hook/src/async_series.rs
  crates/rspack_hook/src/lib.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/lite-tapable/index.ts
  packages/rspack/src/util/fake.ts
  packages/rspack/tests/configCases/hooks/stage-compilation/index.js
  packages/rspack/tests/configCases/hooks/stage-compilation/plugin.js
  packages/rspack/tests/configCases/hooks/stage-compilation/webpack.config.js
  packages/rspack/tests/configCases/hooks/stage-make/index.js
  packages/rspack/tests/configCases/hooks/stage-make/webpack.config.js
  packages/rspack/tests/configCases/hooks/stage-process-assets/index.js
  packages/rspack/tests/configCases/hooks/stage-process-assets/webpack.config.js
  packages/rspack/tests/configCases/plugins/internal-processAssets-stage/index.js
  packages/rspack/tests/configCases/plugins/internal-processAssets-stage/webpack.config.js
Labels: team, release: feature

#5884 refactor(core): move `Compilation::update_module_graph` to its own file
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
Labels: team

#5866 revert: "revert: "fix(rspack_loader_swc): enable SWC plugins""
  .github/workflows/reusable-build.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/scripts/build.js
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack/package.json
  packages/rspack/tests/ConfigTestCases.template.js
  packages/rspack/tests/StatsTestCases.basictest.js
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/webpack.config.js
  packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/index.js
  pnpm-lock.yaml
Labels: team

#5889 test: make sure import not run after it
  packages/rspack/tests/configCases/css/urls/index.js
Labels: team

#5886 refactor: move module_graph_module to module_graph folder
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph/module.rs
Labels: team

#5888 fix: export string name in harmony module
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  packages/rspack/tests/cases/esm/export-string-name/a.js
  packages/rspack/tests/cases/esm/export-string-name/index.js
Labels: team, release: bug fix

#5890 test: run async node library exports may cause error in ci
  packages/rspack/tests/configCases/split-chunks/chunks-function/webpack.config.js
Labels: team

#5891 refactor(core): add a `UpdateModuleGraph` struct with `cutout` and `repair` steps
  crates/rspack_core/src/compiler/make/mod.rs
Labels: team

#5896 fix: css loading runtime order
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap
  crates/rspack_plugin_html/tests/fixtures/variant/snapshot/output.snap
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/dynamic.css
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/dynamic.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/index.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/lib.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/test.config.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/webpack.config.js
  packages/rspack/tests/copyPlugin/build/main.js
Labels: team, release: bug fix

#5898 chore(testng): should not share runner between multiple compiler when run same file
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/multiple.ts
  packages/rspack-test-tools/src/runner/watch.ts
Labels: team

#5893 fix: context request position change error
  crates/rspack_core/src/context_module.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/hotCases/context/request-position/changed-file.js
  packages/rspack/tests/hotCases/context/request-position/file.js
  packages/rspack/tests/hotCases/context/request-position/index.js
  packages/rspack/tests/hotCases/context/request-position/lib/a.js
Labels: team, release: bug fix

#5899 fix: empty resource query and fragment
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/loader/rspack-issue-4297/fragmentloader.js
  packages/rspack/tests/configCases/loader/rspack-issue-4297/index.js
  packages/rspack/tests/configCases/loader/rspack-issue-4297/lib.js
  packages/rspack/tests/configCases/loader/rspack-issue-4297/queryloader.js
  packages/rspack/tests/configCases/loader/rspack-issue-4297/webpack.config.js
Labels: team, release: bug fix

#5892 refactor(core): move compiler/queue.rs to compiler/make/queue.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/queue.rs
  crates/rspack_core/src/compiler/mod.rs
Labels: team

#5901 fix: alias should have order
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/tests/configCases/resolve/alias-order/b.js
  packages/rspack/tests/configCases/resolve/alias-order/index.js
  packages/rspack/tests/configCases/resolve/alias-order/webpack.config.js
Labels: team, release: bug fix

#5829 feat: support `module.noParse`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack/tests/configCases/module/no-parse/foo.js
  packages/rspack/tests/configCases/module/no-parse/index.js
  packages/rspack/tests/configCases/module/no-parse/not-parsed-a.js
  packages/rspack/tests/configCases/module/no-parse/webpack.config.js
  webpack-test/configCases/no-parse/module.exports/test.filter.js
  webpack-test/configCases/no-parse/no-parse-function/test.filter.js
Labels: release: feature

#5914 feat: entrypoint.getRuntimeChunk
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Entrypoint.ts
  packages/rspack/tests/configCases/plugins/get-runtime-chunk/entry1.js
  packages/rspack/tests/configCases/plugins/get-runtime-chunk/entry2.js
  packages/rspack/tests/configCases/plugins/get-runtime-chunk/test.config.js
  packages/rspack/tests/configCases/plugins/get-runtime-chunk/webpack.config.js
Labels: team, release: feature

#5883 chore: bump oxc-resolver
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team

#5909 fix(typing): fix partial ts-expect-error in packages/rspack
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/node/NodeWatchFileSystem.ts
Labels: release: bug fix

#5922 refactor: migrate to hook macro
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/tests/main.rs
  crates/rspack_hook/Cargo.toml
  crates/rspack_hook/src/lib.rs
  crates/rspack_macros/Cargo.toml
  crates/rspack_macros/src/hook.rs
  crates/rspack_macros/src/lib.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_macros/src/source_map_config.rs
  crates/rspack_macros/tests/compiletest.rs
  crates/rspack_macros/tests/test.rs
  crates/rspack_macros/tests/ui/hook/unnamed_struct.rs
  crates/rspack_macros/tests/ui/hook/unnamed_struct.stderr
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  crates/rspack_plugin_worker/Cargo.toml
  crates/rspack_plugin_worker/src/lib.rs
  crates/rspack_testing/src/test_config.rs
Labels: team

#5900 refactor: support new tsfn (stage 2)
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_macros/src/macros.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_napi_shared/src/callback.rs
  crates/rspack_napi_shared/src/new_tsfn.rs
Labels: team

#5926 chore(core): bump oxc_resolver
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team

#5931 refactor: migrate nmf before resolve to new hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_hook/src/async_series_bail.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/src/lite-tapable/index.ts
Labels: team

#5932 refactor: support new tsfn (stage 3)
  .github/CODEOWNERS
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_macros/Cargo.toml
  crates/rspack_binding_macros/src/lib.rs
  crates/rspack_binding_macros/src/macros.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/source.rs
  crates/rspack_binding_values/src/utils.rs
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_fs_node/src/async.rs
  crates/rspack_fs_node/src/lib.rs
  crates/rspack_fs_node/src/node.rs
  crates/rspack_napi/Cargo.toml
  crates/rspack_napi/LICENSE
  crates/rspack_napi/src/callback.rs
  crates/rspack_napi/src/errors.rs
  crates/rspack_napi/src/ext/js_reg_exp_ext.rs
  crates/rspack_napi/src/ext/js_string_ext.rs
  crates/rspack_napi/src/ext/mod.rs
  crates/rspack_napi/src/js_values/js_reg_exp.rs
  crates/rspack_napi/src/js_values/mod.rs
  crates/rspack_napi/src/legacy_threadsafe_function.rs
  crates/rspack_napi/src/lib.rs
  crates/rspack_napi/src/threadsafe_function.rs
  crates/rspack_napi/src/utils.rs
  crates/rspack_napi_shared/LICENSE
  crates/rspack_napi_shared/src/lib.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team

#5936 fix: ci failed caused by unresolved conflict
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  packages/rspack/src/config/adapter.ts
Labels: team, release: bug fix

#5935 chore: fix lint-staged prettier
  lint-staged.config.mjs
  package.json
  packages/rspack-plugin-minify/src/index.js
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/lite-tapable/index.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/index.ts
  pnpm-lock.yaml
Labels: team

#5924 feat: support modify resource in after resolve hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/args.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/configCases/hooks/after-resolve-resource/a.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/b.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/c.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/duplicate.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/request.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/resource.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/test.config.js
  packages/rspack/tests/configCases/hooks/after-resolve-resource/webpack.config.js
Labels: need documentation, release: feature

#5934 refactor: support new tsfn (stage 4)
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/compiler.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/loader.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack/Cargo.toml
  crates/rspack/benches/main.rs
  crates/rspack_allocator/Cargo.toml
  crates/rspack_allocator/src/lib.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/source.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_binding_values/src/utils.rs
  crates/rspack_napi/src/callback.rs
  packages/rspack/src/Compiler.ts
Labels: team

#5937 chore: run tree shaking by new test runner
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/case/treeshaking.ts
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/processor/treeshaking.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack-test-tools/tests/TreeShaking.test.js
Labels: team

#5930 fix: module connection issuse
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/execute_module.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  pnpm-lock.yaml
Labels: release: bug fix

#5940 perf(node-binding): lock-free compiler
  crates/node_binding/src/lib.rs
Labels: team, release: performance

#5942 chore(testng): run compiler cases by new runner
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/processor/index.ts
  packages/rspack-test-tools/src/processor/simple.ts
  packages/rspack-test-tools/src/test/context.ts
  packages/rspack-test-tools/tests/Compiler.test.js
  packages/rspack-test-tools/tests/compilerCases/assets-empty.js
  packages/rspack-test-tools/tests/compilerCases/assets-exist.js
  packages/rspack-test-tools/tests/compilerCases/assets-not-exist.js
  packages/rspack-test-tools/tests/compilerCases/assets-update.js
  packages/rspack-test-tools/tests/compilerCases/assets.js
  packages/rspack-test-tools/tests/compilerCases/bubble-bail.js
  packages/rspack-test-tools/tests/compilerCases/compilation.js
  packages/rspack-test-tools/tests/compilerCases/error-stack-async.js
  packages/rspack-test-tools/tests/compilerCases/error-stack-sync.js
  packages/rspack-test-tools/tests/compilerCases/get-cache.js
  packages/rspack-test-tools/tests/compilerCases/hooks-after-optimize-modules.js
  packages/rspack-test-tools/tests/compilerCases/hooks-optimize-modules.js
  packages/rspack-test-tools/tests/compilerCases/named-chunk.js
  packages/rspack-test-tools/tests/compilerCases/single-file.js
  packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js
  pnpm-lock.yaml
Labels: team

#5941 fix: nmf before resolve bench regression
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_hook/src/async_series.rs
  crates/rspack_hook/src/async_series_bail.rs
  crates/rspack_hook/src/interceptor.rs
Labels: release: bug fix

#5945 perf(node-binding): reduce `JsCallback` lock contentions
  crates/rspack_napi/src/callback.rs
Labels: team, release: performance

#5946 chore: cleanup legacy threadsafe function
  crates/rspack_napi/src/legacy_threadsafe_function.rs
  crates/rspack_napi/src/lib.rs
Labels: team

#5944 refactor(core): set module_graph.* as private attribute
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/execute_module.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/rebuild_deps_builder.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/dependency_id.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph/vec_map.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_core/src/utils/import_var.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
Labels: team

#5947 chore(testng): run defaults cases by new runner
  packages/rspack-test-tools/src/case/defaults.ts
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/index.ts
  packages/rspack-test-tools/tests/Defaults.unittest.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache.js
  packages/rspack-test-tools/tests/defaultsCases/cache/non-root.js
  packages/rspack-test-tools/tests/defaultsCases/config/array-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js
  packages/rspack-test-tools/tests/defaultsCases/config/records-path.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/async-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/both-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/output-module.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/sync-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/filename/const.js
  packages/rspack-test-tools/tests/defaultsCases/filename/function.js
  packages/rspack-test-tools/tests/defaultsCases/library/library.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack-test-tools/tests/defaultsCases/mode/empty.js
  packages/rspack-test-tools/tests/defaultsCases/mode/none.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/multi-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/single-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/true-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/output/ecma-version.js
  packages/rspack-test-tools/tests/defaultsCases/output/unique-name.js
  packages/rspack-test-tools/tests/defaultsCases/stats/stats-false.js
  packages/rspack-test-tools/tests/defaultsCases/stats/stats-string.js
  packages/rspack-test-tools/tests/defaultsCases/stats/stats.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
  packages/rspack-test-tools/tests/defaultsCases/target_/node.js
  packages/rspack-test-tools/tests/defaultsCases/target_/webworker.js
Labels: team

#5939 refactor: support js loader plugin
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/plugins/js_loader_resolver.rs
  crates/rspack_binding_options/src/plugins/mod.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/JsLoaderRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team

#5952 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: team

#5950 refactor: staged should emit hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/lite-tapable/index.ts
Labels: team

#5953 fix: export star missing module panic
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  packages/rspack/tests/TestCases.template.js
  packages/rspack/tests/cases/esm/export-star-missing/errors.js
  packages/rspack/tests/cases/esm/export-star-missing/index.js
  packages/rspack/tests/cases/esm/export-star-missing/lib.js
Labels: team, release: bug fix

#5954 chore: remove unused Rust dependencies
  .taplo.toml
  Cargo.lock
  Cargo.toml
  crates/cargo-rst/Cargo.toml
  crates/node_binding/Cargo.toml
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
Labels: team

#5951 fix: overflow
  crates/rspack_core/src/utils/compile_boolean_matcher.rs
Labels: release: bug fix

#5958 fix: should call compile hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Watching.ts
  packages/rspack/tests/Compiler.test.js
  packages/rspack/tests/Stats.test.js
  packages/rspack/tests/configCases/hooks/interceptor/webpack.config.js
Labels: team, release: bug fix

#4968 feat(create-rspack): support cancel operation
  packages/create-rspack/index.js
Labels: release: feature

#5962 fix: plugin import camel case with number
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/swc_plugin_import/Cargo.toml
  crates/swc_plugin_import/src/lib.rs
  crates/swc_plugin_import/tests/member_case.rs
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/style-true/lib/with-number3d/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/style-true/lib/with-number3d/style/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/style-true.js
Labels: team, release: bug fix

#5963 chore: shorten SAFETY comments
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_napi/src/threadsafe_function.rs
Labels: team

#5977 refactor: runtime module hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_hook/src/async_series.rs
  crates/rspack_hook/src/lib.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team

#5979 fix: remove useless MutexModuleGraph
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: bug fix

#5980 refactor: build module hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/queue.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/util/normalization.ts
  packages/rspack/tests/configCases/compilation/rebuild-module/webpack.config.js
Labels: team

#5982 refactor: succeed module hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/queue.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team

#5983 refactor: chunk asset hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/Chunk.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team

#5984 fix(testng): use compiler.run
  packages/rspack-test-tools/tests/compilerCases/compilation.js
  packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js
  packages/rspack-test-tools/tests/statsAPICases/cache-disabled.js
  packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
Labels: team, release: bug fix

#5988 chore: remove rspack-html-plugin & rspack-plugin-node-polyfill
  diffcases/arco-pro/package.json
  diffcases/arco-pro/rspack.config.js
  packages/rspack-plugin-html/CHANGELOG.md
  packages/rspack-plugin-html/LICENSE
  packages/rspack-plugin-html/README.md
  packages/rspack-plugin-html/default_index.ejs
  packages/rspack-plugin-html/index.cjs
  packages/rspack-plugin-html/package.json
  packages/rspack-plugin-html/src/chunkSorter.ts
  packages/rspack-plugin-html/src/hooks.ts
  packages/rspack-plugin-html/src/html-tags.ts
  packages/rspack-plugin-html/src/index.ts
  packages/rspack-plugin-html/src/template.ts
  packages/rspack-plugin-html/tests/basic.spec.js
  packages/rspack-plugin-html/tests/fixtures/async.js
  packages/rspack-plugin-html/tests/fixtures/common.js
  packages/rspack-plugin-html/tests/fixtures/empty_html.html
  packages/rspack-plugin-html/tests/fixtures/favicon.ico
  packages/rspack-plugin-html/tests/fixtures/index.js
  packages/rspack-plugin-html/tests/fixtures/interpolation.html
  packages/rspack-plugin-html/tests/fixtures/invalid.html
  packages/rspack-plugin-html/tests/fixtures/issue2179.html
  packages/rspack-plugin-html/tests/fixtures/logo.html
  packages/rspack-plugin-html/tests/fixtures/logo.png
  packages/rspack-plugin-html/tests/fixtures/main.css
  packages/rspack-plugin-html/tests/fixtures/plain.html
  packages/rspack-plugin-html/tests/fixtures/spaced_plain.html
  packages/rspack-plugin-html/tests/fixtures/src/index.ejs
  packages/rspack-plugin-html/tests/fixtures/template.pug
  packages/rspack-plugin-html/tests/fixtures/templateParam.js
  packages/rspack-plugin-html/tests/fixtures/test.html
  packages/rspack-plugin-html/tests/fixtures/theme.js
  packages/rspack-plugin-html/tests/fixtures/util.js
  packages/rspack-plugin-html/tests/fixtures/webpackconfig.html
  packages/rspack-plugin-html/tsconfig.build.json
  packages/rspack-plugin-html/tsconfig.json
  packages/rspack-plugin-node-polyfill/CHANGELOG.md
  packages/rspack-plugin-node-polyfill/LICENSE
  packages/rspack-plugin-node-polyfill/README.md
  packages/rspack-plugin-node-polyfill/package.json
  packages/rspack-plugin-node-polyfill/src/index.js
  packages/rspack/package.json
  packages/rspack/tests/configCases/plugins/polyfill/index.js
  packages/rspack/tests/configCases/plugins/polyfill/webpack.config.js
  packages/rspack/tests/hashCases/provided-dependency-order/webpack.config.js
  pnpm-lock.yaml
  webpack-test/package.json
Labels: team

#5996 fix: cached source with raw source
  Cargo.lock
  Cargo.toml
Labels: release: bug fix

#5545 fix(rspack_plugin_html): align rspack_plugin_html inject option behavior with html-webpack-plugin
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/tests/fixtures/inject/index.css
  crates/rspack_plugin_html/tests/fixtures/inject/index.html
  crates/rspack_plugin_html/tests/fixtures/inject/index.js
  crates/rspack_plugin_html/tests/fixtures/inject/snapshot/output.snap
  crates/rspack_plugin_html/tests/fixtures/inject/test.config.json
Labels: release: bug fix

#5995 refactor: after process assets and asset emitted hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_hook/src/async_parallel.rs
  crates/rspack_hook/src/lib.rs
  crates/rspack_hook/src/sync_bail.rs
  crates/rspack_hook/src/util.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team

#6005 perf: cleanup atomics
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_tracing/src/lib.rs
Labels: team, release: performance

#6006 docs: use Open Sans as the default font
  website/package.json
  website/pnpm-lock.yaml
  website/rspress.config.ts
Labels: team

#5997 refactor: emit and after emit hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compiler.ts
Labels: team

#6010 fix: duplicate library plugin
  packages/rspack/src/builtin-plugin/EnableLibraryPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/sharing/ShareRuntimePlugin.ts
  packages/rspack/tests/configCases/library/duplicate-module-library/index.js
  packages/rspack/tests/configCases/library/duplicate-module-library/test.config.js
  packages/rspack/tests/configCases/library/duplicate-module-library/webpack.config.js
Labels: team, release: bug fix

#5998 refactor: optimize modules and after optimize modules hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team

#6014 chore: update rolldown credits
  README.md
  README.zh-CN.md
Labels: team

#6015 doc: add swc plugin usage
  website/docs/en/guide/builtin-swc-loader.mdx
  website/docs/zh/guide/builtin-swc-loader.mdx
Labels: team

#6012 fix: missing define_variable for export declarations
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/harmony.js
  packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/index.js
  packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/mod.js
  packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/webpack.config.js
Labels: release: bug fix

#5992 fix: rsbuild scss module mangle
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  packages/rspack/tests/configCases/mangle-exports/skipping-mangle-css-modules/index.js
  packages/rspack/tests/configCases/mangle-exports/skipping-mangle-css-modules/index.module.css
  packages/rspack/tests/configCases/mangle-exports/skipping-mangle-css-modules/lib.js
  packages/rspack/tests/configCases/mangle-exports/skipping-mangle-css-modules/package.json
  packages/rspack/tests/configCases/mangle-exports/skipping-mangle-css-modules/webpack.config.js
Labels: team, release: bug fix

#6003 refactor: optimize tree and optimize chunk modules hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team

#6016 fix: Move @import to top of concatenated CSS output (#6000)
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/expected/main.css
  crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/snapshot/output.snap
  packages/rspack/tests/__snapshots__/ConfigTestCases.basictest.js.snap
  packages/rspack/tests/configCases/css/at-import-in-the-top/a.css
  packages/rspack/tests/configCases/css/at-import-in-the-top/b.css
  packages/rspack/tests/configCases/css/at-import-in-the-top/c.css
  packages/rspack/tests/configCases/css/at-import-in-the-top/index.js
  packages/rspack/tests/configCases/css/at-import-in-the-top/webpack.config.js
Labels: release: bug fix

#6018 fix: should generate correct context request with query
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/cases/context/resource-query-prefix/index.js
  packages/rspack/tests/cases/context/resource-query-prefix/sub/a.js
  packages/rspack/tests/cases/context/resource-query-prefix/sub/abc.js
  webpack-test/cases/parsing/issue-7778/test.filter.js
Labels: team, release: bug fix

#6019 feat: support webpackChunkName comment for worker
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack/tests/configCases/worker/worker-webpack-chunk-name/a.js
  packages/rspack/tests/configCases/worker/worker-webpack-chunk-name/index.js
  packages/rspack/tests/configCases/worker/worker-webpack-chunk-name/webpack.config.js
Labels: team, release: feature

#6023 refactor: normal module factory after resolve hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_hook/src/async_series_bail.rs
  crates/rspack_hook/src/lib.rs
  packages/playground/cases/hooks/asset-emitted/index.test.ts
  packages/playground/cases/hooks/asset-emitted/rspack.config.js
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-dev-server/src/middleware.ts
  packages/rspack-plugin-minify/src/index.js
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/processor/treeshaking.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/MultiStats.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/browserslistTargetHandler.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/src/lite-tapable/index.ts
  packages/rspack/src/node/nodeConsole.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/bindingVersionCheck.ts
  packages/rspack/src/util/cleverMerge.js
  packages/rspack/src/util/createSource.ts
  packages/rspack/src/util/identifier.js
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/smartGrouping.ts
Labels: team

#6026 fix: assets filename maybe not match a chunk
  crates/rspack_plugin_devtool/src/lib.rs
Labels: release: bug fix

#6029 feat: enable incremental_rebuild when use new treeshaking
  crates/rspack_binding_options/src/options/mod.rs
  packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/changed-file.js
  packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/file.js
  packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/index.js
  packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/reexport.js
  packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/webpack.config.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/a/index.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/b/index.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/changed-file.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/file.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/main/async.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/main/index.js
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/webpack.config.js
Labels: team, release: feature

#6030 docs: update some rspack legacy descriptions
  website/components/CompatibleCard.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/guide/glossary.mdx
  website/docs/zh/config/stats.mdx
  website/docs/zh/guide/glossary.mdx
  website/docs/zh/guide/language-support.mdx
Labels: team

#6027 refactor: context module factory before resolve hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ContextModuleFactory.ts
Labels: team

#6032 docs: add ignoreWarnings option
  website/docs/en/config/other-options.mdx
  website/docs/zh/config/other-options.mdx
Labels: team

#6034 fix: `Compiler` and `Compilation` in `LoaderContext` of a childCompiler should be updated
  packages/rspack-test-tools/tests/compilerCases/child-compiler.js
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/JsLoaderRspackPlugin.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/fixtures/callback-loader.js
Labels: team, release: bug fix

#6037 fix: disable import stmt opt in old tree shaking
  crates/rspack/tests/tree-shaking/array-side-effects/snapshot/output.snap
  crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/output.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/output.snap
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
Labels: team, release: bug fix

#6038 refactor: cmf after resolve hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_hook/src/async_series_bail.rs
  crates/rspack_hook/src/lib.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ContextModuleFactory.ts
Labels: team

#6043 docs: integrate Rsbuild plugins for website
  website/package.json
  website/pnpm-lock.yaml
  website/rspress.config.ts
Labels: team

#6044 docs: remove deprecated html and node-polyfill plugin
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/config/builtins.mdx
  website/docs/en/config/plugins.mdx
  website/docs/en/guide/language-support.mdx
  website/docs/en/misc/branding.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/language-support.mdx
  website/docs/zh/misc/branding.mdx
Labels: team

#6045 chore(workflow): update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: team

#6039 fix: do not concatenate css module
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack/tests/configCases/concatenate-modules/with-css/index.js
  packages/rspack/tests/configCases/concatenate-modules/with-css/webpack.config.js
Labels: release: bug fix

#6050 chore: add rspack-compat
  README.md
  README.zh-CN.md
  website/rspress.config.ts
Labels: team

#6046 chore: remove integrate cases
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/snapshot-resolver.js
  packages/rspack-test-tools/src/case/diff.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack-test-tools/tests/__snapshots__/Stats.test.js.snap
  packages/rspack/tests/Compiler.test.js
  packages/rspack/tests/Defaults.unittest.js
  packages/rspack/tests/Stats.test.js
Labels: team

#6047 refactor: nmf create module hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_hook/src/async_series_bail.rs
  crates/rspack_hook/src/lib.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/tests/configCases/hooks/create-module/index.js
  packages/rspack/tests/configCases/hooks/create-module/webpack.config.js
Labels: team

#6053 docs: add rsfamily-design-resources
  README.md
  README.zh-CN.md
  scripts/alert/discord.js
  website/docs/en/misc/branding.mdx
  website/docs/en/misc/license.md
  website/docs/zh/misc/branding.mdx
  website/docs/zh/misc/license.md
  website/rspress.config.ts
Labels: team

#6055 refactor: nmf resolve for scheme hook
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_schemes/src/file_uri.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/src/lite-tapable/index.ts
Labels: team

#6058 feat: export MultiStats class
  packages/rspack/src/exports.ts
Labels: team, release: feature

#6009 chore: update swc
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/utils/concatenated_module_visitor.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, breaking change, release: breaking change

#6028 feat(rspack): NormalModuleReplacementPlugin
  packages/rspack/src/exports.ts
  packages/rspack/src/lib/NormalModuleReplacementPlugin.ts
  packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/index.js
  packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/request.v1.js
  packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/request.v2.js
  packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/resource.bar.js
  packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/resource.foo.js
  packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/webpack.config.js
Labels: release: feature

#6066 chore: remove `compiler.build` and `compiler.rebuild`
  packages/rspack-dev-server/src/server.ts
  packages/rspack-test-tools/tests/statsAPICases/cache-disabled.js
  packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js
  packages/rspack/src/Compiler.ts
Labels: team, breaking change, release: breaking change
