Repository web-infra-dev/rspack, pull requests merged in 2024-04, with the labels that each got.

#6067 fix: emit asset file with buffer can use in asset emitted hook correctly
  crates/rspack_binding_values/src/source.rs
  packages/rspack/tests/configCases/hooks/asset-emitted-buffer/index.js
  packages/rspack/tests/configCases/hooks/asset-emitted-buffer/webpack.config.js
Labels: team, release: bug fix

#6079 chore: cargo build reuse cache
  .github/actions/docker-build/action.yml
  .github/workflows/reusable-build.yml
Labels: team

#6069 feat: support entry.dependOn
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/execute_module.rs
  crates/rspack_core/src/utils/runtime.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/lib/EntryOptionPlugin.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/diagnostics/factorize/entry-runtime-error/stats.err
  webpack-test/configCases/entry/depend-on-advanced/test.filter.js
  webpack-test/configCases/entry/depend-on-bug/test.filter.js
  webpack-test/configCases/entry/depend-on-non-js/test.filter.js
  webpack-test/configCases/entry/depend-on-simple/test.filter.js
  webpack-test/configCases/entry/issue-12562/test.filter.js
  webpack-test/configCases/errors/depend-on-and-runtime/test.filter.js
  webpack-test/configCases/errors/depend-on-error/test.filter.js
  webpack-test/configCases/runtime/entries-in-runtime/test.filter.js
  webpack-test/configCases/split-chunks/move-to-entrypoint/test.filter.js
Labels: team, release: feature

#6081 fix: handle error of `cacheGroup.name()`
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack/tests/configCases/split-chunks/cache-group-name-function-with-error/errors.js
  packages/rspack/tests/configCases/split-chunks/cache-group-name-function-with-error/index.js
  packages/rspack/tests/configCases/split-chunks/cache-group-name-function-with-error/webpack.config.js
Labels: team, release: bug fix

#6092 fix: ci typo error
  .typos.toml
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#6090 feat: support compilation.hooks.afterSeal
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/configCases/hooks/after-seal/index.js
  packages/rspack/tests/configCases/hooks/after-seal/webpack.config.js
Labels: team, release: feature

#6096 chore(workflow): integrate cspell-ban-words
  website/cspell.config.cjs
  website/cspell.json
  website/docs/en/api/node-api.mdx
  website/docs/en/blog/announcing-0.5.mdx
  website/docs/en/config/dev-server.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/optimization-split-chunks.mdx
  website/docs/en/config/plugins.mdx
  website/docs/zh/blog/announcing-0.5.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/optimization-split-chunks.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/builtin-swc-loader.mdx
  website/package.json
  website/pnpm-lock.yaml
  website/project-words.txt
Labels: team

#6095 chore: add warning notice about @rspack/test-tools
  packages/rspack-test-tools/README.md
Labels: team

#6098 chore: remove change logs because they are outdated and not useful
  benchcases/react-refresh/CHANGELOG.md
  crates/node_binding/CHANGELOG.md
  crates/rspack_fs_node/CHANGELOG.md
  npm/darwin-arm64/CHANGELOG.md
  npm/darwin-x64/CHANGELOG.md
  npm/linux-x64-gnu/CHANGELOG.md
  npm/win32-x64-msvc/CHANGELOG.md
  packages/create-rspack/CHANGELOG.md
  packages/playground/CHANGELOG.md
  packages/rspack-cli/CHANGELOG.md
  packages/rspack-dev-server/CHANGELOG.md
  packages/rspack-plugin-minify/CHANGELOG.md
  packages/rspack-plugin-react-refresh/CHANGELOG.md
  packages/rspack-test-tools/CHANGELOG.md
  packages/rspack/CHANGELOG.md
  webpack-test/CHANGELOG.md
Labels: team

#6071 perf: use mimalloc for musl target
  crates/rspack_allocator/Cargo.toml
  crates/rspack_allocator/src/lib.rs
Labels: release: performance

#6099 chore: remove unused dependencies from crates/rspack
  Cargo.lock
  crates/rspack/Cargo.toml
Labels: team

#6100 refactor: remove rspackFuture.disableApplyEntryLazily
  packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team

#6104 chore: release all platform for canary release
  .github/workflows/release-canary.yml
Labels: team

#6107 feat: support css default export and named export at same time
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  packages/rspack/src/config/normalization.ts
  webpack-test/configCases/css/default-exports-parser-options/index.js
  webpack-test/configCases/css/default-exports-parser-options/style.module.css
  webpack-test/configCases/css/default-exports-parser-options/webpack.config.js
  webpack-test/configCases/css/named-exports-parser-options/index.js
  website/docs/en/config/experiments.mdx
  website/docs/en/config/module.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/module.mdx
  website/project-words.txt
Labels: team, release: feature

#6108 chore: git attributes snap
  .gitattributes
Labels: team

#6097 fix: should add use-credentials into css-loading runtime correctly
  crates/rspack_plugin_css/src/runtime/css_loading.js
  crates/rspack_plugin_css/src/runtime/mod.rs
  crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap
  crates/rspack_plugin_html/tests/fixtures/variant/snapshot/output.snap
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/src/async.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/webpack.config.js
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/css/css-cross-origin-loading-use-credentials/chunk.css
  packages/rspack/tests/configCases/css/css-cross-origin-loading-use-credentials/index.js
  packages/rspack/tests/configCases/css/css-cross-origin-loading-use-credentials/webpack.config.js
  packages/rspack/tests/configCases/css/css-cross-origin-loading/chunk.css
  packages/rspack/tests/configCases/css/css-cross-origin-loading/index.js
  packages/rspack/tests/configCases/css/css-cross-origin-loading/webpack.config.js
Labels: team, release: bug fix

#6070 feat(swc_plugin_import): legacy kebab/snake case for legacy babel-plugin-import compatibility
  crates/swc_plugin_import/src/legacy_case.rs
  crates/swc_plugin_import/src/lib.rs
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/legacy-babel-plugin-import.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/legacy-babel-plugin-import/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/legacy-babel-plugin-import/lib/x-i-p-object/x_i_p_object.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/webpack.config.js
  website/docs/en/guide/builtin-swc-loader.mdx
  website/docs/zh/guide/builtin-swc-loader.mdx
Labels: release: feature

#6085 perf(core): Use unicase for compare_ids
  Cargo.lock
  Cargo.toml
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/comparators.rs
Labels: release: performance

#6110 fix: 🐛 add concatenation bailout reason
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: release: bug fix

#6122 chore: fix diff case
  diffcases/arco-pro/rspack.config.js
Labels: team

#6120 chore: migrate plugin wasm cases
  crates/rspack_plugin_json/tests/fixtures.rs
  crates/rspack_plugin_json/tests/fixtures/simple/expected/main.js
  crates/rspack_plugin_wasm/tests/fixtures.rs
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/test.config.json
  crates/rspack_plugin_wasm/tests/fixtures/v128/expected/main.js
  crates/rspack_plugin_wasm/tests/fixtures/v128/test.config.json
  packages/rspack-test-tools/src/processor/builtin.ts
  packages/rspack-test-tools/tests/builtinCases/plugin-json/simple/index.js
  packages/rspack-test-tools/tests/builtinCases/plugin-json/simple/json.json
  packages/rspack-test-tools/tests/builtinCases/plugin-json/simple/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-json/simple/string.json
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/index.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/module.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/module2.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/test.config.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/wasm.wasm
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/v128/index.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/v128/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/v128/test.config.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/v128/v128.wasm
Labels: team

#5072 feat: mini-css-extract-plugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_css_extract.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_extract_css/LICENSE
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_extract_css/src/lib.rs
  crates/rspack_plugin_extract_css/src/parser_and_generator.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_extract_css/src/runtime.rs
  crates/rspack_plugin_extract_css/src/runtime/css_load.js
  crates/rspack_plugin_extract_css/src/runtime/with_hmr.js
  crates/rspack_plugin_extract_css/src/runtime/with_loading.js
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack/src/ExecuteModulePlugin.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.js
  packages/rspack/src/builtin-plugin/css-extract/hmr/normalize-url.js
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader-options.json
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/css-extract/plugin-options.json
  packages/rspack/src/builtin-plugin/css-extract/utils.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/exports.ts
  packages/rspack/tsconfig.json
Labels: team, release: feature

#6126 docs: use Rspress official plugin for RSS supports
  website/docs/en/index.md
  website/docs/zh/index.md
  website/package.json
  website/pnpm-lock.yaml
  website/rspress.config.ts
  website/rspress/plugin-rss/FeedsAnnotations.tsx
  website/rspress/plugin-rss/index.ts
  website/rspress/plugin-rss/plugin-rss.ts
  website/rspress/plugin-rss/type.ts
  website/rspress/plugin-rss/utils.ts
Labels: team

#6121 chore: remove rspack testing dependency
  .github/CODEOWNERS
  .vscode/settings.json
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/benches/main.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_json/Cargo.toml
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/LICENSE
  crates/rspack_testing/bin/gen_test_config_schema.rs
  crates/rspack_testing/examples/build-cli.rs
  crates/rspack_testing/examples/simple/c.js
  crates/rspack_testing/examples/simple/changed/index.js
  crates/rspack_testing/examples/simple/created/a.js
  crates/rspack_testing/examples/simple/d.js
  crates/rspack_testing/examples/simple/expected/main.hot-update.js
  crates/rspack_testing/examples/simple/expected/main.hot-update.json
  crates/rspack_testing/examples/simple/expected/main.js
  crates/rspack_testing/examples/simple/index.js
  crates/rspack_testing/examples/simple/removed/c.js
  crates/rspack_testing/examples/simple/test.config.json
  crates/rspack_testing/examples/test-cli.rs
  crates/rspack_testing/examples/test-hmr-cli.rs
  crates/rspack_testing/src/eval_raw.rs
  crates/rspack_testing/src/lib.rs
  crates/rspack_testing/src/loader.rs
  crates/rspack_testing/src/run_fixture.rs
  crates/rspack_testing/src/test_config.rs
  crates/rspack_testing/test.config.scheme.json
  scripts/bench/make-threejs10x-production-config.js
  scripts/bench/make-threejs10x.js
Labels: team

#6109 feat: support dependOn in chunk split
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  packages/rspack/src/Module.ts
  webpack-test/configCases/entry/depend-on-simple/node_modules/prop-types.js
  webpack-test/configCases/entry/depend-on-simple/node_modules/react-dom.js
  webpack-test/configCases/entry/depend-on-simple/node_modules/react.js
  webpack-test/configCases/entry/depend-on-simple/test.filter.js
Labels: release: feature

#6131 chore: run format
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/index.ts
Labels: team

#6135 fix: merge with global parser generator options
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/merge.rs
  diffcases/arco-pro/rspack.config.js
  packages/rspack/tests/configCases/module/merge-global-generator/index.js
  packages/rspack/tests/configCases/module/merge-global-generator/index.module.css
  packages/rspack/tests/configCases/module/merge-global-generator/webpack.config.js
Labels: team, release: bug fix

#6134 fix: 🐛 use set queue instead of `VecDeq`
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
Labels: team, release: bug fix

#6132 refactor: js plugin hooks
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack/Cargo.toml
  crates/rspack/LICENSE
  crates/rspack/src/lib.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/drive.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_web_worker_template/src/lib.rs
  crates/rspack_util/src/fx_hash.rs
  crates/rspack_util/src/lib.rs
  packages/rspack/src/builtin-plugin/APIPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/configCases/output-module/only-non-webpack-require/index.js
  packages/rspack/tests/configCases/output-module/only-non-webpack-require/webpack.config.js
  webpack-test/configCases/output-module/non-webpack-require/baz.js
  webpack-test/configCases/output-module/non-webpack-require/index.js
  webpack-test/configCases/output-module/non-webpack-require/mod.js
  webpack-test/configCases/output-module/non-webpack-require/test.filter.js
  webpack-test/configCases/output-module/non-webpack-require/webpack.config.js
Labels: team

#6139 fix: nested `unknown || truthy = unknown truthy` eval logical or
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  packages/rspack/tests/cases/parsing/evaluate-logical/index.js
Labels: team, release: bug fix

#6140 chore: move hot next function from runner to runner factory
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/src/runner/runner/hot.ts
Labels: team

#6136 perf: ⚡️ reduce alloc in ModuleGraphAccessor impl
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
Labels: team, release: performance

#6142 perf: module group get_key
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: release: performance

#6143 chore(rust/dep): update `sugar_path` to 1.2.0
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/context.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_util/src/identifier.rs
Labels: team

#6146 chore: use `cargo-shear` to remove unused dependencies
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_split_chunks/Cargo.toml
Labels: team

#6150 chore: remove workflows/need-doc.yml which is not needed anymore
  .github/workflows/need-doc.yml
Labels: team

#6112 fix: `Rule.enforce` should be applied to `use` of function type
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/tests/configCases/loader/rspack-issue-6068/a.js
  packages/rspack/tests/configCases/loader/rspack-issue-6068/index.js
  packages/rspack/tests/configCases/loader/rspack-issue-6068/loader1.js
  packages/rspack/tests/configCases/loader/rspack-issue-6068/loader2.js
  packages/rspack/tests/configCases/loader/rspack-issue-6068/loader3.js
  packages/rspack/tests/configCases/loader/rspack-issue-6068/webpack.config.js
Labels: team, release: bug fix

#6153 perf: integrate chunks
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
Labels: release: performance

#6145 chore: 🤖 enable new tree shaking by default
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-dev-server/src/middleware.ts
  packages/rspack-plugin-minify/src/index.js
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/processor/treeshaking.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/provide/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/swc-loader/ts/snapshot/output.snap.txt
  packages/rspack/src/MultiStats.ts
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/browserslistTargetHandler.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/src/lite-tapable/index.ts
  packages/rspack/src/node/nodeConsole.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/bindingVersionCheck.ts
  packages/rspack/src/util/cleverMerge.js
  packages/rspack/src/util/createSource.ts
  packages/rspack/src/util/identifier.js
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/smartGrouping.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/copyPlugin/build/main.js
  packages/rspack/tests/diagnostics/factorize/export_star_error/webpack.config.js
  webpack-test/hotCases/conditional-runtime/accept-conditional/test.filter.js
Labels: team

#6149 chore: regenerate pnpm-lock.yaml
  package.json
  packages/rspack/package.json
  pnpm-lock.yaml
  webpack-test/package.json
Labels: team

#6147 docs: cssExtract docs
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/config/plugins.mdx
  website/docs/en/guide/migrate-from-webpack.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/migrate-from-webpack.mdx
Labels: team

#6158 docs: enable new tree shaking by default
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team

#6159 docs(website): enable oxlint
  .eslintignore
  website/components/RspackCompatible.tsx
  website/components/property-type.tsx
  website/components/webpack-license.tsx
  website/theme/components/HomeFooter/index.tsx
Labels: team

#6156 fix: wrong asset info after updateAsset
  packages/rspack/src/Compilation.ts
  packages/rspack/tests/configCases/hooks/update-asset/index.js
  packages/rspack/tests/configCases/hooks/update-asset/test.config.js
  packages/rspack/tests/configCases/hooks/update-asset/webpack.config.js
Labels: team, release: bug fix

#6151 feat: support stats of prefetch and preload
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/statsCases/prefetch-preload-mixed/a.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/a1.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/a2.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/b.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/b1.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/b2.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/b3.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/c.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/c1.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/c2.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/index.js
  packages/rspack/tests/statsCases/prefetch-preload-mixed/webpack.config.js
Labels: team, release: feature

#6169 chore: use workspace rspack version in create-rspack template
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/create-rspack/template-vanilla/package.json
  packages/create-rspack/template-vue/package.json
  pnpm-lock.yaml
Labels: team

#6170 fix(ci): compilation file prettier error
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#6173 docs: ✏️ tree shaking
  website/docs/en/blog/announcing-0.6.mdx
  website/docs/zh/blog/announcing-0.6.mdx
Labels: team

#6174 docs(website): remove contributors list from home page
  website/theme/components/Contributors.tsx
  website/theme/pages/index.tsx
Labels: team

#6180 chore: lock corepack
  .github/actions/docker-build/action.yml
Labels: team

#6179 docs(webiste): change the hiring link in announcement to /misc/join-us
  website/theme/components/Announcement/index.tsx
Labels: team

#6181 chore: use prettier3 to format code
  package.json
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-dev-server/src/middleware.ts
  packages/rspack-plugin-minify/src/index.js
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/MultiStats.ts
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/browserslistTargetHandler.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/src/lite-tapable/index.ts
  packages/rspack/src/node/nodeConsole.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/bindingVersionCheck.ts
  packages/rspack/src/util/cleverMerge.js
  packages/rspack/src/util/createSource.ts
  packages/rspack/src/util/identifier.js
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/smartGrouping.ts
  packages/rspack/tests/cssExtract/manual/src/index.js
Labels: team

#6188 chore: update rspack-sources
  Cargo.lock
  Cargo.toml
Labels: team

#6191 ci: doc workflow check skipable
  .github/workflows/ci.yml
Labels: team

#6167 perf: bitwise operation in code splitter
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: release: performance

#6198 fix: should parse patterns in class
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack/tests/cases/parsing/rspack-issue-6164/index.js
  packages/rspack/tests/configCases/module-variables/global-true/index.js
Labels: team, release: bug fix

#6195 ci: fix doc reuseable workflow
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#6166 feat: support Internal IgnorePlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_ignore.rs
  crates/rspack_plugin_ignore/Cargo.toml
  crates/rspack_plugin_ignore/src/lib.rs
  packages/rspack/src/builtin-plugin/IgnorePlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  packages/rspack/tests/configCases/builtins/ignore-plugin/index.js
  packages/rspack/tests/configCases/builtins/ignore-plugin/test-ignore/a.js
  packages/rspack/tests/configCases/builtins/ignore-plugin/test-ignore/b.js
  packages/rspack/tests/configCases/builtins/ignore-plugin/test-ignore/c.js
  packages/rspack/tests/configCases/builtins/ignore-plugin/test-ignore/d.js
  packages/rspack/tests/configCases/builtins/ignore-plugin/webpack.config.js
  webpack-test/configCases/errors/multi-entry-missing-module/test.filter.js
  webpack-test/configCases/ignore/checkContext/test.filter.js
  webpack-test/configCases/ignore/multiple-with-externals/test.filter.js
  webpack-test/configCases/ignore/only-resource-context/test.filter.js
  webpack-test/configCases/ignore/only-resource/test.filter.js
  webpack-test/configCases/ignore/resource-and-context-contextmodule/test.filter.js
  webpack-test/configCases/ignore/resource-and-context/test.filter.js
Labels: team, release: feature

#6200 fix: favicon path of HtmlRspackPlugin
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/visitors/asset.rs
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-publicpath/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-publicpath/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-publicpath/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-subdir-publicpath/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-subdir-publicpath/static/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-subdir-publicpath/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-subdir/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-subdir/static/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-absolute-subdir/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-absolute/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-absolute/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative-publicpath/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-relative-publicpath/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative-publicpath/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative-subdir-publicpath/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative-subdir-publicpath/static/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-relative-subdir-publicpath/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative-subdir/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative-subdir/static/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-relative-subdir/webpack.config.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative/favicon.ico
  packages/rspack/tests/configCases/builtins/html-favicon-relative/index.js
  packages/rspack/tests/configCases/builtins/html-favicon-relative/webpack.config.js
Labels: team, release: bug fix

#6205 refactor: remove old hook trait
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/plugins/js_loader_resolver.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/execute_module.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/loader/rspack_loader.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/plugin/context.rs
  crates/rspack_core/src/plugin/mod.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_hook/src/async_parallel.rs
  crates/rspack_hook/src/async_series.rs
  crates/rspack_hook/src/async_series_bail.rs
  crates/rspack_hook/src/interceptor.rs
  crates/rspack_hook/src/lib.rs
  crates/rspack_hook/src/sync_series.rs
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_ignore/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_schemes/src/file_uri.rs
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  crates/rspack_plugin_worker/src/lib.rs
Labels: team

#6204 docs: modify treeshaking sideEffects docs and remove removeAvaModules config
  website/docs/en/config/optimization.mdx
  website/docs/en/guide/tree-shaking.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/guide/tree-shaking.mdx
Labels: team

#6203 perf: use set as queue for flag_dependency_usage_plugin
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/utils/queue.rs
Labels: team, release: performance

#6199 perf: remove bad par_iter
  crates/rspack_plugin_split_chunks/src/plugin/chunk.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
Labels: release: performance

#6207 docs: add re-exports optimization diagram
  website/docs/en/guide/tree-shaking.mdx
  website/docs/zh/guide/tree-shaking.mdx
Labels: team

#6176 fix(mf-1): conflict module map in multi container
  crates/rspack_plugin_mf/src/container/container_entry_dependency.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module_factory.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/expose_runtime_module.rs
  packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/a.js
  packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/b.js
  packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/bootstrap.js
  packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/index.js
  packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/test.config.js
  packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/webpack.config.js
Labels: team, release: bug fix

#5500 fix: align alias with webpack
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
Labels: release: bug fix

#6216 feat: support function filename and chunkFilename
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_css_extract.rs
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_extract_css/src/runtime.rs
  packages/rspack/tests/cssExtract/cases/filename-as-function/test.filter.js
Labels: team, release: feature

#6202 refactor: module executor independent of the build process
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/execute_module.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/queue.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor.rs
  crates/rspack_core/src/dependency/loader_import_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/bar.js
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/bar.js.macro
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/entry.js
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/index.js
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/index.js.macro
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/loader.js
  packages/rspack/tests/configCases/loader-import-module/recursive-import-module/webpack.config.js
Labels: team

#5492 fix: builtin swc loader input sourcemap
  crates/rspack_loader_swc/src/lib.rs
  packages/rspack/package.json
  packages/rspack/tests/configCases/source-map/source-map-loader/a.js
  packages/rspack/tests/configCases/source-map/source-map-loader/a.js.map
  packages/rspack/tests/configCases/source-map/source-map-loader/index.js
  packages/rspack/tests/configCases/source-map/source-map-loader/webpack.config.js
  pnpm-lock.yaml
Labels: release: bug fix

#6210 fix: correct active state when side effects is disabled
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/module_graph/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  packages/rspack-test-tools/tests/builtinCases/samples/concatenate-modules/snapshot/output.snap.txt
  packages/rspack/tests/configCases/tree-shaking/side-effects-disabled-active/index.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-disabled-active/side-effect.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-disabled-active/tracker.js
  packages/rspack/tests/configCases/tree-shaking/side-effects-disabled-active/webpack.config.js
Labels: team, release: bug fix

#6220 docs: add IgnorePlugin introduction
  website/components/CompatibleCard.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/plugins/webpack/ignore-plugin.mdx
  website/docs/zh/plugins/webpack/ignore-plugin.mdx
  website/rspress.config.ts
Labels: team

#6223 feat: support css module :export
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  packages/rspack/tests/configCases/css/export-selector/imported.js
  packages/rspack/tests/configCases/css/export-selector/index.js
  packages/rspack/tests/configCases/css/export-selector/reexported.js
  packages/rspack/tests/configCases/css/export-selector/style.module.css
  packages/rspack/tests/configCases/css/export-selector/webpack.config.js
Labels: team, release: feature

#6229 fix: swc plugins not being able to spawn threads
  Cargo.lock
  Cargo.toml
  diffcases/arco-pro/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#6228 chore(docs): improve benchmark appearance
  website/theme/components/Benchmark/ProgressBar.tsx
  website/theme/components/Benchmark/index.module.scss
  website/theme/components/Benchmark/index.tsx
Labels: team

#6232 docs(website): fix broken right nav in join-us page
  website/docs/en/misc/join-us.mdx
Labels: team

#6231 docs(website): move sections around in guide
  website/docs/en/guide/config-diff.mdx
  website/docs/en/guide/migrate-from-cra.mdx
  website/docs/en/guide/migrate-from-webpack.mdx
  website/docs/en/guide/migrate-storybook.mdx
  website/docs/en/misc/glossary.mdx
  website/docs/zh/guide/migrate-from-cra.mdx
  website/docs/zh/guide/migrate-from-webpack.mdx
  website/docs/zh/guide/migrate-storybook.mdx
  website/docs/zh/misc/glossary.mdx
  website/rspress.config.ts
Labels: team

#6235 docs(website): switch images to cdn urls and remove all image binaries
  website/docs/en/blog/announcing-0.2.mdx
  website/docs/en/index.md
  website/docs/en/misc/branding.mdx
  website/docs/public/benchmark.jpeg
  website/docs/public/compare.png
  website/docs/public/logo.png
  website/docs/public/rsbuild.png
  website/docs/zh/blog/announcing-0.2.mdx
  website/docs/zh/misc/branding.mdx
  website/rspress.config.ts
  website/theme/components/HomeHero/index.tsx
Labels: team

#6237 docs: add image assets guide to website README
  website/README.md
  website/docs/en/guide/tree-shaking.mdx
  website/docs/zh/guide/tree-shaking.mdx
Labels: team

#6175 docs(webiste): tweak the recruiting message; balance parenthesis on a wording
  website/theme/i18n/enUS.ts
Labels: team

#6177 docs(website): change "get started" button to primary and "intro" button to secondary
  website/docs/en/index.md
  website/docs/zh/index.md
Labels: team

#6239 chore: remove crates/cargo-rst which is not used anymore
  Cargo.lock
  Cargo.toml
  crates/cargo-rst/Cargo.toml
  crates/cargo-rst/LICENSE
  crates/cargo-rst/fixtures/diff/dirs/actual/tt.js
  crates/cargo-rst/fixtures/diff/dirs/expected/a/a.js
  crates/cargo-rst/fixtures/diff/dirs/expected/tt.js
  crates/cargo-rst/fixtures/diff/files/actual/a.js
  crates/cargo-rst/fixtures/diff/files/expected/a.js
  crates/cargo-rst/fixtures/diff/missing/actual/a.js
  crates/cargo-rst/fixtures/diff/missing/expected/a.js
  crates/cargo-rst/fixtures/diff/missing/expected/b.js
  crates/cargo-rst/fixtures/same/files/actual/a.js
  crates/cargo-rst/fixtures/same/files/expected/a.js
  crates/cargo-rst/fixtures/update/a/actual/a.js
  crates/cargo-rst/fixtures/update/update_all/a/actual/a.js
  crates/cargo-rst/fixtures/update/update_all/b/actual/a.js
  crates/cargo-rst/fixtures/update/update_all/c/actual/a.js
  crates/cargo-rst/readme.md
  crates/cargo-rst/src/helper.rs
  crates/cargo-rst/src/lib.rs
  crates/cargo-rst/src/record.rs
  crates/cargo-rst/src/rst.rs
  crates/cargo-rst/src/terminal_inline.rs
  crates/cargo-rst/src/update.rs
  crates/cargo-rst/tests/fixtures/a/actual/a.js
  crates/cargo-rst/tests/fixtures/a/expected/a.js
  crates/cargo-rst/tests/fixtures/b/actual/a.js
  crates/cargo-rst/tests/fixtures/b/expected/a.js
  crates/cargo-rst/tests/fixtures/files/actual/a.js
  crates/cargo-rst/tests/fixtures/files/expected/a.js
  crates/cargo-rst/tests/fixtures/partial/actual/a.js
  crates/cargo-rst/tests/fixtures/partial/actual/b.js
  crates/cargo-rst/tests/fixtures/partial/expected/a.js
  crates/cargo-rst/tests/main.rs
  crates/cargo-rst/tests/templates/a/actual/a.js
  crates/cargo-rst/tests/templates/a/expected/a.js
  crates/cargo-rst/tests/templates/b/actual/a.js
  crates/cargo-rst/tests/templates/b/expected/a.js
  crates/cargo-rst/tests/templates/files/actual/a.js
  crates/cargo-rst/tests/templates/files/expected/a.js
  crates/cargo-rst/tests/templates/partial/actual/a.js
  crates/cargo-rst/tests/templates/partial/actual/b.js
  crates/cargo-rst/tests/templates/partial/expected/a.js
Labels: team

#6208 chore: introduce api-extractor
  .github/workflows/reusable-build.yml
  .gitignore
  .prettierignore
  .vscode/settings.json
  api-extractor.json
  package.json
  packages/rspack-dev-server/api-extractor.json
  packages/rspack-dev-server/etc/dev-server.api.md
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-react-refresh/api-extractor.json
  packages/rspack-plugin-react-refresh/etc/plugin-react-refresh.api.md
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/api-extractor.json
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/package.json
  packages/rspack/api-extractor.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/MultiWatching.ts
  packages/rspack/src/RuntimeGlobals.ts
  packages/rspack/src/builtin-plugin/SourceMapDevToolPlugin.ts
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/lib/ModuleFilenameHelpers.js
  packages/rspack/src/lib/ModuleFilenameHelpers.ts
  pnpm-lock.yaml
Labels: team

#6251 chore: update api snapshot
  api-extractor.json
  lint-staged.config.mjs
  packages/rspack-dev-server/etc/api.md
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-react-refresh/etc/api.md
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/package.json
  packages/rspack/etc/api.md
  packages/rspack/package.json
Labels: team

#6252 fix: dependencies span should rely on final ast
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  packages/rspack/tests/__snapshots__/ConfigTestCases.basictest.js.snap
  packages/rspack/tests/configCases/css/export-selector/index.js
  packages/rspack/tests/configCases/css/export-selector/style.module.css
  packages/rspack/tests/configCases/css/export-selector/webpack.config.js
Labels: team, release: bug fix

#6253 fix: json empty array panic
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack/tests/configCases/tree-shaking/json-empty-array/arr.json
  packages/rspack/tests/configCases/tree-shaking/json-empty-array/index.js
  packages/rspack/tests/configCases/tree-shaking/json-empty-array/webpack.config.js
Labels: team, release: bug fix

#6250 fix: napi value convert error in css-loader
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/filename.rs
  crates/rspack_binding_values/src/path_data.rs
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/configCases/hooks/compat-path-data-chunk-contenthash/index.js
  packages/rspack/tests/configCases/hooks/compat-path-data-chunk-contenthash/test.config.js
  packages/rspack/tests/configCases/hooks/compat-path-data-chunk-contenthash/webpack.config.js
Labels: team, release: bug fix

#6249 feat: support checkResource option in IgnorePlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_ignore.rs
  crates/rspack_plugin_ignore/Cargo.toml
  crates/rspack_plugin_ignore/src/lib.rs
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/IgnorePlugin.ts
  webpack-test/configCases/ignore/checkContext/test.filter.js
  webpack-test/configCases/ignore/checkResource-one-argument/test.filter.js
  webpack-test/configCases/ignore/checkResource-two-arguments/test.filter.js
  website/docs/en/plugins/webpack/ignore-plugin.mdx
  website/docs/zh/plugins/webpack/ignore-plugin.mdx
Labels: team, release: feature

#6255 feat: add `emit` option for asset modules
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_asset/src/lib.rs
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/configCases/asset/_images/file.jpg
  packages/rspack/tests/configCases/asset/_images/file.png
  packages/rspack/tests/configCases/asset/disable-emit-by-rule/index.js
  packages/rspack/tests/configCases/asset/disable-emit-by-rule/webpack.config.js
  packages/rspack/tests/configCases/asset/disable-emit-for-asset/index.js
  packages/rspack/tests/configCases/asset/disable-emit-for-asset/webpack.config.js
  packages/rspack/tests/configCases/asset/disable-emit-for-resource/index.js
  packages/rspack/tests/configCases/asset/disable-emit-for-resource/webpack.config.js
  webpack-test/configCases/asset-modules/emit/test.filter.js
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: feature

#6257 chore: update package manager of webpack-test README
  .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
  webpack-examples/README.md
  webpack-test/README.md
Labels: team

#6247 fix(core): update module federation runtime
  packages/rspack/package.json
  packages/rspack/src/container/default.runtime.js
  packages/rspack/tests/configCases/container-1-5/2-container-full/index.js
  packages/rspack/tests/configCases/container-1-5/module-federation-with-shareScope/index.js
  pnpm-lock.yaml
Labels: release: bug fix

#6260 feat: split lint-website ci
  .github/workflows/ci.yml
Labels: release: feature

#6263 docs: use PackageManagerTabs to display install commands
  website/docs/en/guide/language-support.mdx
  website/docs/en/guide/react.mdx
  website/docs/en/guide/vue.mdx
  website/docs/zh/guide/language-support.mdx
  website/docs/zh/guide/react.mdx
  website/docs/zh/guide/vue.mdx
Labels: team

#6264 fix: stats in multiple runner
  .github/workflows/test-ng.yml
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/src/runner/multiple.ts
  packages/rspack-test-tools/src/runner/normal.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/hot.ts
  packages/rspack-test-tools/src/runner/runner/watch.ts
  packages/rspack-test-tools/src/runner/type.ts
  packages/rspack-test-tools/src/runner/watch.ts
  packages/rspack-test-tools/src/type.ts
Labels: team, release: bug fix

#6265 fix: JsPathData type
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
Labels: team, release: bug fix

#6269 docs: improve style of API meta tags
  website/components/ApiMeta.module.scss
  website/components/ApiMeta.scss
  website/components/ApiMeta.tsx
  website/docs/en/config/builtins.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/guide/web-workers.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/guide/web-workers.mdx
Labels: team

#6271 chore: remove hot document
  packages/rspack-test-tools/src/helper/legacy/FakeDocument.js
  packages/rspack-test-tools/src/helper/legacy/createHotDocument.js
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/hot.ts
  packages/rspack-test-tools/src/runner/runner/normal.ts
  packages/rspack-test-tools/src/runner/runner/web.ts
  packages/rspack/tests/hotCases/css/css-loading-unique-name/index.js
  packages/rspack/tests/hotCases/css/css-modules/index.js
  packages/rspack/tests/hotCases/css/css/index.js
Labels: team

#6125 fix: add sourcemap file to chunk.auxiliaryFiles
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/tests/configCases/source-map/auxiliary-files/index.js
  packages/rspack/tests/configCases/source-map/auxiliary-files/webpack.config.js
Labels: release: bug fix

#6279 fix: export types of `ModuleFilenameHelpers` and `Template`
  packages/rspack/etc/api.md
  packages/rspack/src/exports.ts
Labels: team, release: bug fix

#6278 fix: performance degradation for auxiliary files
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_devtool/src/mapped_assets_cache.rs
Labels: release: bug fix

#6280 docs: update scaffolding part of quick start document
  website/docs/en/guide/quick-start.mdx
  website/docs/zh/guide/quick-start.mdx
Labels: team

#6258 refactor: split task in make stage
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/queue.rs
  crates/rspack_core/src/compiler/make/tasks/add.rs
  crates/rspack_core/src/compiler/make/tasks/build.rs
  crates/rspack_core/src/compiler/make/tasks/clean.rs
  crates/rspack_core/src/compiler/make/tasks/factorize.rs
  crates/rspack_core/src/compiler/make/tasks/mod.rs
  crates/rspack_core/src/compiler/make/tasks/process_dependencies.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team

#5904 fix: avoid invoking `toJSON` method of `additionalData`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_options/src/plugins/css_extract_additional_data.rs
  crates/rspack_binding_options/src/plugins/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_napi/src/callback.rs
  crates/rspack_napi/src/js_values/js_value_ref.rs
  crates/rspack_napi/src/js_values/mod.rs
  crates/rspack_napi/src/lib.rs
  crates/rspack_napi/src/threadsafe_function.rs
  crates/rspack_napi/src/threadsafe_js_value_ref.rs
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_extract_css/src/lib.rs
  crates/rspack_plugin_extract_css/src/parser_and_generator.rs
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/loadLoader.js
  packages/rspack/tests/configCases/loader/rspack-issue-5600/a.js
  packages/rspack/tests/configCases/loader/rspack-issue-5600/index.js
  packages/rspack/tests/configCases/loader/rspack-issue-5600/loader-a.js
  packages/rspack/tests/configCases/loader/rspack-issue-5600/loader-b.js
  packages/rspack/tests/configCases/loader/rspack-issue-5600/webpack.config.js
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
Labels: release: bug fix

#6282 docs(website): consolidate guide / languages and Frameworks
  website/docs/en/guide/css.mdx
  website/docs/en/guide/json.mdx
  website/docs/en/guide/nodejs.mdx
  website/docs/en/guide/typescript.mdx
  website/docs/en/index.md
  website/docs/zh/guide/css.mdx
  website/docs/zh/guide/json.mdx
  website/docs/zh/guide/nodejs.mdx
  website/docs/zh/guide/typescript.mdx
  website/docs/zh/index.md
  website/rspress.config.ts
Labels: team

#6275 feat(rspack_mf_plugin): federation runtime runtime module
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_plugin_mf/src/container/mod.rs
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_mf/src/lib.rs
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/bootstrap.js
  packages/rspack/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/index.js
  packages/rspack/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/plugin.js
  packages/rspack/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/webpack.config.js
Labels: release: feature

#6286 chore: add jsdom web runner
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/cjs.ts
  packages/rspack-test-tools/src/runner/runner/esm.ts
  packages/rspack-test-tools/src/runner/runner/hot.ts
  packages/rspack-test-tools/src/runner/runner/watch.ts
  packages/rspack-test-tools/src/runner/runner/web.ts
  packages/rspack-test-tools/src/runner/runner/web/fake.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
  packages/rspack-test-tools/src/runner/type.ts
  packages/rspack/tests/configCases/css/css-cross-origin-loading/index.js
  packages/rspack/tests/configCases/nonce/not-set-nonce/index.js
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/snapshot/web/1.snap.txt
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/snapshot/web/2.snap.txt
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/snapshot/web/3.snap.txt
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/snapshot/web/1.snap.txt
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/snapshot/web/2.snap.txt
  packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/snapshot/web/3.snap.txt
  packages/rspack/tests/hotCases/plugins/banner/test.filter.js
Labels: team

#6291 fix: progress bar draw interval
  crates/rspack_plugin_progress/src/lib.rs
Labels: team, release: bug fix

#6296 docs: fix all broken plugin links
  website/cspell.config.cjs
  website/docs/en/blog/announcing-0.4.mdx
  website/docs/en/config/builtins.mdx
  website/docs/en/config/optimization.mdx
  website/docs/en/guide/module-federation.mdx
  website/docs/zh/blog/announcing-0.4.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/guide/module-federation.mdx
Labels: team

#6274 fix(binding): fix type error of binding.d.ts; add test for binding.d.ts
  crates/node_binding/binding.d.ts
  crates/node_binding/package.json
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/scripts/build.js
  crates/node_binding/scripts/dts-header.js
  crates/node_binding/tsconfig.type-test.json
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_values/src/compilation.rs
Labels: release: bug fix

#6301 fix: should minimize asset with query
  Cargo.lock
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack/tests/configCases/builtins/minify-with-query/index.css
  packages/rspack/tests/configCases/builtins/minify-with-query/index.js
  packages/rspack/tests/configCases/builtins/minify-with-query/webpack.config.js
Labels: team, release: bug fix

#6311 fix: compilation.import_module use immutable ref
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor.rs
Labels: team, release: bug fix

#6314 feat: provide type declaration for builtin:swc-loader
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-loader/swc/index.ts
  packages/rspack/src/builtin-loader/swc/pluginImport.ts
  packages/rspack/src/builtin-loader/swc/react.ts
  packages/rspack/src/builtin-loader/swc/relay.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/exports.ts
  website/docs/en/blog/announcing-0.5.mdx
  website/docs/en/guide/builtin-swc-loader.mdx
  website/docs/en/guide/vue.mdx
  website/docs/zh/blog/announcing-0.5.mdx
  website/docs/zh/guide/builtin-swc-loader.mdx
  website/docs/zh/guide/vue.mdx
Labels: team, release: feature

#6292 refactor: make trait `Module` `'static`
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/module.rs
Labels: team

#6319 fix(create-rspack): remove useless sourceMap option in templates
  diffcases/arco-pro/rspack.config.js
  diffcases/arco-pro/webpack.config.js
  packages/create-rspack/template-react-ts/rspack.config.js
  packages/create-rspack/template-react/rspack.config.js
  packages/create-rspack/template-vue/rspack.config.js
  packages/rspack-test-tools/rspack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/inline-pitching/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-automic/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-classic/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/webpack.config.js
  packages/rspack/tests/configCases/loader/loader-builtin-swc/webpack.config.js
  packages/rspack/tests/configCases/source-map/source-map/webpack.config.js
  website/docs/en/blog/announcing-0.3.mdx
  website/docs/en/blog/announcing-0.5.mdx
  website/docs/en/guide/builtin-swc-loader.mdx
  website/docs/en/guide/migrate-from-webpack.mdx
  website/docs/en/guide/vue.mdx
  website/docs/zh/blog/announcing-0.3.mdx
  website/docs/zh/blog/announcing-0.5.mdx
  website/docs/zh/guide/builtin-swc-loader.mdx
  website/docs/zh/guide/migrate-from-webpack.mdx
  website/docs/zh/guide/vue.mdx
Labels: team, release: bug fix

#6321 refactor: import context dependency param evaluate
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_util/src/diff_mode.rs
  crates/rspack_util/src/lib.rs
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/tests/builtinCases/rspack/dynamic-import/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/sub/a.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/sub/a1.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/sub/abc.js
Labels: team

#6329 perf(core): remove events dependency
  packages/rspack/hot/emitter.js
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: performance

#6330 docs: enable cleanUrls for website
  website/components/property-type.tsx
  website/docs/en/blog/announcing-0.2.mdx
  website/docs/en/blog/announcing-0.4.mdx
  website/docs/en/blog/announcing-0.5.mdx
  website/docs/en/blog/announcing-0.6.mdx
  website/docs/en/blog/module-federation-added-to-rspack.mdx
  website/docs/en/config/builtins.mdx
  website/docs/en/config/entry.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/config/externals.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/output.mdx
  website/docs/en/guide/react.mdx
  website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/webpack/electron-target-plugin.mdx
  website/docs/en/plugins/webpack/enable-chunk-loading-plugin.mdx
  website/docs/en/plugins/webpack/enable-library-plugin.mdx
  website/docs/en/plugins/webpack/enable-wasm-loading-plugin.mdx
  website/docs/en/plugins/webpack/externals-plugin.mdx
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/en/plugins/webpack/node-target-plugin.mdx
  website/docs/en/plugins/webpack/source-map-dev-tool-plugin.mdx
  website/docs/zh/blog/announcing-0.2.mdx
  website/docs/zh/blog/announcing-0.4.mdx
  website/docs/zh/blog/announcing-0.5.mdx
  website/docs/zh/blog/announcing-0.6.mdx
  website/docs/zh/blog/module-federation-added-to-rspack.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/entry.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/externals.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/guide/react.mdx
  website/docs/zh/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/webpack/electron-target-plugin.mdx
  website/docs/zh/plugins/webpack/enable-chunk-loading-plugin.mdx
  website/docs/zh/plugins/webpack/enable-library-plugin.mdx
  website/docs/zh/plugins/webpack/enable-wasm-loading-plugin.mdx
  website/docs/zh/plugins/webpack/externals-plugin.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/plugins/webpack/node-target-plugin.mdx
  website/docs/zh/plugins/webpack/source-map-dev-tool-plugin.mdx
  website/rspress.config.ts
Labels: team

#6320 chore: bump oxc_resolver to v1.6.7
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team

#6334 refactor: remove is_new_treeshaking in module_graph
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/tasks/add.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
Labels: team

#6298 fix: incremental rebuild clean module_graph.block & dependencies
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: bug fix

#6342 chore: remove case sensitive case
  packages/rspack-test-tools/tests/cases/warnings/case-sensitive/A.js
  packages/rspack-test-tools/tests/cases/warnings/case-sensitive/B/file.js
  packages/rspack-test-tools/tests/cases/warnings/case-sensitive/a.js
  packages/rspack-test-tools/tests/cases/warnings/case-sensitive/b/file.js
  packages/rspack-test-tools/tests/cases/warnings/case-sensitive/index.js
  packages/rspack-test-tools/tests/cases/warnings/case-sensitive/warnings.js
Labels: team

#6331 feat: support context module critical
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/fake-map/module.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/fake-map/module2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/module.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/cases/context/context-module-dynamic-import-tagged-template/warnings.js
  packages/rspack/tests/configCases/context-module/critical-warning/index.js
  packages/rspack/tests/configCases/context-module/critical-warning/sub/a.js
  packages/rspack/tests/configCases/context-module/critical-warning/sub2/a.js
  packages/rspack/tests/configCases/context-module/critical-warning/warnings.js
  packages/rspack/tests/configCases/context-module/critical-warning/webpack.config.js
  website/components/ApiMeta.tsx
  website/components/builtIns/mdx-components.tsx
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: feature

#6343 chore: remove case sensitive case of webpack-test
  webpack-test/cases/errors/case-sensitive/A.js
  webpack-test/cases/errors/case-sensitive/B/file.js
  webpack-test/cases/errors/case-sensitive/a.js
  webpack-test/cases/errors/case-sensitive/b/file.js
  webpack-test/cases/errors/case-sensitive/index.js
  webpack-test/cases/errors/case-sensitive/test.filter.js
  webpack-test/cases/errors/case-sensitive/warnings.js
Labels: team

#6346 chore: move config case of context module
  packages/rspack-test-tools/tests/configCases/context-module/critical-warning/index.js
  packages/rspack-test-tools/tests/configCases/context-module/critical-warning/sub/a.js
  packages/rspack-test-tools/tests/configCases/context-module/critical-warning/sub2/a.js
  packages/rspack-test-tools/tests/configCases/context-module/critical-warning/warnings.js
  packages/rspack-test-tools/tests/configCases/context-module/critical-warning/webpack.config.js
Labels: team

#6300 feat: support more methods for `errors` and `warnings` in `Compilation`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/tests/Errors.test.js
  packages/rspack/tests/copyPlugin/__snapshots__/CopyPlugin.test.js.snap
Labels: release: feature

#6351 fix: align get_nested_exports_info with webpack
  crates/rspack_core/src/exports_info.rs
Labels: team, release: bug fix

#6241 test: add hook cases
  .gitignore
  .vscode/settings.json
  package.json
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/jest.config.compat.js
  packages/rspack-test-tools/jest.d.ts
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack-test-tools/src/processor/index.ts
  packages/rspack-test-tools/src/processor/snapshot.ts
  packages/rspack-test-tools/tests/HookCases.test.js
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/test.js
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/test.js
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/a.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/b.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/c.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/duplicate.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/a.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/b.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/c.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/request.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/a.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/b.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/c.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/resource.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/test.js
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/Errors.test.js
  packages/rspack/tests/fixtures/hook.js
  packages/rspack/tests/jestFileSnapshot.js
  packages/rspack/tests/setupTestFramework.js
  pnpm-lock.yaml
  scripts/test/diff-exclude.cjs
Labels: team

#6352 chore(api-extractor): exclude warning and add forgotten exports to report
  api-extractor.json
  packages/rspack-dev-server/etc/api.md
  packages/rspack-test-tools/etc/api.md
  packages/rspack/etc/api.md
Labels: team

#6340 fix: default resolve roots
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack-test-tools/tests/defaultsCases/cache/non-root.js
  packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/configCases/resolve/roots/dir/a.js
  packages/rspack/tests/configCases/resolve/roots/dir2/b.js
  packages/rspack/tests/configCases/resolve/roots/index.js
  packages/rspack/tests/configCases/resolve/roots/webpack.config.js
Labels: team, release: bug fix

#6001 feat: diagnostic with labels
  Cargo.lock
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/ext.rs
  crates/rspack_error/src/miette_helpers.rs
Labels: team, release: feature

#6361 chore: move resolve roots test
  packages/rspack-test-tools/tests/configCases/resolve/roots/dir/a.js
  packages/rspack-test-tools/tests/configCases/resolve/roots/dir2/b.js
  packages/rspack-test-tools/tests/configCases/resolve/roots/index.js
  packages/rspack-test-tools/tests/configCases/resolve/roots/webpack.config.js
Labels: team

#6365 docs: improve homepage style
  website/package.json
  website/pnpm-lock.yaml
  website/theme/components/Benchmark/index.tsx
  website/theme/components/HomeFooter/index.tsx
  website/theme/index.css
  website/theme/pages/index.tsx
Labels: team

#6364 refactor: split cutout and repair step in make
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
  crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/rebuild_deps_builder.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/make/tasks/clean.rs
  crates/rspack_core/src/compiler/make/tasks/mod.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team

#6367 chore: modify cwd of test cases and refactor some case creator
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/src/case/compiler.ts
  packages/rspack-test-tools/src/case/defaults.ts
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/case/stats-api.ts
  packages/rspack-test-tools/src/helper/util/currentWatchStep.js
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/simple.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/test/simple.ts
  packages/rspack-test-tools/tests/Compiler.test.js
  packages/rspack-test-tools/tests/ConfigTestCases.test.js
  packages/rspack-test-tools/tests/Defaults.test.js
  packages/rspack-test-tools/tests/HashTestCases.test.js
  packages/rspack-test-tools/tests/HookCases.test.js
  packages/rspack-test-tools/tests/Stats.test.js
  packages/rspack-test-tools/tests/StatsTestCases.test.js
  packages/rspack-test-tools/tests/TestCasesNormal.test.js
  packages/rspack-test-tools/tests/TreeShaking.test.js
  packages/rspack-test-tools/tests/WatchTestCases.test.js
  packages/rspack-test-tools/tests/__snapshots__/ConfigTestCases.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsTestCases.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/test.config.js
  packages/rspack-test-tools/tests/builtinCases/samples/simple/test.config.js
  packages/rspack-test-tools/tests/defaultsCases/cache/non-root.js
  packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js
  packages/rspack-test-tools/tests/defaultsCases/library/library.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/output/unique-name.js
  packages/rspack-test-tools/tests/fixtures/hook.js
Labels: team

#6371 docs: update react doc
  website/docs/en/guide/tech/react.mdx
  website/docs/zh/guide/tech/react.mdx
Labels: team

#6082 fix: errors thrown in userland callbacks should not panic
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group_test.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/chunks-function-with-error/errors.js
  packages/rspack-test-tools/tests/configCases/split-chunks/chunks-function-with-error/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/chunks-function-with-error/webpack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/test-function-with-error/errors.js
  packages/rspack-test-tools/tests/configCases/split-chunks/test-function-with-error/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/test-function-with-error/webpack.config.js
Labels: team, release: bug fix

#6377 fix: process dependencies task remove resolve_options
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
Labels: team, release: bug fix

#6379 chore: jsdom windows
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
Labels: team

#6380 fix: swc minimizer extracted comments should be stable
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/__snapshots__/ConfigTestCases.test.js.snap
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/index.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/bar/index.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/bar/package.json
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/baz/index.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/baz/package.json
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/foo/index.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/relative.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/webpack.config.js
Labels: team, release: bug fix

#6383 docs: fix readme.md credits links
  README.md
  README.zh-CN.md
Labels: team

#6384 docs: update outdated FAQs
  website/docs/en/misc/faq.mdx
  website/docs/zh/misc/faq.mdx
Labels: team

#6385 docs: improve team member list styles
  website/components/RandomMemberList.module.scss
  website/components/RandomMemberList.tsx
  website/docs/en/misc/team/core-team.mdx
  website/docs/zh/misc/team/core-team.mdx
  website/project-words.txt
Labels: team

#6386 fix: minify comments extract
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/configCases/builtins/minify-extract-comments-with-query/index.js
  packages/rspack-test-tools/tests/configCases/builtins/minify-extract-comments-with-query/webpack.config.js
Labels: team, release: bug fix

#6388 fix: runtimeChunk should control all entries' runtime
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_runtime_chunk.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_core/src/utils/runtime.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_runtime_chunk/Cargo.toml
  crates/rspack_plugin_runtime_chunk/src/lib.rs
  packages/rspack-test-tools/tests/configCases/container-1-0/runtime-chunk-single/a.js
  packages/rspack-test-tools/tests/configCases/container-1-0/runtime-chunk-single/bootstrap.js
  packages/rspack-test-tools/tests/configCases/container-1-0/runtime-chunk-single/index.js
  packages/rspack-test-tools/tests/configCases/container-1-0/runtime-chunk-single/test.config.js
  packages/rspack-test-tools/tests/configCases/container-1-0/runtime-chunk-single/webpack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/entry-runtime-false/e1.js
  packages/rspack-test-tools/tests/configCases/runtime/entry-runtime-false/e2.js
  packages/rspack-test-tools/tests/configCases/runtime/entry-runtime-false/test.config.js
  packages/rspack-test-tools/tests/configCases/runtime/entry-runtime-false/webpack.config.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/multi-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/single-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/true-runtime-chunk.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/builtin-plugin/RuntimeChunkPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/container/ContainerPlugin.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/components/PluginSupportStatusTable.tsx
  website/docs/en/config/optimization.mdx
  website/docs/en/plugins/webpack/runtime-chunk-plugin.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/plugins/webpack/runtime-chunk-plugin.mdx
Labels: team, release: bug fix

#6394 fix(mf): remove empty chunk mapping
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
Labels: team, release: bug fix

#6387 fix(config): snapshot.module accept `{ timestamp: true}`
  packages/rspack-test-tools/tests/configCases/cache/issues-6381/a/a.js
  packages/rspack-test-tools/tests/configCases/cache/issues-6381/index.js
  packages/rspack-test-tools/tests/configCases/cache/issues-6381/webpack.config.js
  packages/rspack/src/config/defaults.ts
Labels: release: bug fix

#6389 fix: swc parser should always preserve comments
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/dropped_comments_preserver.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/mod.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/provide/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/a.js
  packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/index.js
  packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/webpack.config.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/new_treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/webpack-innergraph-try-globals/snapshot/new_treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/webpack-innergraph-try-globals/snapshot/output.snap.txt
  plugin-test/css-extract/enforceEsm.test.js
Labels: team, release: bug fix

#6375 feat(copyRspackPlugin): support transform configuration
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
  plugin-test/copy-plugin/CopyPlugin.test.js
  plugin-test/copy-plugin/__snapshots__/CopyPlugin.test.js.snap
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: team, release: feature

#6396 fix: wrong module source
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
Labels: team, release: bug fix

#6393 feat: support dynamic entry
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_dynamic_entry.rs
  crates/rspack_plugin_dynamic_entry/Cargo.toml
  crates/rspack_plugin_dynamic_entry/LICENSE
  crates/rspack_plugin_dynamic_entry/src/lib.rs
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/DynamicEntryPlugin.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/lib/EntryOptionPlugin.ts
  webpack-test/MultiCompiler.test.js
  webpack-test/configCases/entry/depend-on-bug/node_modules/isomorphic-fetch.js
  webpack-test/configCases/entry/descriptor/test.filter.js
  webpack-test/configCases/entry/function-promise/test.filter.js
  webpack-test/configCases/entry/function/test.filter.js
  website/components/PluginSupportStatusTable.tsx
  website/docs/en/config/entry.mdx
  website/docs/zh/config/entry.mdx
Labels: release: feature

#6399 fix(config): support snapshot config {timestamp: true} and {hash: true}
  packages/rspack/src/config/defaults.ts
Labels: release: bug fix
