Repository web-infra-dev/rspack, pull requests merged in 2024-12, with the labels that each got.

#8413 fix: rebuild should reset module.preOrderIndex
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/0/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/0/lib.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/1/lib.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/test.config.js
Labels: team, release: bug fix

#8585 feat: support chunksSortMode option to HtmlRspackPlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/lib.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  tests/plugin-test/html-plugin/basic.test.js
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: release: feature

#8582 docs: align `DefinePlugin` with #7108 in v0.x
  website/docs/en/plugins/webpack/define-plugin.mdx
  website/docs/zh/plugins/webpack/define-plugin.mdx
Labels: release: document

#8587 refactor: css hmr
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-ident-name/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-modules/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-modules/index.js
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/index.js
  packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt
Labels: team

#8564 perf: register cleanup hook on global
  crates/rspack_napi/src/js_values/one_shot_value_ref.rs
Labels: team, release: performance

#8591 fix: prevent from accessing outdated compilation
  packages/rspack/src/Compilation.ts
  packages/rspack/src/util/MergeCaller.ts
  packages/rspack/src/util/fake.ts
Labels: team, release: bug fix

#8581 perf: reduce memory consumption of paths
  Cargo.lock
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/utils/file_counter/incremental_info.rs
  crates/rspack_core/src/utils/file_counter/mod.rs
  crates/rspack_paths/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
Labels: team, release: performance

#8592 fix(incremental): get affected modules with chunk graph perf regression
  crates/rspack_core/src/incremental/mutations.rs
Labels: team, release: bug fix

#8578 chore: add release-check task
  Cargo.lock
  Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_loader_swc/src/transformer.rs
  crates/rspack_plugin_remove_duplicate_modules/Cargo.toml
  crates/swc_plugin_import/Cargo.toml
  justfile
  tasks/release-check/Cargo.toml
  tasks/release-check/src/main.rs
Labels: team

#8589 refactor: remove compilation.built_module
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/stats/mod.rs
Labels: team

#8590 fix: importModule should have err
  crates/rspack_binding_values/src/compilation/mod.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/loader.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/syntax-error.js
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#8479 feat: implement output.clean.keep: Option<string>
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_values/src/clean_options.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/clean_options.rs
  crates/rspack_core/src/options/mod.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/utils/fs_trim.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/configCases/clean/enabled/index.js
  packages/rspack-test-tools/tests/configCases/clean/enabled/readdir.js
  packages/rspack-test-tools/tests/configCases/clean/enabled/rspack.config.js
  packages/rspack-test-tools/tests/configCases/clean/ignore-string/index.js
  packages/rspack-test-tools/tests/configCases/clean/ignore-string/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  pnpm-lock.yaml
  tests/webpack-test/configCases/clean/ignore-hook/index.js
Labels: release: feature

#8616 chore: remove tracking subjects
  .github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
Labels: team

#8617 fix: trusted type should add module runtime requirements
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/index.js
  packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/rspack.config.js
  packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/test.config.js
  packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/worker.js
Labels: team, release: bug fix

#8602 perf: improve cached source data struct
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_lightningcss/src/lib.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$64d8082da28c92f64bc5$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$64d8082da28c92f64bc5$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryA.$00aa4eba20cb7ba5f261$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryB.$de8c661d8907aef4d5af$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/1.main.$bef3a06ea576419d5fcd$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/2.main.$ec5a7d24bc9a3c75d3dd$.css
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: performance

#8619 feat: support `output.trustedTypes.onPolicyCreationFailure`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_trusted_types_policy.js
  packages/rspack-test-tools/tests/defaultsCases/output/unique-name.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/src/chunk.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/webpack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: feature

#8620 perf: reduce heap allocations for `RuntimeModule`
  crates/rspack_cacheable_test/tests/with/as_preset/rspack_sources.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/runtime/mod.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_extract_css/src/runtime.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/expose_runtime_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_module/async_module.rs
  crates/rspack_plugin_runtime/src/runtime_module/compat_get_default_export.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_fake_namespace_object.rs
  crates/rspack_plugin_runtime/src/runtime_module/define_property_getters.rs
  crates/rspack_plugin_runtime/src/runtime_module/esm_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/export_webpack_require.rs
  crates/rspack_plugin_runtime/src/runtime_module/global.rs
  crates/rspack_plugin_runtime/src/runtime_module/has_own_property.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/make_namespace_object.rs
  crates/rspack_plugin_runtime/src/runtime_module/node_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/on_chunk_loaded.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/relative_url.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
Labels: team, release: performance

#8621 docs: rewrite `CopyRspackPlugin` documentation
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: team, release: document

#8623 fix: source map file should use contenthash itself
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/chunk.js
  packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/index.js
  packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/rspack.config.js
  packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/test.config.js
Labels: team, release: bug fix

#8625 perf: avoid heap allocation for getting connections
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/incremental/mutations.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_warn_sensitive_module/src/lib.rs
Labels: team, release: performance

#8628 fix: sync minify file comments from SWC
  Cargo.lock
  crates/rspack_loader_swc/src/compiler.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/swc.rs
  packages/rspack-test-tools/tests/builtinCases/swc-loader/minify/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/swc-loader/minify/index.js
  packages/rspack-test-tools/tests/builtinCases/swc-loader/minify/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/a.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/test.config.js
Labels: team, release: bug fix

#8632 ci: run miri on main
  .github/workflows/ci.yml
Labels: team

#8622 fix: generate wrong chunk filename runtime code on win32
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/a.js
  packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/b.js
  packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/index.js
  packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/rspack.config.js
Labels: team, release: bug fix

#8634 fix: avoid unnamed module ids
  crates/rspack_ids/src/named_module_ids_plugin.rs
  packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/0/index.js
  packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/1/index.js
  packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/rspack.config.js
Labels: team, release: bug fix

#8577 feat: support `getResolve` in external function context
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_binding_values/src/resolver.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_lazy_compilation/src/factory.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/loader-runner/index.ts
  tests/webpack-test/configCases/externals/resolve/node_modules/external.js
  tests/webpack-test/configCases/externals/resolve/test.filter.js
Labels: team, release: feature

#8635 docs: fix error links
  website/docs/zh/blog/announcing-1-1.mdx
Labels: release: document

#8595 fix: passively rebuild modules imported by `importModule`
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/dependency/loader_import.rs
  packages/rspack-test-tools/tests/hotCases/loader/import-module-1/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/loader/import-module-1/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/loader/import-module-1/a.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-1/index.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-1/loader.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-1/loader2.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/a.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/import_module_root.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/import_module_sub.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/index.js
  packages/rspack-test-tools/tests/hotCases/loader/import-module-2/loader.js
Labels: release: bug fix

#8644 fix: external module move out initial chunk
  crates/rspack_plugin_split_chunks/src/plugin/chunk.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/external-modules/external.js
  packages/rspack-test-tools/tests/configCases/split-chunks/external-modules/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/external-modules/rspack.config.js
Labels: team, release: bug fix

#8663 chore(workflow): set Issue types
  .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
  .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
  .github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
Labels: team

#8648 refactor: chunk graph binding API
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/module_graph.rs
  crates/rspack_binding_values/src/runtime.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-chunks/index.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-chunks/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Chunk.ts
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Entrypoint.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
Labels: team

#8665 feat: pass compiler_path to rust Compiler
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/compiler/mod.rs
  packages/rspack/src/Compiler.ts
Labels: team, release: feature

#8466 feat: cache storage
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/dependencies.rs
  crates/rspack_core/src/cache/persistent/occasion/make/meta.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/storage/memory.rs
  crates/rspack_core/src/cache/persistent/storage/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_fs/src/intermediate.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs_node/src/write.rs
  crates/rspack_storage/Cargo.toml
  crates/rspack_storage/LICENSE
  crates/rspack_storage/src/lib.rs
  crates/rspack_storage/src/pack/data/meta.rs
  crates/rspack_storage/src/pack/data/mod.rs
  crates/rspack_storage/src/pack/data/options.rs
  crates/rspack_storage/src/pack/data/pack.rs
  crates/rspack_storage/src/pack/data/scope.rs
  crates/rspack_storage/src/pack/fs/error.rs
  crates/rspack_storage/src/pack/fs/mod.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/manager/queue.rs
  crates/rspack_storage/src/pack/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/mod.rs
  crates/rspack_storage/src/pack/strategy/split/read_pack.rs
  crates/rspack_storage/src/pack/strategy/split/read_scope.rs
  crates/rspack_storage/src/pack/strategy/split/util.rs
  crates/rspack_storage/src/pack/strategy/split/validate_scope.rs
  crates/rspack_storage/src/pack/strategy/split/write_pack.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/node/NodeEnvironmentPlugin.ts
Labels: team, release: feature

#8672 feat: support additional-pass hook
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Watching.ts
  tests/webpack-test/configCases/additional-pass/simple/test.filter.js
Labels: team, release: feature

#8645 perf: ignore watching files in node_modules
  packages/rspack/src/Watching.ts
  website/docs/en/config/watch.mdx
  website/docs/zh/config/watch.mdx
Labels: team, release: performance

#8675 feat: improve cache storage
  Cargo.lock
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_storage/src/pack/data/meta.rs
  crates/rspack_storage/src/pack/data/mod.rs
  crates/rspack_storage/src/pack/data/options.rs
  crates/rspack_storage/src/pack/data/scope.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/handle_file.rs
  crates/rspack_storage/src/pack/strategy/split/mod.rs
  crates/rspack_storage/src/pack/strategy/split/read_scope.rs
  crates/rspack_storage/src/pack/strategy/split/util.rs
  crates/rspack_storage/src/pack/strategy/split/validate_scope.rs
  crates/rspack_storage/src/pack/strategy/split/write_pack.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
Labels: team, release: feature

#8684 docs: invite @GiveMe-A-Name @nyqykk to Rspack core team
  website/components/RandomMemberList.tsx
  website/project-words.txt
Labels: team, release: document

#8678 docs: clarify support for JavaScriptModulesPlugin as partial
  website/components/PluginSupportStatusTable.tsx
Labels: release: document

#8677 feat: exports info binding API
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/exports_info.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/module_graph.rs
  packages/rspack-test-tools/tests/configCases/module_graph/get_exports_info/a.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_exports_info/b.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_exports_info/c.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_exports_info/index.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_exports_info/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ExportsInfo.ts
  packages/rspack/src/ModuleGraph.ts
Labels: team, release: feature

#8680 feat: chunkGraph.getModuleId binding API
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_graph.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-id/index.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-id/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
Labels: team, release: feature

#8681 perf: remove tokio-console to reduce binary size
  .cargo/config.toml
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_tracing/Cargo.toml
  crates/rspack_tracing/src/lib.rs
  justfile
  packages/rspack-cli/src/utils/profile.ts
Labels: team, release: performance

#8689 docs: fix webpack plugins overview docs panic for zh lang
  website/components/PluginSupportStatusTable.tsx
Labels: team, release: document

#8692 docs: fix link for bundle size link in English locale
  website/docs/en/guide/optimization/analysis.mdx
Labels: release: document

#8639 feat(core)!: bump swc_core to 9.0.0
  Cargo.lock
  Cargo.toml
  packages/rspack-test-tools/package.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  pnpm-lock.yaml
  tests/e2e/package.json
  tests/plugin-test/css-extract/cases/pathinfo-devtool-source-map/expected/main.css
  tests/plugin-test/css-extract/cases/pathinfo/expected/main.css
  tests/plugin-test/package.json
  tests/webpack-test/package.json
Labels: release: feature, release: breaking change

#8687 feat: persistent cache
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_cache/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_cache/raw_storage.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/cache/disable.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/dependencies.rs
  crates/rspack_core/src/cache/persistent/occasion/make/meta.rs
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/storage/memory.rs
  crates/rspack_core/src/cache/persistent/storage/mod.rs
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#8694 perf: bump miette v7 to reduce binary size
  Cargo.lock
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/error.rs
  tasks/release-check/Cargo.toml
Labels: team, release: performance

#8642 feat: support `size` option for optimization.chunkIds config
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_ids.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/OccurrenceChunkIdsPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  tests/webpack-test/configCases/contenthash/include-chunk-id/test.filter.js
  website/components/PluginSupportStatusTable.tsx
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: release: feature

#8700 chore: update API change
  packages/rspack/etc/core.api.md
Labels: team

#8703 docs: improve `resolve.mainFields`
  website/docs/en/config/resolve.mdx
  website/docs/zh/config/resolve.mdx
Labels: team, release: document

#8702 feat: do not cleanup Rust instance
  packages/rspack-test-tools/tests/compilerCases/compiler-stats-shutdown.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
Labels: team, release: feature

#8697 feat: export `WarnCaseSensitiveModulesPlugin` and disable it by default
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/warn-case-sensitive-modules-plugin.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/warn-case-sensitive-modules-plugin.mdx
Labels: team, release: feature

#8666 perf: reduce memory consumption of `CachedSource`
  Cargo.lock
  Cargo.toml
  crates/rspack_binding_values/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$ae884e9ae01bc3c32ef3$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$ae884e9ae01bc3c32ef3$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryA.$bd5939485d4f3ec74c0d$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryB.$f4d423c146f6456d2f68$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/1.main.$e35ecf2d8d9936705256$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/2.main.$e0e9bed01c7ef0b55991$.css
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: performance

#8708 docs: React Compiler for React 17 and 18
  website/docs/en/guide/tech/react.mdx
  website/docs/zh/guide/tech/react.mdx
Labels: team, release: document

#8698 fix: escape css
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/css/escape-ident/index.js
  packages/rspack-test-tools/tests/configCases/css/escape-ident/index.module.css
  packages/rspack-test-tools/tests/configCases/css/escape-ident/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css/escape-ident/test.config.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/index.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/style.module.css
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/css/escape-unescape/index.js
  tests/webpack-test/configCases/css/escape-unescape/style.modules.css
  tests/webpack-test/configCases/css/escape-unescape/test.config.js
  tests/webpack-test/configCases/css/escape-unescape/webpack.config.js
Labels: team, release: bug fix

#8721 revert: Revert "chore: sanitize file paths"
  Cargo.toml
Labels: team

#8686 feat: cache storage move lock file
  crates/rspack_storage/src/pack/data/meta.rs
  crates/rspack_storage/src/pack/data/mod.rs
  crates/rspack_storage/src/pack/fs/mod.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/handle_file.rs
  crates/rspack_storage/src/pack/strategy/split/mod.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  crates/rspack_storage/tests/expire.rs
  crates/rspack_storage/tests/lock.rs
Labels: team, release: feature

#8713 feat: addInclude binding API
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  packages/rspack-test-tools/tests/configCases/compilation/add-include/bar.js
  packages/rspack-test-tools/tests/configCases/compilation/add-include/foo.js
  packages/rspack-test-tools/tests/configCases/compilation/add-include/index.js
  packages/rspack-test-tools/tests/configCases/compilation/add-include/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
Labels: release: feature

#8725 docs: persistent cache
  website/docs/en/config/cache.mdx
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/cache.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8729 feat: update experiments.cache signature
  crates/rspack_binding_options/src/options/raw_experiments/raw_cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/version.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#8728 feat(mf): bump @module-federation/runtime-tools to 0.8.4
  packages/rspack-test-tools/tests/configCases/container-1-5/2-container-full/index.js
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: feature

#8709 fix: the wrong filename was passed when calling the assetEmitted hook
  crates/rspack_core/src/compiler/mod.rs
  packages/rspack-test-tools/tests/configCases/hooks/rspack-issue-8676/index.css
  packages/rspack-test-tools/tests/configCases/hooks/rspack-issue-8676/index.js
  packages/rspack-test-tools/tests/configCases/hooks/rspack-issue-8676/rspack.config.js
Labels: release: bug fix

#8730 fix: module concatenation for dynamic export info
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/index.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/lib/a.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/lib/b.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/lib/c.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/rspack.config.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/index.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/lib/a.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/lib/b.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/lib/c.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/rspack.config.js
Labels: team, release: bug fix

#8739 fix: fix nightly release compare-before-emit-disable test failed
  packages/rspack-test-tools/tests/compilerCases/compare-before-emit-disable.js
Labels: team, release: bug fix

#8554 feat: support module.generator.outputPath
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_asset/src/lib.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  tests/webpack-test/configCases/asset-modules/rule-generator-outputPath/test.filter.js
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: feature

#8742 chore(deps): stop updating inventory with renovate ci
  .github/renovate.json5
Labels: team

#8731 perf: faster `substring` of `rspack-sources`
  Cargo.lock
  Cargo.toml
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$c4e695e4a317b7bf38b8$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$c4e695e4a317b7bf38b8$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryA.$a592ecca149e370fdc1b$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryB.$746e3b8334d2e3e55742$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/1.main.$c2b1ac5890b3ce869489$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/2.main.$7f467bf86f8fa8dc5137$.css
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: performance

#8743 ci: linux-musl build failed
  .github/workflows/reusable-build.yml
Labels: team

#8750 ci: should skip trim paths for doc changes
  .github/workflows/reusable-build.yml
Labels: team

#8745 docs: rewrite `SwcJsMinimizerRspackPlugin`
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/webpack/entry-plugin.mdx
Labels: team, release: document

#8746 perf: side effects when there aren't too many optimizable dependencies
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: performance

#8740 refactor: improve storage error message
  crates/rspack_core/src/cache/persistent/storage/memory.rs
  crates/rspack_core/src/cache/persistent/storage/mod.rs
  crates/rspack_storage/src/error.rs
  crates/rspack_storage/src/fs/error.rs
  crates/rspack_storage/src/fs/mod.rs
  crates/rspack_storage/src/lib.rs
  crates/rspack_storage/src/pack/data/pack.rs
  crates/rspack_storage/src/pack/data/scope.rs
  crates/rspack_storage/src/pack/fs/error.rs
  crates/rspack_storage/src/pack/fs/mod.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/handle_file.rs
  crates/rspack_storage/src/pack/strategy/split/mod.rs
  crates/rspack_storage/src/pack/strategy/split/read_pack.rs
  crates/rspack_storage/src/pack/strategy/split/read_scope.rs
  crates/rspack_storage/src/pack/strategy/split/util.rs
  crates/rspack_storage/src/pack/strategy/split/validate_scope.rs
  crates/rspack_storage/src/pack/strategy/split/write_pack.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  crates/rspack_storage/tests/expire.rs
  crates/rspack_storage/tests/lock.rs
  crates/rspack_storage/tests/multi.rs
Labels: team

#8760 feat: add macro to get rspack version
  Cargo.lock
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_macros/Cargo.toml
  crates/rspack_macros/src/lib.rs
  crates/rspack_macros/src/rspack_version.rs
Labels: team, release: feature

#8761 refactor: merge binding crates into `rspack_binding_values`
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/src/lib.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/LICENSE
  crates/rspack_binding_options/src/lib.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/plugins/buildtime_plugins.rs
  crates/rspack_binding_values/src/plugins/context_replacement.rs
  crates/rspack_binding_values/src/plugins/js_loader/context.rs
  crates/rspack_binding_values/src/plugins/js_loader/mod.rs
  crates/rspack_binding_values/src/plugins/js_loader/resolver.rs
  crates/rspack_binding_values/src/plugins/js_loader/scheduler.rs
  crates/rspack_binding_values/src/plugins/mod.rs
  crates/rspack_binding_values/src/raw_options/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_banner.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_bundle_info.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_copy.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_css_extract.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_dll.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_html.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_ids.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_ignore.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_lazy_compilation.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_limit_chunk_count.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_mf.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_progress.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_runtime_chunk.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_size_limits.rs
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_binding_values/src/raw_options/raw_cache.rs
  crates/rspack_binding_values/src/raw_options/raw_devtool.rs
  crates/rspack_binding_values/src/raw_options/raw_dynamic_entry.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/raw_cache/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/raw_cache/raw_snapshot.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/raw_cache/raw_storage.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/raw_incremental.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/raw_rspack_future.rs
  crates/rspack_binding_values/src/raw_options/raw_external.rs
  crates/rspack_binding_values/src/raw_options/raw_mode.rs
  crates/rspack_binding_values/src/raw_options/raw_module/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_node.rs
  crates/rspack_binding_values/src/raw_options/raw_optimization.rs
  crates/rspack_binding_values/src/raw_options/raw_output.rs
  crates/rspack_binding_values/src/raw_options/raw_snapshot.rs
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/raw_split_chunk_size.rs
  crates/rspack_binding_values/src/raw_options/raw_stats.rs
  crates/rspack_tracing/src/lib.rs
  tests/webpack-test/cases/loaders/cjs-loader-type/index.js
Labels: team

#8765 feat: persistent cache expose error to compilation.diagnostic
  crates/rspack_core/src/cache/disable.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/dependencies.rs
  crates/rspack_core/src/cache/persistent/occasion/make/meta.rs
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
Labels: team, release: feature

#8769 release: release v1.1.8 to prevent the attacked version from being installed
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#8777 feat: persistent cache in production mode wait for save to complete
  crates/rspack_core/src/cache/persistent/mod.rs
Labels: release: feature

#8783 chore: remove all unnecessary workflow
  .github/auto_assign.yml
  .github/workflows/auto-assign.yaml
  .github/workflows/bench.yml
  .github/workflows/diff.yml.bak
  .github/workflows/get-runner-labels.yml
  .github/workflows/github-issue-sync.yml
  .github/workflows/issue-mark-assignee.yml
Labels: team

#8784 chore: remove issue_comment trigger from CI
  .github/workflows/ecosystem-ci-trigger.yml
Labels: team

#8775 feat: split big chunks based on modules path similarities
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/rspack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-4.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-4.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-4.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/test.config.js
Labels: release: feature

#8774 feat: add help message for version check
  packages/rspack/src/util/bindingVersionCheck.ts
Labels: release: feature

#8781 perf: parallelize side effects optimization
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/dependency/dependency_id.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: release: performance

#8766 fix: correct type for `loaderContext.importModule`
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#8794 ci: disable pkg preview
  .github/workflows/ci.yml
Labels: team

#8797 ci: disable miri, eco-ci and benchmark check
  .github/workflows/ci.yml
Labels: team

#8779 feat: splitChunks.cacheGroups.filename supports function
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/mod.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/a.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/b.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/common1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/common2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/common3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/rspack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/shared1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/shared2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: release: feature

#8810 ci: add @GiveMe-A-Name to team label
  .github/teams.yml
Labels: team

#8808 feat: bench js api by codspeed
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
  package.json
  packages/bench/README.md
  packages/bench/fixtures/ts-react/index.html
  packages/bench/fixtures/ts-react/rspack.config.ts
  packages/bench/fixtures/ts-react/src/App.css
  packages/bench/fixtures/ts-react/src/App.tsx
  packages/bench/fixtures/ts-react/src/assets/react.svg
  packages/bench/fixtures/ts-react/src/index.css
  packages/bench/fixtures/ts-react/src/index.tsx
  packages/bench/fixtures/ts-react/src/react-env.d.ts
  packages/bench/fixtures/ts-react/tsconfig.json
  packages/bench/package.json
  packages/bench/ts-react.bench.ts
  packages/bench/vitest.config.ts
  pnpm-lock.yaml
Labels: release: feature

#8813 fix: allow empty persistent cache options
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_experiments/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_experiments/raw_cache/mod.rs
Labels: release: bug fix

#8812 feat: support module graph connection js api
  .github/workflows/reusable-build.yml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/module_graph.rs
  crates/rspack_binding_values/src/module_graph_connection.rs
  packages/rspack-test-tools/tests/configCases/module-graph/get-exports-info/a.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-exports-info/b.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-exports-info/c.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-exports-info/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-exports-info/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-issuer/foo.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-issuer/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-issuer/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-module/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-outgoing-connections/foo.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-outgoing-connections/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-outgoing-connections/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ModuleGraph.ts
  packages/rspack/src/ModuleGraphConnection.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tests/bench/README.md
  tests/bench/fixtures/ts-react/index.html
  tests/bench/fixtures/ts-react/rspack.config.ts
  tests/bench/fixtures/ts-react/src/App.css
  tests/bench/fixtures/ts-react/src/App.tsx
  tests/bench/fixtures/ts-react/src/assets/react.svg
  tests/bench/fixtures/ts-react/src/index.css
  tests/bench/fixtures/ts-react/src/index.tsx
  tests/bench/fixtures/ts-react/src/react-env.d.ts
  tests/bench/fixtures/ts-react/tsconfig.json
  tests/bench/package.json
  tests/bench/ts-react.bench.ts
  tests/bench/vitest.config.ts
Labels: release: feature

#8821 docs: add `loaderContext.importModule()`
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: team, release: document

#8802 perf: improve FlagDependencyExportsPlugin for large JSON by depth
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_json/src/json_exports_dependency.rs
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  tests/webpack-test/configCases/json/bailout-flag-dep-export-perf/data.json
  tests/webpack-test/configCases/json/bailout-flag-dep-export-perf/index.js
  tests/webpack-test/configCases/json/bailout-flag-dep-export-perf/webpack.config.js
  tests/webpack-test/configCases/json/flag-dep-export-perf/data.json
  tests/webpack-test/configCases/json/flag-dep-export-perf/index.js
  tests/webpack-test/configCases/json/flag-dep-export-perf/webpack.config.js
Labels: release: performance

#8809 feat: support `match_when_empty` for rule condition
  crates/rspack_binding_values/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack-test-tools/tests/configCases/loader/match-when-empty/a.js
  packages/rspack-test-tools/tests/configCases/loader/match-when-empty/index.js
  packages/rspack-test-tools/tests/configCases/loader/match-when-empty/loader.js
  packages/rspack-test-tools/tests/configCases/loader/match-when-empty/rspack.config.js
Labels: release: feature

#8820 fix: use cgm hash to verify rename inline modules cache
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/foo.js
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/index.js
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/module.js
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/package.json
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/reexports-deep.js
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/reexports.js
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/1/module.js
  packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/rspack.config.js
Labels: release: bug fix

#8824 fix: Rspack cssParser will parse failed when url(' ')
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-url/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-url/index.js
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-url/style.css
Labels: release: bug fix

#8828 chore: split canary to separate scope
  .github/workflows/release-canary.yml
  scripts/release/version.mjs
Labels: team

#8826 docs: update output.clean type declaration
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: release: document

#8829 docs: add FAQ for SWC plugin version unmatched
  website/docs/en/errors/swc-plugin-version.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/errors/swc-plugin-version.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: document

#8001 fix(diagnostic): improve diagnostics for swc wasm plugins when mismatch
  Cargo.lock
  Cargo.toml
  crates/rspack_error/src/miette_helpers.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/build.rs
  crates/rspack_loader_swc/src/compiler.rs
  crates/rspack_loader_swc/src/lib.rs
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/errors.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/index.html
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/node_modules/swc-wasm-plugin/package.json
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/node_modules/swc-wasm-plugin/plugin.wasm
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/src/App.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/src/index.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/test.config.js
Labels: team, release: bug fix

#8803 fix!: handle glob patterns ending with /** in CopyRspackPlugin
  crates/rspack_plugin_copy/src/lib.rs
  tests/plugin-test/copy-plugin/CopyPlugin.test.js
Labels: release: bug fix

#8832 feat: add context info issuer layer for external function
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_external.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_plugin_externals/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/context-info/index.js
  packages/rspack-test-tools/tests/configCases/externals/context-info/other-layer.js
  packages/rspack-test-tools/tests/configCases/externals/context-info/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
Labels: team, release: feature

#8834 fix(exernals): add hash to distinguish conflict id
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/_a/foo.mjs
  packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/a/foo.mjs
  packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/index.js
  packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/test.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
Labels: team, release: bug fix

#8827 fix: importModule should receive error correctly
  crates/node_binding/binding.d.ts
  crates/node_binding/package.json
  crates/rspack_binding_values/src/compilation/mod.rs
  packages/rspack-test-tools/tests/configCases/loader-import-module/execute-failed/import-loader-2.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/execute-failed/import-loader.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/execute-failed/index.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/execute-failed/rspack.config.js
  packages/rspack/src/Compiler.ts
  packages/rspack/src/loader-runner/index.ts
Labels: release: bug fix

#8845 fix(rspack-test-tools): use `process.cwd()` when outside Rspack
  packages/rspack-test-tools/src/helper/expect/placeholder.ts
Labels: release: bug fix

#8848 perf(incremental): better parallel for side effects plugin rebuild
  crates/rspack_core/src/artifacts/side_effects_do_optimize_artifact.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: performance

#8852 chore: ignore style changes in git blame #8228
  .git-blame-ignore-revs
Labels: team

#8855 perf(cli): remove Node.js semver checker
  packages/rspack-cli/package.json
  packages/rspack-cli/src/cli.ts
  pnpm-lock.yaml
Labels: team, release: performance

#8856 perf(cli): lazy import rechoir and interpret
  packages/rspack-cli/src/utils/loadConfig.ts
Labels: team, release: performance

#8853 feat: set default SWC minimizer passes to `2` to reduce bundle size
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/configCases/plugins/minify-disable-minify/index.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/ids.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
Labels: team, release: feature

#8854 test: add cache test cases
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/cache.ts
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/helper/loaders/hot-update.ts
  packages/rspack-test-tools/src/helper/plugins/hot-update.ts
  packages/rspack-test-tools/src/helper/plugins/index.ts
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/src/processor/index.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/src/runner/index.ts
  packages/rspack-test-tools/tests/Cache.test.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/file.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/index.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/rspack.config.js
Labels: team

#8859 chore(deps): bump Rslib to v0.2.2
  packages/create-rspack/package.json
  packages/create-rspack/rslib.config.ts
  packages/rspack-cli/package.json
  packages/rspack-cli/rslib.config.ts
  packages/rspack-cli/src/utils/crossImport.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/src/utils/profile.ts
  pnpm-lock.yaml
Labels: team

#8860 test: split incremental test cases to run in parallel
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/tests/NewIncremental-node.test.js
  packages/rspack-test-tools/tests/NewIncremental-watch-webpack.test.js
  packages/rspack-test-tools/tests/NewIncremental-watch.test.js
  packages/rspack-test-tools/tests/NewIncremental-web.test.js
  packages/rspack-test-tools/tests/NewIncremental-webworker.test.js
  packages/rspack-test-tools/tests/NewIncremental.test.js
Labels: team

#8857 feat: initialize compiler options builder
  crates/rspack_core/src/options/compiler_options_builder.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/options/experiments/cache.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/options/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_core/src/options/target.rs
Labels: release: feature

#8847 feat(storage): improve storage memory
  crates/rspack_core/src/cache/persistent/storage/mod.rs
  crates/rspack_storage/src/pack/data/meta.rs
  crates/rspack_storage/src/pack/data/mod.rs
  crates/rspack_storage/src/pack/data/pack.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/manager/queue.rs
  crates/rspack_storage/src/pack/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/mod.rs
  crates/rspack_storage/src/pack/strategy/split/read_pack.rs
  crates/rspack_storage/src/pack/strategy/split/read_scope.rs
  crates/rspack_storage/src/pack/strategy/split/util.rs
  crates/rspack_storage/src/pack/strategy/split/validate_scope.rs
  crates/rspack_storage/src/pack/strategy/split/write_pack.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  crates/rspack_storage/tests/expire.rs
  crates/rspack_storage/tests/lock.rs
  crates/rspack_storage/tests/multi.rs
  crates/rspack_storage/tests/release.rs
Labels: team, release: feature

#8865 docs: add Google and DeepSeek to who is using
  website/theme/components/Landingpage/WhoIsUsing/assets/deepseek.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/google.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: team, release: document

#8863 test: refresh modified file mtime when run NEXT_START
  packages/rspack-test-tools/src/helper/util/refreshModifyTime.ts
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/index.js
Labels: team

#8866 fix(incremental): build chunk graph with runtime chunk true
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/chunk_group.rs
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/0/index.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/0/lib.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/1/index.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/2/index.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/test.config.js
Labels: team, release: bug fix

#8868 ci: add ecosystem benchmark
  .github/workflows/ecosystem-benchmark.yml
Labels: team

#8869 docs: make LoaderContext documentation more friendly
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: team, release: document

#8870 fix: persistent cache save ModuleArgumentDependency.id
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/tests/Cache.test.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/file.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/index.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/basic/rspack.config.js
Labels: team, release: bug fix

#8872 chore: update version to match the latest release
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#8871 fix(incremental): activate inactive module not codegen
  crates/rspack_ids/src/named_module_ids_plugin.rs
  packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/0/a.js
  packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/0/index.js
  packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/1/index.js
  packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/2/index.js
  packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/rspack.config.js
Labels: team, release: bug fix

#8862 fix: should recognize negative preload value
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack-test-tools/tests/configCases/web/fetch-priority-2/index.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#8778 fix: correct css modules hashing to match Webpack when leading digit #8735
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-6435-xxhash64/index.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-6435/index.js
  packages/rspack-test-tools/tests/configCases/mangle-exports/skipping-mangle-css-modules/index.js
  packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
Labels: release: bug fix

#8874 chore: add profile choice for release canary
  .github/workflows/release-canary.yml
  package.json
Labels: team

#8878 chore: change input_filesystem to ReadableFileSystem
  crates/node_binding/src/resolver_factory.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/cacheable_context.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_fs/src/fs.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_schemes/src/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri.rs
  crates/rspack_plugin_schemes/src/lockfile.rs
Labels: team

#8849 test: easier way to write hmr test cases
  packages/rspack-test-tools/src/helper/legacy/checkArrayExpectation.js
  packages/rspack-test-tools/src/helper/legacy/fake-update-loader.js
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/hash/hot-index/index.js
  packages/rspack-test-tools/tests/hotCases/recover/recover-after-self-error/__snapshots__/web/3.snap.txt
  packages/rspack-test-tools/tests/hotCases/runtime/dispose-removed-module/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/runtime/replace-runtime-module/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/runtime/require-disposed-module-warning/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/runtime/self-accept-factory/__snapshots__/web/1.snap.txt
Labels: team

#8880 fix: rspack_version macro support match alpha version
  crates/rspack_macros/src/rspack_version.rs
Labels: team, release: bug fix

#8883 fix: rspack_version macro use json to parse package.json
  Cargo.lock
  crates/rspack_macros/Cargo.toml
  crates/rspack_macros/src/rspack_version.rs
Labels: team, release: bug fix

#8886 docs: update persistent cache available version and configuration
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8885 ci: remove nightly release
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
Labels: team

#8884 fix: channal error when using sync externals function
  packages/rspack-test-tools/tests/configCases/externals/function-sync/index.js
  packages/rspack-test-tools/tests/configCases/externals/function-sync/inject.js
  packages/rspack-test-tools/tests/configCases/externals/function-sync/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#8889 fix: add stdout draw target to multi progress
  crates/rspack_plugin_progress/src/lib.rs
Labels: team, release: bug fix

#8888 fix: source-map-devtool-plugin file context option
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-file-context/index.js
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-file-context/rspack.config.js
Labels: team, release: bug fix

#8891 refactor(incremental): introduce mutation update module
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/incremental/mutations.rs
  crates/rspack_ids/src/named_module_ids_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team

#8892 docs: correct `avoidEntryIife` added version
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#8894 docs: persistent cache example set root.cache to true
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8890 test: add persistent cache test
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/tests/cacheCases/common/basic/file.js
  packages/rspack-test-tools/tests/cacheCases/common/basic/index.js
  packages/rspack-test-tools/tests/cacheCases/common/basic/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies/file.js
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies/index.js
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/common/version/file.js
  packages/rspack-test-tools/tests/cacheCases/common/version/index.js
  packages/rspack-test-tools/tests/cacheCases/common/version/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/immutable-paths/file.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/immutable-paths/index.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/immutable-paths/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/managed-paths/index.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/managed-paths/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/managed-paths/test_lib/file.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/managed-paths/test_lib/package.json
  packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/index.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/test_lib/changed.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/test_lib/file.js
  packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/test_lib/package.json
  packages/rspack-test-tools/tests/cacheCases/storage/directory/file.js
  packages/rspack-test-tools/tests/cacheCases/storage/directory/index.js
  packages/rspack-test-tools/tests/cacheCases/storage/directory/rspack.config.js
Labels: team

#8897 docs: fix typo in builtin-plugin.md
  website/docs/en/contribute/architecture/builtin-plugin.md
  website/docs/zh/contribute/architecture/builtin-plugin.md
Labels: release: document

#8898 docs: complete `WarnCaseSensitiveModulesPlugin`
  website/docs/en/plugins/webpack/warn-case-sensitive-modules-plugin.mdx
  website/docs/zh/plugins/webpack/warn-case-sensitive-modules-plugin.mdx
Labels: team, release: document

#8902 ci: fix ecosystem-benchmark test pr failed
  .github/workflows/ecosystem-benchmark.yml
Labels: team

#8893 feat: support set build info in js side
  packages/rspack-test-tools/tests/configCases/module/build-info/index.js
  packages/rspack-test-tools/tests/configCases/module/build-info/loader.js
  packages/rspack-test-tools/tests/configCases/module/build-info/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: feature

#8908 fix: transform nested webpack require with innerGraph enabled
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/index.js
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/lib.js
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/lib2.js
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/rspack.config.js
Labels: team, release: bug fix

#8909 refactor: better storage error format
  crates/rspack_storage/src/error.rs
  crates/rspack_storage/src/fs/error.rs
Labels: team
