Repository web-infra-dev/rspack, pull requests merged in 2024-09, with the labels that each got.

#7745 fix: add `in_function_scope` for getters and setters
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/normalCases/parsing/harmony-import-specifier/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/harmony-import-specifier/index.js
Labels: release: bug fix

#7755 docs: correct asset generator filename property type
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: document

#7756 docs: disable bundler info injection by set `force: false`
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#7760 chore: change security report email
  SECURITY.md
Labels: team

#7738 test: webpack test hot cases for new incremental
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/processor/hot-new-incremental.ts
  packages/rspack-test-tools/tests/NewIncremental.test.js
  tests/webpack-test/hotCases/child-compiler/issue-9706/report-child-assets-loader.js
  tests/webpack-test/hotCases/child-compiler/issue-9706/test.filter.js
  tests/webpack-test/hotCases/chunks/accept-system-import-webpackhot/test.filter.js
  tests/webpack-test/hotCases/chunks/accept-system-import/test.filter.js
  tests/webpack-test/hotCases/chunks/dynamic-system-import/test.filter.js
  tests/webpack-test/hotCases/chunks/system-import/test.filter.js
  tests/webpack-test/hotCases/code-generation/this-in-accept-webpackhot/test.filter.js
  tests/webpack-test/hotCases/code-generation/this-in-accept/test.filter.js
  tests/webpack-test/hotCases/concat/reload-compat-flag/test.filter.js
  tests/webpack-test/hotCases/concat/reload-external/test.filter.js
  tests/webpack-test/hotCases/determinism/issue-10174/test.filter.js
  tests/webpack-test/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/test.filter.js
  tests/webpack-test/hotCases/disposing/remove-chunk-with-shared/test.filter.js
  tests/webpack-test/hotCases/errors/decline-webpackhot/test.filter.js
  tests/webpack-test/hotCases/errors/decline/test.filter.js
  tests/webpack-test/hotCases/errors/events/test.filter.js
  tests/webpack-test/hotCases/errors/self-decline/test.filter.js
  tests/webpack-test/hotCases/errors/unaccepted-ignored/test.filter.js
  tests/webpack-test/hotCases/errors/unaccepted/test.filter.js
  tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/node_modules/dep1/exports.js
  tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/node_modules/dep1/file.js
  tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/node_modules/dep1/main.js
  tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/node_modules/dep1/package.json
  tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/test.filter.js
  tests/webpack-test/hotCases/esm-dependency-import/module-hot/node_modules/dep1/exports.js
  tests/webpack-test/hotCases/esm-dependency-import/module-hot/node_modules/dep1/file.js
  tests/webpack-test/hotCases/esm-dependency-import/module-hot/node_modules/dep1/main.js
  tests/webpack-test/hotCases/esm-dependency-import/module-hot/node_modules/dep1/package.json
  tests/webpack-test/hotCases/esm-dependency-import/module-hot/test.filter.js
  tests/webpack-test/hotCases/harmony/auto-import-default/test.filter.js
  tests/webpack-test/hotCases/harmony/auto-import-multiple/test.filter.js
  tests/webpack-test/hotCases/harmony/auto-import/test.filter.js
  tests/webpack-test/hotCases/harmony/auto-reexport/test.filter.js
  tests/webpack-test/hotCases/hashing/exports-info-influence/test.filter.js
  tests/webpack-test/hotCases/hashing/full-hash-main/test.filter.js
  tests/webpack-test/hotCases/invalidate/conditional-accept/test.filter.js
  tests/webpack-test/hotCases/invalidate/during-idle/test.filter.js
  tests/webpack-test/hotCases/numeric-ids/production/test.filter.js
  tests/webpack-test/hotCases/parsing/hot-api-optional-chaining/test.filter.js
  tests/webpack-test/hotCases/runtime/accept/test.filter.js
  tests/webpack-test/hotCases/runtime/bubble-async/test.filter.js
  tests/webpack-test/hotCases/runtime/bubble-update/test.filter.js
  tests/webpack-test/hotCases/runtime/circular/test.filter.js
  tests/webpack-test/hotCases/runtime/dispose-removed-chunk/test.filter.js
  tests/webpack-test/hotCases/runtime/dispose-removed-module/test.filter.js
  tests/webpack-test/hotCases/runtime/import-after-download/test.filter.js
  tests/webpack-test/hotCases/runtime/replace-runtime-module/test.filter.js
  tests/webpack-test/hotCases/runtime/require-disposed-module-warning/test.filter.js
  tests/webpack-test/hotCases/runtime/self-accept-and-dispose/test.filter.js
  tests/webpack-test/hotCases/runtime/self-accept-factory/test.filter.js
  tests/webpack-test/hotCases/runtime/update-multiple-modules/test.filter.js
  tests/webpack-test/hotCases/runtime/update-multiple-times/test.filter.js
  tests/webpack-test/hotCases/sharing/share-plugin/test.filter.js
  tests/webpack-test/hotCases/status/accept/test.filter.js
  tests/webpack-test/hotCases/status/check/test.filter.js
  tests/webpack-test/hotCases/unexpected-invalidation/used-exports/test.filter.js
Labels: team

#7743 fix: escape css ident
  crates/rspack_plugin_css/src/dependency/local_ident.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/css/escape-ident/index.js
  packages/rspack-test-tools/tests/configCases/css/escape-ident/index.module.css
  packages/rspack-test-tools/tests/configCases/css/escape-ident/rspack.config.js
Labels: release: bug fix

#7767 fix: handle ASI for export declaration
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  tests/webpack-test/cases/parsing/harmony-export-import-specifier-asi/a.js
  tests/webpack-test/cases/parsing/harmony-export-import-specifier-asi/index.js
  tests/webpack-test/cases/parsing/harmony-export-specifier-asi/a.js
  tests/webpack-test/cases/parsing/harmony-export-specifier-asi/index.js
Labels: release: bug fix

#7739 perf: source map dev tool plugin
  crates/rspack_plugin_devtool/src/module_filename_helpers.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
Labels: team, release: performance

#7771 docs(deps): upgrade @rstack-dev/doc-ui 1.4.2
  website/package.json
  website/pnpm-lock.yaml
Labels: release: document

#7772 ci: test case have node_modules wrong
  .github/workflows/reusable-build.yml
Labels: team

#7770 docs: Update asset-module.mdx
  website/docs/en/guide/features/asset-module.mdx
  website/docs/zh/guide/features/asset-module.mdx
Labels: release: document

#7784 fix(dev-server): pin webpack-dev-server version
  packages/playground/package.json
  packages/rspack-dev-server/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
  tests/webpack-test/package.json
Labels: team, release: bug fix

#7775 docs: fix migrate-from-builtins.css example codes
  website/docs/zh/blog/announcing-0-6.mdx
Labels: release: document

#7776 feat: support `compilation.chunkGroups[].origins`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_group.rs
  packages/rspack-test-tools/tests/configCases/plugins/compilation-chunk-groups/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/ChunkGroup.ts
  website/docs/en/types/chunk-group.mdx
  website/docs/en/types/entrypoint.mdx
  website/docs/zh/types/chunk-group.mdx
  website/docs/zh/types/entrypoint.mdx
Labels: team, release: feature

#7761 fix(make): isolated module clean incomplete
  crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/mod.rs
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/a.js
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/b.js
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/c.js
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/index.js
  packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/rspack.config.js
Labels: team, release: bug fix

#7774 perf(buildChunkGraph): avoid unneeded visit
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: performance

#7790 chore: cleanup unused module syntax
  crates/rspack_core/src/module_graph/module.rs
  crates/rspack_core/src/normal_module.rs
Labels: team

#7791 fix: cheap source map
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#7793 docs: update html plugin
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
  website/project-words.txt
Labels: team, release: document

#7799 fix: panic when identity mapping with different char indices
  Cargo.lock
  Cargo.toml
  packages/rspack-cli/package.json
Labels: team, release: bug fix

#7803 fix(core): try fix EBUSY problem in windows ci
  package.json
  packages/rspack-cli/package.json
  patches/graceful-fs@4.2.10.patch
  pnpm-lock.yaml
Labels: team, release: bug fix

#7744 fix(core): fix resolve faild when do recursive symbol link
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/.gitignore
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/index.js
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/package.json
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/app/index.js
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/app/package.json
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/lib/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: team, release: bug fix

#7792 fix: overflow panic when shifting left value greater then 31
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-if-binary/index.js
Labels: team, release: bug fix

#7299 ci: clean node_modules and target
  .github/actions/clean/action.yml
  .github/workflows/reusable-build.yml
Labels: team

#7759 feat(modern-module): make dynamic import runtime-less
  Cargo.lock
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_library/src/modern_module/dependency.rs
  crates/rspack_plugin_library/src/modern_module/mod.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/dyn.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/main.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/test.config.js
Labels: release: feature

#7815 docs: add tip for import.meta.webpackContext literal
  website/docs/en/api/runtime-api/module-methods.mdx
  website/docs/en/api/runtime-api/module-variables.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/api/runtime-api/module-variables.mdx
Labels: team, release: document

#7810 fix: remove HotUpdateChunk in chunks
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_hmr/src/lib.rs
  packages/rspack-test-tools/tests/hotCases/stats/chunks/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/stats/chunks/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/stats/chunks/file.js
  packages/rspack-test-tools/tests/hotCases/stats/chunks/index.js
  packages/rspack-test-tools/tests/hotCases/stats/chunks/rspack.config.js
Labels: team, release: bug fix

#7820 docs: fix typo in zh docs
  website/docs/zh/api/javascript-api/index.mdx
Labels: team, release: document

#7817 feat(core): use dyn output_filesystem
  crates/node_binding/src/compiler.rs
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  packages/rspack-cli/jest.config.js
Labels: team, release: feature

#7821 fix: should not transform source to buffer
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin/index.js
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin/test.config.js
Labels: team, release: bug fix

#7812 fix: change javascript parser options in child compiler
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_util/src/merge.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/module/change-parser-in-child-compiler/child-entry.js
  packages/rspack-test-tools/tests/configCases/module/change-parser-in-child-compiler/img.png
  packages/rspack-test-tools/tests/configCases/module/change-parser-in-child-compiler/index.js
  packages/rspack-test-tools/tests/configCases/module/change-parser-in-child-compiler/rspack.config.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
Labels: team, release: bug fix

#7818 fix(loader-runner): remove legacy Node compatible code
  packages/rspack/src/loader-runner/loadLoader.ts
Labels: team, release: bug fix

#7823 fix: improve stats string for match resource with long data url
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsOutputCases/match-resource-data-url/index.js
  packages/rspack-test-tools/tests/statsOutputCases/match-resource-data-url/rspack.config.js
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
Labels: team, release: bug fix

#7825 chore(workflow): correct rspack action scope
  .github/workflows/release-pull-request.yml
Labels: team

#7841 feat: remove `ErrorSpan` in dependency trait
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_extract_css/src/parser_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_library/src/modern_module/dependency.rs
Labels: release: feature

#7832 feat: support context for resolve and resolveWeak
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/mod.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_resolve_context_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  tests/webpack-test/cases/chunks/weak-dependencies-context/index.js
  tests/webpack-test/cases/chunks/weak-dependencies-context/test.filter.js
  tests/webpack-test/cases/parsing/complex-require/cjs.js
  tests/webpack-test/cases/parsing/resolve-weak-context/test.filter.js
Labels: release: feature

#7847 fix: duplicate emit source map from child compiler
  crates/rspack_plugin_devtool/src/mapped_assets_cache.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_resolve_context_dependency.rs
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-child-compiler/child.js
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-child-compiler/index.js
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-child-compiler/rspack.config.js
Labels: team, release: bug fix

#7840 feat: make namedChunkGroups iterable
  packages/rspack-test-tools/tests/configCases/plugins/compilation-chunk-groups/rspack.config.js
  packages/rspack/src/Compilation.ts
  packages/rspack/src/util/createReadonlyMap.ts
Labels: release: feature

#7846 fix: loader intermediate data should be overridden between loaders
  .vscode/settings.json
  crates/rspack_binding_options/src/plugins/css_extract_additional_data.rs
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
  crates/rspack_binding_options/src/plugins/js_loader/scheduler.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_loader_lightningcss/src/lib.rs
  crates/rspack_loader_preact_refresh/src/lib.rs
  crates/rspack_loader_react_refresh/src/lib.rs
  crates/rspack_loader_runner/src/context.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_testing/src/lib.rs
  crates/rspack_plugin_extract_css/src/parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/wth-css-extract-postcss/index.css
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/wth-css-extract-postcss/index.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/wth-css-extract-postcss/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-no-passthrough/a.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-no-passthrough/index.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-no-passthrough/loader-1.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-no-passthrough/loader-2.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-no-passthrough/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-passthrough/a.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-passthrough/index.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-passthrough/loader-1.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-passthrough/loader-2.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-passthrough/rspack.config.js
  scripts/debug/launch.mjs
Labels: team, release: bug fix

#7851 ci: disable dev server test cases
  .github/workflows/reusable-build.yml
  packages/rspack-dev-server/jest.config.js
Labels: team

#7856 docs: add NIO logo at built with rspack
  website/theme/components/Landingpage/BuiltWithRspack/assets/nio.svg
  website/theme/components/Landingpage/BuiltWithRspack/index.tsx
Labels: release: document

#7857 ci: remove firefox
  .github/workflows/reusable-build.yml
Labels: team

#7855 docs: add clarification to loader `this.callback` usage
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: team, release: document

#7836 fix(external_module): use "const" if supported when concatenation
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
Labels: release: bug fix

#7854 fix(create-rspack): eslint-plugin-react-hooks version conflict
  packages/create-rspack/package.json
  packages/create-rspack/src/index.ts
  pnpm-lock.yaml
Labels: team, release: bug fix

#7861 test(dev-server): enable dev server test cases
  packages/rspack-dev-server/jest.config.js
  packages/rspack-dev-server/package.json
Labels: team

#7863 docs: remove disableTransformByDefault
  website/docs/en/config/module.mdx
  website/docs/en/guide/tech/react.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/tech/react.mdx
Labels: team, release: document

#7811 fix: remove LightningCssMinimizerRspackPlugin exclude option default value
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts
Labels: release: bug fix

#7866 fix: trusted type with devtool eval
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/worker/create_script_url_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack-dev-server/tests/e2e/__snapshots__/overlay.test.js.snap.webpack5
  packages/rspack-dev-server/tests/e2e/overlay.test.js
  tests/webpack-test/configCases/trusted-types/devtool-eval/test.filter.js
  tests/webpack-test/configCases/trusted-types/web-worker/test.filter.js
Labels: team, release: bug fix

#7865 fix: do not use affected for side-effects-flag-plugin
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/foo.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/index.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/module.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/package.json
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/reexports-deep.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/reexports.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/rspack.config.js
Labels: team, release: bug fix

#7872 fix: should forward sourcemaps for refresh loaders
  crates/rspack_loader_preact_refresh/src/lib.rs
  crates/rspack_loader_react_refresh/src/lib.rs
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/preact-refresh/index.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/preact-refresh/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/react-refresh/index.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/react-refresh/rspack.config.js
  pnpm-lock.yaml
Labels: team, release: bug fix

#7867 fix: should provide full error message with error name when `hideStack` is set to `true`
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/lib.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/my-loader.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/lib.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/lib.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/my-loader.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/stats.err
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/index.ts
  tests/plugin-test/css-extract/cases/build-in-css-support/warnings.js
Labels: team, release: bug fix

#7876 docs: add `sources` JavaScript API
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/en/api/javascript-api/index.mdx
  website/docs/zh/api/javascript-api/compiler.mdx
  website/docs/zh/api/javascript-api/index.mdx
Labels: team, release: document

#7877 test: disable unstable dev server snapshot case
  packages/rspack-dev-server/tests/e2e/__snapshots__/api.test.js.snap.webpack5
  packages/rspack-dev-server/tests/e2e/api.test.js
  packages/rspack-dev-server/tests/e2e/web-socket-server-url.test.js
  packages/rspack-dev-server/tests/fixtures/reload-config/main.css
Labels: team

#7878 refactor: css-extract using parseMeta to store css info
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/plugins/css_extract_additional_data.rs
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_options/src/plugins/js_loader/scheduler.rs
  crates/rspack_binding_options/src/plugins/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_loader_runner/src/context.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_extract_css/src/lib.rs
  crates/rspack_plugin_extract_css/src/parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
  tests/plugin-test/copy-plugin/build/main.js
  tests/plugin-test/css-extract/cases/custom-loader/expected/main.css
  tests/plugin-test/css-extract/cases/custom-loader/index.js
  tests/plugin-test/css-extract/cases/custom-loader/loader.js
  tests/plugin-test/css-extract/cases/custom-loader/style.css
  tests/plugin-test/css-extract/cases/custom-loader/webpack.config.js
Labels: team

#7881 docs: update slogan for who is using
  website/theme/components/Landingpage/WhoIsUsing/assets/amazon.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/bit.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/bytedance.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/discord.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/intuit.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/microsoft.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/nio.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
  website/theme/components/Landingpage/index.tsx
  website/theme/i18n/enUS.ts
  website/theme/i18n/zhCN.ts
Labels: team, release: document

#7880 docs: add ABB logo at built with rspack
  website/theme/components/Landingpage/WhoIsUsing/assets/abb.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: release: document

#7882 docs: add sequoia logo at who is using
  website/theme/components/Landingpage/WhoIsUsing/assets/sequoia.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: release: document

#7883 docs: add getaround logo at who is using
  website/theme/components/Landingpage/WhoIsUsing/assets/getaround.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: release: document

#7871 feat(rspack_plugin_javascript): improve provide dependency
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/provide_plugin.rs
Labels: release: feature

#7894 fix(rspack-test-tools): corret script `testu`
  packages/rspack-test-tools/package.json
Labels: release: bug fix

#7896 feat(progress-plugin): support custom handler
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_progress.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack-dev-server/jest.config.js
  packages/rspack-dev-server/src/server.ts
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/ProgressPlugin.ts
Labels: team, release: feature

#7899 docs(landingpage): update @rstack-dev/doc-ui to 1.5.1
  website/package.json
  website/pnpm-lock.yaml
  website/theme/components/Announcement/close.tsx
  website/theme/components/Announcement/index.module.scss
  website/theme/components/Announcement/index.tsx
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
  website/theme/index.tsx
  website/theme/pages/index.tsx
Labels: release: document

#7900 docs: update node version and webpack-dev-server@5
  website/docs/en/guide/features/dev-server.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/features/dev-server.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: document

#7897 fix: should run watch cases test in build assets
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/runner/runner/watch.ts
  packages/rspack-test-tools/tests/NewIncremental.test.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/index.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization-for-inaffected-module/module.js
  packages/rspack-test-tools/tests/watchCases/compiler/multiply-compiler/0/entry1.js
  packages/rspack-test-tools/tests/watchCases/compiler/multiply-compiler/0/entry2.js
  packages/rspack-test-tools/tests/watchCases/compiler/multiply-compiler/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/compiler/multiply-compiler/test.config.js
  packages/rspack-test-tools/tests/watchCases/context/out-of-context/test.config.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/0/foo.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/0/index.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/0/module.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/0/package.json
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/0/reexports-deep.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/0/reexports.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/1/module.js
  packages/rspack-test-tools/tests/watchCases/side-effects/basic/rspack.config.js
Labels: team, release: bug fix

#7895 feat: allow ModuleFactoryCreateData modify dependencies
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_lazy_compilation/src/dependency.rs
  crates/rspack_plugin_lazy_compilation/src/factory.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module_factory.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/container/fallback_module_factory.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs
Labels: team, release: feature

#7904 docs: update how to use swc plugin in rspack rule
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: release: document

#7901 docs: add Trellis logo at who is using rspack
  website/theme/components/Landingpage/WhoIsUsing/assets/trellis.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: release: document

#7909 docs(landingpage): update @rstack-dev/doc-ui
  website/package.json
  website/pnpm-lock.yaml
Labels: release: document

#7911 fix(core): use resource shouldn't contain query
  crates/rspack_core/src/normal_module_factory.rs
Labels: team, release: bug fix

#7903 fix: preserve variable names declared with `var`
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/normalCases/parsing/harmony-import-specifier/index.js
Labels: release: bug fix

#7828 fix: use SourceMapSource in js side to support map method
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/source.rs
  crates/rspack_binding_values/src/stats.rs
  packages/rspack-test-tools/tests/configCases/asset/webpack-sources/img.png
  packages/rspack-test-tools/tests/configCases/asset/webpack-sources/index.js
  packages/rspack-test-tools/tests/configCases/asset/webpack-sources/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/util/source.ts
Labels: team, release: bug fix

#7839 fix: avoid import external module re-assigin in concatenation
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/helper/read-config-file.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/externals/m.mjs
  packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/index.js
  packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/test.config.js
  packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/consume.js
  packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/index.js
  packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/test.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
Labels: release: bug fix

#7920 fix: make stage has_module_graph_change calculate incorrectly
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
Labels: team, release: bug fix

#7924 fix(core): align assetInfo with webpack
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
  crates/rspack_plugin_size_limits/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
Labels: team, release: bug fix

#7777 fix: should create an empty codegen result for module that has failure in codegen
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/foo.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/stats.err
Labels: team, release: bug fix

#7929 test: disable dev server e2e test
  packages/rspack-dev-server/jest.config.js
Labels: team

#7917 feat: support `compilation.hooks.runtimeRequirementInTree`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/runtime.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_plugin.rs
  crates/rspack_plugin_runtime/src/bundler_info.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  crates/rspack_plugin_wasm/src/loading_plugin.rs
  packages/rspack-test-tools/tests/configCases/hooks/runtime-requirement-in-tree/index.js
  packages/rspack-test-tools/tests/configCases/hooks/runtime-requirement-in-tree/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team, release: feature

#7879 feat: support experimental loader `emitDiagnostic`
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/diagnostic.rs
  crates/node_binding/src/lib.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/rspack_error.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/location.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/basic.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/lib.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/with-file.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/with-help.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/with-location.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/with-multi-byte-char.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/with-multiple-line.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/RspackError.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
  x.mjs
Labels: team, release: feature

#7925 feat: support `compilation.addRuntimeModule`
  .vscode/settings.json
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module_from_js.rs
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-isolate/index.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-isolate/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-stage/index.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-stage/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/a.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/b.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/c.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/index.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Chunk.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/RuntimeModule.ts
  packages/rspack/src/exports.ts
Labels: team, release: feature

#7853 feat: context repl plugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/plugins/context_replacement.rs
  crates/rspack_binding_options/src/plugins/mod.rs
  crates/rspack_binding_values/src/context_module_factory.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_dependency.rs
  crates/rspack_macros/src/plugin.rs
  crates/rspack_plugin_context_replacement/Cargo.toml
  crates/rspack_plugin_context_replacement/src/lib.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_ignore/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_resolve_context_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/builtin-plugin/ContextReplacementPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  tests/webpack-test/configCases/context-replacement/System.import/test.filter.js
  tests/webpack-test/configCases/context-replacement/a/new-context/node_modules/error.js
  tests/webpack-test/configCases/context-replacement/a/new-context/node_modules/replaced.js
  tests/webpack-test/configCases/context-replacement/a/test.filter.js
  tests/webpack-test/configCases/context-replacement/b/test.filter.js
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/context-replacement-plugin.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/context-replacement-plugin.mdx
Labels: team, release: feature

#7933 fix: eco-ci prebundled enhanced-resolve
  packages/rspack/src/node/NodeEnvironmentPlugin.ts
Labels: release: bug fix

#7935 fix: attach when add runtime module
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/RuntimeModule.ts
Labels: team, release: bug fix

#7858 feat(core): integrate rspack_resolver with input_filesystem
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/src/lib.rs
  crates/node_binding/src/resolver_factory.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/error.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/native.rs
  crates/rspack_fs/src/sync.rs
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_fs_node/src/lib.rs
  crates/rspack_fs_node/src/node.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team, release: feature

#7948 docs: update who is using
  website/project-words.txt
  website/theme/components/Landingpage/WhoIsUsing/assets/abb.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/alibaba.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/amazon.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/bit.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/bytedance.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/discord.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/intuit.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/microsoft.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/sequoia.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/tiktok.svg
  website/theme/components/Landingpage/WhoIsUsing/assets/trellis.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: team, release: document

#7945 feat(core): support using tokio-console
  .cargo/config.toml
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/rspack_tracing/Cargo.toml
  crates/rspack_tracing/src/lib.rs
  justfile
Labels: team, release: feature

#7947 docs: fix link is 404 in README
  README.md
  README.zh-CN.md
Labels: release: document

#7946 fix: change javascript parser options to properly merge
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
Labels: release: bug fix

#7950 chore(workflow): remove rangeStrategy from renovate config
  .github/renovate.json5
Labels: team

#7951 docs: add use case for `extensionAlias`
  website/docs/en/config/resolve.mdx
  website/docs/zh/config/resolve.mdx
Labels: team, release: document

#7931 docs(website): update blog credit
  website/docs/en/blog/announcing-1-0.mdx
  website/docs/zh/blog/announcing-1-0.mdx
  website/project-words.txt
Labels: release: document

#7955 test: fix css concat stats test
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsOutputCases/css-concat/foo.css
  packages/rspack-test-tools/tests/statsOutputCases/css-concat/index.js
  packages/rspack-test-tools/tests/statsOutputCases/css-concat/rspack.config.js
Labels: team

#7953 docs: webpack-merge also applies to rspack
  website/docs/en/config/index.mdx
  website/docs/zh/config/index.mdx
Labels: release: document

#7954 refactor: phases level switcher for incremental options
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/unaffected_cache/mutations.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/processor/hot-new-incremental.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/etc/api.md
  packages/rspack/scripts/check-documentation-coverage.mjs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
Labels: team

#7938 docs: addRuntimeModule and runtimeRequirementInTree
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/javascript-api/compilation.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
Labels: team, release: document

#7963 perf: lazy require `browserslist` package
  packages/rspack/src/config/browserslistTargetHandler.ts
Labels: team, release: performance

#7969 fix(core): ping @rspack/dev-server to 1.0.5
  packages/playground/package.json
  packages/rspack-cli/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#7970 fix(create-rspack): missing vanilla-ts tsconfig.json
  packages/create-rspack/template-vanilla-ts/tsconfig.json
Labels: team, release: bug fix

#7964 chore: not allow run typecheck when run node bin/rspack for other project
  packages/rspack-cli/tsconfig.json
Labels: team

#7966 refactor(core): add task name for tokio-console better display
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team

#7982 refactor(core): use separate tokio_console layer
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_tracing/src/lib.rs
  packages/rspack-cli/src/utils/profile.ts
Labels: team

#7983 chore: fix proxied typo
  packages/rspack/src/Compilation.ts
Labels: team

#7961 perf: lazy create hash utils
  packages/rspack/src/util/hash/md4.ts
  packages/rspack/src/util/hash/wasm-hash.ts
  packages/rspack/src/util/hash/xxhash64.ts
Labels: team, release: performance

#7984 feat: support `compilation.builtModules`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/mod.rs
  packages/rspack-test-tools/tests/watchCases/compilation/built-modules/0/foo.js
  packages/rspack-test-tools/tests/watchCases/compilation/built-modules/0/index.js
  packages/rspack-test-tools/tests/watchCases/compilation/built-modules/1/foo.js
  packages/rspack-test-tools/tests/watchCases/compilation/built-modules/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/zh/api/javascript-api/compilation.mdx
Labels: team, release: feature

#7990 fix: the progress values for the make and sealing statuses are inaccurate
  crates/rspack_plugin_progress/src/lib.rs
Labels: release: bug fix

#7989 fix: correctly display the progress bar when it reaches 100%
  crates/rspack_plugin_progress/src/lib.rs
Labels: release: bug fix

#7997 revert: refactor(core) add task name for tokio-console better display
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team

#7998 docs: update team members, add @shulaoda
  website/components/RandomMemberList.tsx
  website/docs/en/misc/team/core-team.mdx
  website/docs/zh/misc/team/core-team.mdx
  website/project-words.txt
Labels: team, release: document

#7991 fix: swc minifier source map
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-binding/errors.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-binding/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lexically_name_error/stats.err
Labels: team, release: bug fix

#7994 docs: add ReleaseV1Announcement to 0.x
  .typos.toml
  packages/rspack/src/Compilation.ts
  website/theme/components/Announcement/close.tsx
  website/theme/components/Announcement/index.module.scss
  website/theme/components/Announcement/index.tsx
  website/theme/index.tsx
Labels: release: document

#8000 fix: generate params of runtime module
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-isolate/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-stage/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/RuntimeModule.ts
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/javascript-api/compilation.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
Labels: team, release: bug fix

#7996 fix(modern-module): use module style export for non entry module
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/0-create-library/modern-module-non-entry-module-export/bar.js
  packages/rspack-test-tools/tests/configCases/library/0-create-library/modern-module-non-entry-module-export/baz.js
  packages/rspack-test-tools/tests/configCases/library/0-create-library/modern-module-non-entry-module-export/index.js
  packages/rspack-test-tools/tests/configCases/library/0-create-library/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/0-create-library/test.config.js
  packages/rspack-test-tools/tests/configCases/library/1-use-library/default-test.js
  packages/rspack-test-tools/tests/configCases/library/1-use-library/node_modules/external.js
  packages/rspack-test-tools/tests/configCases/library/1-use-library/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/1-use-library/test.config.js
  packages/rspack-test-tools/tests/configCases/library/_0-create-library/a.js
  packages/rspack-test-tools/tests/configCases/library/_0-create-library/index.js
  packages/rspack-test-tools/tests/configCases/library/_0-create-library/nested.js
  packages/rspack-test-tools/tests/configCases/library/_0-create-library/non-external.js
  packages/rspack-test-tools/tests/configCases/library/_0-create-library/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/_1-use-library/default-test.js
  packages/rspack-test-tools/tests/configCases/library/_1-use-library/index.js
  packages/rspack-test-tools/tests/configCases/library/_1-use-library/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/_1-use-library/this-test.js
  packages/rspack-test-tools/tests/configCases/library/_1-use-library/var-test.js
Labels: release: bug fix

#8002 fix: dedup asset_contents to avoid multiple hash changes
  crates/rspack_plugin_real_content_hash/src/lib.rs
  packages/rspack-test-tools/tests/hashCases/issue-7992/rspack.config.js
  packages/rspack-test-tools/tests/hashCases/issue-7992/src/file1.svg
  packages/rspack-test-tools/tests/hashCases/issue-7992/src/file2.svg
  packages/rspack-test-tools/tests/hashCases/issue-7992/src/index.js
  packages/rspack-test-tools/tests/hashCases/issue-7992/test.config.js
Labels: release: bug fix

#8009 fix(core): allow non-utf8 string in source code
  crates/rspack_loader_swc/src/lib.rs
  packages/rspack-test-tools/tests/builtinCases/swc-loader/issue-8006/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/swc-loader/issue-8006/index.js
  packages/rspack-test-tools/tests/builtinCases/swc-loader/issue-8006/rspack.config.js
Labels: team, release: bug fix

#8012 docs: upgrade breaking change description
  website/docs/en/blog/announcing-1-0.mdx
  website/docs/zh/blog/announcing-1-0.mdx
Labels: team, release: document

#8014 docs(progress-plugin): support custom handler
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/plugins/webpack/progress-plugin.mdx
  website/docs/zh/blog/announcing-1-0.mdx
  website/docs/zh/plugins/webpack/progress-plugin.mdx
Labels: team, release: document

#8020 chore: update teams.yml
  .github/teams.yml
Labels: team

#8030 test: try to fix the randomly failed of @rspack/cli test cases
  packages/rspack-cli/tests/build/issue-6359/index.test.ts
  packages/rspack-cli/tests/build/issue-6359/rspack.config.js
Labels: team
