Repository web-infra-dev/rspack, pull requests merged in 2024-10, with the labels that each got.

#7999 fix(externals): distinguish "module" and "import" in "module-import"
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/builtinCases/samples/cycle-entry/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/samples/self-import/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/webpack-inner-graph-switch/__snapshots__/treeshaking.snap.txt
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/configCases/externals/module-import/a.js
  tests/webpack-test/configCases/externals/module-import/index.js
Labels: release: bug fix

#8063 chore(deps): update playwright to 1.47.0
  .github/renovate.json5
  .github/workflows/reusable-build.yml
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team

#8062 fix: should set code generation hash to concatenated module
  crates/rspack_core/src/concatenated_module.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/app.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/m1.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/m2.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/main.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/mock-loader.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/rspack.config.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/test.confg.js
Labels: team, release: bug fix

#8032 fix: should use chunk in path data of `compilation.getPath`
  Cargo.lock
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/path_data.rs
  packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/index.js
  packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/test.config.js
  packages/rspack-test-tools/tests/configCases/hooks/get-path-existing-chunk/index.js
  packages/rspack-test-tools/tests/configCases/hooks/get-path-existing-chunk/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/get-path-existing-chunk/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Chunk.ts
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#8071 fix(type): be compitable to ts5.6
  packages/rspack/src/Compilation.ts
Labels: team

#7939 feat(parser): add new javascript parser options
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/parsing/import-dynamic/index.js
  packages/rspack-test-tools/tests/configCases/parsing/import-dynamic/other.js
  packages/rspack-test-tools/tests/configCases/parsing/import-dynamic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/import-dynamic/test.config.js
  packages/rspack-test-tools/tests/configCases/parsing/import-dynamic/test.js
  packages/rspack-test-tools/tests/configCases/parsing/require-as-expression/index.js
  packages/rspack-test-tools/tests/configCases/parsing/require-as-expression/other.js
  packages/rspack-test-tools/tests/configCases/parsing/require-as-expression/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/require-as-expression/test.config.js
  packages/rspack-test-tools/tests/configCases/parsing/require-as-expression/test.js
  packages/rspack-test-tools/tests/configCases/parsing/require-dynamic/index.js
  packages/rspack-test-tools/tests/configCases/parsing/require-dynamic/other.js
  packages/rspack-test-tools/tests/configCases/parsing/require-dynamic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/require-dynamic/test.config.js
  packages/rspack-test-tools/tests/configCases/parsing/require-dynamic/test.js
  packages/rspack-test-tools/tests/configCases/parsing/require-resolve/index.js
  packages/rspack-test-tools/tests/configCases/parsing/require-resolve/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/require-resolve/test.config.js
  packages/rspack-test-tools/tests/configCases/parsing/require-resolve/test.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  tests/plugin-test/copy-plugin/build/main.js
Labels: release: feature

#7968 fix: the value of this.sourceMap in LoaderContext is incorrect when using SourceMapDevToolPlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/loader/loader_runner.rs
  packages/rspack-test-tools/tests/configCases/source-map/custom-loader/index.js
  packages/rspack-test-tools/tests/configCases/source-map/custom-loader/loader.js
  packages/rspack-test-tools/tests/configCases/source-map/custom-loader/rspack.config.js
  packages/rspack/src/loader-runner/index.ts
Labels: release: bug fix

#8080 fix: source map is not works with Sentry
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#8069 fix: allow file names and directory names to contain brackets
  crates/rspack_plugin_copy/src/lib.rs
  tests/plugin-test/copy-plugin/CopyPlugin.test.js
  tests/plugin-test/copy-plugin/fixtures/directory[1]/file[1].txt
  tests/plugin-test/copy-plugin/fixtures/file[1].txt
Labels: release: bug fix

#7949 feat: support dependencies in resolve hook callback
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/entries.rs
  crates/rspack_binding_values/src/context_module_factory.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/module.rs
  packages/rspack-test-tools/tests/configCases/hooks/context-module-before-resolve/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/DependenciesBlock.ts
  packages/rspack/src/Dependency.ts
  packages/rspack/src/Module.ts
Labels: team, release: feature

#7008 feat(rspack_plugin_schemas): http import schema plugin
  Cargo.lock
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/src/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri.rs
  crates/rspack_plugin_schemes/src/lib.rs
  crates/rspack_plugin_schemes/src/lockfile.rs
Labels: release: feature

#8086 test: disable unstable test case of rspack-cli
  packages/rspack-cli/tests/build/issue-6359/index.test.ts
Labels: team

#8083 chore: polish CSS HMR logs and correct the case
  crates/rspack_plugin_css/webpack_css_cases_to_be_migrated/hmr/expected/main.js
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.ts
  tests/plugin-test/css-extract/__snapshots__/HMR.test.js.snap
  tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js
  tests/plugin-test/css-extract/cases/hmr/expected/main.js
Labels: team

#8046 fix: avoid renaming the export name when outputting a library
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/rspack-issue-8045/index.js
  packages/rspack-test-tools/tests/configCases/library/rspack-issue-8045/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/rspack-issue-8045/test.config.js
Labels: release: bug fix

#8091 fix(ci/preview-commit): remove predicate-quantifier
  .github/workflows/preview-commit.yml
Labels: release: bug fix

#8088 fix: return url in CreateScriptUrlRuntimeModule
  crates/rspack_plugin_runtime/src/runtime_module/create_script_url.rs
  packages/rspack-test-tools/src/compare/replace-runtime-module-name.ts
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url#with-trusted-types/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url#with-trusted-types/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url#with-trusted-types/src/module.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url#with-trusted-types/src/worker.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url#with-trusted-types/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url#with-trusted-types/webpack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url/src/module.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url/src/worker.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/create-script-url/webpack.config.js
Labels: team, release: bug fix

#8089 refactor: remove connection id
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/unaffected_cache/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team

#8072 perf: bundle `@rspack/core` for faster startup
  .github/workflows/reusable-build.yml
  biome.jsonc
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/package.json
  packages/rspack/prebundle.config.mjs
  packages/rspack/scripts/prepare-container-runtime.js
  packages/rspack/src/builtin-plugin/css-extract/hmr/normalizeUrl.ts
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/css-extract/utils.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/runtime/cssExtractHmr.ts
  packages/rspack/src/runtime/moduleFederationDefaultRuntime.js
  packages/rspack/tsconfig.build.json
  packages/rspack/tsconfig.json
  packages/rspack/tsup.config.ts
  pnpm-lock.yaml
  tests/plugin-test/copy-plugin/build/main.js
  tests/plugin-test/css-extract/HMR.test.js
  tests/plugin-test/css-extract/__snapshots__/HMR.test.js.snap
  tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js
  tests/plugin-test/css-extract/cases/hmr/expected/main.js
  tests/plugin-test/css-extract/normalizeUrl.test.js
  tests/plugin-test/css-extract/stringifyLocal.test.js
Labels: team, release: performance

#8099 fix: avoid extra runtime for get javascript chunk filename
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: release: bug fix

#7907 perf(rspack_core): replace `HASH_PLACEHOLDER_REGEX` with simple string parsing
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/utils/runtime.rs
  crates/rspack_plugin_library/Cargo.toml
Labels: release: performance

#8104 feat(core): bump swc to 1.0.0
  Cargo.lock
  Cargo.toml
Labels: team, release: feature

#8077 feat(rspack_plugin_copy): Set source_filename and copied flag when copying an asset
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/AssetInfo.ts
  tests/plugin-test/copy-plugin/CopyPlugin.test.js
Labels: release: feature

#8070 perf: add cache for getting sideEffectState
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: performance

#8112 chore(website/deps): bump 1.33.1
  website/package.json
  website/pnpm-lock.yaml
Labels: team

#8114 chore(workflow): merge website folder to the root pnpm workspace
  package.json
  packages/playground/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/treeShakingCases/issue-4637/__snapshots__/treeshaking.snap.txt
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tests/diff-test/arco-pro/package.json
  tests/plugin-test/css-extract/cases/pathinfo-devtool-source-map/expected/main.css
  tests/plugin-test/css-extract/cases/pathinfo/expected/main.css
  tests/webpack-test/package.json
  website/package.json
  website/pnpm-lock.yaml
  website/pnpm-workspace.yaml
Labels: team

#8119 feat(cli): add exports field
  packages/rspack-cli/package.json
Labels: team, release: feature

#8113 feat(rspack_core): use simple string parsing instead of regex
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/utils/hash.rs
  crates/rspack_core/src/utils/runtime.rs
Labels: release: feature

#8111 chore: upgrade rust to 1.81.0 nightly
  .github/workflows/ci.yml
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/diagnostics.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_core/src/stats/utils.rs
  crates/rspack_regex/src/algo.rs
  crates/rspack_util/src/infallible.rs
  rust-toolchain.toml
Labels: team

#8124 chore(create-rspack): bump Rslib 0.0.12 and adjust dirname
  packages/create-rspack/package.json
  packages/create-rspack/src/index.ts
  packages/create-rspack/tsconfig.json
  pnpm-lock.yaml
Labels: team

#8125 fix: side effects optimize for dynamic reexports
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/index.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/a.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/b.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/c.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/package.json
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/rspack.config.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/index.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/a.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/b.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/c.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/package.json
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/rspack.config.js
  tests/webpack-test/cases/side-effects/dynamic-reexports/index.js
  tests/webpack-test/cases/side-effects/dynamic-reexports/test.config.js
  tests/webpack-test/cases/side-effects/dynamic-reexports/test.filter.js
Labels: team, release: bug fix

#8126 fix(json): only add RuntimeGlobals::MODULE for concatenation
  crates/rspack_plugin_json/src/lib.rs
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#8122 test: not to display obsoleted snapshots when test with `-t`
  packages/rspack-test-tools/jest.config.js
  scripts/test/ignore-snapshot-default-reporter.cjs
  scripts/test/ignore-snapshot-summary-reporter.cjs
  tests/webpack-test/jest.config.js
Labels: team

#8136 fix: should not panic when passing `test` option to SourceMapDevToolPlugin
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin/rspack.config.js
Labels: release: bug fix

#8140 fix(core): should external package.json from bundle
  packages/rspack/tsup.config.ts
Labels: team, release: bug fix

#8144 docs: update `webpack-assets-manifest` compatibility status
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#8138 fix: rspack source for stream_chunks_of_source_map_full
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#8145 chore(deps): update typescript to v5.6
  .github/renovate.json5
  api-extractor.json
  crates/node_binding/package.json
  package.json
  packages/create-rspack/package.json
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-vanilla-ts/package.json
  packages/create-rspack/template-vue-ts/package.json
  packages/playground/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/package.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  pnpm-lock.yaml
  scripts/package.json
  tsconfig.base.json
  website/package.json
Labels: team

#8147 fix: perf degradation in devtool plugin
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
Labels: team, release: bug fix

#8127 feat: incremental for collecting dependencies diagnostics
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/unaffected_cache/mutations.rs
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/processor/hot-new-incremental.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/0/bad.js
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/0/good.js
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/0/index.js
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/0/value.js
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/1/index.js
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/1/warnings.js
  packages/rspack-test-tools/tests/watchCases/collect-modules-diagnostics/revoked-modules/2/index.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#8155 docs: disable doc blog sidebar
  website/docs/en/blog/announcing-0-1.mdx
  website/docs/en/blog/announcing-0-2.mdx
  website/docs/en/blog/announcing-0-3.mdx
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/blog/announcing-0-5.mdx
  website/docs/en/blog/announcing-0-6.mdx
  website/docs/en/blog/announcing-0-7.mdx
  website/docs/en/blog/announcing-1-0-alpha.mdx
  website/docs/en/blog/announcing-1-0.mdx
  website/docs/en/blog/index.mdx
  website/docs/en/blog/module-federation-added-to-rspack.mdx
  website/docs/zh/blog/announcing-0-1.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-3.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/blog/announcing-0-5.mdx
  website/docs/zh/blog/announcing-0-6.mdx
  website/docs/zh/blog/announcing-0-7.mdx
  website/docs/zh/blog/announcing-1-0-alpha.mdx
  website/docs/zh/blog/announcing-1-0.mdx
  website/docs/zh/blog/index.mdx
  website/docs/zh/blog/module-federation-added-to-rspack.mdx
Labels: team, release: document

#8137 test: add global snapshot serializer
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/case/error.ts
  packages/rspack-test-tools/src/case/stats-api.ts
  packages/rspack-test-tools/src/helper/expect/char.ts
  packages/rspack-test-tools/src/helper/expect/diff.ts
  packages/rspack-test-tools/src/helper/expect/error.ts
  packages/rspack-test-tools/src/helper/expect/placeholder.ts
  packages/rspack-test-tools/src/helper/expect/rspack.ts
  packages/rspack-test-tools/src/helper/setup-expect.ts
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/tests/Defaults.test.js
  packages/rspack-test-tools/tests/Validation.test.js
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/compilerCases/assets-exist.js
  packages/rspack-test-tools/tests/compilerCases/assets-not-exist.js
  packages/rspack-test-tools/tests/compilerCases/single-file.js
  packages/rspack-test-tools/tests/defaultsCases/config/array-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/async-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/both-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-root-placeholder.js
  packages/rspack-test-tools/tests/errorCases/error-map.js
  packages/rspack-test-tools/tests/errorCases/error-test-pop.js
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/resolve-fail-esm.js
  packages/rspack-test-tools/tests/errorCases/warning-map.js
  packages/rspack-test-tools/tests/errorCases/warning-test-pop.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/statsAPICases/bundler-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/error-chunk.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/ids.js
  packages/rspack-test-tools/tests/statsAPICases/layer.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack-test-tools/tests/statsAPICases/profile.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  pnpm-lock.yaml
Labels: team

#8157 fix: compatible static methods with html-webpack-plugin 5.6.0
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
Labels: team, release: bug fix

#8158 docs: add `html-rspack-tags-plugin` as an alternative
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#8159 refactor: mutations read write permission from incremental options
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/unaffected_cache/incremental.rs
  crates/rspack_core/src/unaffected_cache/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
Labels: team

#8160 docs: add Kuaishou logo to who is using
  website/project-words.txt
  website/theme/components/Landingpage/WhoIsUsing/assets/kuaishou.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: team, release: document

#7965 perf: cache swc loader
  crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
Labels: release: performance

#8143 fix: generate correct worker expression with trusted types
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/index.js
  packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/module.js
  packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/rspack.config.js
  packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/test.config.js
  packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/worker.js
Labels: team, release: bug fix

#8148 fix: use content hash as [base] and [name] for extracted DataURIs
  crates/rspack_core/src/options/filename.rs
  tests/webpack-test/configCases/asset-modules/data-url-extract/index.js
  tests/webpack-test/configCases/asset-modules/data-url-extract/webpack.config.js
  tests/webpack-test/configCases/asset-modules/resource-from-data-uri/index.js
Labels: release: bug fix

#8168 fix: should keep comments of esm export
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/index.js
  packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/share.js
  packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/used.js
  packages/rspack-test-tools/tests/treeShakingCases/pure_comments_magic_comments/__snapshots__/treeshaking.snap.txt
Labels: release: bug fix

#8172 fix: escape node.__dirname
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8170/dir1/dir2/file.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8170/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8170/rspack.config.js
Labels: release: bug fix

#7972 feat: support `require.ensure`
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_ensure_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_ensure_item_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack-test-tools/tests/normalCases/parsing/unsupport-require-property/index.js
  packages/rspack-test-tools/tests/normalCases/parsing/unsupport-require-property/warnings.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/cases/chunks/context/test.filter.js
  tests/webpack-test/cases/chunks/named-chunks/test.filter.js
  tests/webpack-test/cases/chunks/nested-in-empty/test.filter.js
  tests/webpack-test/cases/chunks/parsing/test.filter.js
  tests/webpack-test/cases/chunks/runtime/test.filter.js
  tests/webpack-test/cases/chunks/var-inject-error-handler/test.filter.js
  tests/webpack-test/cases/parsing/chunks/test.filter.js
  tests/webpack-test/cases/parsing/complex-require/test.filter.js
  tests/webpack-test/cases/parsing/es6.nominimize/test.filter.js
  tests/webpack-test/cases/parsing/issue-758/test.filter.js
  tests/webpack-test/cases/parsing/typeof/test.filter.js
  tests/webpack-test/cases/runtime/module-caching/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/all-selected/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/duplicate/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/existing-name/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/nested/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/simple/test.filter.js
  tests/webpack-test/configCases/parsing/issue-14720/test.filter.js
  tests/webpack-test/configCases/source-map/module-names/test.filter.js
  tests/webpack-test/configCases/split-chunks-common/library/test.filter.js
  tests/webpack-test/statsCases/async-commons-chunk/test.filter.js
  tests/webpack-test/statsCases/limit-chunk-count-plugin/test.filter.js
  tests/webpack-test/statsCases/optimize-chunks/test.filter.js
  website/docs/en/api/runtime-api/module-methods.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
Labels: release: feature

#8173 docs: rename shareScope to shareStrategy
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: release: document

#8175 refactor: incremental options name
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/unaffected_cache/incremental.rs
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/processor/hot-new-incremental.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
Labels: team

#8177 feat(types): export `ResolveData` type
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
Labels: team

#8178 docs: update ContextModuleFactory hook
  website/docs/en/api/plugin-api/context-module-factory-hooks.mdx
  website/docs/zh/api/plugin-api/context-module-factory-hooks.mdx
Labels: team, release: document

#8182 fix: temporarily use `lightingcss_rs` to fix CSS property order
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_lightningcss/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
Labels: release: bug fix

#8115 feat: add setters for errors and warnings in Compilation
  packages/rspack-test-tools/tests/errorCases/error-test-set.js
  packages/rspack-test-tools/tests/errorCases/warning-test-set.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
Labels: release: feature

#8187 feat(CLI): make `@rspack/cli` dual package and bundle with Rslib
  packages/create-rspack/rslib.config.ts
  packages/rspack-cli/bin/rspack
  packages/rspack-cli/bin/rspack.js
  packages/rspack-cli/package.json
  packages/rspack-cli/rslib.config.ts
  packages/rspack-cli/src/bootstrap.ts
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/utils/crossImport.ts
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/utils/test-utils.ts
  pnpm-lock.yaml
Labels: team, release: feature

#8188 fix(deps): upgrade rspack_resolver 0.3.5 to fix extensionAlias edge cases
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
  packages/rspack-test-tools/tests/configCases/resolve/extension-alias/errors.js
  packages/rspack-test-tools/tests/configCases/resolve/extension-alias/index.js
  packages/rspack-test-tools/tests/configCases/resolve/extension-alias/src/m1.mjs
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/errors.js
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/index.js
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/warnings.js
  packages/rspack-test-tools/tests/treeShakingCases/cjs-tree-shaking-basic/package.json
  packages/rspack-test-tools/tests/treeShakingCases/reexport-all-as-multi-level-nested/package.json
  packages/rspack-test-tools/tests/treeShakingCases/reexport-all-as/package.json
Labels: team, release: bug fix

#8191 docs: correct ES modules and some other spellings
  website/docs/en/blog/index.mdx
  website/docs/en/config/index.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/output.mdx
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/blog/index.mdx
  website/docs/zh/config/index.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/guide/features/web-workers.mdx
  website/docs/zh/plugins/webpack/hot-module-replacement-plugin.mdx
Labels: team, release: document

#8189 docs: add tips and examples for experiments configs
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8186 docs: use ApiMeta specific label instead of Webpack specific chapter
  website/docs/en/api/plugin-api/context-module-factory-hooks.mdx
  website/docs/zh/api/plugin-api/context-module-factory-hooks.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
Labels: team, release: document

#8203 docs: update links in README
  README.md
  README.zh-CN.md
Labels: team, release: document

#8202 docs: add layer examples and correct types
  website/docs/en/config/entry.mdx
  website/docs/en/config/module.mdx
  website/docs/zh/config/entry.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#8196 refactor: collect rebuild modules mutations in make
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/incremental/mod.rs
  crates/rspack_core/src/incremental/mutations.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/unaffected_cache/mod.rs
  crates/rspack_core/src/unaffected_cache/mutations.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team

#8204 fix: should correct cacheGroups test regex
  packages/rspack-test-tools/tests/configCases/split-chunks/rspack-issue-5657/rspack.config.js
Labels: team, release: bug fix

#8169 fix(type): function type in cjs require
  packages/rspack-cli/jest.config.js
  packages/rspack-cli/tests/api/type/js-api-cjs.test.ts
  packages/rspack-cli/tests/api/type/js-api-esm.test.mts
  packages/rspack-test-tools/package.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  packages/rspack/src/index.ts
Labels: team, release: bug fix

#8165 fix(modern-module): concatenate entry module regardless bail reasons
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/g/foo.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/g/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
Labels: team, release: bug fix

#8207 test: add `rspack.default` should not exist test
  packages/rspack-cli/tests/api/type/js-api-cjs.test.ts
  packages/rspack-cli/tests/api/type/js-api-esm.test.mts
Labels: team

#8214 chore(typo): rename `lightningCssMiminizerPlugin.ts` file
  packages/rspack/src/builtin-plugin/LightningCssMinimizerRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
Labels: team

#8215 feat: keep SWC types up to date
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  packages/rspack/prebundle.config.mjs
  packages/rspack/src/builtin-loader/swc/react.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/tsconfig.json
  pnpm-lock.yaml
Labels: team, release: feature

#8149 feat: support wrappedContextRegExp
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_util/src/merge.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/index.js
  packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/rspack.config.js
  packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/sub/a1.js
  packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/sub/a2.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: feature

#8216 fix(ci): trigger `pkg-preview` when the needs are skipped
  .github/workflows/ci.yml
Labels: release: bug fix

#8221 fix: incremental provided exports should rebuild clean exports info
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/a.js
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/b.js
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/c.js
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/index.js
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/1/c.js
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/2/a.js
  packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/2/c.js
Labels: team, release: bug fix

#8223 docs: fix link is 404 in Guide
  website/docs/en/guide/migration/storybook.mdx
  website/docs/en/guide/tech/vue.mdx
  website/docs/zh/guide/migration/storybook.mdx
  website/docs/zh/guide/tech/vue.mdx
Labels: release: document

#8222 docs: correct the format of defaultValue
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: document

#8212 fix: module_executor support layer
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/banner.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/index.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/loader.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/rspack.config.js
Labels: team, release: bug fix

#8128 feat: introduce RemoveDuplicateModulesPlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_plugin_remove_duplicate_modules/Cargo.toml
  crates/rspack_plugin_remove_duplicate_modules/LICENSE
  crates/rspack_plugin_remove_duplicate_modules/src/lib.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/RemoveDuplicateModulesPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
Labels: team, release: feature

#8236 ci: allow to use self-host runner when preview package
  .github/workflows/preview-commit.yml
Labels: team

#7753 feat(html): support function filename and `[name]` in filename
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/template.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-html/filename/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/filename/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  tests/plugin-test/copy-plugin/build/main.js
  tests/plugin-test/html-plugin/basic.test.js
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: feature

#8237 ci: allow to get label from self host runner
  .github/workflows/get-runner-labels.yml
Labels: team

#8239 docs: should enable swc `keepImportAttributes` configuration when use `Rule.with`
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#8240 fix: expose incremental.buildChunkGraph
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#8241 docs: addedVersion should link to release tag
  website/components/ApiMeta.tsx
Labels: team, release: document

#8242 fix: compile time evaluation of require.ensure
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  tests/webpack-test/cases/parsing/typeof/index.js
Labels: team, release: bug fix

#8244 fix(cli): display the error which is thrown by the plugin during the starting of `rspack serve`
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/tests/serve/plugin-apply-error/rspack.config.js
  packages/rspack-cli/tests/serve/plugin-apply-error/serve-plugin-apply-error.test.ts
Labels: team, release: bug fix

#8246 docs: update Rspack roadmap
  website/docs/en/misc/planning/roadmap.mdx
  website/docs/zh/misc/planning/roadmap.mdx
Labels: team, release: document

#8252 chore: add Debug trait for FileSystem and Make Task
  Cargo.lock
  crates/rspack_binding_options/src/options/raw_builtins/raw_ignore.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_size.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/task_loop.rs
  crates/rspack_fs/src/async.rs
  crates/rspack_fs/src/native.rs
  crates/rspack_fs/src/sync.rs
  crates/rspack_fs_node/src/async.rs
  crates/rspack_fs_node/src/sync.rs
  crates/rspack_plugin_context_replacement/Cargo.toml
  crates/rspack_plugin_context_replacement/src/lib.rs
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/src/http_uri.rs
  crates/rspack_plugin_schemes/src/lockfile.rs
Labels: team

#8253 ci: allow aarch64 gnu compile on github runner in pkg preview
  .github/workflows/preview-commit.yml
Labels: team

#8249 perf: enable `xxhash64` hash function by default
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/css-loader/css-modules-classname/index.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-6435/rspack.config.js
  packages/rspack-test-tools/tests/configCases/mangle-exports/skipping-mangle-css-modules/index.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/hashCases/issue-7992/test.config.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-md4/rspack.config.js
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hotCases/chunk/asset/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-extract/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/lib/cache/getLazyHashedEtag.ts
  tests/plugin-test/css-extract/TestCases.test.js
  tests/plugin-test/css-extract/__snapshots__/emitOption.test.js.snap
  tests/plugin-test/html-plugin/basic.test.js
  tests/webpack-test/Defaults.unittest.js
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/cases/parsing/hot-hash/index.js
  tests/webpack-test/configCases/asset-modules/custom-condition/index.js
  tests/webpack-test/configCases/asset-modules/generator-asset-publicPath-hash/index.js
  tests/webpack-test/configCases/asset-modules/global-options/index.js
  tests/webpack-test/configCases/asset-modules/query-and-custom-condition/index.js
  tests/webpack-test/configCases/asset-modules/query/index.js
  tests/webpack-test/configCases/asset-modules/resource-from-data-uri/index.js
  tests/webpack-test/configCases/asset-modules/types/index.js
  tests/webpack-test/configCases/deprecations/chunk-and-module/webpack.config.js
  tests/webpack-test/configCases/parsing/extended-api/index.js
  tests/webpack-test/configCases/source-map/source-map-filename-contenthash/index.js
  tests/webpack-test/package.json
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: performance

#8251 test: remove copy plugin build folder
  .gitignore
  tests/plugin-test/copy-plugin/CopyPlugin.test.js
  tests/plugin-test/copy-plugin/build/.dottedfile
  tests/plugin-test/copy-plugin/build/.gitkeep
  tests/plugin-test/copy-plugin/build/_t1/dest1/tempfile1.txt
  tests/plugin-test/copy-plugin/build/_t1/dest2/directory/tempfile1.txt
  tests/plugin-test/copy-plugin/build/_t1/dest2/tempfile2.txt
  tests/plugin-test/copy-plugin/build/_t2/dest1/tempfile1.txt
  tests/plugin-test/copy-plugin/build/_t2/dest1/tempfile2.txt
  tests/plugin-test/copy-plugin/build/_t2/dest2/tempfile1.txt
  tests/plugin-test/copy-plugin/build/_t2/dest2/tempfile2.txt
  tests/plugin-test/copy-plugin/build/_t3/dest1/tempfile1.txt
  tests/plugin-test/copy-plugin/build/_t3/dest1/tempfile2.txt
  tests/plugin-test/copy-plugin/build/asset-modules/deepnested.txt
  tests/plugin-test/copy-plugin/build/binextension.bin
  tests/plugin-test/copy-plugin/build/directory/directoryfile.txt
  tests/plugin-test/copy-plugin/build/directory/nested/deep-nested/deepnested.txt
  tests/plugin-test/copy-plugin/build/directory/nested/nestedfile.txt
  tests/plugin-test/copy-plugin/build/directoryfile.txt
  tests/plugin-test/copy-plugin/build/file.txt
  tests/plugin-test/copy-plugin/build/file[1].txt
  tests/plugin-test/copy-plugin/build/first/file.txt
  tests/plugin-test/copy-plugin/build/main.js
  tests/plugin-test/copy-plugin/build/nested/deep-nested/deepnested.txt
  tests/plugin-test/copy-plugin/build/nested/nestedfile.txt
  tests/plugin-test/copy-plugin/build/newbinextension.bin
  tests/plugin-test/copy-plugin/build/newdirectory/.dottedfile
  tests/plugin-test/copy-plugin/build/newdirectory/deep-nested/deepnested.txt
  tests/plugin-test/copy-plugin/build/newdirectory/directory/directoryfile.txt
  tests/plugin-test/copy-plugin/build/newdirectory/directory/nested/deep-nested/deepnested.txt
  tests/plugin-test/copy-plugin/build/newdirectory/directory/nested/nestedfile.txt
  tests/plugin-test/copy-plugin/build/newdirectory/directoryfile.txt
  tests/plugin-test/copy-plugin/build/newdirectory/nested/deep-nested/deepnested.txt
  tests/plugin-test/copy-plugin/build/newdirectory/nested/nestedfile.txt
  tests/plugin-test/copy-plugin/build/newdirectory/nestedfile.txt
  tests/plugin-test/copy-plugin/build/newfile.txt
  tests/plugin-test/copy-plugin/build/noextension
  tests/plugin-test/copy-plugin/build/second/file.txt
  tests/plugin-test/copy-plugin/build/tempfile1.txt
  tests/plugin-test/copy-plugin/build/tempfile2.txt
  tests/plugin-test/copy-plugin/build/unoptimized.js
  tests/plugin-test/copy-plugin/helpers/getCompiler.js
Labels: team

#8261 docs: add license to website footer
  website/rspress.config.ts
  website/theme/pages/index.tsx
Labels: team, release: document

#8263 ci: create prerelease pull request
  .github/workflows/release-pull-request.yml
  scripts/release/version.mjs
  x.mjs
Labels: team

#8266 ci: fix pretag default value
  .github/workflows/release-pull-request.yml
  scripts/release/version.mjs
Labels: team

#8250 feat(incremental): free space for revoked modules
  crates/rspack_core/src/cgm_hash_results.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/case/watch.ts
Labels: team, release: feature

#8265 docs(swc-loader): add example for syntax lowering and polyfill
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: document

#8264 feat(core): bump swc to 3.0.1
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/src/compiler.rs
  crates/rspack_loader_swc/src/transformer.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/dropped_comments_preserver.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/swc_plugin_import/src/lib.rs
Labels: team, release: feature

#8217 fix: preserve star export from external module
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_library/src/modern_module/import_dependency.rs
  crates/rspack_plugin_library/src/modern_module/mod.rs
  crates/rspack_plugin_library/src/modern_module/reexport_star_external_dependency.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/case1.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/case2.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/case3/foo.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/case3/index.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/index.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/test.config.js
Labels: team, release: bug fix

#8272 chore(ci): change repo owner of rspack-ecosystem-ci
  .github/workflows/ci.yml
  .github/workflows/ecosystem-ci-trigger.yml
  .github/workflows/release-nightly.yml
Labels: team

#8275 perf: enable SWC `disableAllLints` by default to reduce overhead
  packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-swc-loader/stats.err
  packages/rspack/src/config/adapterRuleUse.ts
Labels: team, release: performance

#8282 perf(core): replace `neo-async` with a minimal helper
  packages/rspack/package.json
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/MultiWatching.ts
  packages/rspack/src/lib/CacheFacade.ts
  packages/rspack/src/util/asyncLib.ts
  pnpm-lock.yaml
Labels: team, release: performance

#8279 fix(type): Make iterators compatible with TS 5.6 `--target ESNext`
  packages/rspack/src/Compilation.ts
  packages/rspack/src/util/ArrayQueue.ts
Labels: release: bug fix

#8274 feat: add read API to output file system
  crates/node_binding/binding.d.ts
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_fs/src/async.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/native.rs
  crates/rspack_fs_node/src/async.rs
  crates/rspack_fs_node/src/node.rs
  packages/rspack/src/FileSystem.ts
Labels: team, release: feature

#8281 refactor: module.size fn should a option compilation
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
Labels: team

#8287 test: keep test case stable with different version length
  packages/rspack-test-tools/tests/statsAPICases/bundler-info.js
Labels: team

#8283 feat(rspack/stats): support the option groupModulesByLayer of stats
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/layer-stats.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
Labels: release: feature

#8285 fix(core): remove unused source files
  packages/rspack/src/lib/Dependency.ts
  packages/rspack/src/lib/formatLocation.ts
  packages/rspack/src/logging/runtime.ts
  packages/rspack/src/util/IterableHelpers.ts
  packages/rspack/src/util/scheme.ts
  packages/rspack/src/util/webpack.ts
  tests/webpack-test/formatLocation.unittest.js
  tests/webpack-test/jest.config.js
Labels: team, release: bug fix

#8286 fix: types and docs of umd external object
  crates/rspack_plugin_library/src/utils.rs
  packages/rspack-test-tools/tests/configCases/externals/item-value-object/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/externals.mdx
  website/docs/zh/config/externals.mdx
Labels: team, release: bug fix

#8292 docs: fix inline match resource typo
  website/docs/zh/api/loader-api/inline-match-resource.mdx
Labels: team, release: document

#8293 docs: add docs for incremental
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8295 chore(format): run prettier format
  .devcontainer/devcontainer.json
  CODE_OF_CONDUCT.md
  biome.jsonc
  package.json
  packages/rspack-cli/tsconfig.build.json
  packages/rspack-cli/tsconfig.json
  packages/rspack-test-tools/tsconfig.assets.json
  packages/rspack-test-tools/tsconfig.json
  packages/rspack-test-tools/viewer/entries/diff.tsx
  packages/rspack-test-tools/viewer/templates/diff.html
  packages/rspack/api-extractor.json
  packages/rspack/tsconfig.build.json
  packages/rspack/tsconfig.json
  scripts/release/version.mjs
  scripts/test/diff.cjs
  scripts/test/ignore-snapshot-default-reporter.cjs
  scripts/test/ignore-snapshot-summary-reporter.cjs
  scripts/test/patch-node-env.cjs
  scripts/tsconfig.json
  x
Labels: team

#8294 chore(ci/deps): update renovate
  .github/renovate.json5
  .github/workflows/release-pull-request.yml
Labels: team

#8301 feat(core): improve progress plugin for multi compiler
  Cargo.lock
  crates/rspack_plugin_progress/src/lib.rs
Labels: team, release: feature
