Repository web-infra-dev/rspack, pull requests merged in 2024-06, with the labels that each got.

#6700 docs: translate exportsOnly description
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#6703 fix: should insert semi after variable decl
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/semicolon.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/builtins/define/index.js
  packages/rspack-test-tools/tests/configCases/builtins/define/rspack.config.js
  packages/rspack-test-tools/tests/normalCases/parsing/asi/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
  plugin-test/css-extract/cases/issue-6649/expected/main.js
Labels: team, release: bug fix

#6698 chore: ignore json named exports warnings for non-strict ESM
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack-test-tools/tests/configCases/tree-shaking/import-by-name-json/warnings.js
  packages/rspack-test-tools/tests/normalCases/warnings/json-named-exports-presence/data.json
  packages/rspack-test-tools/tests/normalCases/warnings/json-named-exports-presence/errors.js
  packages/rspack-test-tools/tests/normalCases/warnings/json-named-exports-presence/index.js
  packages/rspack-test-tools/tests/normalCases/warnings/json-named-exports-presence/no-strict.js
  packages/rspack-test-tools/tests/normalCases/warnings/json-named-exports-presence/strict.mjs
  webpack-test/cases/json/import-by-name-with-concatenation/warnings.js
  webpack-test/cases/json/import-by-name/warnings.js
  webpack-test/cases/json/reexport/warnings.js
  webpack-test/cases/scope-hoisting/json-reexport-6700/warnings.js
Labels: team

#6691 fix: should error when matched alias not found
  Cargo.lock
  crates/rspack_core/Cargo.toml
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/index.js
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/node_modules/m1/mod.js
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/node_modules/m2/index.js
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/warnings.js
Labels: team, release: bug fix

#6631 feat: support `_module` of LoaderContext
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/configCases/compilation/rebuild-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader/context-module/a.js
  packages/rspack-test-tools/tests/configCases/loader/context-module/index.js
  packages/rspack-test-tools/tests/configCases/loader/context-module/my-loader.js
  packages/rspack-test-tools/tests/configCases/loader/context-module/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack/etc/api.md
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
Labels: release: feature

#6705 fix: local class with charset
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#6706 fix: allow return outside functions in scripts
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/utils/mod.rs
  crates/rspack_plugin_lazy_compilation/expand.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/a.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/b.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/c.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/stats.err
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
Labels: team, release: bug fix

#6710 refactor: cleanup JavaScript parsing 2
  crates/rspack_core/src/dependency/span.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
Labels: team

#6712 refactor: cleanup source-map stub
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/source-map/index.js
  packages/rspack-test-tools/tests/configCases/source-map/source-map/index.js
Labels: team

#6716 fix: lazy compilation should escape data uri and should not rely on dependency request
  crates/rspack_plugin_lazy_compilation/src/dependency.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  packages/playground/cases/lazy-compilation/ignore-entry/rspack.config.js
  packages/playground/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#6723 fix: correct runtime condition expression
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
Labels: team, release: bug fix

#6707 fix: extract-css should pass cacheable
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_extract_css/src/parser_and_generator.rs
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/hotCases/css/css-extract/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-extract/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-extract/entry.js
  packages/rspack-test-tools/tests/hotCases/css/css-extract/entry2.js
  packages/rspack-test-tools/tests/hotCases/css/css-extract/index.js
  packages/rspack-test-tools/tests/hotCases/css/css-extract/index.module.css
  packages/rspack-test-tools/tests/hotCases/css/css-extract/loader.js
  packages/rspack-test-tools/tests/hotCases/css/css-extract/rspack.config.js
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/change.css
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/change.js
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/index.js
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/no-change.css
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/no-change.js
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/rspack.config.js
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#6724 test: enable jsdom runner by default
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/web.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack-test-tools/src/test/tester.ts
  packages/rspack-test-tools/src/type.ts
Labels: team

#6730 refactor: entry_modules calculate by entry_deps
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
Labels: team

#6733 fix: code splitting won't invalidate in some cases
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: bug fix

#6736 docs: rewrite document for require.context()
  website/docs/en/api/modules/module-methods.mdx
  website/docs/zh/api/modules/module-methods.mdx
Labels: team, release: document

#6745 fix: override existing css exports
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_util/src/fx_hash.rs
  packages/rspack-test-tools/tests/configCases/css/override-exports/index.js
  packages/rspack-test-tools/tests/configCases/css/override-exports/index.module.css
  packages/rspack-test-tools/tests/configCases/css/override-exports/rspack.config.js
Labels: team, release: bug fix

#6746 docs: update Module Federation guide
  website/docs/en/guide/features/module-federation.mdx
  website/docs/en/plugins/webpack/module-federation-plugin-v1.mdx
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/guide/features/module-federation.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin-v1.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: team, release: document

#6428 fix: add chunks and cacheGroupKey to cacheGroups' name
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-name-add-chunks-cachegroupkey/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-name-add-chunks-cachegroupkey/webpack.config.js
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
Labels: release: bug fix

#6721 feat: align `AssetInfo` type with webpack
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack-cli/tests/build/basic/public/main.js.map
  packages/rspack-test-tools/tests/compilerCases/assets-update-info.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/util/AssetInfo.ts
  packages/rspack/src/util/index.ts
Labels: release: feature

#6747 fix: support lazy css using css-extract
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/dependency/loader_import.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  packages/playground/cases/lazy-compilation/ignore-entry/index.test.ts
  packages/playground/cases/lazy-compilation/ignore-entry/rspack.config.js
  packages/playground/cases/lazy-compilation/ignore-entry/src/index.css
Labels: team, release: bug fix

#6748 docs: bump Rspress to improve container style
  website/package.json
  website/pnpm-lock.yaml
Labels: team, release: document

#6749 perf: code-splitting should not regenerate chunk
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: performance

#6751 docs: add import.meta.webpackContext
  website/docs/en/api/modules/module-methods.mdx
  website/docs/en/api/modules/module-variables.mdx
  website/docs/zh/api/modules/module-methods.mdx
  website/docs/zh/api/modules/module-variables.mdx
Labels: team, release: document

#6752 refactor: harmony import dependency parser plugin
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_member_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
  packages/rspack-test-tools/src/case/diff.ts
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/a.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/ax.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/b.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/bx.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/c.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/concatenated-shared.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/cx.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/d1.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/d2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/dep-shared3.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/dep-shared4.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/dep.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/dep2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/shared.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/shared2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/src/super.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-no-inner-graph/webpack.config.js
  webpack-test/configCases/graph/issue-11856.2/test.filter.js
  webpack-test/configCases/graph/issue-11856/test.filter.js
  webpack-test/configCases/graph/issue-11863/test.filter.js
Labels: team

#6757 fix: should clear local classes for invalid composes
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#6758 fix: `Rule.descriptionData` won't match object types
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/empty-loader.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/index.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/loader.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/node_modules/bar/index.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/node_modules/bar/package.json
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/node_modules/foo/index.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/rspack.config.js
Labels: team, release: bug fix

#6760 fix: Add `in_function_scope` for walking method function
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/normalCases/parsing/method-function-in-scope/index.js
  packages/rspack-test-tools/tests/normalCases/parsing/method-function-in-scope/utils.js
Labels: release: bug fix

#6765 test: export setup for plugin testing
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/helper/expect/to-be-typeof.ts
  packages/rspack-test-tools/src/helper/expect/to-end-with.ts
  packages/rspack-test-tools/src/helper/expect/to-match-file-snapshot.ts
  packages/rspack-test-tools/src/helper/setup-env.ts
  packages/rspack-test-tools/src/helper/setup-expect.ts
Labels: team

#6764 chore: enable runtime condition webpack-test
  webpack-test/hotCases/conditional-runtime/accept-conditional/test.filter.js
Labels: team

#6766 fix: has_module_graph_change miscalculation
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
Labels: team, release: bug fix

#6767 chore(infra): bump pnpm v9
  .github/actions/pnpm-cache/action.yml
  .npmrc
  package.json
  pnpm-lock.yaml
  website/package.json
  website/pnpm-lock.yaml
Labels: team

#6769 perf: put visited_chunk_group_keys out of the loop and use FxHashMap
  Cargo.lock
  crates/rspack_plugin_ensure_chunk_conditions/Cargo.toml
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
Labels: release: performance

#6770 ci: use @pnpm/exe in Node 16 CI
  .github/actions/pnpm-cache/action.yml
Labels: team

#6772 feat: css tree shaking
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_wasm/src/dependency/wasm_import_dependency.rs
  packages/rspack-test-tools/tests/treeShakingCases/css/README.md
  packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/css/index.js
  packages/rspack-test-tools/tests/treeShakingCases/css/index.module.css
  packages/rspack-test-tools/tests/treeShakingCases/css/package.json
  packages/rspack-test-tools/tests/treeShakingCases/css/rspack.config.js
Labels: team, release: feature

#6750 perf: code splitter
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
Labels: release: performance

#6771 fix: should remove correct connections
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: bug fix

#6778 fix: panic when resolve failed and enable concatenateModule
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/index.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/a.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/b.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/c.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/reexport.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/index.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/node_modules/some-module/a.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/node_modules/some-module/b.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/node_modules/some-module/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/reexport.ts
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
Labels: team, release: bug fix

#6779 fix: panic when resolve context failed
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/stats.err
Labels: team, release: bug fix

#6722 feat: `ProgressPlugin` configuration
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_progress.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/builtin-plugin/ProgressPlugin.ts
  website/docs/en/plugins/webpack/progress-plugin.mdx
  website/docs/zh/plugins/webpack/progress-plugin.mdx
  website/project-words.txt
Labels: release: feature

#6780 docs: fix discord badge
  README.md
  README.zh-CN.md
Labels: team, release: document

#6777 feat: use warning for css parsing
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/index.module.css
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/stats.err
Labels: team, release: feature

#6781 fix: concatenate module with external
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/configCases/concatenate-modules/with-externals/index.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/with-externals/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/esm-external/index.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
Labels: team, release: bug fix

#6783 fix: increase stack size limit to 4mb
  crates/node_binding/src/env.rs
  crates/node_binding/src/lib.rs
Labels: team, release: bug fix

#6788 fix: diagnostic snapshot
  packages/rspack-test-tools/src/case/diagnostic.ts
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/html_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-loader/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/dynamic-import-non-exist-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/empty-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/entry-runtime-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/fully-specified-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-config-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/prefer-relative-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/resolve-extensions-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/unhandled-scheme-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/basic/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/define_plugin_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/import_meta_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/json/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lexically_name_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/non_support_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/reserved_name_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/tla_disable_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/tla_esm_error/stats.err
Labels: team, release: bug fix

#6784 feat: concatenated modules stats
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack-test-tools/tests/statsOutputCases/concatenated-modules/a.js
  packages/rspack-test-tools/tests/statsOutputCases/concatenated-modules/b.js
  packages/rspack-test-tools/tests/statsOutputCases/concatenated-modules/c.js
  packages/rspack-test-tools/tests/statsOutputCases/concatenated-modules/index.js
  packages/rspack-test-tools/tests/statsOutputCases/concatenated-modules/rspack.config.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPresetPlugin.ts
Labels: team, release: feature

#6787 feat: allow to reference client module types
  packages/rspack/module.d.ts
  packages/rspack/package.json
  website/docs/en/guide/tech/typescript.mdx
  website/docs/zh/guide/tech/typescript.mdx
Labels: team, release: feature

#6794 fix: diagnostic snapshot
  crates/rspack_error/src/diagnostic.rs
  packages/rspack-test-tools/src/case/diagnostic.ts
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/html_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-loader/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/dynamic-import-non-exist-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/empty-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/entry-runtime-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/fully-specified-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-config-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/prefer-relative-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/resolve-extensions-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/unhandled-scheme-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/basic/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/define_plugin_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/import_meta_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/json/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lexically_name_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/non_support_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/reserved_name_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/tla_disable_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/tla_esm_error/stats.err
Labels: team, release: bug fix

#6796 fix(mf): avoid error __webpack_require__.f.consume after hmr
  crates/rspack_plugin_mf/src/container/expose_runtime_module.rs
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
Labels: team, release: bug fix

#6798 docs: update slogan and descriptions
  README.md
  README.zh-CN.md
  package.json
  packages/rspack/README.md
  packages/rspack/package.json
  website/docs/en/guide/start/introduction.mdx
  website/docs/en/index.md
  website/docs/zh/blog/announcing-0-1.mdx
  website/docs/zh/guide/start/introduction.mdx
  website/docs/zh/index.md
  website/docs/zh/misc/team/join-us.mdx
  website/rspress.config.ts
  website/theme/components/HomeHero/index.tsx
Labels: release: document

#6800 feat: upgrade webpack latest version
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_hmr/src/runtime/hot_module_replacement.js
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  diffcases/arco-pro/package.json
  package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  plugin-test/copy-plugin/build/main.js
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$d39cfd64637173d8e8b0$.css
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$d39cfd64637173d8e8b0$.css
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  plugin-test/css-extract/cases/hmr/expected/main.js
  plugin-test/css-extract/cases/insert-function/expected/main.js
  plugin-test/css-extract/cases/insert-string/expected/main.js
  plugin-test/css-extract/cases/insert-undefined/expected/main.js
  plugin-test/css-extract/cases/issue-6649/expected/main.js
  plugin-test/css-extract/cases/no-runtime/expected/main.js
  plugin-test/css-extract/cases/runtime/expected/runtime~main.js
  pnpm-lock.yaml
  webpack-test/cases/mjs/namespace-object-lazy/cjs-dynamic.js
  webpack-test/cases/mjs/namespace-object-lazy/index.mjs
  webpack-test/cases/mjs/non-mjs-namespace-object-lazy/cjs-dynamic.js
  webpack-test/cases/mjs/non-mjs-namespace-object-lazy/index.js
Labels: release: feature

#6806 docs: name and dependencies
  website/docs/en/config/other-options.mdx
  website/docs/zh/config/other-options.mdx
Labels: release: document

#6799 feat: add more stats module properties
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_extract_css/src/parser_and_generator.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/ids.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack-test-tools/tests/statsAPICases/profile.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#6809 chore: remove useless Serialize and Deserialize
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
Labels: team

#6801 feat: lightningcss minimizer
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/index.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/style.module.css
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/invalid.css
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/stats.err
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/project-words.txt
Labels: team, release: feature

#6811 chore: add congcong to team member list
  .github/teams.yml
Labels: team

#6812 chore: remove unused lazy compilation file
  crates/rspack_plugin_lazy_compilation/expand.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
Labels: team

#6815 fix: css modules composes same ident with local class
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/index.js
  packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/index.module.css
  packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/input.module.css
  packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/rspack.config.js
  website/docs/en/config/module.mdx
Labels: team, release: bug fix

#6808 docs: infrastructureLogging
  website/docs/en/config/_meta.json
  website/docs/en/config/infrastructure-logging.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/infrastructure-logging.mdx
Labels: release: document

#6810 ci: check implemented but not documented configs
  packages/rspack/scripts/check-documentation-coverage.mjs
Labels: team, release: feature

#6817 feat(runtime): enable rspack version
  packages/rspack/src/builtin-plugin/BundlerInfoRspackPlugin.ts
Labels: release: feature

#6813 docs: translate `Rule.descriptionData`
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#6814 docs: complete output config
  packages/rspack/scripts/check-documentation-coverage.mjs
  website/docs/en/config/externals.mdx
  website/docs/en/config/output.mdx
  website/docs/en/config/plugins.mdx
  website/docs/zh/config/externals.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/config/plugins.mdx
  website/project-words.txt
Labels: team, release: document

#6825 docs: add semver declaration
  crates/node_binding/README.md
  scripts/build-npm.cjs
Labels: team, release: document

#6824 fix: fix segmentation fault with custom loader
  .cargo/config.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_options/src/plugins/js_loader/scheduler.rs
  crates/rspack_napi/src/external_takable.rs
  crates/rspack_napi/src/lib.rs
  packages/rspack/etc/api.md
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#6826 fix: basically same codegen of arco-pro
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/use_strict_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  diffcases/arco-pro/rspack.config.js
  diffcases/arco-pro/webpack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/eval-cjs-typeof/index.js
  packages/rspack-test-tools/tests/configCases/parsing/eval-cjs-typeof/rspack.config.js
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/cjs-export-computed-property/__snapshots__/treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt
  plugin-test/css-extract/cases/hmr/expected/main.js
  scripts/diff.cjs
Labels: team, release: bug fix

#6827 fix: parse url dependency for minimized css
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#6823 docs: complete experiments docs
  packages/rspack/scripts/check-documentation-coverage.mjs
  website/docs/en/config/experiments.mdx
  website/docs/en/config/externals.mdx
  website/docs/en/config/optimization.mdx
  website/docs/en/config/output.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/externals.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: document

#6834 fix: generate suggestions if api-extractor failed the test
  lint-staged.config.mjs
  x.mjs
Labels: team, release: bug fix

#6835 fix(cli): should close compiler after building
  packages/rspack-cli/src/commands/build.ts
Labels: team, release: bug fix

#6831 refactor: cleanup JavaScript API
  packages/rspack/etc/api.md
  packages/rspack/src/Chunk.ts
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ContextModuleFactory.ts
  packages/rspack/src/Entrypoint.ts
  packages/rspack/src/FileSystem.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/RuleSetCompiler.ts
Labels: team

#6832 feat: export FetchCompileAsyncWasmPlugin for worker loader
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/FetchCompileAsyncWasmPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  website/components/PluginSupportStatusTable.tsx
  website/docs/en/guide/features/web-workers.mdx
  website/docs/en/plugins/webpack/internal-plugins.mdx
  website/docs/zh/guide/features/web-workers.mdx
  website/docs/zh/plugins/webpack/internal-plugins.mdx
Labels: team, release: feature

#6840 fix: docs ci wrong in node 16
  packages/rspack/scripts/check-documentation-coverage.mjs
Labels: team, release: bug fix

#6841 fix: source map wrong when columns is false
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
Labels: team, release: bug fix

#6829 feat: add build time executed modules to stats
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/fixtures/css/index.js
  packages/rspack-test-tools/tests/fixtures/css/style.css
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
Labels: team, release: feature

#6843 docs: complete module docs
  packages/rspack/scripts/check-documentation-coverage.mjs
  website/docs/en/config/module.mdx
  website/docs/en/config/node.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/node.mdx
Labels: team, release: document

#6845 fix: sourceMapFilename default value
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/scripts/check-documentation-coverage.mjs
  packages/rspack/src/config/defaults.ts
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: bug fix

#6846 fix: panic of module_graph.get_depth
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: bug fix

#6850 fix(plugin-preact-refresh): missing plugin type
  README.zh-CN.md
  packages/rspack-plugin-preact-refresh/src/index.ts
Labels: team, release: bug fix

#6848 docs: add preact refresh
  website/docs/en/guide/tech/_meta.json
  website/docs/en/guide/tech/preact.mdx
  website/docs/zh/guide/tech/_meta.json
  website/docs/zh/guide/tech/preact.mdx
Labels: team, release: document

#6851 refactor: use iteration to evaluate binary expressions
  crates/node_binding/src/env.rs
  crates/node_binding/src/lib.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-binary/deep.js
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-binary/deep2.js
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-binary/index.js
  x.mjs
Labels: team

#6852 fix: ci wrong in github runner
  .github/workflows/reusable-build.yml
Labels: release: bug fix

#6853 feat(napi): support js chunk hash hook
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/drive.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/test.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/JavascriptModulesPlugin.ts
  packages/rspack/src/exports.ts
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/api/plugin-api/_meta.json
  website/docs/en/api/plugin-api/javascript-modules-plugin-hooks.mdx
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/javascript-modules-plugin.mdx
  website/docs/zh/api/plugin-api/_meta.json
  website/docs/zh/api/plugin-api/javascript-modules-plugin-hooks.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/javascript-modules-plugin.mdx
Labels: team, release: feature

#6858 feat(napi): compilation chunk hash hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/test.js
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/hooks.snap.txt
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
Labels: team, release: feature

#6697 feat: root module is less prone to be wrapped in IIFE
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  packages/rspack-cli/package.json
  packages/rspack-cli/tests/build/basic/public/main.js
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  plugin-test/css-extract/cases/custom-loader-with-functional-exports/expected/main.js
  plugin-test/css-extract/cases/es-named-export-as-is-output-module/expected/main.mjs
  plugin-test/css-extract/cases/es-named-export-as-is/expected/main.js
  plugin-test/css-extract/cases/es-named-export-output-module/expected/main.mjs
  plugin-test/css-extract/cases/es-named-export/expected/main.js
  plugin-test/css-extract/cases/export-only-locals-and-es-named-export/expected/main.js
  plugin-test/css-extract/cases/export-only-locals-commonjs/expected/main.js
  plugin-test/css-extract/cases/export-only-locals/expected/main.js
  plugin-test/css-extract/cases/multiple-compiler/expected/one-main.js
  plugin-test/css-extract/cases/multiple-compiler/expected/two-main.js
  plugin-test/css-extract/cases/new-url/expected/09a1a1112c577c279435.png
  plugin-test/css-extract/cases/new-url/expected/main.js
  plugin-test/css-extract/cases/no-runtime/expected/main.js
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  webpack-test/configCases/output-module/inlined-module/index.js
  webpack-test/configCases/output-module/inlined-module/module1.js
  webpack-test/configCases/output-module/inlined-module/module2.js
  webpack-test/configCases/output-module/inlined-module/module3.js
  webpack-test/configCases/output-module/inlined-module/webpack.config.js
Labels: release: feature

#6867 fix: pre walk class blocks
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/normalCases/parsing/pre-walk-class-block/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/pre-walk-class-block/index.js
Labels: team, release: bug fix

#6866 feat: CopyRspackPlugin support function `to` option
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/src/lib.rs
  plugin-test/copy-plugin/CopyPlugin.test.js
  plugin-test/copy-plugin/__snapshots__/CopyPlugin.test.js.snap
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: team, release: feature

#6872 refactor!: remove resolve tsConfigPath
  packages/rspack-test-tools/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolve/tsconfig-paths-map/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/config/resolve.mdx
  website/docs/en/guide/tech/typescript.mdx
  website/docs/zh/config/resolve.mdx
  website/docs/zh/guide/tech/typescript.mdx
Labels: team

#6862 feat: remove styled-components, emotion and relay in builtin swc-loader
  Cargo.lock
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_loader_swc/src/transformer.rs
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-custom/custom/MyComponent.graphql.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-custom/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-custom/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-js/custom/MyComponent.graphql.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-js/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-js/relay.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-js/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-json/custom/MyComponent.graphql.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-json/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-json/relay.config.json
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-config-json/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-default/__generated__/MyComponent.graphql.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-default/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-default/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-json/__generated__/MyComponent.graphql.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-json/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-json/package.json
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-json/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-webpack-require/custom/MyComponent.graphql.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-webpack-require/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-webpack-require/mock.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-webpack-require/relay.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/relay-webpack-require/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/styled-components/Button/index.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/styled-components/Button2/index.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/styled-components/index.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/styled-components/rspack.config.js
  packages/rspack/src/config/adapterRuleUse.ts
  website/docs/en/config/builtins.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
  website/project-words.txt
Labels: team, release: feature

#6883 fix: should not eval exports in harmony
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_detection_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/parsing/eval-cjs-typeof/index.js
  packages/rspack-test-tools/tests/configCases/parsing/eval-exports-in-detection-harmony/index.js
  packages/rspack-test-tools/tests/configCases/parsing/eval-exports-in-detection-harmony/rspack.config.js
Labels: team, release: bug fix

#6884 chore: remove old tree shaking code
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/tree_shaking/analyzer.rs
  crates/rspack_core/src/tree_shaking/asset_module.rs
  crates/rspack_core/src/tree_shaking/debug_helper.rs
  crates/rspack_core/src/tree_shaking/js_module.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/symbol_graph.rs
  crates/rspack_core/src/tree_shaking/test.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/tree_shaking/webpack_ext.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#6881 refactor: worker parser plugin
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_syntax_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  webpack-test/configCases/worker/node-worker-hmr/test.filter.js
  webpack-test/configCases/worker/node-worker/test.filter.js
  webpack-test/configCases/worker/web-worker/test.filter.js
Labels: team

#6886 docs: fixed typo on compatibility list header
  website/docs/en/guide/compatibility/plugin.mdx
Labels: release: document

#6889 docs: fix rspack exports in javascript-api.mdx
  website/docs/en/api/javascript-api.mdx
Labels: release: document

#6893 docs: fix rspack exports in zh javascript-api.mdx
  website/docs/en/api/javascript-api.mdx
  website/docs/zh/api/javascript-api.mdx
Labels: team, release: document

#6892 fix: clean up dependencies and types for emotion / relay
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_to_be_deprecated.rs
  crates/rspack_swc_visitors/Cargo.toml
  crates/rspack_swc_visitors/src/emotion.rs
  crates/rspack_swc_visitors/src/lib.rs
  crates/rspack_swc_visitors/src/relay.rs
  crates/rspack_swc_visitors/src/styled_components.rs
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-loader/swc/emotion.ts
  packages/rspack/src/builtin-loader/swc/index.ts
  packages/rspack/src/builtin-loader/swc/preact.ts
  packages/rspack/src/builtin-loader/swc/relay.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/config/adapterRuleUse.ts
Labels: team, release: bug fix

#6894 revert: chore(deps): update crates (major) (#6855)
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/internal-processAssets-param-assets/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err
  plugin-test/css-extract/cases/simple-async-source-map/expected/async_css.css.map
  plugin-test/css-extract/cases/simple-async-source-map/expected/main.css.map
Labels: team

#6897 chore: refactor rspack_plugin_devtool
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_devtool/src/mapped_assets_cache.rs
  crates/rspack_plugin_devtool/src/module_filename_helpers.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_module_options_plugin.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
Labels: team

#6896 feat: generating provenance statements
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team, release: feature

#6882 fix: fix type of CssExtractRspackPluginOptions.{filename,chunkFilename}
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
Labels: release: bug fix

#6875 fix: missing bailout reason after introducing css extract plugin
  crates/rspack_plugin_extract_css/src/parser_and_generator.rs
Labels: release: bug fix

#6888 feat: add `factoryMeta` to `JsModule` and optimize `InnerGraphPlugin` for variable decl with iife
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  packages/rspack-test-tools/tests/configCases/loader/context-module/rspack.config.js
  packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/__snapshots__/treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/b.js
  packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/index.js
  packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Module.ts
Labels: release: feature

#6899 feat: simple custom worker syntax
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_util/src/merge.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/index.js
  packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/module.js
  packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/test.config.js
  packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/webpack.config.js
  packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/worker.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  webpack-test/configCases/worker/custom-worker/node_modules/web-worker.js
  webpack-test/configCases/worker/custom-worker/test.filter.js
Labels: team, release: feature

#6900 fix: compilation errors and warnings should be `RspackError`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/rspack_error.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/configCases/loader/emit-error/errors.js
  packages/rspack-test-tools/tests/configCases/loader/emit-error/index.js
  packages/rspack-test-tools/tests/configCases/loader/emit-error/loader.js
  packages/rspack-test-tools/tests/configCases/loader/emit-error/rspack.config.js
  packages/rspack-test-tools/tests/errorCases/error-map.js
  packages/rspack-test-tools/tests/errorCases/warning-map.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/RspackError.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/util/index.ts
  plugin-test/css-extract/TestCases.test.js
  plugin-test/css-extract/cases/build-in-css-support/warnings.js
Labels: release: breaking change, release: bug fix

#6887 feat: upgrade swc to latest version
  Cargo.lock
  Cargo.toml
  crates/rspack_ast_viewer/src/main.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_swc_visitors/src/define.rs
  packages/rspack-plugin-preact-refresh/client/intercept.cjs
  packages/rspack-plugin-preact-refresh/client/prefresh.cjs
  packages/rspack-plugin-preact-refresh/src/index.ts
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/2.snap.txt
Labels: team, release: feature

#6880 feat: add nwjs target to rspack config
  packages/rspack-test-tools/tests/configCases/target/node-webkit/index.js
  packages/rspack-test-tools/tests/configCases/target/node-webkit/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  website/docs/en/config/target.mdx
  website/docs/zh/config/target.mdx
Labels: release: feature

#6901 fix: sources in source map when use EvalSourceMapDevToolPlugin
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_devtool/src/module_filename_helpers.rs
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/index.js
  webpack-test/configCases/devtools/harmony-eval-source-map/test.filter.js
  webpack-test/configCases/devtools/harmony-eval/test.filter.js
  webpack-test/configCases/filename-template/module-filename-template/test.filter.js
Labels: team, release: bug fix

#6903 feat: encode filename in EvalDevToolModulePlugin
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  packages/rspack-test-tools/tests/configCases/source-map/eval-only/test.js
Labels: team, release: feature

#6864 perf(rspack_plugin_javascript): use Rayon to parse modules parallelly
  crates/rspack_plugin_javascript/src/plugin/mod.rs
Labels: release: performance

#6908 fix: CopyRspackPlugin transform option type
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/src/lib.rs
  plugin-test/copy-plugin/CopyPlugin.test.js
  plugin-test/copy-plugin/__snapshots__/CopyPlugin.test.js.snap
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: team, release: bug fix

#6904 chore: align devtool default value
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack/src/config/defaults.ts
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/config/devtool.mdx
  website/docs/zh/config/devtool.mdx
Labels: team

#6913 feat: add stats.module.dependent
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/bundler-info.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#6912 fix: devtool plugin cache conflict !macos
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
Labels: team, release: bug fix

#6916 feat: custom worker syntax for worklet
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  packages/rspack/src/config/adapter.ts
  webpack-test/configCases/worker/issue-17489/index.js
  webpack-test/configCases/worker/issue-17489/module.js
  webpack-test/configCases/worker/issue-17489/test.config.js
  webpack-test/configCases/worker/issue-17489/test.filter.js
  webpack-test/configCases/worker/issue-17489/webpack.config.js
  webpack-test/configCases/worker/issue-17489/worklet.js
  webpack-test/configCases/worker/worklet/index.js
  webpack-test/configCases/worker/worklet/module.js
  webpack-test/configCases/worker/worklet/test.config.js
  webpack-test/configCases/worker/worklet/test.filter.js
  webpack-test/configCases/worker/worklet/webpack.config.js
  webpack-test/configCases/worker/worklet/worklet-asset-1.js
  webpack-test/configCases/worker/worklet/worklet-asset-2.js
  webpack-test/configCases/worker/worklet/worklet.js
  webpack-test/helpers/createFakeWorker.js
  website/components/ApiMeta.module.scss
  website/components/ApiMeta.tsx
  website/docs/en/config/module.mdx
  website/docs/en/guide/features/web-workers.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/features/web-workers.mdx
Labels: team, release: feature

#6920 feat: add idHints and hash of stats.chunk
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#6914 docs: explain `VariableInfo`
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
Labels: release: document

#6921 fix: fix release build
  crates/rspack_loader_swc/src/lib.rs
Labels: team, release: bug fix

#6922 docs: polish up guide docs
  website/docs/en/config/resolve.mdx
  website/docs/en/guide/tech/_meta.json
  website/docs/en/guide/tech/css.mdx
  website/docs/en/guide/tech/json.mdx
  website/docs/en/guide/tech/nestjs.mdx
  website/docs/en/guide/tech/nodejs.mdx
  website/docs/en/guide/tech/preact.mdx
  website/docs/en/guide/tech/react.mdx
  website/docs/en/guide/tech/solid.mdx
  website/docs/en/guide/tech/svelte.mdx
  website/docs/en/guide/tech/typescript.mdx
  website/docs/en/guide/tech/vue.mdx
  website/docs/zh/config/resolve.mdx
  website/docs/zh/guide/tech/_meta.json
  website/docs/zh/guide/tech/css.mdx
  website/docs/zh/guide/tech/json.mdx
  website/docs/zh/guide/tech/nestjs.mdx
  website/docs/zh/guide/tech/nodejs.mdx
  website/docs/zh/guide/tech/preact.mdx
  website/docs/zh/guide/tech/react.mdx
  website/docs/zh/guide/tech/solid.mdx
  website/docs/zh/guide/tech/svelte.mdx
  website/docs/zh/guide/tech/typescript.mdx
  website/docs/zh/guide/tech/vue.mdx
Labels: release: document

#6917 docs: review devtool and entry config docs
  website/components/property-type.tsx
  website/docs/en/config/cache.mdx
  website/docs/en/config/devtool.mdx
  website/docs/en/config/entry.mdx
  website/docs/en/config/mode.mdx
  website/docs/zh/config/cache.mdx
  website/docs/zh/config/devtool.mdx
  website/docs/zh/config/entry.mdx
  website/docs/zh/config/mode.mdx
Labels: release: document

#6924 chore: clean up unused dev dependencies
  package.json
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
  website/package.json
  website/pnpm-lock.yaml
Labels: team

#6918 docs: improve webpack migration
  website/docs/en/guide/migration/webpack.mdx
  website/docs/zh/guide/migration/webpack.mdx
Labels: team, release: document

#6929 docs: fix license badge and add node badge
  README.md
  README.zh-CN.md
Labels: team, release: document

#6930 feat: support nested __webpack_exports__
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  webpack-test/configCases/library/1-use-library/test.filter.js
  webpack-test/configCases/output-module/reuse-webpack-esm-library/index.js
  webpack-test/configCases/output-module/reuse-webpack-esm-library/lib.js
  webpack-test/configCases/output-module/reuse-webpack-esm-library/react.js
  webpack-test/configCases/output-module/reuse-webpack-esm-library/webpack.config.js
Labels: team, release: feature

#6931 chore: sanitize file paths
  Cargo.toml
Labels: team

#6932 docs(config): temporary fix for mdx display bug
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: release: document

#6928 fix: use entrypoint.options.runtime as key for chunk_graph.runtime_ids map if possible
  crates/rspack_core/src/compiler/compilation.rs
Labels: release: bug fix

#6933 feat: fully support EvalSourceMapDevToolPlugin
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/eval-source-map-dev-tool-plugin/index.js
  packages/rspack-test-tools/tests/configCases/plugins/eval-source-map-dev-tool-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/index.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/rspack.config.js
  website/components/PluginSupportStatusTable.tsx
Labels: release: feature

#6910 fix!: change default value of css to false, align with webpack
  packages/playground/cases/css/chunk-loading-order/rspack.config.js
  packages/playground/cases/css/css-filename/rspack.config.js
  packages/playground/cases/css/import-double-css-files-with-empty/rspack.config.js
  packages/playground/cases/css/import-empty-css-file/rspack.config.js
  packages/playground/cases/css/render-to-body/rspack.config.js
  packages/playground/cases/react/basic/rspack.config.js
  packages/playground/cases/react/class-component/rspack.config.js
  packages/playground/cases/react/tailwindcss/rspack.config.js
  packages/playground/cases/react/with-babel/rspack.config.js
  packages/playground/cases/react/worker/rspack.config.js
  packages/playground/cases/vue3/rspack.config.js
  packages/rspack-test-tools/src/processor/builtin.ts
  packages/rspack-test-tools/src/processor/config.ts
  packages/rspack-test-tools/src/processor/diagnostic.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack-test-tools/src/processor/hash.ts
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/tests/Defaults.test.js
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/source-map/eval-only/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
  packages/rspack-test-tools/tests/defaultsCases/target_/node.js
  packages/rspack-test-tools/tests/defaultsCases/target_/nwjs.js
  packages/rspack-test-tools/tests/defaultsCases/target_/webworker.js
  packages/rspack/src/config/defaults.ts
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#6937 docs: add stats data
  website/docs/en/api/_meta.json
  website/docs/en/api/stats.mdx
  website/docs/zh/api/_meta.json
  website/docs/zh/api/stats.mdx
Labels: team, release: document

#6939 feat: support use data uri with inline loaders
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_loader_runner/src/scheme.rs
  webpack-test/cases/resolving/data-uri/test.filter.js
  webpack-test/configCases/asset-modules/resource-from-data-uri/test.filter.js
Labels: team, release: feature

#6941 docs: describe stats data structure with ts types
  website/docs/en/api/stats.mdx
  website/docs/zh/api/stats.mdx
Labels: team, release: document

#6940 feat(create-rspack): improve the templates
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react-ts/rspack.config.ts
  packages/create-rspack/template-react-ts/tsconfig.json
  packages/create-rspack/template-react/rspack.config.mjs
  packages/create-rspack/template-vanilla/rspack.config.js
  packages/create-rspack/template-vanilla/rspack.config.mjs
  packages/create-rspack/template-vue-ts/package.json
  packages/create-rspack/template-vue-ts/rspack.config.ts
  packages/create-rspack/template-vue-ts/src/main.ts
  packages/create-rspack/template-vue-ts/tsconfig.json
  packages/create-rspack/template-vue/package.json
  packages/create-rspack/template-vue/rspack.config.mjs
  packages/create-rspack/template-vue/src/main.js
  pnpm-lock.yaml
Labels: team, release: feature

#6946 fix: context passed into the `ModuleFactory` is not correct
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/normal_module_factory.rs
Labels: team, release: bug fix

#6942 docs: polish up external config
  website/docs/en/config/externals.mdx
  website/docs/zh/config/externals.mdx
Labels: release: document

#6948 feat: add contextInfo on resolveData
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_macros/src/hook.rs
  packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/a.js
  packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/b.js
  packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/index.js
  packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/rspack.config.js
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/lite-tapable/index.ts
Labels: team, release: feature

#6949 fix!: align webpack defaults
  packages/rspack-test-tools/tests/Defaults.test.js
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/experiments/both-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack/src/config/defaults.ts
Labels: team, release: bug fix

#6944 fix: sources types
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack/declarations/webpack-sources.d.ts
  packages/rspack/etc/api.md
  packages/rspack/package.json
  packages/rspack/prebundle.config.mjs
  packages/rspack/src/exports.ts
  packages/rspack/tsconfig.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#6951 feat: align stats.assets[].info
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/fixtures/asset/image.png
  packages/rspack-test-tools/tests/fixtures/asset/index.js
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  website/docs/en/api/stats.mdx
  website/docs/zh/api/stats.mdx
Labels: team, release: feature

#6953 feat: optimize filename function diagnostic
  crates/rspack_core/src/options/filename.rs
Labels: team, release: feature

#6956 fix!: align optimization.moduleIds and optimization.chunkIds when mode=none
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/src/config/defaults.ts
  plugin-test/copy-plugin/build/main.js
  plugin-test/css-extract/TestCases.test.js
Labels: team, release: breaking change, release: bug fix

#6957 feat(cli): add --profile to enable stats module profile
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/types.ts
Labels: team, release: feature

#6955 feat: stats origin moduleid
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/api/stats.mdx
  website/docs/zh/api/stats.mdx
Labels: team, release: feature

#6791 refactor: improve code style in concate module
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team

#6961 feat: align stats chunk group
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/fixtures/order/chunk-a.js
  packages/rspack-test-tools/tests/fixtures/order/chunk-b.js
  packages/rspack-test-tools/tests/fixtures/order/chunk-c.js
  packages/rspack-test-tools/tests/fixtures/order/chunk.js
  packages/rspack-test-tools/tests/fixtures/order/index.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  website/docs/en/api/stats.mdx
  website/docs/zh/api/stats.mdx
Labels: team, release: feature

#6969 docs(contributing): breaking change PR format
  website/docs/en/contribute/index.mdx
  website/docs/zh/contribute/index.mdx
Labels: team, release: document

#6970 feat!: revert default values of SwcJsMinimizer
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-default-false/a.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-default-false/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-default-false/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-default-false/test.config.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/ids.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
Labels: team, release: feature, release: breaking change

#6962 fix: fix duplicated harmony exports with named exports and re-exports star
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/a.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/b.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/rspack.config.js
Labels: team, release: bug fix

#6972 docs: update assets URLs
  README.md
  README.zh-CN.md
  crates/node_binding/README.md
  packages/create-rspack/README.md
  packages/playground/README.md
  packages/rspack-cli/README.md
  packages/rspack-dev-server/README.md
  packages/rspack-plugin-minify/README.md
  packages/rspack-plugin-preact-refresh/README.md
  packages/rspack-plugin-react-refresh/README.md
  packages/rspack-test-tools/README.md
  packages/rspack/README.md
  scripts/build-npm.cjs
  website/docs/en/blog/module-federation-added-to-rspack.mdx
  website/docs/en/misc/team/join-us.mdx
  website/docs/zh/blog/module-federation-added-to-rspack.mdx
  website/docs/zh/misc/team/join-us.mdx
  website/rspress.config.ts
Labels: team, release: document

#6959 fix!: set default value of concatenateModules to true in production mode
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/container-1-5/1-transitive-overriding/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/2-transitive-overriding/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/after-resolve-resource/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/namespace-cache/rspack.config.js
  packages/rspack-test-tools/tests/configCases/source-map/verify-es6-minify/rspack.config.js
  packages/rspack-test-tools/tests/configCases/source-map/verify-es6/index.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  packages/rspack/src/config/defaults.ts
  webpack-test/configCases/container/2-transitive-overriding/index.js
Labels: breaking change, release: breaking change

#6976 chore(workflow): should allow alpha npm tag
  .github/workflows/release.yml
Labels: team
