Repository web-infra-dev/rspack, pull requests merged in 2024-08, with the labels that each got.

#7374 feat: better diagnostic report for harmony residual dependencies
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
Labels: release: feature

#7394 fix(modern-module): compat with more export cases
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/d.mjs
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/e/bar.cjs
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/e/foo.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/e/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
Labels: release: bug fix

#7401 ci: git clean exclude
  .github/workflows/reusable-build.yml
Labels: team

#7389 feat: add memory cache of javascript plugins
  packages/rspack-test-tools/tests/compilerCases/cache-compilation.js
  packages/rspack-test-tools/tests/configCases/cache/memory/index.js
  packages/rspack-test-tools/tests/configCases/cache/memory/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/lib/Cache.ts
  packages/rspack/src/lib/cache/MemoryCachePlugin.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/docs/en/api/objects/_meta.json
  website/docs/en/api/objects/cache.mdx
  website/docs/en/api/objects/compilation.mdx
  website/docs/en/types/cache.mdx
  website/docs/zh/api/objects/_meta.json
  website/docs/zh/api/objects/cache.mdx
  website/docs/zh/api/objects/compilation.mdx
  website/docs/zh/types/cache.mdx
  website/project-words.txt
Labels: team, release: feature

#7273 feat: add partial lazyOptions.backend options
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: release: feature

#7344 perf: stats to js speed
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/identifier.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_binding_values/src/value_ref.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/errors/module-trace/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-config-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/resolve-extensions-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/unhandled-scheme-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/json/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/resolve-fail-esm.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/statsAPICases/bundler-info.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/error-chunk.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Stats.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPresetPlugin.ts
  packages/rspack/src/stats/StatsFactory.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  tests/plugin-test/css-extract/cases/build-in-css-support/warnings.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/statsCases/async-commons-chunk-auto/test.config.js
  tests/webpack-test/statsCases/import-with-invalid-options-comments/test.config.js
  tests/webpack-test/statsCases/module-trace-disabled-in-error/test.config.js
  tests/webpack-test/statsCases/module-trace-enabled-in-error/test.config.js
  tests/webpack-test/statsCases/parse-error/test.config.js
  tests/webpack-test/statsCases/preset-summary/test.config.js
  tests/webpack-test/statsCases/split-chunks-issue-6696/test.config.js
  tests/webpack-test/statsCases/split-chunks/test.config.js
Labels: team, release: performance

#7404 fix: other git clean command wrong
  .github/workflows/reusable-build.yml
Labels: team, release: bug fix

#7402 fix: render filename with dollar sign
  crates/rspack_core/src/options/filename.rs
  packages/rspack-test-tools/tests/configCases/asset/with-dollar-sign/img$1.png
  packages/rspack-test-tools/tests/configCases/asset/with-dollar-sign/img$2.png
  packages/rspack-test-tools/tests/configCases/asset/with-dollar-sign/index.js
  packages/rspack-test-tools/tests/configCases/asset/with-dollar-sign/rspack.config.js
Labels: team, release: bug fix

#7406 feat: support `compilation.chunkGroup[].isInitial()`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_group.rs
  packages/rspack-test-tools/tests/configCases/plugins/compilation-chunk-groups/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/ChunkGroup.ts
  website/docs/en/types/chunk-group.mdx
  website/docs/en/types/entrypoint.mdx
  website/docs/zh/types/chunk-group.mdx
  website/docs/zh/types/entrypoint.mdx
Labels: team, release: feature

#7407 fix: stats perf degradation in hmr
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#7408 fix(mf2): extra provide sharing data
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_dependency.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/App.js
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/node_modules/react.js
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/container/default.runtime.js
  packages/rspack/src/sharing/ProvideSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
Labels: team, release: bug fix

#7410 fix: change some `walk_block_statement` to `walk_statement`
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/normalCases/parsing/ctor-import-asi/index.js
  packages/rspack-test-tools/tests/normalCases/parsing/ctor-import-asi/util.js
Labels: release: bug fix

#7414 docs: grammar fix
  CONTRIBUTING.md
  website/docs/en/contribute/index.mdx
Labels: release: document

#7409 fix(rspack_loader_lightningcss): customMedia camelCase option
  crates/rspack_loader_lightningcss/src/config.rs
Labels: release: bug fix

#7415 docs: group api docs
  website/components/Columns.tsx
  website/docs/en/api/_meta.json
  website/docs/en/api/index.mdx
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/cache.mdx
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/en/api/javascript-api/index.mdx
  website/docs/en/api/javascript-api/logger.mdx
  website/docs/en/api/javascript-api/stats-json.mdx
  website/docs/en/api/modules/_meta.json
  website/docs/en/api/objects/_meta.json
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/en/api/runtime-api/_meta.json
  website/docs/en/api/runtime-api/hmr.mdx
  website/docs/en/api/runtime-api/module-methods.mdx
  website/docs/en/api/runtime-api/module-variables.mdx
  website/docs/en/config/target.mdx
  website/docs/en/guide/tech/typescript.mdx
  website/docs/en/types/cache.mdx
  website/docs/en/types/compilation.mdx
  website/docs/en/types/logger.mdx
  website/docs/zh/api/_meta.json
  website/docs/zh/api/index.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/cache.mdx
  website/docs/zh/api/javascript-api/compilation.mdx
  website/docs/zh/api/javascript-api/index.mdx
  website/docs/zh/api/javascript-api/logger.mdx
  website/docs/zh/api/javascript-api/stats-json.mdx
  website/docs/zh/api/loader-api.mdx
  website/docs/zh/api/modules/_meta.json
  website/docs/zh/api/objects/_meta.json
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/runtime-api/_meta.json
  website/docs/zh/api/runtime-api/hmr.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/api/runtime-api/module-variables.mdx
  website/docs/zh/config/target.mdx
  website/docs/zh/guide/tech/typescript.mdx
  website/docs/zh/types/cache.mdx
  website/docs/zh/types/compilation.mdx
  website/docs/zh/types/logger.mdx
  website/theme/components/Featured/index.tsx
Labels: team, release: document

#7411 test: enable more webpack-tests
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/chunk-index/order-multiple-entries/test.filter.js
  tests/webpack-test/configCases/css/basic-initial-only/test.filter.js
  tests/webpack-test/configCases/css/basic/test.filter.js
  tests/webpack-test/configCases/css/conflicting-order/test.filter.js
  tests/webpack-test/configCases/css/conflicting-order/webpack.config.js
  tests/webpack-test/configCases/css/css-modules-in-node/test.filter.js
  tests/webpack-test/configCases/css/css-modules/test.filter.js
  tests/webpack-test/configCases/css/exports-in-node/test.filter.js
  tests/webpack-test/configCases/css/exports/test.filter.js
  tests/webpack-test/configCases/css/external/test.filter.js
  tests/webpack-test/configCases/css/large/index.js
  tests/webpack-test/configCases/css/large/test.filter.js
  tests/webpack-test/configCases/css/urls/test.filter.js
  tests/webpack-test/helpers/FakeDocument.js
Labels: team

#7421 fix: add custom browserslist target schema
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  tests/webpack-test/configCases/ecmaVersion/browserslist-config-env/test.filter.js
  tests/webpack-test/configCases/ecmaVersion/browserslist-config-env/webpack.config.js
  tests/webpack-test/configCases/ecmaVersion/browserslist-config/test.filter.js
  tests/webpack-test/configCases/ecmaVersion/browserslist-config/webpack.config.js
  tests/webpack-test/configCases/ecmaVersion/browserslist-query/test.filter.js
  tests/webpack-test/configCases/ecmaVersion/browserslist-query/webpack.config.js
  tests/webpack-test/configCases/ecmaVersion/browserslist/test.filter.js
  tests/webpack-test/configCases/ecmaVersion/browserslist/webpack.config.js
Labels: release: bug fix

#7418 release: 1.0.0-beta.2
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7416 test: enable inner graph and concat modules for runtime condition diff test
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-concatenate-modules/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-concatenate-modules/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-concatenate-modules/webpack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-inner-graph/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-inner-graph/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-inner-graph/webpack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-optimized/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-optimized/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition-optimized/webpack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/a.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/ax.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/b.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/bx.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/c.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/concatenated-shared.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/cx.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/d1.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/d2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/dep-shared3.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/dep-shared4.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/dep.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/dep2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/shared.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/shared2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/src/super.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/runtime-condition/webpack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/test.config.js
Labels: team

#7425 ci: fix git clean wrong by filename too long
  .github/workflows/reusable-build.yml
Labels: team

#7424 fix: provided exports for add entry modules
  crates/rspack_core/src/compiler/compilation.rs
Labels: team, release: bug fix

#7396 feat: support compilation.entries
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs
  crates/rspack_binding_options/src/options/raw_dynamic_entry.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_values/src/compilation/dependency.rs
  crates/rspack_binding_values/src/compilation/entries.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/options/entry.rs
  crates/rspack_binding_values/src/options/library.rs
  crates/rspack_binding_values/src/options/mod.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_napi/src/js_values/mod.rs
  crates/rspack_napi/src/js_values/value_ref.rs
  crates/rspack_napi/src/lib.rs
  packages/rspack-test-tools/tests/configCases/compilation/entries/foo.js
  packages/rspack-test-tools/tests/configCases/compilation/entries/index.js
  packages/rspack-test-tools/tests/configCases/compilation/entries/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/config/adapter.ts
Labels: team, release: feature

#7431 fix(playground/cases): replace window.onmessage with self.onmessage in worker test case
  packages/playground/cases/react/worker/src/worker.js
Labels: release: bug fix

#7434 feat: add `compiler.rspack`
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
Labels: team, release: feature

#7423 docs: add compiler api
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/cache.mdx
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/en/api/javascript-api/logger.mdx
  website/docs/en/api/javascript-api/stats-json.mdx
  website/docs/en/types/input-file-system.mdx
  website/docs/en/types/output-file-system.mdx
  website/docs/en/types/watch-file-system.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/compiler.mdx
  website/docs/zh/api/javascript-api/logger.mdx
  website/docs/zh/types/input-file-system.mdx
  website/docs/zh/types/logger.mdx
  website/docs/zh/types/output-file-system.mdx
  website/docs/zh/types/watch-file-system.mdx
  website/project-words.txt
Labels: team, release: document

#7439 docs: add Stats API
  website/components/Collapse.scss
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/stats.mdx
  website/docs/en/types/stats.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/stats.mdx
  website/docs/zh/types/stats.mdx
Labels: team, release: document

#7440 docs: update dependencies and fix tsconfig paths
  README.md
  website/package.json
  website/pnpm-lock.yaml
  website/theme/components/Benchmark/index.tsx
  website/theme/components/ToolStack/ToolStack.tsx
  website/theme/index.tsx
  website/tsconfig.json
Labels: team, release: document

#7442 fix: remove unused JSON schemas for CSS extract plugin
  packages/rspack/src/builtin-plugin/css-extract/loader-options.json
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/css-extract/plugin-options.json
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
Labels: team, release: bug fix

#7441 perf: rule matcher allocates only if `resource_path` is not a valid UTF-8 sequence
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
Labels: team, release: performance

#7443 docs: remove duplicated part in document of JavaScript API
  website/docs/en/api/javascript-api/index.mdx
  website/docs/zh/api/javascript-api/index.mdx
Labels: team, release: document

#7445 docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack
  website/package.json
  website/pnpm-lock.yaml
Labels: release: document

#7447 fix: update deny.toml
  .github/workflows/ci.yml
  deny.toml
Labels: team, release: bug fix

#7428 feat: support seal hook in js side
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_warn_sensitive_module/src/lib.rs
  packages/rspack-test-tools/tests/configCases/compilation/entries/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
Labels: team, release: feature

#7305 feat(dev-server): export package version
  packages/rspack-dev-server/etc/api.md
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tsconfig.json
  packages/rspack/etc/api.md
  packages/rspack/src/exports.ts
  packages/rspack/tsconfig.json
Labels: release: feature

#7451 chore: remove log in mf test
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/rspack.config.js
Labels: team

#7446 docs: add guide for different CSS usages
  website/docs/en/config/experiments.mdx
  website/docs/en/guide/tech/css.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/guide/tech/css.mdx
Labels: team, release: document

#7459 docs: remove perf note for mergeDuplicateChunks
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#7462 docs: explain usage of inner graph
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#7444 refactor!: redesign minimizer plugin options
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/asset_condition.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/asset_condition.rs
  crates/rspack_util/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/rspack.config.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-ascii-only/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-all/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-disable-mangle-compress/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-drop-console/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-keep-classnames/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-keep-fn-names/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-pure-funcs/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-4797/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/swc-js-minifier/rspack.config.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts
  packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  packages/rspack/src/util/assetCondition.ts
  website/docs/en/config/optimization.mdx
  website/docs/en/guide/optimization/production.mdx
  website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/guide/optimization/production.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
Labels: team

#7458 fix: dynamic entry plugin desc to options
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/module_graph/module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_devtool/src/module_filename_helpers.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  packages/rspack-test-tools/tests/configCases/entry/dynamic-entry-layer/index.js
  packages/rspack-test-tools/tests/configCases/entry/dynamic-entry-layer/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/DynamicEntryPlugin.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#7456 fix: map of empty file should have mappings field
  Cargo.lock
  Cargo.toml
  packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/index.css
  packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/index.js
  packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/loader.js
  packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/rspack.config.js
Labels: team, release: bug fix

#7470 fix: deep merge module resolve options
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/index.js
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib/package.json
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib/right.js
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib/wrong.js
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib2/package.json
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib2/right.js
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib2/wrong.js
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/reexports.js
  packages/rspack-test-tools/tests/configCases/module/merge-resolve/rspack.config.js
Labels: team, release: bug fix

#7466 fix: stats typescript wrong
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack/etc/api.md
  packages/rspack/src/Stats.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
Labels: team, release: bug fix

#7468 docs: add detailed explanation for NormalModuleFactory hooks
  website/docs/en/api/plugin-api/normal-module-factory-hooks.mdx
  website/docs/zh/api/plugin-api/normal-module-factory-hooks.mdx
Labels: team, release: document

#7469 docs: correct some statements of code splitting and splitChunks
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
Labels: team, release: document

#7455 fix: type mismatch when using webpack plugins
  packages/rspack-cli/src/cli.ts
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#7467 feat(stats): support `moduleReason.resolvedModule`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/statsAPICases/bundler-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPresetPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/helpers/diffStats.js
  tests/webpack-test/statsCases/async-commons-chunk-auto/test.config.js
  tests/webpack-test/statsCases/graph-correctness-entries/test.config.js
  tests/webpack-test/statsCases/graph-correctness-modules/test.config.js
  tests/webpack-test/statsCases/module-reasons/test.config.js
  tests/webpack-test/statsCases/named-chunk-groups/test.config.js
  tests/webpack-test/statsCases/side-effects-issue-7428/test.config.js
  tests/webpack-test/statsCases/side-effects-simple-unused/test.config.js
  tests/webpack-test/statsCases/split-chunks-automatic-name/test.config.js
  tests/webpack-test/statsCases/split-chunks-chunk-name/test.config.js
  tests/webpack-test/statsCases/split-chunks-combinations/test.config.js
  tests/webpack-test/statsCases/split-chunks-issue-6413/test.config.js
  tests/webpack-test/statsCases/split-chunks-issue-7401/test.config.js
  tests/webpack-test/statsCases/split-chunks-keep-remaining-size/test.config.js
  tests/webpack-test/statsCases/split-chunks-min-size-reduction/test.config.js
  tests/webpack-test/statsCases/split-chunks-prefer-bigger-splits/test.config.js
  tests/webpack-test/statsCases/split-chunks/test.config.js
Labels: team, release: feature

#7472 feat(diagnostic): prettier diagnostics of magic comments
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/stats.err
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#7471 release: 1.0.0-beta.3
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7460 feat: support compilation.modules[i].blocks
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/dependency.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  packages/rspack-test-tools/tests/configCases/compilation/modules/a.js
  packages/rspack-test-tools/tests/configCases/compilation/modules/index.js
  packages/rspack-test-tools/tests/configCases/compilation/modules/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/DependenciesBlock.ts
  packages/rspack/src/Dependency.ts
  packages/rspack/src/Module.ts
Labels: team, release: feature

#7473 docs: update stats options
  website/components/property-type.tsx
  website/docs/en/config/stats.mdx
  website/docs/zh/config/stats.mdx
Labels: team, release: document

#7464 fix: patch asset info in update asset
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_asset/src/lib.rs
  packages/rspack-test-tools/tests/configCases/hooks/update-asset-patch-asset-info/index.js
  packages/rspack-test-tools/tests/configCases/hooks/update-asset-patch-asset-info/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/update-asset-patch-asset-info/test.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#7479 feat: port "module-import" external type
  Cargo.lock
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_externals/src/plugin.rs
  packages/rspack-test-tools/tests/defaultsCases/experiments/output-module.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  tests/webpack-test/configCases/externals/concatenated-module/index.js
  tests/webpack-test/configCases/externals/concatenated-module/webpack.config.js
  website/docs/en/config/externals.mdx
  website/docs/zh/config/externals.mdx
Labels: release: feature

#7481 docs: list plugin compatible +5
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#7465 feat(node-stuff): implement `node-module` shim
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  packages/rspack/etc/api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  tests/webpack-test/configCases/output-module/node-globals/cjs/file.js
  tests/webpack-test/configCases/output-module/node-globals/cjs/package.json
  tests/webpack-test/configCases/output-module/node-globals/index.js
  tests/webpack-test/configCases/output-module/node-globals/test.config.js
  tests/webpack-test/configCases/output-module/node-globals/webpack.config.js
  website/docs/en/config/node.mdx
  website/docs/zh/config/node.mdx
Labels: release: feature

#7483 feat(stats): support `isOverSizeLimit` in stats
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_size_limits/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/statsCases/import-with-invalid-options-comments/test.config.js
  tests/webpack-test/statsCases/performance-different-mode-and-target/test.config.js
  tests/webpack-test/statsCases/performance-no-async-chunks-shown/test.config.js
  tests/webpack-test/statsCases/performance-oversize-limit-error/test.config.js
  tests/webpack-test/statsCases/related-assets/test.config.js
  website/docs/en/config/stats.mdx
  website/docs/zh/config/stats.mdx
Labels: team, release: feature

#7488 docs: list compatibility status of more plugins
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#7480 docs: add some missing options
  website/components/property-type.tsx
  website/docs/en/config/cache.mdx
  website/docs/en/config/context.mdx
  website/docs/en/config/devtool.mdx
  website/docs/en/config/entry.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/config/mode.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/optimization.mdx
  website/docs/en/config/other-options.mdx
  website/docs/en/config/resolve.mdx
  website/docs/en/config/target.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/cache.mdx
  website/docs/zh/config/context.mdx
  website/docs/zh/config/devtool.mdx
  website/docs/zh/config/entry.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/mode.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/config/other-options.mdx
  website/docs/zh/config/performance.mdx
  website/docs/zh/config/resolve.mdx
  website/docs/zh/config/stats.mdx
  website/docs/zh/config/target.mdx
Labels: team, release: document

#7496 chore: remove useless swc_core features
  Cargo.lock
  crates/rspack_ast/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
Labels: team

#7498 chore(workflow): enable dependency dashboard of renovate
  .github/renovate.json5
Labels: team

#7493 fix(modern-module): export syntax detect more invalid chars
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/foo.cjs
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
Labels: release: bug fix

#7501 chore: fix missing metadata in publish
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_collections/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_hook/Cargo.toml
  crates/rspack_ids/Cargo.toml
  crates/rspack_loader_lightningcss/Cargo.toml
  crates/rspack_loader_preact_refresh/Cargo.toml
  crates/rspack_loader_react_refresh/Cargo.toml
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_testing/Cargo.toml
  crates/rspack_macros_test/Cargo.toml
  crates/rspack_napi/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_dynamic_entry/Cargo.toml
  crates/rspack_plugin_ensure_chunk_conditions/Cargo.toml
  crates/rspack_plugin_entry/Cargo.toml
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_hmr/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_ignore/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_json/Cargo.toml
  crates/rspack_plugin_lazy_compilation/Cargo.toml
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  crates/rspack_plugin_limit_chunk_count/Cargo.toml
  crates/rspack_plugin_merge_duplicate_chunks/Cargo.toml
  crates/rspack_plugin_mf/Cargo.toml
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_remove_empty_chunks/Cargo.toml
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime_chunk/Cargo.toml
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_size_limits/Cargo.toml
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_plugin_web_worker_template/Cargo.toml
  crates/rspack_plugin_worker/Cargo.toml
  crates/rspack_regex/Cargo.toml
  crates/rspack_util/Cargo.toml
  deny.toml
Labels: team

#7485 feat: splitChunks support usedExports
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/bar.js
  packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/foo.js
  packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/rspack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/shared.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: team, release: feature

#7506 docs: fix website error
  website/docs/en/guide/optimization/code-splitting.mdx
Labels: team, release: document

#7513 fix(modern-module): correct use bailout reason
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/f/bar.cjs
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/f/foo.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/f/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
Labels: release: bug fix

#7512 fix: maxInitialRequests should exists in cache groups
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_request.rs
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-7509/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-7509/node_modules/a.js
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-7509/node_modules/b.js
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-7509/node_modules/c.js
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-7509/node_modules/d.js
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-7509/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#7519 docs: remove deprecated configs
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/config/_meta.json
  website/docs/en/config/builtins.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/resolve.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/en/guide/tech/react.mdx
  website/docs/en/guide/tech/vue.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/resolve.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/tech/react.mdx
  website/docs/zh/guide/tech/vue.mdx
Labels: team, release: document

#7510 fix(hmr): replacement of optionalChain is compatible with legacy versions
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.ts
  tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js
  tests/plugin-test/css-extract/cases/hmr/expected/main.js
Labels: release: bug fix

#7517 feat: support `stats.chunkGroup[].childAssets`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_core/src/stats/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  website/docs/en/api/javascript-api/stats-json.mdx
  website/docs/zh/api/javascript-api/stats-json.mdx
Labels: team, release: feature

#7515 chore: increase publish limitation
  Cargo.toml
  justfile
Labels: team

#7482 feat: support module.size function in cacheGroups.[i].test
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group_test.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Module.ts
Labels: team, release: feature

#7525 docs: add MarsCode to online examples
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#7522 feat: expose added/removed compilation.*_dependencies to js side
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/dependencies.rs
  crates/rspack_binding_values/src/compilation/entries.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/utils/file_counter/incremental_info.rs
  crates/rspack_core/src/utils/file_counter/mod.rs
  crates/rspack_core/src/utils/mod.rs
  packages/rspack/src/Compilation.ts
Labels: team, release: feature

#7521 release: 1.0.0-beta.4
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7523 fix: use intersection runtime for concat module code gen
  crates/rspack_core/src/concatenated_module.rs
Labels: team, release: bug fix

#7534 fix: chunk hash unstable
  crates/rspack_plugin_runtime/src/helpers.rs
Labels: team, release: bug fix

#7529 fix: should insert semi after import, export, debugger and class field
  crates/rspack_plugin_javascript/src/visitors/semicolon.rs
  packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
Labels: release: bug fix

#7530 fix: check SuperProp in walk_call_expression
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/normalCases/parsing/super-member-call/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/super-member-call/index.js
Labels: release: bug fix

#7533 fix: remove useless "module" external runtime
  crates/rspack_core/src/external_module.rs
Labels: release: bug fix

#7539 fix(rust-core): no need to pass resolve_factory when using rust api
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/compiler/mod.rs
Labels: team, release: bug fix

#7524 docs: add overview flow chart for compiler hooks
  website/components/Columns.tsx
  website/components/Mermaid.scss
  website/components/Mermaid.tsx
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
  website/package.json
  website/pnpm-lock.yaml
Labels: team, release: document

#7541 fix(cli): wrong entry defaults from cli
  packages/rspack-cli/src/cli.ts
Labels: release: bug fix

#7548 docs: update benchmark data
  website/theme/components/Benchmark/index.tsx
Labels: team, release: document

#7544 perf: use browserslist-rs for lightningcss
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
  crates/rspack_loader_lightningcss/src/config.rs
  crates/rspack_loader_lightningcss/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/rspack.config.js
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts
  packages/rspack/src/config/adapterRuleUse.ts
  website/docs/en/guide/features/builtin-lightningcss-loader.mdx
  website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
Labels: team, release: performance

#7551 docs: correct LightningCssMinimizerRspackPlugin link
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#7552 docs: update chunk type
  website/docs/en/types/chunk.mdx
  website/docs/zh/types/chunk.mdx
Labels: team, release: document

#7545 fix: source map plugin module should enable by default
  crates/rspack_binding_options/src/options/raw_devtool.rs
  packages/rspack-test-tools/tests/configCases/source-map/plugin-defaults/App.jsx
  packages/rspack-test-tools/tests/configCases/source-map/plugin-defaults/index.js
  packages/rspack-test-tools/tests/configCases/source-map/plugin-defaults/rspack.config.js
Labels: team, release: bug fix

#7554 docs: list top50 plugins compatibility
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/project-words.txt
Labels: team, release: document

#7558 docs(module-federation): optimize module federation version selection
  website/docs/en/guide/features/module-federation.mdx
  website/docs/zh/guide/features/module-federation.mdx
Labels: team, release: document

#7537 feat: second param for loader hook
  packages/rspack/etc/api.md
  packages/rspack/src/NormalModule.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: feature

#7555 docs: add overview flow chart for compilation hooks
  website/components/Columns.tsx
  website/components/Mermaid.scss
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/en/config/optimization.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#7557 chore: polish some words on introduction
  website/docs/en/guide/features/loader.mdx
  website/docs/en/guide/features/module-resolution.mdx
  website/docs/en/guide/start/introduction.mdx
  website/docs/zh/guide/features/loader.mdx
  website/docs/zh/guide/features/module-resolution.mdx
  website/docs/zh/guide/start/introduction.mdx
Labels: team

#7560 docs: remove experiments flags
  website/docs/en/config/output.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/en/guide/features/module-federation.mdx
  website/docs/en/plugins/webpack/module-federation-plugin-v1.mdx
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/guide/features/module-federation.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin-v1.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: team, release: document

#7561 docs: remove examples page
  website/docs/en/guide/compatibility/_meta.json
  website/docs/en/guide/compatibility/examples.mdx
  website/docs/en/guide/compatibility/plugin.mdx
  website/docs/zh/guide/compatibility/_meta.json
  website/docs/zh/guide/compatibility/examples.mdx
  website/docs/zh/guide/compatibility/plugin.mdx
Labels: team, release: document

#7562 docs: update glossary
  website/docs/en/api/loader-api/rspack-specific-properties.mdx
  website/docs/en/misc/glossary.mdx
  website/docs/zh/api/loader-api/rspack-specific-properties.mdx
  website/docs/zh/misc/glossary.mdx
Labels: team, release: document

#7566 docs: delete benchmark page
  website/docs/en/misc/_meta.json
  website/docs/en/misc/benchmark.mdx
  website/docs/zh/misc/_meta.json
  website/docs/zh/misc/benchmark.mdx
  website/theme/components/Benchmark/index.tsx
Labels: team, release: document

#7571 test(plugin): test html plugin with basic cases of html-webpack-plugin
  .gitignore
  .prettierignore
  biome.jsonc
  crates/rspack_plugin_html/src/visitors/asset.rs
  package.json
  packages/rspack-test-tools/tests/builtinCases/plugin-html/basic/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/chunks/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/favicon/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/filename/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/inject/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/meta/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/minify/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/mpa/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/public-path/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/template+templateParameters/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/templateContent+templateParameters/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/title/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/builtins/html-inject/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-public-path-auto/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-with-output-public-path/index.js
  pnpm-lock.yaml
  tests/plugin-test/README.md
  tests/plugin-test/html-plugin/README.md
  tests/plugin-test/html-plugin/basic.test.js
  tests/plugin-test/html-plugin/fixtures/async.js
  tests/plugin-test/html-plugin/fixtures/common.js
  tests/plugin-test/html-plugin/fixtures/empty_html.html
  tests/plugin-test/html-plugin/fixtures/favicon.ico
  tests/plugin-test/html-plugin/fixtures/html-template-with-image.html
  tests/plugin-test/html-plugin/fixtures/index.js
  tests/plugin-test/html-plugin/fixtures/interpolation.html
  tests/plugin-test/html-plugin/fixtures/invalid.html
  tests/plugin-test/html-plugin/fixtures/logo.html
  tests/plugin-test/html-plugin/fixtures/logo.png
  tests/plugin-test/html-plugin/fixtures/main.css
  tests/plugin-test/html-plugin/fixtures/plain.html
  tests/plugin-test/html-plugin/fixtures/spaced_plain.html
  tests/plugin-test/html-plugin/fixtures/src/index.ejs
  tests/plugin-test/html-plugin/fixtures/template.pug
  tests/plugin-test/html-plugin/fixtures/templateParam.cjs
  tests/plugin-test/html-plugin/fixtures/templateParam.js
  tests/plugin-test/html-plugin/fixtures/test.html
  tests/plugin-test/html-plugin/fixtures/theme.js
  tests/plugin-test/html-plugin/fixtures/util.js
  tests/plugin-test/html-plugin/fixtures/webpackconfig.html
  tests/plugin-test/package.json
Labels: team

#7580 chore(deps): bump plugin-react-refresh and lite-tapable to v1.0.0
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/playground/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/package.json
  pnpm-lock.yaml
  tests/diff-test/arco-pro/package.json
Labels: team

#7581 feat: upgrade rspress version
  website/package.json
  website/pnpm-lock.yaml
  website/rspress.config.ts
Labels: release: feature

#7577 feat!: improve HtmlRspackPlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/parser.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/visitors/asset.rs
  crates/rspack_plugin_html/src/visitors/mod.rs
  crates/rspack_plugin_html/src/visitors/utils.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-html/basic/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/chunks/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/chunks/rspack.config.js
  packages/rspack-test-tools/tests/builtinCases/plugin-html/favicon/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/filename/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/inject/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/meta/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/minify/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/mpa/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/public-path/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/template+templateParameters/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/templateContent+templateParameters/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/title/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute-publicpath/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute-subdir-publicpath/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute-subdir/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative-publicpath/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative-subdir-publicpath/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative-subdir/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-meta/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/html_syntax_error/stats.err
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  tests/plugin-test/html-plugin/basic.test.js
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: feature, release: breaking change

#7584 fix: avoid inner graph top level symbol for nested __webpack_require__
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/index.js
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/lib.js
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/lib2.js
  packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/rspack.config.js
Labels: team, release: bug fix

#7567 feat(core): don't inject bundlerInfo in library mode
  packages/rspack-test-tools/tests/configCases/output/library-truthy/index.js
  packages/rspack-test-tools/tests/configCases/output/library-truthy/rspack.config.js
  packages/rspack-test-tools/tests/configCases/output/library-undefined/index.js
  packages/rspack-test-tools/tests/configCases/output/library-undefined/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/library/library.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/root-placeholder.js
  packages/rspack/src/config/defaults.ts
Labels: team, release: feature

#7547 refactor!: disable css minify in html minify and remove SwcCssMinimizerRspackPlugin
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_ast/Cargo.toml
  crates/rspack_ast/src/ast/css.rs
  crates/rspack_ast/src/ast/mod.rs
  crates/rspack_ast/src/lib.rs
  crates/rspack_ast_viewer/Cargo.toml
  crates/rspack_ast_viewer/LICENSE
  crates/rspack_ast_viewer/README.md
  crates/rspack_ast_viewer/src/main.rs
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_css_minimizer.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/parser.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_css_minimizer/src/swc_css_compiler.rs
  packages/rspack-test-tools/tests/configCases/builtins/html-minify/index.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/a.css
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/a.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/b.css
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/b.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/test.config.js
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/a.css
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/b-dir/b.css
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/b-dir/c-dir/c.css
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/entry.css
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/index.js
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/rspack.config.js
  packages/rspack-test-tools/tests/configCases/source-map/verify-bundle-css-minify-swc/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/exports.ts
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/project-words.txt
Labels: team, release: breaking change

#7568 docs: rewrite tree-shaking doc
  website/docs/en/guide/optimization/tree-shaking.mdx
  website/docs/zh/guide/optimization/tree-shaking.mdx
Labels: team, release: document

#7587 fix(node-stuff): use more conventional shim method
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
Labels: release: bug fix

#7593 docs: add performance bottlenecks
  website/docs/en/guide/optimization/profile.mdx
  website/docs/zh/guide/optimization/profile.mdx
Labels: team, release: document

#7597 fix: missing `compiler.inputFileSystem` type
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/node/NodeEnvironmentPlugin.ts
  packages/rspack/src/node/NodeWatchFileSystem.ts
Labels: team, release: bug fix

#7595 feat!: support `optimization.emitOnErrors`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_plugin_no_emit_on_errors/Cargo.toml
  crates/rspack_plugin_no_emit_on_errors/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/hooks/should-emit-1/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/should-emit-2/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/NoEmitOnErrorsPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/rspackOptionsApply.ts
  tests/webpack-test/TestCases.template.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/checkArrayExpectation.js
  website/components/PluginSupportStatusTable.tsx
  website/docs/en/config/optimization.mdx
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/no-emit-on-errors-plugin.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/no-emit-on-errors-plugin.mdx
  website/project-words.txt
Labels: team, release: feature, release: breaking change

#7600 feat(html): improve error handling
  crates/rspack_plugin_html/src/plugin.rs
  tests/plugin-test/html-plugin/basic.test.js
Labels: team, release: feature

#7601 feat: add cache for process runtime requirements
  crates/rspack_binding_values/src/codegen_result.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/old_cache/mod.rs
  crates/rspack_core/src/old_cache/occasion/code_generate.rs
  crates/rspack_core/src/old_cache/occasion/mod.rs
  crates/rspack_core/src/old_cache/occasion/process_runtime_requirements.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: team, release: feature

#7606 perf: warn case sensitive plugin
  Cargo.lock
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
  crates/rspack_plugin_warn_sensitive_module/src/lib.rs
Labels: team, release: performance

#7599 feat(rspack_plugin_swc_js_minimizer): add minify option
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/configCases/plugins/minify-disable-minify/a.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-disable-minify/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-disable-minify/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-disable-minify/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
Labels: release: feature

#7609 fix: should not panic if provide dependency is not resolved
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  packages/rspack-test-tools/tests/configCases/builtins/provide-not-resolved/errors.js
  packages/rspack-test-tools/tests/configCases/builtins/provide-not-resolved/index.js
  packages/rspack-test-tools/tests/configCases/builtins/provide-not-resolved/rspack.config.js
Labels: team, release: bug fix

#7607 chore: fix version in case sensitive plugin
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
Labels: team

#7619 docs: keep webpack dependency in some cases
  website/docs/en/guide/migration/webpack.mdx
  website/docs/en/guide/tech/vue.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/tech/vue.mdx
Labels: team, release: document

#7532 feat(core): bump rspack_resolver 0.2.0
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
Labels: release: feature

#7615 fix: remove the unnecessary logic for inserting semicolons
  crates/rspack_plugin_javascript/src/visitors/semicolon.rs
Labels: release: bug fix

#7626 test: add more test cases for asi with sequence expressions
  packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
Labels: team

#7617 fix: allow `null` and `undefined` in EnvironmentPlugin
  packages/rspack/etc/api.md
  packages/rspack/src/lib/EnvironmentPlugin.ts
Labels: release: bug fix

#7627 docs: update eslint-webpack-plugin compatible status
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#7628 chore: remove `Compilation.updateAsset` comment
  packages/rspack/src/Compilation.ts
Labels: team

#7629 docs: filter rspack specific test cases
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/testing-rspack.mdx
Labels: team, release: document

#7631 refactor(core): remove unnecessary enum for resolver
  crates/rspack_core/src/resolver/resolver_impl.rs
Labels: team

#7625 docs: migrating from rspack 0.x
  website/docs/en/guide/migration/_meta.json
  website/docs/en/guide/migration/rspack_0.x.mdx
  website/docs/zh/guide/migration/_meta.json
  website/docs/zh/guide/migration/rspack_0.x.mdx
Labels: team, release: document

#7594 refactor: add more clippy rule
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/cutout/fix_build_meta.rs
  crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/old_cache/occasion/create_chunk_assets.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/utils/compile_boolean_matcher.rs
  crates/rspack_core/src/utils/find_graph_roots.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/runtime.rs
Labels: team

#7630 perf: improve performance of eval-source-map
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
Labels: team, release: performance

#7638 chore(workflow): allow renovate to bump npm dependencies
  .github/renovate.json5
Labels: team

#7640 fix(mf2): correct mf shared options
  packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/index.js
  packages/rspack/src/container/default.runtime.js
Labels: release: bug fix

#7649 feat(deps): bump @module-federation/runtime-tools 0.5.1
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team, release: feature

#7650 fix: unexpected ASI generation with sequence expression
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  tests/webpack-test/cases/parsing/sequence-expression-asi/a.js
  tests/webpack-test/cases/parsing/sequence-expression-asi/index.js
Labels: team, release: bug fix

#7654 fix: wrong `builtin:swc-loader` source maps if `inputSourceMap` is provided
  Cargo.lock
  Cargo.toml
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/a.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/prev-loader.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/a.jsx
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/prev-loader.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/rspack.config.js
Labels: team, release: bug fix

#7652 docs: add notice about htmlRspackPlugin not support ejs syntax
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: document

#7655 fix: rslib link should be its github repo
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: release: bug fix

#7651 feat(mf2): add shareStrategy
  packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/App.js
  packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/node_modules/react.js
  packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/default.runtime.js
  website/docs/en/plugins/webpack/module-federation-plugin-v1.mdx
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin-v1.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: release: feature

#7656 fix(html): emit error when param not found
  Cargo.lock
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/builtins/html-param-not-found/errors.js
  packages/rspack-test-tools/tests/configCases/builtins/html-param-not-found/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-param-not-found/rspack.config.js
  tests/plugin-test/html-plugin/basic.test.js
Labels: team, release: bug fix

#7657 fix(mf2): initializeSharingInitTokens should be object
  packages/rspack/src/container/default.runtime.js
Labels: release: bug fix

#7653 feat: add minify option to lightningcss-loader
  crates/node_binding/binding.d.ts
  crates/rspack_loader_lightningcss/src/config.rs
  crates/rspack_loader_lightningcss/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/minify/index.css
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/minify/index.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/minify/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-loader/lightningcss/index.ts
  website/docs/en/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
Labels: release: feature

#7661 feat(core)!: change dojang default escape|unescape to lodash.template syntax
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  tests/plugin-test/html-plugin/basic.test.js
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: feature, release: breaking change

#7662 release: 1.0.0-rc.0
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/statsAPICases/bundler-info.js
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7666 fix: `Path` pitfall for loader type
  crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
  packages/rspack/src/loader-runner/index.ts
  tests/webpack-test/cases/loaders/cjs-loader-type/index.js
  tests/webpack-test/cases/loaders/cjs-loader-type/loader.cjs
  tests/webpack-test/cases/loaders/cjs-loader-type/loader.js
  tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/cjs/loader.cjs
  tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/cjs/loader.js
  tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/cjs/package.json
  tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/esm/loader.cjs
  tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/esm/package.json
Labels: team, release: bug fix

#7664 fix(security): DOM clobbering in auto public path
  crates/rspack_plugin_hmr/src/runtime/hot_module_replacement.js
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/javascript_hot_module_replacement.js
  package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js
  packages/rspack-test-tools/tests/hotCases/css/recovery-cacheable/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/src/config/defaults.ts
  pnpm-lock.yaml
  tests/diff-test/arco-pro/package.json
  tests/plugin-test/copy-plugin/build/main.js
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$930222abb80b249ed386$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.js
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$930222abb80b249ed386$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/content-entries-with-same-import/expected/one_js.$023ac0d4bb230615c43315b6b064c1b7$.css
  tests/plugin-test/css-extract/cases/content-entries-with-same-import/expected/two_js.$72a8dd45a3f95df1891fb79708a5f852$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryA.$b5f353a4b96240d34000ec2751896fb8$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryB.$8c016b564d25bd3d0bfd87e38be3421f$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/1.main.$aacd0ad1c42de0978eb78d1b45f776f4$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/2.main.$7a8f6d01ccfee2f287001c866d1d099c$.css
  tests/plugin-test/css-extract/cases/dependOn-multiple-files-per-entry/expected/common.js
  tests/plugin-test/css-extract/cases/dependOn-multiple-files-per-entry/expected/entry1.js
  tests/plugin-test/css-extract/cases/dependOn/expected/common.js
  tests/plugin-test/css-extract/cases/dependOn/expected/entry1.js
  tests/plugin-test/css-extract/cases/es-named-export-as-is-output-module/expected/main.mjs
  tests/plugin-test/css-extract/cases/es-named-export-as-is/expected/main.js
  tests/plugin-test/css-extract/cases/es-named-export-output-module/expected/main.mjs
  tests/plugin-test/css-extract/cases/es-named-export/expected/main.js
  tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js
  tests/plugin-test/css-extract/cases/hmr/expected/main.js
  tests/plugin-test/css-extract/cases/insert-function/expected/main.js
  tests/plugin-test/css-extract/cases/insert-function/expected/src_inject_css.js
  tests/plugin-test/css-extract/cases/insert-string/expected/main.js
  tests/plugin-test/css-extract/cases/insert-string/expected/src_inject_css.js
  tests/plugin-test/css-extract/cases/insert-undefined/expected/main.js
  tests/plugin-test/css-extract/cases/insert-undefined/expected/src_inject_css.js
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/plugin-test/css-extract/cases/js-hash/expected/style.$0807b2b8361eb34664fe98ac7f3ec0fe$.1.css
  tests/plugin-test/css-extract/cases/js-hash/expected/style.$0f94f124eac78739b528d3fc9e386fe8$.2.css
  tests/plugin-test/css-extract/cases/multiple-compiler/expected/one-main.js
  tests/plugin-test/css-extract/cases/multiple-compiler/expected/two-main.js
  tests/plugin-test/css-extract/cases/new-url/expected/main.js
  tests/plugin-test/css-extract/cases/no-runtime/expected/async.js
  tests/plugin-test/css-extract/cases/no-runtime/expected/main.js
  tests/plugin-test/css-extract/cases/pathinfo-devtool-source-map/expected/main.css
  tests/plugin-test/css-extract/cases/pathinfo/expected/main.css
  tests/plugin-test/css-extract/cases/runtime/expected/runtime~main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/helpers/CurrentScript.js
Labels: team, release: bug fix

#7667 docs: use --experimental-transform-types load tsconfig
  website/docs/en/config/index.mdx
  website/docs/zh/config/index.mdx
Labels: team, release: document

#7675 fix: resolve issue with external array not working in UMD libraryTarget
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/index.js
  packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/test.config.js
Labels: release: bug fix

#7669 docs(mf): add `@module-federation/sdk` to FAQ
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: team, release: document

#7676 fix(deps): bump webpack-dev-middleware v7.4.2 to fix assetsInfo
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#7677 fix(create-rspack): should not replace plugin-react-refresh version
  packages/create-rspack/index.js
Labels: team, release: bug fix

#7679 refactor: use trait for dependencyConditionFn for better cacheable
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
Labels: team

#7680 fix(cli): peerDep allows @rspack/core@1.0
  packages/rspack-cli/package.json
Labels: team, release: bug fix

#7681 fix: reuse codegen results only for new incremental
  crates/rspack_core/src/compiler/hmr.rs
Labels: team, release: bug fix

#7670 fix: fallback to next main field when resolve failed
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/index.js
  packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/node_modules/invalid-pkg/exist.js
  packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/node_modules/invalid-pkg/package.json
  packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/rspack.config.js
Labels: team, release: bug fix
