Repository web-infra-dev/rspack, pull requests merged in 2024-07, with the labels that each got.

#6991 chore: disable renovate update for swc
  .github/renovate.json5
Labels: team

#6992 chore: add deprecated notice for rspack-plugin-minify
  crates/node_binding/README.md
  packages/rspack-plugin-minify/README.md
Labels: team

#6995 feat: enable lightning css minimizer error recovery
  crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
  packages/rspack-test-tools/src/case/diagnostic.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/dynamic-import-non-exist-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/fully-specified-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-config-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/prefer-relative-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/resolve-extensions-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/invalid.css
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/unhandled-scheme-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/basic/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/json/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lexically_name_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/reserved_name_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/return-outside-function/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/tla_disable_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/tla_esm_error/stats.err
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts
  website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
Labels: team, release: feature

#6997 fix: experiments css exports convention tree shaking
  crates/rspack_plugin_css/src/dependency/export.rs
  crates/rspack_plugin_css/src/dependency/local_ident.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/index.js
  packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/style.module.css
  packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/test.config.js
  packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/webpack.config.js
  packages/rspack/src/config/adapter.ts
Labels: team, release: bug fix

#6999 docs: complete the module methods
  website/docs/en/api/modules/module-methods.mdx
  website/docs/zh/api/modules/module-methods.mdx
Labels: team, release: document

#6980 docs: module variables
  website/components/Columns.tsx
  website/docs/en/api/modules/module-variables.mdx
  website/docs/zh/api/modules/module-variables.mdx
  website/project-words.txt
Labels: team, release: document

#7002 docs: add specifics for api meta
  website/components/ApiMeta.module.scss
  website/components/ApiMeta.tsx
  website/docs/en/api/loader-api/rspack-specific-properties.mdx
  website/docs/en/api/modules/module-methods.mdx
  website/docs/en/api/modules/module-variables.mdx
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/api/loader-api/rspack-specific-properties.mdx
  website/docs/zh/api/modules/module-variables.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
Labels: team, release: document

#7003 perf: make picking concatenable modules parallel
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team, release: performance

#6998 feat: support nmf resolve hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/a.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/b.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/c.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/resource.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/test.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/NormalModuleFactory.ts
  website/components/Columns.tsx
  website/docs/en/api/plugin-api/normal-module-factory-hooks.mdx
  website/docs/zh/api/plugin-api/normal-module-factory-hooks.mdx
Labels: team, release: feature

#6993 fix: align source name conflict handling
  Cargo.lock
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/source-map/conflict/a.js
  packages/rspack-test-tools/tests/configCases/source-map/conflict/b.js
  packages/rspack-test-tools/tests/configCases/source-map/conflict/common.js
  packages/rspack-test-tools/tests/configCases/source-map/conflict/index.js
  packages/rspack-test-tools/tests/configCases/source-map/conflict/rspack.config.js
  tests/plugin-test/css-extract/cases/devtool-source-map-from-loaders/expected/main.css.map
  tests/plugin-test/css-extract/cases/devtool-source-map/expected/main.css.map
  tests/plugin-test/css-extract/cases/pathinfo-devtool-source-map/expected/main.css.map
Labels: release: bug fix

#6989 feat: support splitChunkSizes type
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_size.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/rspack-issue-4331/rspack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/rspack-issue-4331/src/a.js
  packages/rspack-test-tools/tests/configCases/split-chunks/rspack-issue-4331/src/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/rspack-issue-4331/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/util/SplitChunkSize.ts
  tests/plugin-test/copy-plugin/build/main.js
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: release: feature

#7011 docs: add Module Federation to features list
  README.md
  README.zh-CN.md
  website/docs/en/guide/start/introduction.mdx
  website/docs/en/index.md
  website/docs/zh/guide/start/introduction.mdx
  website/docs/zh/index.md
Labels: team, release: document

#6161 feat: refresh overlay
  packages/rspack-plugin-react-refresh/api-extractor.json
  packages/rspack-plugin-react-refresh/client/errorOverlayEntry.js
  packages/rspack-plugin-react-refresh/client/overlay/components/CompileErrorTrace.js
  packages/rspack-plugin-react-refresh/client/overlay/components/PageHeader.js
  packages/rspack-plugin-react-refresh/client/overlay/components/RuntimeErrorFooter.js
  packages/rspack-plugin-react-refresh/client/overlay/components/RuntimeErrorHeader.js
  packages/rspack-plugin-react-refresh/client/overlay/components/RuntimeErrorStack.js
  packages/rspack-plugin-react-refresh/client/overlay/components/Spacer.js
  packages/rspack-plugin-react-refresh/client/overlay/containers/CompileErrorContainer.js
  packages/rspack-plugin-react-refresh/client/overlay/containers/RuntimeErrorContainer.js
  packages/rspack-plugin-react-refresh/client/overlay/index.js
  packages/rspack-plugin-react-refresh/client/overlay/theme.js
  packages/rspack-plugin-react-refresh/client/overlay/utils.js
  packages/rspack-plugin-react-refresh/client/utils/ansi-html.js
  packages/rspack-plugin-react-refresh/client/utils/errorEventHandlers.js
  packages/rspack-plugin-react-refresh/client/utils/formatWebpackErrors.js
  packages/rspack-plugin-react-refresh/client/utils/retry.js
  packages/rspack-plugin-react-refresh/etc/api.md
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-plugin-react-refresh/src/index.ts
  packages/rspack-plugin-react-refresh/src/options.ts
  packages/rspack-plugin-react-refresh/src/sockets/WDSSocket.ts
  packages/rspack-plugin-react-refresh/src/sockets/utils/getCurrentScriptSource.ts
  packages/rspack-plugin-react-refresh/src/sockets/utils/getSocketUrlParts.ts
  packages/rspack-plugin-react-refresh/src/sockets/utils/getUrlFromParts.ts
  packages/rspack-plugin-react-refresh/src/sockets/utils/getWDSMetadata.ts
  packages/rspack-plugin-react-refresh/src/utils/getAdditionalEntries.ts
  packages/rspack-plugin-react-refresh/src/utils/getSocketIntegration.ts
  packages/rspack-plugin-react-refresh/tsconfig.build.json
  pnpm-lock.yaml
Labels: release: feature

#7009 docs: improve externals plugin doc
  website/docs/en/plugins/webpack/externals-plugin.mdx
  website/docs/zh/plugins/webpack/externals-plugin.mdx
Labels: team, release: document

#7010 docs: add prefetch&preload modules
  website/docs/en/api/modules/module-methods.mdx
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/zh/api/modules/module-methods.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
Labels: team, release: document

#7014 fix: should not generate pure expression if test is failed
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7012/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7012/rspack.config.js
Labels: team, release: bug fix

#7015 docs: default value in node config
  website/docs/en/_meta.json
  website/docs/en/config/node.mdx
  website/docs/zh/_meta.json
  website/docs/zh/config/node.mdx
Labels: team, release: document

#7019 refactor!: move global trace export to experiments
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack/etc/api.md
  packages/rspack/src/exports.ts
  website/docs/en/contribute/development/profiling.md
  website/docs/zh/contribute/development/profiling.md
Labels: team, breaking change

#7025 chore(module-federation): update @module-federation/runtime-tools to 0.2.3 version
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#7021 fix: use lite-tapable for enhanced-resolve
  packages/rspack-lite-tapable/etc/api.md
  packages/rspack-lite-tapable/src/index.ts
  packages/rspack-lite-tapable/temp/api.md
  packages/rspack/etc/api.md
  packages/rspack/prebundle.config.mjs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/stats/StatsFactory.ts
Labels: team, release: bug fix

#5164 fix: fix npm script in window
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/create-rspack/template-vanilla/package.json
  packages/create-rspack/template-vue-ts/package.json
  packages/create-rspack/template-vue/package.json
  pnpm-lock.yaml
Labels: release: bug fix

#7018 docs: update compilation hooks
  website/docs/en/api/plugin-api/_meta.json
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/en/api/plugin-api/stats-hooks.mdx
  website/docs/zh/api/plugin-api/_meta.json
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/stats-hooks.mdx
Labels: team, release: document

#7027 feat: align webpack target and stats api
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/options/target.rs
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Stats.ts
Labels: team, release: feature

#7036 fix: pnpm install failed in ci
  .github/actions/pnpm-cache/action.yml
Labels: team, release: bug fix

#7037 docs: add fetch priority
  website/docs/en/api/modules/module-methods.mdx
  website/docs/zh/api/modules/module-methods.mdx
Labels: team, release: document

#7038 chore: release force use github runner
  .github/workflows/get-runner-labels.yml
  .github/workflows/release-canary.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
Labels: team

#7028 fix: wrong cjs exports type caused unexpected exports presence
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/cjs.js
  packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/index.js
Labels: team, release: bug fix

#7041 test: enable cases/context/issue-10969
  tests/webpack-test/cases/context/issue-10969/index.js
  tests/webpack-test/cases/context/issue-10969/test.filter.js
Labels: team

#7044 fix: add warning for context module flag g and y
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  tests/webpack-test/cases/context/issue-5750/test.filter.js
  tests/webpack-test/cases/parsing/issue-627/test.filter.js
Labels: team, release: bug fix

#7040 fix: deduplicate extracted comments
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/configCases/plugins/minify-extract-comments/index.js
Labels: release: bug fix

#7046 chore: release run macos test when arch match
  .github/workflows/reusable-build.yml
Labels: team

#7042 release: 1.0.0-alpha.1
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7048 chore(lite-tapable): clean up temp/api.md
  .gitignore
  packages/rspack-lite-tapable/temp/api.md
Labels: team

#7051 chore: nightly release upload webpack-test metric data
  tests/webpack-test/scripts/generate.js
Labels: team

#7047 fix: detect magic comments around expr
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  tests/webpack-test/configCases/trusted-types/custom-policy-name/test.filter.js
  tests/webpack-test/configCases/trusted-types/default-policy-name/test.filter.js
  tests/webpack-test/configCases/trusted-types/no-policy-name/test.filter.js
  tests/webpack-test/configCases/trusted-types/no-trusted-types/test.filter.js
Labels: team, release: bug fix

#7053 chore: nightly release add write contents permission
  .github/workflows/release-nightly.yml
Labels: team

#7052 fix: truncateArgs is not a function
  packages/rspack/src/node/nodeConsole.ts
Labels: team, release: bug fix

#7035 docs: add compare with parcel section
  website/docs/en/guide/start/introduction.mdx
  website/docs/zh/guide/start/introduction.mdx
  website/project-words.txt
Labels: team, release: document

#7054 chore: add provenance option to pnpm publish
  scripts/release/publish.mjs
Labels: team

#7061 chore: migrate lint to biome
  .github/workflows/ci.yml
  biome.json
  lint-staged.config.mjs
  package.json
  packages/create-rspack/template-vue-ts/src/shims-vue.d.ts
  pnpm-lock.yaml
Labels: team

#7063 fix(core): migrate to rspack_resolver
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  website/docs/en/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/debugging.mdx
Labels: team, release: bug fix

#7064 fix: zod is pre-bundled twice
  packages/rspack/prebundle.config.mjs
Labels: team, release: bug fix

#7056 fix: magic comment warning
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/stats.err
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#7069 refactor!: use swc_plugin_prefresh instead of builtin swc plugin
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_loader_swc/src/transformer.rs
  crates/rspack_swc_visitors/Cargo.toml
  crates/rspack_swc_visitors/src/lib.rs
  crates/rspack_swc_visitors/src/preact.rs
  crates/swc_plugin_preact/Cargo.toml
  crates/swc_plugin_preact/src/lib.rs
  crates/swc_plugin_preact/tests/fixtures/basic/input.js
  crates/swc_plugin_preact/tests/fixtures/basic/output.js
  crates/swc_plugin_preact/tests/fixtures/import_custom_preact/input.js
  crates/swc_plugin_preact/tests/fixtures/import_custom_preact/output.js
  crates/swc_plugin_preact/tests/fixtures/import_default/input.js
  crates/swc_plugin_preact/tests/fixtures/import_default/output.js
  crates/swc_plugin_preact/tests/fixtures/import_lib_computed/input.js
  crates/swc_plugin_preact/tests/fixtures/import_lib_computed/output.js
  crates/swc_plugin_preact/tests/fixtures/import_named/input.js
  crates/swc_plugin_preact/tests/fixtures/import_named/output.js
  crates/swc_plugin_preact/tests/fixtures/import_namespace/input.js
  crates/swc_plugin_preact/tests/fixtures/import_namespace/output.js
  crates/swc_plugin_preact/tests/fixtures/local/input.js
  crates/swc_plugin_preact/tests/fixtures/local/output.js
  crates/swc_plugin_preact/tests/fixtures/multiple/input.js
  crates/swc_plugin_preact/tests/fixtures/multiple/output.js
  crates/swc_plugin_preact/tests/fixtures/param/input.js
  crates/swc_plugin_preact/tests/fixtures/param/output.js
  crates/swc_plugin_preact/tests/fixtures/value/input.js
  crates/swc_plugin_preact/tests/fixtures/value/output.js
  crates/swc_plugin_preact/tests/test.rs
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/rspack.config.js
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/rspack.config.js
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-loader/swc/index.ts
  packages/rspack/src/builtin-loader/swc/preact.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/config/adapterRuleUse.ts
  pnpm-lock.yaml
  website/docs/en/guide/tech/preact.mdx
  website/docs/zh/guide/tech/preact.mdx
Labels: team, release: breaking change

#7071 fix: revert detect statement level sequence expression
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/normalCases/parsing/asi-sequence-expression/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/asi-sequence-expression/index.js
Labels: team, release: bug fix

#7043 refactor: port inner graph
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/state.rs
  crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  packages/rspack-test-tools/tests/treeShakingCases/issue-7016/__snapshots__/treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/issue-7016/index.js
  packages/rspack-test-tools/tests/treeShakingCases/issue-7016/rspack.config.js
Labels: team

#7073 docs: add baidu verify file for SEO optimization
  website/docs/public/baidu_verify_codeva-bE2dFTowhk.html
Labels: team, release: document

#7074 docs: fix netlify redirect cause baidu verify failed
  website/docs/public/baidu_verify_codeva-bE2dFTowhk.html
  website/project-words.txt
  website/rspress.config.ts
Labels: team, release: document

#7059 perf: cache `compilation.entrypoints`
  packages/rspack/src/Compilation.ts
Labels: team, release: performance

#7076 docs: update license ui
  website/components/webpack-license.tsx
Labels: team, release: document

#7083 docs: update teams page, add Rsfamily members
  website/components/RandomMemberList.module.scss
  website/components/RandomMemberList.tsx
  website/docs/en/misc/team/core-team.mdx
  website/docs/zh/misc/team/core-team.mdx
  website/project-words.txt
Labels: team, release: document

#7086 feat!: remove `builtins.provide`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_to_be_deprecated.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/builtins.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/mod.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_loader_swc/src/transformer.rs
  crates/rspack_plugin_extract_css/src/parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/provide_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_swc_visitors/Cargo.toml
  crates/rspack_swc_visitors/src/define.rs
  crates/rspack_swc_visitors/src/import.rs
  crates/rspack_swc_visitors/src/lib.rs
  crates/rspack_swc_visitors/src/react.rs
  crates/swc_plugin_import/src/lib.rs
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-loader/swc/index.ts
  packages/rspack/src/builtin-loader/swc/pluginImport.ts
  packages/rspack/src/builtin-loader/swc/react.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/zod.ts
  x.mjs
Labels: team, breaking change, release: feature, release: breaking change

#7079 fix: Add missing code for compatibility plugin
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/a.js
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/b.js
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/index.js
Labels: release: bug fix

#7082 fix: panic when get max target in find target
  crates/rspack_core/src/exports_info.rs
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/index.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/core.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/empty.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/lib.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/package.json
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/queryclient.js
  packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/rspack.config.js
Labels: team, release: bug fix

#7088 perf: enable "fat" LTO for production release
  .github/workflows/release.yml
  Cargo.toml
  crates/node_binding/package.json
  crates/node_binding/scripts/build.js
  package.json
Labels: team, release: performance

#7039 feat(rspack_core): nmf resolve in schema hook
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_values/src/normal_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_loader_runner/src/scheme.rs
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_schemes/src/file_uri.rs
  packages/rspack-test-tools/tests/configCases/code-generation/path-ends-with-star/rspack.config.js
Labels: release: feature

#6877 feat: tree shakable output for module library
  .prettierignore
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/plugin/context.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  tests/webpack-test/configCases/library/0-create-library/webpack.config.js
  tests/webpack-test/configCases/library/1-use-library/default-test-modern-module.js
  tests/webpack-test/configCases/library/1-use-library/test.filter.js
  tests/webpack-test/configCases/library/1-use-library/webpack.config.js
Labels: release: feature

#7085 feat: downgrade container runtime to es2015
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  packages/rspack/scripts/prepare-container-runtime.js
  pnpm-lock.yaml
  scripts/package.json
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: team, release: feature

#4945 feat!: use native resolver in loader
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/resolver_factory.rs
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/options/mod.rs
  crates/rspack_binding_values/src/options/raw_resolve.rs
  crates/rspack_binding_values/src/resolver.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Resolver.ts
  packages/rspack/src/ResolverFactory.js
  packages/rspack/src/ResolverFactory.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/configCases/loader/issue-4672/index.js
  packages/rspack/tests/configCases/loader/issue-4672/index.ts
  packages/rspack/tests/configCases/loader/issue-4672/loader.js
  packages/rspack/tests/configCases/loader/issue-4672/tsconfig.json
  packages/rspack/tests/configCases/loader/issue-4672/webpack.config.js
Labels: release: feature

#7068 feat: to function can return Promise
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
Labels: team, release: feature

#7105 docs: enable sitemap for SEO
  website/package.json
  website/pnpm-lock.yaml
  website/rspress.config.ts
Labels: team, release: document

#7104 perf: remove unneeded string clone
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/context.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/template.rs
  crates/rspack_core/src/utils/identifier.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_util/src/atom.rs
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/merge.rs
Labels: release: performance

#7108 feat: support more features of `DefinePlugin`
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/builtins/define/index.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin-bigint/index.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin-bigint/webpack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin/dir/a.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin/index.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin/webpack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-7084/index.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-7084/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/define-plugin/stats.err
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/DefinePlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  website/docs/en/plugins/webpack/define-plugin.mdx
  website/docs/zh/plugins/webpack/define-plugin.mdx
Labels: release: feature

#7109 perf: reduce `get_scheme` allocation
  crates/rspack_loader_runner/src/scheme.rs
Labels: team, release: performance

#7092 feat(create-rspack): add custom template pkg name
  packages/create-rspack/index.js
Labels: release: feature

#7101 fix: support css nonce
  crates/rspack_plugin_css/src/runtime/css_loading.js
  crates/rspack_plugin_extract_css/src/runtime/css_load.js
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/web/nonce/chunk.css
  packages/rspack-test-tools/tests/configCases/web/nonce/chunk.js
  packages/rspack-test-tools/tests/configCases/web/nonce/index.js
  packages/rspack-test-tools/tests/configCases/web/nonce/nonce.js
  packages/rspack-test-tools/tests/configCases/web/nonce/rspack.config.js
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$2380e69aff7ffd91bf3b$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$2380e69aff7ffd91bf3b$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/hmr/expected/main.js
  tests/plugin-test/css-extract/cases/insert-function/expected/main.js
  tests/plugin-test/css-extract/cases/insert-string/expected/main.js
  tests/plugin-test/css-extract/cases/insert-undefined/expected/main.js
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
Labels: team, release: bug fix

#7113 fix(mf): runtime should respect output environment
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/expose_runtime_module.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/rspack/dynamic-import/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/a.js
  packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/bootstrap.js
  packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/index.js
  packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/test.config.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#7102 feat: reduce unnecessary exports runtime
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/chunk_prefetch_preload.rs
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  tests/plugin-test/copy-plugin/build/main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/configCases/library/1-use-library/webpack.config.js
Labels: release: feature

#7106 refactor: report `Module not found` instead of `Resolve Error`
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-loader/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/dynamic-import-non-exist-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/entry-runtime-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/fully-specified-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-entry/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/prefer-relative-resolve-suggestions/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/resolve-extensions-error/stats.err
  packages/rspack-test-tools/tests/errorCases/error-map.js
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/resolve-fail-esm.js
  tests/webpack-test/Compiler.test.js
  tests/webpack-test/cases/chunks/inline-options/index.js
  tests/webpack-test/cases/chunks/inline-options/test.filter.js
  tests/webpack-test/cases/errors/crash-missing-import/test.filter.js
  tests/webpack-test/cases/errors/harmony-import-missing/test.filter.js
  tests/webpack-test/cases/errors/harmony-import-missing2/test.filter.js
  tests/webpack-test/cases/errors/loader-error-warning/test.filter.js
  tests/webpack-test/cases/errors/mjs-non-fully-specified/errors.js
  tests/webpack-test/cases/errors/mjs-non-fully-specified/test.filter.js
  tests/webpack-test/cases/errors/module-request/test.filter.js
  tests/webpack-test/cases/json/default-default-with-concatenation/test.filter.js
  tests/webpack-test/cases/json/import-with-default-with-concatenation/test.filter.js
  tests/webpack-test/cases/loaders/import-module/test.filter.js
  tests/webpack-test/cases/loaders/resolve/test.filter.js
  tests/webpack-test/cases/parsing/evaluate/index.js
  tests/webpack-test/cases/parsing/evaluate/test.filter.js
  tests/webpack-test/cases/parsing/issue-2600/test.filter.js
  tests/webpack-test/cases/resolving/context/test.filter.js
  tests/webpack-test/cases/runtime/error-handling/test.filter.js
  tests/webpack-test/cases/runtime/missing-module-exception/test.filter.js
  tests/webpack-test/cases/runtime/missing-module-syntax-error/test.filter.js
  tests/webpack-test/cases/scope-hoisting/circular-root-export/test.filter.js
Labels: team

#7117 docs: polish migration wordings
  website/docs/en/blog/announcing-0-6.mdx
  website/docs/en/guide/migration/cra.mdx
  website/docs/en/guide/migration/storybook.mdx
  website/docs/en/guide/migration/webpack.mdx
Labels: team, release: document

#7118 perf: reduce alloc for bailout reason
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team, release: performance

#7119 fix: should not shake used json fields
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  packages/rspack-test-tools/tests/configCases/tree-shaking/json-with-prototype-methods/index.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/json-with-prototype-methods/rspack.config.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/json-with-prototype-methods/value.json
Labels: team, release: bug fix

#7114 docs: use CssExtractRspackPlugin and experiments.css together
  website/docs/en/guide/migration/webpack.mdx
  website/docs/en/guide/tech/css.mdx
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/tech/css.mdx
  website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
Labels: team, release: document

#7121 release: 1.0.0-alpha.3
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7123 feat(stats): support `StatsError.moduleTrace`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/errors/module-trace/a.js
  packages/rspack-test-tools/tests/configCases/errors/module-trace/b.js
  packages/rspack-test-tools/tests/configCases/errors/module-trace/c.js
  packages/rspack-test-tools/tests/configCases/errors/module-trace/errors.js
  packages/rspack-test-tools/tests/configCases/errors/module-trace/index.js
  packages/rspack-test-tools/tests/configCases/errors/module-trace/rspack.config.js
  packages/rspack-test-tools/tests/configCases/errors/module-trace/test.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-config-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/resolve-extensions-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/unhandled-scheme-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/json/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/resolve-fail-esm.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/statsAPICases/error-chunk.js
  packages/rspack/src/Stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPresetPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  tests/plugin-test/css-extract/cases/build-in-css-support/warnings.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/statsCases/module-trace-disabled-in-error/test.filter.js
  tests/webpack-test/statsCases/module-trace-enabled-in-error/test.filter.js
Labels: team, release: feature

#7131 feat: add trace in hook macro
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_ids/Cargo.toml
  crates/rspack_macros/src/plugin.rs
  crates/rspack_macros_test/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_dynamic_entry/Cargo.toml
  crates/rspack_plugin_ensure_chunk_conditions/Cargo.toml
  crates/rspack_plugin_entry/Cargo.toml
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_hmr/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_ignore/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_lazy_compilation/Cargo.toml
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  crates/rspack_plugin_limit_chunk_count/Cargo.toml
  crates/rspack_plugin_merge_duplicate_chunks/Cargo.toml
  crates/rspack_plugin_mf/Cargo.toml
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_remove_empty_chunks/Cargo.toml
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime_chunk/Cargo.toml
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_size_limits/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_plugin_worker/Cargo.toml
Labels: team, release: feature

#7134 fix: remove all unused local variables
  packages/rspack-cli/tests/build/issue-4467/index.test.ts
  packages/rspack-dev-server/src/server.ts
  packages/rspack-lite-tapable/src/index.ts
  packages/rspack-test-tools/src/compare/format-code.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/runner/watch.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack/etc/api.md
  packages/rspack/src/Module.ts
  packages/rspack/src/builtin-plugin/WorkerPlugin.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/container/ContainerPlugin.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  tsconfig.base.json
Labels: team, release: bug fix

#7137 refactor: remove clone in js walk
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
Labels: team

#7111 feat: support `test`, `include` and `exclude` options for `SwcCssMinimizerRspackPlugin`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_swc_css_minimizer.rs
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/a.css
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/a.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/b.css
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/b.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts
  website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
Labels: release: feature

#7142 chore(test-tools): fix type issue for benchmark CI
  packages/rspack-test-tools/src/processor/hot-step.ts
Labels: team

#7143 fix: unset cjs exports type on access exports directly
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/b.js
  packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/cjs.js
  packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/index.js
Labels: team, release: bug fix

#7141 refactor: js estree statement
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/2.snap.txt
Labels: team

#7126 perf: stats rust side generate speed
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/stats.rs
Labels: team, release: performance

#7159 docs: update benchmark data and improve UI
  website/docs/en/misc/benchmark.mdx
  website/docs/zh/misc/benchmark.mdx
  website/theme/components/Benchmark/ProgressBar.module.scss
  website/theme/components/Benchmark/ProgressBar.tsx
  website/theme/components/Benchmark/index.module.scss
  website/theme/components/Benchmark/index.tsx
  website/theme/components/HomeHero/index.module.scss
  website/theme/i18n/enUS.ts
  website/theme/i18n/zhCN.ts
Labels: team, release: document

#7155 fix: avoid type error when skipLibCheck is not enabled
  packages/rspack-dev-server/package.json
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  pnpm-lock.yaml
  tests/webpack-test/package.json
Labels: release: bug fix

#7154 fix: align resolverFactory resolveOptions parameter with resolve options
  packages/rspack/etc/api.md
  packages/rspack/src/ResolverFactory.ts
Labels: team, release: bug fix

#7158 test: calcuate test compatibility by test case
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/Examples.test.js
  tests/webpack-test/HotTestCases.template.js
  tests/webpack-test/MemoryLimitTestCases.test.js
  tests/webpack-test/StatsTestCases.basictest.js
  tests/webpack-test/TestCases.template.js
  tests/webpack-test/WatchTestCases.template.js
  tests/webpack-test/cases/chunks/weak-dependencies/index.js
  tests/webpack-test/cases/cjs-tree-shaking/bailouts/index.js
  tests/webpack-test/cases/esm/import-meta/index.js
  tests/webpack-test/cases/esm/import-meta/test.filter.js
  tests/webpack-test/cases/mjs/type-module/test.filter.js
  tests/webpack-test/cases/parsing/chunks/test.filter.js
  tests/webpack-test/cases/parsing/complex-require/cjs.js
  tests/webpack-test/cases/parsing/complex-require/index.js
  tests/webpack-test/cases/parsing/complex-require/test.filter.js
  tests/webpack-test/lib/util/filterUtil.js
  tests/webpack-test/scripts/test-metric-util.js
Labels: team

#7162 docs: update the quick start guide
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#7164 fix: invalid "javascript/auto" rule.type in getRawGeneratorOptions
  packages/rspack-test-tools/tests/configCases/module/generator-js/index.js
  packages/rspack-test-tools/tests/configCases/module/generator-js/lib.js
  packages/rspack-test-tools/tests/configCases/module/generator-js/rspack.config.js
  packages/rspack/src/config/adapter.ts
Labels: team, release: bug fix

#7152 fix: should merge parser.javascript
  crates/rspack_core/src/lib.rs
  packages/rspack-test-tools/src/processor/builtin.ts
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/swc-loader/ts/rspack.config.js
  packages/rspack-test-tools/tests/configCases/babel-loader/plugin-import/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader/file-loader/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/override-strict/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/rspack.config.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  tests/plugin-test/css-extract/cases/together-with-experiment-css/webpack.config.js
Labels: team, release: bug fix

#7167 docs: polish up output config
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
  website/project-words.txt
Labels: release: document

#7173 fix(cli): update peerDep of rspack-cli
  packages/rspack-cli/package.json
  packages/rspack/scripts/check-documentation-coverage.mjs
Labels: team, release: bug fix

#7165 feat(stats): align stats factory
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPresetPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#7175 fix(release): alpha peerDependencies in @rspack/cli
  packages/rspack-cli/package.json
Labels: release: bug fix

#7168 docs: complete the target configuration
  website/docs/en/config/target.mdx
  website/docs/zh/config/target.mdx
Labels: team, release: document

#7177 docs: reuse HomeLayout from Rspress
  website/docs/zh/index.md
  website/pnpm-lock.yaml
  website/rspress.config.ts
  website/theme/components/Benchmark/index.tsx
  website/theme/components/HomeFeatures/index.module.scss
  website/theme/components/HomeFeatures/index.tsx
  website/theme/components/HomeFooter/index.tsx
  website/theme/components/HomeHero/index.module.scss
  website/theme/components/HomeHero/index.tsx
  website/theme/i18n/enUS.ts
  website/theme/index.css
  website/theme/pages/index.tsx
  website/theme/tailwind.css
Labels: team, release: document

#7138 perf: reduce allocation for filename render
  crates/rspack_core/src/options/filename.rs
  crates/rspack_util/src/ext.rs
Labels: team, release: performance

#7180 docs(format): run prettier --write
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/zh/api/loader-api/rspack-specific-properties.mdx
  website/docs/zh/blog/announcing-1-0-alpha.mdx
  website/docs/zh/contribute/architecture/rspack-loader.md
  website/docs/zh/contribute/development/profiling.md
  website/docs/zh/contribute/development/testing-rspack.mdx
Labels: release: document

#7183 docs: add new features section to home page
  README.md
  README.zh-CN.md
  website/docs/en/blog/index.mdx
  website/docs/zh/blog/index.mdx
  website/theme/components/Benchmark/ProgressBar.tsx
  website/theme/components/Benchmark/index.module.scss
  website/theme/components/Benchmark/index.tsx
  website/theme/components/Featured/index.module.scss
  website/theme/components/Featured/index.tsx
  website/theme/i18n/enUS.ts
  website/theme/i18n/index.ts
  website/theme/i18n/zhCN.ts
  website/theme/pages/index.tsx
Labels: team, release: document

#7184 fix: eval condition expr range
  crates/rspack_plugin_javascript/src/utils/eval/eval_cond_expr.rs
  packages/rspack-test-tools/tests/configCases/parsing/eval-condition-inside-require/a.js
  packages/rspack-test-tools/tests/configCases/parsing/eval-condition-inside-require/index.js
  packages/rspack-test-tools/tests/configCases/parsing/eval-condition-inside-require/rspack.config.js
  website/theme/components/Benchmark/index.tsx
Labels: team, release: bug fix

#7185 docs: improve home page SSG and benchmark data
  website/pnpm-lock.yaml
  website/theme/components/Benchmark/ProgressBar.module.scss
  website/theme/components/Benchmark/ProgressBar.tsx
  website/theme/components/Benchmark/index.tsx
  website/theme/components/Featured/index.module.scss
  website/theme/components/Featured/index.tsx
  website/theme/components/HomeFooter/index.module.scss
  website/theme/components/HomeFooter/index.tsx
  website/theme/index.css
Labels: team, release: document

#7187 feat: align part of compile time binary evaluation with webpack
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-if-binary/index.js
  tests/webpack-test/cases/esm/import-meta/index.js
  tests/webpack-test/cases/parsing/evaluate-nullish/test.filter.js
  tests/webpack-test/cases/parsing/extract-require/index.js
  tests/webpack-test/cases/parsing/extract-require/test.filter.js
  tests/webpack-test/cases/parsing/issue-4596/test.filter.js
  tests/webpack-test/cases/parsing/typeof/index.js
  tests/webpack-test/cases/parsing/typeof/test.filter.js
  tests/webpack-test/cases/parsing/typeof/warnings.js
Labels: team, release: feature

#7179 release: 1.0.0-alpha.4
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#6668 fix: pattern with wildcard and globstar can't match correctly when using `glob_match`
  Cargo.lock
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: release: bug fix

#7190 feat: align StatsAsset with webpack
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hashCases/real-content-hash-md4/test.config.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-xxhash64/test.config.js
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#7195 docs: update stats data
  website/docs/en/api/stats.mdx
  website/docs/zh/api/stats.mdx
Labels: team, release: document

#7163 perf: optimize JS communication with lazy getters
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_macros/src/lib.rs
  crates/rspack_macros/src/napi.rs
  packages/rspack/etc/api.md
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
Labels: team, release: performance

#7192 perf: reduce allocation for `TraceableError`
  crates/rspack_error/src/error.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/html_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/non_support_warning/stats.err
Labels: team, release: performance

#7196 test(css-extract): enable function filename test
  tests/plugin-test/css-extract/cases/chunkFilename-as-function/expected/expected.async.css
  tests/plugin-test/css-extract/cases/chunkFilename-as-function/test.filter.js
  tests/plugin-test/css-extract/cases/chunkFilename-as-function/webpack.config.js
Labels: team

#7191 feat: add support for function types to `output.assetModuleFilename`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  tests/webpack-test/configCases/asset-modules/assetModuleFilename/test.filter.js
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: release: feature

#7197 fix: panic in hmr cause by auxiliary_assets
  crates/rspack_core/src/stats.rs
Labels: team, release: bug fix

#7201 release: 1.0.0-alpha.5
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  tests/plugin-test/copy-plugin/build/main.js
Labels: team

#7189 feat: support output.charset and output.chunkLoadTimeout
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_css/src/runtime/css_loading.js
  crates/rspack_plugin_css/src/runtime/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/output/chunk-load-timeout/a.js
  packages/rspack-test-tools/tests/configCases/output/chunk-load-timeout/b.js
  packages/rspack-test-tools/tests/configCases/output/chunk-load-timeout/index.js
  packages/rspack-test-tools/tests/configCases/output/chunk-load-timeout/rspack.config.js
  packages/rspack-test-tools/tests/configCases/output/chunk-load-timeout/test.config.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
  packages/rspack-test-tools/tests/defaultsCases/target_/node.js
  packages/rspack-test-tools/tests/defaultsCases/target_/nwjs.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: release: feature

#7124 perf: reduce allocation for `Stats`
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/package.json
  crates/node_binding/scripts/build.js
  crates/rspack_binding_options/src/options/raw_cache.rs
  crates/rspack_binding_options/src/options/raw_mode.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/options/mode.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
Labels: team, release: performance

#7205 feat: support __webpack_exports_info__
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/import_dependency_trait.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/exports_info_api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack-test-tools/tests/normalCases/parsing/webpack-exports/dir12/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/webpack-exports/dir13/a.js
  packages/rspack-test-tools/tests/normalCases/parsing/webpack-exports/dir13/b.js
  packages/rspack-test-tools/tests/normalCases/parsing/webpack-exports/index.js
  tests/webpack-test/cases/inner-graph/extend-class2/test.filter.js
  tests/webpack-test/cases/parsing/harmony-deep-exports/test.filter.js
  tests/webpack-test/cases/parsing/harmony-export-import-specifier/test.filter.js
  tests/webpack-test/cases/parsing/harmony-reexport/test.filter.js
  tests/webpack-test/configCases/optimization/runtime-specific-used-exports/test.filter.js
  website/docs/en/api/modules/module-variables.mdx
  website/docs/zh/api/modules/module-variables.mdx
Labels: team, release: feature

#7215 fix: panic in ImportMetaContextDependency when resolve failed
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/import-meta-context-error/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/import-meta-context-error/stats.err
Labels: team, release: bug fix

#7217 test: enable webpack test cases of webpackHot.data
  tests/webpack-test/hotCases/chunks/update-chunk-loading-runtime/node_modules/vendor.js
  tests/webpack-test/hotCases/chunks/update-chunk-loading-runtime/test.filter.js
  tests/webpack-test/hotCases/recover/recover-after-self-error/test.filter.js
Labels: team

#7210 feat: external callbacks receive contextInfo.issuer
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_external.rs
  crates/rspack_core/src/options/externals.rs
  crates/rspack_plugin_externals/src/plugin.rs
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
Labels: release: feature

#7220 fix!: correct names of hash fields in asset.info
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_binding_values/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/configCases/hooks/update-asset/rspack.config.js
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/test.js
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack/src/util/AssetInfo.ts
Labels: release: breaking change, release: bug fix

#7221 docs: add tool stack to homepage
  website/package.json
  website/pnpm-lock.yaml
  website/theme/components/Benchmark/ProgressBar.module.scss
  website/theme/components/Benchmark/ProgressBar.tsx
  website/theme/components/Benchmark/index.module.scss
  website/theme/components/Benchmark/index.tsx
  website/theme/components/Featured/index.tsx
  website/theme/components/ToolStack/ToolStack.module.scss
  website/theme/components/ToolStack/ToolStack.tsx
  website/theme/i18n/enUS.ts
  website/theme/i18n/zhCN.ts
  website/theme/index.css
  website/theme/index.tsx
  website/theme/pages/index.tsx
Labels: team, release: document

#7222 fix: collect auxiliary assets from module
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_options/src/plugins/js_loader/scheduler.rs
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_loader_runner/src/context.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/AssetInfo.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/configCases/loader-import-module/css/test.filter.js
  tests/webpack-test/statsCases/module-assets/test.config.js
Labels: team, release: bug fix

#7219 perf: reduce allocation for parsing
  crates/rspack_identifier/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
Labels: team, release: performance

#7229 feat: support destructuring of import.meta
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  tests/webpack-test/cases/esm/import-meta/index.js
  tests/webpack-test/cases/esm/import-meta/test.filter.js
Labels: team, release: feature

#7230 feat: support tree shaking with awaiting dynamic import
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/tree-shaking/dynamic-import-unused/index.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/dynamic-import-unused/lib.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/dynamic-import-unused/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/webpack-exports-warning/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/webpack-exports-warning/lib.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/webpack-exports-warning/stats.err
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#7232 test: enable preact refresh snapshot test
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/2.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/1.snap.txt
  packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/2.snap.txt
Labels: team

#7233 perf: use Set as Queue to solve the duplication
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/utils/queue.rs
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/statsCases/module-deduplication/test.config.js
Labels: team, release: performance

#7237 test: enable inner graph basic webpack test case
  tests/webpack-test/configCases/inner-graph/basic/test.filter.js
Labels: team

#7236 docs: add __webpack_get_script_filename__
  website/docs/en/api/modules/module-variables.mdx
  website/docs/zh/api/modules/module-variables.mdx
Labels: team, release: document

#7216 feat: align `publicPath` options with webpack
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_dynamic_entry.rs
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/filename.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack-dev-server/src/middleware.ts
  packages/rspack-test-tools/tests/configCases/entry/public-path/a.js
  packages/rspack-test-tools/tests/configCases/entry/public-path/test.config.js
  packages/rspack-test-tools/tests/configCases/entry/public-path/webpack.config.js
  packages/rspack-test-tools/tests/configCases/output/public-path/index.js
  packages/rspack-test-tools/tests/configCases/output/public-path/webpack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/zod.ts
  tests/webpack-test/configCases/asset-modules/_images/file.png
  tests/webpack-test/configCases/asset-modules/generator-asset-publicPath-hash/index.js
  tests/webpack-test/configCases/asset-modules/generator-asset-publicPath-hash/test.filter.js
  tests/webpack-test/configCases/asset-modules/generator-asset-publicPath/test.filter.js
  tests/webpack-test/configCases/asset-modules/publicPath/test.filter.js
  website/docs/en/config/entry.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/output.mdx
  website/docs/zh/config/entry.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/output.mdx
Labels: release: feature

#7240 fix: fix panic about runtime order
  crates/rspack_core/src/runtime.rs
Labels: release: bug fix

#7249 perf: reduce allocation for `ModuleRule` matching
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/utils/module_rules.rs
  crates/rspack_loader_runner/src/scheme.rs
  crates/rspack_macros/src/lib.rs
  crates/rspack_napi_macros/Cargo.toml
  crates/rspack_napi_macros/src/getters.rs
  crates/rspack_napi_macros/src/lib.rs
  crates/rspack_napi_macros/src/tagged_union.rs
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
Labels: team, release: performance

#7248 refactor: remove duplicated extract member expression info
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/exports_info_api_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: team

#7214 feat: support lightningcss-loader
  Cargo.lock
  Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
  crates/rspack_loader_lightningcss/Cargo.toml
  crates/rspack_loader_lightningcss/LICENSE
  crates/rspack_loader_lightningcss/src/config.rs
  crates/rspack_loader_lightningcss/src/lib.rs
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/index.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/index.module.css
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-loader/lightningcss/index.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/exports.ts
  website/docs/en/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
Labels: team, release: feature

#7250 test: add test case for runtime condition
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/a.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/ax.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/b.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/bx.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/concatenated-shared.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/dep.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/dep2.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/shared.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/super.js
  packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/test.config.js
Labels: team

#7271 fix: real content full hash replacement
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/asset.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-html/filename/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/filename/rspack.config.js
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-wasm/v128/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/hashCases/real-content-hash-fullhash/index.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-fullhash/rspack.config.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-fullhash/test.config.js
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack/src/util/AssetInfo.ts
Labels: team, release: bug fix

#7275 fix(fs): remove generic in `FileSystem` trait
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_fs/src/async.rs
  crates/rspack_fs/src/native.rs
  crates/rspack_fs/src/sync.rs
  crates/rspack_fs_node/src/async.rs
  crates/rspack_fs_node/src/sync.rs
Labels: team, release: bug fix

#7272 fix(panic): stable runtime key sequence
  crates/rspack_core/src/runtime.rs
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/statsCases/module-deduplication/test.config.js
Labels: team, release: bug fix

#7274 docs: complete processAssets document
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
Labels: team, release: document

#7277 fix: corrects result for `truthy || any` and `falsy && any`
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-logical/index.js
Labels: release: bug fix

#7130 feat(deps)!: update`webpack-dev-server` to v5 and no longer lock the versions
  packages/playground/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
  packages/rspack/package.json
  pnpm-lock.yaml
  tests/webpack-test/package.json
Labels: release: feature

#7280 refactor: reuse binary evaluation expression and support null coalescing
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  packages/rspack-test-tools/tests/normalCases/parsing/evaluate-nullish-coalescing/index.js
Labels: team

#7283 fix: Update index.mdx
  website/docs/zh/contribute/index.mdx
Labels: release: bug fix

#7286 perf: reduce large pre-allocations for `JavascriptParser::new`
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
Labels: team, release: performance

#7297 feat: support EntryPlugin filename function
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_entry.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/a.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/index.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/test.config.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/a.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/index.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/config/zod.ts
  website/components/PluginSupportStatusTable.tsx
Labels: team, release: feature

#7294 ci: solve slow build & test in windows
  .github/actions/pnpm-cache/action.yml
  .github/workflows/reusable-build.yml
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-lite-tapable/package.json
  packages/rspack-plugin-preact-refresh/package.json
  packages/rspack-plugin-react-refresh/package.json
Labels: team

#7257 perf: a bunch of small improvement for ConcatenatedModule
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: release: performance

#7296 test: add diff test case of concatenated runtime condition
  crates/rspack_core/src/concatenated_module.rs
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/diff.ts
  packages/rspack-test-tools/src/compare/compare.ts
  packages/rspack-test-tools/src/helper/parse-modules.ts
  packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/interop-test/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/interop-test/webpack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/a.mjs
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/b.mjs
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/package.json
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/shared.mjs
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/utils.cjs
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/value.mjs
  packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/webpack.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team

#7302 chore(ci): fix ci wrong
  .github/workflows/reusable-build.yml
Labels: team

#7300 docs: fix build typo in the benchmark
  website/theme/components/Benchmark/index.tsx
  website/theme/index.css
Labels: team, release: document

#7301 perf: reduce allocation for adding dependencies
  crates/rspack_core/src/module_factory.rs
Labels: team, release: performance
