Repository web-infra-dev/rspack, pull requests merged in 2024-11, with the labels that each got.

#8306 fix(type): Patch rollup-plugin-dts bug that broke prebundled zod
  package.json
  patches/rollup-plugin-dts.patch
  pnpm-lock.yaml
Labels: release: bug fix

#8273 fix: hotUpdate chunk should have correct runtime
  crates/rspack_plugin_hmr/src/lib.rs
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/index.js
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/lib/a.js
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/lib/b.js
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/lib/package.json
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/module.js
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/rspack.config.js
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/test.filter.js
  packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/worker.js
Labels: team, release: bug fix

#8262 feat: unify module in loader context
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_loader_runner/src/context.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
Labels: team, release: feature

#8308 docs: add swc cacheRoot guide
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: document

#8307 fix: error for set user request
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/normal_module.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
Labels: team, release: bug fix

#8297 fix: falsy rule should be filtered
  packages/rspack-test-tools/tests/configCases/module/falsy/index.js
  packages/rspack-test-tools/tests/configCases/module/falsy/lib.js
  packages/rspack-test-tools/tests/configCases/module/falsy/loader.js
  packages/rspack-test-tools/tests/configCases/module/falsy/loader1.js
  packages/rspack-test-tools/tests/configCases/module/falsy/loader2.js
  packages/rspack-test-tools/tests/configCases/module/falsy/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: bug fix

#8226 refactor: use async thread pool
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/task_loop.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
Labels: team

#8311 fix: use incremental in production build
  packages/playground/cases/hooks/asset-emitted/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/src/builtin-plugin/FlagDependencyUsagePlugin.ts
  packages/rspack/src/builtin-plugin/MangleExportsPlugin.ts
  packages/rspack/src/builtin-plugin/ModuleConcatenationPlugin.ts
  packages/rspack/src/config/defaults.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: bug fix

#8319 fix: correct usage of `pnpm --filter` in package scripts
  package.json
  x.mjs
Labels: release: bug fix

#8317 chore(renovate): manually update peer dependencies
  .github/renovate.json5
Labels: team

#8322 feat(core): bump swc to 4.0.2
  Cargo.lock
  Cargo.toml
Labels: team, release: feature

#8324 feat: use lightningcss v1.0.0-alpha.60 stead of lightningcss_rs
  Cargo.lock
  Cargo.toml
  crates/rspack_cacheable/Cargo.toml
  crates/rspack_cacheable_test/Cargo.toml
  crates/rspack_loader_lightningcss/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
Labels: release: feature

#8330 chore: prevent clone when create ModuleIdentifier
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
Labels: team

#8303 fix: runtime chunk hash should respect their reference order
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/codegen_result.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/cgm_runtime_requirement_results.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/code_generation_results.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/old_cache/occasion/code_generate.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_full_hash.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module_from_js.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hashCases/depend-async-entrypoint/index.js
  packages/rspack-test-tools/tests/hashCases/depend-async-entrypoint/rspack.config.js
  packages/rspack-test-tools/tests/hashCases/depend-async-entrypoint/test.config.js
  packages/rspack-test-tools/tests/hashCases/depend-async-entrypoint/worker.js
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/src/RuntimeModule.ts
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$c351e5d25b5dca2a32cf$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$c351e5d25b5dca2a32cf$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#8320 perf: remove unnecessary regex
  Cargo.lock
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/identifier.rs
Labels: release: performance

#8331 perf(cli): enable Node.js compile cache
  packages/rspack-cli/bin/rspack.js
Labels: team, release: performance

#8325 fix(ci): pkg.pr.preview not work
  .github/workflows/ci.yml
  .github/workflows/preview-commit.yml
  package.json
Labels: team, release: bug fix

#8336 docs: add Docusaurus to ecosystem
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#8338 docs: add Nuxt to ecosystem
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/project-words.txt
Labels: team, release: document

#8315 feat: throw error for outdated compilation
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  packages/rspack-test-tools/tests/compilerCases/access-outdated-compilation.js
  packages/rspack-test-tools/tests/hotCases/stats/chunks/rspack.config.js
  packages/rspack/src/Compiler.ts
  tests/plugin-test/css-extract/TestMemoryFS.test.js
Labels: team, release: feature

#8328 fix: file dependencies are lost when css module fails
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_options/src/plugins/js_loader/scheduler.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/diagnostics.rs
  crates/rspack_core/src/normal_module.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/0/dep.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/0/entry.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/0/index.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/1/dep.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/1/errors.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/2/dep.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/loader.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed-css/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/0/dep.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/0/entry.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/0/index.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/1/dep.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/1/errors.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/2/dep.txt
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/loader.js
  packages/rspack-test-tools/tests/watchCases/build-failed/watch-loader-failed/rspack.config.js
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#8339 docs: improve default value, types and examples for `optimization`
  website/docs/en/config/optimization.mdx
  website/docs/en/misc/glossary.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/misc/glossary.mdx
Labels: team, release: document

#8050 feat: support compilation.modules[i].dependencies
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  packages/rspack-test-tools/tests/configCases/compilation/modules/b.js
  packages/rspack-test-tools/tests/configCases/compilation/modules/index.js
  packages/rspack-test-tools/tests/configCases/compilation/modules/rspack.config.js
  packages/rspack/src/Module.ts
Labels: to be discussed, release: feature

#8341 fix: code auto merging error
  crates/rspack_binding_values/src/module.rs
Labels: team, release: bug fix

#8343 docs: fix missing internal plugins
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/internal-plugins.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/electron-target-plugin.mdx
  website/docs/zh/plugins/webpack/entry-plugin.mdx
  website/docs/zh/plugins/webpack/internal-plugins.mdx
Labels: team, release: document

#8342 refactor: css-module should have strict buildInfo
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_extract_css/src/parser_plugin.rs
Labels: team

#8327 refactor: rm UNASSOCIATED_MODULE_INSTANCE_REFS
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_lazy_compilation.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_options/src/plugins/js_loader/context.rs
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_napi/src/js_values/one_shot_value_ref.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_module_options_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_lazy_compilation/src/factory.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Module.ts
Labels: team

#8355 fix(cli): missing `exports.types` field
  packages/rspack-cli/package.json
Labels: team, release: bug fix

#8356 fix(tests): layer-stats snapshot problem
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/layer-stats.js
Labels: release: bug fix

#8354 feat(core): bump swc to 5.0.0
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
Labels: team, release: feature

#8357 fix: correct split-chunks tests
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/helper/util/checkStats.js
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/type.ts
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/available-modules-change/0/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/available-modules-change/1/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/available-modules-change/1/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/available-modules-change/1/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/available-modules-change/1/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/available-modules-change/test.config.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/basic/1/dyn-2.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/basic/1/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/basic/1/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/0/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/1/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/1/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/1/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/1/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/2/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/2/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/2/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-add-then-change-ava-module/test.config.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/0/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/1/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/1/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/1/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/1/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/2/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/2/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/2/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/2/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/3/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/3/dyn-2.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/3/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/3/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/3/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-modify/test.config.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-remove/0/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-remove/1/dyn-1.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-remove/1/index.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-remove/1/m.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-remove/1/shared.js
  packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/chunk-remove/test.config.js
Labels: team, release: bug fix

#8225 fix(experiments css): should preserve keywords decl and compose ident for self reference
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_plugin_css/src/dependency/compose.rs
  crates/rspack_plugin_css/src/dependency/mod.rs
  crates/rspack_plugin_css/src/dependency/self_reference.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack-test-tools/tests/configCases/css/css-modules-animation/index.js
  packages/rspack-test-tools/tests/configCases/css/css-modules-animation/index.module.css
  packages/rspack-test-tools/tests/configCases/css/css-modules-animation/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css/css-modules-animation/test.config.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/index.js
Labels: release: bug fix

#8358 fix: import order change should re-seal
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/a.css
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/b.css
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/change.js
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/index.js
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/rspack.config.js
  packages/rspack-test-tools/tests/hotCases/module-graph/import-order-change/test.config.js
Labels: team, release: bug fix

#8362 fix(core): bump swc to 5.0.1
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
Labels: team, release: bug fix

#8361 feat: improve description, types and JSDoc for entry options
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/EntryPlugin.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  website/docs/en/config/entry.mdx
  website/docs/en/plugins/webpack/entry-plugin.mdx
  website/docs/zh/config/entry.mdx
  website/docs/zh/plugins/webpack/entry-plugin.mdx
Labels: team, release: feature

#8363 fix(cli): Run config function before looking for `--config-name`
  packages/rspack-cli/src/cli.ts
Labels: release: bug fix

#8368 fix: items_to_regexp for chinese
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/utils/compile_boolean_matcher.rs
Labels: team, release: bug fix

#8344 fix: allow passing Infinity to parser.asset.dataUrlCondition.maxSize
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_util/src/merge.rs
  tests/webpack-test/configCases/asset-modules/data-url/index.js
  tests/webpack-test/configCases/asset-modules/data-url/test.filter.js
Labels: release: bug fix

#8373 docs: add bluesky file
  website/docs/public/.well-known/atproto-did
Labels: team, release: document

#8371 fix(side effects): should optimize for same target export
  crates/rspack_core/src/exports_info.rs
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/const.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/index.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/const.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/error.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/index.js
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/package.json
  packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/rspack.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#8366 refactor: rspack_fs use `Utf8Path` and `FileMetadata`
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/async.rs
  crates/rspack_fs/src/file_metadata.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs/src/sync.rs
  crates/rspack_fs_node/src/async.rs
  crates/rspack_fs_node/src/node.rs
  crates/rspack_fs_node/src/sync.rs
  crates/rspack_loader_runner/src/runner.rs
Labels: team

#8372 feat: add memory fs
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/file_metadata.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/memory_fs.rs
Labels: team, release: feature

#8359 chore: bump to napi@3
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/package.json
  crates/node_binding/scripts/build.js
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/options/raw_cache.rs
  crates/rspack_binding_options/src/options/raw_mode.rs
  crates/rspack_binding_options/src/plugins/context_replacement.rs
  crates/rspack_binding_values/src/compilation/entries.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/filename.rs
  crates/rspack_binding_values/src/utils.rs
  crates/rspack_fs_node/src/lib.rs
  crates/rspack_fs_node/src/node.rs
  crates/rspack_napi/src/callback.rs
  crates/rspack_napi/src/js_values/js_value_ref.rs
  crates/rspack_napi/src/js_values/one_shot_value_ref.rs
  crates/rspack_napi/src/threadsafe_function.rs
  crates/rspack_regex/src/napi.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/loader-runner/index.ts
  pnpm-lock.yaml
Labels: team

#8376 fix: tapable run in wrong closure
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/mod.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack-test-tools/tests/compilerCases/hooks-closure.js
Labels: team, release: bug fix

#8377 refactor(napi): prevent depend on ClassInstance
  crates/rspack_binding_values/src/compilation/mod.rs
Labels: team

#8378 refactor(napi): rm unreachable FromNapiValue
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/stats.rs
Labels: team

#8382 build: use symlinked executables instead of command shims
  .npmrc
Labels: team

#8392 fix: panic in sort of chunk combination bucket
  crates/rspack_plugin_limit_chunk_count/src/chunk_combination.rs
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#8398 test: add missing dev dependencies back
  pnpm-lock.yaml
  tests/plugin-test/package.json
  tests/webpack-test/package.json
Labels: team

#8381 fix: compile time evaluation of `__webpack_layer__`
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-disable-layer/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-disable-layer/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-enable-layer/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-enable-layer/rspack.config.js
Labels: release: bug fix

#8296 feat: support rspack.DllPlugin & rspack.DllReferencePlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_dll.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_dll/Cargo.toml
  crates/rspack_plugin_dll/LICENSE
  crates/rspack_plugin_dll/src/dll_entry/dll_entry_dependency.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_entry_plugin.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module_factory.rs
  crates/rspack_plugin_dll/src/dll_entry/mod.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_plugin.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_source_dependency.rs
  crates/rspack_plugin_dll/src/dll_reference/dll_reference_agency_plugin.rs
  crates/rspack_plugin_dll/src/dll_reference/mod.rs
  crates/rspack_plugin_dll/src/flag_all_modules_as_used_plugin.rs
  crates/rspack_plugin_dll/src/lib.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/DllEntryPlugin.ts
  packages/rspack/src/builtin-plugin/DllReferenceAgencyPlugin.ts
  packages/rspack/src/builtin-plugin/FlagAllModulesAsUsedPlugin.ts
  packages/rspack/src/builtin-plugin/LibManifestPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/lib/DllPlugin.ts
  packages/rspack/src/lib/DllReferencePlugin.ts
  tests/webpack-test/configCases/dll-plugin-entry/0-create-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin-entry/1-use-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin-entry/2-error-non-entry/test.filter.js
  tests/webpack-test/configCases/dll-plugin-format/0-create-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin-side-effects/0-create-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin-side-effects/1-use-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin/0-create-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/constants.js
  tests/webpack-test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/index.js
  tests/webpack-test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/package.json
  tests/webpack-test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/someFunction.js
  tests/webpack-test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/working-constants.js
  tests/webpack-test/configCases/dll-plugin/0-issue-10475/test.filter.js
  tests/webpack-test/configCases/dll-plugin/1-issue-10475/test.filter.js
  tests/webpack-test/configCases/dll-plugin/1-use-dll/test.filter.js
  tests/webpack-test/configCases/dll-plugin/2-use-dll-without-scope/test.filter.js
  tests/webpack-test/configCases/dll-plugin/3-use-dll-with-hashid/test.filter.js
  tests/webpack-test/configCases/dll-plugin/3-use-dll-with-hashid/webpack.config.js
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/dll-plugin.mdx
  website/docs/en/plugins/webpack/dll-reference-plugin.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/dll-plugin.mdx
  website/docs/zh/plugins/webpack/dll-reference-plugin.mdx
Labels: release: feature

#8397 fix: panic when imported json file is empty
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/empty.json
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/stats.err
Labels: team, release: bug fix

#8400 fix: css runtime should have hmr handler when lazy-compilation
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_extract_css/src/runtime.rs
  packages/playground/cases/lazy-compilation/css-update/index.test.ts
  packages/playground/cases/lazy-compilation/css-update/rspack.config.js
  packages/playground/cases/lazy-compilation/css-update/src/blue.css
  packages/playground/cases/lazy-compilation/css-update/src/change.js
  packages/playground/cases/lazy-compilation/css-update/src/index.js
  packages/playground/cases/lazy-compilation/css-update/src/red.css
  tests/plugin-test/css-extract/cases/runtime/expected/runtime~main.js
Labels: team, release: bug fix

#8268 fix: fix `Compiler` not getting freed after use
  packages/rspack/src/Compiler.ts
  tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/index.js
Labels: team, release: bug fix

#8414 feat(externals): support 'commonjs-import' type
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/configCases/externals/commonjs-import/case.js
  packages/rspack-test-tools/tests/configCases/externals/commonjs-import/index.js
  packages/rspack-test-tools/tests/configCases/externals/commonjs-import/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/commonjs-import/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/externals.mdx
  website/docs/zh/config/externals.mdx
Labels: team, release: feature

#8394 feat: unify js dependency
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/entries.rs
  crates/rspack_binding_values/src/context_module_factory.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/dependency_block.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/context_module_factory.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Dependency.ts
Labels: release: feature

#8425 fix: output should be consistent when using splitChunks
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack-test-tools/tests/compilerCases/consistent.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/400k.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-1.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-2.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-3.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-4.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-5.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-6.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-7.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-8.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k.js
  packages/rspack-test-tools/tests/fixtures/split-chunks/src/index.js
Labels: team, release: bug fix

#8385 refactor: rename async_run to background_run & sync_run to main_run
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team

#8434 fix(core): remove hang risk caused by coop budget in tokio
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team, release: bug fix

#8437 fix: should not free native compiler while compiler is running
  packages/rspack/src/Compiler.ts
Labels: team, release: bug fix

#8422 feat: support attributes for ESM external module
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_library/src/modern_module/import_dependency.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/main.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/rspack.config.js
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/configCases/externals/import-attributes/test.filter.js
  tests/webpack-test/configCases/externals/import-attributes/webpack.config.js
  tests/webpack-test/helpers/pkg.json
Labels: team, release: feature

#8448 docs: polish module methods documentation
  website/docs/en/api/cli.mdx
  website/docs/en/api/runtime-api/module-methods.mdx
  website/docs/en/api/runtime-api/module-variables.mdx
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/en/guide/tech/react.mdx
  website/docs/zh/api/cli.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/tech/react.mdx
Labels: team, release: document

#8450 fix: align bytes ptr address for `cacheable::from_byte`
  .github/workflows/ci.yml
  crates/rspack_cacheable/src/deserialize.rs
  crates/rspack_cacheable_test/tests/macro/cacheable_dyn.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn_with_generics.rs
  crates/rspack_macros_test/tests/compiletest.rs
Labels: team, release: bug fix

#8415 fix: correct favicon path when output.publicPath is set to `auto`
  crates/rspack_plugin_html/src/asset.rs
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute-publicpath-auto/favicon.ico
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute-publicpath-auto/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-absolute-publicpath-auto/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative-publicpath-auto/favicon.ico
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative-publicpath-auto/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-relative-publicpath-auto/rspack.config.js
Labels: release: bug fix

#8456 fix(lightningcss): align type with lightningcss
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_loader_lightningcss/src/config.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-loader/lightningcss/index.ts
  packages/rspack/src/builtin-plugin/LightningCssMinimizerRspackPlugin.ts
  website/docs/en/guide/features/builtin-lightningcss-loader.mdx
  website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
Labels: release: bug fix

#8443 fix: the attribute values of HTML tags should not be converted to lowercase
  crates/rspack_binding_values/src/html.rs
  packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/test.config.js
Labels: release: bug fix

#8452 feat: align webpack DefinePlugin for destructuring optimization
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8120/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8120/rspack.config.js
Labels: release: feature

#8440 feat(incremental): render chunk manifest
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
Labels: team, release: feature

#8462 docs: invite @inottn to Rspack core team
  website/components/RandomMemberList.tsx
  website/project-words.txt
Labels: team, release: document

#8464 docs: add more JavaScript runtimes
  website/docs/en/api/javascript-api/index.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/api/javascript-api/index.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#8424 feat(persistent cache): add snapshot module
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_binding_options/src/options/raw_experiments/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_cache/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_cache/raw_snapshot.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_cache/raw_storage.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_incremental.rs
  crates/rspack_binding_options/src/options/raw_experiments/raw_rspack_future.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/cache/disable.rs
  crates/rspack_core/src/cache/memory.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/option.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/cache/persistent/storage/memory.rs
  crates/rspack_core/src/cache/persistent/storage/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/options/experiments/cache.rs
  crates/rspack_core/src/options/experiments/mod.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#8467 fix: linux musl resolve failed
  crates/rspack_fs/src/file_metadata.rs
Labels: team, release: bug fix

#8465 build(windows): static linking VS CRT on aarch64 msvc !windows
  .cargo/config.toml
Labels: team

#8476 chore(ci): add rust bench ci
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  tasks/benchmark/Cargo.toml
  tasks/benchmark/benches/basic.rs
  tasks/benchmark/src/lib.rs
Labels: team

#8482 fix: unstable stats test snapshot
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/layer.js
Labels: team, release: bug fix

#8481 perf: move matching logic in source map plugin to rust side
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/EvalSourceMapDevToolPlugin.ts
  packages/rspack/src/builtin-plugin/SourceMapDevToolPlugin.ts
Labels: release: performance

#8470 feat: js module graph api
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/module_graph.rs
  packages/rspack-test-tools/tests/configCases/module_graph/get_issuer/foo.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_issuer/index.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_issuer/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_module/index.js
  packages/rspack-test-tools/tests/configCases/module_graph/get_module/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Dependency.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/ModuleGraph.ts
Labels: release: feature

#8495 fix: css escape when consume string
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#8500 feat(cacheable): add AsOwned
  crates/rspack_cacheable/src/with/as_owned.rs
  crates/rspack_cacheable/src/with/mod.rs
  crates/rspack_cacheable_test/tests/with/as_owned.rs
  crates/rspack_cacheable_test/tests/with/mod.rs
  crates/rspack_macros/src/cacheable.rs
Labels: team, release: feature

#8498 docs: add examples for ESM loader
  website/docs/en/api/loader-api/examples.mdx
  website/docs/en/guide/features/loader.mdx
  website/docs/zh/api/loader-api/examples.mdx
  website/docs/zh/guide/features/loader.mdx
Labels: team, release: document

#8505 docs: chunk level incremental
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8491 test: create issues for webpack-test failure cases
  tests/webpack-test/cases/wasm/v128/test.filter.js
  tests/webpack-test/configCases/additional-pass/simple/test.filter.js
  tests/webpack-test/configCases/asset-modules/_images/file_copy.png
  tests/webpack-test/configCases/asset-modules/custom-condition/test.filter.js
  tests/webpack-test/configCases/asset-modules/file-url/test.filter.js
  tests/webpack-test/configCases/asset-modules/file-url/webpack.config.js
  tests/webpack-test/configCases/asset-modules/global-options/test.filter.js
  tests/webpack-test/configCases/asset-modules/http-url/test.filter.js
  tests/webpack-test/configCases/asset-modules/real-content-hash/test.filter.js
  tests/webpack-test/configCases/concatenate-modules/import-module/test.filter.js
  tests/webpack-test/hotCases/define/issue-6962/test.filter.js
  tests/webpack-test/hotCases/runtime/root-error/test.filter.js
  tests/webpack-test/statsCases/wasm-explorer-examples-sync/test.filter.js
Labels: release: bug fix

#8504 fix(incremental): wrong runtime module when rebuild
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  packages/rspack-test-tools/tests/watchCases/runtime-requirements/entry-runtime-requirements/0/a.js
  packages/rspack-test-tools/tests/watchCases/runtime-requirements/entry-runtime-requirements/0/b.js
  packages/rspack-test-tools/tests/watchCases/runtime-requirements/entry-runtime-requirements/0/index.js
  packages/rspack-test-tools/tests/watchCases/runtime-requirements/entry-runtime-requirements/1/b.js
  packages/rspack-test-tools/tests/watchCases/runtime-requirements/entry-runtime-requirements/2/b.js
Labels: team, release: bug fix

#8520 refactor: rename FileSystem to SyncFileSystem
  Cargo.lock
  crates/node_binding/src/resolver_factory.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs/src/sync.rs
  crates/rspack_loader_runner/src/runner.rs
Labels: team

#8522 refactor: unify to filesystem in rspack_core
  crates/node_binding/src/resolver_factory.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_fs/src/async.rs
  crates/rspack_fs/src/fs.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_schemes/src/http_cache.rs
  crates/rspack_plugin_schemes/src/lockfile.rs
Labels: team

#8523 fix: `WebWorkerTemplatePlugin` should generate import-scripts chunk loading runtime
  package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/index.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/rspack.config.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/test.config.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/worker-async.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/worker.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/WebWorkerTemplatePlugin.ts
  pnpm-lock.yaml
Labels: team, release: bug fix

#8380 fix: handle DataURI without base64 word
  crates/rspack_plugin_schemes/src/data_uri.rs
  tests/webpack-test/configCases/asset-modules/data-url/index.js
Labels: release: bug fix

#8386 fix: variable name conflict with concatenate and runtime code
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  tests/webpack-test/configCases/library/issue-18932/index.js
  tests/webpack-test/configCases/library/issue-18932/webpack.config.js
Labels: release: bug fix

#8521 feat: rspack_cacheable support `as` attr
  crates/rspack_cacheable/src/with/inline.rs
  crates/rspack_cacheable/src/with/mod.rs
  crates/rspack_cacheable_test/tests/macro/cacheable.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/basic.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/hashable.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/mod.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/omit_bounds.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/with_attr.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/with_attr_and_generics.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/basic.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/hashable.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/mod.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/omit_bounds.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/with_attr.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/with_attr_and_generics.rs
  crates/rspack_cacheable_test/tests/with/inline.rs
  crates/rspack_cacheable_test/tests/with/mod.rs
  crates/rspack_macros/src/cacheable.rs
  crates/rspack_macros/src/cacheable/args.rs
  crates/rspack_macros/src/cacheable/impl.rs
  crates/rspack_macros/src/cacheable/impl_as.rs
  crates/rspack_macros/src/cacheable/impl_disable.rs
  crates/rspack_macros/src/cacheable/impl_with.rs
  crates/rspack_macros/src/cacheable/mod.rs
  crates/rspack_macros/src/lib.rs
Labels: team, release: feature

#8388 feat(mf): recursive search for versions of shared dependencies
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/cjs/index.js
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/cjs/package.json
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/node_modules/lib/index.js
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/node_modules/lib/package.json
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/node_modules/transitive_lib/index.js
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/node_modules/transitive_lib/package.json
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/package.json
  tests/webpack-test/configCases/sharing/share-plugin-dual-mode/webpack.config.js
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/app1/index.js
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/app1/node_modules/lib2/index.js
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/app1/node_modules/lib2/package.json
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/app1/package.json
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/node_modules/lib1/index.js
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/node_modules/lib1/package.json
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/node_modules/lib2/index.js
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/node_modules/lib2/package.json
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/package.json
  tests/webpack-test/configCases/sharing/share-plugin-monorepo/webpack.config.js
Labels: release: feature

#8525 refactor: remove unnecessary filesystem trait
  Cargo.lock
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/fs.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs/src/read.rs
  crates/rspack_fs/src/sync.rs
  crates/rspack_fs/src/write.rs
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_fs_node/src/lib.rs
  crates/rspack_fs_node/src/sync.rs
  crates/rspack_fs_node/src/write.rs
  crates/rspack_plugin_schemes/src/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri.rs
  crates/rspack_plugin_schemes/src/lockfile.rs
Labels: team

#8429 fix: reset the progress bar in the correct hook
  crates/rspack_plugin_progress/src/lib.rs
Labels: release: bug fix

#8532 docs: add examples for watchOptions
  website/docs/en/config/watch.mdx
  website/docs/zh/config/watch.mdx
Labels: team, release: document

#8516 feat: support output.environment.nodePrefixForCoreModules
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  tests/webpack-test/configCases/node/prefix-in-runtime/index.js
  tests/webpack-test/configCases/node/prefix-in-runtime/test.filter.js
  tests/webpack-test/configCases/node/prefix-in-runtime/webpack.config.js
Labels: release: feature

#8535 feat(rspack_cacheable): `as` attr support use with dyn trait
  crates/rspack_cacheable/src/context.rs
  crates/rspack_cacheable/src/with/as.rs
  crates/rspack_cacheable/src/with/as_cacheable.rs
  crates/rspack_cacheable/src/with/as_inner.rs
  crates/rspack_cacheable/src/with/as_map.rs
  crates/rspack_cacheable/src/with/as_ref_str.rs
  crates/rspack_cacheable/src/with/as_string.rs
  crates/rspack_cacheable/src/with/as_tuple2.rs
  crates/rspack_cacheable/src/with/as_tuple3.rs
  crates/rspack_cacheable/src/with/as_vec.rs
  crates/rspack_cacheable/src/with/inline.rs
  crates/rspack_cacheable/src/with/unsupported.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/as_attr.rs
  crates/rspack_macros/src/cacheable/impl_as.rs
Labels: team, release: feature

#8545 fix: get encoded asset content correctly
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_schemes/src/data_uri.rs
  tests/webpack-test/configCases/asset-modules/data-url/index.js
  tests/webpack-test/configCases/asset-modules/input-data-url-encoding/test.filter.js
Labels: release: bug fix

#8540 perf: create tsfn error resolver once
  crates/rspack_napi/src/callback.rs
  crates/rspack_napi/src/threadsafe_function.rs
Labels: team, release: performance

#8528 perf: mem cache for chunk render source
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/old_cache/mod.rs
  crates/rspack_core/src/old_cache/occasion/chunk_render.rs
  crates/rspack_core/src/old_cache/occasion/create_chunk_assets.rs
  crates/rspack_core/src/old_cache/occasion/mod.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
Labels: team, release: performance

#8552 fix: missing dependencies type in Module class
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
Labels: team, release: bug fix

#8534 refactor: css loading
  Cargo.lock
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/runtime/css_loading_with_hmr.js
  crates/rspack_plugin_css/src/runtime/css_loading_with_loading.js
  crates/rspack_plugin_css/src/runtime/mod.rs
  crates/rspack_plugin_hmr/Cargo.toml
  crates/rspack_plugin_hmr/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-ident-name/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/at-charset/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/at-import/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/default-options/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/http_import/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/multiple-entry/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/nested/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/output-iife/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/shared-import/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-async-load-css/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-async/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-commonjs-syntax/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-es-module-syntax/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-multiple/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/simple/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/webpack.config.js
  packages/rspack-test-tools/tests/configCases/web/fetch-priority/index.js
  packages/rspack-test-tools/tests/configCases/web/nonce/index.js
  packages/rspack-test-tools/tests/hotCases/css/css-loading-unique-name/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-loading-unique-name/test.config.js
  packages/rspack-test-tools/tests/hotCases/css/css-modules/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css-modules/index.js
  packages/rspack-test-tools/tests/hotCases/css/css-modules/rspack.config.js
  packages/rspack-test-tools/tests/hotCases/css/css/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/css/index.css
  packages/rspack-test-tools/tests/hotCases/css/css/index.js
  packages/rspack-test-tools/tests/hotCases/css/css/test.config.js
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/index.js
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/rspack.config.js
  packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt
  tests/webpack-test/configCases/css/basic/test.config.js
  tests/webpack-test/configCases/css/conflicting-order/test.config.js
  tests/webpack-test/configCases/css/css-modules/test.config.js
  tests/webpack-test/configCases/css/exports-in-node/index.js
  tests/webpack-test/configCases/css/exports-in-node/test.filter.js
  tests/webpack-test/configCases/css/external/test.config.js
  tests/webpack-test/configCases/css/large/index.js
  tests/webpack-test/configCases/css/large/webpack.config.js
  tests/webpack-test/configCases/css/pseudo-export/imported.js
  tests/webpack-test/configCases/css/pseudo-export/index.js
  tests/webpack-test/configCases/css/pseudo-export/reexported.js
  tests/webpack-test/configCases/css/pseudo-export/style.module.css
  tests/webpack-test/configCases/css/pseudo-export/test.filter.js
  tests/webpack-test/configCases/css/pseudo-export/webpack.config.js
Labels: team

#8555 refactor: remove unused cssHeadDataCompression config
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_output.rs
  crates/rspack_core/src/options/output.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
Labels: team

#8562 fix: chunk render cache panic on css extract diagnostics
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/old_cache/occasion/chunk_render.rs
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/a.css
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/ab.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/b.css
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/ba.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/warnings.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/1/ab.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/1/warnings.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/2/ab.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/test.config.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/a.css
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/ab.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/b.css
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/ba.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/warnings.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/1/ab.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/1/warnings.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/2/ab.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/test.config.js
Labels: team, release: bug fix

#8561 fix: should report errors if stats was being accessed after the compiler was closed
  packages/rspack-test-tools/tests/compilerCases/compiler-stats-shutdown.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#8565 docs: polish Rule configuration
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#8570 fix: add missing affectedHooks parameter to ProvidePlugin
  packages/rspack-test-tools/tests/configCases/builtins/provide-issue-8553/index.js
  packages/rspack-test-tools/tests/configCases/builtins/provide-issue-8553/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/provide-issue-8553/str.js
  packages/rspack-test-tools/tests/configCases/builtins/provide-issue-8553/worker.js
  packages/rspack/src/builtin-plugin/ProvidePlugin.ts
Labels: release: bug fix

#8572 fix: rule.issuerLayer
  crates/rspack_core/src/utils/module_rules.rs
  packages/rspack-test-tools/tests/configCases/issuer/empty-entry-layer/index.js
  packages/rspack-test-tools/tests/configCases/issuer/empty-entry-layer/node_modules/foo/dark.js
  packages/rspack-test-tools/tests/configCases/issuer/empty-entry-layer/node_modules/foo/index.js
  packages/rspack-test-tools/tests/configCases/issuer/empty-entry-layer/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/issuer/empty-entry-layer/rspack.config.js
  packages/rspack-test-tools/tests/configCases/layer/empty-entry-layer/index.js
  packages/rspack-test-tools/tests/configCases/layer/empty-entry-layer/node_modules/foo/dark.js
  packages/rspack-test-tools/tests/configCases/layer/empty-entry-layer/node_modules/foo/index.js
  packages/rspack-test-tools/tests/configCases/layer/empty-entry-layer/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/layer/empty-entry-layer/rspack.config.js
Labels: team, release: bug fix

#8559 fix: should have module-post-order-index when incremental build
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/a.css
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/ab.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/b.css
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/ba.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/index.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/1/ab.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/test.config.js
Labels: team, release: bug fix

#8576 feat(cli): set default `process.title`
  packages/rspack-cli/bin/rspack.js
Labels: team, release: feature

#8575 chore: fix crate publish problems
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_cacheable/Cargo.toml
  crates/rspack_cacheable_test/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_fs_node/Cargo.toml
  crates/rspack_hook/Cargo.toml
  crates/rspack_ids/Cargo.toml
  crates/rspack_loader_lightningcss/Cargo.toml
  crates/rspack_loader_preact_refresh/Cargo.toml
  crates/rspack_loader_react_refresh/Cargo.toml
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_testing/Cargo.toml
  crates/rspack_macros_test/Cargo.toml
  crates/rspack_napi/Cargo.toml
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_banner/Cargo.toml
  crates/rspack_plugin_context_replacement/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_dll/Cargo.toml
  crates/rspack_plugin_dynamic_entry/Cargo.toml
  crates/rspack_plugin_ensure_chunk_conditions/Cargo.toml
  crates/rspack_plugin_entry/Cargo.toml
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_hmr/Cargo.toml
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_ignore/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_json/Cargo.toml
  crates/rspack_plugin_lazy_compilation/Cargo.toml
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  crates/rspack_plugin_limit_chunk_count/Cargo.toml
  crates/rspack_plugin_merge_duplicate_chunks/Cargo.toml
  crates/rspack_plugin_mf/Cargo.toml
  crates/rspack_plugin_no_emit_on_errors/Cargo.toml
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_remove_duplicate_modules/Cargo.toml
  crates/rspack_plugin_remove_empty_chunks/Cargo.toml
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime_chunk/Cargo.toml
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_size_limits/Cargo.toml
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
  crates/rspack_plugin_wasm/Cargo.toml
  crates/rspack_plugin_web_worker_template/Cargo.toml
  crates/rspack_plugin_worker/Cargo.toml
  crates/rspack_regex/Cargo.toml
  crates/rspack_util/Cargo.toml
  crates/swc_plugin_import/Cargo.toml
Labels: team

#8574 perf: move from `Buffer` to zero-copy `BufferSlice`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/source.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/util/source.ts
Labels: team, release: performance
