Repository web-infra-dev/rspack, pull requests merged in 2024-05, with the labels that each got.

#6423 fix: comment preserver should be placed prior to inline globals
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments-define/index.js
  packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments-define/webpack.config.js
  packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/new_treeshaking.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/output.snap.txt
Labels: team, release: bug fix

#6412 fix(rspack_loader_runner): char_boundary panic when debug content
  crates/rspack_loader_runner/src/content.rs
  crates/rspack_loader_runner/src/lib.rs
Labels: release: bug fix

#6415 perf: optimize execute module
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/compiler/module_executor/overwrite.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team, release: performance

#6421 feat: export Chunk and Module types from `@rspack/core`
  packages/rspack/etc/api.md
  packages/rspack/src/exports.ts
Labels: team, release: feature

#6446 docs: add blogs overview page
  website/docs/en/_meta.json
  website/docs/en/blog/_meta.json
  website/docs/en/blog/index.mdx
  website/docs/zh/_meta.json
  website/docs/zh/blog/_meta.json
  website/docs/zh/blog/index.mdx
Labels: team

#6450 fix(mf): __webpack_init_sharing__ with empty config
  packages/rspack-test-tools/tests/configCases/container-1-0/init-sharing-without-config/index.js
  packages/rspack-test-tools/tests/configCases/container-1-0/init-sharing-without-config/webpack.config.js
  packages/rspack/src/container/ModuleFederationPluginV1.ts
Labels: team, release: bug fix

#6455 chore: take down diff&canary release workflow temporarily
  .github/workflows/diff.yml.bak
  .github/workflows/release-canary.yml.bak
Labels: team

#6459 chore: add x test plugin
  x.mjs
Labels: team

#6460 chore: remove tokens
  .github/workflows/ci.yml
  .github/workflows/diff.yml.bak
  .github/workflows/ecosystem-ci-trigger.yml
  .github/workflows/github-issue-sync.yml
  .github/workflows/release-nightly.yml
Labels: team

#6462 perf(core): use prebundle to reduce dependencies
  .gitignore
  package.json
  packages/rspack/etc/api.md
  packages/rspack/package.json
  packages/rspack/prebundle.config.mjs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/global.d.ts
  packages/rspack/src/node/NodeWatchFileSystem.ts
  packages/rspack/tsconfig.json
  pnpm-lock.yaml
Labels: team, release: performance

#6464 chore: add tag to docs pr and release note
  .github/pr-labeler.yml
  .github/release.yml
Labels: team

#6370 fix(cli): load `@rspack/dev-server` on demand
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/tests/build/issue-6359/entry.js
  packages/rspack-cli/tests/build/issue-6359/index.test.ts
  packages/rspack-cli/tests/build/issue-6359/rspack.config.js
Labels: release: bug fix

#6465 fix: remove --force flag to fix prebundle
  package.json
  packages/rspack/etc/api.md
Labels: team, release: bug fix

#6451 fix: add trace log for module executor
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
Labels: team, release: bug fix

#6466 docs: update guide plugins
  website/docs/en/guide/features/plugin.mdx
Labels: release: document

#6471 docs(html-plugin): add comparison and examples
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: document

#6472 fix: css modules local ident name context
  Cargo.lock
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/css/deep-dir-local-path/deep/index.module.css
  packages/rspack-test-tools/tests/configCases/css/deep-dir-local-path/index.js
  packages/rspack-test-tools/tests/configCases/css/deep-dir-local-path/index.module.css
  packages/rspack-test-tools/tests/configCases/css/deep-dir-local-path/webpack.config.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-6435/index.js
Labels: team, release: bug fix

#6468 docs: check documentation coverage
  .github/workflows/reusable-build.yml
  package.json
  packages/rspack/api-extractor.json
  packages/rspack/etc/api.md
  packages/rspack/package.json
  packages/rspack/scripts/check-documentation-coverage.mjs
  packages/rspack/src/config/zod.ts
  packages/rspack/src/exports.ts
Labels: release: document

#6476 docs: update community plugin compatibility list
  website/components/CommunityCompatibleTable.tsx
  website/components/CompatibleCard.tsx
  website/components/PluginSupportStatusTable.module.scss
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/guide/compatibility/plugin.mdx
  website/docs/zh/guide/compatibility/plugin.mdx
Labels: team, release: document

#6475 docs(zh): update guide plugins
  website/docs/en/guide/features/plugin.mdx
  website/docs/zh/guide/features/plugin.mdx
Labels: team, release: document

#6484 docs: remove inconsistent title
  website/docs/zh/config/output.mdx
Labels: release: document

#6434 fix(rspack_plugin_mf): add chunk js matcher runtime to federation runtime
  Cargo.lock
  crates/rspack_plugin_mf/Cargo.toml
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_runtime/src/lib.rs
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/App.js
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/ComponentB.js
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/ComponentC.js
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/package.json
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/runtimePlugin.js
  packages/rspack-test-tools/tests/configCases/container-1-5/chunk-matcher/webpack.config.js
Labels: release: bug fix

#6485 docs: improve compat table style
  website/components/CommunityCompatibleTable.tsx
  website/components/PluginSupportStatusTable.module.scss
  website/components/PluginSupportStatusTable.tsx
  website/components/builtIns/mdx-components.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#6489 refactor: make hooks remove make_param
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_core/src/cache/local/code_splitting_cache.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_dynamic_entry/src/lib.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack-test-tools/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/snapshot/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/harmony/cjs-analyze-changed/snapshot/web/1.snap.txt
Labels: team

#6490 feat: compat chunkGroup.chunks
  packages/rspack-test-tools/tests/configCases/plugins/chunk-group-chunks/entry1.js
  packages/rspack-test-tools/tests/configCases/plugins/chunk-group-chunks/entry2.js
  packages/rspack-test-tools/tests/configCases/plugins/chunk-group-chunks/test.config.js
  packages/rspack-test-tools/tests/configCases/plugins/chunk-group-chunks/webpack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/ChunkGroup.ts
Labels: team, release: feature

#6492 fix: systemjs runtime extra semicolon
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  packages/rspack-test-tools/tests/configCases/library/system-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/system-runtime/test.config.js
  packages/rspack-test-tools/tests/configCases/library/system-runtime/webpack.config.js
Labels: team, release: bug fix

#6493 docs: remove loader compatible page
  website/components/CompatibleCard.tsx
  website/docs/en/guide/compatibility/_meta.json
  website/docs/en/guide/compatibility/loader.mdx
  website/docs/en/guide/features/loader.mdx
  website/docs/zh/guide/compatibility/_meta.json
  website/docs/zh/guide/compatibility/loader.mdx
  website/docs/zh/guide/features/loader.mdx
Labels: team, release: document

#6456 feat: support performance config
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_size_limits.rs
  crates/rspack_plugin_size_limits/Cargo.toml
  crates/rspack_plugin_size_limits/src/lib.rs
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/size.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/a.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/b.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/c.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/d.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/e.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/index.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-disabled/webpack.config.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/a.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/b.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/c.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/d.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/e.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/index.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-error/webpack.config.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/a.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/b.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/c.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/d.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/e.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/index.js
  packages/rspack-test-tools/tests/statsOutputCases/performance-no-hints/webpack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/SizeLimitsPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  webpack-test/statsCases/performance-different-mode-and-target/test.filter.js
  webpack-test/statsCases/performance-no-async-chunks-shown/test.filter.js
  webpack-test/statsCases/performance-oversize-limit-error/test.filter.js
  website/docs/en/config/_meta.json
  website/docs/en/config/performance.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/performance.mdx
Labels: release: feature

#6491 feat: support resolve.enforceExtension / descriptionFiles / importsFields options
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack/etc/api.md
  packages/rspack/src/config/zod.ts
  website/docs/en/config/resolve.mdx
  website/docs/zh/config/resolve.mdx
Labels: team, release: feature

#6495 docs: `resolve plugin` not supported
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#6497 docs: add some links for awesome-rspack
  README.md
  README.zh-CN.md
  website/docs/en/guide/compatibility/plugin.mdx
  website/docs/en/plugins/index.mdx
  website/docs/zh/guide/compatibility/plugin.mdx
  website/docs/zh/plugins/index.mdx
  website/theme/components/HomeFooter/index.tsx
Labels: team, release: document

#6498 fix: make *_dependencies memory leak
  crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/file_counter.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
Labels: team, release: bug fix

#6483 docs: internal plugins doc
  packages/rspack/etc/api.md
  packages/rspack/scripts/check-documentation-coverage.mjs
  packages/rspack/src/exports.ts
  website/docs/en/plugins/webpack/_meta.json
  website/docs/en/plugins/webpack/eval-source-map-dev-tool-plugin.mdx
  website/docs/en/plugins/webpack/internal-plugins.mdx
  website/docs/zh/plugins/webpack/_meta.json
  website/docs/zh/plugins/webpack/electron-target-plugin.mdx
  website/docs/zh/plugins/webpack/entry-plugin.mdx
  website/docs/zh/plugins/webpack/eval-source-map-dev-tool-plugin.mdx
  website/docs/zh/plugins/webpack/internal-plugins.mdx
Labels: release: document

#6499 docs: add vanilla-extract supported
  website/components/CommunityCompatibleTable.tsx
Labels: team, release: document

#6502 ci: release canary by dispatch
  .github/workflows/release-canary.yml
Labels: team

#6441 chore: update swc
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/provide/snapshot/output.snap.txt
Labels: team

#6503 ci: contribution hook
  .github/workflows/issue-pr-trigger.yml
Labels: team

#6420 feat: support contextModuleFactory beforeResolve hook
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_values/src/context_module_factory.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_macros/src/hook.rs
  crates/rspack_plugin_ignore/src/lib.rs
  packages/rspack-test-tools/tests/configCases/hooks/context-module-before-resolve/index.js
  packages/rspack-test-tools/tests/configCases/hooks/context-module-before-resolve/locale/en.js
  packages/rspack-test-tools/tests/configCases/hooks/context-module-before-resolve/locale/fr.js
  packages/rspack-test-tools/tests/configCases/hooks/context-module-before-resolve/locale/zh.js
  packages/rspack-test-tools/tests/configCases/hooks/context-module-before-resolve/webpack.config.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ContextModuleFactory.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/lite-tapable/index.ts
Labels: release: feature

#6507 docs: fix wrong heading
  website/docs/zh/plugins/webpack/ignore-plugin.mdx
Labels: release: document

#6506 docs: add missing `module` option of swc minimizer plugin
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
Labels: release: document

#6511 docs: add webpack-aligned plugin link
  website/components/PluginSupportStatusTable.tsx
Labels: team, release: document

#6510 docs: make the cases correct
  website/docs/en/blog/announcing-0-3.mdx
  website/docs/en/blog/announcing-0-5.mdx
  website/docs/en/blog/announcing-0-6.mdx
  website/docs/en/blog/module-federation-added-to-rspack.mdx
  website/docs/en/config/builtins.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/config/index.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/optimization.mdx
  website/docs/en/config/other-options.mdx
  website/docs/en/config/output.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/en/guide/features/dev-server.mdx
  website/docs/en/guide/migration/webpack.mdx
  website/docs/en/guide/optimization/tree-shaking.mdx
  website/docs/en/guide/tech/css.mdx
  website/docs/en/guide/tech/vue.mdx
  website/docs/en/misc/benchmark.mdx
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/api/node-api.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-3.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/blog/announcing-0-5.mdx
  website/docs/zh/blog/announcing-0-6.mdx
  website/docs/zh/config/builtins.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/config/other-options.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/guide/compatibility/examples.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/docs/zh/guide/optimization/tree-shaking.mdx
  website/docs/zh/guide/tech/nestjs.mdx
  website/docs/zh/misc/benchmark.mdx
  website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
Labels: team, release: document

#6516 docs: duplicated ignoreOrder option in CssExtractPlugin
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
Labels: team, release: document

#6515 docs: move rspack dev guide to documentation site
  website/docs/en/_meta.json
  website/docs/en/contribute/_meta.json
  website/docs/en/contribute/building/_meta.json
  website/docs/en/contribute/building/build-and-run.md
  website/docs/en/contribute/building/prerequisites.md
  website/docs/en/contribute/debugging.md
  website/docs/en/contribute/debugging/mix-debug.md
  website/docs/en/contribute/index.mdx
  website/docs/en/contribute/profiling.md
  website/docs/en/contribute/releasing.md
  website/docs/en/contribute/repro.md
  website/docs/en/contribute/rspack.md
  website/docs/en/contribute/rspack/loader.md
  website/docs/en/contribute/rspack/plugin.md
  website/docs/en/contribute/sending-pr.md
  website/docs/en/contribute/testing.md
  website/docs/en/contribute/testing/e2e.md
  website/docs/en/contribute/webpack.md
  website/docs/en/contribute/webpack/dependency.md
  website/docs/en/contribute/webpack/loader.md
  website/docs/en/contribute/workflows/meetings.md
  website/docs/en/contribute/workflows/misc.md
  website/docs/en/contribute/workflows/releases.md
  website/project-words.txt
  website/rspress.config.ts
  website/sortProjectWords.js
Labels: release: document

#6518 docs: reorganize the structure of dev guide
  website/docs/en/contribute/_meta.json
  website/docs/en/contribute/architecture/_meta.json
  website/docs/en/contribute/architecture/builtin-plugin.md
  website/docs/en/contribute/architecture/rspack-loader.md
  website/docs/en/contribute/building/_meta.json
  website/docs/en/contribute/debugging/mix-debug.md
  website/docs/en/contribute/development/_meta.json
  website/docs/en/contribute/development/building.md
  website/docs/en/contribute/development/debugging.md
  website/docs/en/contribute/development/prerequisites.md
  website/docs/en/contribute/development/profiling.md
  website/docs/en/contribute/development/releasing.md
  website/docs/en/contribute/development/testing.md
  website/docs/en/contribute/index.mdx
  website/docs/en/contribute/repro.md
  website/docs/en/contribute/rspack.md
  website/docs/en/contribute/sending-pr.md
  website/docs/en/contribute/testing/e2e.md
  website/docs/en/contribute/webpack.md
  website/docs/en/contribute/webpack/dependency.md
  website/docs/en/contribute/webpack/loader.md
  website/docs/en/contribute/workflows/meetings.md
  website/docs/en/contribute/workflows/misc.md
  website/docs/en/contribute/workflows/releases.md
Labels: team, release: document

#6520 docs: update outdated links and contents in dev guide
  CONTRIBUTING.md
  website/components/RandomMemberList.tsx
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/contribute/architecture/builtin-plugin.md
  website/docs/en/contribute/architecture/rspack-loader.md
  website/docs/en/contribute/development/building.md
  website/docs/en/contribute/development/debugging.md
  website/docs/en/contribute/development/prerequisites.md
  website/docs/en/contribute/index.mdx
  website/docs/en/misc/planning/future.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#6521 fix(minimizer): resolve error in minimizing esm asset file
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/index.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/pkg/package.json
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/pkg/pkg.js
  packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/webpack.config.js
Labels: release: bug fix

#6524 test: add type of defaults cases
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/defaults.ts
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/tests/Defaults.test.js
  packages/rspack-test-tools/tests/compilerCases/single-file.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem.js
  packages/rspack-test-tools/tests/defaultsCases/cache/cache.js
  packages/rspack-test-tools/tests/defaultsCases/cache/non-root.js
  packages/rspack-test-tools/tests/defaultsCases/config/array-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js
  packages/rspack-test-tools/tests/defaultsCases/config/records-path.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/async-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/both-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/output-module.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/sync-wasm.js
  packages/rspack-test-tools/tests/defaultsCases/filename/const.js
  packages/rspack-test-tools/tests/defaultsCases/filename/function.js
  packages/rspack-test-tools/tests/defaultsCases/library/library.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/name-root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/library/root-placeholder.js
  packages/rspack-test-tools/tests/defaultsCases/mode/development.js
  packages/rspack-test-tools/tests/defaultsCases/mode/empty.js
  packages/rspack-test-tools/tests/defaultsCases/mode/none.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/multi-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/single-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/optimization/true-runtime-chunk.js
  packages/rspack-test-tools/tests/defaultsCases/output/ecma-version.js
  packages/rspack-test-tools/tests/defaultsCases/output/unique-name.js
  packages/rspack-test-tools/tests/defaultsCases/stats/stats-false.js
  packages/rspack-test-tools/tests/defaultsCases/stats/stats-string.js
  packages/rspack-test-tools/tests/defaultsCases/stats/stats.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
  packages/rspack-test-tools/tests/defaultsCases/target_/node.js
  packages/rspack-test-tools/tests/defaultsCases/target_/webworker.js
Labels: team

#6526 refactor: make `make_artifact` as raw data
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team

#6527 fix: make entry add include dependencies
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/options/entry.rs
Labels: team, release: bug fix

#6529 docs: rename Node.js API to JavaScript API
  website/docs/en/api/_meta.json
  website/docs/en/api/index.mdx
  website/docs/en/api/javascript-api.mdx
  website/docs/en/config/stats.mdx
  website/docs/zh/api/_meta.json
  website/docs/zh/api/index.mdx
  website/docs/zh/api/javascript-api.mdx
  website/docs/zh/config/stats.mdx
  website/theme/components/HomeFooter/index.tsx
Labels: team, release: document

#6448 feat: deprecate `Compiler` and `MultiCompiler` API
  crates/node_binding/binding.d.ts
  crates/rspack_fs_node/src/node.rs
  packages/rspack-cli/tests/build/issue-6359/rspack.config.js
  packages/rspack-dev-server/src/middleware.ts
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/processor/snapshot.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/legacy-test/Output.test.js
  packages/rspack-test-tools/tests/statsAPICases/cache-disabled.js
  packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/placeholders.js
  packages/rspack/etc/api.md
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/Watching.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/fileSystem.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/logging/Logger.ts
  packages/rspack/src/node/NodeEnvironmentPlugin.ts
  packages/rspack/src/util/fs.ts
  packages/rspack/src/util/index.ts
Labels: team, breaking change, release: feature, release: breaking change

#5993 docs: update documentation contribution
  CONTRIBUTING.md
Labels: team, release: document

#6505 feat: deprecate `Compilation` API
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack-test-tools/tests/errorCases/error-map.js
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/resolve-fail-esm.js
  packages/rspack-test-tools/tests/errorCases/warning-map.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/createSource.ts
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/source.ts
Labels: team, breaking change, release: feature, release: breaking change

#6530 docs: dev server docs
  website/docs/en/config/dev-server.mdx
  website/docs/zh/config/dev-server.mdx
  website/project-words.txt
Labels: release: document

#6528 feat: export types of CSS extract plugin
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/exports.ts
Labels: team, release: feature

#6531 test: add type of hook cases
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/hook.ts
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/test.js
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/test.js
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/test.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/test.js
Labels: team

#6543 docs: list workbox & react-refresh webpack plugin compatibility status
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/project-words.txt
Labels: team, release: document

#6542 ci: renovate lark trigger
  .github/workflows/issue-pr-trigger.yml
Labels: team

#6536 chore: remove new split chunks options
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_binding_options/src/options/raw_optimization.rs
  crates/rspack_core/src/options/experiments.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
Labels: team

#6534 refactor: align js render bootstrap
  Cargo.lock
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$dec0863f5e812ee7cadd$.css
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$dec0863f5e812ee7cadd$.css
  plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  plugin-test/css-extract/cases/custom-loader-with-functional-exports/expected/main.js
  plugin-test/css-extract/cases/es-named-export-output-module/expected/main.mjs
  plugin-test/css-extract/cases/es-named-export/expected/main.js
  plugin-test/css-extract/cases/export-only-locals-and-es-named-export/expected/main.js
  plugin-test/css-extract/cases/export-only-locals-commonjs/expected/main.js
  plugin-test/css-extract/cases/export-only-locals/expected/main.js
  plugin-test/css-extract/cases/hmr/expected/main.js
  plugin-test/css-extract/cases/insert-function/expected/main.js
  plugin-test/css-extract/cases/insert-string/expected/main.js
  plugin-test/css-extract/cases/insert-undefined/expected/main.js
  plugin-test/css-extract/cases/multiple-compiler/expected/one-main.js
  plugin-test/css-extract/cases/multiple-compiler/expected/two-main.js
  plugin-test/css-extract/cases/new-url/expected/main.js
  plugin-test/css-extract/cases/no-runtime/expected/main.js
  plugin-test/css-extract/cases/runtime/expected/runtime~main.js
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team

#6382 feat: improve diagnostics if expressions passed into `DefinePlugin` are failed to parse
  Cargo.lock
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_swc_visitors/Cargo.toml
  crates/rspack_swc_visitors/src/define.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/define_plugin_warning/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/define_plugin_warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/define_plugin_warning/webpack.config.js
Labels: release: feature

#6376 feat: support cjs css with css esModule generator options
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/snapshot/output.snap.txt
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  webpack-test/configCases/css/cjs-module-syntax/index.js
  webpack-test/configCases/css/cjs-module-syntax/style.module.css
  webpack-test/configCases/css/cjs-module-syntax/test.config.js
  webpack-test/configCases/css/cjs-module-syntax/webpack.config.js
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
  website/project-words.txt
Labels: team, release: feature

#6544 chore: revert cargo lock to fix ci
  Cargo.lock
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/snapshot/output.snap.txt
Labels: team

#6545 docs: improve plugins docs
  website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/en/plugins/webpack/banner-plugin.mdx
  website/docs/en/plugins/webpack/ignore-plugin.mdx
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/en/plugins/webpack/normal-module-replacement-plugin.mdx
  website/docs/en/plugins/webpack/progress-plugin.mdx
  website/docs/en/plugins/webpack/source-map-dev-tool-plugin.mdx
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
  website/docs/zh/plugins/webpack/banner-plugin.mdx
  website/docs/zh/plugins/webpack/ignore-plugin.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/plugins/webpack/normal-module-replacement-plugin.mdx
  website/docs/zh/plugins/webpack/progress-plugin.mdx
  website/docs/zh/plugins/webpack/source-map-dev-tool-plugin.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: release: document

#6547 fix: when comparing, cache group index should consider before modules
  crates/rspack_plugin_split_chunks/src/module_group.rs
Labels: team, release: bug fix

#6548 refactor: remove build & resolve_module cache
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/cache/occasion/mod.rs
  crates/rspack_core/src/cache/occasion/resolve_module.rs
  crates/rspack_core/src/cache/snapshot/manager.rs
  crates/rspack_core/src/cache/snapshot/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/cutout/fix_build_meta.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/self_module_factory.rs
  packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js
Labels: team

#6551 docs: mark some `Incompatible` plugins `Alternative`
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#5834 feat(create-rspack): add template-vue-ts
  packages/create-rspack/index.js
  packages/create-rspack/template-vue-ts/.npmignore
  packages/create-rspack/template-vue-ts/_gitignore
  packages/create-rspack/template-vue-ts/index.html
  packages/create-rspack/template-vue-ts/package.json
  packages/create-rspack/template-vue-ts/rspack.config.ts
  packages/create-rspack/template-vue-ts/src/App.vue
  packages/create-rspack/template-vue-ts/src/assets/rspack.svg
  packages/create-rspack/template-vue-ts/src/assets/vue.svg
  packages/create-rspack/template-vue-ts/src/components/HelloWorld.vue
  packages/create-rspack/template-vue-ts/src/main.ts
  packages/create-rspack/template-vue-ts/src/shims-vue.d.ts
  packages/create-rspack/template-vue-ts/src/style.css
  packages/create-rspack/template-vue-ts/tsconfig.json
  pnpm-lock.yaml
Labels: release: feature

#6431 perf: improve determine_export_assignments
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
Labels: release: performance

#6558 ci: support release beta version
  .github/workflows/release.yml
Labels: team

#6559 release: v0.7.0-beta.0
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#6566 docs: remove canary comment release in contribute guide
  .github/workflows/release-canary.yml
  website/docs/en/contribute/development/releasing.md
Labels: team, release: document

#6555 chore: remove exportsConvention for css generator
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team

#6519 docs: new testing guide
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/processor/stats-api.ts
  webpack-test/README.md
  website/docs/en/contribute/development/_meta.json
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/en/contribute/development/testing-webpack.mdx
  website/docs/en/contribute/development/testing.md
  website/docs/en/contribute/development/testing.mdx
  website/docs/zh/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/testing-webpack.mdx
  website/docs/zh/contribute/development/testing.mdx
Labels: team, release: document

#6567 fix: change the data URI type in ModuleFederationPlugin
  packages/rspack/src/container/ModuleFederationPlugin.ts
Labels: team, release: bug fix

#6565 fix: module_executor keep make_failed_module
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery/changed-file.js
  packages/rspack-test-tools/tests/hotCases/css/recovery/index.css
  packages/rspack-test-tools/tests/hotCases/css/recovery/index.js
  packages/rspack-test-tools/tests/hotCases/css/recovery/rspack.config.js
Labels: team, release: bug fix

#6570 fix: finish_module_task skip self reference connection
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
Labels: team, release: bug fix

#6575 test: fix dependencies of test tools
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
Labels: team

#6577 test: fix dependencies of test tools
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
Labels: team

#6578 docs: list more webpack-contrib plugins compatible
  website/components/CommunityCompatibleTable.tsx
Labels: team, release: document

#5915 feat: lazy compilation
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_lazy_compilation.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/module_factory.rs
  crates/rspack_core/src/utils/queue.rs
  crates/rspack_database/src/database.rs
  crates/rspack_macros/src/plugin.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_lazy_compilation/Cargo.toml
  crates/rspack_plugin_lazy_compilation/expand.rs
  crates/rspack_plugin_lazy_compilation/src/backend.rs
  crates/rspack_plugin_lazy_compilation/src/dependency.rs
  crates/rspack_plugin_lazy_compilation/src/factory.rs
  crates/rspack_plugin_lazy_compilation/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  crates/rspack_plugin_runtime/src/lib.rs
  packages/rspack-dev-server/src/server.ts
  packages/rspack/etc/api.md
  packages/rspack/src/Watching.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/lazyCompilation.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  webpack-test/hotCases/lazy-compilation/context/test.filter.js
  webpack-test/hotCases/lazy-compilation/context/webpack.config.js
  webpack-test/hotCases/lazy-compilation/https/test.filter.js
  webpack-test/hotCases/lazy-compilation/https/webpack.config.js
  webpack-test/hotCases/lazy-compilation/module-test/test.filter.js
  webpack-test/hotCases/lazy-compilation/module-test/webpack.config.js
  webpack-test/hotCases/lazy-compilation/only-entries/test.filter.js
  webpack-test/hotCases/lazy-compilation/simple/test.filter.js
  webpack-test/hotCases/lazy-compilation/simple/webpack.config.js
  webpack-test/hotCases/lazy-compilation/unrelated/test.filter.js
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: release: feature

#6576 fix: css-extract-plugin should keep file dependencies
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_extract_css/src/parser_and_generator.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  packages/playground/cases/react/tailwindcss-with-css-extract/index.test.ts
  packages/playground/cases/react/tailwindcss-with-css-extract/rspack.config.js
  packages/playground/cases/react/tailwindcss-with-css-extract/src/App.css
  packages/playground/cases/react/tailwindcss-with-css-extract/src/App.jsx
  packages/playground/cases/react/tailwindcss-with-css-extract/src/index.html
  packages/playground/cases/react/tailwindcss-with-css-extract/src/main.jsx
  packages/playground/cases/react/tailwindcss-with-css-extract/tailwind.config.js
Labels: team, release: bug fix

#6579 test: pass expect in test env
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/defaults.ts
  packages/rspack-test-tools/src/case/error.ts
  packages/rspack-test-tools/src/case/stats-api.ts
  packages/rspack-test-tools/src/helper/legacy/createFakeWorker.js
  packages/rspack-test-tools/src/helper/legacy/createLazyTestEnv.js
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/diagnostic.ts
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack-test-tools/src/processor/hash.ts
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/snapshot.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/src/runner/runner/cjs.ts
  packages/rspack-test-tools/src/runner/runner/web/fake.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
  packages/rspack-test-tools/src/runner/type.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack-test-tools/src/test/simple.ts
  packages/rspack-test-tools/src/type.ts
  packages/rspack-test-tools/tests/Defaults.test.js
Labels: team

#6585 perf(core): prebundle enhanced-resolve to reduce dependencies
  packages/rspack/etc/api.md
  packages/rspack/package.json
  packages/rspack/prebundle.config.mjs
  packages/rspack/tsconfig.json
  pnpm-lock.yaml
Labels: team, release: performance

#6363 fix: support `"..."` in importFields
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack/src/config/defaults.ts
  webpack-test/configCases/resolve-merging/imports-fields/index.js
  webpack-test/configCases/resolve-merging/imports-fields/node_modules/lib/index.js
  webpack-test/configCases/resolve-merging/imports-fields/node_modules/lib/lib.mjs
  webpack-test/configCases/resolve-merging/imports-fields/node_modules/lib/package.json
  webpack-test/configCases/resolve-merging/imports-fields/package.json
  webpack-test/configCases/resolve-merging/imports-fields/pkg.mjs
  webpack-test/configCases/resolve-merging/imports-fields/webpack.config.js
Labels: team, release: bug fix

#6582 test: compiler type extends
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/builtin.ts
  packages/rspack-test-tools/src/case/compiler.ts
  packages/rspack-test-tools/src/case/config.ts
  packages/rspack-test-tools/src/case/defaults.ts
  packages/rspack-test-tools/src/case/diagnostic.ts
  packages/rspack-test-tools/src/case/error.ts
  packages/rspack-test-tools/src/case/hash.ts
  packages/rspack-test-tools/src/case/hot-step.ts
  packages/rspack-test-tools/src/case/hot.ts
  packages/rspack-test-tools/src/case/normal.ts
  packages/rspack-test-tools/src/case/stats-api.ts
  packages/rspack-test-tools/src/case/stats-output.ts
  packages/rspack-test-tools/src/case/treeshaking.ts
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/builtin.ts
  packages/rspack-test-tools/src/processor/config.ts
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/diagnostic.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/processor/error.ts
  packages/rspack-test-tools/src/processor/hash.ts
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/processor/multi.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/processor/simple.ts
  packages/rspack-test-tools/src/processor/snapshot.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/src/processor/treeshaking.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/tests/Defaults.test.js
Labels: team

#6587 fix: optional context dependency
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/locale.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/optional-context-dependency/stats.err
Labels: team, release: bug fix

#6588 refactor: create codegen dependencies
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#6586 release: 0.7.0-beta.1
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#6589 test: fix hot snapshot recovery checker
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/recovery/index.js
Labels: team

#6591 fix: panic when update entry dependency
  crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
Labels: team, release: bug fix

#6592 test: check hot step match
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/diff.ts
  packages/rspack-test-tools/src/case/stats-output.ts
  packages/rspack-test-tools/src/helper/directory.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js
  packages/rspack-test-tools/tests/hotCases/chunk/issue-4476/file.js
  packages/rspack-test-tools/tests/hotCases/chunk/multi-chunk-single-runtime/file.js
  packages/rspack-test-tools/tests/hotCases/chunk/multi-chunk-single-runtime/main/index.js
  packages/rspack-test-tools/tests/hotCases/chunk/multi-chunk/file.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/file.js
  packages/rspack-test-tools/tests/hotCases/runtime/dispose-removed-chunk/a.js
  packages/rspack-test-tools/tests/hotCases/runtime/update-multiple-times/file.js
Labels: team

#6598 revert: revert swc comment preserver (#6389)
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-javascript/provide/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/index.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/treeShakingCases/webpack-innergraph-try-globals/__snapshots__/treeshaking.snap.txt
  plugin-test/css-extract/enforceEsm.test.js
Labels: team

#6595 fix: context module after resolve
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_lazy_compilation.rs
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/context_module_factory.rs
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/regex.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_plugin_javascript/src/dependency/context/mod.rs
  crates/rspack_regex/src/lib.rs
  packages/rspack-test-tools/tests/configCases/context-module/critical-warning/rspack.config.js
  packages/rspack-test-tools/tests/configCases/context-module/without-extension/index.js
  packages/rspack-test-tools/tests/configCases/context-module/without-extension/rspack.config.js
  packages/rspack-test-tools/tests/configCases/context-module/without-extension/sub/a.js
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/lazyCompilation.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
Labels: team, release: bug fix

#6601 docs: add moment-locales-webpack-plugin support status
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#6600 fix: fix module type export name
  crates/rspack_plugin_library/src/module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/output-module/rspack-issue-6572/index.js
  packages/rspack-test-tools/tests/configCases/output-module/rspack-issue-6572/lib.js
  packages/rspack-test-tools/tests/configCases/output-module/rspack-issue-6572/rspack.config.js
Labels: team, release: bug fix

#6602 docs: remove snapshot
  website/docs/en/blog/announcing-0-7.mdx
  website/docs/zh/blog/announcing-0-7.mdx
Labels: team, release: document

#6593 feat: remove snapshot config
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_snapshot.rs
  crates/rspack_core/src/options/snapshot.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/cache/issues-6381/rspack.config.js
  packages/rspack-test-tools/tests/configCases/cache/issuse-3254/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/mode/production.js
  packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/_meta.json
  website/docs/en/config/cache.mdx
  website/docs/en/config/snapshot.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/cache.mdx
  website/docs/zh/config/snapshot.mdx
Labels: team, release: feature

#6604 docs: fix the video component in md
  website/docs/en/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/debugging.mdx
  website/docs/zh/contribute/index.mdx
Labels: release: document

#6599 docs: change Storybook migration to storybook-rsbuild
  website/docs/en/guide/migration/storybook.mdx
  website/docs/zh/guide/migration/storybook.mdx
Labels: release: document

#6609 docs: example for lazy compilation with custom global entry
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#6608 release: 0.7.0-beta.2
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-plugin-minify/package.json
  packages/rspack-plugin-react-refresh/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#6605 test: handle test error more friendly
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack-test-tools/src/test/simple.ts
  packages/rspack-test-tools/src/test/tester.ts
  packages/rspack-test-tools/src/type.ts
  packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js
Labels: team

#6610 chore(workflow): enable MDX type hints
  website/package.json
  website/pnpm-lock.yaml
  website/theme/index.tsx
  website/tsconfig.json
Labels: team

#6612 fix: hmr should consider all imported members
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/bar.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/changed-file.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/entry.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/foo.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/index.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/package.json
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/reexport.js
  packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/rspack.config.js
Labels: team, release: bug fix

#6615 docs: list more plugins compatible status
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#6617 docs: recommend using sass-embedded for performance
  website/docs/en/guide/tech/css.mdx
  website/docs/zh/guide/tech/css.mdx
Labels: team, release: document

#6611 test: vitest compatiblity
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/case/defaults.ts
  packages/rspack-test-tools/src/case/diagnostic.ts
  packages/rspack-test-tools/src/helper/index.ts
  packages/rspack-test-tools/src/helper/legacy/createLazyTestEnv.js
  packages/rspack-test-tools/src/helper/update-snapshot.ts
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/builtin.ts
  packages/rspack-test-tools/src/processor/diagnostic.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/processor/index.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/processor/snapshot.ts
  packages/rspack-test-tools/src/processor/treeshaking.ts
  packages/rspack-test-tools/src/runner/runner/cjs.ts
  packages/rspack-test-tools/src/runner/type.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack-test-tools/src/test/simple.ts
  packages/rspack-test-tools/src/type.ts
Labels: team

#6619 docs(react): add guide for React Compiler
  website/docs/en/guide/tech/react.mdx
  website/docs/zh/guide/tech/react.mdx
Labels: team, release: document

#6620 refactor: rename cache to old_cache
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_core/src/old_cache/local/mod.rs
  crates/rspack_core/src/old_cache/mod.rs
  crates/rspack_core/src/old_cache/occasion/code_generate.rs
  crates/rspack_core/src/old_cache/occasion/create_chunk_assets.rs
  crates/rspack_core/src/old_cache/occasion/mod.rs
  crates/rspack_core/src/old_cache/storage/memory.rs
  crates/rspack_core/src/old_cache/storage/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team

#6623 feat: support `stage` option of `BannerPlugin`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
  crates/rspack_plugin_banner/src/lib.rs
  packages/rspack-test-tools/tests/configCases/builtins/banner-stage/a.js
  packages/rspack-test-tools/tests/configCases/builtins/banner-stage/b.js
  packages/rspack-test-tools/tests/configCases/builtins/banner-stage/empty.png
  packages/rspack-test-tools/tests/configCases/builtins/banner-stage/index.js
  packages/rspack-test-tools/tests/configCases/builtins/banner-stage/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/banner-stage/test.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/BannerPlugin.ts
  website/docs/en/plugins/webpack/banner-plugin.mdx
  website/docs/zh/plugins/webpack/banner-plugin.mdx
Labels: release: feature

#6621 test: add custom compiler factories in context
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/compiler.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/test/context.ts
  packages/rspack-test-tools/src/type.ts
Labels: team

#6594 refactor: analyze css dependencies with css-module-lexer
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/dependency/dependency_category.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/dependency/export.rs
  crates/rspack_plugin_css/src/dependency/local_ident.rs
  crates/rspack_plugin_css/src/dependency/mod.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_css/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_swc_css_minimizer/Cargo.toml
  crates/rspack_plugin_swc_css_minimizer/src/lib.rs
  crates/rspack_plugin_swc_css_minimizer/src/swc_css_compiler.rs
  packages/rspack-cli/tests/build/basic/public/main.js
  packages/rspack-cli/tests/build/basic/public/main.js.map
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-ident-name/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css/at-import-in-the-middle/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/index.css
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/node_modules/normalize.css/LICENSE.md
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/node_modules/normalize.css/normalize.css
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/node_modules/normalize.css/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/node_modules/pkg/img.png
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/node_modules/pkg/index.css
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/node_modules/pkg/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/css-module-request-prefix/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/a.css
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/b.css
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/c.css
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/index.css
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err
Labels: team

#6580 fix: provide plugin should support IIFE
  crates/rspack_binding_options/src/plugins/js_loader_resolver.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/provide_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/configCases/builtins/provide/index.js
  packages/rspack-test-tools/tests/configCases/builtins/provide/rspack.config.js
  webpack-test/configCases/plugins/provide-plugin/test.filter.js
Labels: release: bug fix

#6627 chore: enable more tests
  webpack-test/configCases/split-chunks/chunk-filename-delimiter-default/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-async-node/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-node-13130/test.filter.js
  webpack-test/configCases/split-chunks/runtime-chunk-node/test.filter.js
Labels: team

#6628 perf: change JS code target to ES2021
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  tsconfig.base.json
Labels: team, release: performance

#6629 fix: browserslist resolve is broken by prebundle
  packages/rspack/prebundle.config.mjs
Labels: team, release: bug fix

#6630 test: export runner
  packages/rspack-test-tools/etc/api.md
  packages/rspack-test-tools/src/runner/index.ts
  packages/rspack-test-tools/src/runner/runner/index.ts
Labels: team

#6562 docs: announcing 0.7
  website/docs/en/blog/_meta.json
  website/docs/en/blog/announcing-0-7.mdx
  website/docs/en/blog/index.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/misc/planning/roadmap.mdx
  website/docs/zh/blog/_meta.json
  website/docs/zh/blog/announcing-0-7.mdx
  website/docs/zh/blog/index.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/misc/planning/roadmap.mdx
  website/project-words.txt
Labels: team, release: document

#6634 chore: update swc-minifier
  Cargo.lock
  Cargo.toml
Labels: team

#6635 docs: fix og image URL
  website/rspress.config.ts
Labels: release: document

#6637 chore: cleanup compilation struct
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
Labels: team

#6638 docs: improve lazy compilation document
  website/docs/en/blog/announcing-0-7.mdx
  website/docs/en/config/experiments.mdx
  website/docs/zh/blog/announcing-0-7.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#6640 feat: support target in loader context
  packages/rspack-test-tools/tests/configCases/loader/context-target/a.js
  packages/rspack-test-tools/tests/configCases/loader/context-target/index.js
  packages/rspack-test-tools/tests/configCases/loader/context-target/my-loader.js
  packages/rspack-test-tools/tests/configCases/loader/context-target/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack/etc/api.md
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: team, release: feature

#6642 fix: loader context target array
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/loader/context-target-array/a.js
  packages/rspack-test-tools/tests/configCases/loader/context-target-array/index.js
  packages/rspack-test-tools/tests/configCases/loader/context-target-array/my-loader.js
  packages/rspack-test-tools/tests/configCases/loader/context-target-array/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/output-module.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
  packages/rspack-test-tools/tests/defaultsCases/target_/node.js
  packages/rspack-test-tools/tests/defaultsCases/target_/webworker.js
  packages/rspack/etc/api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#6650 docs: change compatibility link
  website/docs/en/index.md
  website/docs/zh/index.md
  website/theme/components/HomeFooter/index.tsx
Labels: release: document

#6653 fix: css modules ident escape
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-ident-name/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/concatenate-modules/with-css/index.js
  packages/rspack-test-tools/tests/configCases/css/deep-dir-local-path/index.js
  packages/rspack-test-tools/tests/hotCases/css/css-modules/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/index.js
  webpack-test/configCases/css/cjs-module-syntax/index.js
  webpack-test/configCases/css/default-exports-parser-options/index.js
  webpack-test/configCases/css/named-exports-parser-options/index.js
Labels: team, release: bug fix

#6646 docs: update esModule generator description & version
  website/docs/en/config/module.mdx
Labels: release: document

#6655 fix: should not lazy static context element dependency
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_dependency.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
Labels: team, release: bug fix

#6656 fix: replace `\0` to `\u200b`
  crates/rspack_core/src/utils/identifier.rs
  crates/rspack_loader_runner/src/loader.rs
  packages/rspack-test-tools/src/helper/legacy/parseResource.js
  packages/rspack-test-tools/src/helper/util/identifier.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/a.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/convert-loader.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/empty.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/import-loader.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/index.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/source-loader.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/identifier.js
Labels: team, release: bug fix

#6672 fix: apply js rule on module federation runtime
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/module.js
  packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module/match-resource-mimetype/get-source.js
  packages/rspack-test-tools/tests/configCases/module/match-resource-mimetype/index.js
  packages/rspack-test-tools/tests/configCases/module/match-resource-mimetype/rspack.config.js
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
Labels: team, release: bug fix

#6670 refactor: make_module_graph use immutable compilation
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
Labels: team

#6669 docs: rewrite the webpack migration guide
  website/docs/en/guide/compatibility/plugin.mdx
  website/docs/en/guide/migration/webpack.mdx
  website/docs/zh/guide/compatibility/plugin.mdx
  website/docs/zh/guide/migration/webpack.mdx
  website/project-words.txt
Labels: team, release: document

#6674 feat: lazy compilation ignore global entry
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/dependency/entry.rs
  crates/rspack_plugin_dynamic_entry/src/lib.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  packages/playground/cases/lazy-compilation/ignore-entry/index.test.ts
  packages/playground/cases/lazy-compilation/ignore-entry/rspack.config.js
  packages/playground/cases/lazy-compilation/ignore-entry/src/index.js
  packages/playground/playwright.config.ts
Labels: team, release: feature

#6678 docs: display edit link in the footer
  website/rspress.config.ts
Labels: team, release: document

#6680 docs: correct GitHub spelling
  CONTRIBUTING.md
  website/docs/en/contribute/index.mdx
  website/docs/zh/contribute/index.mdx
Labels: release: document

#6679 chore: fix testDir
  packages/playground/playwright.config.ts
Labels: team

#6681 docs: exports presence
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#6688 fix: use numeric moduleId
  crates/rspack_core/src/dependency/runtime_template.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/to-string.js
  plugin-test/copy-plugin/build/main.js
  webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: release: bug fix

#6684 ci: incremental patch version when release canary and nightly
  scripts/release/version.mjs
Labels: team

#6676 perf: parallel collect export presence diagnostics
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
Labels: team, release: performance

#6677 feat: partial support compilation.additionalTreeRuntimeRequirements hook
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/src/lib.rs
  crates/rspack_binding_values/src/runtime.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_runtime/src/chunk_prefetch_preload.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  packages/rspack-test-tools/tests/configCases/hooks/additional-tree-runtime-requirements/index.js
  packages/rspack-test-tools/tests/configCases/hooks/additional-tree-runtime-requirements/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/RuntimeGlobals.ts
Labels: team, release: feature

#6685 feat: add `optimization.moduleIds: 'natural'`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_ids/src/natural_module_ids_plugin.rs
  packages/rspack-test-tools/tests/configCases/loader/options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/optimization/module-ids-natural/a.js
  packages/rspack-test-tools/tests/configCases/optimization/module-ids-natural/b.js
  packages/rspack-test-tools/tests/configCases/optimization/module-ids-natural/c.js
  packages/rspack-test-tools/tests/configCases/optimization/module-ids-natural/d.js
  packages/rspack-test-tools/tests/configCases/optimization/module-ids-natural/index.js
  packages/rspack-test-tools/tests/configCases/optimization/module-ids-natural/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/NaturalModuleIdsPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: release: feature

#6692 feat: add `optimization.chunkIds: 'natural'`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_ids/src/natural_chunk_ids_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/e1.js
  packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/e2.js
  packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/modules/a.js
  packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/modules/b.js
  packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/modules/c.js
  packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/rspack.config.js
  packages/rspack/etc/api.md
  packages/rspack/src/builtin-plugin/NaturalChunkIdsPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  website/components/PluginSupportStatusTable.tsx
Labels: release: feature

#6693 docs: update support status of `BannerPlugin`
  website/components/PluginSupportStatusTable.tsx
Labels: release: document

#6694 refactor: regenerate module_graph after finish make
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/cutout/mod.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/module.rs
Labels: team

#6682 fix: installedCssChunks unicode error on windows
  Cargo.lock
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_extract_css/src/runtime.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  plugin-test/css-extract/cases/issue-6649/expected/main.js
  plugin-test/css-extract/cases/issue-6649/src/chunk.js
  plugin-test/css-extract/cases/issue-6649/src/index.js
  plugin-test/css-extract/cases/issue-6649/src/inject.css
  plugin-test/css-extract/cases/issue-6649/webpack.config.js
Labels: team, release: bug fix
