Repository web-infra-dev/rspack, pull requests merged in 2024-02, with the labels that each got.

#5540 feat(rspack): align default resolveOptions with webpack
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#5553 chore: update issue template with title prefix
  .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
  .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
Labels: team

#5549 refactor: move chunk_group_info to code splitting
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/execute_module.rs
Labels: team

#5555 chore: rename split_chunks_new to split_chunks
  .github/CODEOWNERS
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_split_chunks/LICENSE
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/lib.rs
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group_test.rs
  crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
  crates/rspack_plugin_split_chunks/src/options/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/chunk.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_request.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: team

#5522 feat: support custom source root
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/tests/configCases/plugins/source-map-dev-tool-plugin-source-root/index.js
  packages/rspack/tests/configCases/plugins/source-map-dev-tool-plugin-source-root/webpack.config.js
Labels: release: feature

#5538 fix: wrongly generated alternative requests in context modules
  crates/rspack_core/src/context_module.rs
  packages/rspack/tests/cases/context/rspack-issue-5535/index.js
  packages/rspack/tests/cases/context/rspack-issue-5535/test-module/index.js
  packages/rspack/tests/cases/context/rspack-issue-5535/test-module/modules/test.module.js
Labels: team, release: bug fix

#5558 chore: align more tests
  .eslintignore
  .typos.toml
  packages/rspack/tests/configCases/asset-url/relative-rewrite/index.css
  packages/rspack/tests/configCases/asset-url/relative-rewrite/index.js
  packages/rspack/tests/configCases/asset-url/relative-rewrite/webpack.config.js
  packages/rspack/tests/configCases/externals/externals-system/index.js
  packages/rspack/tests/configCases/externals/externals-system/reexport-external.js
  packages/rspack/tests/configCases/externals/externals-system/test.config.js
  packages/rspack/tests/configCases/externals/externals-system/webpack.config.js
  packages/rspack/tests/helpers/FakeDocument.js
  packages/rspack/tests/hotCases/errors/events/index.js
  packages/rspack/tests/hotCases/errors/events/k.js
  packages/rspack/tests/hotCases/fake-update-loader.js
  packages/rspack/tests/hotCases/invalidate/during-idle/a.js
  packages/rspack/tests/hotCases/invalidate/during-idle/b.js
  packages/rspack/tests/hotCases/invalidate/during-idle/c.js
  packages/rspack/tests/hotCases/invalidate/during-idle/index.js
  packages/rspack/tests/hotCases/invalidate/during-idle/module.js
  packages/rspack/tests/watchCases/simple/simple/0/changing-file.js
  packages/rspack/tests/watchCases/simple/simple/0/index.js
  packages/rspack/tests/watchCases/simple/simple/1/changing-file.js
  packages/rspack/tests/watchCases/simple/simple/2/changing-file.js
  scripts/test/binary-path.cjs
  scripts/test/diff-exclude.cjs
  scripts/test/diff.cjs
  scripts/test/math.cjs
  scripts/test/recursive-compare.cjs
  webpack-test/helpers/captureStdio.js
  webpack-test/hotCases/fake-update-loader.js
  webpack-test/watchCases/simple/simple/test.filter.js
Labels: team

#5562 fix: should split chunks size larger than maxSize
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack/tests/configCases/split-chunks/issue-5267/chunk.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/file-A2.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/file-B2.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/file-a1.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/file-b1.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/index.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/test.config.js
  packages/rspack/tests/configCases/split-chunks/issue-5267/webpack.config.js
Labels: team, release: bug fix

#5559 fix: 🐛 call finish module in rebuild_module instead of update_module_graph
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
Labels: team, release: bug fix

#5543 refactor: immutable module graph during code generation
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team

#5569 chore: more total cases
  webpack-test/Stats.test.js
  webpack-test/TestCasesHot.test.js
  webpack-test/jest.config.js
Labels: team

#5568 fix: exec `per_statement` parser hooks
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
  packages/rspack/tests/cases/parsing/nested-webpack-require/a.js
  packages/rspack/tests/cases/parsing/nested-webpack-require/b.js
  packages/rspack/tests/cases/parsing/nested-webpack-require/index.js
  pnpm-lock.yaml
Labels: release: bug fix

#5565 fix: json parse error
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack/tests/diagnostics/factorize/json-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/json-module-build-failed/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/json-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/json-module-build-failed/syntax-error.json
  packages/rspack/tests/diagnostics/module-parse-failed/json-module-build-failed/webpack.config.js
  packages/rspack/tests/diagnostics/module-parse-failed/module-parse-error/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/module-parse-error/non-recoverable.js
  packages/rspack/tests/diagnostics/module-parse-failed/module-parse-error/recoverable.js
  packages/rspack/tests/diagnostics/module-parse-failed/module-parse-error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/module-parse-error/webpack.config.js
  packages/rspack/tests/diagnostics/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack/tests/hotCases/json/error-in-json/errors.js
Labels: team, release: bug fix

#5575 fix(cli): fix cts support
  packages/rspack-cli/src/utils/isEsmFile.ts
  packages/rspack-cli/tests/build/config/cjs_in_esm/main.ts
  packages/rspack-cli/tests/build/config/cjs_in_esm/package.json
  packages/rspack-cli/tests/build/config/cjs_in_esm/rspack.config.cjs
  packages/rspack-cli/tests/build/config/cjs_in_esm/rspack.config.cts
  packages/rspack-cli/tests/build/config/config.test.ts
Labels: team, release: bug fix

#5478 fix: zod.devtool - missing inline-nosources-cheap-source-map
  packages/rspack/src/config/zod.ts
Labels: release: bug fix

#5581 fix: source root error in windows
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/tests/configCases/plugins/source-map-dev-tool-plugin-source-root/index.js
  packages/rspack/tests/configCases/plugins/source-map-dev-tool-plugin-source-root/webpack.config.js
Labels: release: bug fix

#5495 feat(devtool): add "eval" support
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/src/builtin-plugin/EvalDevToolModulePlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/configCases/source-map/eval-only/index.js
  packages/rspack/tests/configCases/source-map/eval-only/index.scss
  packages/rspack/tests/configCases/source-map/eval-only/test.config.js
  packages/rspack/tests/configCases/source-map/eval-only/test.js
  packages/rspack/tests/configCases/source-map/eval-only/webpack.config.js
Labels: release: feature

#5552 fix: 🐛 inner graph extend class super with constructor
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  webpack-test/cases/cjs-tree-shaking/mutate/test.filter.js
  webpack-test/cases/inner-graph/extend-class/a.js
  webpack-test/cases/inner-graph/extend-class/b.js
  webpack-test/cases/inner-graph/extend-class/c.js
  webpack-test/cases/inner-graph/extend-class/dep1.js
  webpack-test/cases/inner-graph/extend-class/dep2.js
  webpack-test/cases/inner-graph/extend-class/dep3.js
  webpack-test/cases/inner-graph/extend-class/index.js
  webpack-test/cases/inner-graph/extend-class/module3.js
  webpack-test/cases/inner-graph/extend-class/module4.js
  webpack-test/cases/inner-graph/extend-class/module5.js
  webpack-test/cases/inner-graph/extend-class/module6.js
  webpack-test/cases/inner-graph/extend-class/module7.js
  webpack-test/cases/inner-graph/extend-class/module8.js
  webpack-test/cases/inner-graph/extend-class/module9.js
  webpack-test/cases/inner-graph/extend-class/test.filter.js
Labels: team, release: bug fix

#5583 feat: deprecate `compiler.rebuild`
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/rebuild_deps_builder.rs
  crates/rspack_core/src/module_graph/mod.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/Watching.ts
  packages/rspack/tests/hotCases/json/.gitkeep
  packages/rspack/tests/hotCases/json/error-in-json/changed-file.js
  packages/rspack/tests/hotCases/json/error-in-json/data.json
  packages/rspack/tests/hotCases/json/error-in-json/errors.js
  packages/rspack/tests/hotCases/json/error-in-json/index.js
  webpack-test/HotTestCases.template.js
  webpack-test/hotCases/json/error-in-json/test.filter.js
Labels: team, release: feature

#5566 chore: align more hotcases
  packages/rspack/tests/hotCases/recover/recover-after-error/a.js
  packages/rspack/tests/hotCases/recover/recover-after-error/changed-file.js
  packages/rspack/tests/hotCases/recover/recover-after-error/index.js
  packages/rspack/tests/hotCases/recover/recover-after-parsing-error/a.js
  packages/rspack/tests/hotCases/recover/recover-after-parsing-error/changed-file.js
  packages/rspack/tests/hotCases/recover/recover-after-parsing-error/errors1.js
  packages/rspack/tests/hotCases/recover/recover-after-parsing-error/index.js
  packages/rspack/tests/hotCases/recover/recover-after-removal-self-accepted/changed-file.js
  packages/rspack/tests/hotCases/recover/recover-after-removal-self-accepted/index.js
  packages/rspack/tests/hotCases/recover/recover-after-removal-self-accepted/inner.js
  packages/rspack/tests/hotCases/recover/recover-after-removal-self-accepted/module.js
  packages/rspack/tests/hotCases/runtime/import-after-download/index.js
  packages/rspack/tests/hotCases/update.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/changed-file.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/compute.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/index.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/test.filter.js
  packages/rspack/tests/hotCases/worker/remove-add-worker/worker.js
  packages/rspack/tests/hotCases/worker/update-in-worker/changed-file.js
  packages/rspack/tests/hotCases/worker/update-in-worker/index.js
  packages/rspack/tests/hotCases/worker/update-in-worker/module.js
  packages/rspack/tests/hotCases/worker/update-in-worker/test.filter.js
  packages/rspack/tests/hotCases/worker/update-in-worker/worker.js
  scripts/test/diff-exclude.cjs
  webpack-test/hotCases/child-compiler/issue-9706/test.filter.js
  webpack-test/hotCases/chunks/update-chunk-loading-runtime/test.filter.js
  webpack-test/hotCases/recover/recover-after-error/test.filter.js
  webpack-test/hotCases/recover/recover-after-loader-error/test.filter.js
  webpack-test/hotCases/recover/recover-after-parsing-error/test.filter.js
  webpack-test/hotCases/recover/recover-after-removal-self-accepted/test.filter.js
  webpack-test/hotCases/recover/recover-after-self-error/test.filter.js
  webpack-test/hotCases/worker/move-between-runtime/test.filter.js
  webpack-test/hotCases/worker/remove-add-worker/test.filter.js
  webpack-test/hotCases/worker/update-in-worker/test.filter.js
Labels: team

#5598 chore: 🤖 add comments when the export name is unused
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
Labels: team

#5599 chore: align the rest of diffing cases
  .github/workflows/reusable-build.yml
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/logging-loader/index.js
  packages/rspack/tests/statsCases/logging-loader/test-loader.js
  packages/rspack/tests/statsCases/logging-loader/webpack.config.js
  packages/rspack/tests/statsCases/simple-export/index.js
  packages/rspack/tests/watchCases/simple/production/0/changing-module.js
  packages/rspack/tests/watchCases/simple/production/0/index.js
  packages/rspack/tests/watchCases/simple/production/1/changing-module.js
  packages/rspack/tests/watchCases/simple/production/2/changing-module.js
  packages/rspack/tests/watchCases/simple/production/webpack.config.js
  scripts/test/diff-exclude.cjs
  webpack-test/statsCases/limit-chunk-count-plugin/test.filter.js
  webpack-test/statsCases/logging/test.filter.js
  webpack-test/statsCases/parse-error/test.filter.js
  webpack-test/statsCases/simple/test.filter.js
  webpack-test/watchCases/simple/multi-compiler/test.filter.js
  webpack-test/watchCases/simple/production/test.filter.js
Labels: team

#5602 chore: run diff on linux only
  .github/workflows/reusable-build.yml
Labels: team

#5586 refactor: on demand apply `hooks.compilation` js hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_macros/src/macros.rs
  crates/rspack_binding_values/src/hooks.rs
  packages/rspack/src/Compiler.ts
Labels: team

#5603 fix: buildinfo cacheable default value should be true
  crates/rspack_core/src/module.rs
Labels: team, release: bug fix

#5591 fix: missing visitor in concatenate modules
  crates/rspack_core/src/utils/concatenated_module_visitor.rs
Labels: team, release: bug fix

#5605 fix: codegen cache should consider runtime
  crates/rspack_core/src/cache/occasion/code_generate.rs
  packages/rspack/tests/configCases/loader-import-module/codegen-cache/app-proxy.js
  packages/rspack/tests/configCases/loader-import-module/codegen-cache/app.js
  packages/rspack/tests/configCases/loader-import-module/codegen-cache/foo.js
  packages/rspack/tests/configCases/loader-import-module/codegen-cache/index.js
  packages/rspack/tests/configCases/loader-import-module/codegen-cache/loader.js
  packages/rspack/tests/configCases/loader-import-module/codegen-cache/webpack.config.js
Labels: team, release: bug fix

#5609 chore: remove wrapped module identifier
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team

#5610 fix: should gracefully shutdown on bail
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack/tests/configCases/errors/bail/a.js
  packages/rspack/tests/configCases/errors/bail/b.js
  packages/rspack/tests/configCases/errors/bail/c.js
  packages/rspack/tests/configCases/errors/bail/d.js
  packages/rspack/tests/configCases/errors/bail/e.js
  packages/rspack/tests/configCases/errors/bail/errors.js
  packages/rspack/tests/configCases/errors/bail/f.js
  packages/rspack/tests/configCases/errors/bail/g.js
  packages/rspack/tests/configCases/errors/bail/index.js
  packages/rspack/tests/configCases/errors/bail/loader.js
  packages/rspack/tests/configCases/errors/bail/webpack.config.js
Labels: team, release: bug fix

#5617 chore: fix yanked handlebars
  Cargo.lock
  crates/swc_plugin_import/Cargo.toml
Labels: team

#5621 fix: should not panic while running build_module hook
  crates/rspack_core/src/compiler/queue.rs
Labels: team, release: bug fix

#5622 fix: fix broken js error stack
  crates/rspack_napi_shared/src/errors.rs
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/diagnostics.test.ts
  packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/index.js
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/logo.svg
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/my-loader.js
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/webpack.config.js
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/index.js
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/lib.js
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/my-loader.js
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/webpack.config.js
  packages/rspack/tests/lib/util/replaceMitteDiagnostic.js
Labels: team, release: bug fix

#5626 chore: support open macos & windows ci in PR
  .github/workflows/ci.yml
Labels: team

#5625 chore: replace splitter on windows !windows !macos
  packages/rspack/tests/diagnostics.test.ts
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/json/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/json/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/json/syntax-error.json
  packages/rspack/tests/diagnostics/module-parse-failed/json/webpack.config.js
  packages/rspack/tests/lib/util/replaceMitteDiagnostic.js
Labels: team

#5633 refactor: merge duplicate implementation of boolean matcher
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/utils/compile_boolean_matcher.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_css/src/runtime/mod.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
Labels: team

#5612 refactor: align module request of CommonJsExportRequireDependency
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
Labels: team

#5476 feat: support resource query in context module
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  packages/rspack/tests/cases/context/resource-query/a.js
  packages/rspack/tests/cases/context/resource-query/abc.js
  packages/rspack/tests/cases/context/resource-query/index.js
Labels: release: feature

#5649 chore: do not update pnpm with renovate bot
  .github/renovate.json
Labels: team

#5646 refactor: refactor remove parent modules
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/mod.rs
  crates/rspack_core/src/build_chunk_graph/remove_parent_modules.rs
  packages/rspack/tests/__snapshots__/configCase.test.ts.snap
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/A.js
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/B-2.js
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/B.js
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/m.css
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/main.js
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/n.css
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/shared.js
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/test.config.js
  packages/rspack/tests/configCases/chunk-index/available-modules-order-index/webpack.config.js
Labels: team

#5660 chore: rename bundler info plugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  packages/rspack/src/builtin-plugin/BundlerInfoRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team

#5661 fix: runtime module hook after tree runtime requirements
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/tests/configCases/hooks/issue-5571/index.css
  packages/rspack/tests/configCases/hooks/issue-5571/index.js
  packages/rspack/tests/configCases/hooks/issue-5571/webpack.config.js
Labels: team, release: bug fix

#5664 chore: migrate husky to v9
  .husky/pre-commit
  package.json
Labels: team

#5662 chore: run prettier
  package.json
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-dev-server/src/middleware.ts
  packages/rspack-plugin-html/src/index.ts
  packages/rspack-plugin-html/src/template.ts
  packages/rspack-plugin-minify/src/index.js
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiStats.ts
  packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/browserslistTargetHandler.js
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/src/node/nodeConsole.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/sharing/ConsumeSharedPlugin.ts
  packages/rspack/src/sharing/SharePlugin.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  packages/rspack/src/util/bindingVersionCheck.ts
  packages/rspack/src/util/cleverMerge.js
  packages/rspack/src/util/createSource.ts
  packages/rspack/src/util/identifier.js
  packages/rspack/src/util/index.ts
  packages/rspack/src/util/smartGrouping.ts
Labels: team

#5665 chore: remove unused scripts/update_swc_version.js
  pnpm-lock.yaml
  scripts/node_modules/@iarna/toml/index.d.ts
  scripts/node_modules/@iarna/toml/lib/create-date.js
  scripts/node_modules/@iarna/toml/lib/create-datetime-float.js
  scripts/node_modules/@iarna/toml/lib/create-datetime.js
  scripts/node_modules/@iarna/toml/lib/create-time.js
  scripts/node_modules/@iarna/toml/lib/format-num.js
  scripts/node_modules/@iarna/toml/lib/parser-debug.js
  scripts/node_modules/@iarna/toml/lib/parser.js
  scripts/node_modules/@iarna/toml/lib/toml-parser.js
  scripts/node_modules/@iarna/toml/package.json
  scripts/node_modules/@iarna/toml/parse-async.js
  scripts/node_modules/@iarna/toml/parse-pretty-error.js
  scripts/node_modules/@iarna/toml/parse-stream.js
  scripts/node_modules/@iarna/toml/parse-string.js
  scripts/node_modules/@iarna/toml/parse.js
  scripts/node_modules/@iarna/toml/stringify.js
  scripts/node_modules/@iarna/toml/toml.js
  scripts/package.json
  scripts/update_swc_version.js
Labels: team

#5636 fix: runtime condition of hot accept dependency
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
  packages/rspack/tests/hotCases/worker/issue-5597/changed-file.js
  packages/rspack/tests/hotCases/worker/issue-5597/chunk.js
  packages/rspack/tests/hotCases/worker/issue-5597/chunkS.js
  packages/rspack/tests/hotCases/worker/issue-5597/index.js
  packages/rspack/tests/hotCases/worker/issue-5597/module.js
  packages/rspack/tests/hotCases/worker/issue-5597/moduleA.js
  packages/rspack/tests/hotCases/worker/issue-5597/moduleAs.js
  packages/rspack/tests/hotCases/worker/issue-5597/moduleB.js
  packages/rspack/tests/hotCases/worker/issue-5597/moduleBs.js
  packages/rspack/tests/hotCases/worker/issue-5597/moduleS.js
  packages/rspack/tests/hotCases/worker/issue-5597/webpack.config.js
  packages/rspack/tests/hotCases/worker/issue-5597/worker.js
  packages/rspack/tests/hotCases/worker/issue-5597/workerA.js
  packages/rspack/tests/hotCases/worker/issue-5597/workerB.js
Labels: release: bug fix

#5667 ci: improve cargo-deny run
  .github/workflows/ci.yml
Labels: team

#5668 ci: upgrade all default node versions to v20
  .github/actions/pnpm-cache/action.yml
  .github/workflows/ci.yml
  .github/workflows/release-nightly.yml
  .github/workflows/reusable-build.yml
Labels: team

#5663 refactor: replace asyncDependenciesBlockId with Identifier
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/chunk_graph/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core_macros/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#5670 feat: eval more identifier and call expr
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_call_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/parsing/rspack-issue-4816/index.js
  packages/rspack/tests/cases/parsing/rspack-issue-4816/resourceFragment/index.js
  packages/rspack/tests/cases/parsing/rspack-issue-4816/resourceFragment/returnRF.js
  packages/rspack/tests/cases/parsing/rspack-issue-4816/resourceQuery/index.js
  packages/rspack/tests/cases/parsing/rspack-issue-4816/resourceQuery/returnRQ.js
Labels: release: feature

#5635 fix: concate modules with css
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/statsCases/css-concat/foo.css
  packages/rspack/tests/statsCases/css-concat/index.js
  packages/rspack/tests/statsCases/css-concat/webpack.config.js
Labels: team, release: bug fix

#5588 refactor: align get_exports of CommonJsExportRequireDependency
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  packages/rspack-test-tools/src/case/diff.ts
  packages/rspack-test-tools/src/compare/comparator.ts
  packages/rspack-test-tools/src/compare/format-code.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/react.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/reexport.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/webpack.config.js
Labels: team

#5674 chore: remove unused dev dependencies
  packages/rspack-cli/package.json
  packages/rspack-dev-server/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#5676 chore: remove unused jest-worker from rspack-plugin-minify
  packages/rspack-plugin-minify/package.json
  pnpm-lock.yaml
Labels: team

#5673 feat: eval more unary expr
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: release: feature

#5678 fix: typo `vesrion` -> `version`
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/parsing/unsupport-require-property/index.js
  packages/rspack/tests/cases/parsing/unsupport-require-property/warnings.js
Labels: release: bug fix

#5616 fix: 5595
  Cargo.lock
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: team, release: bug fix

#5681 chore: change non-using facing dependencies to devDependencies
  benchcases/react-refresh/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: team

#5683 fix: can not resolve warning of cjs export require
  crates/rspack_core/src/tree_shaking/visitor.rs
Labels: team, release: bug fix

#5682 chore: bump oxc-resolver
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team

#5694 fix: hit cache when imports connection not changed
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: bug fix

#5693 fix: eval `typeof aliasRequire` should work
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/parsing/renaming/index.js
Labels: release: bug fix

#5697 fix: panic in harmony_export_imported_specifier_dependency
  webpack-test/configCases/optimization/runtime-specific-used-exports/test.filter.js
  webpack-test/configCases/optimization/runtime-specific-used-exports2/node_modules/root1/index.js
  webpack-test/configCases/optimization/runtime-specific-used-exports2/node_modules/root2/index.js
  webpack-test/configCases/optimization/runtime-specific-used-exports2/webpack.config.js
  webpack-test/configCases/output/inner-dirs-entries/node_modules/dummy_module/index.js
  webpack-test/configCases/output/inner-dirs-entries/test.filter.js
Labels: team, release: bug fix

#5701 feat: rename during walk assign expr
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack/tests/cases/parsing/issue-3346/index.js
  packages/rspack/tests/cases/parsing/issue-3346/locale/a.js
  packages/rspack/tests/cases/parsing/issue-3346/locale/b.js
Labels: release: feature

#5710 feat(dev-server): support custom client ws transport
  packages/rspack-dev-server/package.json
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/fixtures/custom-client/CustomSockJSClient.js
  packages/rspack-dev-server/tests/fixtures/provide-plugin-custom/foo.js
  packages/rspack-dev-server/tests/fixtures/provide-plugin-custom/webpack.config.js
  packages/rspack-dev-server/tests/helpers/html-generator-plugin.js
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack-dev-server/tests/tsconfig.json
  pnpm-lock.yaml
Labels: release: feature

#5700 fix: split-chunks inf loop
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/src/index.js
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/src/lib/a.css
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/src/lib/b.css
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/src/lib/c.css
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/src/lib/mod.js
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/test.config.js
  packages/rspack/tests/configCases/split-chunks/rspack-issue-5657/webpack.config.js
Labels: team, release: bug fix

#5715 chore: speed up webpack-test/configCases/css/urls by using smaller files
  webpack-test/configCases/asset-modules/_images/file.png
  webpack-test/configCases/asset-modules/_images/file_copy.png
  webpack-test/configCases/css/urls/img img.png
  webpack-test/configCases/css/urls/img'''img.png
  webpack-test/configCases/css/urls/img'() img.png
  webpack-test/configCases/css/urls/img'img.png
  webpack-test/configCases/css/urls/img(img.png
  webpack-test/configCases/css/urls/img)img.png
  webpack-test/configCases/css/urls/img.png
  webpack-test/configCases/css/urls/img1x.png
  webpack-test/configCases/css/urls/img2x.png
  webpack-test/configCases/css/urls/img3x.png
  webpack-test/configCases/css/urls/imgimg.png
  webpack-test/configCases/css/urls/imgn.png
  webpack-test/configCases/css/urls/other-img.png
Labels: team

#5692 fix: module_graph update module align with webpack
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team, release: bug fix

#5717 fix: add missing field in EvalSourceMapDevToolPlugin
  packages/rspack/src/builtin-plugin/EvalSourceMapDevToolPlugin.ts
Labels: team, release: bug fix

#5718 fix: disable incRebuild when enable new treeshaking
  crates/rspack_binding_options/src/options/mod.rs
Labels: team, release: bug fix

#5720 feat: eval more binary add op
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
Labels: release: feature

#5719 fix: quote meta slash error
  crates/rspack_core/src/utils/compile_boolean_matcher.rs
Labels: team, release: bug fix

#5712 fix: computed member expression on exports
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/cases/parsing/issue-5638/computed-inner.js
  packages/rspack/tests/cases/parsing/issue-5638/computed-nested.js
  packages/rspack/tests/cases/parsing/issue-5638/computed-require.js
  packages/rspack/tests/cases/parsing/issue-5638/computed.js
  packages/rspack/tests/cases/parsing/issue-5638/index.js
  packages/rspack/tests/cases/parsing/issue-5638/lib.js
Labels: team, release: bug fix

#5726 fix(plugin/swc_js_minimizer): remove parens before optimizing
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/copyPlugin/build/main.js
Labels: release: bug fix

#5740 fix: missing export when using library output under production mode
  packages/rspack/src/rspackOptionsApply.ts
Labels: team, release: bug fix

#5741 fix: loaderCtx.hot should be injected by HMRPlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_hmr/src/lib.rs
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/tests/configCases/loader/hot/index.js
  packages/rspack/tests/configCases/loader/hot/loader.js
  packages/rspack/tests/configCases/loader/hot/webpack.config.js
Labels: team, release: bug fix

#5722 fix: bump `oxc-resolver` to fix windows path
  Cargo.lock
  crates/rspack_core/Cargo.toml
Labels: team, release: bug fix

#5739 refactor: make hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_hook/src/async_parallel.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/copyPlugin/build/main.js
  packages/rspack/tests/copyPlugin/fixtures/watch/_t5/tempfile1.txt
  packages/rspack/tests/copyPlugin/fixtures/watch/_t5/tempfile2.txt
Labels: team

#5749 fix: should not warp `(0,` for non-directly import
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/output.snap
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
Labels: release: bug fix

#5753 fix: should report validation error if no callback exists
  packages/rspack/src/rspack.ts
Labels: team, release: bug fix

#5750 fix: minChunks should be greater than 0
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Compiler.test.ts
Labels: team, release: bug fix

#5754 feat: support `parser.hooks.expression_conditional_operation`
  crates/rspack_plugin_javascript/src/parser_plugin/const/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack/tests/configCases/parsring/eval-null-in-none-mode/a.js
  packages/rspack/tests/configCases/parsring/eval-null-in-none-mode/index.js
  packages/rspack/tests/configCases/parsring/eval-null-in-none-mode/webpack.config.js
Labels: release: feature

#5762 feat: support eval `undefined`
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack/tests/configCases/parsing/eval-null-in-none-mode/a.js
  packages/rspack/tests/configCases/parsing/eval-null-in-none-mode/index.js
  packages/rspack/tests/configCases/parsing/eval-null-in-none-mode/webpack.config.js
  packages/rspack/tests/configCases/parsing/eval-undefined-in-none-mode/a.js
  packages/rspack/tests/configCases/parsing/eval-undefined-in-none-mode/index.js
  packages/rspack/tests/configCases/parsing/eval-undefined-in-none-mode/webpack.config.js
Labels: team, release: feature

#5745 perf(code-splitting): optimize modules intersection
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  packages/rspack/tests/Stats.test.ts
Labels: team, release: performance

#5680 feat: add hint for missing resolve.extensions when resolving module
  crates/rspack_core/src/resolver/mod.rs
  packages/rspack/tests/diagnostics/builtins/recoverable_syntax_error/stats.err
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/a.txt
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/err/index.js
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/index.js
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/stats.err
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/test/index.txt
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/webpack.config.js
Labels: release: feature

#5770 fix: hash exports info should not fall into inf recursive
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/exports_info.rs
Labels: team, release: bug fix

#5773 fix: should visit prop-name in getter/setter
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack/tests/configCases/parsing/getter-import-specifier/a.js
  packages/rspack/tests/configCases/parsing/getter-import-specifier/index.js
  packages/rspack/tests/configCases/parsing/getter-import-specifier/webpack.config.js
Labels: team, release: bug fix

#5768 fix: update chunk files in hmr
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/plugin.rs
  packages/rspack/tests/hotCases/plugins/banner/changed-file.js
  packages/rspack/tests/hotCases/plugins/banner/file.js
  packages/rspack/tests/hotCases/plugins/banner/index.js
  packages/rspack/tests/hotCases/plugins/banner/webpack.config.js
  packages/rspack/tests/hotCases/plugins/html/changed-file.js
  packages/rspack/tests/hotCases/plugins/html/file.js
  packages/rspack/tests/hotCases/plugins/html/index.html
  packages/rspack/tests/hotCases/plugins/html/index.js
  packages/rspack/tests/hotCases/plugins/html/webpack.config.js
Labels: team, release: bug fix

#5778 fix: runtime chunk filename
  crates/rspack_plugin_runtime/src/helpers.rs
  packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/webpack.config.js
Labels: team, release: bug fix

#5779 fix: cjs export require should bailout in old tree shaking
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/package.json
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/reexport.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/value.js
  packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/webpack.config.js
Labels: team, release: bug fix

#5711 fix: CSS module does not emit correctly with concatenateModules
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/raw_to_be_deprecated.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/dependency_category.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_plugin_css/src/dependency/css_module_export.rs
  crates/rspack_plugin_css/src/dependency/mod.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_testing/src/test_config.rs
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/tests/cases/concatenate-modules/with-css/foo.css
  packages/rspack/tests/cases/concatenate-modules/with-css/index.js
  packages/rspack/tests/cases/concatenate-modules/with-css/lib.js
  packages/rspack/tests/cases/concatenate-modules/with-css/package.json
  packages/rspack/tests/cases/concatenate-modules/with-css/webpack.config.js
Labels: team, release: bug fix

#5780 fix: compiler test error in !windows
  packages/rspack/tests/Compiler.test.js
  webpack-test/Compiler.test.js
Labels: release: bug fix

#5784 feat: call parser hooks with tag
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/provide.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
Labels: release: feature

#5789 chore: align stats test
  package.json
  packages/rspack/jest.config.js
  packages/rspack/tests/Stats.test.js
  packages/rspack/tests/__snapshots__/Stats.test.js.snap
  pnpm-lock.yaml
  scripts/test/diff-exclude.cjs
  webpack-test/Compiler.test.js
  webpack-test/Stats.test.js
  webpack-test/jest.config.js
Labels: team

#5787 fix: fix `this` in ctor default param transform into `undefined`
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack/tests/cases/parsing/issue-5786/index.js
Labels: release: bug fix

#5790 feat: polish diagnostic suggestion wordings for module resolution
  crates/rspack_core/src/resolver/mod.rs
  packages/rspack/tests/diagnostics/builtins/recoverable_syntax_error/stats.err
  packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/stats.err
Labels: team, release: feature

#5796 chore: js hash test
  packages/rspack/tests/HashTestCases.test.js
Labels: team

#5798 chore: align MultiStats tests
  packages/rspack/tests/MultiStats.test.ts
  webpack-test/MultiStats.test.js
Labels: team

#5799 chore: align default test runner
  packages/rspack/jest.config.js
  packages/rspack/package.json
  packages/rspack/tests/Defaults.unittest.js
  packages/rspack/tests/__snapshots__/Defaults.unittest.js.snap
  scripts/test/diff-exclude.cjs
  webpack-test/Defaults.unittest.js
  webpack-test/MultiCompiler.test.js
  webpack-test/jest.config.js
Labels: team

#5805 chore: align output test runners
  packages/rspack/tests/Output.test.js
Labels: team

#5793 fix: 🐛 fix 5782
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  packages/rspack/tests/configCases/tree-shaking/issue-5782/index.js
  packages/rspack/tests/configCases/tree-shaking/issue-5782/package/index.js
  packages/rspack/tests/configCases/tree-shaking/issue-5782/webpack.config.js
Labels: team, release: bug fix

#5801 chore: migrate miscellaneous test runners and remove swc-jest
  packages/rspack/jest.config.js
  packages/rspack/package.json
  packages/rspack/tests/BuiltinPlugin.test.js
  packages/rspack/tests/Diagnostics.test.js
  packages/rspack/tests/Errors.test.js
  packages/rspack/tests/Output.test.js
  packages/rspack/tests/RuntimeCases.test.js
  packages/rspack/tests/configCases/hooks/before-resolve/webpack.config.js
  packages/rspack/tests/configCases/loader/loader-syntax-error/errors.js
  packages/rspack/tests/configCases/loader/loader-syntax-error/index.js
  packages/rspack/tests/configCases/loader/loader-syntax-error/lib.js
  packages/rspack/tests/configCases/loader/loader-syntax-error/my-loader.js
  packages/rspack/tests/configCases/loader/loader-syntax-error/webpack.config.js
  packages/rspack/tests/copyPlugin/CopyPlugin.test.js
  packages/rspack/tests/copyPlugin/helpers/compile.js
  packages/rspack/tests/copyPlugin/helpers/getCompiler.js
  packages/rspack/tests/copyPlugin/helpers/index.js
  packages/rspack/tests/copyPlugin/helpers/readAsset.js
  packages/rspack/tests/copyPlugin/helpers/readAssets.js
  packages/rspack/tests/copyPlugin/helpers/run.js
  packages/rspack/tests/diagnostics/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/module-build-failed/loader-throw-error/stats.err
  packages/rspack/tests/tsconfig.json
  packages/rspack/tests/utils.js
  packages/rspack/tests/utils.ts
  pnpm-lock.yaml
Labels: team

#5709 perf: add cache for source map
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_devtool/src/mapped_assets_cache.rs
Labels: release: feature

#5809 fix: skip release rspack-test-tools and webpack-cli-test
  packages/rspack-test-tools/package.json
  webpack-cli-test/package.json
Labels: team, release: bug fix

#5810 fix: release @rspack/test-tools
  packages/rspack-test-tools/package.json
Labels: team, release: bug fix

#5812 fix: disable hooks should respect interceptor
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/configCases/hooks/interceptor/index.js
  packages/rspack/tests/configCases/hooks/interceptor/webpack.config.js
Labels: team, release: bug fix

#5807 refactor(code-splitting): using raw dependencies order
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
Labels: team

#5813 fix(parser): should walk parameters in class methods
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack/tests/configCases/parsing/class-method-parameters/foo.js
  packages/rspack/tests/configCases/parsing/class-method-parameters/index.js
  packages/rspack/tests/configCases/parsing/class-method-parameters/webpack.config.js
Labels: team, release: bug fix

#5814 refactor: move runtimeCases to configCases
  packages/rspack/tests/RuntimeCases.test.js
  packages/rspack/tests/configCases/runtime/dynamic-chunk-with-hash/dynamic.js
  packages/rspack/tests/configCases/runtime/dynamic-chunk-with-hash/index.js
  packages/rspack/tests/configCases/runtime/dynamic-chunk-with-hash/webpack.config.js
  packages/rspack/tests/configCases/runtime/dynamic-chunk/dynamic.js
  packages/rspack/tests/configCases/runtime/dynamic-chunk/index.js
  packages/rspack/tests/configCases/runtime/dynamic-chunk/webpack.config.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-content-hash/dynamic.css
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-content-hash/dynamic.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-content-hash/index.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-content-hash/webpack.config.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-hash/common.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-hash/dynamic.css
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-hash/dynamic.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-hash/index.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-hash/webpack.config.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk/common.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk/dynamic.css
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk/dynamic.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk/index.js
  packages/rspack/tests/configCases/runtime/dynamic-css-chunk/webpack.config.js
  packages/rspack/tests/configCases/runtime/entry-runtime/index.js
  packages/rspack/tests/configCases/runtime/entry-runtime/test.config.js
  packages/rspack/tests/configCases/runtime/entry-runtime/webpack.config.js
  packages/rspack/tests/configCases/runtime/issue-4019/dynamic.js
  packages/rspack/tests/configCases/runtime/issue-4019/index.js
  packages/rspack/tests/configCases/runtime/issue-4019/index2.js
  packages/rspack/tests/configCases/runtime/issue-4019/shared.js
  packages/rspack/tests/configCases/runtime/issue-4019/test.config.js
  packages/rspack/tests/configCases/runtime/issue-4019/webpack.config.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/common.css
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/common.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/index1.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/index2.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/index3.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/share.css
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/share.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/test.config.js
  packages/rspack/tests/configCases/runtime/split-css-chunk-async/webpack.config.js
  packages/rspack/tests/configCases/runtime/split-css-chunk/common.css
  packages/rspack/tests/configCases/runtime/split-css-chunk/common.js
  packages/rspack/tests/configCases/runtime/split-css-chunk/index1.js
  packages/rspack/tests/configCases/runtime/split-css-chunk/index2.js
  packages/rspack/tests/configCases/runtime/split-css-chunk/test.config.js
  packages/rspack/tests/configCases/runtime/split-css-chunk/webpack.config.js
  packages/rspack/tests/configCases/runtime/split-dynamic-import-common-chunk/a.js
  packages/rspack/tests/configCases/runtime/split-dynamic-import-common-chunk/b.js
  packages/rspack/tests/configCases/runtime/split-dynamic-import-common-chunk/common.js
  packages/rspack/tests/configCases/runtime/split-dynamic-import-common-chunk/index.js
  packages/rspack/tests/configCases/runtime/split-dynamic-import-common-chunk/webpack.config.js
  packages/rspack/tests/runtimeCases/runtime/split-dynamic-import-common-chunk/index.js
Labels: team

#5815 chore: align jest config
  packages/rspack/jest.config.js
  packages/rspack/tests/Compiler.test.js
  packages/rspack/tests/Stats.test.js
  packages/rspack/tests/__snapshots__/ConfigTestCases.basictest.js.snap
  packages/rspack/tests/__snapshots__/Defaults.unittest.js.snap
  packages/rspack/tests/__snapshots__/Stats.test.js.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
  packages/rspack/tests/copyPlugin/__snapshots__/CopyPlugin.test.js.snap
Labels: team

#5816 fix: should not contain duplicate initFragments for namespace_cache
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  packages/rspack/tests/configCases/runtime/namespace-cache/index.mjs
  packages/rspack/tests/configCases/runtime/namespace-cache/proxy.js
  packages/rspack/tests/configCases/runtime/namespace-cache/utils.js
  packages/rspack/tests/configCases/runtime/namespace-cache/webpack.config.js
Labels: team, release: bug fix

#5823 chore: remove source-map-support
  packages/rspack-cli/bin/rspack
  packages/rspack-cli/package.json
  pnpm-lock.yaml
Labels: team

#5746 fix: add context module afterResolve hook
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ContextModuleFactory.ts
  packages/rspack/tests/configCases/hooks/context-module-after-resolve/dir/foo.js
  packages/rspack/tests/configCases/hooks/context-module-after-resolve/index.js
  packages/rspack/tests/configCases/hooks/context-module-after-resolve/webpack.config.js
Labels: team, release: bug fix
