Repository web-infra-dev/rspack, pull requests merged in 2024-01, with the labels that each got.

#5154 fix: empty name and complex member expression in cjs dependency
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/assign-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/assign-module-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/assign-this.js
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/self-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/self-module-exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/complex-member/self-this.js
Labels: team, release: bug fix

#5167 feat: support module.require
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  webpack-test/cases/parsing/issue-7728/test.filter.js
Labels: team, release: feature

#5170 chore: comment benchmark result for commit
  .github/workflows/bench-main.yaml
  .github/workflows/bench-rust.yaml
  .github/workflows/ci.yml
Labels: team

#5172 feat: support `webpackIgnore` comment
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  pnpm-lock.yaml
  webpack-test/configCases/parsing/import-ignore/test.filter.js
Labels: release: feature

#5171 fix: missing module in block
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  packages/rspack/tests/configCases/errors/dynamic-import-non-exist-module/index.js
  packages/rspack/tests/configCases/errors/dynamic-import-non-exist-module/webpack.config.js
Labels: team, release: bug fix

#5174 chore: build rspack/core first
  package.json
Labels: team

#5175 fix(mf1.5): container name in runtime
  packages/rspack/package.json
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/default.runtime.js
  packages/rspack/tests/configCases/container/2-container-full/index.js
  pnpm-lock.yaml
  webpack-test/scripts/test-metric-util.js
Labels: team, release: bug fix

#5163 fix: do not generate dependency after removing
  crates/rspack_plugin_javascript/src/utils/const/if_stmt.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_array_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_cond_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_new_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_top_level_this.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  packages/rspack/tests/cases/parsing/remove-dependency/index.js
Labels: team, release: bug fix

#5181 feat: support eval nullish in const plugin
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
  pnpm-lock.yaml
Labels: release: feature

#5161 feat: support evaluate_typeof of module variables
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm4.js
  packages/rspack/tests/cases/parsing/typeof-api/index.js
  packages/rspack/tests/cases/parsing/typeof-api/typeof.js
Labels: team, release: feature

#5162 feat: support logical evaluation
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  packages/rspack/tests/cases/parsing/evaluate-logical/index.js
Labels: team, release: feature

#5186 feat: skip transitiveonly dependencies and enable more test
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  webpack-test/configCases/chunk-graph/issue-9634/test.filter.js
Labels: team, release: feature

#5089 refactor(rspack_core): remove nodejs_resolver and `experiments.rspackFuture.newResolver`
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_experiments.rs
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/experiments.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/factory.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/resolve/tsconfig-project-references-auto/webpack.config.js
  packages/rspack/tests/configCases/resolve/tsconfig-project-references-manual/webpack.config.js
Labels: need documentation

#5190 test: jest serializer path should be working with non-ascii code
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack/jest.config.js
  scripts/test/slash.cjs
Labels: team

#5065 feat: normalModule loader hook
  crates/rspack_core/src/loader/mod.rs
  crates/rspack_core/src/loader/process_resource.rs
  crates/rspack_core/src/loader/rspack_loader.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_loader_runner/src/plugin.rs
  crates/rspack_loader_runner/src/runner.rs
Labels: team, release: feature

#5191 feat: support eval null
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5192 test: remove manual path normalizations in snapshots
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/StatsTestCases.test.ts
Labels: team

#5176 chore: remove useless benchmark crate
  .github/CODEOWNERS
  .github/workflows/bench-merge-queue.yml
  Cargo.lock
  crates/bench/Cargo.toml
  crates/bench/LICENSE
  crates/bench/README.md
  crates/bench/src/main.rs
  crates/bench/src/termcolorful.rs
Labels: team

#5193 refactor: replace devServer.hot by HotModuleReplacementPlugin
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_dev_server.rs
  crates/rspack_core/src/loader/mod.rs
  crates/rspack_core/src/loader/process_resource.rs
  crates/rspack_core/src/loader/rspack_loader.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_loader_runner/src/plugin.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_hmr/src/lib.rs
  packages/rspack-dev-server/src/server.ts
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/NormalModule.ts
  packages/rspack/src/Watching.ts
  packages/rspack/src/builtin-plugin/HotModuleReplacementPlugin.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/lib/LoaderOptionsPlugin.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/runtimeDiffCases/runtime-get-main-filename/rspack.config.js
  packages/rspack/tests/runtimeDiffCases/runtime-hot-module-replacement/rspack.config.js
  packages/rspack/tests/statsCases/hot+production/webpack.config.js
Labels: team

#5203 fix: replace null if has not side effect
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: bug fix

#5179 refactor: enable disableApplyEntryLazily by default
  packages/rspack/src/config/defaults.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/container/2-container-full/webpack.config.js
  packages/rspack/tests/configCases/container/module-federation-with-shareScope/webpack.config.js
  webpack-test/ConfigTestCases.template.js
Labels: team

#5177 refactor: remove builtin:sass-loader for 0.5
  .github/CODEOWNERS
  Cargo.lock
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_module/mod.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/fixtures__char-based-offset-error-span.snap
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/index.js
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/index.scss
  crates/rspack_error/tests/fixtures/char-based-offset-error-span/test.config.json
  crates/rspack_error/tests/fixtures/sass-warnings/fixtures__sass-warnings.snap
  crates/rspack_error/tests/fixtures/sass-warnings/index.js
  crates/rspack_error/tests/fixtures/sass-warnings/index.scss
  crates/rspack_error/tests/fixtures/sass-warnings/test.config.json
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_loader_sass/Cargo.toml
  crates/rspack_loader_sass/LICENSE
  crates/rspack_loader_sass/src/lib.rs
  crates/rspack_loader_sass/tests/expected/rspack_importer.css
  crates/rspack_loader_sass/tests/fixtures.rs
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/expected/main.css
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/index.js
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/snapshot/output.snap
  crates/rspack_loader_sass/tests/fixtures/rspack_importer/test.config.json
  crates/rspack_loader_sass/tests/scss/another/_variables.scss
  crates/rspack_loader_sass/tests/scss/file.css
  crates/rspack_loader_sass/tests/scss/language.scss
  crates/rspack_testing/Cargo.toml
  crates/rspack_testing/src/loader.rs
  package.json
  packages/rspack/src/config/adapterRuleUse.ts
  pnpm-lock.yaml
Labels: team, need documentation

#5184 feat: remove extended resolve extensions
  crates/rspack_testing/src/eval_raw.rs
  diffcases/arco-pro/rspack.config.js
  examples/arco-pro/rspack.config.js
  examples/basic-ts/rspack.config.js
  examples/builtin-swc-loader/rspack.config.js
  examples/cra-ts/rspack.config.js
  examples/cra/rspack.config.js
  examples/emotion/rspack.config.js
  examples/express/rspack.config.js
  examples/loader-compat/rspack.config.js
  examples/nestjs/rspack.config.js
  examples/react-15-classic/rspack.config.js
  examples/react-15/rspack.config.js
  examples/react-refresh-babel-loader/rspack.config.js
  examples/react-refresh/rspack.config.js
  examples/react-storybook/rspack.config.js
  examples/react-with-less/rspack.config.js
  examples/react-with-sass/rspack.config.js
  examples/react/rspack.config.js
  examples/solid/rspack.config.js
  examples/styled-components/rspack.config.js
  examples/svgr/rspack.config.js
  examples/vue2-ts/rspack.config.js
  examples/vue2-tsx/rspack.config.js
  examples/vue3-jsx/rspack.config.js
  examples/vue3-tsx/rspack.config.js
  examples/vue3-vanilla/rspack.config.js
  packages/playground/cases/react/basic/rspack.config.js
  packages/playground/cases/react/class-component/rspack.config.js
  packages/playground/cases/react/tailwindcss/rspack.config.js
  packages/playground/cases/react/with-babel/rspack.config.js
  packages/playground/cases/react/worker/rspack.config.js
  packages/playground/cases/vue3/rspack.config.js
  packages/rspack/package.json
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/exports.ts
  packages/rspack/tests/ConfigCase.template.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/builtin-swc-loader/basic/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/chain/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/inline-pitching/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/react-refresh-false/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-automic/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-classic/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/relay-config-custom/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/relay-config-js/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/relay-config-json/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/relay-default/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/relay-json/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/relay-webpack-require/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/source-map/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/webpack.config.js
  packages/rspack/tests/configCases/errors/rule-type-fatal-error/webpack.config.js
  packages/rspack/tests/configCases/source-map/source-map/webpack.config.js
  packages/rspack/tests/statsCases/parse-error-builtin-swc-loader/webpack.config.js
  pnpm-lock.yaml
Labels: team, need documentation, release: feature

#5208 chore: remove deprecated splitChunksPlugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_split_chunks/LICENSE
  crates/rspack_plugin_split_chunks/src/cache_group.rs
  crates/rspack_plugin_split_chunks/src/cache_group_source.rs
  crates/rspack_plugin_split_chunks/src/chunks_info_item.rs
  crates/rspack_plugin_split_chunks/src/lib.rs
  crates/rspack_plugin_split_chunks/src/max_size_queue_item.rs
  crates/rspack_plugin_split_chunks/src/options/cache_group_options.rs
  crates/rspack_plugin_split_chunks/src/options/mod.rs
  crates/rspack_plugin_split_chunks/src/options/split_chunks_options.rs
  crates/rspack_plugin_split_chunks/src/plugin.rs
  crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs
  crates/rspack_plugin_split_chunks/src/utils.rs
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: team

#5209 feat: add require.main
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  webpack-test/configCases/parsing/require.main/test.filter.js
  webpack-test/configCases/split-chunks-common/correct-order/test.filter.js
  webpack-test/configCases/split-chunks-common/inverted-order/test.filter.js
Labels: team, release: feature

#5180 feat: add common_js_full_require_dependency
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/output.snap
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/self_module_factory.rs
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/cjs-tree-shaking/full-require/exports.js
  packages/rspack/tests/cases/cjs-tree-shaking/full-require/index.js
Labels: team, release: feature

#5198 chore: nightly release failed alert to all platform
  .github/workflows/release-nightly.yml
  scripts/alert/discord.js
  scripts/alert/lark.js
Labels: team

#5212 fix: remove module/exports evaluation
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/typeof-api/index.js
  packages/rspack/tests/cases/parsing/typeof-api/typeof.js
Labels: team, release: bug fix

#5215 ci: fix flaky e2e tests
  packages/playground/cases/context/delete-file/index.test.ts
  packages/playground/cases/css/chunk-loading-order/index.test.ts
  packages/playground/cases/css/css-filename/index.test.ts
  packages/playground/cases/css/render-to-body/index.test.ts
  packages/playground/cases/hooks/asset-emitted/index.test.ts
  packages/playground/cases/html/issue-4366/index.test.ts
  packages/playground/cases/react/basic-disableTransformByDefault/index.test.ts
  packages/playground/cases/react/basic/index.test.ts
  packages/playground/cases/react/class-component-disableTransformByDefault/index.test.ts
  packages/playground/cases/react/class-component/index.test.ts
  packages/playground/cases/react/tailwindcss-disableTransformByDefault/index.test.ts
  packages/playground/cases/react/tailwindcss/index.test.ts
  packages/playground/cases/react/with-babel/index.test.ts
  packages/playground/cases/vue3/index.test.ts
  packages/playground/fixtures/rspack.ts
  packages/playground/playwright.config.ts
Labels: team

#5210 fix: failed to import string json
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_json/tests/fixtures/simple/index.js
  crates/rspack_plugin_json/tests/fixtures/simple/snapshot/output.snap
  crates/rspack_plugin_json/tests/fixtures/simple/string.json
Labels: team, release: bug fix

#5204 refactor: move build_info and build_meta to module
  crates/rspack_core/src/cache/occasion/build_module.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph_module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
Labels: team

#5217 feat: support eval null
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
Labels: release: feature

#5226 fix: use exports_type in module instead of mgm
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
Labels: team, release: bug fix

#5225 feat: remove experiments.incrementalRebuild option
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/mod.rs
  crates/rspack_binding_options/src/options/raw_experiments.rs
  packages/playground/cases/hooks/asset-emitted/rspack.config.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/HotTestCases.template.ts
  packages/rspack/tests/HotTestCasesNode.test.ts
  packages/rspack/tests/HotTestCasesNodeWithIncRebuild.test.ts
  packages/rspack/tests/HotTestCasesWeb.test.ts
  packages/rspack/tests/HotTestCasesWebWithIncRebuild.test.ts
  packages/rspack/tests/HotTestCasesWebWorker.test.ts
  packages/rspack/tests/HotTestCasesWebWorkerWithIncRebuild.test.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: feature

#5230 feat(stats): support orphan field
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/stats.rs
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: feature

#5229 feat: more case for eval strict equality
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  packages/rspack/tests/cases/parsing/issue-4816/index.js
Labels: release: feature

#5228 refactor: move swc helpers and react-refresh to peer
  diffcases/arco-pro/package.json
  examples/arco-pro/package.json
  examples/builtin-swc-loader/package.json
  examples/cra-ts/package.json
  examples/cra/package.json
  examples/module-federation-v1.5/app/package.json
  examples/module-federation-v1.5/lib1/package.json
  examples/module-federation-v1.5/lib2/package.json
  examples/module-federation-v1/app/package.json
  examples/module-federation-v1/lib1/package.json
  examples/module-federation-v1/lib2/package.json
  examples/react-15/package.json
  examples/react-storybook/package.json
  examples/react-with-less/package.json
  examples/react-with-sass/package.json
  examples/react/package.json
  examples/styled-components/package.json
  examples/svgr/package.json
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/playground/package.json
  packages/rspack/package.json
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/web/ResolveSwcPlugin.ts
  pnpm-lock.yaml
Labels: team, need documentation

#5216 perf: `HarmonyExportImportedSpecifierDependency::get_mode` and `get_exports|export_info_by_id`
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/module_graph/vec_map.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
Labels: team, release: performance

#5231 chore: remove builder path of diff plugins
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts
  packages/rspack-test-tools/src/processor/diff.ts
  pnpm-lock.yaml
Labels: team

#5233 ci: fix flaky e2e tests
  packages/playground/fixtures/pathInfo.ts
  packages/playground/fixtures/rspack.ts
  packages/playground/playwright.config.ts
Labels: team

#5234 fix: scan self module
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: bug fix

#5238 chore: nightly release failed
  .github/workflows/release-nightly.yml
Labels: team

#5239 fix(mf1.5): add resolve alias for mf runtime
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/default.runtime.js
Labels: team, release: bug fix

#5236 feat: unsupport require property
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/parsing/unsupport-require-property/index.js
  packages/rspack/tests/cases/parsing/unsupport-require-property/warnings.js
Labels: team, release: feature

#5202 fix: some js hooks are always enabled
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  packages/rspack/src/Compiler.ts
Labels: team, release: bug fix

#5240 ci: only linux test all nodejs version
  .github/workflows/reusable-build.yml
Labels: team

#5241 refactor: change return type of `render_manifest` to `TWithDiagnosticArray`
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
Labels: team

#5242 feat: eval `+` op for binary expr
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/parser_plugin/webpack_included_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_swc_visitors/src/define.rs
  packages/rspack-cli/tests/build/basic/public/main.js
  packages/rspack/tests/cases/parsing/typeof-api/index.js
  pnpm-lock.yaml
  webpack-test/cases/parsing/webpack-is-included/test.filter.js
Labels: release: feature

#5244 fix: remove useless tracing span
  crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
Labels: team, release: bug fix

#5243 fix(runtime): align GetChunkFilenameRuntimeModule name
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team, release: bug fix

#5246 fix: should not remove unsupport require declaration when local variable
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/parsing/unsupport-require-property/index.js
Labels: team, release: bug fix

#5247 feat: add remoteInitOptions as initContainer params
  packages/rspack/src/container/default.runtime.js
Labels: team, release: feature

#5262 fix: full require in try catch should be optional
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  packages/rspack/tests/cases/cjs-tree-shaking/full-require/index.js
  packages/rspack/tests/cases/cjs-tree-shaking/full-require/warnings.js
Labels: team, release: bug fix

#5253 fix: address expect-error in react-refresh and script
  packages/rspack-plugin-react-refresh/src/index.ts
  packages/rspack-plugin-react-refresh/src/options.ts
  scripts/meta/check_is_workspace_root.js
Labels: release: bug fix

#5257 fix: replace undefined with void in hooks
  packages/rspack/src/Compilation.ts
Labels: release: bug fix

#5261 chore: fix template version
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_testing/src/test_config.rs
  examples/tailwind/l.js
  packages/create-rspack/index.js
  packages/create-rspack/template-react-ts/rspack.config.js
  packages/create-rspack/template-react/rspack.config.js
  packages/create-rspack/template-vue/rspack.config.js
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: team

#5260 fix: not enable rspack-plugin-react-refresh when mode set to 'product…
  packages/rspack-dev-server/tests/normalizeOptions.test.ts
  packages/rspack-plugin-react-refresh/src/index.ts
  packages/rspack-plugin-react-refresh/src/options.ts
Labels: team, release: bug fix

#5245 chore: bump oxc_resolver
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack/tests/StatsTestCases.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#5053 fix: new tree shaking with hmr
  crates/rspack_core/src/compiler/compilation.rs
Labels: team, release: bug fix

#5276 feat: support `compilation.hooks.afterProcessAssets`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/hook.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/hooks.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/configCases/hooks/after-process-assets/index.js
  packages/rspack/tests/configCases/hooks/after-process-assets/webpack.config.js
Labels: release: feature

#5152 fix: missing dependencies should be recoverable
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/playground/cases/file/context-delete-file/index.test.ts
  packages/playground/cases/file/context-delete-file/rspack.config.js
  packages/playground/cases/file/context-delete-file/src/index.html
  packages/playground/cases/file/context-delete-file/src/index.js
  packages/playground/cases/file/context-delete-file/src/mod1.js
  packages/playground/cases/file/context-delete-file/src/mod2.js
  packages/playground/cases/file/missing-files/index.test.ts
  packages/playground/cases/file/missing-files/rspack.config.js
  packages/playground/cases/file/missing-files/src/index.html
  packages/playground/cases/file/missing-files/src/index.js
  packages/rspack/tests/MultiCompiler.test.ts
  packages/rspack/tests/StatsTestCases.test.ts
Labels: team, release: bug fix

#5279 fix: `succeedModule` should not panic
  crates/rspack_binding_values/src/module.rs
Labels: team, release: bug fix

#5248 chore: modify diff plugin options
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/rspack.config.js
  packages/rspack-test-tools/src/case/diff.ts
  packages/rspack-test-tools/src/compare/comparator.ts
  packages/rspack-test-tools/src/compare/compare.ts
  packages/rspack-test-tools/src/helper/parse-modules.ts
  packages/rspack-test-tools/src/index.ts
  packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts
  packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts
  packages/rspack-test-tools/src/processor/diff.ts
  packages/rspack-test-tools/template/diff.bundle.js
  packages/rspack-test-tools/template/editor.worker.js
  pnpm-lock.yaml
Labels: team

#5278 test: add cjs module interop diff case
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/assign-exports-property.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/assign-module-exports-property.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/assign-this-property.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/attach-to-arrow-function.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/attach-to-function.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/attach-to-object.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/define-exports-property.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/define-module-exports-property.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/define-this-property.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/exports-default-bailout-flagged.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/exports-default-bailout.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/exports-default-flagged.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/exports-default.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/module-exports-default.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/reading-self-from-exports.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/reading-self-from-module-exports.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/reading-self-from-this.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/cjs/require-default.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-cjs/test.config.js
Labels: team

#5275 chore: fixed mf 1.5 runtime version
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#5284 perf: rm unnecessary collection
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
Labels: release: performance

#5289 fix: should not generate css runtime if not enable experiments.css
  Cargo.lock
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/runtime/css_loading.js
  crates/rspack_plugin_css/src/runtime/css_loading_with_hmr.js
  crates/rspack_plugin_css/src/runtime/css_loading_with_loading.js
  crates/rspack_plugin_css/src/runtime/mod.rs
  crates/rspack_plugin_runtime/src/css_modules.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_testing/src/test_config.rs
Labels: team, release: bug fix

#5299 chore(diff): fix diff detail output
  packages/rspack-test-tools/src/case/diff.ts
Labels: team

#5297 chore: add link to rspack-contrib/rspack-examples in README
  README.md
  README.zh-CN.md
Labels: team

#5301 fix: module graph incorrect when delete or create file
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/hmr.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/rebuild_deps_builder.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_entry/src/lib.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/playground/cases/css/chunk-loading-order/rspack.config.js
  packages/playground/cases/css/css-filename/rspack.config.js
  packages/playground/cases/css/import-double-css-files-with-empty/rspack.config.js
  packages/playground/cases/css/import-empty-css-file/rspack.config.js
  packages/playground/cases/css/render-to-body/rspack.config.js
  packages/playground/cases/file/context-delete-file/rspack.config.js
  packages/playground/cases/file/missing-files/index.test.ts
  packages/playground/cases/file/missing-files/rspack.config.js
  packages/playground/cases/react/basic/rspack.config.js
  packages/playground/cases/react/class-component/rspack.config.js
  packages/playground/cases/react/with-babel/rspack.config.js
  packages/playground/cases/react/worker/rspack.config.js
  packages/playground/cases/vue3/rspack.config.js
Labels: team, release: bug fix

#5303 chore: turn off `--bail` `--forceExit` `--logHeapUsage` from webpack test
  webpack-test/jest.config.js
  webpack-test/package.json
Labels: team

#5304 refactor: use pnpm v8 default flags
  .npmrc
  pnpm-lock.yaml
Labels: team

#5305 chore: upgrade Rust to v1.75.0 (nightly)
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_testing/src/test_config.rs
  rust-toolchain.toml
Labels: team

#5223 feat: deprecate resolve.browserField and enable resolve.{preferAbsolute,restrictions,roots,aliasFields}
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_resolve.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  webpack-test/TestCases.template.js
Labels: team, need documentation, release: feature

#5178 feat: resolve with hint
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/diagnostics.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/plugin/args.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_error/src/diagnostic.rs
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/tests/Errors.test.ts
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/cannot-resolve-with-loader/stats.err
  packages/rspack/tests/diagnostics/factorize/cannot-resolve/stats.err
  packages/rspack/tests/diagnostics/factorize/css-module-request-prefix/stats.err
  packages/rspack/tests/diagnostics/factorize/dynamic-import-non-exist-module/stats.err
  packages/rspack/tests/diagnostics/factorize/empty-dependency/stats.err
  packages/rspack/tests/diagnostics/factorize/experiments-disable-transform-parse-error/stats.err
  packages/rspack/tests/diagnostics/factorize/fully-specified-resolve-suggestions/foo.js
  packages/rspack/tests/diagnostics/factorize/fully-specified-resolve-suggestions/index.js
  packages/rspack/tests/diagnostics/factorize/fully-specified-resolve-suggestions/stats.err
  packages/rspack/tests/diagnostics/factorize/fully-specified-resolve-suggestions/webpack.config.js
  packages/rspack/tests/diagnostics/factorize/json-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
  packages/rspack/tests/diagnostics/factorize/mismatched-module-type/stats.err
  packages/rspack/tests/diagnostics/factorize/missing-config-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/missing-module/stats.err
  packages/rspack/tests/diagnostics/factorize/module-parse-error/stats.err
  packages/rspack/tests/diagnostics/factorize/prefer-relative-resolve-suggestions/foo.js
  packages/rspack/tests/diagnostics/factorize/prefer-relative-resolve-suggestions/index.js
  packages/rspack/tests/diagnostics/factorize/prefer-relative-resolve-suggestions/stats.err
  packages/rspack/tests/diagnostics/factorize/prefer-relative-resolve-suggestions/webpack.config.js
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/basic/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/jsx_syntax_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/lack-equal/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/multi_json_syntax_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/multiple_file_syntax_error/stats.err
Labels: team, release: feature

#5307 fix: fix cli command alias bug
  packages/rspack-cli/src/utils/options.ts
Labels: release: bug fix

#5309 perf: lazily init help message
  crates/rspack_core/src/diagnostics.rs
Labels: release: performance

#5312 chore: remove unused Rust dependencies
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/rspack_ast/Cargo.toml
  crates/rspack_binding_options/Cargo.toml
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_externals/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_limit_chunk_count/Cargo.toml
  crates/rspack_plugin_merge_duplicate_chunks/Cargo.toml
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_split_chunks_new/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_warn_sensitive_module/Cargo.toml
  crates/rspack_plugin_web_worker_template/Cargo.toml
  crates/rspack_plugin_worker/Cargo.toml
  crates/rspack_testing/Cargo.toml
Labels: team

#5280 feat: introduce `JavascriptParser`
  crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/utils/const/mod.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/clear_mark.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  crates/rspack_plugin_javascript/src/visitors/mod.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
  pnpm-lock.yaml
Labels: release: feature

#5286 feat: support module build error
  Cargo.lock
  crates/rspack_core/src/diagnostics.rs
  crates/rspack_core/src/loader/rspack_loader.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_error/src/error.rs
  crates/rspack_error/src/ext.rs
  crates/rspack_error/src/lib.rs
  crates/rspack_error/src/miette_helpers.rs
  crates/rspack_loader_runner/src/plugin.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_napi_shared/src/errors.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/configCases/loader/loader-error-async/errors.js
  packages/rspack/tests/configCases/loader/loader-syntax-error/errors.js
  packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
Labels: team, release: feature

#5325 test: replace error stack in test
  packages/rspack/tests/diagnostics.test.ts
  packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
Labels: team

#5323 chore: nightly release alert when failed
  .github/workflows/release-nightly.yml
Labels: team

#5327 chore: bump oxlint to v0.2.0
  .eslintignore
  .eslintrc.json
  lint-staged.config.mjs
  package.json
  packages/rspack/src/config/browserslistTargetHandler.js
  pnpm-lock.yaml
Labels: team

#5326 fix: should not assume module directories always exist
  crates/rspack_core/src/resolver/mod.rs
Labels: team, release: bug fix

#5330 fix: unregistered case handler should not panic
  crates/swc_plugin_import/src/lib.rs
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/errors.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/index.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/lib-entry.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/lib.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/webpack.config.js
  packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/custom-name-tpl-nopanic/fooBar/index.js
Labels: team, release: bug fix

#5319 fix(parser): reserved binding name in strict mode
  .prettierignore
  crates/rspack_plugin_javascript/src/ast/parse.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/cases/parsing/issue-5120-binding/errors.js
  packages/rspack/tests/cases/parsing/issue-5120-binding/fail.js
  packages/rspack/tests/cases/parsing/issue-5120-binding/index.js
  packages/rspack/tests/cases/parsing/issue-5120-binding/webpack.config.js
  packages/rspack/tests/cases/parsing/issue-5120-strict-block/errors.js
  packages/rspack/tests/cases/parsing/issue-5120-strict-block/fail.js
  packages/rspack/tests/cases/parsing/issue-5120-strict-block/index.js
  packages/rspack/tests/cases/parsing/issue-5120-strict-block/webpack.config.js
  packages/rspack/tests/cases/parsing/issue-5120-strict/errors.js
  packages/rspack/tests/cases/parsing/issue-5120-strict/fail.js
  packages/rspack/tests/cases/parsing/issue-5120-strict/index.js
  packages/rspack/tests/cases/parsing/issue-5120-strict/webpack.config.js
  packages/rspack/tests/cases/parsing/issue-5120-var/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/lexically_name_error/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/lexically_name_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/reserved_name_error/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/reserved_name_error/stats.err
Labels: team, release: bug fix

#5310 feat(runtime): add rspack version
  crates/node_binding/binding.d.ts
  crates/rspack_binding_options/src/options/raw_builtins/mod.rs
  crates/rspack_binding_options/src/options/raw_builtins/raw_bundle_info.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_runtime/src/bundler_info.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/rspack_version.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_version.js
  packages/rspack/src/builtin-plugin/BundlerInfoPlugin.ts
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
  packages/rspack/tests/configCases/version/all/index.js
  packages/rspack/tests/configCases/version/all/webpack.config.js
  packages/rspack/tests/configCases/version/array/index.js
  packages/rspack/tests/configCases/version/array/webpack.config.js
  packages/rspack/tests/configCases/version/auto/index.js
  packages/rspack/tests/configCases/version/auto/webpack.config.js
Labels: team, need documentation, release: feature

#5341 refactor: traceable magic comments warnings
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/a.js
  packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/stats.err
Labels: team

#5308 chore: bump swc
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/Stats.test.ts.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Labels: team

#5346 fix: stable version snapshot
  packages/rspack/tests/Defaults.unittest.ts
  packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
Labels: team, release: bug fix

#5272 feat(cli): support built-in rspack envs
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
  packages/rspack-cli/tests/build/basic/entry.env.js
Labels: release: feature

#5345 chore: remove a console.log from rspack tests that fills the screen
  packages/rspack/tests/configCases/split-chunks/chunks-function/webpack.config.js
Labels: team

#5344 refactor: traceable harmony scanner errors
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  packages/rspack/tests/diagnostics/module-parse-failed/import_meta_warning/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/import_meta_warning/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/webpack.config.js
  packages/rspack/tests/diagnostics/module-parse-failed/tla_esm_error/index.js
  packages/rspack/tests/diagnostics/module-parse-failed/tla_esm_error/stats.err
Labels: team

#5350 chore: remove sinon from webpack-test
  pnpm-lock.yaml
  webpack-test/package.json
Labels: team

#5335 refactor: remove load chunk with block runtime
  crates/rspack/tests/fixtures/code-splitting/snapshot/output.snap
  crates/rspack/tests/fixtures/dynamic-import/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/cycle-dynamic-entry/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/cycle-entry/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/intersection/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/self-import/snapshot/output.snap
  crates/rspack/tests/samples/remove-parent-modules/simple/snapshot/output.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
  crates/rspack/tests/tree-shaking/tree-shaking-lazy-import/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/tree-shaking-lazy-import/snapshot/output.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/output.snap
  crates/rspack/tests/tree-shaking/webpack-innergraph-circular/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/webpack-innergraph-circular/snapshot/output.snap
  crates/rspack_core/src/cache/occasion/code_generate.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_core/src/update_hash.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/tests/fixtures/magic_comment/snapshot/output.snap
  crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_block.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_wasm/tests/fixtures/imports-multiple/snapshot/output.snap
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/changed-file.js
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/chunk.js
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/file.js
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/index.js
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/node_modules/react.js
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/node_modules/vue.js
  packages/rspack/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/webpack.config.js
Labels: team

#5349 fix: tree shaking size differentiation between webpack
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: bug fix

#5353 chore: remove unused puppeteer
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: team

#4835 refactor(compilation): Add callback to factorizeTask and make process dependencies happen after all dependencies get factorized
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  pnpm-lock.yaml
Labels: team

#4785 feat(compilation): introduce queue handles representing task_queue
  Cargo.lock
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_error/src/lib.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/fx_dashmap.rs
  crates/rspack_util/src/lib.rs
Labels: team, release: feature

#5356 refactor: remove async dependencies block identifier
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/chunk_graph/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_runtime/src/lazy_compilation.rs
Labels: team

#5355 test: remove outdated tests
  packages/rspack/tests/diagnostics/factorize/experiments-disable-transform-parse-error/stats.err
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/errors.js
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/index.js
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/jsx.jsx
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/stats.err
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/ts.ts
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/tsx.tsx
  packages/rspack/tests/diagnostics/factorize/rule-type-fatal-error/webpack.config.js
  packages/rspack/tests/diagnostics/module-parse-failed/jsx_syntax_error/stats.err
Labels: team

#5300 chore(diff): add esm export case
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-as.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-class.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-class-nameless.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-class.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-expression.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-async.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-generator.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-nameless.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-params.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-function.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-star.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/variables.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/no-strict.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/webpack.config.js
Labels: team

#5302 chore(diff): add esm import case
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/default-multiple-rename.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/default-rename.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/default.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-default-multiple.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-multiple-rename.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-multiple.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-rename.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-single.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/star.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/unuse.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/no-strict.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/test.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/webpack.config.js
Labels: team

#5359 fix(asset): real content hash changed even if asset has not changed
  crates/rspack_plugin_real_content_hash/src/lib.rs
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/hashCases/real-content-hash-consistent/src/file.png
  packages/rspack/tests/hashCases/real-content-hash-consistent/src/index.js
  packages/rspack/tests/hashCases/real-content-hash-consistent/test.config.js
  packages/rspack/tests/hashCases/real-content-hash-consistent/webpack.config.js
Labels: team, release: bug fix

#5361 chore: remove logs from tests
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  packages/rspack/tests/configCases/builtin-swc-loader/styled-components/index.jsx
  packages/rspack/tests/configCases/builtins/minify-pure-funcs/index.js
  packages/rspack/tests/configCases/builtins/minify-pure-funcs/webpack.config.js
  packages/rspack/tests/configCases/hooks/before-resolve/webpack.config.js
  packages/rspack/tests/configCases/parsing/node-source-plugin-off/index.js
  packages/rspack/tests/configCases/parsing/node-source-plugin-off/webpack.config.js
  packages/rspack/tests/configCases/plugins/minify-esbuild/index.js
  packages/rspack/tests/configCases/plugins/minify-pure-funcs/index.js
  packages/rspack/tests/configCases/plugins/minify-pure-funcs/webpack.config.js
  packages/rspack/tests/configCases/split-chunks-common/enforce-minsize/async.js
  packages/rspack/tests/configCases/split-chunks-common/enforce-minsize/foo.js
  packages/rspack/tests/configCases/split-chunks/css-simple/index.js
  packages/rspack/tests/configCases/split-chunks/issue-3646/src/shared.js
  scripts/debug/launch.mjs
  webpack-test/configCases/parsing/node-source-plugin-off/test.filter.js
Labels: team

#5366 perf: use hashset to compare ignore
  crates/rspack_core/src/dependencies_block.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/if_stmt.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_top_level_this.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
Labels: release: performance

#5369 chore: normalizing jsword
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/dependency_id.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/import_dependency_trait.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/dependency/static_exports_dependency.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/init_fragment.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_core/src/tree_shaking/optimizer.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/utils.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_core/src/tree_shaking/webpack_ext.rs
  crates/rspack_core/src/utils/visitor.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_html/src/visitors/asset.rs
  crates/rspack_plugin_html/src/visitors/utils.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_api_dep.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_plugin_wasm/src/dependency/wasm_import_dependency.rs
  crates/rspack_swc_visitors/src/relay.rs
  crates/rspack_util/src/swc.rs
  crates/swc_plugin_import/src/lib.rs
Labels: team

#5363 feat: not printing error code in error
  Cargo.lock
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_error/src/graphical.rs
  crates/rspack_error/src/lib.rs
  packages/rspack/tests/Stats.test.ts
  packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
  packages/rspack/tests/cases/parsing/issue-5120-binding/index.js
  packages/rspack/tests/cases/parsing/issue-5120-strict-block/index.js
  packages/rspack/tests/cases/parsing/issue-5120-strict/index.js
  packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/css-module-request-prefix/stats.err
  packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
  packages/rspack/tests/diagnostics/factorize/mismatched-module-type/stats.err
  packages/rspack/tests/diagnostics/factorize/missing-config-build-failed/stats.err
  packages/rspack/tests/diagnostics/factorize/module-parse-error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/basic/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/import_meta_warning/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/lack-equal/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/lexically_name_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/non_support_warning/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/reserved_name_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/stats.err
  packages/rspack/tests/diagnostics/module-parse-failed/tla_esm_error/stats.err
Labels: team, release: feature

#5333 chore: remove unused @types/webpack-dev-server from rspack devDependencies
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#5378 fix: return type of `Compiler.shouldEmit` should be boolean
  packages/rspack/src/Compiler.ts
Labels: release: bug fix

#5371 feat: handle webpack internal module source map
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/foo.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/index.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-no-source-root.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-pre-relative.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root-2-slash.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root-slash.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root-source-slash.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/webpack.config.js
Labels: release: feature

#5379 test(diff): add diff test case for harmony+commonjs mixed modules
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/index.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/bbb.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs1.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs3.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs4.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs5.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm1.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm2.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm3.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm4.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm5.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm6.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/test.config.js
Labels: team

#5376 chore: enable most of the tests from webpack-examples
  webpack-examples/aggressive-merging/test.filter.js
  webpack-examples/asset-simple/test.filter.js
  webpack-examples/build-http/test.filter.js
  webpack-examples/chunkhash/test.filter.js
  webpack-examples/code-splitted-require.context-amd/test.filter.js
  webpack-examples/code-splitted-require.context/test.filter.js
  webpack-examples/code-splitting-depend-on-advanced/test.filter.js
  webpack-examples/code-splitting-depend-on-simple/test.filter.js
  webpack-examples/code-splitting-harmony/test.filter.js
  webpack-examples/code-splitting-native-import-context-filter/test.filter.js
  webpack-examples/code-splitting-native-import-context/test.filter.js
  webpack-examples/code-splitting-specify-chunk-name/test.filter.js
  webpack-examples/code-splitting/test.filter.js
  webpack-examples/coffee-script/test.filter.js
  webpack-examples/common-chunk-and-vendor-chunk/test.filter.js
  webpack-examples/commonjs/test.filter.js
  webpack-examples/css/test.filter.js
  webpack-examples/externals/test.filter.js
  webpack-examples/extra-async-chunk-advanced/test.filter.js
  webpack-examples/extra-async-chunk/test.filter.js
  webpack-examples/harmony-interop/test.filter.js
  webpack-examples/harmony-library/test.filter.js
  webpack-examples/harmony-unused/test.filter.js
  webpack-examples/harmony/test.filter.js
  webpack-examples/hybrid-routing/test.filter.js
  webpack-examples/loader/test.filter.js
  webpack-examples/many-pages/test.filter.js
  webpack-examples/mixed/test.filter.js
  webpack-examples/module-code-splitting/test.filter.js
  webpack-examples/module-library/test.filter.js
  webpack-examples/module-worker/test.filter.js
  webpack-examples/module/test.filter.js
  webpack-examples/multi-compiler/test.filter.js
  webpack-examples/multi-part-library/test.filter.js
  webpack-examples/multiple-entry-points/test.filter.js
  webpack-examples/named-chunks/test.filter.js
  webpack-examples/reexport-components/test.filter.js
  webpack-examples/require.context/test.filter.js
  webpack-examples/require.resolve/test.filter.js
  webpack-examples/scope-hoisting/test.filter.js
  webpack-examples/side-effects/test.filter.js
  webpack-examples/source-map/test.filter.js
  webpack-examples/top-level-await/test.filter.js
  webpack-examples/two-explicit-vendor-chunks/test.filter.js
  webpack-examples/wasm-complex/test.filter.js
  webpack-examples/wasm-simple/test.filter.js
  webpack-examples/worker/test.filter.js
  webpack-test/Examples.test.js
  webpack-test/jest.config.js
Labels: team

#5380 fix(mf): different fallback module context
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  packages/rspack/tests/configCases/container/fallback-context/src/index.js
  packages/rspack/tests/configCases/container/fallback-context/src/shared.js
  packages/rspack/tests/configCases/container/fallback-context/webpack.config.js
Labels: team, release: bug fix

#5386 perf: reduce alloc
  crates/rspack_core/src/resolver/mod.rs
Labels: release: performance

#5357 fix(rspack_core): fix resolver returning broken missing dependencies
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
Labels: team, release: bug fix

#5389 fix: remove unnecessary return type of runtime module hook
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#5390 perf: cleanup `ApiScanner`
  crates/rspack_ast/src/ast/javascript.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack-cli/tests/build/basic/public/main.js.map
  packages/rspack/tests/cases/parsing/typeof-api-2/index.js
Labels: release: performance

#5391 chore: diff rspack/webpack test cases
  .eslintignore
  .typos.toml
  diff.js
  pnpm-lock.yaml
  scripts/package.json
  scripts/test/diff-exclude.cjs
  scripts/test/diff.cjs
Labels: team

#5397 fix: url-dependency pos error
  crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs
  packages/rspack/tests/configCases/asset-url/relative/index.css
  packages/rspack/tests/configCases/asset-url/relative/index.js
  packages/rspack/tests/configCases/asset-url/relative/webpack.config.js
Labels: team, release: bug fix

#5008 feat: progress plugin
  Cargo.lock
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_progress/src/lib.rs
Labels: release: feature

#5404 fix: remove unnecessary react-refreshfrom dev-server's dependencies
  packages/rspack-dev-server/package.json
  pnpm-lock.yaml
Labels: team, release: bug fix

#5406 ci: setup renovatebot
  .github/renovate.json
Labels: team

#5410 ci: only update github-actions and cargo dependencies
  .github/renovate.json
Labels: team

#5413 fix(renovate): fix cargo
  .github/renovate.json
Labels: team, release: bug fix

#5405 fix: use correct stats for child compilation
  packages/rspack/src/Stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/StatsFactory.ts
  packages/rspack/tests/Stats.test.ts
Labels: team, release: bug fix

#4718 feat(compilation): add ImportModule and executeModule
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_options/src/options/raw_module/js_loader.rs
  crates/rspack_binding_values/src/codegen_result.rs
  crates/rspack_binding_values/src/compilation.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/execute_module.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/queue.rs
  crates/rspack_core/src/dependency/dependency_category.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_core/src/dependency/loader_import_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/logger.rs
  crates/rspack_core/src/plugin/api.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_database/src/database.rs
  crates/rspack_loader_swc/tests/fixtures.rs
  crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ExecuteModulePlugin.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/tests/configCases/loader-import-module/css/colors.js
  packages/rspack/tests/configCases/loader-import-module/css/file.jpg
  packages/rspack/tests/configCases/loader-import-module/css/file.png
  packages/rspack/tests/configCases/loader-import-module/css/index.js
  packages/rspack/tests/configCases/loader-import-module/css/loader.js
  packages/rspack/tests/configCases/loader-import-module/css/other-stylesheet.js
  packages/rspack/tests/configCases/loader-import-module/css/stylesheet.js
  packages/rspack/tests/configCases/loader-import-module/css/webpack.config.js
  webpack-test/ConfigTestCases.template.js
  webpack-test/configCases/loader-import-module/css/test.filter.js
Labels: team, release: feature

#5402 chore: 🤖 remove redundant config
  webpack-test/cases/cjs-tree-shaking/cjs-to-esm/test.config.js
  webpack-test/cases/cjs-tree-shaking/esModule-getter/test.config.js
  webpack-test/cases/cjs-tree-shaking/esm-to-cjs/test.config.js
  webpack-test/cases/cjs-tree-shaking/exports/test.config.js
  webpack-test/cases/cjs-tree-shaking/importing/test.config.js
  webpack-test/cases/cjs-tree-shaking/mjs/test.config.js
  webpack-test/cases/cjs-tree-shaking/namespace/test.config.js
  webpack-test/cases/cjs-tree-shaking/non-root-this/test.config.js
  webpack-test/cases/cjs-tree-shaking/object-define-property-replace/test.config.js
  webpack-test/cases/cjs-tree-shaking/objects/test.config.js
  webpack-test/cases/cjs-tree-shaking/parsing/test.config.js
  webpack-test/cases/cjs-tree-shaking/reexports/test.config.js
  webpack-test/cases/cjs-tree-shaking/transpiled/test.config.js
  webpack-test/cases/cjs-tree-shaking/weird-names/test.config.js
  webpack-test/cases/inner-graph/circular/test.config.js
  webpack-test/cases/inner-graph/circular2/test.config.js
  webpack-test/cases/inner-graph/class-dynamic-props/test.config.js
  webpack-test/cases/inner-graph/export-default-named/test.config.js
  webpack-test/cases/inner-graph/extend-class/test.config.js
  webpack-test/cases/inner-graph/extend-class2/test.config.js
  webpack-test/cases/inner-graph/no-side-effects/test.config.js
  webpack-test/cases/inner-graph/pure-in-removed/test.config.js
  webpack-test/cases/inner-graph/reexport-namespace-and-default/test.config.js
  webpack-test/cases/inner-graph/simple/test.config.js
  webpack-test/cases/inner-graph/static-of-class/test.config.js
  webpack-test/cases/inner-graph/switch/test.config.js
  webpack-test/cases/inner-graph/try-globals/test.config.js
  webpack-test/cases/optimize/concat-star-import/test.config.js
  webpack-test/cases/optimize/many-exports-100/test.config.js
  webpack-test/cases/optimize/many-exports-120/test.config.js
  webpack-test/cases/optimize/many-exports-40/test.config.js
  webpack-test/cases/optimize/side-effects-all-chain-unused/test.config.js
  webpack-test/cases/optimize/side-effects-all-used/test.config.js
  webpack-test/cases/optimize/side-effects-immediate-unused/test.config.js
  webpack-test/cases/optimize/side-effects-root-unused/test.config.js
  webpack-test/cases/optimize/side-effects-scope-hoisting/test.config.js
  webpack-test/cases/optimize/side-effects-simple-unused/test.config.js
  webpack-test/cases/optimize/side-effects-transitive-unused/test.config.js
  webpack-test/cases/optimize/tree-shaking-commonjs/test.config.js
  webpack-test/cases/optimize/tree-shaking-star/test.config.js
  webpack-test/cases/optimize/tree-shaking-star2/test.config.js
  webpack-test/cases/side-effects/dynamic-reexports/test.config.js
  webpack-test/cases/side-effects/empty-modules/test.config.js
  webpack-test/cases/side-effects/issue-11673/test.config.js
  webpack-test/cases/side-effects/issue-12071/test.config.js
  webpack-test/cases/side-effects/issue-12114/test.config.js
  webpack-test/cases/side-effects/issue-12570-second-try/test.config.js
  webpack-test/cases/side-effects/issue-12570/test.config.js
  webpack-test/cases/side-effects/missing-module-7499/test.config.js
  webpack-test/cases/side-effects/order-issue-7665/test.config.js
  webpack-test/cases/side-effects/wrong-module-10146/test.config.js
Labels: team

#5414 fix(renovate): improve handling of certain packages
  .github/renovate.json
Labels: team, release: bug fix

#5427 fix: use `eval.as_string()` lazily
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  packages/rspack/tests/cases/parsing/issue-5426/index.js
Labels: release: bug fix

#5428 fix: cannot block the current thread from within a runtime
  crates/rspack_binding_options/src/options/raw_devtool.rs
  crates/rspack_plugin_devtool/src/lib.rs
Labels: release: bug fix

#5431 fix: evaluate if stmt should skip import specifier in dead branch
  crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
  packages/rspack/tests/cases/parsing/evaluate-if/foo.js
  packages/rspack/tests/cases/parsing/evaluate-if/index.js
Labels: team, release: bug fix

#5433 perf: lazy calculate compilation.modules and compilation.chunks
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/util/memoize.ts
Labels: team, release: performance

#5409 fix: resolve error with inline loader without module specifier
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_loader_runner/src/runner.rs
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/foo.js
  packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/index.js
Labels: release: bug fix

#5436 fix(@rspack/core): js Compilation instance is not recreated as expected when rebuilding on watch/serve mode
  packages/rspack/src/Compiler.ts
Labels: release: bug fix

#5429 chore: use `cargo machete` for checking unused dependencies
  .github/workflows/ci.yml
  Cargo.lock
  crates/rspack_core_macros/Cargo.toml
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_runtime/Cargo.toml
  crates/swc_plugin_import/Cargo.toml
Labels: team

#5449 chore: unify crate versions
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_testing/Cargo.toml
Labels: team

#5448 fix: InnerGraph does not rename the usage of the renamed class in if statement #5441
  crates/rspack/tests/tree-shaking/unused-class-rename/app.js
  crates/rspack/tests/tree-shaking/unused-class-rename/index.js
  crates/rspack/tests/tree-shaking/unused-class-rename/snapshot/new_treeshaking.snap
  crates/rspack/tests/tree-shaking/unused-class-rename/snapshot/output.snap
  crates/rspack/tests/tree-shaking/unused-class-rename/test.config.json
  crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
Labels: team, release: bug fix

#5451 chore: pin `styled_components` along with the same swc versions
  .github/renovate.json
  Cargo.toml
Labels: team

#5447 fix: use full content hash in `SourceMapDevtoolPlugin`
  crates/rspack_plugin_devtool/src/lib.rs
  packages/rspack/tests/configCases/source-map/source-map-filename-contenthash/index.js
  packages/rspack/tests/configCases/source-map/source-map-filename-contenthash/webpack.config.js
  webpack-test/configCases/source-map/source-map-filename-contenthash/test.filter.js
Labels: release: bug fix

#5459 chore: bump indexmap from 1.9.3 to 2.1.0
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_css/Cargo.toml
Labels: team

#5458 fix: assign depth for include dependencies
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/a/index.js
  packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/a/util.js
  packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/index.js
  packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/reexport.js
  packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/webpack.config.js
Labels: team, release: bug fix

#5462 chore: bump bitflags to v2.4.2
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/fake_namespace_object.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/runtime_globals.rs
  crates/rspack_core/src/tree_shaking/mod.rs
  crates/rspack_core/src/tree_shaking/symbol/mod.rs
  crates/rspack_core/src/tree_shaking/visitor.rs
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
Labels: team

#5464 chore: renovate bot turn on npm devDependencies update
  .github/renovate.json
Labels: team

#5466 chore: renovate ignore more directories
  .github/renovate.json
Labels: team

#5463 chore: bump handlebars to v5.1.1
  Cargo.lock
  crates/swc_plugin_import/Cargo.toml
  crates/swc_plugin_import/src/lib.rs
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/errors.js
  packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/index.js
Labels: team

#4931 feat: context module support inline loader
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/context_module_factory.rs
  packages/rspack/tests/configCases/loader/context/a.js
  packages/rspack/tests/configCases/loader/context/index.js
  packages/rspack/tests/configCases/loader/context/replace-loader.js
  packages/rspack/tests/configCases/loader/context/webpack.config.js
  webpack-test/cases/loaders/context/test.filter.js
Labels: release: feature

#5468 chore: bump TypeScript to 5.3.3
  package.json
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
  tsconfig.base.json
Labels: team

#5470 chore: remove typescript devDependencies from packages/create-rspack/template-react-ts
  .github/renovate.json
  packages/create-rspack/template-react-ts/package.json
  pnpm-lock.yaml
Labels: team

#5471 chore: bump @types/react and @types/react-dom
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react/package.json
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
Labels: team
