Repository web-infra-dev/rspack, pull requests merged in 2025-09, with the labels that each got.

#11544 fix: css runtime
  crates/rspack_plugin_extract_css/src/runtime/css_load.js
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/src/runtime/cssExtractHmr.ts
  tests/e2e/cases/css/update-initial-chunks-after-hmr/index.test.ts
  tests/e2e/cases/css/update-initial-chunks-after-hmr/rspack.config.js
  tests/e2e/cases/css/update-initial-chunks-after-hmr/src/blue.css
  tests/e2e/cases/css/update-initial-chunks-after-hmr/src/index.css
  tests/e2e/cases/css/update-initial-chunks-after-hmr/src/index.html
  tests/e2e/cases/css/update-initial-chunks-after-hmr/src/index.js
Labels: team, release: bug fix

#11547 fix: should check http url using `link.href` for extract-css runtime
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/src/runtime/cssExtractHmr.ts
Labels: team, release: bug fix

#11519 fix: extend modify event handling to include metadata changes
  crates/rspack_fs/src/watcher/disk_watcher.rs
  packages/rspack-test-tools/tests/watchCases/change-event/metadata/0/index.js
  packages/rspack-test-tools/tests/watchCases/change-event/metadata/1/_module.js
  packages/rspack-test-tools/tests/watchCases/change-event/metadata/rspack.config.js
Labels: team, release: bug fix

#11528 fix: don't throw error when browserslist config is resolved from env var
  packages/rspack/src/config/target.ts
Labels: release: bug fix

#11534 chore: release v1.5.2
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-browser/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#11555 fix: use stable swc lexer for correct asi
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/semicolon.rs
  packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
Labels: team, release: bug fix

#11561 docs: add tree shaking blog to the blog list
  website/docs/en/blog/index.mdx
  website/docs/zh/blog/index.mdx
Labels: team, release: document

#11520 chore: use pnpm in package.json scripts
  .husky/pre-commit
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  lint-staged.config.mjs
  package.json
  tests/e2e/package.json
  x.mjs
Labels: team

#11568 fix: respect to `jsc.output.charset` in swc loader
  crates/rspack_javascript_compiler/src/compiler/minify.rs
  crates/rspack_javascript_compiler/src/compiler/stringify.rs
  crates/rspack_javascript_compiler/src/compiler/transform.rs
  crates/rspack_util/src/swc.rs
  packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/a.js
  packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/b.js
  packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/rspack.config.js
Labels: team, release: bug fix

#11548 feat: add css field support in Experiments configuration
  crates/node_binding/napi-binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_api/src/raw_options/raw_experiments/mod.rs
  crates/rspack_core/src/options/experiments/mod.rs
Labels: release: feature

#11569 refactor: use for_name for cjs import parser plugin
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_rslib/src/parser_plugin.rs
Labels: team, release: refactor

#11556 perf: improve bundle splitting
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
Labels: team, release: performance

#11573 perf: improve for each runtime
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime_id.rs
Labels: team, release: performance

#11524 perf: improve exports info
  crates/rspack_core/src/exports/exports_info_getter.rs
Labels: team, release: performance

#11585 docs(loader-api): add new sections for handling source maps
  website/docs/en/api/loader-api/_meta.json
  website/docs/en/api/loader-api/context.mdx
  website/docs/en/api/loader-api/index.mdx
  website/docs/en/api/loader-api/writing-loaders.mdx
  website/docs/en/config/module.mdx
  website/docs/en/guide/features/loader.mdx
  website/docs/zh/api/loader-api/_meta.json
  website/docs/zh/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/index.mdx
  website/docs/zh/api/loader-api/writing-loaders.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/features/loader.mdx
  website/project-words.txt
Labels: team, release: document

#11575 perf: improve deterministic chunk ids
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_ids/src/named_chunk_ids_plugin.rs
  crates/rspack_ids/src/natural_chunk_ids_plugin.rs
  crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
Labels: team, release: performance

#11591 fix: only enable inline const in production
  packages/rspack-test-tools/tests/configCases/inline-const/dev/index.js
  packages/rspack-test-tools/tests/configCases/inline-const/dev/rspack.config.js
  packages/rspack/src/config/defaults.ts
  website/docs/en/config/module.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: bug fix

#11579 perf: improve get chunk modules
  Cargo.lock
  crates/rspack_binding_api/src/chunk_graph.rs
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_extract_css/src/runtime.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/drive.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_mf/src/container/expose_runtime_module.rs
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
  crates/rspack_plugin_module_info_header/Cargo.toml
  crates/rspack_plugin_module_info_header/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
Labels: team, release: performance

#11596 chore: update Rspress to beta.31 to use JSON schemas
  .vscode/settings.json
  pnpm-lock.yaml
  website/package.json
Labels: team

#11601 docs: fix esm syntax error
  website/docs/en/guide/features/esm.mdx
  website/docs/zh/guide/features/esm.mdx
Labels: release: document

#11608 fix: flaky css chunking test case
  packages/rspack-test-tools/tests/configCases/css-chunking-plugin/base-global-css-chunking/rspack.config.js
Labels: team, release: bug fix

#11613 feat: static analyze in operator for esm import specifier
  crates/rspack_plugin_javascript/src/dependency/esm/esm_evaluated_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack-test-tools/tests/configCases/parsing/esm-in-operator/index.js
  packages/rspack-test-tools/tests/configCases/parsing/esm-in-operator/m.js
Labels: team, release: feature

#11610 fix: e2e lazy-compialtion/default-prefix flasky
  tests/e2e/cases/lazy-compilation/default-prefix/index.test.ts
  tests/e2e/cases/lazy-compilation/default-prefix/rspack.config.js
  tests/e2e/cases/lazy-compilation/default-prefix/src/index.js
Labels: team, release: bug fix

#11628 feat: add inline value condition for reexport
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/export_info_setter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
  crates/rspack_core/src/exports/exports_info_setter.rs
  crates/rspack_core/src/exports/target.rs
  crates/rspack_core/src/exports/utils.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  tests/rspack-test/configCases/inline-const/basic/index.js
  tests/rspack-test/configCases/inline-const/basic/re-export.barrel-side-effects.js
  tests/rspack-test/configCases/inline-const/basic/re-export.destructing-barrel-side-effects.js
Labels: team, release: feature

#11630 fix: revert "fix(rslib): treat `module` identifier as normal (#11588)"
  crates/rspack_plugin_rslib/src/parser_plugin.rs
  tests/rspack-test/configCases/rslib/plugin-api/index.js
  tests/rspack-test/configCases/rslib/plugin-api/test.js
Labels: team, release: bug fix

#11636 chore: make @rspack/tests private
  tests/rspack-test/package.json
Labels: team

#11657 chore(ci): add rstest to ecosystem-ci
  .github/workflows/ecosystem-ci.yml
Labels: team

#11658 chore: release 1.5.4
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-arm64-gnu/package.json
  npm/linux-arm64-musl/package.json
  npm/linux-x64-gnu/package.json
  npm/linux-x64-musl/package.json
  npm/wasm32-wasi/package.json
  npm/win32-arm64-msvc/package.json
  npm/win32-ia32-msvc/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-browser/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#11670 fix(core): support NAPI_RS_NATIVE_LIBRARY_PATH
  crates/node_binding/binding.js
Labels: team, release: bug fix

#11668 chore(refactor): inline base64 utilities into rspack_util
  Cargo.lock
  Cargo.toml
  crates/rspack_base64/Cargo.toml
  crates/rspack_base64/src/lib.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/filename.rs
  crates/rspack_plugin_asset/Cargo.toml
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/sri.rs
  crates/rspack_plugin_schemes/Cargo.toml
  crates/rspack_plugin_schemes/src/data_uri.rs
  crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
  crates/rspack_plugin_sri/Cargo.toml
  crates/rspack_plugin_sri/src/integrity.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/base64.rs
  crates/rspack_util/src/lib.rs
Labels: team

#11671 docs: remove incorrect `emitRecords` compiler hook
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
Labels: team, release: document

#11676 test: run webpack compiler test cases with rspack test tools
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/compiler.ts
  packages/rspack-test-tools/src/compiler.ts
  packages/rspack-test-tools/src/helper/legacy/deprecationTracking.js
  packages/rspack-test-tools/src/processor/simple.ts
  packages/rspack-test-tools/src/type.ts
  tests/rspack-test/compilerCases/after-done-hook.js
  tests/rspack-test/compilerCases/asm-constants.js
  tests/rspack-test/compilerCases/assets-empty.js
  tests/rspack-test/compilerCases/assets-exist.js
  tests/rspack-test/compilerCases/assets-not-exist.js
  tests/rspack-test/compilerCases/assets-update-info.js
  tests/rspack-test/compilerCases/assets-update.js
  tests/rspack-test/compilerCases/assets.js
  tests/rspack-test/compilerCases/bubble-bail.js
  tests/rspack-test/compilerCases/cache-second-run.js
  tests/rspack-test/compilerCases/child-compiler.js
  tests/rspack-test/compilerCases/compare-before-emit-disable.js
  tests/rspack-test/compilerCases/compare-before-emit.js
  tests/rspack-test/compilerCases/compilation.js
  tests/rspack-test/compilerCases/error-stack-async.js
  tests/rspack-test/compilerCases/error-stack-sync.js
  tests/rspack-test/compilerCases/error-stack.js
  tests/rspack-test/compilerCases/failed-hook.js
  tests/rspack-test/compilerCases/get-cache.js
  tests/rspack-test/compilerCases/hooks-after-optimize-modules.js
  tests/rspack-test/compilerCases/hooks-closure.js
  tests/rspack-test/compilerCases/hooks-optimize-modules.js
  tests/rspack-test/compilerCases/infrastructure-logging.js
  tests/rspack-test/compilerCases/is-child.js
  tests/rspack-test/compilerCases/multiple-chunks.js
  tests/rspack-test/compilerCases/named-chunk.js
  tests/rspack-test/compilerCases/no-emit-errors.js
  tests/rspack-test/compilerCases/persist-build-info.js
  tests/rspack-test/compilerCases/purge-input-filesystem.js
  tests/rspack-test/compilerCases/resolver-api.js
  tests/rspack-test/compilerCases/run-again.js
  tests/rspack-test/compilerCases/run-twice.js
  tests/rspack-test/compilerCases/single-file.js
  tests/rspack-test/compilerCases/splitchunks-minchunks.js
  tests/rspack-test/compilerCases/stats.js
  tests/rspack-test/compilerCases/swc-api-sourcemaps.js
  tests/rspack-test/compilerCases/swc-api.js
  tests/rspack-test/compilerCases/tracing.js
  tests/rspack-test/compilerCases/transitive-dependencies.js
  tests/rspack-test/compilerCases/watching.js
  tests/rspack-test/fixtures/node_modules/complexm/step1.js
  tests/rspack-test/fixtures/node_modules/complexm/step2.js
  tests/rspack-test/fixtures/node_modules/m1/a.js
  tests/rspack-test/fixtures/node_modules/m1/b.js
  tests/rspack-test/fixtures/node_modules/m2-loader/b.js
  tests/rspack-test/fixtures/node_modules/m2/b.js
  tests/webpack-test/jest.config.js
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/testing-rspack.mdx
Labels: team

#11679 fix: inline value condition for namespace import
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  tests/rspack-test/configCases/inline-const/issue-11677/index.js
  tests/rspack-test/configCases/inline-const/issue-11677/lib.js
  tests/rspack-test/configCases/inline-const/issue-11677/rspack.config.js
Labels: team, release: bug fix

#11692 ci: fix build-dependencies-resolve test case
  tests/rspack-test/cacheCases/common/build-dependencies-resolve/file.js
  tests/rspack-test/cacheCases/common/build-dependencies-resolve/index.js
  tests/rspack-test/cacheCases/common/build-dependencies-resolve/node_modules/lib/package.json
  tests/rspack-test/cacheCases/common/build-dependencies-resolve/rspack.config.js
Labels: team

#11674 fix: align context module element dependence resource identifer with webpack
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_plugin_module_replacement/src/context_replacement.rs
  tests/rspack-test/configCases/context-module/two_files_share_a_request/index.js
  tests/rspack-test/configCases/context-module/two_files_share_a_request/rspack.config.js
  tests/rspack-test/configCases/context-module/two_files_share_a_request/sub/index.js
  tests/rspack-test/configCases/context-module/two_files_share_a_request/sub/index.ts
Labels: team, release: bug fix

#11700 docs: update join-us page content and structure
  website/docs/en/misc/team/join-us.mdx
  website/docs/zh/misc/team/join-us.mdx
Labels: team, release: document

#11701 fix: inline value condition connection active for re-export
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  tests/rspack-test/__snapshots__/StatsAPI.test.js.snap
  tests/rspack-test/__snapshots__/StatsOutput.test.js.snap
  tests/rspack-test/configCases/inline-const/connection-active/a.js
  tests/rspack-test/configCases/inline-const/connection-active/index.js
  tests/rspack-test/configCases/inline-const/connection-active/lib.js
  tests/rspack-test/configCases/inline-const/connection-active/reexport.js
  tests/rspack-test/configCases/inline-const/connection-active/rspack.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#11705 test: refactor runner
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/hot-step.ts
  packages/rspack-test-tools/src/case/normal.ts
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/src/runner/index.ts
  packages/rspack-test-tools/src/runner/normal.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/cjs.ts
  packages/rspack-test-tools/src/runner/runner/esm.ts
  packages/rspack-test-tools/src/runner/runner/index.ts
  packages/rspack-test-tools/src/runner/runner/node/index.ts
  packages/rspack-test-tools/src/runner/runner/normal.ts
  packages/rspack-test-tools/src/runner/runner/watch.ts
  packages/rspack-test-tools/src/runner/runner/web/fake.ts
  packages/rspack-test-tools/src/runner/runner/web/index.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
  packages/rspack-test-tools/src/runner/type.ts
  packages/rspack-test-tools/src/runner/watch.ts
  packages/rspack-test-tools/src/type.ts
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/testing-rspack.mdx
Labels: team

#11686 fix: support non-ascii paths in dirname
  crates/rspack_core/src/options/context.rs
  tests/rspack-test/configCases/一个非常长的中文目录/context/rspack.config.js
  tests/rspack-test/configCases/一个非常长的中文目录/context/src/index.js
  tests/rspack-test/configCases/一个非常长的中文目录/context/src/message.js
Labels: team, release: bug fix, codex

#11634 fix(rslib): only treat "module" as normal variable when module have ESM syntax
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_rslib/src/parser_plugin.rs
  tests/rspack-test/configCases/rslib/plugin-api/cjsFile.cjs
  tests/rspack-test/configCases/rslib/plugin-api/index.js
  tests/rspack-test/configCases/rslib/plugin-api/rspack.config.js
  tests/rspack-test/configCases/rslib/plugin-api/test.js
Labels: team, release: bug fix

#11708 refactor: rspack_cacheable `owned_or_ref` implement rkyv macro
  crates/rspack_cacheable/src/utils/owned_or_ref.rs
  crates/rspack_cacheable_test/tests/utils/mod.rs
  crates/rspack_cacheable_test/tests/utils/owned_or_ref.rs
  crates/rspack_cacheable_test/tests/utils_case.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
Labels: team, release: refactor

#11706 fix: remove `serde` feature of `lightningcss`
  Cargo.lock
  Cargo.toml
  crates/rspack_cacheable/src/with/as_preset/lightningcss.rs
  crates/rspack_cacheable_test/tests/with/as_preset/lightningcss.rs
Labels: release: bug fix

#11711 feat: rspack_cacheable add custom with wrapper
  crates/rspack_cacheable/src/with/custom.rs
  crates/rspack_cacheable/src/with/mod.rs
  crates/rspack_cacheable_test/tests/with/custom.rs
  crates/rspack_cacheable_test/tests/with/mod.rs
Labels: team, release: feature

#11712 refactor: rspack module profiler
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/stats.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/add.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/build.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/factorize.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/mod.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/process_dependencies.rs
  crates/rspack_core/src/compilation/make/module_executor/entry.rs
  crates/rspack_core/src/module_graph/module.rs
  crates/rspack_core/src/module_profile.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
Labels: team, release: refactor

#11715 feat: persistent cache save ModuleProfiler
  crates/rspack_core/src/module_graph/module.rs
  crates/rspack_core/src/module_profile.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team, release: feature

#11665 feat: static analyse import then for tree shaking
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_plugin_javascript/src/dependency/context/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/compare/format-code.ts
  packages/rspack-test-tools/src/helper/legacy/checkArrayExpectation.js
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/src/runner/hot.ts
  tests/rspack-test/builtinCases/rspack/dynamic-import/__snapshots__/output.snap.txt
  tests/rspack-test/configCases/lazy-barrel/basic/rspack.config.js
  tests/rspack-test/configCases/parsing/statical-dynamic-import-this/index.js
  tests/rspack-test/configCases/rsdoctor/assets/rspack.config.js
  tests/rspack-test/configCases/split-chunks/rspack-issue-11583/src/index.js
  tests/rspack-test/normalCases/chunks/inline-options/index.js
  tests/rspack-test/normalCases/chunks/inline-options/warnings.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then-destructuring/dir1/a.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then-destructuring/index.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then-destructuring/required.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then-destructuring/test.filter.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then-destructuring/warnings.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/dir1/a.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/index.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/required.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/test.filter.js
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/warnings.js
  tests/rspack-test/normalCases/parsing/webpack-exports/index.js
  tests/rspack-test/runtimeDiffCases/module-interop/context-module/test.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#11704 feat: support webpackIgnore in commonjs require
  crates/node_binding/napi-binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_api/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/schema/config.ts
  tests/rspack-test/configCases/parsing/require-ignore/test.filter.js
Labels: team, release: feature, codex

#11743 fix: mf should correctly hoist modules
  crates/rspack_plugin_mf/src/container/hoist_container_references_plugin.rs
  tests/rspack-test/watchCases/async-modules/top-level-await/0/case1/index.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/a.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/b.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/getWorker.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/main.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/worker.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/1/main.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/rspack.config.js
  tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/test.config.js
Labels: team, release: bug fix

#11750 chore: release v1.5.7
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-arm64-gnu/package.json
  npm/linux-arm64-musl/package.json
  npm/linux-x64-gnu/package.json
  npm/linux-x64-musl/package.json
  npm/wasm32-wasi/package.json
  npm/win32-arm64-msvc/package.json
  npm/win32-ia32-msvc/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-browser/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#11760 fix: should always walk import then arguments
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/index.js
Labels: team, release: bug fix

#11764 test: close compiler
  packages/rspack-test-tools/src/test/tester.ts
Labels: team

#11749 perf: rspack sources buffer function
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: team, release: performance

#11767 docs: document parser jsx option
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#11643 fix: should update alias resolution when a higher-priority file is created in watch mode
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/compilation/make/artifact.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/factorize.rs
  crates/rspack_core/src/dependency/factorize_info.rs
  crates/rspack_core/src/normal_module_factory.rs
  tests/rspack-test/configCases/context/missing-dependency/rspack.config.js
  tests/rspack-test/watchCases/resolve/alias/0/a.js
  tests/rspack-test/watchCases/resolve/alias/0/index.js
  tests/rspack-test/watchCases/resolve/alias/1/b.js
  tests/rspack-test/watchCases/resolve/alias/rspack.config.js
Labels: team, release: bug fix

#11765 feat: transform url in new URL without runtime
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
  crates/rspack_core/src/artifacts/code_generation_results.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/dependency_id.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/url_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/src/runner/node/index.ts
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/URLPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/schema/config.ts
  tests/rspack-test/configCases/asset-url/new-url-relative/asset.js
  tests/rspack-test/configCases/asset-url/new-url-relative/index.js
  tests/rspack-test/configCases/asset-url/new-url-relative/rspack.config.js
  tests/rspack-test/configCases/asset-url/new-url-relative/test.config.js
  tests/rspack-test/configCases/asset-url/new-url-relative/test.js
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: feature

#11769 test: add persistent cache symlink test case
  tests/rspack-test/cacheCases/invalidation/lib-symlink/file.js
  tests/rspack-test/cacheCases/invalidation/lib-symlink/index.js
  tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v1/index.js
  tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v1/package.json
  tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v2/index.js
  tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v2/package.json
  tests/rspack-test/cacheCases/invalidation/lib-symlink/rspack.config.js
Labels: team

#11768 fix: should analyze correct variable for dynamic import
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  tests/rspack-test/normalCases/chunks/statical-dynamic-import/index.js
Labels: team, release: bug fix

#11777 docs: add Snap to who is using section
  website/theme/components/Landingpage/WhoIsUsing/assets/snap.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: team, release: document

#11784 docs(style): remove unexpected borders on code block focus
  website/theme/index.css
Labels: release: document

#11785 fix: URLPlugin in child compiler
  packages/rspack/src/builtin-plugin/URLPlugin.ts
Labels: team, release: bug fix

#11787 test: run webpack multi compiler test cases with test tools
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/case/multi-compiler.ts
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
  tests/rspack-test/MultiCompiler.test.js
  tests/rspack-test/legacy-test/MultiCompiler.test.js
  tests/rspack-test/multiCompilerCases/invalidate.js
  tests/rspack-test/multiCompilerCases/lazy-compilation.js
  tests/rspack-test/multiCompilerCases/parallelism.js
  tests/rspack-test/multiCompilerCases/pressure.js
  tests/rspack-test/multiCompilerCases/run-again.js
  tests/rspack-test/multiCompilerCases/run-twice.js
  tests/rspack-test/multiCompilerCases/run.js
  tests/webpack-test/jest.config.js
Labels: team

#11786 release: 1.5.8
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-arm64-gnu/package.json
  npm/linux-arm64-musl/package.json
  npm/linux-x64-gnu/package.json
  npm/linux-x64-musl/package.json
  npm/wasm32-wasi/package.json
  npm/win32-arm64-msvc/package.json
  npm/win32-ia32-msvc/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-browser/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#11789 chore: rspack_plugin_esm_library should have description
  crates/rspack_plugin_esm_library/Cargo.toml
Labels: team

#11792 docs: improve documentation for stats properties
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  website/docs/en/api/javascript-api/stats-json.mdx
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/javascript-api/stats-json.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: team, release: document

#11794 fix(loader-runner): add missing break statements in switch cases
  biome.jsonc
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/worker.ts
  packages/rspack/src/logging/createConsoleLogger.ts
Labels: team, release: bug fix

#11798 refactor: update type definitions to fix Rslint issues
  package.json
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Diagnostics.ts
  packages/rspack/src/ExecuteModulePlugin.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/Watching.ts
  packages/rspack/src/builtin-loader/swc/pluginImport.ts
  packages/rspack/src/builtin-plugin/CircularDependencyRspackPlugin.ts
  packages/rspack/src/builtin-plugin/DefinePlugin.ts
  packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
  packages/rspack/src/builtin-plugin/RsdoctorPlugin.ts
  packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
  packages/rspack/src/builtin-plugin/css-extract/index.ts
  packages/rspack/src/builtin-plugin/css-extract/loader.ts
  packages/rspack/src/builtin-plugin/html-plugin/plugin.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/devServer.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/target.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/lib/cache/getLazyHashedEtag.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/worker.ts
  packages/rspack/src/runtime/cssExtractHmr.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPresetPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/trace/index.ts
  packages/rspack/src/util/ArrayQueue.ts
  packages/rspack/src/util/comparators.ts
  rslint.json
Labels: team, release: refactor

#11799 docs: explain how `resolve.alias` affects package resolution
  website/docs/en/config/resolve.mdx
  website/docs/zh/config/resolve.mdx
Labels: team, release: document
