Repository web-infra-dev/rspack, pull requests merged in 2025-05, with the labels that each got.

#10243 ci: remove stale workflow
  .github/renovate.json5
  .github/stale.yml
Labels: team

#10263 refactor: CI lint add required check
  .github/workflows/ci-lint.yaml
Labels: team

#10256 chore: upgrade swc to v22.5.3 and enable swc tracing
  Cargo.lock
  Cargo.toml
  crates/rspack_tracing/src/chrome.rs
Labels: team

#10267 docs: enhance Data URI module and MIME type rules
  packages/rspack/src/config/types.ts
  website/docs/en/api/runtime-api/module-methods.mdx
  website/docs/en/config/module.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#10272 chore(deps): remove loader-utils v2
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/inline-pitching/pitching-loader.js
  packages/rspack-test-tools/tests/configCases/loader/rspack-issue-4838/node_modules/loader1.js
  pnpm-lock.yaml
  tests/webpack-test/cases/loaders/issue-10725/loader.js
  tests/webpack-test/cases/wasm/two-files-loader/wrapper-loader.js
  tests/webpack-test/cases/wasm/two-files-loader/wrapper-loader2.js
  tests/webpack-test/configCases/loaders/issue-3320/node_modules/any-loader.js
  tests/webpack-test/package.json
Labels: team

#10276 chore: bump rspack resolver 0.5.6
  Cargo.lock
  Cargo.toml
Labels: team

#10273 fix: process warnings multiple times
  crates/node_binding/binding.d.ts
  crates/node_binding/src/stats.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  tests/webpack-test/statsCases/ignore-warnings/test.filter.js
Labels: team, release: bug fix

#10284 fix(html): not to override plugin options when using multiple instances
  crates/node_binding/binding.d.ts
  crates/node_binding/src/html.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_html.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/drive.rs
  crates/rspack_plugin_html/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/builtins/html-custom-options/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-custom-options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/html-multiple-options/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-multiple-options/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/html-plugin/hooks.ts
  packages/rspack/src/builtin-plugin/html-plugin/options.ts
  packages/rspack/src/builtin-plugin/html-plugin/plugin.ts
  packages/rspack/src/builtin-plugin/html-plugin/taps.ts
Labels: team, release: bug fix

#10246 feat(wasm): support `tracing-chrome` in wasm
  crates/rspack_tracing/src/chrome.rs
  crates/rspack_tracing/src/lib.rs
  crates/rspack_tracing/src/stdout.rs
  crates/rspack_tracing_chrome/src/lib.rs
  packages/rspack/src/Compiler.ts
Labels: release: feature

#10229 feat: add url config to css parser
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: feature

#10285 chore: release v1.3.9
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10287 docs(diagnostic): add loader experimental diagnostic API
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: team, release: document

#10289 fix(types): export PitchLoaderDefinitionFunction type
  packages/rspack/src/config/adapter.ts
Labels: release: bug fix

#10286 feat: expose hasChunkEntryDependentChunks on ChunkGraph
  crates/node_binding/binding.d.ts
  crates/node_binding/src/chunk_graph.rs
  packages/rspack/src/ChunkGraph.ts
Labels: release: feature

#10294 fix: allow the SRI plugin to be used without passing options
  packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
Labels: team, release: bug fix

#9939 test: remove new code splitting tests as now its the default
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/case/new-code-splitting.ts
  packages/rspack-test-tools/tests/NewCodeSplitting-config.test.js
  packages/rspack-test-tools/tests/NewCodeSplitting-stats-output.test.js
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
Labels: team

#10288 test: enable some test cases
  pnpm-lock.yaml
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/StatsTestCases.basictest.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/configCases/asset-emitted/normal/test.filter.js
  tests/webpack-test/configCases/asset-emitted/normal/webpack.config.js
  tests/webpack-test/configCases/async-commons-chunk/existing-name/test.filter.js
  tests/webpack-test/configCases/code-generation/require-context-id/test.filter.js
  tests/webpack-test/configCases/context-exclusion/simple/test.filter.js
  tests/webpack-test/configCases/context-replacement/a/test.filter.js
  tests/webpack-test/configCases/context-replacement/d/test.filter.js
  tests/webpack-test/configCases/css/async-chunk-node/index.js
  tests/webpack-test/configCases/css/async-chunk-node/test.filter.js
  tests/webpack-test/configCases/css/basic-esm-target-web/test.filter.js
  tests/webpack-test/configCases/css/contenthash/test.filter.js
  tests/webpack-test/configCases/css/pseudo-export/index.js
  tests/webpack-test/configCases/css/pseudo-export/test.filter.js
  tests/webpack-test/configCases/library/modern-module-reexport-type/test.filter.js
  tests/webpack-test/package.json
  tests/webpack-test/statsCases/chunks-development/test.filter.js
  tests/webpack-test/statsCases/chunks/test.filter.js
  tests/webpack-test/statsCases/performance-disabled/test.filter.js
  tests/webpack-test/statsCases/performance-error/test.filter.js
  tests/webpack-test/statsCases/performance-no-hints/test.filter.js
  tests/webpack-test/statsCases/preset-detailed/test.filter.js
  tests/webpack-test/statsCases/preset-minimal/test.filter.js
  tests/webpack-test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/test.filter.js
  tests/webpack-test/statsCases/preset-normal-performance/test.filter.js
  tests/webpack-test/statsCases/preset-normal/test.filter.js
Labels: team

#10299 docs: fix invalid link
  website/docs/en/api/runtime-api/module-variables.mdx
  website/docs/zh/api/runtime-api/module-variables.mdx
Labels: team, release: document

#10301 feat: support binary option of asset generator
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  tests/webpack-test/configCases/asset-modules/keep-source-maps/index.js
  tests/webpack-test/configCases/asset-modules/keep-source-maps/test.filter.js
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: feature

#10298 fix: parser generator arg validate
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#10302 test: enable more webpack stats test cases
  pnpm-lock.yaml
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/StatsTestCases.basictest.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/package.json
  tests/webpack-test/statsCases/chunks-development/test.filter.js
  tests/webpack-test/statsCases/chunks/test.filter.js
  tests/webpack-test/statsCases/performance-disabled/test.filter.js
  tests/webpack-test/statsCases/performance-error/test.filter.js
  tests/webpack-test/statsCases/performance-no-hints/test.filter.js
  tests/webpack-test/statsCases/preset-detailed/test.filter.js
  tests/webpack-test/statsCases/preset-minimal/test.filter.js
  tests/webpack-test/statsCases/preset-normal-performance-ensure-filter-sourcemaps/test.filter.js
  tests/webpack-test/statsCases/preset-normal-performance/test.filter.js
  tests/webpack-test/statsCases/preset-normal/test.filter.js
Labels: team

#10307 fix: chunk loading should be import by default when chunk format is module
  crates/rspack_plugin_runtime/src/runtime_module/export_webpack_require.rs
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/configCases/output/chunk-format-with-runtimeChunk/test.filter.js
Labels: team, release: bug fix

#10306 test: enable more webpack config test cases
  tests/webpack-test/configCases/asset-emitted/normal/test.filter.js
  tests/webpack-test/configCases/asset-emitted/normal/webpack.config.js
  tests/webpack-test/configCases/async-commons-chunk/existing-name/test.filter.js
  tests/webpack-test/configCases/code-generation/require-context-id/test.filter.js
  tests/webpack-test/configCases/context-exclusion/simple/test.filter.js
  tests/webpack-test/configCases/context-replacement/a/test.filter.js
  tests/webpack-test/configCases/context-replacement/d/test.filter.js
  tests/webpack-test/configCases/css/async-chunk-node/index.js
  tests/webpack-test/configCases/css/async-chunk-node/test.filter.js
  tests/webpack-test/configCases/css/basic-esm-target-web/test.filter.js
  tests/webpack-test/configCases/css/contenthash/test.filter.js
Labels: team

#10308 fix: not evaluate `typeof __dirname` when set to false
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  tests/webpack-test/configCases/parsing/issue-9042/index.js
  tests/webpack-test/configCases/parsing/issue-9042/test.filter.js
Labels: team, release: bug fix

#10313 fix: test no setTimeout
  tests/webpack-test/ConfigTestCases.template.js
Labels: team, release: bug fix

#10268 feat: compilation.addEntry support
  crates/node_binding/binding.d.ts
  crates/node_binding/src/compilation/mod.rs
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack-test-tools/tests/configCases/compilation/add-entry/bar.js
  packages/rspack-test-tools/tests/configCases/compilation/add-entry/foo.js
  packages/rspack-test-tools/tests/configCases/compilation/add-entry/index.js
  packages/rspack-test-tools/tests/configCases/compilation/add-entry/rspack.config.js
  packages/rspack-test-tools/tests/configCases/compilation/add-entry/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
Labels: release: feature

#10316 fix: `dataWebpackPrefix` of load script runtime module
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  tests/webpack-test/cases/parsing/context/errors.js
  tests/webpack-test/cases/parsing/context/test.filter.js
  tests/webpack-test/cases/parsing/context/warnings.js
  tests/webpack-test/cases/parsing/es2020/test.filter.js
  tests/webpack-test/cases/parsing/nullish-coalescing/test.filter.js
  tests/webpack-test/configCases/errors/entry-not-found/errors.js
  tests/webpack-test/configCases/errors/entry-not-found/test.filter.js
  tests/webpack-test/configCases/filename-template/split-chunks-filename/test.filter.js
  tests/webpack-test/configCases/loaders/#-issue-14755-#/test.filter.js
  tests/webpack-test/configCases/plugins/define-plugin-bigint/test.filter.js
  tests/webpack-test/configCases/web/attach-existing/test.filter.js
  tests/webpack-test/configCases/web/unique-jsonp/test.filter.js
Labels: team, release: bug fix

#10318 feat: support `include` and `exclude` of `import.meta.webpackContext`
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  tests/webpack-test/cases/chunks/weak-dependencies/index.js
  tests/webpack-test/cases/chunks/weak-dependencies/test.filter.js
  tests/webpack-test/cases/context/import-meta-webpack-context/test.filter.js
  tests/webpack-test/cases/loaders/no-string/errors.js
  tests/webpack-test/cases/loaders/no-string/test.filter.js
  tests/webpack-test/cases/nonce/set-nonce/test.filter.js
  tests/webpack-test/cases/optimize/side-effects-reexport-start-unknown/test.filter.js
  tests/webpack-test/configCases/entry/depend-on-bug/test.filter.js
  tests/webpack-test/configCases/entry/depend-on-non-js/test.filter.js
  tests/webpack-test/configCases/entry/depend-on-non-js/webpack.config.js
  tests/webpack-test/configCases/parsing/issue-14720/test.filter.js
  tests/webpack-test/configCases/source-map/relative-source-map-path/test.filter.js
  tests/webpack-test/configCases/source-map/relative-source-maps-by-loader/test.filter.js
  tests/webpack-test/configCases/split-chunks-common/hot/test.filter.js
  tests/webpack-test/configCases/split-chunks/custom-filename-function/test.filter.js
  tests/webpack-test/configCases/split-chunks/issue-11513/test.filter.js
Labels: team, release: feature

#10293 chore: bump SWC to v23.2.0 and remove swc_parallel
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_javascript_compiler/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
Labels: team

#10312 feat(swc): enhance TransformOutput with diagnostics
  crates/rspack_javascript_compiler/src/compiler/mod.rs
  crates/rspack_javascript_compiler/src/compiler/stringify.rs
  crates/rspack_javascript_compiler/src/compiler/transform.rs
  crates/rspack_loader_swc/src/lib.rs
Labels: team, release: feature

#10290 feat(create-rspack): better default browserslist target
  packages/create-rspack/template-react-js/rspack.config.mjs
  packages/create-rspack/template-react-ts/rspack.config.ts
  packages/create-rspack/template-vanilla-js/rspack.config.mjs
  packages/create-rspack/template-vanilla-ts/rspack.config.ts
  packages/create-rspack/template-vue-js/rspack.config.mjs
  packages/create-rspack/template-vue-ts/rspack.config.ts
Labels: release: feature

#10325 fix: simplify trace implementation by removing unused code
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/build/profile/profile.test.ts
  packages/rspack-cli/tests/utils/test-utils.ts
Labels: team, release: bug fix

#10304 fix(template-react-ts): work with newer Node
  packages/create-rspack/template-react-js/package.json
  packages/create-rspack/template-react-js/rspack.config.mjs
  packages/create-rspack/template-react-ts/package.json
  packages/create-rspack/template-react-ts/rspack.config.ts
  packages/create-rspack/template-vue-js/rspack.config.mjs
  packages/create-rspack/template-vue-ts/rspack.config.ts
  packages/rspack-test-tools/package.json
  pnpm-lock.yaml
  tests/bench/package.json
  tests/e2e/package.json
Labels: release: bug fix

#10230 chore: remove unnecessary asset info setting
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
Labels: team

#10314 fix(core): fix relative http import failed
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_loader_runner/src/content.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri/mod.rs
  packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
  tests/webpack-examples/build-http/webpack.config.js
Labels: team, release: bug fix

#10332 fix(wasm): avoid passing fd across threads
  crates/rspack_tracing/src/chrome.rs
  crates/rspack_tracing_chrome/src/lib.rs
Labels: release: bug fix

#10331 fix: compile time evaluation of `__filename`
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  tests/webpack-test/cases/loaders/utils/test.filter.js
Labels: team, release: bug fix

#10338 docs: add tree shaking prerequisites and pure annotation
  website/docs/en/config/experiments.mdx
  website/docs/en/guide/optimization/tree-shaking.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/guide/optimization/tree-shaking.mdx
Labels: team, release: document

#10326 feat: JS API can access buildInfo.assets
  crates/node_binding/binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/src/allocator.rs
  crates/node_binding/src/build_info.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/concatenated_module.rs
  crates/node_binding/src/modules/context_module.rs
  crates/node_binding/src/modules/external_module.rs
  crates/node_binding/src/modules/macros.rs
  crates/node_binding/src/modules/normal_module.rs
  crates/rspack_core/src/binding/cell.rs
  crates/rspack_core/src/binding/napi_allocator.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/module.rs
  packages/rspack-test-tools/tests/configCases/module/build-info/loader.js
  packages/rspack-test-tools/tests/configCases/module/build-info/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
Labels: team, release: feature

#10336 fix(wasm): copy data to `ArrayBuffer` when decoding `SharedArrayBuffer`
  packages/rspack/src/loader-runner/utils.ts
Labels: release: bug fix

#10334 feat(compiler-builder): support `browserslist` as the target
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/browserslist_target.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack/src/builder/snapshots/rspack__builder__browserslist_target__tests__browserslist_targets_snapshots.snap
  crates/rspack/src/builder/target.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
Labels: team, release: feature

#10330 chore: release v1.3.10
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10341 fix(core): remove filename fn in sync js api
  crates/node_binding/binding.d.ts
  crates/node_binding/src/compilation/mod.rs
  packages/rspack/src/Compilation.ts
  packages/rspack/src/RspackError.ts
  packages/rspack/src/Stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
Labels: team, release: bug fix

#10348 perf: skip UTF-8 validation if JS loader returned a string
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/node_binding/src/plugins/js_loader/scheduler.rs
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: performance

#10354 docs: fix render of note title and file name
  website/docs/en/config/experiments.mdx
  website/docs/en/config/externals.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/externals.mdx
Labels: release: document

#10346 refactor: use OwnedOrRef instead of #[cacheable(as=...)]
  crates/rspack_cacheable/src/lib.rs
  crates/rspack_cacheable/src/utils/mod.rs
  crates/rspack_cacheable/src/utils/owned_or_ref.rs
  crates/rspack_cacheable/src/with/as_owned.rs
  crates/rspack_cacheable/src/with/inline.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/mod.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/mod.rs
  crates/rspack_cacheable_test/tests/with/as_owned.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_macros/src/cacheable/args.rs
  crates/rspack_macros/src/cacheable/impl_as.rs
  crates/rspack_macros/src/cacheable/impl_disable.rs
  crates/rspack_macros/src/cacheable/mod.rs
Labels: team

#10349 fix: AMD parser plugin replaced define plugin values mutiple times
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs
  tests/webpack-test/configCases/parsing/issue-8293/test.filter.js
Labels: team, release: bug fix

#10363 feat: support full options for EvalSourceMapDevToolPlugin
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/mod.rs
  crates/node_binding/src/raw_options/raw_devtool.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/EvalSourceMapDevToolPlugin.ts
  packages/rspack/src/builtin-plugin/SourceMapDevToolPlugin.ts
Labels: team, release: feature

#10362 chore: add complexity tracing for ensure_chunk_conditions plugin
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
Labels: team

#10370 docs: fix typos in zh/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: document

#10368 docs: clarify the parallelCodeSplitting and removeAvailableModules options
  website/docs/en/config/experiments.mdx
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#10360 fix: improve inner graph assignment analysis
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-10005/warnings.js
  tests/webpack-test/configCases/inner-graph/class/test.filter.js
  tests/webpack-test/configCases/inner-graph/const/test.filter.js
  tests/webpack-test/configCases/inner-graph/varNotWritten/test.filter.js
  tests/webpack-test/configCases/inner-graph/varWritten/test.filter.js
Labels: team, release: bug fix

#10366 docs: add examples for Rule conditions
  website/docs/en/config/module.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/optimization/tree-shaking.mdx
Labels: team, release: document

#10371 fix: inner graph block scopes
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/state.rs
  crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs
  tests/webpack-test/configCases/inner-graph/blockScopes/test.filter.js
Labels: team, release: bug fix

#10235 feat: CssChunkingPlugin
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/css_chunking.rs
  crates/node_binding/src/raw_options/raw_builtins/mod.rs
  crates/rspack_plugin_css_chunking/Cargo.toml
  crates/rspack_plugin_css_chunking/LICENSE
  crates/rspack_plugin_css_chunking/src/lib.rs
  packages/rspack/scripts/check-documentation-coverage.ts
  packages/rspack/src/builtin-plugin/CssChunkingPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
Labels: team, release: feature

#10373 fix: dynamic import json with default name
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  tests/webpack-test/cases/chunks/destructuring-assignment/test.filter.js
  tests/webpack-test/configCases/web/fetch-priority/index.js
  tests/webpack-test/configCases/web/fetch-priority/test.filter.js
  tests/webpack-test/configCases/web/fetch-priority/warnings.js
Labels: team, release: bug fix

#10359 fix: the modules order cross render manifest and content hash should be equal
  Cargo.lock
  crates/rspack_plugin_extract_css/Cargo.toml
  crates/rspack_plugin_extract_css/src/plugin.rs
Labels: team, release: bug fix

#10374 fix(core): make build-http compatible with node16
  packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
Labels: team, release: bug fix

#10376 fix(core): fix release panic problem
  crates/rspack_core/src/logger.rs
Labels: team, release: bug fix

#10379 fix: use name instead of identifier in CircularDependencyRspackPlugin
  crates/rspack_plugin_circular_dependencies/src/lib.rs
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/loader.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/stats.err
Labels: release: bug fix

#10381 docs: add Rstest to homepage
  README.zh-CN.md
  pnpm-lock.yaml
  website/components/builtIns/mdx-components.tsx
  website/package.json
  website/theme/components/Landingpage/ToolStack/index.tsx
  website/theme/components/Landingpage/WhyRspack/index.tsx
  website/theme/i18n/enUS.ts
  website/theme/i18n/zhCN.ts
  website/theme/pages/index.tsx
Labels: team, release: document

#10377 fix: emit warning when optional dynamic import missing
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/dynamic-import-non-exist-module/stats.err
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/cases/runtime/missing-module-exception-dynamic-import/test.filter.js
  tests/webpack-test/configCases/asset-modules/entry-with-runtimeChunk/test.filter.js
  tests/webpack-test/configCases/library/issue-18951/test.filter.js
  tests/webpack-test/configCases/parsing/bom/test.filter.js
  tests/webpack-test/configCases/parsing/url-ignore/test.filter.js
  tests/webpack-test/configCases/target/amd-container-named/index.js
  tests/webpack-test/configCases/target/amd-container-named/test.filter.js
  tests/webpack-test/configCases/target/amd-container-unnamed/index.js
  tests/webpack-test/configCases/target/amd-container-unnamed/test.filter.js
  tests/webpack-test/configCases/target/amd-container-unnamed/webpack.config.js
  tests/webpack-test/configCases/target/amd-named/index.js
  tests/webpack-test/configCases/target/amd-named/test.filter.js
  tests/webpack-test/configCases/target/amd-unnamed/index.js
  tests/webpack-test/configCases/target/amd-unnamed/test.filter.js
  tests/webpack-test/configCases/target/amd-unnamed/webpack.config.js
  tests/webpack-test/configCases/target/umd-auxiliary-comments-object/index.js
  tests/webpack-test/configCases/target/umd-auxiliary-comments-object/test.filter.js
  tests/webpack-test/configCases/target/umd-auxiliary-comments-string/index.js
  tests/webpack-test/configCases/target/umd-auxiliary-comments-string/test.filter.js
Labels: team, release: bug fix

#10345 perf: scan scope idents parallel for concate module
  crates/rspack_core/src/concatenated_module.rs
Labels: team, release: performance

#10386 fix: chunk format runtime with entry starts with slash
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  packages/rspack-test-tools/src/test/creator.ts
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/configCases/asset-modules/build-http/test.filter.js
  tests/webpack-test/configCases/asset-modules/only-entry/test.filter.js
  tests/webpack-test/configCases/cache-filesystem/multicompiler-mode-cache-3/test.filter.js
  tests/webpack-test/configCases/cache-filesystem/multicompiler-mode-cache-4/test.filter.js
  tests/webpack-test/configCases/chunk-index/issue-18008/test.filter.js
  tests/webpack-test/configCases/clean/lib-manifest-plugin/test.filter.js
  tests/webpack-test/configCases/runtime/dynamic-nested-with-deep-entries-commonjs/test.filter.js
  tests/webpack-test/configCases/runtime/dynamic-nested-with-deep-entries-esm/test.filter.js
  tests/webpack-test/configCases/runtime/dynamic-with-deep-entries-commonjs/test.filter.js
  tests/webpack-test/configCases/runtime/dynamic-with-deep-entries-esm/test.filter.js
  tests/webpack-test/configCases/runtime/single-with-deep-entries-commonjs/test.filter.js
  tests/webpack-test/configCases/runtime/single-with-deep-entries-esm/test.filter.js
  tests/webpack-test/configCases/target/universal/index.js
  tests/webpack-test/configCases/target/universal/test.filter.js
  tests/webpack-test/configCases/types/filesystems/test.filter.js
  tests/webpack-test/hotCases/css/fetch-priority/test.filter.js
  tests/webpack-test/package.json
  tests/webpack-test/watchCases/cache/loader-import-module-progress/test.filter.js
  tests/webpack-test/watchCases/cache/loader-load-module-progress/test.filter.js
  tests/webpack-test/watchCases/cache/max-generation/test.filter.js
Labels: team, release: bug fix

#10390 feat(core): add tracing for javascript plugin
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-set.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-set.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/src/Compiler.ts
  packages/rspack/src/trace/index.ts
  packages/rspack/src/trace/traceHookPlugin.ts
Labels: team, release: feature

#10388 fix: css local ident name with empty unique name
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic-include/__snapshot__/bundle0.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-auto/__snapshot__/index.module.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-composes-preprocessers/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-composes-sass/__snapshot__/index.scss.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-composes/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-dedupe/__snapshot__/source.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-exports-only/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-locals-convention-camelCase/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-locals-convention-camelCaseOnly/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-locals-convention-dashes/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-pseudo/__snapshot__/index.css.txt
  packages/rspack-test-tools/tests/configCases/builtins/css-modules-simple/__snapshot__/index.module.css.txt
  packages/rspack-test-tools/tests/configCases/css/override-exports/index.js
  packages/rspack-test-tools/tests/configCases/mangle-exports/skipping-mangle-css-modules/index.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack-test-tools/tests/hotCases/css/css-modules/__snapshots__/web/1.snap.txt
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/css/build-http/test.filter.js
  tests/webpack-test/configCases/css/cjs-module-syntax/index.js
  tests/webpack-test/configCases/css/css-auto/index.js
  tests/webpack-test/configCases/css/css-auto/test.filter.js
  tests/webpack-test/configCases/css/css-modules-in-node/test.filter.js
  tests/webpack-test/configCases/css/css-modules-no-space/test.filter.js
  tests/webpack-test/configCases/css/css-modules-no-space/warnings.js
  tests/webpack-test/configCases/css/css-modules/test.filter.js
  tests/webpack-test/configCases/css/css-types/index.js
  tests/webpack-test/configCases/css/css-types/test.filter.js
  tests/webpack-test/configCases/css/css-types/webpack.config.js
  tests/webpack-test/configCases/css/default-exports-parser-options/index.js
  tests/webpack-test/configCases/css/exports-convention/test.filter.js
  tests/webpack-test/configCases/css/exports-in-node/index.js
  tests/webpack-test/configCases/css/exports-in-node/test.filter.js
  tests/webpack-test/configCases/css/exports-only-generator-options/index.js
  tests/webpack-test/configCases/css/exports-only-generator-options/test.config.js
  tests/webpack-test/configCases/css/exports-only-generator-options/test.filter.js
  tests/webpack-test/configCases/css/exports-only-generator-options/webpack.config.js
  tests/webpack-test/configCases/css/import-at-middle/test.filter.js
  tests/webpack-test/configCases/css/import/test.filter.js
  tests/webpack-test/configCases/css/named-exports-parser-options/index.js
  tests/webpack-test/configCases/css/no-extra-runtime-in-js/test.filter.js
  tests/webpack-test/hotCases/css/css-modules/index.js
Labels: team, release: bug fix

#10392 test: fix snapshot of main branch
  packages/rspack-test-tools/tests/errorCases/error-test-set-with-index.js
Labels: team

#10394 test: upload build http lock files in example
  tests/webpack-examples/build-http/rspack.lock
  tests/webpack-examples/build-http/rspack.lock.data/https___cdn.esm.sh/_p-map@7.0.3_es2022_p-map_f7200de247a6b3ebaf2b.mjs
  tests/webpack-examples/build-http/rspack.lock.data/https___cdn.esm.sh/_p-map_9dd32c023fd5f3d3e7f2
  tests/webpack-examples/build-http/rspack.lock.data/https___cdn.skypack.dev/_-_p-map@v7.0.3-39IW5BbvyTmGh858LQn2_dist=es2019,mode=imports_optimized_p-map_dc06ffec2bc56bff7a0c.js
  tests/webpack-examples/build-http/rspack.lock.data/https___cdn.skypack.dev/_p-map_85ed609042d47e169edd
  tests/webpack-examples/build-http/rspack.lock.data/https___jspm.dev/_npm_p-map@7.0_7fb8d9d09e35352d9f60.0
  tests/webpack-examples/build-http/rspack.lock.data/https___jspm.dev/_p-map_875efed0b6bd20646dd2
  tests/webpack-examples/build-http/rspack.lock.data/https___unpkg.com/_p-map-series@3.0.0_index_module_cb329557880410b778cf.js
Labels: team

#10395 docs: remove duplicate undefined types
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/DefinePlugin.ts
  website/docs/en/plugins/webpack/define-plugin.mdx
  website/docs/zh/plugins/webpack/define-plugin.mdx
Labels: team, release: document

#10391 fix: assets imported by css should not generate js modules
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css_chunking/src/lib.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_externals/src/plugin.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/css/no-extra-runtime-in-js/test.filter.js
Labels: team, release: bug fix

#10399 chore: run duplicate version check in ci
  .github/workflows/ci-rust.yaml
  deny.toml
Labels: team

#10389 docs: simplify the description of optimization.sideEffects
  website/docs/en/config/optimization.mdx
  website/docs/en/guide/optimization/tree-shaking.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/guide/optimization/tree-shaking.mdx
Labels: team, release: document

#10397 chore: CI build wasm in runner directly
  .github/workflows/reusable-build-build.yml
Labels: team

#10401 fix: missing destucturing properties while getting referenced exports
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack-test-tools/tests/treeShakingCases/cyclic-reference-export-all/__snapshots__/treeshaking.snap.txt
  tests/webpack-test/cases/errors/case-sensitive/test.filter.js
  tests/webpack-test/cases/errors/import-module-cycle-multiple/test.filter.js
  tests/webpack-test/cases/errors/import-module-cycle/test.filter.js
  tests/webpack-test/cases/parsing/harmony-destructuring-assignment/test.filter.js
Labels: team, release: bug fix

#10400 chore: 🔧 prettier yaml files
  .github/workflows/ci-lint.yaml
  .github/workflows/ci.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/release-otp.yml
  lint-staged.config.mjs
Labels: team

#10387 docs(rspress): upgrade to Rspress v2.0.0-beta.6
  pnpm-lock.yaml
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/testing-rspack.mdx
  website/package.json
  website/project-words.txt
  website/rspress.config.ts
Labels: team, release: document

#10407 fix: missing module header info of css modules
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/src/raw_options/raw_builtins/mod.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/plugin/drive.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_module_info_header/Cargo.toml
  crates/rspack_plugin_module_info_header/LICENSE
  crates/rspack_plugin_module_info_header/src/lib.rs
  packages/rspack-test-tools/tests/configCases/build-http/css/__snapshot__/bundle0.css.txt
  packages/rspack-test-tools/tests/configCases/css/export-selector/__snapshot__/imported_js.bundle0.css.txt
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/chunk-index/recalc-index/test.filter.js
  tests/webpack-test/configCases/container/reference-hoisting/test.filter.js
  tests/webpack-test/configCases/container/track-initial-chunks/test.filter.js
  tests/webpack-test/configCases/contenthash/css-generator-options/test.config.js
  tests/webpack-test/configCases/contenthash/css-generator-options/test.filter.js
  tests/webpack-test/configCases/contenthash/css-generator-options/webpack.config.js
  tests/webpack-test/configCases/contenthash/module-ids-size/test.filter.js
  tests/webpack-test/configCases/css/pathinfo/test.config.js
  tests/webpack-test/configCases/css/pathinfo/test.filter.js
Labels: team, release: bug fix

#10411 docs: invite @quininer to Rspack core team
  website/components/RandomMemberList.tsx
  website/project-words.txt
Labels: team, release: document

#10398 fix: normalize CopyRspackPlugins's transform function in js side
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/index.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/src/test-async-fn.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/src/test-async-obj.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/src/test-sync-fn.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/src/test-sync-obj.txt
  packages/rspack/src/builtin-plugin/CopyRspackPlugin.ts
Labels: release: bug fix

#10414 docs: update docs, remove unused useBuiltins
  website/docs/en/blog/announcing-0-3.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/en/guide/tech/typescript.mdx
  website/docs/zh/blog/announcing-0-3.mdx
  website/docs/zh/guide/tech/typescript.mdx
Labels: release: document

#10418 docs: introducing Compilation and Compiler objects
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/en/api/plugin-api/index.mdx
  website/docs/zh/api/javascript-api/compilation.mdx
  website/docs/zh/api/javascript-api/compiler.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/plugin-api/index.mdx
Labels: team, release: document

#10420 fix(cli): upgrade @rspack/dev-server
  packages/rspack-cli/package.json
  pnpm-lock.yaml
  tests/e2e/package.json
Labels: team, release: bug fix

#10416 fix: CopyRspackPlugin's transformer function should handle Buffer input
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/rspack.config.js
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: release: bug fix

#10424 docs: update Rstack introduction
  .vscode/settings.json
  README.md
  README.zh-CN.md
  pnpm-lock.yaml
  website/docs/en/guide/start/ecosystem.mdx
  website/docs/zh/guide/start/ecosystem.mdx
  website/package.json
  website/theme/components/HomeFooter/index.tsx
  website/theme/i18n/enUS.ts
  website/theme/i18n/zhCN.ts
Labels: team, release: document

#10405 fix(minify): parser allow import attributes syntax
  crates/rspack_javascript_compiler/src/compiler/minify.rs
  packages/rspack-test-tools/tests/configCases/plugins/minify-parser/importAttributes.mjs
  packages/rspack-test-tools/tests/configCases/plugins/minify-parser/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-parser/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-parser/test.config.js
Labels: team, release: bug fix

#10415 chore: release v1.3.11
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10439 fix: set compilation errors result is wrong
  crates/node_binding/binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/src/compilation/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack-test-tools/tests/configCases/compilation/errors/index.js
  packages/rspack-test-tools/tests/configCases/compilation/errors/loader.js
  packages/rspack-test-tools/tests/configCases/compilation/errors/rspack.config.js
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#10443 fix: eval sourcemap debugids
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_devtool/src/generate_debug_id.rs
  crates/rspack_plugin_devtool/src/lib.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  tests/webpack-test/configCases/source-map/eval-source-map-debugids/test.filter.js
  tests/webpack-test/configCases/target/system-named-assets-path/test.filter.js
Labels: team, release: bug fix

#10435 feat(swc_compiler_api): add diagnostics field to TransformOutput
  crates/node_binding/binding.d.ts
  crates/node_binding/src/swc.rs
  packages/rspack/etc/core.api.md
Labels: team, release: feature

#10445 refactor: avoid read rust side json in js side
  crates/rspack_tracing_chrome/src/lib.rs
  packages/rspack/src/trace/index.ts
Labels: team

#10438 fix: swc compiler api using wasm plugin without tokio runtime panic.
  crates/node_binding/src/swc.rs
  packages/rspack-test-tools/tests/compilerCases/swc-api.js
Labels: team, release: bug fix

#9832 docs: improve devtool docs
  website/docs/en/config/devtool.mdx
  website/docs/zh/config/devtool.mdx
Labels: team, release: document

#10450 fix: missing import scripts runtime when target is webworker
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading.ejs
  tests/webpack-test/configCases/runtime/target-webworker/test.filter.js
Labels: team, release: bug fix

#10449 test: enable more webpack test cases
  packages/rspack/src/config/adapterRuleUse.ts
  tests/webpack-test/configCases/custom-hash-function/debug-hash/test.filter.js
  tests/webpack-test/configCases/loaders-and-plugins-falsy/basic/test.filter.js
  tests/webpack-test/configCases/mangle/mangle-with-destructuring-assignment/index.js
  tests/webpack-test/configCases/mangle/mangle-with-destructuring-assignment/test.filter.js
  tests/webpack-test/configCases/optimization/issue-19184/test.filter.js
  tests/webpack-test/configCases/records/with-readRecords-hook/test.filter.js
  tests/webpack-test/configCases/resolve/function-plugins/test.filter.js
  tests/webpack-test/configCases/resolve/unsafe-cache-proxy/test.filter.js
  tests/webpack-test/configCases/rule-set/oneOf/test.filter.js
  tests/webpack-test/statsCases/split-chunks-dedup/test.filter.js
  tests/webpack-test/statsCases/split-chunks-dedup/webpack.config.js
  tests/webpack-test/statsCases/track-returned/test.filter.js
Labels: team

#10453 chore: add rspack_version and options to tracing
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/src/lib.rs
Labels: team

#10454 docs(rspress): use @rspress/plugin-algolia for search
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
  website/theme/index.tsx
Labels: team, release: document

#10455 fix(core): fix tracing async exit early
  packages/rspack/src/exports.ts
  packages/rspack/src/trace/index.ts
Labels: team, release: bug fix

#10365 fix: loader in module user request should be resolved path
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/utils/identifier.rs
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/cases/loaders/no-string/errors.js
Labels: team, release: bug fix

#10463 docs: add info option and JSDoc for copy plugin
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/CopyRspackPlugin.ts
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: team, release: document

#10464 fix(core): remove Node 10 compatibility code
  packages/rspack/src/util/bindingVersionCheck.ts
Labels: team, release: bug fix

#10465 perf: lazy load watchpack and some Node built-in modules
  packages/rspack/src/ExecuteModulePlugin.ts
  packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
  packages/rspack/src/node/NodeWatchFileSystem.ts
Labels: team, release: performance

#10471 fix: http build redirect to another url
  crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri/mod.rs
  packages/rspack-test-tools/tests/configCases/build-http/redirect/index.js
  packages/rspack-test-tools/tests/configCases/build-http/redirect/lock-files/lock.json
  packages/rspack-test-tools/tests/configCases/build-http/redirect/lock-files/test/https___raw.githubusercontent.com/_web-infra-dev_rspack_main_packages_rspack-test-tools_tests_configCases_asset__images_file_5fb8a694480bf741d1b4.png
  packages/rspack-test-tools/tests/configCases/build-http/redirect/rspack.config.js
Labels: team, release: bug fix

#10473 refactor: rename TaskType::Sync to Main & TaskType::Async to background
  crates/rspack_core/src/compiler/make/repair/add.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/utils/task_loop.rs
Labels: team

#10472 fix: check directory before reading when running clean options
  crates/rspack_core/src/utils/fs_trim.rs
Labels: team, release: bug fix

#10482 docs: Add Miro into the list of consumers
  website/project-words.txt
  website/theme/components/Landingpage/WhoIsUsing/assets/miro.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: release: document

#10488 refactor: rename some enums of exports info
  crates/node_binding/src/module_graph.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/static_exports_dependency.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_plugin_asset/src/asset_exports_dependency.rs
  crates/rspack_plugin_css/src/dependency/export.rs
  crates/rspack_plugin_css/src/dependency/local_ident.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_json/src/json_exports_dependency.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
Labels: team

#10480 perf: Use ustr for RuntimeSpec
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/src/chunk_graph.rs
  crates/node_binding/src/compilation/code_generation_results.rs
  crates/node_binding/src/exports_info.rs
  crates/node_binding/src/module_graph.rs
  crates/rspack_cacheable/src/with/as_ref_str.rs
  crates/rspack_collections/src/identifier.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports_info.rs
  crates/rspack_core/src/runtime.rs
  crates/rspack_core/src/utils/runtime.rs
  crates/rspack_plugin_dll/src/flag_all_modules_as_used_plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
Labels: release: performance

#10499 refactor: optimize module executor error info
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/compiler/module_executor/module_tracker.rs
Labels: team

#10498 fix: should render name by chunk id when chunk name is empty
  crates/rspack_core/src/options/filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/rspack.config.js
Labels: team, release: bug fix

#10500 fix: wrong warning sort
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: release: bug fix

#10489 feat(rstest_plugin): handle import.meta.dirname and import.meta.filename
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/rstest/index.js
  packages/rspack-test-tools/tests/configCases/plugins/rstest/src/bar.js
  packages/rspack-test-tools/tests/configCases/plugins/rstest/src/baz.js
  packages/rspack-test-tools/tests/configCases/plugins/rstest/src/foo.js
  packages/rspack-test-tools/tests/configCases/plugins/rstest/src/index.js
Labels: team, release: feature

#10505 chore: bench record chunk group
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
  tests/bench/ts-react.bench.ts
Labels: team

#10497 refactor: split code of exports info
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/mod.rs
  crates/rspack_core/src/exports/utils.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
Labels: team

#10511 test: add benchmark prefixes based on its location
  tasks/benchmark/benches/groups/basic_build.rs
  tasks/benchmark/benches/groups/build_chunk_graph.rs
  tests/bench/package.json
  tests/bench/ts-react.bench.ts
Labels: team

#10513 perf: js api resolver.resolve
  crates/node_binding/binding.d.ts
  crates/node_binding/src/resolver.rs
  packages/rspack-test-tools/tests/configCases/resolver/resolve/index.js
  packages/rspack-test-tools/tests/configCases/resolver/resolve/rspack.config.js
  packages/rspack/src/Resolver.ts
Labels: team, release: performance

#10507 refactor: remove module graph param of export info setters
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/export_info_setter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
Labels: team

#10403 feat(core): support dump chunk graph as graphviz
  Cargo.toml
  crates/rspack_core/src/chunk_graph/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_util/src/env.rs
  crates/rspack_util/src/lib.rs
Labels: team, release: feature

#10509 fix: align tsconfig paths matching with tsconfig-paths-webpack-plugin
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#10525 fix: don't panic for esm hmr
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
Labels: team, release: bug fix

#10528 perf: use js api to access module.resourceResolveData
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/macros.rs
  crates/node_binding/src/modules/normal_module.rs
  crates/node_binding/src/resource_data.rs
  crates/rspack_core/src/normal_module.rs
Labels: team, release: performance

#10526 fix: module_executor circular check only for internal modules
  crates/rspack_core/src/compiler/module_executor/entry.rs
  crates/rspack_core/src/compiler/module_executor/module_tracker.rs
  packages/rspack-test-tools/tests/configCases/loader-import-module/cycle-dependency/loader.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/index.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/loader.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/value.js
Labels: team, release: bug fix

#10517 perf: resource data in js loader context
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/js_loader/context.rs
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: performance

#10527 docs: clarify `target` default value and browserslist usage
  website/docs/en/config/target.mdx
  website/docs/zh/config/target.mdx
  website/project-words.txt
Labels: team, release: document

#10529 chore(ci): add release debug workflow
  .github/workflows/release-canary.yml
  .github/workflows/release-debug.yml
  .github/workflows/reusable-build-all.yml
  scripts/release/version.mjs
Labels: team

#10531 feat: support dependences in build info
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/build_info.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/macros.rs
  packages/rspack-test-tools/tests/configCases/module/build-info/build.txt
  packages/rspack-test-tools/tests/configCases/module/build-info/loader.js
  packages/rspack-test-tools/tests/configCases/module/build-info/rspack.config.js
  packages/rspack/src/Module.ts
Labels: team, release: feature
