Repository web-infra-dev/rspack, pull requests merged in 2025-04, with the labels that each got.

#9845 fix: should remove all sub chunks if chunk is removed
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
Labels: team, release: bug fix

#9860 fix(deps): update @rspack/dev-server to v1.1.1
  packages/rspack-cli/package.json
  pnpm-lock.yaml
  tests/e2e/package.json
Labels: team, release: bug fix

#9859 refactor: improve storage error and result
  crates/rspack_storage/src/fs/error.rs
  crates/rspack_storage/src/fs/mod.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/strategy/split/handle_file.rs
  crates/rspack_storage/src/pack/strategy/split/read_pack.rs
  crates/rspack_storage/src/pack/strategy/split/read_scope.rs
  crates/rspack_storage/src/pack/strategy/split/validate_scope.rs
  crates/rspack_storage/src/pack/strategy/split/write_pack.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  crates/rspack_storage/tests/expire.rs
  crates/rspack_storage/tests/lock.rs
  crates/rspack_storage/tests/multi.rs
  crates/rspack_storage/tests/release.rs
Labels: team

#9862 fix: eval source map panic at getting codegen results
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/drive.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map-multi-runtime/a.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map-multi-runtime/b.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map-multi-runtime/lib.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map-multi-runtime/rspack.config.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map-multi-runtime/test.config.js
Labels: team, release: bug fix

#9868 test: fix cjs js api tests
  packages/rspack-cli/tests/api/type/js-api-cjs.test.ts
Labels: team

#9869 test: fix unexpected missing errors and warnings
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/tests/configCases/compilation/add-include/errors.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/loader-in-worker.js
  packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/2/warnings.js
  packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/2/warnings.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/util/index.ts
Labels: team

#9865 chore: release v1.3.1
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9882 docs: invite @CPunisher to Rspack core team
  website/components/RandomMemberList.tsx
  website/docs/en/misc/planning/roadmap.mdx
  website/docs/en/misc/team/core-team.mdx
  website/docs/en/misc/team/emeriti.mdx
  website/docs/zh/misc/planning/roadmap.mdx
  website/docs/zh/misc/team/core-team.mdx
  website/docs/zh/misc/team/emeriti.mdx
Labels: team, release: document

#9866 refactor: convert result with message
  crates/node_binding/src/compilation/mod.rs
  crates/node_binding/src/error.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/js_cleanup_plugin.rs
  crates/node_binding/src/plugins/js_loader/resolver.rs
  crates/node_binding/src/raw_options/raw_builtins/mod.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_core/src/runtime_template.rs
  crates/rspack_error/src/convert.rs
  crates/rspack_loader_lightningcss/src/config.rs
  crates/rspack_loader_lightningcss/src/lib.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_napi/src/errors.rs
  crates/rspack_napi/src/lib.rs
  crates/rspack_napi/src/threadsafe_function.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_html/src/template.rs
  crates/rspack_plugin_schemes/src/file_uri.rs
  crates/rspack_plugin_schemes/src/http_uri/mod.rs
  crates/rspack_storage/src/fs/mod.rs
Labels: team

#9883 test(loader-parallel): test `parallel-option` would only recieve `true` in parallel mode
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
Labels: team

#9884 feat(loader-parallel): support more `LoaderContext` APIs in parallel loader
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/app-proxy.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/app.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/foo.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/colors.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/file.jpg
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/file.png
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/other-stylesheet.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/stylesheet.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/execute-failed/import-loader-2.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/execute-failed/import-loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/execute-failed/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/execute-failed/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/a.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/convert-loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/empty.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/import-loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/source-loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/bar.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/bar.js.macro
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/entry.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/index.js.macro
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/with-layer/banner.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/with-layer/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/with-layer/loader.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/with-layer/rspack.config.js
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/service.ts
  packages/rspack/src/loader-runner/worker.ts
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: feature

#9888 feat(loader-parallel): support `LoaderContext.fs` as `node:fs`
  packages/rspack/src/loader-runner/worker.ts
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: feature

#9872 feat: support rspack wasi with node.js
  .cargo/config.toml
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/build.rs
  crates/node_binding/package.json
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/src/lib.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_regex/src/napi.rs
  package.json
Labels: release: feature

#9886 fix: should ensure cache exist when incremental rebuild chunk graph
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  packages/rspack-test-tools/tests/cacheCases/common/basic/rspack.config.js
Labels: team, release: bug fix

#9894 docs: add basic guide for Next.js
  website/docs/en/guide/tech/next.mdx
  website/docs/zh/guide/tech/next.mdx
Labels: team, release: document

#9893 fix: more stable named chunk ids
  crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_ids/src/named_chunk_ids_plugin.rs
  crates/rspack_ids/src/natural_chunk_ids_plugin.rs
  crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/__snapshot__/snapshot.txt
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/index.js
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/module.js
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/cell/index.js
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/cell/package.json
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/row/index.js
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/row/package.json
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/table/index.js
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/table/package.json
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/templater/index.js
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/templater/package.json
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/package.json
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/webpack.config.js
Labels: team, release: bug fix

#9898 fix: multiple runtimeRequirementInTree js hook call
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/runtime.rs
  packages/rspack-test-tools/tests/configCases/hooks/runtime-requirement-in-tree/rspack.config.js
  packages/rspack/src/taps/compilation.ts
Labels: team, release: bug fix

#9892 fix: should merge chunkCreateRoot instead of merge chunks later
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/entry1.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/entry2.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/lib1.css
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/lib1.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/lib2.css
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/lib2.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/rspack.config.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/test.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#9901 fix: should walk for worker args
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  packages/rspack-test-tools/tests/normalCases/worker/specifier-in-worker-args/config.js
  packages/rspack-test-tools/tests/normalCases/worker/specifier-in-worker-args/index.js
  packages/rspack-test-tools/tests/normalCases/worker/specifier-in-worker-args/worker.js
Labels: team, release: bug fix

#9900 chore: release 1.3.2
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9909 feat(wasm): limit tokio `max_blocking_threads` to 1
  crates/node_binding/src/lib.rs
Labels: release: feature

#9919 docs: fix the incorrect parameters used when creating the DevServer
  website/docs/en/blog/announcing-1-3.mdx
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/zh/blog/announcing-1-3.mdx
  website/docs/zh/guide/features/lazy-compilation.mdx
Labels: release: document

#9920 docs: improve Next.js guide
  website/docs/en/blog/announcing-1-3.mdx
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/en/guide/tech/next.mdx
  website/docs/zh/blog/announcing-1-3.mdx
  website/docs/zh/guide/features/lazy-compilation.mdx
  website/docs/zh/guide/tech/next.mdx
Labels: team, release: document

#9921 refactor: remove unused `AsDependency` trait
  crates/rspack_core/src/dependency/cached_const_dependency.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/esm_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
Labels: team

#9926 chore: rollback rust to nightly 2025-03-26
  rust-toolchain.toml
Labels: team

#9927 chore: remove unnecessary linked project
  .vscode/settings.json
Labels: team

#9925 fix(deps): `tinypool` not being able to run on older node versions
  packages/rspack/move-tinypool.js
  packages/rspack/package.json
  packages/rspack/tsconfig.json
  packages/rspack/tsup.config.ts
  pnpm-lock.yaml
Labels: team, release: bug fix

#9863 fix(modern-module): leave non exist dependency to throw on resolve
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/rspack.config.js
Labels: team, release: bug fix

#9936 test: use errors.js to test expected error
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/errors.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/rspack.config.js
Labels: team

#9934 refactor: clean dependency template code
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/dependency/cached_const_dependency.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_plugin_asset/src/asset_exports_dependency.rs
  crates/rspack_plugin_css/src/dependency/export.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/local_ident.rs
  crates/rspack_plugin_css/src/dependency/self_reference.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_define_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_array_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_item_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/local_module_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/unsupported_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_ensure_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/amd_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/context/require_resolve_context_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/esm_accept_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
  crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/url/mod.rs
  crates/rspack_plugin_javascript/src/dependency/worker/create_script_url_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_json/src/json_exports_dependency.rs
  crates/rspack_plugin_library/src/modern_module/import_dependency.rs
  crates/rspack_plugin_library/src/modern_module/reexport_star_external_dependency.rs
Labels: team

#9761 ci: cache support self hosted runner
  .github/actions/artifact/download/action.yml
  .github/actions/artifact/upload/action.yml
  .github/actions/cache/restore/action.yml
  .github/actions/cache/save/action.yml
  .github/actions/debuger/action.yml
  .github/actions/docker/linux-build/action.yml
  .github/actions/docker/run/action.yml
  .github/actions/pnpm/setup/action.yml
  .github/actions/rustup/action.yml
  .github/actions/rustup/cargo/action.yml
  .github/workflows/reusable-build.yml
Labels: team

#9937 docs: redirect rspack.org to rspack.dev
  website/_redirects
Labels: team, release: document

#9924 refactor: add dynamic dependency template implementation
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
Labels: team

#9942 docs: Document content display error in 'experiments.mdx'
  website/docs/zh/config/experiments.mdx
Labels: release: document

#9946 ci: rustup install clippy
  .github/actions/docker/linux-build/action.yml
  .github/actions/pnpm/install-binding-dependencies/action.yml
  .github/actions/rustup/action.yml
Labels: team

#9944 fix: generated name for splitted chunk
  crates/rspack_core/src/chunk.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  packages/rspack-test-tools/tests/configCases/chunks/chunk-file/index.js
  packages/rspack-test-tools/tests/configCases/chunks/chunk-file/node_modules/foo/index.js
  packages/rspack-test-tools/tests/configCases/chunks/chunk-file/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/chunks/chunk-file/rspack.config.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: bug fix

#9957 ci: fix rustup download target failed
  .github/actions/docker/linux-build/action.yml
Labels: team

#9941 ci: split reusable-build.yml
  .github/workflows/ci.yml
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/reusable-build-bench.yml
  .github/workflows/reusable-build-build.yml
  .github/workflows/reusable-build-test.yml
  .github/workflows/reusable-build.yml
Labels: team

#9950 chore: release v1.3.4
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9945 refactor: dynamic templates of javascript esm dependencies
  crates/rspack_core/src/dependency/dependency_template.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_header_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
Labels: team

#9955 perf: js module loaders getter
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/asset.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/external_module.rs
  crates/node_binding/src/modules/normal_module.rs
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/rspack_napi/Cargo.toml
  crates/rspack_napi/src/js_values/mod.rs
  crates/rspack_napi/src/js_values/weak_ref.rs
  crates/rspack_napi/src/lib.rs
  packages/rspack-test-tools/tests/configCases/context-module/module-instance/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/module-instance/rspack.config.js
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js
  tests/bench/ts-react.bench.ts
Labels: team, release: performance

#9960 refactor: dynamic templates of all dependencies
  crates/rspack_core/src/dependency/cached_const_dependency.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
  crates/rspack_plugin_asset/src/asset_exports_dependency.rs
  crates/rspack_plugin_css/src/dependency/export.rs
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/dependency/local_ident.rs
  crates/rspack_plugin_css/src/dependency/self_reference.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_json/src/json_exports_dependency.rs
  crates/rspack_plugin_library/src/modern_module/import_dependency.rs
  crates/rspack_plugin_library/src/modern_module/reexport_star_external_dependency.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
Labels: team

#9963 test: not to print unnecessary message when testing
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/processor/builtin.ts
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/src/processor/defaults.ts
  packages/rspack-test-tools/src/processor/diagnostic.ts
  packages/rspack-test-tools/src/processor/hash.ts
  packages/rspack-test-tools/src/processor/hook.ts
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/src/processor/treeshaking.ts
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
Labels: team

#9962 docs: add rspack & next.js partner annoucement
  website/docs/en/blog/_meta.json
  website/docs/en/blog/index.mdx
  website/docs/en/blog/rspack-next-partner.mdx
  website/project-words.txt
  website/rspress.config.ts
Labels: team, release: document

#9970 docs: add next.js guide to sidebar
  website/docs/en/guide/tech/_meta.json
  website/docs/en/guide/tech/next.mdx
  website/docs/zh/guide/tech/_meta.json
  website/docs/zh/guide/tech/next.mdx
Labels: team, release: document

#9965 chore: use async trace style for chrome tracing
  crates/rspack_tracing/src/chrome.rs
Labels: team

#9973 chore: remove unused scripts
  scripts/alert/discord.js
  scripts/log.js
  scripts/meta/check_is_workspace_root.js
  scripts/meta/setup.js
  scripts/test/binary-path.cjs
  scripts/test/diff-exclude.cjs
  scripts/test/diff.cjs
  scripts/test/math.cjs
  scripts/test/recursive-compare.cjs
Labels: team

#9923 fix: jsonpChunksLoadingWithCallback code format
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.ejs
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/__snapshots__/web/1.snap.txt
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: release: bug fix

#9974 docs: translate Next.js blog to Chinese
  website/docs/en/blog/_meta.json
  website/docs/en/blog/rspack-next-partner.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/guide/tech/next.mdx
  website/docs/zh/blog/_meta.json
  website/docs/zh/blog/index.mdx
  website/docs/zh/blog/rspack-next-partner.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/guide/tech/next.mdx
Labels: team, release: document

#9975 ci: update lynx infra artifact action
  .github/actions/artifact/download/action.yml
  .github/actions/artifact/upload/action.yml
  .github/actions/debugger/action.yml
  .github/actions/pnpm/install-binding-dependencies/action.yml
  .github/actions/pnpm/install-dependencies/action.yml
Labels: team

#9977 docs: improve clarity in documentation
  website/docs/en/api/index.mdx
  website/docs/en/blog/rspack-next-partner.mdx
  website/docs/en/guide/tech/next.mdx
  website/docs/en/plugins/index.mdx
  website/docs/zh/api/index.mdx
  website/docs/zh/blog/rspack-next-partner.mdx
  website/docs/zh/contribute/development/profiling.md
  website/docs/zh/guide/features/lazy-compilation.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/guide/tech/next.mdx
  website/docs/zh/plugins/index.mdx
Labels: team, release: document

#9979 fix: lightningcss loader report error by default
  crates/rspack_loader_lightningcss/src/lib.rs
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-error/errors.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-error/index.css
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-error/index.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-error/rspack.config.js
Labels: team, release: bug fix

#9980 fix: external with properties array list in module format
  crates/rspack_core/src/external_module.rs
  tests/webpack-test/configCases/externals/externals-array/test.filter.js
  tests/webpack-test/configCases/externals/externals-array/webpack.config.js
Labels: team, release: bug fix

#9972 docs: add dependency in glossary
  website/docs/en/misc/glossary.mdx
  website/docs/zh/misc/glossary.mdx
Labels: team, release: document

#9981 fix: external module to pass webpack test cases
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  tests/webpack-test/configCases/externals/async-externals/test.filter.js
  tests/webpack-test/configCases/externals/externals-in-commons-chunk/test.filter.js
  tests/webpack-test/configCases/externals/externals-system-custom/test.filter.js
  tests/webpack-test/configCases/externals/optional-externals-root/test.filter.js
  tests/webpack-test/configCases/externals/optional-externals-umd/test.filter.js
  tests/webpack-test/configCases/externals/optional-externals-umd2-mixed/test.filter.js
  tests/webpack-test/configCases/externals/optional-externals-umd2/test.filter.js
Labels: team, release: bug fix

#9747 feat: adapter rspack-resolver async api
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/js_loader/resolver.rs
  crates/node_binding/src/resolver.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs/src/read.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_plugin_rsdoctor/src/module_graph.rs
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/configCases/chunks/chunk-file/rspack.config.js
  packages/rspack-test-tools/tests/configCases/compilation/emit-asset/rspack.config.js
  tasks/benchmark/Cargo.toml
  tasks/release-check/Cargo.toml
Labels: release: feature

#9990 feat: rspack cacheable noop feature
  crates/rspack_cacheable/src/lib.rs
  crates/rspack_cacheable/src/with/as_preset/rspack_sources/mod.rs
  crates/rspack_cacheable_test/tests/context.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/basic.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/hashable.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/omit_bounds.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/with_attr.rs
  crates/rspack_cacheable_test/tests/macro/cacheable/with_attr_and_generics.rs
  crates/rspack_cacheable_test/tests/macro/cacheable_dyn.rs
  crates/rspack_cacheable_test/tests/macro/disable_cacheable/manual.rs
  crates/rspack_cacheable_test/tests/macro/disable_cacheable/mod.rs
  crates/rspack_cacheable_test/tests/macro/disable_cacheable/with_macro.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable/as_attr.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn.rs
  crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn_with_generics.rs
  crates/rspack_cacheable_test/tests/macro/mod.rs
  crates/rspack_cacheable_test/tests/with/as.rs
  crates/rspack_cacheable_test/tests/with/as_cacheable.rs
  crates/rspack_cacheable_test/tests/with/as_inner.rs
  crates/rspack_cacheable_test/tests/with/as_map.rs
  crates/rspack_cacheable_test/tests/with/as_owned.rs
  crates/rspack_cacheable_test/tests/with/as_preset/camino.rs
  crates/rspack_cacheable_test/tests/with/as_preset/json.rs
  crates/rspack_cacheable_test/tests/with/as_preset/lightningcss.rs
  crates/rspack_cacheable_test/tests/with/as_preset/rspack_resolver.rs
  crates/rspack_cacheable_test/tests/with/as_preset/rspack_sources.rs
  crates/rspack_cacheable_test/tests/with/as_preset/serde_json.rs
  crates/rspack_cacheable_test/tests/with/as_preset/swc.rs
  crates/rspack_cacheable_test/tests/with/as_preset/ustr.rs
  crates/rspack_cacheable_test/tests/with/as_ref_str.rs
  crates/rspack_cacheable_test/tests/with/as_string.rs
  crates/rspack_cacheable_test/tests/with/as_tuple2.rs
  crates/rspack_cacheable_test/tests/with/as_tuple3.rs
  crates/rspack_cacheable_test/tests/with/as_vec.rs
  crates/rspack_cacheable_test/tests/with/inline.rs
  crates/rspack_cacheable_test/tests/with/unsupported.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/dependency/dependency_type.rs
  crates/rspack_macros/src/cacheable/args.rs
  crates/rspack_macros/src/cacheable/impl_disable.rs
  crates/rspack_macros/src/cacheable/mod.rs
  crates/rspack_macros/src/lib.rs
Labels: team, release: feature

#9992 refactor: remove useless code
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
Labels: team

#10004 docs: add a standalone ecosystem page
  pnpm-lock.yaml
  website/components/Tag.scss
  website/components/Tag.tsx
  website/docs/en/guide/start/_meta.json
  website/docs/en/guide/start/ecosystem.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/_meta.json
  website/docs/zh/guide/start/ecosystem.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/package.json
Labels: team, release: document

#9994 chore: add more tracing data
  .gitignore
  .vscode/settings.json
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  crates/rspack_tracing/src/chrome.rs
Labels: team

#9885 feat: resolver restriction support regex
  crates/node_binding/binding.d.ts
  crates/node_binding/src/options/raw_resolve.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_regex/src/lib.rs
  packages/rspack-test-tools/tests/configCases/resolver/restriction/index.js
  packages/rspack-test-tools/tests/configCases/resolver/restriction/node_modules/style/index.css
  packages/rspack-test-tools/tests/configCases/resolver/restriction/node_modules/style/index.js
  packages/rspack-test-tools/tests/configCases/resolver/restriction/node_modules/style/package.json
  packages/rspack-test-tools/tests/configCases/resolver/restriction/rspack.config.js
  packages/rspack/src/Resolver.ts
Labels: team, release: feature

#10010 fix: hmr wasm filename
  crates/rspack_plugin_wasm/src/wasm_plugin.rs
  packages/rspack-test-tools/tests/watchCases/wasm/issue-6463/0/index.js
  packages/rspack-test-tools/tests/watchCases/wasm/issue-6463/0/module.js
  packages/rspack-test-tools/tests/watchCases/wasm/issue-6463/0/wasm.wasm
  packages/rspack-test-tools/tests/watchCases/wasm/issue-6463/1/wasm.wasm
  packages/rspack-test-tools/tests/watchCases/wasm/issue-6463/2/module.js
  packages/rspack-test-tools/tests/watchCases/wasm/issue-6463/rspack.config.js
Labels: team, release: bug fix

#9986 fix: sometimes entry chunk hash not changes with full hash runtime modules
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  packages/rspack-test-tools/tests/NewIncremental-watch.test.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/full-hash.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/index.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/index2.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/1/index.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/test.config.js
Labels: team, release: bug fix

#9999 fix(wasm): align trait methods for `native_fs`
  crates/rspack_fs/src/native_fs.rs
Labels: release: bug fix

#9608 fix: incorrect type signatures on Hash's digest and update methods
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/hooks.snap.txt
  packages/rspack/etc/core.api.md
  packages/rspack/src/taps/compilation.ts
  packages/rspack/src/taps/javascriptModules.ts
  packages/rspack/src/util/createHash.ts
  packages/rspack/src/util/hash/BatchedHash.ts
  packages/rspack/src/util/hash/index.ts
Labels: release: bug fix

#10018 fix: error when load binding multiple times
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/module.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/NormalModule.ts
Labels: team, release: bug fix

#10019 fix(incremental): dynamic add entries with infer async modules
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/0/index0.js
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/0/module.js
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/0/tla.js
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/1/index0.js
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/1/index1.js
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/test.config.js
Labels: team, release: bug fix

#10030 fix: covert optional import meta property to `undefined`
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/normalCases/esm/import-meta-property/index.js
  packages/rspack-test-tools/tests/normalCases/esm/import-meta/index.js
Labels: team, release: bug fix

#10021 fix: worker alias with module
  crates/rspack_core/src/normal_module_factory.rs
  packages/rspack-test-tools/src/case/config.ts
  packages/rspack-test-tools/src/case/new-code-splitting.ts
  packages/rspack-test-tools/tests/configCases/resolve/worker-alias/index.js
  packages/rspack-test-tools/tests/configCases/resolve/worker-alias/node_modules/corejs/modules/esnext.map.update.js
  packages/rspack-test-tools/tests/configCases/resolve/worker-alias/node_modules/corejs/package.json
  packages/rspack-test-tools/tests/configCases/resolve/worker-alias/package.json
  packages/rspack-test-tools/tests/configCases/resolve/worker-alias/rspack.config.cjs
  packages/rspack-test-tools/tests/configCases/resolve/worker-alias/worker.js
Labels: team, release: bug fix

#10032 fix(incremental): chunk id change should affect associate chunk
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/incremental/mutations.rs
  crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
Labels: team, release: bug fix

#9895 fix(wasm): shutdown async runtime and thread workers after finishing
  crates/node_binding/rspack.wasi.cjs
  packages/rspack/src/Compiler.ts
Labels: release: bug fix

#10035 docs: enhance Rsdoctor analysis guide
  website/docs/en/blog/rspack-next-partner.mdx
  website/docs/en/guide/optimization/profile.mdx
  website/docs/en/guide/optimization/use-rsdoctor.mdx
  website/docs/en/guide/tech/next.mdx
  website/docs/zh/guide/optimization/profile.mdx
  website/docs/zh/guide/optimization/use-rsdoctor.mdx
Labels: team, release: document

#10031 chore: release v1.3.5
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#10034 fix: remove progressbar instance when closing compiler
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_plugin_progress/src/lib.rs
  packages/rspack/src/Compiler.ts
Labels: team, release: bug fix

#10033 chore: bump swc version to 22.4.0
  Cargo.lock
  Cargo.toml
  crates/rspack_ast/src/ast/javascript.rs
  crates/rspack_loader_swc/src/compiler.rs
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
Labels: team

#10016 fix: should not rename __webpack_require__ if declared in current scope
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/a.js
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/c.js
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/index.js
Labels: team, release: bug fix

#10036 fix: should rename __webpack_require__ pat in parameters
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/index.js
Labels: team, release: bug fix

#10039 test: cacheCases update dynamic file by write
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/cache.ts
  packages/rspack-test-tools/src/helper/hot-update/index.ts
  packages/rspack-test-tools/src/helper/hot-update/loader.ts
  packages/rspack-test-tools/src/helper/hot-update/plugin.ts
  packages/rspack-test-tools/src/helper/util/refreshModifyTime.ts
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/tests/Cache.test.js
Labels: team

#10040 fix: failed to resolve tinypool when using parallel loader
  packages/rspack/rslib.config.ts
Labels: team, release: bug fix

#10047 fix: require with string raw
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  tests/webpack-test/cases/parsing/complex-require/cjs.js
Labels: team, release: bug fix

#10038 fix: dev server types
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
  packages/rspack/src/config/devServer.ts
  packages/rspack/src/config/types.ts
  pnpm-lock.yaml
Labels: team, release: bug fix

#10048 perf(build): custom Rslib minify options for `@rspack/core`
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err
  packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
  packages/rspack/rslib.config.ts
Labels: team, release: performance

#10052 ci: lock cargo shear version
  .github/workflows/ci.yml
Labels: team

#10059 fix: conflict hot update main content warning
  crates/rspack_plugin_hmr/src/lib.rs
  tests/webpack-test/hotCases/disposing/runtime-independent-filename/test.filter.js
Labels: team, release: bug fix

#10007 feat: rsdoctor module object add issuerPath property
  crates/node_binding/binding.d.ts
  crates/node_binding/src/rsdoctor.rs
  crates/rspack_plugin_rsdoctor/src/data.rs
  crates/rspack_plugin_rsdoctor/src/module_graph.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/rsdoctor/moduleGraph/rspack.config.js
Labels: release: feature

#10050 feat: persistent cache snapshot save file hash by default
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/option.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_core/src/cache/persistent/storage/mod.rs
  crates/rspack_core/src/utils/iterator_consumer/future.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs/src/read.rs
  packages/rspack-test-tools/src/helper/hot-update/plugin.ts
  packages/rspack-test-tools/src/helper/plugins/hot-update.ts
  packages/rspack-test-tools/tests/cacheCases/common/update-file/file.js
  packages/rspack-test-tools/tests/cacheCases/common/update-file/index.js
  packages/rspack-test-tools/tests/cacheCases/common/update-file/loader.js
  packages/rspack-test-tools/tests/cacheCases/common/update-file/rspack.config.js
Labels: team, release: feature

#10055 fix: should validate options of builtin swc loader
  packages/create-rspack/template-vue-ts/rspack.config.ts
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/compiler.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/preact-refresh/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/react-refresh/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/swc-loader-incompatible-wasm-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/validate/errors.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/validate/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/validate/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-swc-loader/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-swc-loader/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/rspack.config.js
  packages/rspack/src/builtin-loader/swc/pluginImport.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/config/utils.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/util/validate.ts
Labels: team, release: bug fix

#10060 perf(hash): avoid heap allocations in hash
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_hash/Cargo.toml
  crates/rspack_hash/src/lib.rs
Labels: release: performance

#10028 fix: context dependency with complex require
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_detection_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_array_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_call_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_cond_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_member_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_new_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/context-module/with-define-plugin/index.js
  packages/rspack-test-tools/tests/configCases/context-module/with-define-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/context-module/with-define-plugin/sub/a1.js
Labels: team, release: bug fix

#10067 feat(core): remove otel tracing support
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/rspack_tracing/Cargo.toml
  crates/rspack_tracing/src/lib.rs
  crates/rspack_tracing/src/opentelemetry.rs
  packages/rspack-cli/package.json
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-tracing/README.md
  packages/rspack-tracing/index.d.ts
  packages/rspack-tracing/index.js
  packages/rspack-tracing/package.json
  packages/rspack-tracing/tsconfig.build.json
  packages/rspack-tracing/types/index.d.ts
  packages/rspack-tracing/types/package.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  packages/rspack/src/exports.ts
  packages/rspack/src/loader-runner/index.ts
  pnpm-lock.yaml
Labels: team, release: feature

#10066 feat: support svg-chunk-webpack-plugin
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/macros.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ConcatenatedModule.ts
  packages/rspack/src/ContextModule.ts
  packages/rspack/src/ExternalModule.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/NormalModule.ts
Labels: team, release: feature

#10070 fix: import module entry dependency resolve options
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_core/src/dependency/dependency_category.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
  packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
  packages/rspack-test-tools/tests/defaultsCases/target_/node.js
  packages/rspack-test-tools/tests/defaultsCases/target_/nwjs.js
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/configCases/concatenate-modules/import-module/test.filter.js
Labels: team, release: bug fix

#10071 fix(cli): remove JSCPU & LOGGING support
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/build/profile/profile.test.ts
  website/docs/en/contribute/development/profiling.md
  website/docs/en/guide/optimization/profile.mdx
  website/docs/zh/contribute/development/profiling.md
  website/docs/zh/guide/optimization/profile.mdx
  website/project-words.txt
Labels: team, release: bug fix

#10074 fix: allow lazyCompilation.serverUrl to end with slash
  packages/rspack-test-tools/tests/hotCases/lazy-compilation/context/webpack.config.js
  packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
  packages/rspack/src/config/types.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: bug fix

#10076 revert: lightningcss loader error recovery default value
  crates/rspack_loader_lightningcss/src/lib.rs
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-warning/index.css
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-warning/index.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-warning/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-warning/warnings.js
Labels: team

#10077 docs: lightningcss errorRecovery option
  website/docs/en/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
Labels: team, release: document

#10069 fix: should have correct interop for default exportsType
  crates/rspack_plugin_library/src/module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/module-asset-entry-inline/img.png
  packages/rspack-test-tools/tests/configCases/library/module-asset-entry-inline/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/module-asset-entry-inline/test.config.js
Labels: team, release: bug fix

#10082 fix: ThreadsafeOneShotRef prevents event loop destroy
  crates/rspack_napi/src/js_values/threadsafe_one_shot_value_ref.rs
Labels: team, release: bug fix

#10093 fix: allow assignment of `require` identifier
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-10005/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-10005/rspack.config.js
Labels: release: bug fix

#10072 fix(cli): simplify RSPACK_PROFILE
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/utils/profile.ts
  packages/rspack-cli/tests/build/profile/profile.test.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/trace/index.ts
Labels: team, release: bug fix

#10098 fix: compilation.chuks not corresponds to a unique jsobect
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/src/compilation/chunks.rs
  crates/node_binding/src/compilation/mod.rs
  crates/rspack_napi/src/js_values/weak_ref.rs
  crates/rspack_napi/src/lib.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/compilation-chunks-instance/index.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/compilation-chunks-instance/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Chunks.ts
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#10061 fix: hmr should not include unchanged module when adding a new runtime
  crates/rspack_core/src/compiler/rebuild.rs
  crates/rspack_plugin_hmr/src/lib.rs
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/tests/hotCases/asset/parser-and-generator-states/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/worker/move-between-runtime/__snapshots__/web/5.snap.txt
  packages/rspack-test-tools/tests/hotCases/worker/move-between-runtime/__snapshots__/web/6.snap.txt
  tests/webpack-test/hotCases/asset-modules-source/source/index.js
  tests/webpack-test/hotCases/asset-modules-source/source/test.filter.js
  tests/webpack-test/hotCases/hashing/full-hash-syntax-error/errors1.js
  tests/webpack-test/hotCases/hashing/full-hash-syntax-error/test.filter.js
  tests/webpack-test/hotCases/loader-import-module/css/test.filter.js
  tests/webpack-test/hotCases/runtime/add-runtime/test.filter.js
Labels: team, release: bug fix

#9826 feat: swc loader support emitAssertForImportAttributes config
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  packages/rspack-test-tools/tests/builtinCases/swc-loader/experimental/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/swc-loader/experimental/index.js
  packages/rspack-test-tools/tests/builtinCases/swc-loader/experimental/rspack.config.js
  packages/rspack-test-tools/tests/builtinCases/swc-loader/experimental/static-package.json
Labels: release: feature

#10080 refactor: improve render external module for module output
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case2.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case3.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case5.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case6.txt
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/lib.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-module/index.js
  tests/webpack-test/configCases/externals/module-import/index.js
Labels: team

#10100 fix: comma in regex value of magic comments
  crates/rspack_plugin_javascript/src/webpack_comment.rs
  packages/rspack-test-tools/tests/cacheCases/common/update-file/rspack.config.js
Labels: team, release: bug fix

#10064 chore: add tracing for hook call in define_hook macro
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_hook/Cargo.toml
  crates/rspack_hook/src/lib.rs
  crates/rspack_macros/src/hook.rs
  crates/rspack_macros/src/plugin.rs
Labels: team

#10099 docs: rewrite tracing section
  website/docs/en/contribute/development/_meta.json
  website/docs/en/contribute/development/debugging.mdx
  website/docs/en/contribute/development/profiling.md
  website/docs/en/contribute/development/tracing.md
  website/docs/zh/contribute/development/_meta.json
  website/docs/zh/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/profiling.md
  website/docs/zh/contribute/development/tracing.md
Labels: team, release: document

#10103 feat: improve lightningcss minimize warning
  Cargo.lock
  crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
  crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/stats.err
Labels: team, release: feature

#10105 test: fix Jest haste module naming collision
  packages/rspack-test-tools/tests/cacheCases/snapshot/managed-paths/test_lib/package.json
  packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/test_lib/package.json
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/package.json
Labels: team

#10106 docs: fix tracing title
  website/docs/en/contribute/development/tracing.md
  website/docs/zh/contribute/development/tracing.md
Labels: team, release: document

#10109 fix(diagnostic): fix excessively large width causing `format_args` panics
  Cargo.lock
  crates/rspack_error/Cargo.toml
  crates/rspack_error/src/graphical.rs
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
Labels: team, release: bug fix

#10111 fix(pnp): resolved wrong description file in yarn pnp mode
  Cargo.lock
  Cargo.toml
Labels: release: bug fix

#10107 fix: use evaluate expression to extract hmr accept dependencies
  crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/HotTestCases.template.js
  tests/webpack-test/TestCases.template.js
  tests/webpack-test/WatchTestCases.template.js
  tests/webpack-test/checkArrayExpectation.js
  tests/webpack-test/helpers/FakeDocument.js
  tests/webpack-test/hotCases/css/css-modules/index.js
  tests/webpack-test/hotCases/css/css-modules/test.filter.js
  tests/webpack-test/hotCases/css/fetch-priority/test.filter.js
  tests/webpack-test/hotCases/css/vanilla/test.filter.js
  tests/webpack-test/hotCases/define/issue-6962/test.filter.js
  tests/webpack-test/lib/css/walkCssTokens.js
Labels: team, release: bug fix

#10102 chore: fork tracing-chrome for better support for perfetto
  .github/workflows/reusable-build-bench.yml
  Cargo.lock
  Cargo.toml
  README.md
  crates/rspack_tracing/Cargo.toml
  crates/rspack_tracing/src/chrome.rs
  crates/rspack_tracing_chrome/Cargo.toml
  crates/rspack_tracing_chrome/LICENSE
  crates/rspack_tracing_chrome/README.md
  crates/rspack_tracing_chrome/src/lib.rs
Labels: team

#10112 fix: compilation chunks for each is undefined
  packages/rspack-test-tools/tests/configCases/chunk-graph/compilation-chunks-instance/rspack.config.js
  packages/rspack/src/Chunks.ts
Labels: team, release: bug fix

#10114 docs: update banner image
  README.md
  README.zh-CN.md
  crates/node_binding/README.md
  packages/create-rspack/README.md
  packages/rspack-cli/README.md
  packages/rspack-test-tools/README.md
  packages/rspack/README.md
  scripts/build-npm.cjs
  tests/e2e/README.md
Labels: team, release: document

#10115 docs: add `optimization.removeAvailableModules` config
  website/docs/en/config/optimization.mdx
  website/docs/zh/config/optimization.mdx
Labels: team, release: document

#10110 fix(incremental): fallback when chunk depend on full hash
  crates/rspack_core/src/artifacts/chunk_hashes_artifact.rs
  crates/rspack_core/src/artifacts/mod.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/rebuild.rs
  crates/rspack_core/src/incremental/mod.rs
  packages/rspack-test-tools/tests/NewIncremental-watch.test.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/warnings.js
  tasks/benchmark/benches/groups/build_chunk_graph.rs
Labels: team, release: bug fix

#10117 refactor(incremental): use ChunkSetHashes for chunk render
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/incremental/mutations.rs
Labels: team

#10120 chore: disable hook macro tracing by default
  crates/rspack_macros/src/hook.rs
  crates/rspack_macros/src/plugin.rs
Labels: team

#10122 perf(core): remove json-parse-even-better-errors dependency
  packages/rspack/package.json
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/worker.ts
  pnpm-lock.yaml
Labels: team, release: performance

#10126 Revert "refactor: improve render external module for module output"
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case2.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case3.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case5.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case6.txt
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/lib.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-module/index.js
  tests/webpack-test/configCases/externals/module-import/index.js
Labels: team

#10121 perf: define Rspack version to reduce require calls
  .github/workflows/release-canary.yml
  package.json
  packages/rspack/rslib.config.ts
  packages/rspack/src/MultiStats.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/env.d.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/util/bindingVersionCheck.ts
Labels: team, release: performance

#10134 chore(deps): bump Rslib 0.6.7
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#10124 fix: should rebuild css module when rebuild css extract entry
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/module_executor/ctrl.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/index.js
  packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/loader.js
  packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/render.css
  packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/render.js
  packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/rspack.config.js
Labels: team, release: bug fix

#10137 fix: plugin compilation hooks leak
  crates/node_binding/src/plugins/js_hooks_plugin.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/rebuild.rs
  crates/rspack_core/src/plugin/mod.rs
  crates/rspack_core/src/plugin/plugin_driver.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: release: bug fix

#10139 fix(core): add more trace for loaders
  crates/rspack_loader_runner/src/runner.rs
  packages/rspack/src/exports.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/trace/index.ts
Labels: team, release: bug fix

#10143 fix(storage): should flush writer when flushing file mtime
  crates/rspack_storage/src/pack/strategy/split/util.rs
Labels: team, release: bug fix

#10116 chore: release v1.3.6
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10101 fix: storage validate hash with content
  crates/rspack_storage/src/pack/strategy/split/mod.rs
  crates/rspack_storage/src/pack/strategy/split/validate_scope.rs
  crates/rspack_storage/tests/error.rs
Labels: team, release: bug fix

#10144 fix: multiple runtime keys broke filename in runtime module
  crates/rspack_core/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  packages/rspack-test-tools/tests/configCases/runtime/get-chunk-filename-runtime/a.js
  packages/rspack-test-tools/tests/configCases/runtime/get-chunk-filename-runtime/b.js
  packages/rspack-test-tools/tests/configCases/runtime/get-chunk-filename-runtime/common.js
  packages/rspack-test-tools/tests/configCases/runtime/get-chunk-filename-runtime/rspack.config.js
  packages/rspack-test-tools/tests/configCases/runtime/get-chunk-filename-runtime/test.config.js
Labels: team, release: bug fix

#10151 refactor: remove dead_code and use spawn_blocking for fast_set
  crates/rspack_core/src/utils/fast_actions.rs
  tasks/benchmark/benches/groups/build_chunk_graph.rs
Labels: team

#10155 fix: pass `null` to additional data of loader context
  packages/rspack-test-tools/tests/configCases/loader/additional-data-null/a.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-null/index.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-null/loader.js
  packages/rspack-test-tools/tests/configCases/loader/additional-data-null/rspack.config.js
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#10156 chore: disable more hook tracing
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/drive.rs
  crates/rspack_plugin_javascript/src/plugin/module_info_header_plugin.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
Labels: team

#10157 docs(llms): bump to Rspress@2.0.0-beta.1 and add llms.txt
  pnpm-lock.yaml
  website/package.json
  website/project-words.txt
  website/rspress.config.ts
Labels: team, release: document

#10158 fix: support license plugin when enable concatenated
  crates/node_binding/binding.d.ts
  crates/node_binding/src/dependency.rs
  crates/node_binding/src/modules/concatenated_module.rs
Labels: team, release: bug fix

#10164 fix(parallel-loader): should not pass options for which loaders are not set to `parallel`
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/unclonable.js
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#10165 docs(llms): bump to Rspress@2.0.0-beta.2
  pnpm-lock.yaml
  website/package.json
Labels: team, release: document

#10166 feat: persistent cache snapshot expose is_hot_start
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/compiler/mod.rs
Labels: team, release: feature

#10160 refactor: dependency range of remain dependencies
  crates/rspack_core/src/dependency/cached_const_dependency.rs
  crates/rspack_core/src/dependency/const_dependency.rs
  crates/rspack_plugin_css/src/dependency/self_reference.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_define_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_array_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_item_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/local_module_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/unsupported_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/if_stmt.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/logic_expr.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_top_level_this_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/exports_info_api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/use_strict_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/webpack_included_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Labels: team

#10163 fix: circularDependencyRspackPlugin should check all cycle
  crates/rspack_plugin_circular_dependencies/src/lib.rs
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/a.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/b.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/c.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/d.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/e.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/stats.err
Labels: release: bug fix

#10167 fix: should regenerate runtime chunk hash when using get chunk filename runtime module
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/dependent-hash.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/index.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/index2.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/warnings.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/1/index.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/test.config.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/0/warnings.js
Labels: team, release: bug fix

#10171 ci: close inactive issues with `need more info` or `awaiting more feedback`
  .github/workflows/issue-close-require.yml
Labels: team

#10147 feat: custom prefix for lazy compilation
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  tests/e2e/cases/lazy-compilation/custom-prefix/index.test.ts
  tests/e2e/cases/lazy-compilation/custom-prefix/rspack.config.js
  tests/e2e/cases/lazy-compilation/custom-prefix/src/component.js
  tests/e2e/cases/lazy-compilation/custom-prefix/src/index.js
  tests/e2e/cases/lazy-compilation/default-prefix/index.test.ts
  tests/e2e/cases/lazy-compilation/default-prefix/rspack.config.js
  tests/e2e/cases/lazy-compilation/default-prefix/src/component.js
  tests/e2e/cases/lazy-compilation/default-prefix/src/index.js
  website/docs/en/config/experiments.mdx
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/guide/features/lazy-compilation.mdx
Labels: release: feature

#10174 chore(ci): refactor incremental causes ci tests failed
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/warnings.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/1/warnings.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/0/warnings.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/1/warnings.js
Labels: team

#10169 docs: fix grammar in rspack-next-partner.mdx
  website/docs/en/blog/rspack-next-partner.mdx
Labels: release: document

#10180 fix: truncate width into `u16::MAX` for graphical reporter
  crates/rspack_error/src/graphical.rs
Labels: team, release: bug fix

#10178 perf: use `Vec::with_capacity` for hooks and plugins
  crates/node_binding/src/lib.rs
  crates/rspack_macros/src/hook.rs
Labels: release: performance

#10181 docs(llms.txt): add more description
  website/rspress.config.ts
Labels: team, release: document

#10184 fix: Vue CSS pseudo class warning in lightningcss
  crates/rspack_loader_lightningcss/src/lib.rs
  packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/ignore-css-modules-warning/index.module.css
Labels: team, release: bug fix
