Repository web-infra-dev/rspack, pull requests merged in 2025-01, with the labels that each got.

#8906 fix: get resolved module
  crates/rspack_binding_values/src/module_graph.rs
  crates/rspack_core/src/module_graph/connection.rs
  packages/rspack-test-tools/tests/configCases/module-graph/get-module/foo.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-module/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-module/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
Labels: team, release: bug fix

#8917 docs: add warning about hmr fails when filename has hash
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: document

#8907 ci: fix documentation coverage check
  .github/workflows/reusable-build.yml
  packages/rspack/package.json
  packages/rspack/scripts/check-documentation-coverage.ts
  pnpm-lock.yaml
  website/docs/en/plugins/webpack/internal-plugins.mdx
  website/docs/zh/plugins/webpack/internal-plugins.mdx
Labels: team

#8919 test: clean up unused dev dependencies
  pnpm-lock.yaml
  tests/webpack-examples/package.json
  tests/webpack-test/package.json
Labels: team

#8920 feat: support invalidate persistent cache using `config.mode` and `config.name`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_core/src/options/compiler_options.rs
  crates/rspack_core/src/options/compiler_options_builder.rs
  crates/rspack_core/src/options/mode.rs
  packages/rspack-test-tools/tests/cacheCases/invalidation/config-mode/file.js
  packages/rspack-test-tools/tests/cacheCases/invalidation/config-mode/index.js
  packages/rspack-test-tools/tests/cacheCases/invalidation/config-mode/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/invalidation/config-name/file.js
  packages/rspack-test-tools/tests/cacheCases/invalidation/config-name/index.js
  packages/rspack-test-tools/tests/cacheCases/invalidation/config-name/rspack.config.js
  packages/rspack/src/config/adapter.ts
Labels: team, release: feature

#8837 fix(modern-module): skip the asset entry module concaten for Rslib
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/h/file.png
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
Labels: team

#8923 ci: ecosystem-benchmark checkout failed
  .github/workflows/ecosystem-benchmark.yml
Labels: team

#8926 ci: use corepack instead of pnpm/action-setup
  .github/actions/pnpm-cache/action.yml
  .github/workflows/reusable-build.yml
Labels: team

#8899 fix: include versions in error message for version mismatch
  packages/rspack/src/util/bindingVersionCheck.ts
Labels: release: bug fix

#8928 docs: add loader API overview page
  website/docs/en/api/loader-api/index.mdx
  website/docs/en/api/loader-api/inline-match-resource.mdx
  website/docs/en/api/loader-api/rspack-specific-properties.mdx
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/plugins/index.mdx
  website/docs/zh/api/loader-api/index.mdx
  website/docs/zh/api/loader-api/inline-match-resource.mdx
  website/docs/zh/blog/announcing-0-3.mdx
  website/docs/zh/plugins/index.mdx
Labels: team, release: document

#8929 ci: pnpm cache install pnpm/exe when node16
  .github/actions/pnpm-cache/action.yml
Labels: team

#8931 ci: add ecosystem ci
  .github/workflows/ecosystem-ci.yml
Labels: team

#8932 ci: enable ecosystem-ci on main branch
  .github/workflows/ci.yml
  .github/workflows/ecosystem-ci-trigger.yml
  .github/workflows/ecosystem-ci.yml
Labels: team

#8934 fix: allow custom `lazyCompilation.backend.client`
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
Labels: release: bug fix

#8940 feat: support `devtool` to compiler options builder
  crates/rspack_core/src/options/compiler_options_builder.rs
  crates/rspack_core/src/options/devtool.rs
  crates/rspack_core/src/options/mod.rs
Labels: team, release: feature

#8941 refactor: move compiler options builder to new crate
  Cargo.lock
  Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack/LICENSE
  crates/rspack/src/lib.rs
  crates/rspack/src/options/builder.rs
  crates/rspack/src/options/devtool.rs
  crates/rspack/src/options/mod.rs
  crates/rspack/src/options/target.rs
  crates/rspack_core/src/options/mod.rs
Labels: team

#8952 fix: lazy compilation use persistent cache restart failure
  crates/rspack_plugin_lazy_compilation/src/module.rs
  tests/e2e/cases/lazy-compilation/persistent-cache/index.test.ts
  tests/e2e/cases/lazy-compilation/persistent-cache/rspack.config.js
  tests/e2e/cases/lazy-compilation/persistent-cache/src/component.js
  tests/e2e/cases/lazy-compilation/persistent-cache/src/index.js
  tests/e2e/fixtures/rspack.ts
Labels: team, release: bug fix

#8921 docs: add persistent cache invalidation notes
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8954 feat: initialize builtin plugins in compiler options builder
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/options/builder.rs
  crates/rspack/src/options/devtool.rs
  crates/rspack/src/options/mod.rs
  crates/rspack_core/src/options/output.rs
Labels: team, release: feature

#8955 ci: ecosystem-ci runs on ubuntu-22.04
  .github/workflows/ecosystem-ci.yml
Labels: team

#8969 docs: fix canary package name
  website/docs/en/contribute/development/releasing.md
  website/docs/zh/contribute/development/releasing.md
Labels: team, release: document

#8588 feat: support chunkGroup.getModulePreOrderIndex
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_core/src/chunk_group.rs
  packages/rspack-test-tools/tests/configCases/chunks/module-order-index/index.js
  packages/rspack-test-tools/tests/configCases/chunks/module-order-index/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGroup.ts
Labels: team, release: feature

#8967 feat(core): bump swc_core to 10.0.1
  Cargo.lock
  Cargo.toml
Labels: team, release: feature

#8971 docs: update blog list
  website/docs/en/blog/index.mdx
  website/docs/zh/blog/index.mdx
Labels: team, release: document

#8970 fix: should recalculate order indices in outdated entrypoint
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  tests/plugin-test/css-extract/cases/dependOn-multiple-files-per-entry/expected/entry1.css
Labels: team, release: bug fix

#7639 feat(core): add yarn pnp support
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/resolver_factory.rs
  crates/rspack_binding_values/src/options/raw_resolve.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/boxfs.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/file_metadata.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_storage/src/pack/strategy/split/util.rs
  crates/rspack_storage/tests/build.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  crates/rspack_storage/tests/expire.rs
  crates/rspack_storage/tests/lock.rs
  crates/rspack_storage/tests/multi.rs
  crates/rspack_storage/tests/release.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/.gitignore
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/.pnp.cjs
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/.yarn/cache/the-answer-npm-1.0.0-c6ae1caf6d-5870a78be9.zip
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/.yarn/install-state.gz
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/index.js
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/package.json
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/yarn.lock
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/.gitignore
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/.pnp.cjs
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/.yarn/cache/the-answer-npm-1.0.0-c6ae1caf6d-5870a78be9.zip
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/.yarn/install-state.gz
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/yarn.lock
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/ResolverFactory.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/resolve.mdx
  website/docs/zh/config/resolve.mdx
Labels: team, release: feature

#8707 fix(type): Add missing OptimizationSplitChunksNameFunction param
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: release: bug fix

#8979 feat: support `optimization` in compiler options builder
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/devtool.rs
  crates/rspack/src/builder/externals.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack/src/builder/target.rs
  crates/rspack/src/lib.rs
  crates/rspack/src/options/mod.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
  crates/rspack_plugin_externals/src/electron_target_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/mod.rs
Labels: team, release: feature

#8980 feat: make builtin plugin options ordered in compiler options builder
  Cargo.lock
  Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/mod.rs
  crates/rspack/src/builder/target.rs
Labels: team, release: feature

#8947 feat: support custom parser for `json` type
  crates/node_binding/binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-8785/data.toml
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-8785/index.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-8785/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  pnpm-lock.yaml
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/custom-modules/json-custom/test.filter.js
  tests/webpack-test/package.json
Labels: release: feature

#8983 docs: unify title capitalization style for more docs
  packages/create-rspack/template-common/README.md
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack/etc/core.api.md
  tests/bench/README.md
  tests/webpack-examples/README.md
  tests/webpack-examples/require.context/README.md
  tests/webpack-examples/require.context/template.md
  tests/webpack-test/README.md
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/en/api/javascript-api/index.mdx
  website/docs/en/api/javascript-api/logger.mdx
  website/docs/en/api/javascript-api/stats-json.mdx
  website/docs/en/api/javascript-api/stats.mdx
  website/docs/en/api/loader-api/examples.mdx
  website/docs/en/blog/announcing-0-2.mdx
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/blog/announcing-0-5.mdx
  website/docs/en/blog/announcing-0-6.mdx
  website/docs/en/blog/announcing-0-7.mdx
  website/docs/en/blog/announcing-1-0-alpha.mdx
  website/docs/en/blog/announcing-1-1.mdx
  website/docs/en/blog/index.mdx
  website/docs/en/blog/module-federation-added-to-rspack.mdx
  website/docs/en/config/entry.mdx
  website/docs/en/config/module.mdx
  website/docs/en/config/output.mdx
  website/docs/en/contribute/development/debugging.mdx
  website/docs/en/contribute/index.mdx
  website/docs/en/errors/swc-plugin-version.mdx
  website/docs/en/guide/features/asset-module.mdx
  website/docs/en/guide/features/loader.mdx
  website/docs/en/guide/migration/rspack_0.x.mdx
  website/docs/en/misc/faq.mdx
  website/docs/en/misc/team/join-us.mdx
  website/docs/zh/api/javascript-api/stats.mdx
  website/docs/zh/api/loader-api/examples.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/blog/announcing-0-7.mdx
  website/docs/zh/blog/announcing-1-0-alpha.mdx
  website/docs/zh/blog/announcing-1-0.mdx
  website/docs/zh/blog/index.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/contribute/development/profiling.md
  website/docs/zh/contribute/development/testing-webpack.mdx
  website/docs/zh/contribute/index.mdx
  website/docs/zh/guide/features/asset-module.mdx
  website/docs/zh/guide/migration/rspack_0.x.mdx
  website/docs/zh/guide/optimization/profile.mdx
  website/docs/zh/guide/optimization/tree-shaking.mdx
  website/docs/zh/misc/faq.mdx
  website/docs/zh/plugins/webpack/eval-source-map-dev-tool-plugin.mdx
  website/docs/zh/plugins/webpack/provide-plugin.mdx
  website/docs/zh/plugins/webpack/source-map-dev-tool-plugin.mdx
Labels: team, release: document

#8982 docs: fix loader API getLogger types documentation
  website/docs/en/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/context.mdx
Labels: release: document

#8984 fix: merge global parser and generator options
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  packages/rspack-test-tools/tests/configCases/module/merge-global-asset-generator/a.txt
  packages/rspack-test-tools/tests/configCases/module/merge-global-asset-generator/index.js
  packages/rspack-test-tools/tests/configCases/module/merge-global-asset-generator/rspack.config.js
Labels: release: bug fix

#8985 fix(core): calculate pkgJson from configPath dir
  packages/rspack-cli/src/utils/isEsmFile.ts
Labels: team, release: bug fix

#8995 feat(core): bump swc_core to 10.1.0
  Cargo.lock
  Cargo.toml
Labels: team, release: feature

#8978 docs: add persistent cache migration
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#8966 fix: should run invalidation when watching is invalid
  crates/rspack_plugin_extract_css/src/plugin.rs
  packages/rspack-test-tools/tests/compilerCases/invalidation-multi-times.js
  packages/rspack/src/Watching.ts
Labels: team, release: bug fix

#9001 feat: add tracing instrument for persistent cache
  Cargo.lock
  crates/rspack_core/src/cache/persistent/occasion/make/dependencies.rs
  crates/rspack_core/src/cache/persistent/occasion/make/meta.rs
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_storage/Cargo.toml
  crates/rspack_storage/src/pack/manager/mod.rs
Labels: team, release: feature

#9003 docs: add `invalid` compiler hook
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/javascript-api/compiler.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
Labels: team, release: document

#9009 fix(types): missing `lazyCompilation.backend.server` option
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
  packages/rspack/src/config/types.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: bug fix

#9008 feat: mark `@rspack/tracing` as peer dependency
  packages/rspack-cli/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
  packages/rspack/src/exports.ts
  packages/rspack/src/loader-runner/index.ts
  pnpm-lock.yaml
Labels: team, release: feature

#9010 perf: persistent cache use multi-thread
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
Labels: team, release: performance

#9015 feat: initial support for compiler builder
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/basic.rs
  crates/rspack/tests/fixtures/basic/src/index.js
  crates/rspack_binding_values/src/raw_options/raw_builtins/mod.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
Labels: team, release: feature

#8997 chore(deps): update lightningcss to v1.0.0-alpha.63
  Cargo.lock
  Cargo.toml
Labels: team

#9018 ci: declare minimal permissions for Actions
  .github/workflows/ci.yml
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/ecosystem-ci.yml
  .github/workflows/label-auto-comment.yml
  .github/workflows/lint-pr.yaml
  .github/workflows/preview-commit.yml
  .github/workflows/release-canary.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  tests/webpack-test/scripts/generate.js
Labels: team

#9021 ci: fix workflow permission issues
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/ecosystem-ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#9020 feat: hoist compiler options builder to `Compiler::builder`
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/basic.rs
  crates/rspack/tests/fixtures/basic/src/index.js
  crates/rspack_core/src/options/entry.rs
Labels: team

#9028 docs: rewrite CLI documentation
  website/docs/en/api/cli.mdx
  website/docs/en/api/index.mdx
  website/docs/zh/api/cli.mdx
  website/docs/zh/api/index.mdx
Labels: team

#9029 chore(deps): bump prebundle v1.2.7 to disable CI cache
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: team

#9030 fix(core): don't panic when accept invalid sourcemap
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/rspack_napi/src/ext/js_string_ext.rs
Labels: team

#9019 perf: persistent cache recovery use consumer mode
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/utils/iterator_consumer/future.rs
  crates/rspack_core/src/utils/iterator_consumer/rayon.rs
  crates/rspack_core/src/utils/iterator_consumer/rayon_fut.rs
Labels: team

#9036 docs: improve hot module replacement
  website/docs/en/api/runtime-api/hmr.mdx
  website/docs/en/api/runtime-api/module-methods.mdx
  website/docs/en/guide/tech/preact.mdx
  website/docs/en/guide/tech/react.mdx
  website/docs/en/plugins/webpack/hot-module-replacement-plugin.mdx
  website/docs/zh/api/cli.mdx
  website/docs/zh/api/runtime-api/hmr.mdx
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/guide/tech/preact.mdx
  website/docs/zh/guide/tech/react.mdx
  website/docs/zh/plugins/webpack/hot-module-replacement-plugin.mdx
Labels: team

#9032 ci: ecosystem ci shows errors only on comment
  .github/workflows/ecosystem-ci.yml
Labels: team

#9037 fix: patched mimalloc to use `MADV_DONTNEED` than `MADV_FREE` on Linux
  Cargo.lock
  Cargo.toml
Labels: team

#9045 perf: caching require @rspack/tracing
  packages/rspack/src/loader-runner/index.ts
Labels: team

#9046 perf: disable js tracing in non-profile mode
  packages/rspack-tracing/README.md
  packages/rspack-tracing/package.json
  packages/rspack-tracing/types/index.d.ts
  packages/rspack-tracing/types/package.json
  packages/rspack/src/loader-runner/index.ts
Labels: team

#9047 fix: skip mf tests for new code splitting
  packages/rspack-test-tools/tests/NewCodeSplitting-config.test.js
Labels: team

#9051 docs: add parallel code splitting docs
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team

#9049 feat(stats): add module reason locations and module trace dependencies
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_core/src/stats/utils.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
  pnpm-lock.yaml
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/package.json
Labels: team

#9053 feat: support more options in compiler builder
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/mod.rs
  crates/rspack_binding_values/src/raw_options/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_node.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/options/node.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
Labels: team

#8943 feat: Add support for debug IDs
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack_binding_values/src/raw_options/raw_devtool.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  packages/rspack/src/rspackOptionsApply.ts
  tests/webpack-test/configCases/source-map/source-map-debugids/index.js
  tests/webpack-test/configCases/source-map/source-map-debugids/webpack.config.js
Labels: release: feature

#9054 test: add basic rust benchmark
  .github/workflows/reusable-build.yml
  Cargo.lock
  tasks/benchmark/Cargo.toml
  tasks/benchmark/benches/basic.rs
Labels: team

#9066 fix: add issue permission for release workflow
  .github/workflows/release.yml
Labels: team

#9061 refactor: split compiler hook registers into multiple files
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  packages/rspack-tracing/index.d.ts
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/html-plugin/hooks.ts
  packages/rspack/src/builtin-plugin/html-plugin/index.ts
  packages/rspack/src/builtin-plugin/html-plugin/options.ts
  packages/rspack/src/builtin-plugin/html-plugin/plugin.ts
  packages/rspack/src/builtin-plugin/html-plugin/taps.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/taps/compilation.ts
  packages/rspack/src/taps/compiler.ts
  packages/rspack/src/taps/contextModuleFactory.ts
  packages/rspack/src/taps/index.ts
  packages/rspack/src/taps/javascriptModules.ts
  packages/rspack/src/taps/normalModuleFactory.ts
  packages/rspack/src/taps/types.ts
Labels: team

#9065 release: 1.2.0
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9060 docs: add 1.2.0 release blog
  crates/rspack_fs/src/native_fs.rs
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  website/docs/en/blog/announcing-1-2.mdx
  website/docs/en/blog/index.mdx
  website/docs/zh/blog/announcing-1-2.mdx
  website/docs/zh/blog/index.mdx
  website/project-words.txt
Labels: team

#9067 feat: improve compatibility with compiler options
  crates/rspack/src/builder/builder_context.rs
  crates/rspack/src/builder/devtool.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack/src/builder/target.rs
  crates/rspack/src/lib.rs
  crates/rspack_core/src/options/experiments/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_core/src/options/output.rs
Labels: team

#9068 docs: add v1.2 ecosystem updates
  .typos.toml
  website/docs/en/blog/announcing-1-2.mdx
  website/docs/zh/blog/announcing-1-2.mdx
  website/project-words.txt
Labels: team

#9079 feat: integrate rspack_dojang for enhanced template rendering
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/runtime_module.rs
  crates/rspack_core/src/runtime_template.rs
  crates/rspack_plugin_runtime/src/runtime_module/async_module.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js
Labels: team

#9085 docs: polish some documentations
  packages/rspack-tracing/README.md
  website/docs/en/api/cli.mdx
  website/docs/en/blog/announcing-1-2.mdx
  website/docs/zh/api/runtime-api/module-variables.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/blog/announcing-0-5.mdx
  website/docs/zh/blog/announcing-1-2.mdx
  website/docs/zh/blog/module-federation-added-to-rspack.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/profiling.md
  website/docs/zh/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/testing-webpack.mdx
  website/docs/zh/contribute/development/testing.mdx
  website/docs/zh/contribute/index.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/optimization/profile.mdx
  website/docs/zh/guide/optimization/use-rsdoctor.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/rspress.config.ts
  website/theme/index.tsx
Labels: team

#9088 fix: amd define in function params
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  packages/rspack-test-tools/tests/normalCases/amd/real-amd-libs/define-in-params.js
  packages/rspack-test-tools/tests/normalCases/amd/real-amd-libs/index.js
Labels: team

#9082 revert: rspack sources substring heuristic algorithm
  Cargo.lock
  Cargo.toml
Labels: team

#8939 fix: resolve the inconsistent type issue in `JsModule`
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  packages/rspack/src/Module.ts
Labels: release: bug fix

#9090 chore: release packages 1.2.1
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9084 feat: add runtime plugin hooks
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/runtime.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/drive.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_prefetch.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_preload.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/hooks/create-script/a.js
  packages/rspack-test-tools/tests/configCases/hooks/create-script/index.js
  packages/rspack-test-tools/tests/configCases/hooks/create-script/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/create-script/test.config.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/chunk1-a.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/chunk1-b.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/chunk1-c.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/chunk1.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/chunk2.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/index.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/link-prefetch-preload/test.config.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack/etc/core.api.md
  packages/rspack/scripts/check-documentation-coverage.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/builtin-plugin/RuntimePlugin.ts
  packages/rspack/src/exports.ts
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/async.$f4608fdcfef13de69f10$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.$f4608fdcfef13de69f10$.css
  tests/plugin-test/css-extract/cases/chunkFilename-fullhash/expected/main.js
  tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js
  tests/plugin-test/css-extract/cases/hmr/expected/main.js
  tests/plugin-test/css-extract/cases/insert-function/expected/main.js
  tests/plugin-test/css-extract/cases/insert-string/expected/main.js
  tests/plugin-test/css-extract/cases/insert-undefined/expected/main.js
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/plugin-test/css-extract/cases/no-runtime/expected/main.js
  tests/plugin-test/css-extract/cases/runtime/expected/runtime~main.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/api/plugin-api/_meta.json
  website/docs/en/api/plugin-api/runtime-plugin-hooks.mdx
  website/docs/zh/api/plugin-api/_meta.json
  website/docs/zh/api/plugin-api/runtime-plugin-hooks.mdx
Labels: team

#9091 fix: should not have warnings for cjs when using dll
  crates/rspack_core/src/exports_info.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/a.js
  packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/lib.js
  packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/main.js
  packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/rspack.config.js
  packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/warnings.js
  tests/webpack-test/configCases/dll-plugin/1-use-dll/index.js
  tests/webpack-test/configCases/dll-plugin/2-use-dll-without-scope/index.js
Labels: team

#9086 fix: should not cache tracing instance
  packages/rspack-tracing/types/index.d.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team

#9081 perf(options): replace `Regexp` with `ends_with` match
  crates/rspack/src/builder/mod.rs
  crates/rspack_core/src/options/module.rs
Labels: team

#9099 fix: render module id as number if we can
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_dll.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/unaffected_cache/mod.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_dll/src/lib.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/chunks.js
  packages/rspack-test-tools/tests/statsAPICases/ids.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/configCases/dll-plugin/1-use-dll/index.js
  tests/webpack-test/configCases/dll-plugin/2-use-dll-without-scope/index.js
Labels: team

#9100 test(benchmark): add basic sourcemap bench case
  crates/rspack/src/builder/builder_context.rs
  crates/rspack/tests/basic.rs
  tasks/benchmark/benches/basic.rs
Labels: team

#9106 chore: release packages 1.2.2
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9102 chore(CI): split PR labeler workflow
  .github/workflows/lint-pr.yaml
  .github/workflows/pr-labeler.yaml
Labels: team

#9112 fix: dll manifest zod validation
  packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/errors.js
  packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/lib.js
  packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/main.js
  packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/lib/DllReferencePlugin.ts
Labels: team, release: bug fix

#9110 chore: update Rslib description in README.md
  README.md
  README.zh-CN.md
Labels: team

#9113 fix: amd require array
  crates/rspack_plugin_javascript/src/dependency/amd/amd_define_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_array_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/amd/amd_require_item_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  tests/webpack-test/cases/amd/namedModulesConstArrayDep/test.filter.js
  tests/webpack-test/cases/mjs/type-module/package.json
  tests/webpack-test/cases/mjs/type-module/test.filter.js
Labels: team, release: bug fix

#9114 fix: require local module and support new require
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  packages/rspack-test-tools/src/helper/legacy/checkArrayExpectation.js
  tests/webpack-test/cases/parsing/issue-4940/test.filter.js
  tests/webpack-test/cases/parsing/local-modules/test.filter.js
  tests/webpack-test/cases/parsing/unsupported-amd/errors.js
  tests/webpack-test/cases/parsing/unsupported-amd/test.filter.js
  tests/webpack-test/cases/parsing/unsupported-amd/warnings.js
  tests/webpack-test/cases/resolving/commomjs-local-module/test.filter.js
  tests/webpack-test/checkArrayExpectation.js
Labels: team, release: bug fix

#9120 docs: add Khan Academy to who is using
  website/theme/components/Landingpage/WhoIsUsing/assets/khan-academy.svg
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: team, release: document

#9122 docs: add notes for injecting core-js polyfill
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: document

#9125 chore(deps): update `swc_core` to v10.7.0
  Cargo.lock
  Cargo.toml
Labels: team

#9129 docs: fix invalid `cacheGroups` example
  website/docs/en/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
Labels: team, release: document

#9117 fix: amd alias define renaming
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/amd/define-wrapper/lib1.js
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/StatsTestCases.basictest.js
  tests/webpack-test/TestCases.template.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/cases/parsing/issue-2641/index.js
  tests/webpack-test/cases/parsing/issue-2641/test.filter.js
  tests/webpack-test/cases/parsing/renaming/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/all-selected/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/existing-name/test.filter.js
  tests/webpack-test/configCases/async-commons-chunk/simple/test.filter.js
  tests/webpack-test/statsCases/async-commons-chunk/test.filter.js
Labels: team, release: bug fix

#9130 feat(create-rspack): create React 19 project by default
  packages/create-rspack/template-react-js/package.json
  packages/create-rspack/template-react-ts/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/lib/package.json
  pnpm-lock.yaml
  tests/bench/package.json
  tests/e2e/package.json
  tests/webpack-examples/package.json
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/package.json
  website/package.json
Labels: team, release: feature

#9131 docs: add examples for all module parser and generator options
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: team, release: document

#9132 docs: rewrite plugins usage guide
  website/docs/en/config/plugins.mdx
  website/docs/en/guide/features/plugin.mdx
  website/docs/en/plugins/webpack/hot-module-replacement-plugin.mdx
  website/docs/zh/config/plugins.mdx
  website/docs/zh/guide/features/plugin.mdx
  website/docs/zh/plugins/webpack/hot-module-replacement-plugin.mdx
Labels: team, release: document

#9127 feat: add rust benchmark case for code splitting
  Cargo.lock
  crates/rspack_core/src/build_chunk_graph/mod.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  tasks/benchmark/Cargo.toml
  tasks/benchmark/benches/basic.rs
  tasks/benchmark/benches/benches.rs
  tasks/benchmark/benches/build_chunk_graph.rs
  tasks/benchmark/benches/build_chunk_graph/random_table.json
  tasks/benchmark/src/lib.rs
Labels: team, release: feature

#9140 chore(workflow): remove duplicated issue label
  .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
  .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
Labels: team
