Repository web-infra-dev/rspack, pull requests merged in 2025-03, with the labels that each got.

#9522 docs: update local debugging command
  website/docs/en/contribute/development/building.md
  website/docs/en/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/building.md
  website/docs/zh/contribute/development/debugging.mdx
Labels: release: document

#9509 feat: render module_chunk_loading template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading_with_loading.ejs
Labels: team, release: feature

#9498 feat: render import_scripts_chunk_loading template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr_manifest.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading_with_hmr_manifest.js
Labels: team, release: feature

#9528 docs: update Module Federation syntax downgrade FAQ
  website/docs/en/plugins/webpack/module-federation-plugin.mdx
  website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Labels: team, release: document

#9521 fix(rspack_plugin_runtime): do not render chunks that only contain non-js module types
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
Labels: release: bug fix

#9518 perf: try reduce max_blocking_threads to save memory and reduce fs contention
  crates/node_binding/src/lib.rs
Labels: team, release: performance

#9529 feat: improve add include error msg
  crates/node_binding/src/compilation/mod.rs
  packages/rspack-test-tools/tests/configCases/compilation/add-include/rspack.config.js
  packages/rspack/src/Compilation.ts
Labels: team, release: feature

#9530 fix: update asset can return undefined
  crates/node_binding/binding.d.ts
  crates/node_binding/src/compilation/mod.rs
  packages/rspack-test-tools/tests/configCases/hooks/update-asset-return-undefined/index.js
  packages/rspack-test-tools/tests/configCases/hooks/update-asset-return-undefined/rspack.config.js
  packages/rspack-test-tools/tests/configCases/hooks/update-asset-return-undefined/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#9536 fix: change module matchResource in loader
  crates/node_binding/binding.d.ts
  crates/node_binding/src/module.rs
  crates/rspack_core/src/normal_module.rs
  packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/img.png
  packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/index.js
  packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/loader.js
  packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/rspack.config.js
  packages/rspack/src/Module.ts
Labels: team, release: bug fix

#9501 feat: render runtime template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/make_namespace_object.rs
  crates/rspack_plugin_runtime/src/runtime_module/node_module_decorator.rs
  crates/rspack_plugin_runtime/src/runtime_module/on_chunk_loaded.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/make_namespace_object.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/node_module_decorator.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/node_module_decorator.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/on_chunk_loaded.ejs
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/rsdoctor/assets/rspack.config.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#9533 feat(memory-allocator): use mimalloc-v3 on macOS and bump mimalloc to v2.1.7 on other platforms
  Cargo.lock
  Cargo.toml
  crates/rspack_allocator/Cargo.toml
Labels: team, release: feature

#9539 docs: fix invalid link in roadmap
  website/docs/en/misc/planning/roadmap.mdx
  website/docs/zh/misc/planning/roadmap.mdx
Labels: team, release: document

#9537 fix: should re-build chunk graph when adding a entry connection
  crates/rspack_core/src/artifacts/cgm_hash_artifact.rs
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/rebuild.rs
  crates/rspack_core/src/incremental/mutations.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_core/src/runtime.rs
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-add-same-entry/0/index.js
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-add-same-entry/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-add-same-entry/test.config.js
Labels: team, release: bug fix

#9541 test: run watch cases concurrently
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/hot-step.ts
  packages/rspack-test-tools/src/case/hot.ts
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/compiler.ts
  packages/rspack-test-tools/src/helper/util/currentWatchStep.js
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/test/creator.ts
  packages/rspack-test-tools/src/type.ts
  packages/rspack-test-tools/tsconfig.build.json
Labels: team

#9543 feat(cli): `rspack preview` support for `nodeEnv` flag and default env
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/options.ts
  website/docs/en/api/cli.mdx
  website/docs/zh/api/cli.mdx
Labels: team, release: feature

#9546 docs: invite @stormslowly to Rspack core team
  website/components/RandomMemberList.module.scss
  website/components/RandomMemberList.tsx
Labels: team, release: document

#9547 test: run partial cases concurrently
  packages/rspack-test-tools/src/case/builtin.ts
  packages/rspack-test-tools/src/case/cache.ts
  packages/rspack-test-tools/src/case/diagnostic.ts
  packages/rspack-test-tools/src/case/normal.ts
Labels: team

#9545 fix(lazy-compilation): should have separate state in multi-compiler
  packages/rspack-test-tools/tests/NewIncremental-node.test.js
  packages/rspack-test-tools/tests/NewIncremental-web.test.js
  packages/rspack-test-tools/tests/NewIncremental-webworker.test.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
Labels: team, release: bug fix

#9526 fix(html): include `innerHTML` content in rendered asset tags
  crates/rspack_plugin_html/src/tag.rs
  tests/e2e/cases/html/asset-tag-hooks/index.test.ts
  tests/e2e/cases/html/asset-tag-hooks/rspack.config.js
  tests/e2e/cases/html/asset-tag-hooks/src/index.html
  tests/e2e/cases/html/asset-tag-hooks/src/index.js
Labels: release: bug fix

#9556 docs: add Rspeedy and Lynx to ecosystem
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/project-words.txt
Labels: team, release: document

#8900 fix: copy filename_template into split chunks
  crates/rspack_core/src/chunk.rs
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/statsCases/split-chunks-cache-group-filename/index.js
  tests/webpack-test/statsCases/split-chunks-cache-group-filename/node_modules/a.js
  tests/webpack-test/statsCases/split-chunks-cache-group-filename/node_modules/b.js
  tests/webpack-test/statsCases/split-chunks-cache-group-filename/node_modules/c.js
  tests/webpack-test/statsCases/split-chunks-cache-group-filename/webpack.config.js
Labels: release: bug fix

#9558 test: fix import failed while running cases concurrently
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/src/test/creator.ts
Labels: team

#9561 ci: run api and doc coverage check in lint job
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#9566 feat(diagnostic): support `JSONError` diagnostic in resolver
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-bom/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-bom/node_modules/bommodule/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-bom/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-broken-json/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-broken-json/node_modules/foo/package.json
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-broken-json/stats.err
Labels: team, release: feature

#9569 chore: bench stats.toJson()
  tests/bench/ts-react.bench.ts
Labels: team

#9574 chore: split and group .github/action by features
  .github/actions/artifact/download/action.yml
  .github/actions/artifact/upload/action.yml
  .github/actions/cache/restore/action.yml
  .github/actions/cache/save/action.yml
  .github/actions/download-artifact/action.yml
  .github/actions/pnpm/install-binding-dependencies/action.yml
  .github/actions/pnpm/install-dependencies/action.yml
  .github/actions/pnpm/setup/action.yml
  .github/actions/rustup/action.yml
  .github/actions/rustup/cache/action.yml
  .github/actions/upload-artifact/action.yml
  .github/workflows/ci.yml
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/ecosystem-ci.yml
  .github/workflows/preview-commit.yml
  .github/workflows/release-canary.yml
  .github/workflows/release-otp.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
Labels: team

#9577 docs: add Angular Rspack and update example repo link
  README.md
  README.zh-CN.md
  website/docs/en/blog/announcing-0-2.mdx
  website/docs/en/blog/announcing-0-3.mdx
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/blog/announcing-0-6.mdx
  website/docs/en/blog/announcing-1-2.mdx
  website/docs/en/config/resolve.mdx
  website/docs/en/guide/compatibility/plugin.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/en/guide/features/module-federation.mdx
  website/docs/en/guide/features/web-workers.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/guide/tech/nestjs.mdx
  website/docs/en/guide/tech/preact.mdx
  website/docs/en/guide/tech/react.mdx
  website/docs/en/guide/tech/solid.mdx
  website/docs/en/guide/tech/svelte.mdx
  website/docs/en/guide/tech/vue.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-3.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/blog/announcing-0-6.mdx
  website/docs/zh/blog/announcing-1-2.mdx
  website/docs/zh/config/resolve.mdx
  website/docs/zh/guide/compatibility/plugin.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/module-federation.mdx
  website/docs/zh/guide/features/web-workers.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/guide/tech/nestjs.mdx
  website/docs/zh/guide/tech/preact.mdx
  website/docs/zh/guide/tech/react.mdx
  website/docs/zh/guide/tech/solid.mdx
  website/docs/zh/guide/tech/svelte.mdx
  website/docs/zh/guide/tech/vue.mdx
Labels: team, release: document

#9579 chore: ecosystem benchmark should download artifact from github
  .github/actions/artifact/download/action.yml
  .github/actions/artifact/upload/action.yml
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/ecosystem-ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#9576 ci: install nightly components manually
  .cargo/config.toml
  .github/actions/rustup/action.yml
  .github/actions/rustup/cache/action.yml
  .github/workflows/ci.yml
  rust-toolchain.toml
Labels: team

#9583 test: rollback windows ci profile to dev
  .github/workflows/ci.yml
Labels: team

#9540 docs: add debugging guide
  .vscode/launch.json
  examples/basic/README.md
  examples/basic/index.js
  examples/basic/lib.js
  examples/basic/rspack.config.cjs
  website/docs/en/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/debugging.mdx
Labels: team, release: document

#9600 docs: update quick start guide
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#9590 fix: require_ensure block's dep
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  tests/webpack-test/Compiler.test.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: release: bug fix

#9603 fix: add support for using id placeholder in the webassemblyModuleFilename
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/runtime.rs
  packages/rspack-test-tools/tests/configCases/wasm/name-with-id/index.js
  packages/rspack-test-tools/tests/configCases/wasm/name-with-id/module.js
  packages/rspack-test-tools/tests/configCases/wasm/name-with-id/module2.js
  packages/rspack-test-tools/tests/configCases/wasm/name-with-id/rspack.config.js
  packages/rspack-test-tools/tests/configCases/wasm/name-with-id/wasm.wasm
Labels: release: bug fix

#9610 docs: deprecate `sri` option of HTML plugin
  packages/rspack/src/builtin-plugin/html-plugin/options.ts
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: document

#9612 test: should not output too much logs during the test
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/src/processor/config.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/runner/runner/cjs.ts
  packages/rspack-test-tools/tests/configCases/hooks/stillValidModule/plugins/MyStillValidModulePlugin.js
  packages/rspack-test-tools/tests/configCases/hooks/succeedModule/plugins/MySucceedModulePlugin.js
  packages/rspack-test-tools/tests/configCases/svg/different-module-by-loaders/test.config.js
Labels: team

#9611 refactor: add unconstrained to tokio spawn tasks
  Cargo.lock
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_storage/src/pack/manager/mod.rs
Labels: team

#9591 chore(workflow): add interactive debug test launch
  .vscode/extensions.json
  .vscode/launch.json
Labels: team

#9585 feat(wasm): support wasm compilation
  .github/actions/docker-build/action.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/node_binding/.gitignore
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.js
  crates/node_binding/browser.js
  crates/node_binding/package.json
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/node_binding/wasi-worker-browser.mjs
  crates/node_binding/wasi-worker.mjs
  crates/rspack_allocator/Cargo.toml
  crates/rspack_allocator/src/lib.rs
  crates/rspack_core/Cargo.toml
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_futures/Cargo.toml
  crates/rspack_futures/src/lib.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_napi/Cargo.toml
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/ast/parse.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
  crates/rspack_storage/Cargo.toml
  crates/rspack_tracing/Cargo.toml
  crates/rspack_tracing/src/lib.rs
  crates/rspack_tracing/src/opentelemetry.rs
  npm/wasm32-wasi/package.json
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  pnpm-lock.yaml
  scripts/build-npm.cjs
Labels: release: feature

#9622 test: remove color setting and node warnings
  packages/rspack-test-tools/package.json
Labels: team

#9602 fix: support access to userRequest of ExternalModule
  crates/node_binding/src/module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/user-request/index.js
  packages/rspack-test-tools/tests/configCases/externals/user-request/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/user-request/test.config.js
Labels: release: bug fix

#9604 feat(core): enhanced version hashing to support directory build dependencies
  crates/rspack_core/src/cache/persistent/version.rs
  crates/rspack_fs/src/memory_fs.rs
  crates/rspack_fs/src/native_fs.rs
  crates/rspack_fs/src/read.rs
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/file.js
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/index.js
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/test/.gitkeep
  packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/test/test2/.gitkeep
Labels: release: feature

#9623 chore: add build:wasm scripts
  crates/node_binding/package.json
  pnpm-lock.yaml
Labels: team

#9625 feat: support `entrypoint.getEntrypointChunk()`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/chunk_group.rs
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/chunk_group.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/mod.rs
  crates/rspack_plugin_runtime/src/runtime_module/startup_entrypoint.rs
  packages/rspack-test-tools/tests/configCases/chunks/get-entrypoint-chunk/async.js
  packages/rspack-test-tools/tests/configCases/chunks/get-entrypoint-chunk/index.js
  packages/rspack-test-tools/tests/configCases/chunks/get-entrypoint-chunk/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Entrypoint.ts
Labels: team, release: feature

#9587 fix(core): remove blocking to avoid deadlock for multi compiler
  .github/workflows/ci.yml
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
Labels: team, release: bug fix

#9621 chore: release v1.2.8
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9629 docs: improve publicPath with more details and examples
  website/docs/en/api/runtime-api/module-variables.mdx
  website/docs/en/config/output.mdx
  website/docs/zh/api/runtime-api/module-variables.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: document

#9627 feat(compiler-builder)!: support `BuilderError`
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/basic.rs
  crates/rspack/tests/defaults.rs
  crates/rspack/tests/errors.rs
  crates/rspack/tests/loader.rs
  crates/rspack/tests/snapshots/errors__options-2.snap
  crates/rspack/tests/snapshots/errors__options.snap
  tasks/benchmark/benches/basic.rs
  tasks/benchmark/benches/build_chunk_graph.rs
Labels: team, release: feature, release: breaking change

#9630 fix(commonjs-static): export unprovided variables
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  tests/webpack-test/configCases/library/0-create-library/index.js
  tests/webpack-test/configCases/library/0-create-library/non-external-named.js
  tests/webpack-test/configCases/library/0-create-library/webpack.config.js
  tests/webpack-test/configCases/library/1-use-library/index.js
  tests/webpack-test/configCases/library/1-use-library/node_modules/external-named.js
  tests/webpack-test/configCases/library/1-use-library/webpack.config.js
  tests/webpack-test/configCases/library/cjs-static/index.js
  tests/webpack-test/configCases/library/cjs-static/webpack.config.js
Labels: team, release: bug fix

#9628 test: modify concurrent to 5 to increase the config test concurrency
  packages/rspack-test-tools/src/case/config.ts
  packages/rspack-test-tools/src/case/new-code-splitting.ts
Labels: team

#9641 docs: add `entrypoint.getEntrypointChunk` to documentation
  website/docs/en/types/entrypoint.mdx
  website/docs/zh/types/entrypoint.mdx
Labels: team, release: document

#9646 fix: define with recursion value
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  packages/rspack-test-tools/tests/configCases/parsing/recursion-define/index.js
  packages/rspack-test-tools/tests/configCases/parsing/recursion-define/rspack.config.js
Labels: team, release: bug fix

#9638 fix: revoke dependency clean dependency at module and block
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_library/src/modern_module/import_dependency.rs
  crates/rspack_plugin_library/src/modern_module/reexport_star_external_dependency.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
Labels: team, release: bug fix

#9649 docs: add new customer
  website/project-words.txt
  website/theme/components/Landingpage/WhoIsUsing/assets/verkada.png
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
Labels: release: document

#9637 fix(core): use future_scope to run parallel future
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_futures/Cargo.toml
  crates/rspack_futures/src/lib.rs
  crates/rspack_futures/src/scope.rs
Labels: release: bug fix

#9613 feat: support module subtype in js side
  crates/node_binding/binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/scripts/build.js
  crates/node_binding/src/chunk_graph.rs
  crates/node_binding/src/chunk_group.rs
  crates/node_binding/src/compilation/mod.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/module_graph.rs
  crates/node_binding/src/module_graph_connection.rs
  crates/node_binding/src/modules/concatenated_module.rs
  crates/node_binding/src/modules/context_module.rs
  crates/node_binding/src/modules/external_module.rs
  crates/node_binding/src/modules/macros.rs
  crates/node_binding/src/modules/mod.rs
  crates/node_binding/src/modules/normal_module.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_lazy_compilation.rs
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_napi/src/js_values/one_shot_instance_ref.rs
  packages/rspack-test-tools/tests/configCases/context-module/module-instance/index.js
  packages/rspack-test-tools/tests/configCases/context-module/module-instance/rspack.config.js
  packages/rspack-test-tools/tests/configCases/context-module/module-instance/sub/a.js
  packages/rspack-test-tools/tests/configCases/externals/module-instance/index.js
  packages/rspack-test-tools/tests/configCases/externals/module-instance/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/module-instance/test.config.js
  packages/rspack-test-tools/tests/configCases/externals/user-request/rspack.config.js
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/index.js
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/scripts/check-documentation-coverage.ts
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/ConcatenatedModule.ts
  packages/rspack/src/ContextModule.ts
  packages/rspack/src/ExternalModule.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/ModuleGraph.ts
  packages/rspack/src/ModuleGraphConnection.ts
  packages/rspack/src/NormalModule.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/lazyCompilation.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/lib/LoaderTargetPlugin.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/rspackOptionsApply.ts
  packages/rspack/src/taps/compilation.ts
Labels: team, release: feature

#9658 docs: Writing Plugins Compatible with Rspack and Webpack
  website/docs/en/api/plugin-api/index.mdx
  website/docs/zh/api/plugin-api/index.mdx
Labels: team, release: document

#9660 chore: upgrade @rspack/dev-server and webpack-dev-server
  packages/rspack-cli/package.json
  packages/rspack/package.json
  pnpm-lock.yaml
  tests/e2e/package.json
Labels: team

#9666 feat: implement `module.generator.json.JSONParse`
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_json/src/lib.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  tests/webpack-test/configCases/json/generator-json-parse-false/data.json
  tests/webpack-test/configCases/json/generator-json-parse-false/data1.json
  tests/webpack-test/configCases/json/generator-json-parse-false/index.js
  tests/webpack-test/configCases/json/generator-json-parse-false/webpack.config.js
  tests/webpack-test/configCases/json/generator-json-parse-true/data.json
  tests/webpack-test/configCases/json/generator-json-parse-true/data1.json
  tests/webpack-test/configCases/json/generator-json-parse-true/index.js
  tests/webpack-test/configCases/json/generator-json-parse-true/webpack.config.js
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: feature

#9673 chore: test mac on main branch
  .github/workflows/ci.yml
Labels: team

#9664 feat: support read `NormalModule.loaders`
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/modules/normal_module.rs
  crates/node_binding/src/plugins/js_loader/mod.rs
  crates/node_binding/src/plugins/mod.rs
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/passthrough-loader.js
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js
  website/docs/zh/types/module.mdx
Labels: team, release: feature

#9674 docs: improve docs for amd
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/StatsTestCases.basictest.js
  tests/webpack-test/TestCases.template.js
  website/docs/en/config/other-options.mdx
  website/docs/zh/config/other-options.mdx
Labels: team, release: document

#9671 feat(deps)!: update SWC version to 16.5.0
  Cargo.lock
  Cargo.toml
  packages/rspack/scripts/prepare-container-runtime.js
Labels: team, release: feature, release: breaking change

#9667 feat: incremental for new code splitting
  crates/rspack_core/src/build_chunk_graph/mod.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/remove_available_modules.rs
  crates/rspack_core/src/chunk.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_core/src/options/entry.rs
Labels: team, release: feature

#9680 docs(zh): fix typo in contribute/index.mdx
  website/docs/zh/contribute/index.mdx
Labels: release: document

#9617 feat: add extends property in config options
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/tests/build/config/extends/base/base.rspack.config.js
  packages/rspack-cli/tests/build/config/extends/base/rspack.config.js
  packages/rspack-cli/tests/build/config/extends/base/src/index.js
  packages/rspack-cli/tests/build/config/extends/error/not-found.config.js
  packages/rspack-cli/tests/build/config/extends/extends.test.ts
  packages/rspack-cli/tests/build/config/extends/function/base.rspack.config.js
  packages/rspack-cli/tests/build/config/extends/function/rspack.config.js
  packages/rspack-cli/tests/build/config/extends/function/src/index.js
  packages/rspack-cli/tests/build/config/extends/multiple/base.rspack.config.js
  packages/rspack-cli/tests/build/config/extends/multiple/dev.rspack.config.js
  packages/rspack-cli/tests/build/config/extends/multiple/rspack.config.js
  packages/rspack-cli/tests/build/config/extends/multiple/src/index.js
  packages/rspack-cli/tests/build/config/extends/nested/base.rspack.config.js
  packages/rspack-cli/tests/build/config/extends/nested/core.rspack.config.js
  packages/rspack-cli/tests/build/config/extends/nested/rspack.config.js
  packages/rspack-cli/tests/build/config/extends/nested/src/index.js
  packages/rspack-cli/tests/build/config/extends/node-module/node_modules/mock-rspack-config/index.js
  packages/rspack-cli/tests/build/config/extends/node-module/node_modules/mock-rspack-config/package.json
  packages/rspack-cli/tests/build/config/extends/node-module/rspack.config.js
  packages/rspack-cli/tests/build/config/extends/node-module/src/index.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/_meta.json
  website/docs/en/config/extends.mdx
  website/docs/en/config/index.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/extends.mdx
  website/docs/zh/config/index.mdx
Labels: release: feature

#9677 refactor: remove async-scope
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/cache/persistent/snapshot/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/utils/iterator_consumer/future.rs
  crates/rspack_core/src/utils/iterator_consumer/rayon_fut.rs
  crates/rspack_futures/Cargo.toml
  crates/rspack_futures/src/lib.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
Labels: team

#9682 chore: remove unused feature for lightningcss
  Cargo.lock
  Cargo.toml
Labels: team

#9688 chore: remove zod from exports
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/index.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationPluginV1.ts
  packages/rspack/src/rspack.ts
Labels: team

#9689 docs: apply new theme colors to the documentation site
  website/theme/index.css
Labels: team, release: document

#9686 chore: disable lto for ci
  Cargo.toml
Labels: team

#9681 feat: externals getResolve callback third argument
  crates/node_binding/binding.d.ts
  crates/node_binding/src/resolver.rs
  crates/node_binding/src/resource_data.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_loader_runner/src/content.rs
  packages/rspack-test-tools/tests/configCases/externals/resolve-callback/index.js
  packages/rspack-test-tools/tests/configCases/externals/resolve-callback/node_modules/external.js
  packages/rspack-test-tools/tests/configCases/externals/resolve-callback/node_modules/package.json
  packages/rspack-test-tools/tests/configCases/externals/resolve-callback/webpack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
  packages/rspack/src/Resolver.ts
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#9661 feat: js api support instranceof AsyncDependenciesBlock
  crates/node_binding/binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/src/async_dependency_block.rs
  crates/node_binding/src/chunk_graph.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/macros.rs
  packages/rspack-test-tools/tests/configCases/compilation/modules/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ConcatenatedModule.ts
  packages/rspack/src/ContextModule.ts
  packages/rspack/src/DependenciesBlock.ts
  packages/rspack/src/ExternalModule.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/NormalModule.ts
  packages/rspack/src/exports.ts
Labels: team, release: feature

#9626 refactor: modify `module.code_generation` to async fn
  Cargo.lock
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/old_cache/occasion/code_generate.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_macros_test/Cargo.toml
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_sri/Cargo.toml
Labels: team

#9693 chore: only keep one bench entry in bench
  tasks/benchmark/benches/benches.rs
  tasks/benchmark/benches/groups/basic_build.rs
  tasks/benchmark/benches/groups/build_chunk_graph.rs
  tasks/benchmark/benches/groups/mod.rs
Labels: team

#9697 fix: remove outdata compilation error
  crates/node_binding/src/compilation/mod.rs
  packages/rspack-test-tools/tests/compilerCases/access-outdated-compilation.js
Labels: team, release: bug fix

#9698 chore: change frozen-lockfile default value to true
  .github/actions/pnpm/install-dependencies/action.yml
Labels: team

#9694 docs: correct `experiments.outputModule` default value
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: document

#9700 refactor: remove `block_on` in rspack_storage
  Cargo.lock
  crates/rspack_storage/Cargo.toml
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/tests/dev.rs
  crates/rspack_storage/tests/error.rs
  crates/rspack_storage/tests/expire.rs
  crates/rspack_storage/tests/lock.rs
Labels: team

#9650 feat: add file permission bits on copy
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack-test-tools/tests/configCases/context-module/module-instance/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/module-instance/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-folder-permissions/index.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-folder-permissions/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-folder-permissions/src/subfolder/nested.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-folder-permissions/src/test.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-glob-permissions/index.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-glob-permissions/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-glob-permissions/src/test1.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-glob-permissions/src/test2.txt
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-permissions/index.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-permissions/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-permissions/src/test.txt
  packages/rspack/src/builtin-plugin/CopyRspackPlugin.ts
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: release: feature

#9702 chore: update rspack-resolver
  Cargo.lock
  Cargo.toml
Labels: team

#9706 chore: disable tokio lifo optimization
  .cargo/config.toml
  crates/node_binding/src/lib.rs
Labels: team

#9704 fix: rename loader item request to loader
  crates/node_binding/binding.d.ts
  crates/node_binding/src/plugins/js_loader/context.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: bug fix

#9695 fix: should convert diagnostic.loc to string
  packages/rspack-test-tools/tests/configCases/errors/push-custom-error/errors.js
  packages/rspack-test-tools/tests/configCases/errors/push-custom-error/index.js
  packages/rspack-test-tools/tests/configCases/errors/push-custom-error/rspack.config.js
  packages/rspack/src/util/index.ts
Labels: team, release: bug fix

#9711 chore: revert "chore: disable tokio lifo optimization"
  .cargo/config.toml
  crates/node_binding/src/lib.rs
Labels: team

#9718 docs: improve loader related documentations
  website/docs/en/api/loader-api/_meta.json
  website/docs/en/api/loader-api/context.mdx
  website/docs/en/api/loader-api/index.mdx
  website/docs/en/api/loader-api/rspack-specific-properties.mdx
  website/docs/en/guide/features/_meta.json
  website/docs/en/guide/features/builtin-lightningcss-loader.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/en/guide/features/plugin.mdx
  website/docs/en/guide/features/web-workers.mdx
  website/docs/zh/api/loader-api/_meta.json
  website/docs/zh/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/index.mdx
  website/docs/zh/api/loader-api/rspack-specific-properties.mdx
  website/docs/zh/guide/features/_meta.json
  website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/plugin.mdx
  website/docs/zh/guide/features/web-workers.mdx
Labels: team, release: document

#9715 release: 1.3.0-beta.0
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9719 docs: polish `extends` configuration and blog titles
  pnpm-lock.yaml
  website/components/WebpackLicense.tsx
  website/docs/en/api/plugin-api/index.mdx
  website/docs/en/api/plugin-api/runtime-plugin-hooks.mdx
  website/docs/en/blog/announcing-0-1.mdx
  website/docs/en/blog/announcing-0-2.mdx
  website/docs/en/blog/announcing-0-3.mdx
  website/docs/en/blog/announcing-0-4.mdx
  website/docs/en/blog/announcing-0-5.mdx
  website/docs/en/blog/announcing-0-6.mdx
  website/docs/en/blog/announcing-0-7.mdx
  website/docs/en/blog/announcing-1-0-alpha.mdx
  website/docs/en/blog/announcing-1-0.mdx
  website/docs/en/blog/announcing-1-1.mdx
  website/docs/en/blog/announcing-1-2.mdx
  website/docs/en/config/extends.mdx
  website/docs/en/config/index.mdx
  website/docs/en/contribute/development/debugging.mdx
  website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx
  website/docs/zh/blog/announcing-0-1.mdx
  website/docs/zh/blog/announcing-0-2.mdx
  website/docs/zh/blog/announcing-0-3.mdx
  website/docs/zh/blog/announcing-0-4.mdx
  website/docs/zh/blog/announcing-0-5.mdx
  website/docs/zh/blog/announcing-0-6.mdx
  website/docs/zh/blog/announcing-0-7.mdx
  website/docs/zh/blog/announcing-1-0-alpha.mdx
  website/docs/zh/blog/announcing-1-0.mdx
  website/docs/zh/blog/announcing-1-1.mdx
  website/docs/zh/blog/announcing-1-2.mdx
  website/docs/zh/config/extends.mdx
  website/package.json
Labels: team, release: document

#9717 refactor: remove `block_on` in devtool
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
Labels: team

#9720 chore: bump swc to v16.7.0
  Cargo.lock
  Cargo.toml
Labels: team

#9722 refactor: remove `block_on` in split chunk name and test
  Cargo.lock
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
  crates/rspack_plugin_limit_chunk_count/src/lib.rs
  crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_remove_duplicate_modules/src/lib.rs
  crates/rspack_plugin_remove_empty_chunks/src/lib.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  crates/rspack_plugin_split_chunks/Cargo.toml
  crates/rspack_plugin_split_chunks/src/options/cache_group_test.rs
  crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: team

#9725 fix: improve diagnostic messages for Subresource Integrity plugin
  crates/rspack_plugin_sri/src/asset.rs
  crates/rspack_plugin_sri/src/lib.rs
Labels: team, release: bug fix

#9714 feat(copyRspackPlugin): align transform api with webpack plugin
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  crates/rspack_plugin_copy/src/lib.rs
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/index.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/src/test.txt
  website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Labels: release: feature

#9620 fix(module_federation_runtime_plugin): add support for root output dir
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  packages/rspack-test-tools/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/bootstrap.js
  packages/rspack-test-tools/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/federation-instance-in-runtime-plugin/test.config.js
Labels: release: bug fix

#9707 fix(rspack_plugin_mf): Track all referenced chunks
  crates/rspack_plugin_mf/src/container/remote_runtime_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
Labels: release: bug fix

#9735 test: enable concurrent mode of `block_on` related test cases
  packages/rspack-test-tools/tests/configCases/asset/filename/test.config.js
  packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/test.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-4376/test.config.js
Labels: team

#9712 fix: source map line mapping bug
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#9746 docs: add afterProcessAssets and shouldEmit example
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
Labels: team, release: document

#9734 chore: add rayon worker name and forbid block_on
  Cargo.lock
  clippy.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/src/lib.rs
  crates/rspack_core/src/utils/fast_actions.rs
  crates/rspack_futures/src/scope.rs
Labels: team

#9749 docs: add guide for assets base path
  website/docs/en/config/output.mdx
  website/docs/en/guide/features/_meta.json
  website/docs/en/guide/features/asset-base-path.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/guide/features/_meta.json
  website/docs/zh/guide/features/asset-base-path.mdx
Labels: team, release: document

#9736 feat: introduce par_iter_then_collect
  crates/rspack_futures/Cargo.toml
  crates/rspack_futures/src/lib.rs
Labels: release: feature

#9757 refactor: remove blocking_call_with_sync in module layer filter
  crates/node_binding/src/raw_options/raw_split_chunks/mod.rs
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: team

#9758 refactor: async ids hooks and remove blocking in progress plugin
  Cargo.lock
  crates/node_binding/src/raw_options/raw_builtins/raw_progress.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
  crates/rspack_ids/src/named_chunk_ids_plugin.rs
  crates/rspack_ids/src/named_module_ids_plugin.rs
  crates/rspack_ids/src/natural_chunk_ids_plugin.rs
  crates/rspack_ids/src/natural_module_ids_plugin.rs
  crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
  crates/rspack_plugin_dll/src/flag_all_modules_as_used_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_progress/Cargo.toml
  crates/rspack_plugin_progress/src/lib.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  tasks/benchmark/benches/groups/build_chunk_graph.rs
Labels: team

#9760 refactor: remove blocking call in json parser and SRI plugin
  crates/node_binding/src/raw_options/raw_builtins/raw_sri.rs
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  crates/rspack_plugin_sri/src/asset.rs
  crates/rspack_plugin_sri/src/config.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#9772 fix: getter and setter type in module subtype
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/modules/concatenated_module.rs
  crates/node_binding/src/modules/external_module.rs
  crates/node_binding/src/modules/normal_module.rs
Labels: team, release: bug fix

#9750 refactor: async process runtime requirements
  Cargo.lock
  crates/node_binding/src/module.rs
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/old_cache/occasion/process_runtime_requirements.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  crates/rspack_plugin_mf/src/sharing/share_runtime_plugin.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/bundler_info.rs
  crates/rspack_plugin_runtime/src/chunk_prefetch_preload.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module_from_js.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs
  crates/rspack_plugin_wasm/src/loading_plugin.rs
Labels: team

#8876 feat: implement CircularDependencyRspackPlugin
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/mod.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_circular_dependency.rs
  crates/rspack_plugin_circular_dependencies/Cargo.toml
  crates/rspack_plugin_circular_dependencies/src/lib.rs
  package.json
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/ignore-circular/a.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/ignore-circular/b.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/import-circular/a.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/import-circular/b.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/import-circular/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/no-cycle/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/require-circular/a.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/require-circular/b.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/require-circular/c.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/require-circular/d.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/require-circular/e.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/require-circular/f.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/stats.err
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/CircularDependencyRspackPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  website/docs/en/plugins/rspack/circular-dependency-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/circular-dependency-rspack-plugin.mdx
Labels: release: feature

#9748 fix(css): local_names may be None
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9726/index.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9726/index.module.css
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9726/rspack.config.js
Labels: release: bug fix

#9774 fix: array in asset info
  crates/node_binding/src/asset.rs
  packages/rspack-test-tools/tests/configCases/compilation/emit-asset/rspack.config.js
Labels: team, release: bug fix

#9777 fix: import-assertion test case should not run in node 16
  tests/webpack-test/configCases/externals/import-assertion/test.filter.js
Labels: team, release: bug fix

#9776 fix: optimize circular-dependency-check log
  Cargo.lock
  README.md
  crates/rspack_plugin_circular_dependencies/Cargo.toml
  crates/rspack_plugin_circular_dependencies/src/lib.rs
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/import-circular/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/stats.err
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/plugins/index.mdx
  website/docs/en/plugins/rspack/circular-dependency-rspack-plugin.mdx
  website/docs/zh/plugins/index.mdx
  website/docs/zh/plugins/rspack/circular-dependency-rspack-plugin.mdx
Labels: release: bug fix

#9773 chore(deps): bump swc to 16.10.0
  Cargo.lock
  Cargo.toml
  crates/rspack_ast/Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  packages/rspack-test-tools/tests/configCases/source-map/verify-es6-minify/index.js
Labels: team

#9784 fix(modern-module): correct count non export star connections
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case5.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case6.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/case5.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/case6.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/index.js
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/rspack.config.js
Labels: team, release: bug fix

#9785 fix: `getModuleId` should return number for deterministic moduleIds
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/src/chunk_graph.rs
  crates/node_binding/src/stats.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_core/src/stats/utils.rs
  crates/rspack_ids/src/named_module_ids_plugin.rs
  crates/rspack_plugin_lazy_compilation/Cargo.toml
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-id/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
Labels: team, release: bug fix

#9782 fix: compilation.*_dependencies iterator ignore added items when sync call
  packages/rspack-test-tools/tests/configCases/compilation/update-context-dependencies/index.js
  packages/rspack-test-tools/tests/configCases/compilation/update-context-dependencies/rspack.config.js
  packages/rspack/src/util/MergeCaller.ts
  packages/rspack/src/util/fake.ts
Labels: team, release: bug fix

#9789 fix: call invalid hook for `watching.invalidateWithChangesAndRemovals()`
  packages/rspack-test-tools/tests/compilerCases/invalidation-multi-times.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Watching.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
Labels: team, release: bug fix

#9791 fix: align ExternalModule module type with webpack's implementation
  crates/rspack_core/src/external_module.rs
  packages/rspack-test-tools/tests/configCases/externals/module-instance/rspack.config.js
Labels: release: bug fix

#9775 chore: release v1.3.0-beta.1
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9762 refactor: async lazy compilation test tsfn
  crates/node_binding/src/raw_options/raw_builtins/raw_lazy_compilation.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
Labels: team

#9792 refactor: async parser_and_generator hashing
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
Labels: team

#9801 fix: buildHttp upgrade false
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_builtins/raw_http_uri.rs
  crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri/lockfile.rs
  crates/rspack_plugin_schemes/src/http_uri/mod.rs
  crates/rspack_plugin_schemes/src/lib.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: bug fix

#9799 refactor: async hooks in rust
  crates/node_binding/src/plugins/js_loader/scheduler.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/loader/loader_runner.rs
  crates/rspack_core/src/loader/rspack_loader.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_loader_runner/src/plugin.rs
  crates/rspack_loader_runner/src/runner.rs
  crates/rspack_macros/src/hook.rs
  crates/rspack_macros_test/tests/hook.rs
  crates/rspack_macros_test/tests/plugin.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/provide_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/drive.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_real_content_hash/src/drive.rs
  crates/rspack_plugin_rsdoctor/src/drive.rs
  crates/rspack_plugin_runtime/src/drive.rs
Labels: team

#9803 refactor: clean threadsafe function methods
  crates/node_binding/binding.d.ts
  crates/node_binding/src/module.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_banner.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_circular_dependency.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_html.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_ignore.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_lazy_compilation.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_progress.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_runtime_chunk.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_size_limits.rs
  crates/node_binding/src/raw_options/raw_builtins/raw_sri.rs
  crates/node_binding/src/raw_options/raw_devtool.rs
  crates/node_binding/src/raw_options/raw_dynamic_entry.rs
  crates/node_binding/src/raw_options/raw_external.rs
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/node_binding/src/raw_options/raw_split_chunks/mod.rs
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_napi/src/threadsafe_function.rs
Labels: team

#9806 docs: add `modern-module` docs
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: document

#9808 refactor: async public path
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/compilation/mod.rs
  crates/node_binding/src/filename.rs
  crates/rspack/src/builder/builder_context.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack_core/src/artifacts/code_generation_results.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_html/src/template.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_update_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/runtime.rs
  crates/rspack_util/src/infallible.rs
  crates/rspack_util/src/lib.rs
Labels: team

#9814 refactor: async filename rendering
  Cargo.lock
  crates/node_binding/src/compilation/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_napi/src/threadsafe_function.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_banner/src/lib.rs
  crates/rspack_plugin_copy/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_css/src/utils.rs
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
  crates/rspack_plugin_library/Cargo.toml
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/lib.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/helpers.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_chunk_update_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/get_main_filename.rs
  crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
  crates/rspack_plugin_wasm/src/runtime.rs
Labels: team

#9819 docs: improve lazy compilation guide
  website/docs/en/guide/features/_meta.json
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/zh/guide/features/_meta.json
  website/docs/zh/guide/features/lazy-compilation.mdx
Labels: team, release: document

#9059 feat: enable parallel code splitting by default
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
  crates/rspack_core/src/build_chunk_graph/mod.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/remove_available_modules.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/error-chunk.js
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/skip-building-chunk-graph/rspack.config.js
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/Defaults.unittest.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: feature

#9800 fix(plugin_http): implement respond_with_url_module
  crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
  crates/rspack_plugin_schemes/src/http_uri/lockfile.rs
  crates/rspack_plugin_schemes/src/http_uri/mod.rs
  examples/basic/rspack.config.cjs
  packages/rspack-test-tools/tests/configCases/build-http/asset/index.js
  packages/rspack-test-tools/tests/configCases/build-http/asset/lock-files/lock.json
  packages/rspack-test-tools/tests/configCases/build-http/asset/lock-files/test/https___raw.githubusercontent.com/_web-infra-dev_rspack_55d5d81_packages_rspack-test-tools_tests_configCases_asset__images_file_a661b00f00235b3186ff.png
  packages/rspack-test-tools/tests/configCases/build-http/asset/webpack.config.js
  packages/rspack-test-tools/tests/configCases/build-http/css/__snapshot__/bundle0.css.txt
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/compat-get-default-export/src/index.js
Labels: release: bug fix

#9821 perf: remove useless iterator in new code splitting and some allocations
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
Labels: team, release: performance

#9824 fix: sort diagnostics before push to compilation
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
Labels: team, release: bug fix

#9809 feat: support alias false
  crates/node_binding/binding.d.ts
  crates/node_binding/src/options/raw_resolve.rs
  crates/node_binding/src/resolver.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
  packages/rspack-test-tools/tests/configCases/resolve/alias/index.js
  packages/rspack-test-tools/tests/configCases/resolve/alias/no-alias.js
  packages/rspack-test-tools/tests/configCases/resolve/alias/node_modules/@b/index.js
  packages/rspack-test-tools/tests/configCases/resolve/alias/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#9817 docs: add Rspack 1.3 release blog
  website/docs/en/blog/announcing-1-3.mdx
  website/docs/en/blog/index.mdx
  website/docs/en/config/experiments.mdx
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/blog/announcing-1-3.mdx
  website/docs/zh/blog/index.mdx
  website/docs/zh/guide/features/lazy-compilation.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/project-words.txt
  website/rspress.config.ts
Labels: team, release: document

#9823 chore: release v1.3.0
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9830 docs: add banner to 1.3 blog
  website/docs/en/blog/announcing-1-3.mdx
  website/docs/zh/blog/announcing-1-3.mdx
Labels: team, release: document

#9831 docs: fix lynx link in en blog
  website/docs/en/blog/announcing-1-3.mdx
Labels: team, release: document

#9843 chore: adjust defaultRustTraceFilter to info
  packages/rspack-cli/src/utils/profile.ts
Labels: team

#9846 test(loader-parallel): disable cases that rely on `import()` in node 16
  packages/rspack-test-tools/src/helper/legacy/supportsImportFn.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data-no-passthrough/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data-passthrough/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/async/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/binary-with-source-map/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/issue-webpack-9053/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-error-async/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-raw-string/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-raw/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-string/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/module-build-error/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/pitching-mixed/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/pitching/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/pre-post-loader/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/source-map/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/sync/rspack.config.js
Labels: team

#9853 fix: make Compilation check logs clearer
  packages/rspack/src/Compilation.ts
  packages/rspack/src/NormalModule.ts
  packages/rspack/src/builtin-plugin/JavascriptModulesPlugin.ts
  packages/rspack/src/builtin-plugin/RsdoctorPlugin.ts
  packages/rspack/src/builtin-plugin/RuntimePlugin.ts
  packages/rspack/src/builtin-plugin/html-plugin/hooks.ts
Labels: team, release: bug fix

#9848 feat: support passing `PathBuf` and `&Path` to `Context`
  crates/rspack/src/lib.rs
  crates/rspack_core/src/options/context.rs
Labels: team, release: feature

#9854 ci: alpine apk use stable release branch
  .github/workflows/reusable-build.yml
Labels: team

#9850 chore: bump swc to v18.0.0
  Cargo.lock
  Cargo.toml
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/statsAPICases/basic.js
Labels: team
