Repository web-infra-dev/rspack, pull requests merged in 2025-07, with the labels that each got.

#10845 fix: fix_issuer mgm not found panic
  crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/a1.js
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/a2.js
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/b.js
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/file.js
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/index.js
  packages/rspack-test-tools/tests/hotCases/make/fix-issuer/rspack.config.js
Labels: team, release: bug fix

#10852 fix: fix_issuer compatibility with incomplete module graph
  crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
Labels: team, release: bug fix

#10859 fix(tracing): disable emit tracing event when call cleanup
  crates/rspack_binding_api/src/lib.rs
  packages/rspack-test-tools/tests/compilerCases/tracing.js
Labels: team, release: bug fix

#10342 fix: should union available modules when depend on multiple entry
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/async.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/main.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/rspack.config.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/test.config.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/vendor1.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/vendor2.js
Labels: team, release: bug fix

#10861 fix: try fix node.js 16 crash
  .github/workflows/reusable-build-test.yml
  packages/rspack/src/trace/index.ts
Labels: team, release: bug fix

#10868 fix(core): improve ignorePlugin error report
  crates/rspack_plugin_ignore/src/lib.rs
Labels: team, release: bug fix

#10857 feat(binding-builder): support using custom binding
  .github/workflows/ci-rust.yaml
  .github/workflows/reusable-build-build.yml
  Cargo.lock
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
  crates/rspack_binding_builder_macros/src/lib.rs
  crates/rspack_binding_builder_macros/src/register_plugin.rs
  crates/rspack_binding_builder_testing/.gitignore
  crates/rspack_binding_builder_testing/Cargo.toml
  crates/rspack_binding_builder_testing/binding.js
  crates/rspack_binding_builder_testing/build.rs
  crates/rspack_binding_builder_testing/package.json
  crates/rspack_binding_builder_testing/scripts/build.js
  crates/rspack_binding_builder_testing/src/lib.rs
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/helper/setup-env.ts
  packages/rspack-test-tools/tests/configCases/plugins/binding-builder-plugin/index.js
  packages/rspack-test-tools/tests/configCases/plugins/binding-builder-plugin/test.filter.js
  packages/rspack-test-tools/tests/configCases/plugins/binding-builder-plugin/webpack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  packages/rspack/scripts/codmod/binding.js
  packages/rspack/scripts/codmod/index.js
  packages/rspack/src/builtin-plugin/base.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: release: feature

#10849 refactor: remove export info map on module graph
  crates/rspack_binding_api/src/exports_info.rs
  crates/rspack_binding_api/src/module_graph.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/factorize.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/export_info_setter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
  crates/rspack_core/src/exports/exports_info_setter.rs
  crates/rspack_core/src/exports/mod.rs
  crates/rspack_core/src/exports/referenced_export.rs
  crates/rspack_core/src/exports/target.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team, release: refactor

#10860 feat: set module.ptr to None when cleanup the module
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/module.rs
  crates/rspack_binding_api/src/plugins/js_cleanup_plugin.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  packages/rspack-test-tools/tests/hotCases/module/access-dropped-module/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/module/access-dropped-module/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/module/access-dropped-module/a.js
  packages/rspack-test-tools/tests/hotCases/module/access-dropped-module/b.js
  packages/rspack-test-tools/tests/hotCases/module/access-dropped-module/index.js
  packages/rspack-test-tools/tests/hotCases/module/access-dropped-module/rspack.config.js
Labels: team, release: feature

#10878 perf: use dashmap to reduce lock contention
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
Labels: team, release: performance

#10875 chore: CI enable binary size limit
  .github/actions/binary-limit/action.yml
  .github/actions/binary-limit/binary-limit-script.js
  .github/workflows/ci.yml
  .github/workflows/size-limit.yml
Labels: team

#10884 perf: remove visitor feature of lightningcss
  crates/rspack_loader_lightningcss/Cargo.toml
Labels: team, release: performance

#10502 perf: chunk js api
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/chunk.rs
  crates/rspack_binding_api/src/chunk_graph.rs
  crates/rspack_binding_api/src/chunk_group.rs
  crates/rspack_binding_api/src/compilation/chunks.rs
  crates/rspack_binding_api/src/compilation/mod.rs
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/module.rs
  crates/rspack_binding_api/src/plugins/interceptor.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_banner.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_api/src/runtime.rs
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/hooks.snap.txt
  packages/rspack/etc/core.api.md
  packages/rspack/src/Chunk.ts
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Chunks.ts
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Entrypoint.ts
  packages/rspack/src/builtin-plugin/BannerPlugin.ts
  packages/rspack/src/builtin-plugin/RuntimePlugin.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/taps/compilation.ts
  packages/rspack/src/taps/javascriptModules.ts
  website/docs/en/plugins/webpack/banner-plugin.mdx
  website/docs/zh/plugins/webpack/banner-plugin.mdx
Labels: team, release: performance

#10873 fix: always rebuild error module
  crates/rspack_core/src/module.rs
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/__snapshots__/web/2.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/a.js
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/errors1.js
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/file.js
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/index.js
  packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/loader.js
Labels: team, release: bug fix

#10891 fix: add error handling for invalid browserslist configuration
  packages/rspack-test-tools/tests/configCases/target/invalid-browserslist/errors.js
  packages/rspack-test-tools/tests/configCases/target/invalid-browserslist/index.js
  packages/rspack-test-tools/tests/configCases/target/invalid-browserslist/rspack.config.js
  packages/rspack/src/config/target.ts
Labels: team, release: bug fix

#10892 fix(wasm): use `parking_lot` nightly to avoid panic in tests
  Cargo.lock
  crates/rspack_binding_api/Cargo.toml
Labels: team, release: bug fix

#10894 perf: parallel create map assets
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
Labels: team, release: performance

#10897 feat: support base64 hash digest for css local ident name
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/utils/hash.rs
  packages/rspack-test-tools/tests/configCases/css/local-ident-name/index.js
  packages/rspack-test-tools/tests/configCases/css/local-ident-name/index.module.css
  packages/rspack-test-tools/tests/configCases/css/local-ident-name/rspack.config.js
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: feature

#10896 feat: render css runtime module with dojang
  crates/rspack_plugin_css/src/runtime/css_loading.ejs
  crates/rspack_plugin_css/src/runtime/css_loading_with_hmr.ejs
  crates/rspack_plugin_css/src/runtime/css_loading_with_loading.ejs
  crates/rspack_plugin_css/src/runtime/css_loading_with_prefetch.ejs
  crates/rspack_plugin_css/src/runtime/css_loading_with_prefetch.js
  crates/rspack_plugin_css/src/runtime/css_loading_with_preload.ejs
  crates/rspack_plugin_css/src/runtime/css_loading_with_preload.js
  crates/rspack_plugin_css/src/runtime/mod.rs
Labels: team, release: feature

#10901 feat(wasm): align panic handler with native
  crates/rspack_binding_api/src/lib.rs
Labels: team, release: feature

#10895 fix: upgrade swc_core to 30.0.2
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#10902 fix: break cycle for type reexports check
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/index.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/reexport-cycle.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/warnings.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/with-cycle.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant/warnings.js
Labels: team, release: bug fix

#10900 refactor: remove js stats warning
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/stats.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/raw-warning.err
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/stats.err
  packages/rspack/etc/core.api.md
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/StatsFactory.ts
  packages/rspack/src/stats/statsFactoryUtils.ts
Labels: team, release: refactor

#10888 perf: improve parallelism of real content hash plugin
  Cargo.lock
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/lib.rs
  packages/rspack-test-tools/tests/hashCases/real-content-hash-consistent/test.filter.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-fullhash/test.filter.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-md4/test.filter.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-sha256/test.filter.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-xxhash64/test.filter.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash/test.filter.js
Labels: team, release: performance

#10906 perf: parallelize getting full module names in the deterministic module ids plugin
  crates/rspack_ids/src/deterministic_module_ids_plugin.rs
Labels: team, release: performance

#10908 perf: cache ordered modules ids while sorting chunks
  crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_ids/src/named_chunk_ids_plugin.rs
  crates/rspack_ids/src/natural_chunk_ids_plugin.rs
  crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
Labels: team, release: performance

#10910 perf: parallelize getting source sizes in size limit plugin
  Cargo.lock
  crates/rspack_plugin_size_limits/Cargo.toml
  crates/rspack_plugin_size_limits/src/lib.rs
Labels: team, release: performance

#10907 fix: use AhoCorasick for real content hash
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/lib.rs
Labels: team, release: bug fix

#10912 perf: parallelize processing chunk hashes
  crates/rspack_core/src/compiler/compilation.rs
Labels: team, release: performance

#10913 docs: upgrade Rspress-2.0.0-beta.19
  pnpm-lock.yaml
  website/docs/en/_nav.json
  website/docs/en/blog/announcing-1-0-alpha.mdx
  website/docs/en/config/context.mdx
  website/docs/en/guide/tech/preact.mdx
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/_nav.json
  website/docs/zh/api/runtime-api/module-methods.mdx
  website/docs/zh/blog/announcing-1-0-alpha.mdx
  website/docs/zh/config/context.mdx
  website/docs/zh/guide/tech/preact.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
  website/package.json
Labels: team, release: document

#10916 fix(deps): update swc to 30.1.2
  Cargo.lock
  Cargo.toml
Labels: team, release: bug fix

#10890 feat: pass WebpackError to ignoreWarnings
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/compilation/mod.rs
  crates/rspack_binding_api/src/stats.rs
  crates/rspack_core/src/stats/mod.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/a.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/b.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/index.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/loader.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Stats.ts
  packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
  packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
  packages/rspack/src/stats/StatsFactory.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#10917 chore: release v1.4.4
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10921 chore(workflow): skip ecosystem CI and benchmark in forked repos
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/ecosystem-ci.yml
Labels: team

#10926 chore: enable plugin feature for RA
  .vscode/settings.json
Labels: team

#10933 fix: type error with the pre-bundled watchpack package
  .prettierignore
  packages/rspack/prebundle.config.mjs
  packages/rspack/tsconfig.api.extractor.json
Labels: team, release: bug fix

#10929 fix: js api module readable identifier
  crates/rspack_binding_api/src/module.rs
  packages/rspack-test-tools/tests/configCases/normal-module/readable-identifier/bar.js
  packages/rspack-test-tools/tests/configCases/normal-module/readable-identifier/index.js
  packages/rspack-test-tools/tests/configCases/normal-module/readable-identifier/node_modules/foo/index.js
  packages/rspack-test-tools/tests/configCases/normal-module/readable-identifier/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/normal-module/readable-identifier/rspack.config.js
Labels: team, release: bug fix

#10934 chore(ci): add size threadhold
  .github/actions/binary-limit/action.yml
  .github/actions/binary-limit/binary-limit-script.js
  .github/workflows/ci.yml
  .github/workflows/size-limit.yml
Labels: team

#10869 chore(ci): config testing `fail-fast` to false
  .github/workflows/reusable-build-test.yml
Labels: team

#10939 chore: disable wildcard version
  Cargo.lock
  crates/rspack_tracing_perfetto/Cargo.toml
  deny.toml
Labels: team

#10940 chore(ci): CI.yml failed due to size-limit skipped
  .github/workflows/ci.yml
Labels: team

#10832 perf: improve remove_available_modules
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/lib.rs
Labels: team, release: performance

#10945 chore: check workspace duplicate version
  .github/workflows/reusable-rust-test.yml
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_error/Cargo.toml
  crates/rspack_fs/Cargo.toml
  crates/rspack_javascript_compiler/Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_json/Cargo.toml
  crates/rspack_plugin_schemes/Cargo.toml
  deny.toml
  tasks/release-check/Cargo.toml
Labels: team

#10946 chore(build): convert build scripts into Rslib plugins
  packages/rspack/package.json
  packages/rspack/rslib.config.ts
  packages/rspack/scripts/codmod/binding.js
  packages/rspack/scripts/codmod/index.js
  packages/rspack/scripts/prepare-container-runtime.js
  pnpm-lock.yaml
Labels: team

#10953 refactor: move chunk_artifacts occasion to artifact
  crates/rspack_core/src/artifacts/chunk_render_cache_artifact.rs
  crates/rspack_core/src/artifacts/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/rebuild.rs
  crates/rspack_core/src/old_cache/mod.rs
  crates/rspack_core/src/old_cache/occasion/mod.rs
  crates/rspack_core/src/utils/memory_gc.rs
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
Labels: team, release: refactor

#10959 fix: multiRspackOptions should apply `extends` configuration
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/tests/build/config/extends/multiple/rspack.config.js
Labels: team, release: bug fix

#10966 feat(binding-builder): export workspace version
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_javascript_compiler/src/compiler/transform.rs
  crates/rspack_workspace/src/lib.rs
  tasks/codegen/src/main.rs
Labels: team, release: feature

#10965 chore: disable default features by default
  Cargo.lock
  Cargo.toml
Labels: team

#10968 fix: destructuring assignment a call expr
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  packages/rspack-test-tools/tests/normalCases/parsing/destructuring-assignment/index.js
  packages/rspack-test-tools/tests/normalCases/parsing/destructuring-assignment/module.js
  packages/rspack-test-tools/tests/normalCases/parsing/destructuring-assignment/reexport.js
Labels: team, release: bug fix

#10969 refactor: use symbol defined in `binding_api` to ensure the version consistency
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/lib.rs
  packages/rspack/rslib.config.ts
  packages/rspack/src/util/bindingVersionCheck.ts
Labels: team, release: refactor

#10972 chore: rename tasks to xtask
  .taplo.toml
  Cargo.toml
  scripts/README.md
  xtask/README.md
  xtask/benchmark/Cargo.toml
  xtask/benchmark/benches/benches.rs
  xtask/benchmark/benches/build_chunk_graph/random_table.json
  xtask/benchmark/benches/groups/build_chunk_graph.rs
  xtask/benchmark/benches/groups/bundle.rs
  xtask/benchmark/benches/groups/bundle/basic_react.rs
  xtask/benchmark/benches/groups/bundle/threejs.rs
  xtask/benchmark/benches/groups/bundle/util.rs
  xtask/benchmark/benches/groups/mod.rs
  xtask/benchmark/src/lib.rs
  xtask/codegen/Cargo.toml
  xtask/codegen/src/main.rs
  xtask/deny-ext/Cargo.toml
  xtask/deny-ext/README.md
  xtask/deny-ext/src/main.rs
  xtask/release-check/Cargo.toml
  xtask/release-check/src/main.rs
Labels: team

#10977 fix: ensure reexport is backtracked for provided exports
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/index.js
  packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/lib.js
  packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/reexport.js
  packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/warnings.js
Labels: team, release: bug fix

#10976 fix: getModuleChunksIterable was mistakenly deleted
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/rspack.config.js
  packages/rspack/src/ChunkGraph.ts
Labels: team, release: bug fix

#10980 chore: release v1.4.6
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10983 fix: add more info for collect ts info warning
  crates/rspack_loader_swc/src/lib.rs
Labels: team, release: bug fix

#10982 refactor: avoid exposing `Ref` and `RefMut` of `DashMap`
  Cargo.lock
  crates/rspack_binding_api/src/plugins/js_hooks_plugin.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_rsdoctor/Cargo.toml
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_sri/Cargo.toml
  crates/rspack_plugin_sri/src/asset.rs
  crates/rspack_plugin_sri/src/html.rs
  crates/rspack_plugin_sri/src/lib.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
Labels: team, release: refactor

#10984 chore: add default-feaults=false check
  xtask/src/deny_ext/mod.rs
Labels: team

#10990 docs: improve `splitChunks.chunks` and update glossary
  website/docs/en/misc/glossary.mdx
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/misc/glossary.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: team, release: document

#10992 fix: compat non ascii for progress plugin
  Cargo.lock
  crates/rspack_plugin_progress/Cargo.toml
Labels: team, release: bug fix

#10995 chore(ci): size-limit ignore comment error
  .github/actions/binary-limit/binary-limit-script.js
Labels: team

#10989 perf: napi source map serialize and deserialize
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/plugins/js_loader/context.rs
  crates/rspack_binding_api/src/plugins/js_loader/scheduler.rs
  crates/rspack_binding_api/src/source.rs
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: performance

#10962 chore(ci): support ecosystem-ci use different npm in different repo
  .github/workflows/ecosystem-ci.yml
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/rspack.config.js
  packages/rspack/src/util/bindingVersionCheck.ts
Labels: team

#10986 fix: update swc to 31.1.0
  Cargo.lock
  Cargo.toml
Labels: release: bug fix

#10954 fix: tree-shaking unused `RawModule`
  crates/rspack_core/src/context_module_factory.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/raw_module.rs
  tests/webpack-test/configCases/ignore/side-effects/ignored-module.js
  tests/webpack-test/configCases/ignore/side-effects/locales/a.js
  tests/webpack-test/configCases/ignore/side-effects/locales/b.js
  tests/webpack-test/configCases/ignore/side-effects/test.js
  tests/webpack-test/configCases/ignore/side-effects/webpack.config.js
Labels: release: bug fix

#10880 fix: the `--devtool` CLI flag not work as expected
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
  website/docs/en/config/devtool.mdx
  website/docs/zh/config/devtool.mdx
Labels: release: bug fix

#11001 chore: support separated cargo check for crate publishing
  .github/workflows/release-crates.yml
  .github/workflows/reusable-rust-test.yml
  x.mjs
Labels: team

#11013 fix: use regress to parse regex syntax
  Cargo.lock
  Cargo.toml
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
  packages/rspack-test-tools/tests/configCases/context/issue-10889/index.js
Labels: team, release: bug fix

#10844 fix(rstest): bugs
  crates/rspack_plugin_rstest/src/import_dependency.rs
  crates/rspack_plugin_rstest/src/mock_method_dependency.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/rstest/mock/importActual.js
  packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
Labels: team, release: bug fix

#11017 chore: bump crate versions in non-debug non-snapshot releases only
  scripts/release/version.mjs
Labels: team

#11015 chore: renovate update lock for cargo
  .github/renovate.json5
Labels: team

#11010 docs: add open in stacklitz button in README
  README.md
  README.zh-CN.md
Labels: team

#11020 perf: avoid duplicate calculations in executor task
  crates/rspack_core/src/compiler/module_executor/execute.rs
Labels: team, release: performance

#11027 perf: Use release_max_level_info for tracing
  Cargo.lock
  crates/node_binding/Cargo.toml
  crates/node_binding/scripts/build.js
Labels: team, release: performance

#11025 chore: release 1.4.7
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  x.mjs
Labels: team

#11030 fix: chunk_graph_module maybe undefined while compiling
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/stats/mod.rs
  packages/rspack-test-tools/tests/compilerCases/stats.js
Labels: team, release: bug fix

#11042 fix: fix not printing backtrace when panic
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/scripts/build.js
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/src/panic.rs
Labels: team, release: bug fix

#11071 perf(wasm): set lto=fat and cgu=1
  Cargo.toml
Labels: team, release: performance

#11079 fix: remove last builtin:swc-loader warning for collecting ts info
  crates/rspack_loader_swc/src/lib.rs
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: bug fix

#11080 perf: use fxhash for HashMap in napi
  crates/rspack_binding_api/src/chunk.rs
  crates/rspack_binding_api/src/chunk_group.rs
  crates/rspack_binding_api/src/codegen_result.rs
  crates/rspack_binding_api/src/html.rs
  crates/rspack_binding_api/src/options/raw_resolve.rs
  crates/rspack_binding_api/src/plugins/context_replacement.rs
  crates/rspack_binding_api/src/plugins/js_loader/context.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_css_extract.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_html.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_http_uri.rs
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  crates/rspack_binding_api/src/raw_options/raw_module/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_size.rs
  crates/rspack_binding_api/src/trace_event.rs
  crates/rspack_plugin_html/src/config.rs
  crates/rspack_plugin_html/src/tag.rs
  crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
  packages/rspack/src/ChunkGraph.ts
Labels: team, release: performance

#11077 perf: Use build-std for release
  crates/node_binding/scripts/build.js
  rust-toolchain.toml
Labels: team, release: performance

#11092 perf: dedupe derive_more
  Cargo.lock
  Cargo.toml
  crates/rspack_binding_api/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/parser_and_generator.rs
  deny.toml
Labels: team, release: performance

#11078 fix: snapshot not work for renamed files
  crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
  crates/rspack_fs/src/file_metadata.rs
  tests/e2e/cases/persistent-cache/rename-file/a.js
  tests/e2e/cases/persistent-cache/rename-file/b.js
  tests/e2e/cases/persistent-cache/rename-file/index.js
  tests/e2e/cases/persistent-cache/rename-file/index.test.ts
  tests/e2e/cases/persistent-cache/rename-file/rspack.config.js
  tests/e2e/fixtures/fileAction.ts
  tests/e2e/fixtures/rspack.ts
Labels: team, release: bug fix

#11050 fix: works with async mock factory
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_rstest/src/mock_method_dependency.rs
  crates/rspack_plugin_rstest/src/mock_module_id_dependency.rs
  crates/rspack_plugin_rstest/src/module_path_name_dependency.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
  packages/rspack-test-tools/tests/configCases/rstest/mock/test.js
Labels: team, release: bug fix

#11094 chore: setup rpath for sftrace
  Cargo.lock
  crates/node_binding/build.rs
Labels: team

#11091 perf(wasm): use build-std for release-wasi
  crates/node_binding/scripts/build.js
Labels: release: performance

#11098 fix: change request at before resolve for mf
  crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
  packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/a.js
  packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/bootstrap.js
  packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/index.js
  packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/rspack.config.js
Labels: team, release: bug fix

#10524 feat(plugin_mf): Module Hoisting, Entry initialization via __webpack_require__.x, Custom Hooks
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_mf.rs
  crates/rspack_plugin_mf/Cargo.toml
  crates/rspack_plugin_mf/src/container/container_plugin.rs
  crates/rspack_plugin_mf/src/container/embed_federation_runtime_module.rs
  crates/rspack_plugin_mf/src/container/embed_federation_runtime_plugin.rs
  crates/rspack_plugin_mf/src/container/federation_data_runtime_module.rs
  crates/rspack_plugin_mf/src/container/federation_modules_plugin.rs
  crates/rspack_plugin_mf/src/container/federation_runtime_dependency.rs
  crates/rspack_plugin_mf/src/container/hoist_container_references_plugin.rs
  crates/rspack_plugin_mf/src/container/mod.rs
  crates/rspack_plugin_mf/src/container/module_federation_runtime_plugin.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/lib.rs
  packages/rspack-cli/tests/utils/test-utils.ts
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/App.js
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/ComponentA.js
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/node_modules/react.js
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/test.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/0-container-full/upgrade-react.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/App.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/ComponentB.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/ComponentC.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/index.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/node_modules/package.json
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/node_modules/react.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/package.json
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/rspack.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/test.config.js
  packages/rspack-test-tools/tests/configCases/container-1-5/multiple-runtime-chunk/upgrade-react.js
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
  packages/rspack/src/container/index.ts
Labels: release: feature

#11086 fix: should match `resource` instead of `identifier`
  crates/rspack_plugin_circular_dependencies/src/lib.rs
  packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
  website/docs/en/plugins/rspack/circular-dependency-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/circular-dependency-rspack-plugin.mdx
Labels: release: bug fix

#11108 fix: should allow `externalHelpers: false`
  crates/rspack_loader_swc/Cargo.toml
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-default/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-default/lib.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-default/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-false/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-false/lib.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-false/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-true/index.js
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-true/lib.ts
  packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-true/rspack.config.js
Labels: release: bug fix

#11102 perf: napi resolve request
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/resolver.rs
  packages/rspack-test-tools/tests/configCases/resolver/resolve/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Resolver.ts
Labels: release: performance

#11109 feat: support SwcJsMinimizerRspackPlugin specifying ECMAScript version
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11057/index.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11057/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11057/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
  website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
Labels: release: feature

#11099 feat(rstest): strip import_call as first arg in mock function
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/rstest/mock/mockFirstArgIsImport.js
  packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
  packages/rspack-test-tools/tests/configCases/rstest/mock/src/__mocks__/baz.js
  packages/rspack-test-tools/tests/configCases/rstest/mock/src/barrel.js
  packages/rspack-test-tools/tests/configCases/rstest/mock/src/baz.js
Labels: team, release: feature

#11111 perf: get resolve in external plugin
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
Labels: team, release: performance

#11113 perf: parallel set sync modules
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
Labels: team, release: performance

#11119 feat: rspack_storage support reset
  crates/rspack_core/src/cache/persistent/storage/memory.rs
  crates/rspack_storage/src/lib.rs
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/mod.rs
Labels: team, release: feature

#11118 chore(wasm): bump @napi-rs/cli and @napi-rs/wasm-runtime
  crates/node_binding/package.json
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/node_binding/wasi-worker-browser.mjs
  crates/rspack_binding_builder_testing/package.json
  npm/wasm32-wasi/package.json
  pnpm-lock.yaml
Labels: team

#11121 chore: no need to add code owner for test cases folder
  .github/CODEOWNERS
Labels: team

#11120 refactor: remove cache from compilation and use mutable self in cache trait
  crates/rspack_core/src/cache/disable.rs
  crates/rspack_core/src/cache/mod.rs
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/compiler/rebuild.rs
  xtask/benchmark/benches/groups/build_chunk_graph.rs
Labels: team, release: refactor

#11110 perf: parallel process exports spec
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports/export_info_setter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/exports_info_setter.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
Labels: team, release: performance

#11144 fix: external resolve esm module
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  packages/rspack-test-tools/tests/configCases/externals/get-resolve/index.js
  packages/rspack-test-tools/tests/configCases/externals/get-resolve/node_modules/foo/index.cjs
  packages/rspack-test-tools/tests/configCases/externals/get-resolve/node_modules/foo/index.mjs
  packages/rspack-test-tools/tests/configCases/externals/get-resolve/node_modules/foo/package.json
  packages/rspack-test-tools/tests/configCases/externals/get-resolve/rspack.config.js
Labels: team, release: bug fix

#11132 perf: napi communication
  Cargo.lock
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/src/build_info.rs
  crates/rspack_binding_api/src/compilation/mod.rs
  crates/rspack_binding_api/src/dependency.rs
  crates/rspack_binding_api/src/module.rs
  crates/rspack_binding_api/src/module_graph.rs
  crates/rspack_binding_api/src/modules/concatenated_module.rs
  crates/rspack_binding_api/src/modules/context_module.rs
  crates/rspack_binding_api/src/modules/external_module.rs
  crates/rspack_binding_api/src/modules/macros.rs
  crates/rspack_binding_api/src/modules/normal_module.rs
  crates/rspack_binding_api/src/normal_module_factory.rs
  crates/rspack_binding_api/src/plugins/interceptor.rs
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  crates/rspack_binding_api/src/resource_data.rs
  crates/rspack_core/src/module_graph/mod.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/taps/normalModuleFactory.ts
Labels: team, release: performance

#11067 refactor: disable parallel code splitting by default
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/build_chunk_graph/mod.rs
  crates/rspack_ids/src/id_helpers.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/entry-runtime-error/raw-error.err
  packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: refactor

#11156 chore: release v1.4.10
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#11140 perf: enhance native watcher with customizable ignore patterns
  Cargo.lock
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/native_watcher.rs
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/watcher/analyzer/directories.rs
  crates/rspack_fs/src/watcher/analyzer/root.rs
  crates/rspack_fs/src/watcher/executor.rs
  crates/rspack_fs/src/watcher/ignored.rs
  crates/rspack_fs/src/watcher/mod.rs
  crates/rspack_fs/src/watcher/path_manager.rs
  crates/rspack_fs/src/watcher/scanner.rs
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/src/case/nativeWatcher.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack/package.json
  packages/rspack/prebundle.config.mjs
  packages/rspack/src/NativeWatchFileSystem.ts
  pnpm-lock.yaml
Labels: team, release: performance

#11169 fix: should not enable `exportedEnum` by default
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant/index.ts
  packages/rspack/src/builtin-loader/swc/collectTypeScriptInfo.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: bug fix

#11165 chore(deps): update Rspress to v2.0.0-beta.22
  pnpm-lock.yaml
  website/components/ApiMeta.tsx
  website/components/CommunityCompatibleTable.tsx
  website/components/DeprecationTable.tsx
  website/components/PluginSupportStatusTable.tsx
  website/components/PropertyType.tsx
  website/components/RandomMemberList.tsx
  website/components/WebpackLicense.tsx
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
  website/hooks/useLocation.ts
  website/package.json
  website/rspress.config.ts
  website/theme/components/HomeFooter/index.tsx
  website/theme/components/Landingpage/FullyFeatured/index.tsx
  website/theme/components/Landingpage/Hero/index.tsx
  website/theme/components/Landingpage/ToolStack/index.tsx
  website/theme/components/Landingpage/WhoIsUsing/index.tsx
  website/theme/components/Landingpage/WhyRspack/index.tsx
  website/theme/i18n/index.ts
  website/theme/index.tsx
Labels: team

#11166 revert: "revert: perf: napi communication (#11132) (#11162)"
  Cargo.lock
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/src/build_info.rs
  crates/rspack_binding_api/src/compilation/mod.rs
  crates/rspack_binding_api/src/dependency.rs
  crates/rspack_binding_api/src/module.rs
  crates/rspack_binding_api/src/module_graph.rs
  crates/rspack_binding_api/src/modules/concatenated_module.rs
  crates/rspack_binding_api/src/modules/context_module.rs
  crates/rspack_binding_api/src/modules/external_module.rs
  crates/rspack_binding_api/src/modules/macros.rs
  crates/rspack_binding_api/src/modules/normal_module.rs
  crates/rspack_binding_api/src/normal_module_factory.rs
  crates/rspack_binding_api/src/plugins/interceptor.rs
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  crates/rspack_binding_api/src/resource_data.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/taps/normalModuleFactory.ts
Labels: team

#11163 fix: correct cache option in tests
  crates/rspack_ids/src/id_helpers.rs
  tests/webpack-test/watchCases/cache/reexport-mangle/webpack.config.js
Labels: team, release: bug fix

#11173 fix: should add incoming blocks for async entrypoint
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Labels: team, release: bug fix

#11158 refactor(webpack-test): use webpack runner for hot test cases
  tests/webpack-test/HotTestCases.template.js
  tests/webpack-test/helpers/FakeDocument.js
  tests/webpack-test/runner/index.js
Labels: team, release: refactor

#11175 chore: upgrade rspack_resolver to 0.6.1
  Cargo.lock
  Cargo.toml
Labels: team

#11146 chore: use rslint to do typed linting
  .github/workflows/ci-lint.yaml
  package.json
  pnpm-lock.yaml
  rslint.json
Labels: team

#11181 perf: improve ensure min size fit
  crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
Labels: team, release: performance

#11180 perf: improve prepare group by used exports
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: team, release: performance

#11177 perf: replace rwlock with `atomic_refcell`
  Cargo.lock
  Cargo.toml
  crates/rspack_binding_api/src/plugins/js_hooks_plugin.rs
  crates/rspack_plugin_css/Cargo.toml
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/lib.rs
  crates/rspack_plugin_rsdoctor/Cargo.toml
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  crates/rspack_plugin_runtime/Cargo.toml
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_sri/src/lib.rs
Labels: team, release: performance

#11190 chore: upgrade rslint to 0.0.9
  package.json
  pnpm-lock.yaml
  rslint.json
Labels: team

#11178 fix: persistent cache lose module build error
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  packages/rspack-test-tools/src/helper/hot-update/plugin.ts
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/errors.js
  packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/file.js
  packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/index.js
  packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/loader.js
  packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/rspack.config.js
Labels: team, release: bug fix

#11193 feat: support moduleLayer for css-extract
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_extract_css/src/parser_plugin.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/css-extract/module-layer/index.css
  packages/rspack-test-tools/tests/configCases/css-extract/module-layer/index.js
  packages/rspack-test-tools/tests/configCases/css-extract/module-layer/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css-extract/module-layer/test.config.js
Labels: team, release: feature

#11179 perf: improve code splitting
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/build_chunk_graph/mod.rs
  crates/rspack_core/src/chunk_group.rs
Labels: release: performance

#11200 chore: ignore rustc ice reports
  .gitignore
Labels: team

#11176 feat: use zstd to cache compress
  .github/actions/rustup/cargo/action.yml
Labels: team, release: feature

#11124 fix(pnp): add yarn pnp support to read_dir
  crates/rspack_fs/src/native_fs.rs
Labels: release: bug fix

#11204 fix: fix_issuers not clean cycled modules children
  crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/__snapshots__/web/0.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/__snapshots__/web/1.snap.txt
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/a.js
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/b.js
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/c.js
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/d.js
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/file.js
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/index.js
  packages/rspack-test-tools/tests/hotCases/make/issue-10915/rspack.config.js
Labels: team, release: bug fix

#11212 feat(binding-builder): use full path to `napi` bindgen preludes
  crates/rspack_binding_builder_macros/src/register_plugin.rs
Labels: team, release: feature

#11207 fix: sri plugin should process async chunk in async entrypoints
  crates/rspack_plugin_sri/src/asset.rs
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/dyn.js
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/index.js
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/my-worker.worker.js
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/rspack.config.js
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/test.filter.js
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/worker.js
Labels: team, release: bug fix

#11214 perf: improve code splitting part 2
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
Labels: team, release: performance

#11216 docs: improve `resolve.conditionNames` documentation
  packages/rspack/src/config/types.ts
  website/docs/en/config/resolve.mdx
  website/docs/zh/config/resolve.mdx
Labels: team, release: document

#11218 feat: preserve all comments if user use externalize dynamic import
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_library/src/modern_module/import_dependency.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  crates/rspack_util/src/swc.rs
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/main.js
Labels: team, release: feature

#11196 chore: upgrade rslint to v0.0.15
  package.json
  pnpm-lock.yaml
Labels: team

#11229 fix: do not use user_request to match external module
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/bar.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/foo.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/test.config.js
Labels: team, release: bug fix

#11238 fix(types): change HotUpdateStatus from enum to union type
  packages/rspack/module.d.ts
Labels: team, release: bug fix

#11211 feat: add resolver JavaScript API
  Cargo.lock
  Cargo.toml
  crates/node_binding/napi-binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/rspack_resolver/mod.rs
  crates/rspack_binding_api/src/rspack_resolver/options.rs
  packages/rspack-test-tools/tests/compilerCases/resolver-api.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/resolver.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/resolver.mdx
Labels: team, release: feature

#11243 refactor: remove features that are not supported in stable Rust
  crates/rspack_binding_api/src/compilation/mod.rs
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_collections/src/lib.rs
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/cache/persistent/build_dependencies/helper/visitor.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_error/src/emitter.rs
  crates/rspack_error/src/lib.rs
  crates/rspack_ids/src/id_helpers.rs
  crates/rspack_ids/src/lib.rs
  crates/rspack_loader_runner/src/content.rs
  crates/rspack_loader_runner/src/lib.rs
  crates/rspack_macros/src/lib.rs
  crates/rspack_macros/src/merge.rs
  crates/rspack_napi/src/lib.rs
  crates/rspack_napi_macros/src/lib.rs
  crates/rspack_plugin_circular_dependencies/src/lib.rs
  crates/rspack_plugin_css/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_html/src/lib.rs
  crates/rspack_plugin_javascript/src/lib.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/const/if_stmt.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_runtime/src/lib.rs
  crates/rspack_regex/tests/main.rs
  crates/rspack_util/src/lib.rs
Labels: team, release: refactor

#11248 chore(releasing): should not publish testing crates
  crates/rspack_cacheable_test/Cargo.toml
  crates/rspack_loader_testing/Cargo.toml
  crates/rspack_macros_test/Cargo.toml
Labels: team

#11250 chore: add crates.io badge
  README.md
Labels: team
