Repository web-infra-dev/rspack, pull requests merged in 2025-02, with the labels that each got.

#9144 docs: improve HtmlRspackPlugin docs and types
  packages/rspack/src/builtin-plugin/html-plugin/options.ts
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: release: document

#9146 docs: add `compiler.hooks.finishMake`
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
Labels: release: document

#9148 docs: set Open Graph images based on page routes
  website/rspress.config.ts
Labels: team, release: document

#9153 ci: fix corepack key id mismatch
  .github/actions/docker-build/action.yml
  .github/actions/pnpm-cache/action.yml
Labels: team

#9138 fix: correct lazy compilation backend options schema
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#9157 docs: add profile guide using samply
  website/docs/en/contribute/development/profiling.md
  website/docs/zh/contribute/development/profiling.md
  website/project-words.txt
Labels: team, release: document

#9133 perf(deps): update `swc_core` to v13
  Cargo.lock
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/transformer.rs
  crates/rspack_plugin_javascript/src/ast/stringify.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
  crates/rspack_plugin_swc_js_minimizer/Cargo.toml
  crates/rspack_plugin_swc_js_minimizer/src/minify.rs
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: performance

#8903 refactor: path relative in source map plugin
  Cargo.lock
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/path.rs
Labels: team

#9161 fix: should not tree shaking used ident accidentally in composes
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/index.js
  packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/style.module.css
Labels: team, release: bug fix

#9164 chore(renovate): split npm updates into fine-grained PRs
  .github/renovate.json5
Labels: team

#9163 refactor: remove `NormalModule` last_successful_build_meta field
  crates/rspack_core/src/normal_module.rs
Labels: team

#9165 feat: get block chunk group
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_binding_values/src/dependency_block.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-block-chunk-group/foo.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-block-chunk-group/index.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-block-chunk-group/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
Labels: team, release: feature

#9173 fix(types): prebundle `@swc/types` to fix missing dts files
  packages/rspack/etc/core.api.md
  packages/rspack/prebundle.config.mjs
Labels: release: bug fix

#9172 feat: support missing module graph js api
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module_graph.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/module_graph/mod.rs
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-block-index/bar.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-block-index/foo.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-block-index/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-block-index/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-module/foo.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-module/index.js
  packages/rspack-test-tools/tests/configCases/module-graph/get-parent-module/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ModuleGraph.ts
Labels: team, release: feature

#9178 refactor: module.build directly updates build_info and build_meta
  crates/rspack_binding_values/src/raw_options/raw_builtins/raw_dll.rs
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/compiler/make/cutout/fix_build_meta.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_dll/src/flag_all_modules_as_used_plugin.rs
  crates/rspack_plugin_dll/src/lib.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
Labels: team

#9179 docs(typo): Fix rspack.config typo in nestjs
  website/docs/en/guide/tech/nestjs.mdx
  website/docs/zh/guide/tech/nestjs.mdx
Labels: release: document

#9186 docs: support for tabbed code blocks for ESM/CJS toggle
  pnpm-lock.yaml
  website/docs/en/config/context.mdx
  website/docs/en/config/devtool.mdx
  website/docs/en/config/module.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/types/logger.mdx
  website/docs/zh/config/context.mdx
  website/docs/zh/config/devtool.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/types/logger.mdx
  website/package.json
  website/rspress.config.ts
  website/theme/index.css
  website/theme/index.tsx
Labels: team, release: document

#9177 feat: support missing module js api
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/module.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  packages/rspack-test-tools/tests/configCases/module/lib-ident/index.js
  packages/rspack-test-tools/tests/configCases/module/lib-ident/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module/match-resource/index.js
  packages/rspack-test-tools/tests/configCases/module/match-resource/loader.js
  packages/rspack-test-tools/tests/configCases/module/match-resource/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module/resource-resolve-data/index.js
  packages/rspack-test-tools/tests/configCases/module/resource-resolve-data/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
Labels: team, release: feature

#9187 perf(storage): release pack contents after loading
  crates/rspack_storage/src/pack/manager/mod.rs
  crates/rspack_storage/src/pack/strategy/mod.rs
  crates/rspack_storage/src/pack/strategy/split/util.rs
  crates/rspack_storage/src/pack/strategy/split/write_scope.rs
  crates/rspack_storage/tests/release.rs
Labels: team, release: performance

#9188 fix: do not expose `build()` for level-2 options builder
  crates/rspack/src/builder/mod.rs
  crates/rspack/src/builder/target.rs
  tasks/benchmark/benches/build_chunk_graph.rs
Labels: team, release: bug fix

#9116 fix: align default options with JS
  .taplo.toml
  Cargo.lock
  Cargo.toml
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/defaults.rs
  crates/rspack/tests/snapshots/defaults__default_options-2.snap
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_values/src/raw_options/raw_output.rs
  crates/rspack_core/src/options/entry.rs
  crates/rspack_core/src/options/output.rs
Labels: team, release: bug fix

#9189 feat: layer option support function
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_split_chunks/mod.rs
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-layer-function/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-layer-function/rspack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-layer-function/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#9194 docs: fix `output.workerChunkLoading` link
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: document

#9193 fix(core): initialize resolverFactory early
  packages/rspack-test-tools/tests/configCases/hooks/after-environment/index.js
  packages/rspack-test-tools/tests/configCases/hooks/after-environment/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/config/defaults.ts
Labels: team, release: bug fix

#9199 perf: speedup compile
  .cargo/config.toml
Labels: team, release: performance

#9200 chore(workflow): let renovate pin GitHub Action digests
  .github/renovate.json5
Labels: team

#9201 docs: update profiling guide
  website/docs/en/contribute/development/profiling.md
  website/docs/zh/contribute/development/profiling.md
Labels: team, release: document

#9195 feat: chunkGroup.childrenIterable & dependency.ids
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/module_graph_connection.rs
  crates/rspack_core/src/chunk_group.rs
  packages/rspack-test-tools/tests/configCases/dependency/ids/foo.js
  packages/rspack-test-tools/tests/configCases/dependency/ids/index.js
  packages/rspack-test-tools/tests/configCases/dependency/ids/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGroup.ts
  packages/rspack/src/Dependency.ts
  packages/rspack/src/ModuleGraphConnection.ts
Labels: team, release: feature

#9211 docs: rewrite configure Rspack section
  website/docs/en/config/externals.mdx
  website/docs/en/config/index.mdx
  website/docs/zh/config/externals.mdx
  website/docs/zh/config/index.mdx
Labels: team, release: document

#9208 fix(core): don't swallowing exceptions in stats.toJson
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#9216 fix: ignore generator options for `asset/source` module type
  packages/rspack/src/config/adapter.ts
  tests/webpack-test/configCases/contenthash/assets/test.filter.js
Labels: release: bug fix

#9215 docs: improve FlagDependencyExportsPlugin for large JSON by depth
  website/docs/en/config/module.mdx
  website/docs/zh/config/module.mdx
Labels: release: document

#9218 docs: correct splitChunks chunk.name
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: team, release: document

#9220 docs: link to Tailwind CSS v4 documentation
  website/docs/en/guide/tech/css.mdx
  website/docs/zh/guide/tech/css.mdx
Labels: team, release: document

#9222 refactor: get plugin hooks by compilation id
  crates/node_binding/src/plugins/mod.rs
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_library/src/amd_library_plugin.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_library/src/system_library_plugin.rs
  crates/rspack_plugin_library/src/umd_library_plugin.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
  crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/runtime_plugin.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
Labels: team

#9166 fix: lazy compilation request handler should filter lazy-compilation request
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
  tests/e2e/cases/css/css-filename/index.test.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: bug fix

#9223 feat(lazy-compilation): support module id for LazyCompilationProxyModule
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
Labels: team, release: feature

#9206 fix: alias sequence order & merge result
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  packages/rspack-test-tools/tests/configCases/compilation/entrypoints/bar.js
  packages/rspack-test-tools/tests/configCases/compilation/entrypoints/foo.js
  packages/rspack-test-tools/tests/configCases/compilation/entrypoints/index.js
  packages/rspack-test-tools/tests/configCases/compilation/entrypoints/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module/alias-sequence-merge/exist.js
  packages/rspack-test-tools/tests/configCases/module/alias-sequence-merge/index.js
  packages/rspack-test-tools/tests/configCases/module/alias-sequence-merge/rspack.config.js
  packages/rspack-test-tools/tests/configCases/module/alias-sequence-order/exist.js
  packages/rspack-test-tools/tests/configCases/module/alias-sequence-order/index.js
  packages/rspack-test-tools/tests/configCases/module/alias-sequence-order/rspack.config.js
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#9231 chore: bump rspack_dojang to 0.1.11
  Cargo.lock
  Cargo.toml
Labels: team

#9221 feat(plugin-css): should handle css layer supports media
  crates/rspack_plugin_css/src/dependency/import.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
  packages/rspack-test-tools/tests/configCases/css/at-import/a.css
  packages/rspack-test-tools/tests/configCases/css/at-import/b.css
  packages/rspack-test-tools/tests/configCases/css/at-import/c.css
  packages/rspack-test-tools/tests/configCases/css/at-import/index.js
  packages/rspack-test-tools/tests/configCases/css/at-import/rspack.config.js
Labels: team, release: feature

#9185 fix: namedChunks / emitAsset js api
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_plugin_dll/Cargo.toml
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_html/src/plugin.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/node_path.rs
  packages/rspack-test-tools/tests/configCases/compilation/emit-asset/index.js
  packages/rspack-test-tools/tests/configCases/compilation/emit-asset/rspack.config.js
  packages/rspack/src/Compilation.ts
Labels: team, release: bug fix

#9234 feat: add native hook of real content hash plugin
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_values/src/raw_options/raw_optimization.rs
  crates/rspack_core/src/options/optimizations.rs
  crates/rspack_plugin_real_content_hash/Cargo.toml
  crates/rspack_plugin_real_content_hash/src/drive.rs
  crates/rspack_plugin_real_content_hash/src/lib.rs
Labels: team, release: feature

#9230 refactor: build info save module asset
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_cacheable/src/with/as_preset/serde_json.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
  crates/rspack_core/src/compiler/module_executor/mod.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  packages/rspack-test-tools/tests/cacheCases/common/module-asset/file.js
  packages/rspack-test-tools/tests/cacheCases/common/module-asset/index.js
  packages/rspack-test-tools/tests/cacheCases/common/module-asset/loader.js
  packages/rspack-test-tools/tests/cacheCases/common/module-asset/rspack.config.js
  packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/interop-test/plugin.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team

#9236 refactor: add compilation id to html hook data
  Cargo.toml
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/html.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_html/Cargo.toml
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_html/src/drive.rs
  crates/rspack_plugin_html/src/plugin.rs
  packages/rspack/src/builtin-plugin/html-plugin/taps.ts
Labels: team

#9233 fix(deps): ⬆️ rspack_resolver 0.5.1
  Cargo.lock
  Cargo.toml
Labels: release: bug fix

#9241 docs: update Rspack roadmap
  website/docs/en/api/javascript-api/index.mdx
  website/docs/en/guide/start/introduction.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/misc/planning/roadmap.mdx
  website/docs/zh/api/javascript-api/index.mdx
  website/docs/zh/guide/start/introduction.mdx
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/misc/planning/roadmap.mdx
  website/project-words.txt
Labels: team, release: document

#9235 fix: use entry arg with match resource
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/raw_options/raw_module/mod.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/module.rs
  packages/rspack-test-tools/tests/configCases/module/function-use-match-resource/index.js
  packages/rspack-test-tools/tests/configCases/module/function-use-match-resource/lib.js
  packages/rspack-test-tools/tests/configCases/module/function-use-match-resource/loader.js
  packages/rspack-test-tools/tests/configCases/module/function-use-match-resource/rspack.config.js
Labels: release: bug fix

#9242 feat: chunk graph get module hash
  crates/node_binding/binding.d.ts
  crates/rspack_binding_values/src/chunk_graph.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/exports_info.rs
  crates/rspack_binding_values/src/runtime.rs
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-hash/index.js
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-hash/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ExportsInfo.ts
  packages/rspack/src/util/runtime.ts
Labels: team, release: feature

#9210 feat: add `--config-loader` CLI option
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/src/utils/options.ts
Labels: release: feature

#9244 fix: introduce AsyncTask, make rebuildModule safer
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/a.js
  packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/index.js
  packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/loader.js
  packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/util/AsyncTask.ts
  website/docs/en/api/javascript-api/compilation.mdx
  website/docs/zh/api/javascript-api/compilation.mdx
Labels: release: bug fix

#9162 chore: enable no-dts-cache by default
  Cargo.lock
  crates/node_binding/scripts/build.js
  crates/rspack_binding_values/Cargo.toml
  crates/rspack_binding_values/build.rs
Labels: team

#9247 fix(core): fix module external not treated as async
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
Labels: team, release: bug fix

#9261 docs: display GitHub button on homepage
  pnpm-lock.yaml
  website/docs/en/misc/planning/roadmap.mdx
  website/docs/zh/misc/planning/roadmap.mdx
  website/package.json
  website/theme/components/Landingpage/Hero/index.tsx
Labels: team, release: document

#9239 fix(css,assets): wrong "publicPath: auto" asset path in windows
  crates/rspack_core/src/options/output.rs
  crates/rspack_plugin_extract_css/src/plugin.rs
  crates/rspack_plugin_javascript/src/runtime.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/utils.rs
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9237/index.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9237/logo.svg
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9237/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9237/style.css
Labels: team, release: bug fix

#9259 fix(deps): govern graceful-fs sourcemap phantom dependencies
  package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
  patches/graceful-fs.patch
  pnpm-lock.yaml
  tests/webpack-test/package.json
Labels: team, release: bug fix

#9263 fix: has async chunks
  crates/rspack_core/src/chunk.rs
  packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/index.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/polyfill.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/rspack.config.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/test.config.js
Labels: team, release: bug fix

#9262 feat: support enabling builtin loaders in compiler builder
  .github/workflows/ci.yml
  Cargo.lock
  crates/rspack/Cargo.toml
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/fixtures/lightningcss/src/index.css
  crates/rspack/tests/fixtures/lightningcss/src/index.js
  crates/rspack/tests/fixtures/preact-refresh/src/index.jsx
  crates/rspack/tests/fixtures/react-refresh/src/index.jsx
  crates/rspack/tests/fixtures/swc/src/index.jsx
  crates/rspack/tests/loader.rs
  crates/rspack_loader_lightningcss/Cargo.toml
  crates/rspack_loader_lightningcss/src/lib.rs
  crates/rspack_loader_lightningcss/src/plugin.rs
  crates/rspack_loader_preact_refresh/Cargo.toml
  crates/rspack_loader_preact_refresh/src/lib.rs
  crates/rspack_loader_preact_refresh/src/plugin.rs
  crates/rspack_loader_react_refresh/Cargo.toml
  crates/rspack_loader_react_refresh/src/lib.rs
  crates/rspack_loader_react_refresh/src/plugin.rs
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/src/plugin.rs
Labels: team, release: feature

#9264 refactor: module diagnostic action move to `Diagnosable` trait
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/repair/build.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs
Labels: team

#9267 perf: one shot ref for class instance
  crates/rspack_binding_values/src/chunk.rs
  crates/rspack_binding_values/src/chunk_group.rs
  crates/rspack_binding_values/src/compilation/mod.rs
  crates/rspack_binding_values/src/dependency.rs
  crates/rspack_binding_values/src/dependency_block.rs
  crates/rspack_binding_values/src/module.rs
  crates/rspack_binding_values/src/module_graph_connection.rs
  crates/rspack_binding_values/src/stats.rs
  crates/rspack_napi/src/js_values/mod.rs
  crates/rspack_napi/src/js_values/one_shot_instance_ref.rs
  crates/rspack_napi/src/js_values/one_shot_value_ref.rs
  crates/rspack_napi/src/lib.rs
Labels: team, release: performance

#9272 test: bump pug v3 and reduce npm dependencies
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/src/processor/normal.ts
  packages/rspack-test-tools/tests/configCases/plugins/html-webpack-plugin/rspack.config.js
  pnpm-lock.yaml
  tests/plugin-test/html-plugin/basic.test.js
  tests/plugin-test/package.json
  tests/webpack-test/TestCases.template.js
  tests/webpack-test/cases/loaders/pug-loader/index.js
  tests/webpack-test/package.json
Labels: team

#9274 test: remove copy-webpack-plugin v5
  packages/rspack-test-tools/package.json
  packages/rspack-test-tools/tests/configCases/plugins/copy-webpack-plugin-v5/index.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-webpack-plugin-v5/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/copy-webpack-plugin-v5/stuff.txt
  pnpm-lock.yaml
  tests/webpack-test/package.json
Labels: team

#9276 docs: update plugin compatibility status
  website/components/CommunityCompatibleTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
Labels: team, release: document

#9275 fix(core): add sourceURL when devtool set to 'eval-source-map'
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/index.js
  packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/rspack.config.js
Labels: team, release: bug fix

#9277 chore(workflow): update version scripts and reduce dependencies
  package.json
  pnpm-lock.yaml
  scripts/package.json
  scripts/release/version.mjs
  website/docs/en/api/runtime-api/module-variables.mdx
  website/docs/en/config/externals.mdx
  website/docs/en/config/output.mdx
  website/docs/zh/api/runtime-api/module-variables.mdx
  website/docs/zh/config/output.mdx
  website/package.json
Labels: team

#9284 docs: reuse antd from `@rstack-dev/doc-ui`
  pnpm-lock.yaml
  website/components/Collapse.tsx
  website/package.json
  website/theme/index.tsx
Labels: team, release: document

#9283 chore: simplify ci workflow
  .github/workflows/ci.yml
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/ecosystem-ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#9291 docs: config-loader CLI option
  website/docs/en/api/cli.mdx
Labels: release: document

#9300 chore: pin codspeed version
  .github/workflows/reusable-build.yml
Labels: team

#9288 chore: use more semantic naming profile
  .github/workflows/ci.yml
  .github/workflows/preview-commit.yml
  .github/workflows/release-canary.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  Cargo.toml
  crates/node_binding/package.json
  crates/node_binding/scripts/build.js
  package.json
  website/docs/en/contribute/development/debugging.mdx
  website/docs/zh/contribute/development/debugging.mdx
  x.mjs
Labels: team

#9301 chore: fix bench ci
  package.json
Labels: team

#9312 chore: add codspeed badge
  README.md
  README.zh-CN.md
Labels: team

#9309 fix: persistent cache remove non-existent modules from make_failed_module
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
Labels: team, release: bug fix

#9308 chore: continue clean up workflow
  .github/actions/rustup/action.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#9302 docs: add `SubresourceIntegrityPlugin`
  packages/rspack/scripts/check-documentation-coverage.ts
  website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx
  website/docs/zh/plugins/rspack/subresource-integrity-plugin.mdx
Labels: team, release: document

#9316 docs: fix Chinese comment in English docs
  website/docs/en/config/output.mdx
Labels: release: document

#9304 revert: Revert "refactor(rust): improve `replace_all_placeholder`"
  crates/rspack_core/src/utils/hash.rs
Labels: team

#9327 refactor: rename Rspack to JsCompiler
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  packages/rspack/src/Compiler.ts
Labels: team

#9331 fix: build cli dev failed
  Cargo.toml
Labels: team, release: bug fix

#9332 chore: remove justfile
  crates/node_binding/package.json
  justfile
  website/docs/en/contribute/development/profiling.md
Labels: team

#9334 ci: cargo shear not found
  .github/workflows/ci.yml
Labels: team

#9248 feat: supports chunkGraph and moduleGraph for cacheGroup.test
  packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/ChunkGraph.ts
  packages/rspack/src/ModuleGraph.ts
  packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/plugins/webpack/split-chunks-plugin.mdx
  website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
Labels: team, release: feature

#9281 refactor: NormalModule.source remove diagnostic data
  crates/rspack_binding_values/src/module.rs
  crates/rspack_core/src/compiler/make/cutout/fix_build_meta.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/raw_module.rs
  crates/rspack_core/src/self_module.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_core/src/stats/struct.rs
  crates/rspack_error/src/diagnostic.rs
  crates/rspack_macros/src/runtime_module.rs
  crates/rspack_plugin_asset/src/lib.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_extract_css/src/css_module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_mf/src/container/container_entry_module.rs
  crates/rspack_plugin_mf/src/container/fallback_module.rs
  crates/rspack_plugin_mf/src/container/remote_module.rs
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
  crates/rspack_plugin_rsdoctor/src/module_graph.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#9338 chore: run bench using release profile
  .github/workflows/ecosystem-benchmark.yml
Labels: team

#9337 fix: force load all symbol
  .cargo/config.toml
  Cargo.toml
Labels: team, release: bug fix

#9339 perf: revert opt-level to 3
  Cargo.toml
Labels: team, release: performance

#9342 fix: initialize lazy compilation backend earlier
  packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
Labels: team, release: bug fix

#9344 docs: fix letter casing of Re.Pack
  website/docs/en/guide/start/quick-start.mdx
Labels: release: document

#9326 fix: allow loaderContext methods to be called independently of context
  packages/rspack/src/loader-runner/index.ts
Labels: release: bug fix

#9346 fix: clear module_execution_results every compilation
  packages/rspack/src/ExecuteModulePlugin.ts
Labels: team, release: bug fix

#9357 docs: update release workflow
  .github/workflows/release-pull-request.yml
  website/docs/en/contribute/development/releasing.md
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/contribute/development/releasing.md
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#9363 ci: add option to test when releasing canary
  .github/workflows/release-canary.yml
Labels: team

#9352 perf: reuse js dependency
  crates/node_binding/binding.d.ts
  crates/node_binding/src/compilation/entries.rs
  crates/node_binding/src/context_module_factory.rs
  crates/node_binding/src/dependency.rs
  crates/node_binding/src/dependency_block.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/module_graph_connection.rs
  crates/rspack_core/src/context_module_factory.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/DependenciesBlock.ts
  packages/rspack/src/Dependency.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/ModuleGraph.ts
  packages/rspack/src/ModuleGraphConnection.ts
Labels: team, release: performance

#9374 docs: enhance compiler run hooks documentation
  website/docs/en/api/javascript-api/index.mdx
  website/docs/en/api/plugin-api/compiler-hooks.mdx
  website/docs/en/contribute/development/releasing.md
  website/docs/zh/api/javascript-api/index.mdx
  website/docs/zh/api/plugin-api/compiler-hooks.mdx
  website/docs/zh/contribute/development/releasing.md
Labels: team, release: document

#9376 docs: fix import SRI statement
  website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx
  website/docs/zh/plugins/rspack/subresource-integrity-plugin.mdx
Labels: team, release: document

#9373 fix: revert linux x86_64 publish to docker
  .github/workflows/reusable-build.yml
Labels: team, release: bug fix

#9348 fix: remove unnecessary path-to-URL conversion in html plugin
  Cargo.lock
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_plugin_html/src/asset.rs
  crates/rspack_plugin_html/src/template.rs
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-with-chinese-path/index.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-with-chinese-path/rspack.config.js
  packages/rspack-test-tools/tests/configCases/builtins/html-favicon-with-chinese-path/资源/favicon-图标.ico
Labels: release: bug fix

#9384 docs: update Dll and SRI plugin status
  website/components/CommunityCompatibleTable.tsx
  website/components/PluginSupportStatusTable.tsx
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx
  website/docs/zh/plugins/rspack/subresource-integrity-plugin.mdx
Labels: team, release: document

#9371 chore(deps): update SWC to 14.0.1
  Cargo.lock
  Cargo.toml
  tests/plugin-test/css-extract/cases/content-entries-with-same-import/expected/one_js.$3eee7f9cec64ca9ffeb3$.css
  tests/plugin-test/css-extract/cases/content-entries-with-same-import/expected/two_js.$2a60141158d03110b825$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryA.$0bda113b53289a19f9ff$.css
  tests/plugin-test/css-extract/cases/contenthash-multiple-entries/expected/entryB.$f24d54f731e648ad3e7a$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/1.main.$2343dba8f37350b808da$.css
  tests/plugin-test/css-extract/cases/contenthash/expected/2.main.$199ace69310b6b57766d$.css
  tests/plugin-test/css-extract/cases/issue-6649/expected/main.js
  tests/plugin-test/css-extract/cases/js-hash/expected/style.$2032f44480c52d8556b2$.2.css
  tests/plugin-test/css-extract/cases/js-hash/expected/style.$8f598b234f360ef39d24$.1.css
  x.mjs
Labels: team

#9285 fix(splitChunks): splitChunks maxSize not work as expected if size of some type is small
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/rspack.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/aaa/50k-1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/aaa/50k-2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/aaa/50k-3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/aaa/50k-4.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/aaa/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/aaa/small.css
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/bbb/50k-1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/bbb/50k-2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/bbb/50k-3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/bbb/50k-4.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/bbb/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/ccc/50k-1.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/ccc/50k-2.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/ccc/50k-3.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/ccc/50k-4.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/ccc/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/index.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/src/small.css
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split-with-css/test.config.js
Labels: team, release: bug fix

#9389 Revert "perf: reuse js dependency"
  crates/node_binding/binding.d.ts
  crates/node_binding/src/compilation/entries.rs
  crates/node_binding/src/context_module_factory.rs
  crates/node_binding/src/dependency.rs
  crates/node_binding/src/dependency_block.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/module_graph_connection.rs
  crates/rspack_core/src/context_module_factory.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/DependenciesBlock.ts
  packages/rspack/src/Dependency.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/ModuleGraph.ts
  packages/rspack/src/ModuleGraphConnection.ts
Labels: team

#9388 chore: release 1.2.5
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9394 fix: sort group by group index
  crates/rspack_plugin_extract_css/src/plugin.rs
Labels: team, release: bug fix

#9392 test(incremental): enable more webpack watch tests
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/case/watch.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/runner/runner/watch.ts
  packages/rspack-test-tools/src/runner/watch.ts
  packages/rspack-test-tools/tests/NewIncremental-watch-webpack.test.js
Labels: team

#9403 perf(loader-runner): memoize resolver creation for improved performance
  packages/rspack/src/loader-runner/index.ts
Labels: release: performance

#9387 fix(type): Change the module in the LazyCompilationOptions from any to Module
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
Labels: release: bug fix

#9406 perf: remove blocking for execute module hook
  crates/node_binding/src/plugins/interceptor.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/module_executor/execute.rs
Labels: team, release: performance

#9414 fix: clean up deps at the beginning of compilation.finish
  crates/rspack_core/src/compiler/compilation.rs
Labels: team, release: bug fix

#9421 ci: use different shared key between normal build and codspeed build
  .github/workflows/reusable-build.yml
Labels: team

#9410 chore(codeowners): update code ownership to match repository structure
  .github/CODEOWNERS
Labels: team

#9419 fix(json): correctly escape unicode characters
  crates/rspack_plugin_json/src/utils.rs
  tests/webpack-test/cases/json/unicode/a.json
  tests/webpack-test/cases/json/unicode/b.json
  tests/webpack-test/cases/json/unicode/c.json
  tests/webpack-test/cases/json/unicode/index.js
Labels: release: bug fix

#9401 ci: run codspeed build in parallel
  .github/workflows/reusable-build.yml
Labels: team

#9425 fix: remove dynamic entry should re-build chunk graph
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/0/index0.js
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/0/index1.js
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/1/index0.js
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/test.config.js
Labels: team, release: bug fix

#9426 chore: move modern module library finish_modules to finish_make
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
Labels: team

#9427 perf: use partition_map to avoid clone
  crates/rspack_core/src/incremental/mutations.rs
Labels: team, release: performance

#9430 chore(workflow): no need to run pnpm cache in rust jobs
  .github/workflows/ci.yml
Labels: team

#9429 ci: only install binding dependencies when building binary
  .github/actions/pnpm-cache/action.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-build.yml
Labels: team

#9439 fix: build error with reserved keywords in CSS modules
  crates/rspack_plugin_css/src/utils.rs
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9432/index.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9432/index.module.css
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-9432/rspack.config.js
Labels: release: bug fix

#9434 test: should not call stats toJson if not necessary
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/stats-output.ts
  packages/rspack-test-tools/src/processor/basic.ts
  packages/rspack-test-tools/src/processor/hash.ts
  packages/rspack-test-tools/src/processor/hot-step.ts
  packages/rspack-test-tools/src/processor/simple.ts
  packages/rspack-test-tools/src/processor/snapshot.ts
  packages/rspack-test-tools/src/processor/stats-api.ts
  packages/rspack-test-tools/src/processor/stats.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/src/type.ts
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-1652/test.config.js
  packages/rspack-test-tools/tests/configCases/module/rspack-issue-5548/test.config.js
  packages/rspack-test-tools/tests/configCases/output/rspack-issue-4338/test.config.js
  packages/rspack-test-tools/tests/configCases/plugins/swc-js-minifier/test.config.js
  packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/test.config.js
  packages/rspack-test-tools/tests/watchCases/chunk-ids/id-equals-name/test.config.js
  packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/test.config.js
  packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/test.config.js
  packages/rspack-test-tools/tests/watchCases/module-ids/update-module/test.config.js
Labels: team

#9442 fix: update CLI flags to use camelCase consistently
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/types.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/build/basic/basic.test.ts
  website/docs/en/api/cli.mdx
  website/docs/zh/api/cli.mdx
Labels: team, release: bug fix

#9422 feat: using dojang to render runtime_template
  crates/rspack_core/src/runtime_template.rs
  crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/compat_get_default_export.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_fake_namespace_object.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/auto_public_path.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/create_fake_namespace_object.ejs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#9445 fix: use persistent cache with module foundation
  crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
  packages/rspack-test-tools/src/helper/loaders/hot-update.ts
  packages/rspack-test-tools/tests/cacheCases/mf/issue-9150/file.js
  packages/rspack-test-tools/tests/cacheCases/mf/issue-9150/index.js
  packages/rspack-test-tools/tests/cacheCases/mf/issue-9150/rspack.config.js
Labels: team, release: bug fix

#9448 fix: persistent cache skip calc modified_files when rebuild
  crates/rspack_core/src/cache/persistent/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/compiler/rebuild.rs
  tasks/benchmark/benches/build_chunk_graph.rs
Labels: team, release: bug fix

#9446 chore: release v1.2.6
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack-tracing/package.json
  packages/rspack/package.json
Labels: team

#9456 fix: hash runtime condition for connection
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/module_graph/connection.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
Labels: team, release: bug fix

#9465 chore: reduce debug symbol size
  Cargo.toml
Labels: team

#9464 fix: unify js assets info type
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/asset.rs
  crates/node_binding/src/compilation/mod.rs
  crates/node_binding/src/filename.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/path_data.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_napi_macros/src/field_names.rs
  crates/rspack_napi_macros/src/getters.rs
  crates/rspack_napi_macros/src/lib.rs
  packages/rspack-test-tools/tests/statsAPICases/child-compiler.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/config/adapterRuleUse.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/util/AssetInfo.ts
  website/docs/en/api/loader-api/context.mdx
  website/docs/en/config/output.mdx
  website/docs/zh/api/loader-api/context.mdx
  website/docs/zh/config/output.mdx
Labels: team, release: bug fix

#9390 fix: commonjs static library mode
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  packages/rspack-test-tools/tests/configCases/library/cjs-static/index.js
  packages/rspack-test-tools/tests/configCases/library/cjs-static/rspack.config.js
  tests/webpack-test/configCases/library/1-use-library/webpack.config.js
Labels: release: bug fix

#9468 fix(cli): failed to run preview with TS config file
  packages/rspack-cli/src/commands/build.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-cli/src/utils/options.ts
  packages/rspack-cli/tests/preview/basic/index.test.ts
  packages/rspack-cli/tests/preview/basic/rspack.config.js
  packages/rspack-cli/tests/preview/basic/src/index.js
  packages/rspack-cli/tests/preview/ts-config-file/index.test.ts
  packages/rspack-cli/tests/preview/ts-config-file/rspack.config.ts
  packages/rspack-cli/tests/preview/ts-config-file/src/index.js
  packages/rspack-cli/tests/utils/test-utils.ts
Labels: team, release: bug fix

#9444 feat: render runtime template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/create_script.rs
  crates/rspack_plugin_runtime/src/runtime_module/create_script_url.rs
  crates/rspack_plugin_runtime/src/runtime_module/define_property_getters.rs
  crates/rspack_plugin_runtime/src/runtime_module/ensure_chunk.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/create_script.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/create_script_url.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/define_property_getters.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/ensure_chunk.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/ensure_chunk_with_inline.ejs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/configCases/rsdoctor/assets/rspack.config.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#9469 test: lazy create stats in runner
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/runner/basic.ts
  packages/rspack-test-tools/src/runner/cache.ts
  packages/rspack-test-tools/src/runner/hot-step.ts
  packages/rspack-test-tools/src/runner/hot.ts
  packages/rspack-test-tools/src/runner/multiple.ts
  packages/rspack-test-tools/src/runner/normal.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/cjs.ts
  packages/rspack-test-tools/src/runner/runner/watch.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
  packages/rspack-test-tools/src/runner/watch.ts
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/pre-order-index/0/index.js
  tests/webpack-test/WatchTestCases.template.js
  tests/webpack-test/watchCases/cache/asset-modules/0/index.js
  tests/webpack-test/watchCases/cache/asset-modules/2/index.js
  tests/webpack-test/watchCases/cache/asset-modules/3/index.js
  tests/webpack-test/watchCases/cache/emit-when-clean/2/index.js
  tests/webpack-test/watchCases/cache/emit-when-clean/3/index.js
  tests/webpack-test/watchCases/cache/emit-without-clean/2/index.js
  tests/webpack-test/watchCases/cache/emit-without-clean/3/index.js
  tests/webpack-test/watchCases/cache/new-split-chunk-entry-node/0/index.js
  tests/webpack-test/watchCases/cache/new-split-chunk-entry-web/0/index.js
  tests/webpack-test/watchCases/long-term-caching/issue-8766-with-cache/0/index.js
  tests/webpack-test/watchCases/long-term-caching/issue-8766-with-cache/1/index.js
  tests/webpack-test/watchCases/long-term-caching/issue-8766/0/index.js
  tests/webpack-test/watchCases/long-term-caching/issue-8766/1/index.js
  tests/webpack-test/watchCases/plugins/automatic-prefetch-plugin-9485/0/index.js
  tests/webpack-test/watchCases/plugins/automatic-prefetch-plugin/0/index.js
  tests/webpack-test/watchCases/plugins/mini-css-extract-plugin/1/index.js
  tests/webpack-test/watchCases/plugins/module-concatenation-plugin/0/index.js
  tests/webpack-test/watchCases/runtime/dynamic-import/0/index.js
  tests/webpack-test/watchCases/runtime/static-import/0/index.js
  tests/webpack-test/watchCases/simple/multi-compiler/0/index.js
  tests/webpack-test/watchCases/warnings/warnings-contribute-to-hash/0/index.js
Labels: team

#9472 chore: mark `compiler.compile` as private method
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/zh/api/javascript-api/compiler.mdx
Labels: team

#9474 ci: save cache in test task
  .github/workflows/reusable-build.yml
Labels: team

#9467 fix: handle css with BOM
  crates/rspack_core/src/utils/mod.rs
  crates/rspack_core/src/utils/remove_bom.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  packages/rspack-test-tools/tests/configCases/css/css-with-bom/index.css
  packages/rspack-test-tools/tests/configCases/css/css-with-bom/index.js
  packages/rspack-test-tools/tests/configCases/css/css-with-bom/rspack.config.js
Labels: release: bug fix

#9478 docs: complete loader context API doc and JSDoc
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapterRuleUse.ts
  website/docs/en/api/loader-api/context.mdx
  website/docs/en/api/loader-api/examples.mdx
  website/docs/zh/api/loader-api/context.mdx
  website/docs/zh/api/loader-api/examples.mdx
  website/project-words.txt
Labels: team, release: document

#9450 feat: render runtime template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
  crates/rspack_plugin_runtime/src/runtime_module/global.rs
  crates/rspack_plugin_runtime/src/runtime_module/has_own_property.rs
  crates/rspack_plugin_runtime/src/runtime_module/rspack_version.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_trusted_types_policy.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_version.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/get_version.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/global.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/has_own_property.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/has_own_property.js
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/rsdoctor/assets/rspack.config.js
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/asset-info.js
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js
  packages/rspack-test-tools/tests/statsAPICases/exports.js
  packages/rspack-test-tools/tests/statsAPICases/nested-modules.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#9487 feat: render runtime template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/public_path.rs
  crates/rspack_plugin_runtime/src/runtime_module/relative_url.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/define_property_getters.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/ensure_chunk.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/ensure_chunk_with_inline.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/public_path.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/relative_url.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_chunk_dependencies.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_entrypoint.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_entrypoint.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_entrypoint_with_async.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/startup_entrypoint_with_async.js
  crates/rspack_plugin_runtime/src/runtime_module/startup_chunk_dependencies.rs
  crates/rspack_plugin_runtime/src/runtime_module/startup_entry_point.rs
  packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
Labels: team, release: feature

#9486 chore: use tmpdir to avoid no space left error
  .github/actions/docker-build/action.yml
  .github/workflows/reusable-build.yml
Labels: team

#9485 docs: fix the reference to process asset stages in examples
  website/docs/en/api/plugin-api/compilation-hooks.mdx
  website/docs/zh/api/plugin-api/compilation-hooks.mdx
Labels: release: document

#9482 fix: rebuild ignore modules contain built-in loader errors
  crates/rspack_core/src/normal_module.rs
  tests/e2e/cases/make/failed_module_by_builtin_loader/index.test.ts
  tests/e2e/cases/make/failed_module_by_builtin_loader/rspack.config.js
  tests/e2e/cases/make/failed_module_by_builtin_loader/src/index.js
  tests/e2e/cases/make/failed_module_by_js_loader/index.test.ts
  tests/e2e/cases/make/failed_module_by_js_loader/loader.js
  tests/e2e/cases/make/failed_module_by_js_loader/rspack.config.js
  tests/e2e/cases/make/failed_module_by_js_loader/src/index.js
Labels: team, release: bug fix

#9452 feat: render require_chunk_loading template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_external_install_chunk.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_external_install_chunk.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr_manifest.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr_manifest.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading_matcher.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_on_chunk_load.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_on_chunk_load.js
Labels: team, release: feature

#9489 test: improve webpack test performance
  tests/webpack-test/ConfigTestCases.template.js
  tests/webpack-test/TestCases.template.js
  tests/webpack-test/WatchTestCases.template.js
Labels: team

#9470 feat(ci): enable cfa
  .github/workflows/release-otp.yml
  package.json
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/auto-public-path/__snapshot__/bundle.json
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/global/__snapshot__/bundle.json
  packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/public-path/__snapshot__/bundle.json
  packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
  pnpm-lock.yaml
  scripts/release/publish.mjs
  x.mjs
Labels: release: feature

#9494 test: improve cli test performance
  packages/rspack-cli/tests/api/type/js-api-cjs.test.ts
  packages/rspack-cli/tests/api/type/js-api-esm.test.mts
  packages/rspack-cli/tests/build/basic/basic.test.ts
  packages/rspack-cli/tests/build/config/config.test.ts
  packages/rspack-cli/tests/build/issue-4467/index.test.ts
  packages/rspack-cli/tests/build/issue-6214/index.test.ts
  packages/rspack-cli/tests/build/issue-6359/index.test.ts
  packages/rspack-cli/tests/build/json/json.test.ts
  packages/rspack-cli/tests/build/plugin-apply-error/plugin-apply-error.test.ts
  packages/rspack-cli/tests/preview/basic/index.test.ts
  packages/rspack-cli/tests/preview/ts-config-file/index.test.ts
  packages/rspack-cli/tests/serve/basic/serve-basic.test.ts
  packages/rspack-cli/tests/serve/flags/serve-flags.test.ts
  packages/rspack-cli/tests/serve/plugin-apply-error/serve-plugin-apply-error.test.ts
Labels: team

#9491 feat: render readfile_chunk_loading template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_external_install_chunk.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_external_install_chunk.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_hmr.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_hmr_manifest.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_hmr_manifest.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_on_chunk_load.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/readfile_chunk_loading_with_on_chunk_load.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading.js
  packages/rspack-test-tools/tests/configCases/rsdoctor/assets/rspack.config.js
Labels: team, release: feature

#9499 chore: cleanup for avoiding meaningless diff with more-js-api-v2
  .github/workflows/ci.yml
  Cargo.lock
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_plugin_copy/Cargo.toml
  crates/rspack_plugin_copy/src/lib.rs
Labels: team

#9496 feat: render jsonp_chunk_loading template with dojang
  crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_callback.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_hmr.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_hmr_manifest.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_on_chunk_load.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_on_chunk_load.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_prefetch.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_prefetch.js
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_preload.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/jsonp_chunk_loading_with_preload.js
  packages/rspack-test-tools/tests/builtinCases/plugin-html/variant/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/__snapshots__/web/1.snap.txt
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: feature

#9475 feat: compiler.run add options to set modifiedFiles and removedFiles
  packages/rspack-test-tools/tests/errorCases/error-test-push.js
  packages/rspack-test-tools/tests/errorCases/error-test-set.js
  packages/rspack-test-tools/tests/errorCases/error-test-shift.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
  packages/rspack-test-tools/tests/errorCases/warning-test-push.js
  packages/rspack-test-tools/tests/errorCases/warning-test-set.js
  packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
  packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/Watching.ts
Labels: team, release: feature

#9502 test: run cli test cases parallel
  package.json
  packages/rspack-cli/tests/build/basic/basic.test.ts
  packages/rspack-cli/tests/build/config/config.test.ts
Labels: team

#9503 docs: compiler.run add option param
  website/docs/en/api/javascript-api/compiler.mdx
  website/docs/zh/api/javascript-api/compiler.mdx
Labels: team, release: document

#9504 feat: add contextInfo.issuerLayer for nmf resolve hooks
  crates/node_binding/binding.d.ts
  crates/node_binding/src/normal_module_factory.rs
  crates/node_binding/src/plugins/interceptor.rs
  packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/index.js
  packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/request.v1.js
  packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/request.v2.js
  packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
  packages/rspack/src/taps/normalModuleFactory.ts
Labels: team, release: feature
