Repository web-infra-dev/rspack, pull requests merged in 2025-08, with the labels that each got.

#10870 feat(wasm): support `@rspack/browser`
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/package.json
  crates/node_binding/scripts/build.js
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_browser/Cargo.toml
  crates/rspack_browser/src/lib.rs
  crates/rspack_browser/src/oneshot.rs
  crates/rspack_browser/src/panic.rs
  crates/rspack_napi/Cargo.toml
  crates/rspack_napi/src/threadsafe_function.rs
  package.json
  packages/rspack-browser/LICENSE
  packages/rspack-browser/package.json
  packages/rspack/package.json
  packages/rspack/rslib.browser.config.ts
  packages/rspack/rslib.config.ts
  packages/rspack/src/browser/buffer.ts
  packages/rspack/src/browser/fs.ts
  packages/rspack/src/browser/index.ts
  packages/rspack/src/browser/service.ts
  packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
  packages/rspack/src/builtin-plugin/html-plugin/plugin.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/env.d.ts
  packages/rspack/src/loader-runner/index.ts
  packages/rspack/src/loader-runner/loadLoader.ts
  packages/rspack/src/loader-runner/utils.ts
  packages/rspack/src/loader-runner/worker.ts
  packages/rspack/src/util/bindingVersionCheck.ts
  packages/rspack/src/util/require.ts
  packages/rspack/tsconfig.browser.json
  packages/rspack/tsconfig.build.json
  pnpm-lock.yaml
  rslint.json
Labels: team, release: feature

#10643 perf: align number hash algorithm with webpack
  crates/rspack_util/src/number_hash.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/samples/mangle-exports/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-id/rspack.config.js
  packages/rspack-test-tools/tests/configCases/css/css-cross-origin-loading-use-credentials/index.js
  packages/rspack-test-tools/tests/configCases/css/css-cross-origin-loading/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/__snapshot__/b.js.txt
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/__snapshot__/e.js.txt
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/__snapshot__/f.js.txt
  packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/__snapshot__/g.js.txt
  packages/rspack-test-tools/tests/configCases/plugins/chunk-modules/__snapshot__/data.json.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#chunkHash/update-hash/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/hooks.snap.txt
  packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/output.snap.txt
  packages/rspack-test-tools/tests/hookCases/javascriptModulesPlugin#chunkHash/update-hash/output.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
  packages/rspack-test-tools/tests/statsAPICases/ids.js
  tests/webpack-test/Compiler.test.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
  tests/webpack-test/configCases/asset-emitted/normal/webpack.config.js
  tests/webpack-test/configCases/css/external/test.config.js
  tests/webpack-test/configCases/mangle/mangle-with-destructuring-assignment/index.js
  tests/webpack-test/configCases/wasm/fetch/test.config.js
  tests/webpack-test/configCases/web/fetch-priority/index.js
Labels: release: performance

#11171 refactor: bench external getResolve & remove ResolveClosureContext
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  tests/bench/ts-react.bench.ts
Labels: team, release: refactor

#11117 feat: lazy make for reexport in side effects free barrel file
  crates/node_binding/napi-binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_api/src/raw_options/raw_experiments/mod.rs
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/compilation/make/artifact.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/add.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/build.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/lazy.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/mod.rs
  crates/rspack_core/src/compilation/make/graph_updater/repair/process_dependencies.rs
  crates/rspack_core/src/compilation/make/lazy_barrel_artifact.rs
  crates/rspack_core/src/compilation/make/mod.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/dependency/module_dependency.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_core/src/options/experiments/mod.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_plugin_dll/src/flag_all_modules_as_used_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_rsdoctor/Cargo.toml
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/index.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/mixed-barrel/a.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/mixed-barrel/b.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/mixed-barrel/c.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/mixed-barrel/index.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/named-barrel/a.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/named-barrel/b.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/named-barrel/index.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/nested-barrel/a.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/nested-barrel/b.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/nested-barrel/c.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/nested-barrel/index.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/package.json
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/star-barrel/a.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/star-barrel/b.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/star-barrel/c.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/star-barrel/index.js
  packages/rspack-test-tools/tests/configCases/lazy-barrel/basic/test.filter.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/schema/config.ts
Labels: team, release: feature

#11245 fix: JsResolverFactory should cache Resolver instance based on different options
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/options/raw_resolve.rs
  crates/rspack_binding_api/src/resolver.rs
  crates/rspack_binding_api/src/resolver_factory.rs
  crates/rspack_core/src/dependency/dependency_category.rs
  packages/rspack-test-tools/tests/configCases/resolver-factory/by-dependency/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/by-dependency/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/cache-for-get/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/cache-for-get/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/cache-for-resolver-with-options/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/cache-for-resolver-with-options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/get-with-options/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/get-with-options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/resolve/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/resolve/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/restriction/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/restriction/node_modules/style/index.css
  packages/rspack-test-tools/tests/configCases/resolver-factory/restriction/node_modules/style/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/restriction/node_modules/style/package.json
  packages/rspack-test-tools/tests/configCases/resolver-factory/restriction/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/with-fragment/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/with-fragment/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/with-query/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/with-query/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/NormalModuleFactory.ts
  packages/rspack/src/Resolver.ts
  packages/rspack/src/ResolverFactory.ts
  packages/rspack/src/config/adapter.ts
Labels: team, release: bug fix

#11233 perf: improve bundle splitting part 2
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: team, release: performance

#11260 fix: lifetime error
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
Labels: team, release: bug fix

#11258 refactor: move builtin loader registration to plugin
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/plugins/js_loader/resolver.rs
Labels: team, release: refactor

#11262 fix: avoid render weak import dependency
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
Labels: team, release: bug fix

#11264 perf: improve process concatenated configurations
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team, release: performance

#11256 fix: buildDependencies skip resolve nodejs builtin module
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_api/src/options/raw_resolve.rs
  crates/rspack_core/src/cache/persistent/build_dependencies/helper/mod.rs
  crates/rspack_core/src/options/resolve/clever_merge.rs
  crates/rspack_core/src/options/resolve/mod.rs
  crates/rspack_core/src/resolver/mod.rs
  crates/rspack_core/src/resolver/resolver_impl.rs
Labels: team, release: bug fix

#11210 fix: handle unwatch errors gracefully and improve native watcher integration
  Cargo.lock
  crates/rspack_fs/Cargo.toml
  crates/rspack_fs/src/watcher/disk_watcher.rs
  crates/rspack_fs/src/watcher/executor.rs
  crates/rspack_fs/src/watcher/path_manager.rs
  packages/rspack-test-tools/jest.config.js
  packages/rspack-test-tools/src/case/index.ts
  packages/rspack-test-tools/src/case/native-watcher.ts
  packages/rspack-test-tools/src/processor/watch.ts
  packages/rspack-test-tools/tests/NativeWatcher-webpack.test.js
  packages/rspack-test-tools/tests/NativeWatcher.test.js
  packages/rspack/src/NativeWatchFileSystem.ts
  packages/rspack/src/node/NodeEnvironmentPlugin.ts
Labels: team, release: bug fix

#11269 chore: ignore moduleFederationDefaultRuntime.js in rslint
  package.json
  rslint.json
Labels: team

#11254 chore(wasm): release `@rspack/browser`
  .github/workflows/reusable-build-build.yml
  crates/node_binding/scripts/build.js
  packages/rspack-browser/package.json
  packages/rspack/rslib.browser.config.ts
  pnpm-lock.yaml
Labels: team

#11263 refactor: limit exported symbols in `rspack_binding_api`
  Cargo.lock
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/README.md
  crates/rspack_binding_api/src/allocator.rs
  crates/rspack_binding_api/src/asset_condition.rs
  crates/rspack_binding_api/src/async_dependency_block.rs
  crates/rspack_binding_api/src/build_info.rs
  crates/rspack_binding_api/src/chunk.rs
  crates/rspack_binding_api/src/chunk_graph.rs
  crates/rspack_binding_api/src/chunk_group.rs
  crates/rspack_binding_api/src/compilation/chunks.rs
  crates/rspack_binding_api/src/compilation/code_generation_results.rs
  crates/rspack_binding_api/src/compilation/diagnostics.rs
  crates/rspack_binding_api/src/compilation/entries.rs
  crates/rspack_binding_api/src/compilation/mod.rs
  crates/rspack_binding_api/src/context_module_factory.rs
  crates/rspack_binding_api/src/dependencies/mod.rs
  crates/rspack_binding_api/src/dependency.rs
  crates/rspack_binding_api/src/error.rs
  crates/rspack_binding_api/src/exports_info.rs
  crates/rspack_binding_api/src/filename.rs
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/module.rs
  crates/rspack_binding_api/src/module_graph.rs
  crates/rspack_binding_api/src/module_graph_connection.rs
  crates/rspack_binding_api/src/modules/concatenated_module.rs
  crates/rspack_binding_api/src/modules/context_module.rs
  crates/rspack_binding_api/src/modules/external_module.rs
  crates/rspack_binding_api/src/modules/macros.rs
  crates/rspack_binding_api/src/modules/normal_module.rs
  crates/rspack_binding_api/src/normal_module_factory.rs
  crates/rspack_binding_api/src/options/entry.rs
  crates/rspack_binding_api/src/path_data.rs
  crates/rspack_binding_api/src/plugins/interceptor.rs
  crates/rspack_binding_api/src/plugins/js_loader/context.rs
  crates/rspack_binding_api/src/plugins/js_loader/mod.rs
  crates/rspack_binding_api/src/raw_options/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_banner.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_css_extract.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_dll.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_lazy_compilation.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_lightning_css_minimizer.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_mf.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_swc_js_minimizer.rs
  crates/rspack_binding_api/src/raw_options/raw_devtool.rs
  crates/rspack_binding_api/src/raw_options/raw_dynamic_entry.rs
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  crates/rspack_binding_api/src/raw_options/raw_module/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_output.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
  crates/rspack_binding_api/src/resolver.rs
  crates/rspack_binding_api/src/resolver_factory.rs
  crates/rspack_binding_api/src/runtime.rs
  crates/rspack_binding_api/src/source.rs
  crates/rspack_binding_api/src/stats.rs
  crates/rspack_binding_api/src/utils.rs
Labels: team, release: refactor

#11270 chore: supporting linux cache compressing with zstd
  .github/actions/rustup/action.yml
  .github/actions/rustup/cargo/action.yml
Labels: team

#11276 fix: get resolve in externals should return query
  packages/rspack-test-tools/tests/configCases/externals/resolve-with-query/index.js
  packages/rspack-test-tools/tests/configCases/externals/resolve-with-query/rspack.config.js
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
Labels: team, release: bug fix

#11285 feat: support persistent cache for lazy barrel
  crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/compilation/make/lazy_barrel_artifact.rs
  packages/rspack-test-tools/tests/cacheCases/common/basic/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/common/update-file/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/index.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/a.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/b.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/c.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/index.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/package.json
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/rspack.config.js
  packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/test.js
Labels: team, release: feature

#11267 chore: upgrade rslint to 0.1.3
  package.json
  pnpm-lock.yaml
Labels: team

#11286 perf: improve add concatenated modules by parallelizing conneciton modifications
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team, release: performance

#11299 fix: swc transform api output sourcemaps
  crates/rspack_binding_api/src/swc.rs
  packages/rspack-test-tools/tests/compilerCases/swc-api-sourcemaps.js
Labels: release: bug fix

#11288 feat: rspack cli add config path to build dependencies
  packages/rspack-cli/src/cli.ts
  packages/rspack-cli/src/commands/preview.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/tests/build/issue-11009/base.config.js
  packages/rspack-cli/tests/build/issue-11009/entry.js
  packages/rspack-cli/tests/build/issue-11009/index.test.ts
  packages/rspack-cli/tests/build/issue-11009/rspack.config.js
  packages/rspack-cli/tests/build/plugin-apply-error/plugin-apply-error.test.ts
  packages/rspack-cli/tests/serve/issue-11009/base.config.js
  packages/rspack-cli/tests/serve/issue-11009/entry.js
  packages/rspack-cli/tests/serve/issue-11009/index.test.ts
  packages/rspack-cli/tests/serve/issue-11009/rspack.config.js
Labels: team, release: feature

#11300 feat: expose `experiments.swc` in parallel loader context
  packages/rspack/src/loader-runner/worker.ts
Labels: release: feature

#11301 fix: pass actual root context to parallel loader context
  packages/rspack/src/loader-runner/index.ts
Labels: release: bug fix

#11290 docs: add docs for custom binding crates
  crates/rspack_binding_build/README.md
  crates/rspack_binding_build/src/lib.rs
  crates/rspack_binding_builder/README.md
  crates/rspack_binding_builder/src/lib.rs
  crates/rspack_binding_builder_macros/README.md
  crates/rspack_binding_builder_macros/src/lib.rs
Labels: team, release: document

#11284 chore: deprecated `experiments.topLevelAwait` config
  packages/rspack/src/config/defaults.ts
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team

#11307 chore: remove from `rspack_binding_api` in CODEOWNERS
  .github/CODEOWNERS
Labels: team

#11311 feat: propagate const for inline const
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/exports/utils.rs
  crates/rspack_loader_swc/src/collect_ts_info.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  crates/rspack_util/Cargo.toml
  crates/rspack_util/src/itoa.rs
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/ryu_js.rs
  packages/rspack-test-tools/tests/configCases/inline-const/basic/constants.js
  packages/rspack-test-tools/tests/configCases/inline-const/basic/index.js
  packages/rspack-test-tools/tests/configCases/inline-const/basic/rspack.config.js
  packages/rspack/src/config/defaults.ts
  website/docs/en/config/experiments.mdx
  website/docs/en/config/module.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team, release: feature

#11310 fix: rsdoctor multi compiler data scope
  crates/rspack_plugin_rsdoctor/src/chunk_graph.rs
  crates/rspack_plugin_rsdoctor/src/module_graph.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
Labels: team, release: bug fix

#11325 fix: batch rename_asset with parallel optimization
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_plugin_real_content_hash/src/lib.rs
Labels: team, release: bug fix

#11334 perf: cache concatenated imports
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
Labels: team, release: performance

#11160 feat: module chunk HMR
  Cargo.toml
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_plugin_hmr/src/lib.rs
  crates/rspack_plugin_runtime/src/module_chunk_format.rs
  crates/rspack_plugin_runtime/src/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading_with_hmr.ejs
  crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading_with_hmr_manifest.ejs
  crates/rspack_util/Cargo.toml
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/builtin.ts
  packages/rspack-test-tools/src/helper/index.ts
  packages/rspack-test-tools/src/helper/is.ts
  packages/rspack-test-tools/src/processor/cache.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/src/runner/runner/basic.ts
  packages/rspack-test-tools/src/runner/runner/web/fake.ts
  packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
  packages/rspack-test-tools/tests/configCases/asset/real-content-hash-related-source-map/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/get-resolve/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/resolve-with-query/rspack.config.js
  packages/rspack-test-tools/tests/configCases/parsing/import-eager/index.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/by-dependency/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/cache-for-get/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/cache-for-resolver-with-options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/get-with-options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver-factory/restriction/rspack.config.js
  packages/rspack-test-tools/tests/defaultsCases/experiments/output-module.js
  packages/rspack/src/config/defaults.ts
  tests/webpack-test/HotTestCases.template.js
  tests/webpack-test/hotCases/esm-output/async-chunks/async-module.js
  tests/webpack-test/hotCases/esm-output/async-chunks/index.js
  tests/webpack-test/hotCases/esm-output/async-chunks/lazy-module.js
  tests/webpack-test/hotCases/esm-output/async-chunks/webpack.config.js
  tests/webpack-test/hotCases/esm-output/css-modules/index.js
  tests/webpack-test/hotCases/esm-output/css-modules/style.module.css
  tests/webpack-test/hotCases/esm-output/css-modules/style2.module.css
  tests/webpack-test/hotCases/esm-output/css-modules/test.config.js
  tests/webpack-test/hotCases/esm-output/css-modules/webpack.config.js
  tests/webpack-test/hotCases/esm-output/runtime-chunk/async-shared.js
  tests/webpack-test/hotCases/esm-output/runtime-chunk/index.js
  tests/webpack-test/hotCases/esm-output/runtime-chunk/shared.js
  tests/webpack-test/hotCases/esm-output/runtime-chunk/webpack.config.js
  tests/webpack-test/hotCases/esm-output/simple/index.js
  tests/webpack-test/hotCases/esm-output/simple/module.js
  tests/webpack-test/hotCases/esm-output/simple/test.filter.js
  tests/webpack-test/hotCases/esm-output/simple/webpack.config.js
  tests/webpack-test/hotCases/esm-output/split-chunks/common/shared.js
  tests/webpack-test/hotCases/esm-output/split-chunks/index.js
  tests/webpack-test/hotCases/esm-output/split-chunks/node_modules/vendor-lib.js
  tests/webpack-test/hotCases/esm-output/split-chunks/webpack.config.js
  tests/webpack-test/hotCases/update.esm.js
Labels: team, release: feature

#11343 chore(ci): use npm trusted publish
  .github/workflows/release-canary.yml
  .github/workflows/release-debug.yml
  .github/workflows/release-otp.yml
  .github/workflows/release.yml
Labels: team

#11021 feat: add VirtualModulesPlugin
  Cargo.toml
  crates/node_binding/napi-binding.d.ts
  crates/node_binding/rspack.wasi-browser.js
  crates/node_binding/rspack.wasi.cjs
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/native_watcher.rs
  crates/rspack_binding_api/src/raw_options/mod.rs
  crates/rspack_binding_api/src/virtual_modules/fs.rs
  crates/rspack_binding_api/src/virtual_modules/mod.rs
  crates/rspack_binding_api/src/virtual_modules/trie_store.rs
  crates/rspack_fs/src/lib.rs
  crates/rspack_fs/src/watcher/disk_watcher.rs
  crates/rspack_fs/src/watcher/mod.rs
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-base/index.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-base/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-context/index.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-context/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-dynamic/index.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-dynamic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-no-conflicts/index.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-no-conflicts/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-parent-dir/index.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-parent-dir/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/virtual-modules/base/0/index.js
  packages/rspack-test-tools/tests/watchCases/virtual-modules/base/1/readme.txt
  packages/rspack-test-tools/tests/watchCases/virtual-modules/base/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/NativeWatchFileSystem.ts
  packages/rspack/src/VirtualModulesPlugin.ts
  packages/rspack/src/exports.ts
  website/docs/en/plugins/index.mdx
  website/docs/en/plugins/rspack/virtual-modules-plugin.mdx
  website/docs/zh/plugins/index.mdx
  website/docs/zh/plugins/rspack/virtual-modules-plugin.mdx
Labels: release: feature

#11352 chore(ci): fix flaky serve test
  packages/rspack-cli/tests/serve/basic/serve-basic.test.ts
Labels: team

#11341 perf: Replace hot regex with parser
  Cargo.lock
  Cargo.toml
  crates/rspack_core/Cargo.toml
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/normal_module_factory.rs
  crates/rspack_core/src/options/filename.rs
  crates/rspack_core/src/utils/comment.rs
  crates/rspack_core/src/utils/identifier.rs
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/src/loader.rs
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_devtool/src/module_filename_helpers.rs
  crates/rspack_plugin_externals/src/http_externals_plugin.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_util/src/identifier.rs
  deny.toml
Labels: team, release: performance

#11360 fix(incremental): LimitChunkCountPlugin panic with incremental turned on
  crates/rspack_plugin_limit_chunk_count/src/lib.rs
  packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/0/index.js
  packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/0/utilA.js
  packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/0/utilB.js
  packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/1/utilA.js
  packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/test.config.js
Labels: release: bug fix

#11339 feat: define plugin use value dependencies
  crates/rspack_core/src/compilation/make/graph_updater/cutout/mod.rs
  crates/rspack_core/src/compilation/make/graph_updater/mod.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/lib.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/value_cache_versions.rs
  crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
  crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/utils.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/walk_data.rs
  packages/rspack-test-tools/tests/cacheCases/make/issue-11221/a.js
  packages/rspack-test-tools/tests/cacheCases/make/issue-11221/b.js
  packages/rspack-test-tools/tests/cacheCases/make/issue-11221/entry.js
  packages/rspack-test-tools/tests/cacheCases/make/issue-11221/file.js
  packages/rspack-test-tools/tests/cacheCases/make/issue-11221/rspack.config.js
Labels: team, release: feature

#11353 refactor: move builtin virtual module plugin to experiments
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-base/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-context/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-dynamic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-no-conflicts/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-parent-dir/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/virtual-modules/base/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
  website/docs/en/plugins/rspack/virtual-modules-plugin.mdx
  website/docs/zh/plugins/rspack/virtual-modules-plugin.mdx
Labels: team, release: refactor

#11363 fix(cli): resolve port conflicts in parallel test execution
  packages/rspack-cli/tests/utils/test-utils.ts
Labels: team, release: bug fix

#11362 feat: port normal module replacement plugin to builtin plugin
  Cargo.lock
  Cargo.toml
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/Cargo.toml
  crates/rspack_binding_api/src/normal_module_factory.rs
  crates/rspack_binding_api/src/plugins/interceptor.rs
  crates/rspack_binding_api/src/plugins/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_context_replacement.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_css_chunking.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/raw_normal_replacement.rs
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  crates/rspack_plugin_devtool/Cargo.toml
  crates/rspack_plugin_module_replacement/Cargo.toml
  crates/rspack_plugin_module_replacement/src/context_replacement.rs
  crates/rspack_plugin_module_replacement/src/lib.rs
  crates/rspack_plugin_module_replacement/src/normal_module_replacement.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/Module.ts
  packages/rspack/src/builtin-plugin/CssChunkingPlugin.ts
  packages/rspack/src/builtin-plugin/NormalModuleReplacementPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
  packages/rspack/src/lib/NormalModuleReplacementPlugin.ts
  packages/rspack/src/taps/normalModuleFactory.ts
Labels: release: feature

#11369 docs(config): output.filename link fix
  website/docs/en/config/output.mdx
Labels: release: document

#11349 fix: modify lazy compilation tests
  packages/rspack-test-tools/src/plugin/lazy-compilation-test-plugin.ts
  packages/rspack-test-tools/src/processor/hot.ts
  packages/rspack-test-tools/tests/hotCases/lazy-compilation/context/webpack.config.js
  packages/rspack-test-tools/tests/hotCases/lazy-compilation/module-test/webpack.config.js
  packages/rspack-test-tools/tests/hotCases/lazy-compilation/only-entries/webpack.config.js
  packages/rspack-test-tools/tests/hotCases/lazy-compilation/simple/webpack.config.js
  packages/rspack-test-tools/tests/hotCases/lazy-compilation/unrelated/webpack.config.js
  tests/e2e/cases/lazy-compilation/css-update/rspack.config.js
  tests/e2e/cases/lazy-compilation/custom-prefix/rspack.config.js
  tests/e2e/cases/lazy-compilation/default-prefix/index.test.ts
  tests/e2e/cases/lazy-compilation/default-prefix/rspack.config.js
  tests/e2e/cases/lazy-compilation/ignore-entry/rspack.config.js
  tests/e2e/cases/lazy-compilation/persistent-cache/rspack.config.js
  tests/e2e/fixtures/rspack.ts
  tests/webpack-examples/lazy-compilation/README.md
  tests/webpack-examples/lazy-compilation/webpack.config.js
  tests/webpack-test/hotCases/lazy-compilation/context/webpack.config.js
  tests/webpack-test/hotCases/lazy-compilation/https/webpack.config.js
  tests/webpack-test/hotCases/lazy-compilation/module-test/webpack.config.js
  tests/webpack-test/hotCases/lazy-compilation/only-entries/webpack.config.js
  tests/webpack-test/hotCases/lazy-compilation/simple/webpack.config.js
  tests/webpack-test/hotCases/lazy-compilation/unrelated/webpack.config.js
Labels: team, release: bug fix

#11356 feat: support `[folder]` template string in `localIdentName` option
  crates/rspack_plugin_css/src/utils.rs
  tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
  tests/webpack-test/configCases/css/local-ident-name/index.js
  tests/webpack-test/configCases/css/local-ident-name/nested1/nested2/style.module.css
  tests/webpack-test/configCases/css/local-ident-name/test.config.js
  tests/webpack-test/configCases/css/local-ident-name/webpack.config.js
Labels: release: feature

#11364 perf: improve bundle splitting
  crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
  crates/rspack_plugin_split_chunks/src/common.rs
  crates/rspack_plugin_split_chunks/src/plugin/chunk.rs
  crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Labels: release: performance

#11375 chore: build http test case avoid send http request
  tests/webpack-examples/build-http/example.js
Labels: team

#11379 chore: Use macro instead of runtime debug_assert
  crates/node_binding/scripts/build.js
  crates/rspack_core/src/utils/identifier.rs
Labels: team

#11382 docs: fix typos in asset modules
  website/docs/en/config/output.mdx
  website/docs/en/guide/features/asset-module.mdx
  website/docs/zh/config/output.mdx
Labels: release: document

#11372 fix: should use specific runtime to get target url
  crates/rspack_core/src/artifacts/code_generation_results.rs
  crates/rspack_plugin_css/src/dependency/url.rs
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-11345/image.svg
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-11345/main.css
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-11345/main.js
  packages/rspack-test-tools/tests/configCases/css/rspack-issue-11345/rspack.config.js
Labels: team, release: bug fix

#11384 docs: add playground to navbar
  website/docs/en/_nav.json
  website/docs/zh/_nav.json
Labels: team, release: document

#11283 fix(wasm): remove cjs loader support
  packages/rspack/src/util/require.ts
Labels: team, release: bug fix

#11393 docs: remove outdated Node version requirements from quick start
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#11385 fix: cache concatenated module imports is not safe
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
  crates/rspack_core/src/concatenated_module.rs
Labels: team, release: bug fix

#11389 refactor: distinguish free variable and tagged variable
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
Labels: team, release: refactor

#11394 fix: add query to avoid browser cache the link
  crates/rspack_plugin_extract_css/src/runtime/with_hmr.js
Labels: team, release: bug fix

#11395 feat: support using declaration
  crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
  crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/check_var_decl.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  tests/webpack-test/cases/parsing/using/index.js
  tests/webpack-test/cases/parsing/using/module.js
  tests/webpack-test/cases/parsing/using/test.filter.js
  tests/webpack-test/configCases/source-map/exclude-modules-source-map/index.js
  tests/webpack-test/helpers/supportsUsing.js
Labels: team, release: feature

#11409 docs: update ts config guide
  website/docs/en/config/index.mdx
  website/docs/zh/config/index.mdx
Labels: team, release: document

#11414 docs: add building and testing guide for rspack wasm
  website/docs/en/contribute/development/building.md
  website/docs/en/contribute/development/testing-rspack.mdx
  website/docs/zh/contribute/development/building.md
  website/docs/zh/contribute/development/testing-rspack.mdx
Labels: team, release: document

#11416 refactor: add module pre walk
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_module_pre.rs
Labels: team, release: refactor

#11417 fix(browser): fix @rspack/browser building
  packages/rspack-browser/package.json
  packages/rspack/src/browser/service.ts
Labels: team, release: bug fix

#11419 chore: bump `swc_core` from 35.0.0 to 36.0.0
  Cargo.lock
  Cargo.toml
  crates/rspack_workspace/src/generated.rs
  packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/stats.err
Labels: team

#11423 chore: update swc types and docs
  packages/rspack-browser/package.json
  packages/rspack/etc/core.api.md
  packages/rspack/package.json
  pnpm-lock.yaml
  website/docs/en/config/experiments.mdx
  website/docs/en/config/module.mdx
  website/docs/en/guide/features/builtin-swc-loader.mdx
  website/docs/zh/config/experiments.mdx
  website/docs/zh/config/module.mdx
  website/docs/zh/guide/features/builtin-swc-loader.mdx
Labels: team

#11424 chore(ci): prevent prerelease published to lastest
  .github/workflows/release.yml
  scripts/release/publish.mjs
Labels: team

#11430 fix: bailout optimize if there are external modules in other concate scope
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/utils/concatenation_scope.rs
  packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/cjs.js
  packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/index.js
  packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/other-entry.js
  packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/rspack.config.js
  packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/test.config.js
Labels: team, release: bug fix

#11433 refactor: only collect destructuring assignment properties for specific expression
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin/index.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin/webpack.config.js
  tests/webpack-test/cases/esm/import-meta/index.js
  tests/webpack-test/configCases/plugins/define-plugin/index.js
  tests/webpack-test/configCases/plugins/define-plugin/webpack.config.js
Labels: team, release: refactor

#11418 feat(rslib): intercept more APIPlugin expressions
  crates/rspack_plugin_rslib/src/parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/rslib/plugin-api/index.js
  packages/rspack-test-tools/tests/configCases/rslib/plugin-api/test.js
Labels: team, release: feature

#11436 perf(browser): remove tracing
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_binding_api/src/trace_event.rs
Labels: release: performance

#11431 feat(browser): add `BrowserImportEsmPlugin`
  packages/rspack/src/browser/BrowserImportEsmPlugin.ts
  packages/rspack/src/browser/index.ts
  packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
Labels: team, release: feature

#11439 perf(browser): set `fmt_debug` to `none`
  crates/node_binding/scripts/build.js
Labels: release: performance

#11420 fix: native watcher fails to work correctly with persistent cache
  packages/rspack/src/NativeWatchFileSystem.ts
Labels: team, release: bug fix

#11438 fix(ci): should check package name in pre-release check
  scripts/release/publish.mjs
  scripts/release/version.mjs
Labels: team, release: bug fix

#11444 fix: update node inspector import and remove workaround
  packages/rspack/src/trace/index.ts
Labels: team, release: bug fix

#11442 test: remove legacy Node version helpers
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/helper/index.ts
  packages/rspack-test-tools/src/helper/legacy/supportsImportFn.ts
  packages/rspack-test-tools/src/helper/legacy/supportsWorker.js
  packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/test.filter.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/codegen-cache/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/css/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/execute-failed/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/nul-byte/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/recursive-import-module/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel-import-module/with-layer/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data-no-passthrough/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data-passthrough/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/async/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/binary-with-source-map/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/issue-webpack-9053/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-error-async/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-raw-string/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-raw/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/loader-string/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/module-build-error/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/options/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/index.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/pitching-mixed/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/pitching/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/pre-post-loader/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/source-map/rspack.config.js
  packages/rspack-test-tools/tests/configCases/loader-parallel/sync/rspack.config.js
  packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/test.filter.js
  packages/rspack-test-tools/tests/hotCases/worker/move-between-runtime/test.filter.js
Labels: team

#11411 feat(cli): use SWC to do TS config transformamation
  biome.jsonc
  crates/rspack_binding_api/src/swc.rs
  packages/rspack-cli/package.json
  packages/rspack-cli/src/utils/isTsFile.ts
  packages/rspack-cli/src/utils/loadConfig.ts
  packages/rspack-cli/tests/build/config/config.test.ts
  packages/rspack-cli/tests/build/config/ts-node-register/main.ts
  packages/rspack-cli/tests/build/config/ts-node-register/rspack.config.ts
  packages/rspack-cli/tests/build/config/ts-node-register/tsconfig.json
  pnpm-lock.yaml
Labels: team, release: feature, release: breaking change

#11443 fix: lazy compilation with only loader module
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  tests/e2e/cases/lazy-compilation/loader-only-module/index.test.ts
  tests/e2e/cases/lazy-compilation/loader-only-module/loader.js
  tests/e2e/cases/lazy-compilation/loader-only-module/rspack.config.js
Labels: team, release: bug fix

#11344 docs(ESM): add ESM guide
  website/docs/en/guide/features/_meta.json
  website/docs/en/guide/features/esm.mdx
  website/docs/zh/guide/features/_meta.json
  website/docs/zh/guide/features/esm.mdx
Labels: team, release: document

#11452 chore: add Claude local config to gitignore
  .gitignore
Labels: team

#11449 perf: reuse plugin hooks
  crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
  crates/rspack_plugin_javascript/src/runtime.rs
Labels: team, release: performance

#11447 refactor: clean paren ast for analyzing dependencies
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
Labels: team, release: refactor

#11456 revert: "fix: lazy compilation with only loader module (#11443)"
  crates/rspack_plugin_lazy_compilation/src/module.rs
  crates/rspack_plugin_lazy_compilation/src/plugin.rs
  tests/e2e/cases/lazy-compilation/loader-only-module/index.test.ts
  tests/e2e/cases/lazy-compilation/loader-only-module/loader.js
  tests/e2e/cases/lazy-compilation/loader-only-module/rspack.config.js
Labels: team

#11446 chore: release 1.5.0-rc.0
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  crates/node_binding/package.json
  crates/rspack_workspace/src/generated.rs
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-browser/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#11460 fix: update event handling to support batch processing of FsEvents
  crates/rspack_fs/src/watcher/executor.rs
  crates/rspack_fs/src/watcher/mod.rs
  crates/rspack_fs/src/watcher/scanner.rs
  crates/rspack_fs/src/watcher/trigger.rs
Labels: team, release: bug fix

#11464 fix: should recompile correctly when a shared entry specified in 'dependOn' is modified during watch mode
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/bar.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/foo.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/index1.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/index2.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/main.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/shared.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/1/shared.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/test.config.js
Labels: team, release: bug fix

#11421 feat: allow external modules placed in async chunks
  crates/node_binding/napi-binding.d.ts
  crates/rspack/src/builder/builder_context.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
  crates/rspack_binding_api/src/raw_options/raw_external.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_plugin_dll/src/dll_reference/dll_reference_agency_plugin.rs
  crates/rspack_plugin_externals/src/electron_target_plugin.rs
  crates/rspack_plugin_externals/src/http_externals_plugin.rs
  crates/rspack_plugin_externals/src/node_target_plugin.rs
  crates/rspack_plugin_externals/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/externals/in-async-chunks/index.js
  packages/rspack-test-tools/tests/configCases/externals/in-async-chunks/module.js
  packages/rspack-test-tools/tests/configCases/externals/in-async-chunks/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
  packages/rspack/src/container/ContainerReferencePlugin.ts
  packages/rspack/src/rspackOptionsApply.ts
Labels: release: feature

#11467 docs: improve virtual-modules-plugin documentation
  website/components/i18n/en.json
  website/components/i18n/zh.json
  website/docs/en/plugins/index.mdx
  website/docs/en/plugins/rspack/virtual-modules-plugin.mdx
  website/docs/zh/plugins/index.mdx
  website/docs/zh/plugins/rspack/virtual-modules-plugin.mdx
Labels: team, release: document

#11465 perf: improve bundle splitting
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  tests/e2e/cases/css/chunk-loading-order/index.test.ts
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team, release: performance

#11469 fix(browser): rename and ignore requests with match resource and inline loaders
  packages/rspack/src/browser/BrowserHttpImportEsmPlugin.ts
  packages/rspack/src/browser/index.ts
Labels: team, release: bug fix

#11474 fix: unstable bundle splitting
  crates/rspack_plugin_split_chunks/src/module_group.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  tests/e2e/cases/css/chunk-loading-order/index.test.ts
Labels: team, release: bug fix

#11475 perf: add fast path for `get_scheme`
  Cargo.lock
  crates/rspack_loader_runner/Cargo.toml
  crates/rspack_loader_runner/src/scheme.rs
Labels: team, release: performance

#11482 refactor(browser): remove `esm.sh` default domain in `BrowserHttpImportEsmPlugin`
  packages/rspack/src/browser/BrowserHttpImportEsmPlugin.ts
Labels: team, release: refactor

#11472 docs: add guide for the `@rspack/browser` package
  packages/rspack-browser/README.md
  website/docs/en/api/javascript-api/_meta.json
  website/docs/en/api/javascript-api/browser.mdx
  website/docs/zh/api/javascript-api/_meta.json
  website/docs/zh/api/javascript-api/browser.mdx
Labels: team, release: document

#11481 fix: build chunk graph incremental logic when dynamic entry with depend on
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/main.js
  packages/rspack-test-tools/tests/watchCases/chunks/depend-on/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/0/foo.js
  packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/0/shared.js
  packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/1/main.js
  packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/test.config.js
Labels: team, release: bug fix

#11480 perf: replace `Mutex<Option<T>>` with `OnceLock<T>`
  crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
Labels: team, release: performance

#11483 refactor: use Atom for parser variable name
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/exports_info_api_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_member_expr.rs
  crates/rspack_plugin_javascript/src/utils/eval/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_module_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
  crates/rspack_plugin_javascript/src/visitors/scope_info.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
Labels: team, release: refactor

#11470 feat(browser): introduce `BrowserRequirePlugin` and remove `nonWebpackRequire`
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compiler.ts
  packages/rspack/src/browser/BrowserRequire.ts
  packages/rspack/src/browser/index.ts
  packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
  packages/rspack/src/builtin-plugin/html-plugin/plugin.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/loader-runner/loadLoader.ts
  packages/rspack/src/util/require.ts
Labels: release: feature

#11484 perf(browser): disable `ProgressPlugin`, `RsdoctorPlugin` and `RstestPlugin`
  crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
Labels: team, release: performance

#11496 fix: wrong match object logic in `SwcJsMinimizerRspackPlugin`
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11183/index.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11183/rspack.config.js
  packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11183/test.config.js
Labels: team, release: bug fix

#11497 fix: asset info related source map can set null
  crates/node_binding/napi-binding.d.ts
  crates/rspack_binding_api/src/asset.rs
  packages/rspack-test-tools/tests/configCases/asset/update-asset-sourcemap-null/index.js
  packages/rspack-test-tools/tests/configCases/asset/update-asset-sourcemap-null/rspack.config.js
Labels: team, release: bug fix

#11501 fix: source map sources in node modules should convert to absolute path
  Cargo.lock
  crates/rspack_loader_swc/Cargo.toml
  crates/rspack_loader_swc/src/lib.rs
  packages/rspack-test-tools/tests/configCases/source-map/source-map-resolve-vendor-path/index.js
  packages/rspack-test-tools/tests/configCases/source-map/source-map-resolve-vendor-path/node_modules/lib-with-source-map/index.js
  packages/rspack-test-tools/tests/configCases/source-map/source-map-resolve-vendor-path/node_modules/lib-with-source-map/index.js.map
  packages/rspack-test-tools/tests/configCases/source-map/source-map-resolve-vendor-path/node_modules/lib-with-source-map/package.json
  packages/rspack-test-tools/tests/configCases/source-map/source-map-resolve-vendor-path/rspack.config.js
Labels: team, release: bug fix

#11499 fix: add tsEnumIsMutable option to SWC loader schema
  packages/rspack/src/schema/loaders.ts
Labels: team, release: bug fix

#11505 chore(deps): update SWC related crates to v37.0.0
  Cargo.lock
  Cargo.toml
  crates/rspack_workspace/src/generated.rs
Labels: team

#11511 fix(types): allow async loader to return void
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapterRuleUse.ts
  website/docs/en/api/loader-api/types.mdx
  website/docs/zh/api/loader-api/types.mdx
Labels: team, release: bug fix

#11510 fix: code splitting incremental missing module to update
  crates/rspack_core/src/build_chunk_graph/incremental.rs
  tests/e2e/cases/chunk/recover-error/index.test.ts
  tests/e2e/cases/chunk/recover-error/rspack.config.js
  tests/e2e/cases/chunk/recover-error/src/App.jsx
  tests/e2e/cases/chunk/recover-error/src/AppIndex.jsx
  tests/e2e/cases/chunk/recover-error/src/index.html
  tests/e2e/cases/chunk/recover-error/src/main.jsx
  tests/e2e/cases/hooks/asset-emitted/index.test.ts
  tests/e2e/fixtures/rspack.ts
Labels: team, release: bug fix

#11525 fix: import.meta.prop with define plugin
  crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
  crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_member_expr.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin-import-meta/index.js
  packages/rspack-test-tools/tests/configCases/plugins/define-plugin-import-meta/webpack.config.js
Labels: team, release: bug fix

#11533 refactor: disable incremental buildChunkGraph by default
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/available-modules-change/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/basic/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/chunk-add-then-change-ava-module/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/chunk-modify/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/chunk-remove/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/pre-order-index/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk-recover-error/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/rspack.config.js
  packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/rspack.config.js
  packages/rspack/src/config/defaults.ts
Labels: team, release: refactor
