Repository web-infra-dev/rspack, pull requests merged in 2025-06, with the labels that each got.

#10547 perf: add cache for getImports and module graph visiting
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Labels: team, release: performance

#10552 chore: release 1.3.13
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10510 refactor: remove module graph of export_info getters
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
Labels: team

#10555 chore(allocator): bump mimalloc to v3.0.3
  Cargo.lock
  Cargo.toml
Labels: team

#10560 fix(incremental): fullhash chunk filename should disable incremental for chunk render
  crates/rspack_core/src/build_chunk_graph/code_splitter.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/case/new-incremental.ts
  packages/rspack-test-tools/src/processor/hot-new-incremental.ts
  packages/rspack-test-tools/tests/NewIncremental-node.test.js
  packages/rspack-test-tools/tests/NewIncremental-web.test.js
  packages/rspack-test-tools/tests/NewIncremental-webworker.test.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/1/warnings.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/1/warnings.js
  packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/1/warnings.js
Labels: team, release: bug fix

#10537 perf: regex from js and js resolver api
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/rspack_regex/src/napi.rs
Labels: team, release: performance

#10508 feat: improve external render
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/utils/concatenation_scope.rs
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case2.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case3.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case5.txt
  packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case6.txt
  packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/index.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/lib.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/rspack.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.config.js
  packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-module/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-parser/index.js
  tests/webpack-test/configCases/externals/module-import/index.js
Labels: team, release: feature

#10566 chore: bump swc version to 26.3.4
  Cargo.lock
  Cargo.toml
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_javascript_compiler/src/compiler/stringify.rs
  crates/rspack_javascript_compiler/src/compiler/transform.rs
  crates/rspack_javascript_compiler/src/error.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_plugin_javascript/Cargo.toml
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
  crates/rspack_plugin_swc_js_minimizer/src/lib.rs
  crates/rspack_util/src/swc.rs
  packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
  packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
  packages/rspack-test-tools/tests/builtinCases/samples/cycle-dynamic-entry/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/samples/intersection/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/builtinCases/samples/parent-have-partial-module/__snapshots__/output.snap.txt
  packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/__snapshot__/snapshot.txt
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-strict-block/errors.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-strict-block/index.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-strict/errors.js
  packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-strict/index.js
  packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/module-parse-error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/reserved_name_error/raw-error.err
  packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/reserved_name_error/stats.err
  packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt
  packages/rspack-test-tools/tests/statsAPICases/basic.js
  tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Labels: team

#10550 chore(ci): fix debug release not triggered
  .github/workflows/release-debug.yml
Labels: team

#10534 refactor: prefetch exports info data of getters
  crates/node_binding/src/exports_info.rs
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
  crates/rspack_core/src/exports/exports_info_setter.rs
  crates/rspack_core/src/exports/mod.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
  packages/rspack-test-tools/tests/configCases/build-http/custom-http-client/rspack-http-lockfile.json
Labels: team

#10575 release: 1.3.14
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10577 fix: should rebuild chunk outgoings when incremental runtime change
  crates/rspack_core/src/artifacts/cgm_hash_artifact.rs
  crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  packages/rspack-test-tools/tests/NewIncremental-node.test.js
  packages/rspack-test-tools/tests/NewIncremental-web.test.js
  packages/rspack-test-tools/tests/NewIncremental-webworker.test.js
Labels: team, release: bug fix

#10581 docs: update terminology and improve clarity in optimization and devtool
  website/docs/en/config/devtool.mdx
  website/docs/en/config/optimization.mdx
  website/docs/en/guide/optimization/analysis.mdx
  website/docs/en/guide/optimization/production.mdx
  website/docs/en/guide/optimization/tree-shaking.mdx
  website/docs/zh/blog/announcing-1-3.mdx
  website/docs/zh/config/devtool.mdx
  website/docs/zh/config/optimization.mdx
  website/docs/zh/config/output.mdx
  website/docs/zh/guide/optimization/analysis.mdx
  website/docs/zh/guide/optimization/code-splitting.mdx
  website/docs/zh/guide/optimization/production.mdx
  website/docs/zh/misc/glossary.mdx
  website/theme/i18n/zhCN.ts
Labels: team, release: document

#10587 fix(deps): update @rspack/dev-server to ~1.1.3 [security]
  packages/rspack-cli/package.json
  pnpm-lock.yaml
  tests/e2e/package.json
Labels: team, release: bug fix

#10588 chore: release v1.3.15
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10586 chore(workflow): remove CI lark alerts
  .github/workflows/ci.yml
  .github/workflows/issue-pr-trigger.yml
  scripts/alert/lark.js
Labels: team

#10578 feat: serialized build info custom fields from js
  Cargo.lock
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/asset.rs
  crates/node_binding/src/build_info.rs
  crates/node_binding/src/define_symbols.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/macros.rs
  crates/rspack_core/src/module.rs
  crates/rspack_napi/Cargo.toml
  crates/rspack_napi/src/utils.rs
  packages/rspack-test-tools/tests/compilerCases/persist-build-info.js
  packages/rspack-test-tools/tests/fixtures/build-info-loader.js
  packages/rspack/src/BuildInfo.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/loader-runner/index.ts
Labels: team, release: feature

#10585 feat: rsdoctor native plugin add bailout_reason property
  crates/node_binding/binding.d.ts
  crates/node_binding/src/rsdoctor.rs
  crates/rspack_plugin_rsdoctor/src/data.rs
  crates/rspack_plugin_rsdoctor/src/module_graph.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/rsdoctor/moduleGraph/rspack.config.js
Labels: release: feature

#10594 fix: correct remove_available_modules
  crates/rspack_core/src/build_chunk_graph/available_modules.rs
Labels: team, release: bug fix

#10484 perf: launch background tasks immediately
  crates/rspack_core/src/utils/task_loop.rs
Labels: release: performance

#10612 docs: fix rsbuild command typo in tracing doc
  website/docs/en/contribute/development/tracing.md
  website/docs/zh/contribute/development/tracing.md
Labels: team, release: document

#10615 fix: `number_hash` should use `u64` to avoid addition overflow
  crates/rspack_util/src/number_hash.rs
Labels: release: bug fix

#10616 fix(create-rspack): ignore rspack profile and remove npmignore file
  packages/create-rspack/template-common/gitignore
  packages/create-rspack/template-react-js/.npmignore
  packages/create-rspack/template-react-ts/.npmignore
  packages/create-rspack/template-vanilla-js/.npmignore
  packages/create-rspack/template-vanilla-ts/.npmignore
  packages/create-rspack/template-vue-js/.npmignore
  packages/create-rspack/template-vue-ts/.npmignore
Labels: team, release: bug fix

#8643 feat: consume js `inputFileSystem` on the rust side
  .github/actions/cache/restore/action.yml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/fs_node/hybrid.rs
  crates/node_binding/src/fs_node/mod.rs
  crates/node_binding/src/fs_node/node.rs
  crates/node_binding/src/fs_node/write.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/raw_options/raw_experiments/mod.rs
  crates/node_binding/src/resolver.rs
  packages/rspack-test-tools/src/helper/util/checkStats.js
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/input-file-system/disk.js
  packages/rspack-test-tools/tests/configCases/input-file-system/webpack.config.js
  packages/rspack-test-tools/tests/configCases/module/build-info/rspack.config.js
  packages/rspack-test-tools/tests/configCases/resolver/resolve/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/module.d.ts
  packages/rspack/src/Compiler.ts
  packages/rspack/src/FileSystem.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  tests/webpack-test/Defaults.unittest.js
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: release: feature

#10622 feat: support passing error code to `callbackify` callbacks
  crates/node_binding/src/resolver.rs
  crates/node_binding/src/utils.rs
Labels: team, release: feature

#10624 feat(core): expose `StatsErrorCode`
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
Labels: team, release: feature

#10619 fix(rstest): should stringify resource path
  Cargo.lock
  crates/rspack_plugin_rstest/Cargo.toml
  crates/rspack_plugin_rstest/src/module_path_name_dependency.rs
  crates/rspack_plugin_rstest/src/parser_plugin.rs
  packages/rspack-test-tools/tests/configCases/rstest/module-path-names/index.js
Labels: team, release: bug fix

#10633 Revert "chore(deps): update napi to 3.0.0-beta.8"
  Cargo.lock
  Cargo.toml
  crates/node_binding/src/resolver.rs
  crates/node_binding/src/utils.rs
  deny.toml
Labels: team

#10576 refactor: prefetch exports info data of getters part 2
  crates/node_binding/src/exports_info.rs
  crates/node_binding/src/module_graph.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
  crates/rspack_core/src/exports/utils.rs
  crates/rspack_core/src/external_module.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/stats/mod.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_dll/src/lib_manifest_plugin.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: team

#10637 chore(deps): update napi to 3.0.0-beta.8
  Cargo.lock
  Cargo.toml
  crates/node_binding/src/resolver.rs
  crates/node_binding/src/utils.rs
  deny.toml
Labels: team

#10634 feat: add d.ts in binding build artficats
  .github/workflows/reusable-build-build.yml
  .github/workflows/reusable-build-test.yml
Labels: team, release: feature

#10640 feat: add swc transformSync and minifySync api
  crates/node_binding/binding.d.ts
  crates/node_binding/src/swc.rs
  packages/rspack-test-tools/tests/compilerCases/swc-api.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
  packages/rspack/src/swc.ts
  website/docs/en/api/javascript-api/swc.mdx
  website/docs/zh/api/javascript-api/swc.mdx
Labels: team, release: feature

#10653 fix: change bailout_reason to array in rsdoctor native plugin
  crates/node_binding/src/rsdoctor.rs
  crates/rspack_plugin_rsdoctor/src/data.rs
  crates/rspack_plugin_rsdoctor/src/module_graph.rs
  crates/rspack_plugin_rsdoctor/src/plugin.rs
Labels: release: bug fix

#10656 chore(workflow): update changelog generator to include refactor label
  .github/pr-labeler.yml
  .github/release.yml
Labels: team

#10657 perf: reduce memory allocation in `esm_export_imported_specifier_dependency`
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
  crates/rspack_core/src/dependency/mod.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
Labels: release: performance

#10667 chore: update team members
  .github/teams.yml
Labels: team

#10668 fix(schema): add `jsc.output.charset` of swc-loader
  packages/rspack/src/builtin-loader/swc/types.ts
Labels: team, release: bug fix

#10662 refactor: make merge modified files and removed files
  crates/rspack_core/src/compiler/make/cutout/mod.rs
Labels: team, release: refactor

#10660 chore: bump swc to 27.0.4
  Cargo.lock
  Cargo.toml
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_error/src/error.rs
  crates/rspack_javascript_compiler/src/compiler/parse.rs
  crates/rspack_javascript_compiler/src/compiler/stringify.rs
  crates/rspack_javascript_compiler/src/compiler/transform.rs
  crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
  crates/rspack_util/src/swc.rs
Labels: team

#10579 chore(ci): use windows self hosted
  .github/actions/rustup/action.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-build-build.yml
  .github/workflows/reusable-build.yml
Labels: team

#9828 refactor!: lazy compilation middleware supports multiCompiler and use config from compiler instance
  packages/rspack-cli/src/commands/serve.ts
  packages/rspack-test-tools/etc/test-tools.api.md
  packages/rspack-test-tools/src/plugin/lazy-compilation-test-plugin.ts
  packages/rspack-test-tools/tests/fixtures/esm/d-dynamic.js
  packages/rspack-test-tools/tests/fixtures/esm/d.js
  packages/rspack-test-tools/tests/legacy-test/MultiCompiler.test.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/MultiCompiler.ts
  packages/rspack/src/MultiWatching.ts
  packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
  packages/rspack/src/config/devServer.ts
  tests/e2e/fixtures/rspack.ts
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/zh/guide/features/lazy-compilation.mdx
Labels: team

#10682 fix: generator data url function panic
  crates/node_binding/src/raw_options/raw_module/mod.rs
  packages/rspack-test-tools/tests/configCases/asset/custom-encoder/index.js
  packages/rspack-test-tools/tests/configCases/asset/custom-encoder/rspack.config.js
  packages/rspack-test-tools/tests/configCases/asset/custom-encoder/style.css
Labels: team, release: bug fix

#10680 perf(ci): move benchmark building to self-hosted
  .github/workflows/ci.yml
  .github/workflows/ecosystem-benchmark.yml
  .github/workflows/reusable-build-build.yml
  .github/workflows/reusable-build.yml
Labels: team, release: performance

#10686 refactor: js api readableIdentifier in module
  crates/node_binding/binding.d.ts
  crates/node_binding/scripts/banner.d.ts
  crates/node_binding/src/module.rs
  crates/node_binding/src/modules/macros.rs
  packages/rspack/src/ConcatenatedModule.ts
  packages/rspack/src/ContextModule.ts
  packages/rspack/src/ExternalModule.ts
  packages/rspack/src/Module.ts
  packages/rspack/src/NormalModule.ts
Labels: team, release: refactor

#10687 refactor: fast fail matrix testing to better utilizing CI runner
  .github/workflows/preview-commit.yml
  .github/workflows/release-canary.yml
  .github/workflows/release-otp.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build-all.yml
  .github/workflows/reusable-build-test.yml
Labels: team, release: refactor

#10691 chore: remove rspack.dev redirect
  website/docs/public/netlify.toml
Labels: team

#10685 fix(binding): remove Node 10 compatibility code
  crates/node_binding/binding.js
Labels: team, release: bug fix

#10693 fix(ci): linux x86 native build hardcoded profile
  .github/workflows/reusable-build-build.yml
Labels: team, release: bug fix

#10695 docs: update lazyCompilationMiddleware interface
  website/docs/en/guide/features/lazy-compilation.mdx
  website/docs/zh/guide/features/lazy-compilation.mdx
Labels: release: document

#9345 chore(benchmark): add rspack benchcases
  .github/workflows/reusable-build.yml
  .gitignore
  Cargo.lock
  package.json
  pnpm-lock.yaml
  scripts/bench/setup.mjs
  scripts/package.json
  tasks/benchmark/Cargo.toml
  tasks/benchmark/benches/benches.rs
  tasks/benchmark/benches/groups/basic_build.rs
  tasks/benchmark/benches/groups/bundle.rs
  tasks/benchmark/benches/groups/bundle/basic_react.rs
  tasks/benchmark/benches/groups/bundle/threejs.rs
  tasks/benchmark/benches/groups/bundle/util.rs
  tasks/benchmark/benches/groups/mod.rs
Labels: team

#10652 refactor: prefetch exports info data of getters part 3
  Cargo.lock
  crates/node_binding/src/exports_info.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/exports/export_info.rs
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/export_info_setter.rs
  crates/rspack_core/src/exports/exports_info.rs
  crates/rspack_core/src/exports/exports_info_getter.rs
  crates/rspack_core/src/exports/mod.rs
  crates/rspack_core/src/exports/referenced_export.rs
  crates/rspack_core/src/exports/target.rs
  crates/rspack_core/src/exports/utils.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_css/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
  crates/rspack_plugin_json/src/lib.rs
  crates/rspack_plugin_library/src/assign_library_plugin.rs
  crates/rspack_plugin_library/src/export_property_library_plugin.rs
  crates/rspack_plugin_library/src/modern_module_library_plugin.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
  crates/rspack_plugin_merge_duplicate_chunks/Cargo.toml
  crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
  crates/rspack_plugin_module_info_header/src/lib.rs
  crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
  crates/rspack_plugin_wasm/src/parser_and_generator.rs
Labels: release: refactor

#10714 refactor: remove unnecessary callback
  crates/node_binding/src/compilation/mod.rs
  crates/node_binding/src/lib.rs
  crates/node_binding/src/resolver.rs
  crates/node_binding/src/utils.rs
Labels: team, release: refactor

#10723 docs: update tracing doc typo
  website/docs/zh/contribute/development/tracing.md
Labels: team, release: document

#10713 feat: support preamble in swc minifier
  crates/rspack_javascript_compiler/src/compiler/stringify.rs
  packages/rspack-test-tools/tests/configCases/plugins/minify-preamble/index.js
  packages/rspack-test-tools/tests/configCases/plugins/minify-preamble/rspack.config.js
  packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
Labels: release: feature

#10674 feat(create-rspack): update tsconfig.json
  packages/create-rspack/template-react-ts/tsconfig.json
  packages/create-rspack/template-vanilla-ts/tsconfig.json
  packages/create-rspack/template-vue-ts/tsconfig.json
Labels: team, release: feature

#10553 feat: add support for SHA-256
  Cargo.lock
  crates/rspack_hash/Cargo.toml
  crates/rspack_hash/src/lib.rs
  packages/rspack-test-tools/tests/configCases/errors/rspack-issue-4504/errors.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-sha256/rspack.config.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-sha256/src/file.svg
  packages/rspack-test-tools/tests/hashCases/real-content-hash-sha256/src/index.js
  packages/rspack-test-tools/tests/hashCases/real-content-hash-sha256/test.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  website/docs/en/config/output.mdx
  website/docs/zh/config/output.mdx
Labels: release: feature

#10719 feat: type reexports presence tolerant
  crates/node_binding/binding.d.ts
  crates/node_binding/src/raw_options/raw_experiments/mod.rs
  crates/node_binding/src/raw_options/raw_module/mod.rs
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_core/src/options/experiments/mod.rs
  crates/rspack_core/src/options/module.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/basic.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/empty.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/index.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/rspack.config.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/types.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/warnings.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/with-empty.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/index.ts
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/rspack.config.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/warnings.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/adapter.ts
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: feature

#10727 perf: inline module graph partials
  crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/make/mod.rs
  crates/rspack_core/src/compiler/make/repair/mod.rs
  crates/rspack_core/src/module_graph/mod.rs
Labels: team, release: performance

#10724 feat(ci): use full match only to find self-hosted buil caches
  .github/actions/rustup/cargo/action.yml
Labels: team, release: feature

#10728 fix: add `-debugids` to Zod schema
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: release: bug fix

#10729 refactor(zod/v4): replace deprecated `.superRefine()`
  packages/rspack/src/config/zod.ts
Labels: release: refactor

#10741 perf: cache get exports type on module graph cache
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
  crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/context_module.rs
  crates/rspack_core/src/dependency/context_element_dependency.rs
  crates/rspack_core/src/dependency/runtime_template.rs
  crates/rspack_core/src/module.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
  crates/rspack_plugin_library/src/module_library_plugin.rs
Labels: team, release: performance

#10744 perf: parallel get runtime hash of concatenated modules
  crates/rspack_core/src/concatenated_module.rs
Labels: team, release: performance

#10747 perf: parallel get concatenated imports when enter module
  crates/rspack_core/src/concatenated_module.rs
Labels: team, release: performance

#10756 docs: add wasm example and usage
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: team, release: document

#10758 fix(rstest): put Rstest plugin in `experiments` field
  packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
  packages/rspack-test-tools/tests/configCases/rstest/module-path-names/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/exports.ts
Labels: team, release: bug fix

#10759 chore: release v1.4.0-rc.0
  crates/node_binding/package.json
  npm/darwin-arm64/package.json
  npm/darwin-x64/package.json
  npm/linux-x64-gnu/package.json
  npm/wasm32-wasi/package.json
  npm/win32-x64-msvc/package.json
  package.json
  packages/create-rspack/package.json
  packages/rspack-cli/package.json
  packages/rspack-test-tools/package.json
  packages/rspack/package.json
Labels: team

#10768 perf: skip schema creation and parse when validation is disabled
  packages/rspack/src/builtin-plugin/IgnorePlugin.ts
  packages/rspack/src/builtin-plugin/RsdoctorPlugin.ts
  packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
  packages/rspack/src/builtin-plugin/html-plugin/options.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/container/ModuleFederationPlugin.ts
  packages/rspack/src/container/ModuleFederationPluginV1.ts
  packages/rspack/src/lib/DllPlugin.ts
  packages/rspack/src/lib/DllReferencePlugin.ts
  packages/rspack/src/rspack.ts
  packages/rspack/src/util/validate.ts
Labels: team, release: performance

#10769 docs: adjust incremental docs for v1.4.0
  website/docs/en/config/experiments.mdx
  website/docs/zh/config/experiments.mdx
Labels: team, release: document

#10735 feat: initialize Rslib built-in plugin
  Cargo.lock
  Cargo.toml
  crates/node_binding/Cargo.toml
  crates/node_binding/binding.d.ts
  crates/node_binding/src/lib.rs
  crates/node_binding/src/raw_options/raw_builtins/mod.rs
  crates/node_binding/src/rslib.rs
  crates/rspack_plugin_rslib/Cargo.toml
  crates/rspack_plugin_rslib/LICENSE
  crates/rspack_plugin_rslib/README.md
  crates/rspack_plugin_rslib/src/lib.rs
  crates/rspack_plugin_rslib/src/parser_plugin.rs
  crates/rspack_plugin_rslib/src/plugin.rs
  packages/rspack-test-tools/tests/configCases/rslib/plugin-api/index.js
  packages/rspack-test-tools/tests/configCases/rslib/plugin-api/rspack.config.js
  packages/rspack-test-tools/tests/configCases/rslib/plugin-api/test.js
  packages/rspack/etc/core.api.md
  packages/rspack/scripts/check-documentation-coverage.ts
  packages/rspack/src/builtin-plugin/RslibPlugin.ts
  packages/rspack/src/builtin-plugin/index.ts
  packages/rspack/src/exports.ts
Labels: team, release: feature

#10774 chore: update pnpm lockfile
  pnpm-lock.yaml
Labels: team

#10775 chore(workflow): integrate heading-case to format title
  pnpm-lock.yaml
  website/docs/en/config/devtool.mdx
  website/docs/en/contribute/development/tracing.md
  website/docs/en/plugins/rspack/css-chunking-plugin.mdx
  website/docs/zh/api/loader-api/types.mdx
  website/docs/zh/contribute/development/tracing.md
  website/package.json
Labels: team

#10773 feat: css chunking plugin custom maxSize and minSize options
  crates/node_binding/binding.d.ts
  crates/rspack_binding_api/src/raw_options/raw_builtins/css_chunking.rs
  crates/rspack_plugin_css_chunking/src/lib.rs
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-plugin/CssChunkingPlugin.ts
  website/docs/en/plugins/rspack/css-chunking-plugin.mdx
  website/docs/zh/plugins/rspack/css-chunking-plugin.mdx
Labels: release: feature

#10771 feat(wasm): add simd flag
  .cargo/config.toml
Labels: team, release: feature

#10781 chore: add `NeverGrowInPlaceAllocator` for benchmark
  tasks/benchmark/src/lib.rs
Labels: team

#10778 perf(zod): prefer to use `partial` to make all properties optional
  packages/rspack/src/builtin-loader/swc/collectTypeScriptInfo.ts
  packages/rspack/src/builtin-loader/swc/pluginImport.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/builtin-plugin/html-plugin/options.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/lib/DllReferencePlugin.ts
Labels: team, release: performance

#10780 feat: typescript cross module enum inlining
  crates/rspack_core/src/exports/export_info_getter.rs
  crates/rspack_core/src/exports/utils.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/parser_and_generator.rs
  crates/rspack_loader_swc/src/collect_ts_info.rs
  crates/rspack_loader_swc/src/lib.rs
  crates/rspack_loader_swc/src/options.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
  crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
  crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
  crates/swc_plugin_ts_collector/src/enums.rs
  crates/swc_plugin_ts_collector/src/lib.rs
  crates/swc_plugin_ts_collector/src/type_exports.rs
  packages/rspack-test-tools/tests/configCases/inline-const/basic/constants.cjs
  packages/rspack-test-tools/tests/configCases/inline-const/basic/index.js
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/enum.destructing.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/enum.not-only-properties-used.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/enum.side-effects.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/enum.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/index.js
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/re-export.side-effects.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/re-export.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/test.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/cjs/index.cjs
  packages/rspack-test-tools/tests/configCases/inline-enum/cjs/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/const-enum-only/enum.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/const-enum-only/index.js
  packages/rspack-test-tools/tests/configCases/inline-enum/const-enum-only/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/enum-merging/enum.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/enum-merging/index.js
  packages/rspack-test-tools/tests/configCases/inline-enum/enum-merging/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/member-value-undefined/enum.ts
  packages/rspack-test-tools/tests/configCases/inline-enum/member-value-undefined/index.js
  packages/rspack-test-tools/tests/configCases/inline-enum/member-value-undefined/only-a.js
  packages/rspack-test-tools/tests/configCases/inline-enum/member-value-undefined/only-b.js
  packages/rspack-test-tools/tests/configCases/inline-enum/member-value-undefined/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/builtin-loader/swc/collectTypeScriptInfo.ts
  packages/rspack/src/builtin-loader/swc/index.ts
  packages/rspack/src/builtin-loader/swc/types.ts
  packages/rspack/src/config/adapterRuleUse.ts
Labels: team, release: feature

#10734 chore: enable `fair-sched` for codspeed
  .github/actions/codspeed/action.yaml
  .github/workflows/reusable-build-bench.yml
Labels: team

#10802 fix: remove catch for statsFactory.create
  packages/rspack/src/Stats.ts
Labels: team, release: bug fix

#10806 fix: add experiments gate for ts first feature
  crates/node_binding/binding.d.ts
  crates/rspack/src/builder/mod.rs
  crates/rspack/tests/snapshots/defaults__default_options.snap
  crates/rspack_binding_api/src/raw_options/raw_experiments/mod.rs
  crates/rspack_core/src/options/experiments/mod.rs
  crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs
  crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
  packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
  packages/rspack-test-tools/tests/configCases/inline-const/basic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/basic/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/cjs/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/const-enum-only/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/enum-merging/rspack.config.js
  packages/rspack-test-tools/tests/configCases/inline-enum/member-value-undefined/rspack.config.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/rspack.config.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/rspack.config.js
  packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/config/defaults.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
Labels: team, release: bug fix

#10793 docs: add blog for announcing Rspack 1.4
  website/docs/en/blog/_meta.json
  website/docs/en/blog/announcing-1-4.mdx
  website/docs/en/blog/index.mdx
  website/docs/en/contribute/development/tracing.md
  website/docs/en/guide/start/quick-start.mdx
  website/docs/en/plugins/rspack/css-chunking-plugin.mdx
  website/docs/zh/blog/_meta.json
  website/docs/zh/blog/announcing-1-4.mdx
  website/docs/zh/blog/index.mdx
  website/docs/zh/contribute/development/tracing.md
  website/docs/zh/guide/start/quick-start.mdx
  website/docs/zh/plugins/rspack/css-chunking-plugin.mdx
  website/project-words.txt
  website/rspress.config.ts
Labels: team, release: document

#10763 perf: improve concatenated modules plugin
  crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_core/src/dependency/dependency_trait.rs
  crates/rspack_core/src/module.rs
  crates/rspack_core/src/module_graph/mod.rs
  crates/rspack_core/src/normal_module.rs
  crates/rspack_plugin_extract_css/src/css_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
  crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
  crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Labels: team, release: performance

#10805 fix: add `_webpack_require_` while using SRI plugin
  crates/rspack_plugin_sri/src/runtime.rs
  packages/rspack-test-tools/tests/configCases/sri/runtime-requirement/index.js
  packages/rspack-test-tools/tests/configCases/sri/runtime-requirement/rspack.config.js
Labels: team, release: bug fix

#10800 feat: let ignore warnings match by object
  packages/rspack-test-tools/tests/Validation.test.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/bar.json
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/foo.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/index.js
  packages/rspack-test-tools/tests/statsOutputCases/ignore-warning/rspack.config.js
  packages/rspack/etc/core.api.md
  packages/rspack/src/Compilation.ts
  packages/rspack/src/config/normalization.ts
  packages/rspack/src/config/types.ts
  packages/rspack/src/config/zod.ts
  packages/rspack/src/lib/WebpackError.ts
Labels: team, release: feature

#10809 fix: should not panic in esm specifier dependency when resolve failed
  crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
  packages/rspack-test-tools/tests/configCases/mangle-exports/issue-10565/errors.js
  packages/rspack-test-tools/tests/configCases/mangle-exports/issue-10565/index.js
  packages/rspack-test-tools/tests/configCases/mangle-exports/issue-10565/rspack.config.js
Labels: team, release: bug fix

#10755 perf: pre-allocate codegen buffer
  crates/rspack_javascript_compiler/src/compiler/minify.rs
  crates/rspack_javascript_compiler/src/compiler/stringify.rs
  crates/rspack_javascript_compiler/src/compiler/transform.rs
Labels: team, release: performance

#10820 perf: parallel drop AST of concated module infos
  crates/rspack_core/src/concatenated_module.rs
  crates/rspack_plugin_javascript/src/plugin/mod.rs
Labels: team, release: performance

#10831 feat(tracing): add tracing bench preset for benchmark
  crates/rspack_binding_api/src/lib.rs
  crates/rspack_core/src/compiler/compilation.rs
  crates/rspack_core/src/compiler/mod.rs
  crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
  crates/rspack_plugin_split_chunks/src/plugin/mod.rs
  crates/rspack_tracing/src/stdout.rs
  crates/rspack_util/src/lib.rs
  crates/rspack_util/src/tracing_preset.rs
  packages/rspack-cli/src/utils/profile.ts
Labels: team, release: feature

#10829 fix: skip non-resource link tags in SRI plugin
  crates/rspack_plugin_sri/src/html.rs
  packages/rspack-test-tools/tests/configCases/sri/link-tags/index.js
  packages/rspack-test-tools/tests/configCases/sri/link-tags/rspack.config.js
  packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
Labels: team, release: bug fix

#10830 docs: correct hook usage in HtmlRspackPlugin documentation
  website/docs/en/plugins/rspack/html-rspack-plugin.mdx
  website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Labels: team, release: document
